########
# Please copy it as build.properties (in the same folder as this file), 
# and change the properties as needed

# Properties for specify a local distribution directory

# jdk home
#jdk.home=/usr/local/mac/jdk1.8.0_271/
jdk.home=/usr/local/mac/jdk-15.0.1.jdk/

# app
app.name=VERDI
app.version=2.1
  
# basic settings - use '/' as a separator

user.home=/home/tahoward
install.dir=verdi_install

