/* Generated By:JJTree: Do not edit this line. ASTAbs.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.DoubleFunction;
import anl.verdi.util.FormulaArray;


public class ASTAbs extends SimpleNode {

	private static class AbsFunction implements DoubleFunction {
		
		public double apply(double val) {
			return Math.abs(val);
		}
	}

	public ASTAbs(int id) {
    super(id);
  }

  public ASTAbs(Parser p, int id) {
    super(p, id);
  }


	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return jjtGetChild(0).evaluate(frame).foreach(new AbsFunction());
	}
}
