/* Generated By:JJTree: Do not edit this line. ASTCosd.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.DoubleFunction;
import anl.verdi.util.FormulaArray;

public class ASTCosd extends SimpleNode {

	static class Cosd implements DoubleFunction {
		public double apply(double val) {
			return Math.cos(Math.toRadians(val));
		}
	}

  public ASTCosd(int id) {
    super(id);
  }

  public ASTCosd(Parser p, int id) {
    super(p, id);
  }

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return jjtGetChild(0).evaluate(frame).foreach(new Cosd());
	}
}
