/* Generated By:JJTree: Do not edit this line. ASTE.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.FormulaArray;

public class ASTE extends SimpleNode {

	private static FormulaArray E_ARRAY = new FormulaArray(Math.E);

  public ASTE(int id) {
    super(id);
  }

  public ASTE(Parser p, int id) {
    super(p, id);
  }


	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return E_ARRAY;
	}


}
