/* Generated By:JJTree: Do not edit this line. ASTExp.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.DoubleFunction;
import anl.verdi.util.FormulaArray;

public class ASTExp extends SimpleNode {

	static class Exp implements DoubleFunction {
		public double apply(double val) {
			return Math.exp(val);
		}
	}

	public ASTExp(int id) {
		super(id);
	}

	public ASTExp(Parser p, int id) {
		super(p, id);
	}

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return jjtGetChild(0).evaluate(frame).foreach(new Exp());
	}
}
