/* Generated By:JJTree: Do not edit this line. ASTLog.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.DoubleFunction;
import anl.verdi.util.FormulaArray;

public class ASTLog extends SimpleNode {

 static class Log implements DoubleFunction {
		public double apply(double val) {
			return Math.log10(val);
		}
	}

	public ASTLog(int id) {
		super(id);
	}

	public ASTLog(Parser p, int id) {
		super(p, id);
	}

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return jjtGetChild(0).evaluate(frame).foreach(new Log());
	}
}
