/* Generated By:JJTree: Do not edit this line. ASTLn.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.DoubleFunction;
import anl.verdi.util.FormulaArray;

public class ASTLn extends SimpleNode {

  static class Ln implements DoubleFunction {
		public double apply(double val) {
			return Math.log(val);
		}
	}

	public ASTLn(int id) {
		super(id);
	}

	public ASTLn(Parser p, int id) {
		super(p, id);
	}

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return jjtGetChild(0).evaluate(frame).foreach(new Ln());
	}
}
