/* Generated By:JJTree: Do not edit this line. ASTMaxz.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.FormulaArray;

public class ASTMaxz extends AggregateFuncNode {
  public ASTMaxz(int id) {
    super(id);
  }

  public ASTMaxz(Parser p, int id) {
    super(p, id);
  }

	protected int getIndex(Frame frame) {
		return frame.getLayer();
	}

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		int max = max(frame.getLayer(), frame);
		return new FormulaArray(max + frame.getLayerOffset());
	}

}
