/* Generated By:JJTree: Do not edit this line. ASTMint.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.FormulaArray;

public class ASTMint extends AggregateFuncNode {

	public ASTMint(int id) {
		super(id);
	}

	public ASTMint(Parser p, int id) {
		super(p, id);
	}

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		int mint = min(frame.getTimeStep(), frame);
		return new FormulaArray(mint + frame.getTimeStepOffset());
	}
}
