/* Generated By:JJTree: Do not edit this line. ASTMiny.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.FormulaArray;

public class ASTMiny extends AggregateFuncNode {
  public ASTMiny(int id) {
    super(id);
  }

  public ASTMiny(Parser p, int id) {
    super(p, id);
  }

	protected int getIndex(Frame frame) {
		return frame.getY();
	}

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		int min = min(frame.getY(), frame);
		return new FormulaArray(min + frame.getYOffset());
	}

}
