/* Generated By:JJTree: Do not edit this line. ASTMaxy.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.FormulaArray;

public class ASTMaxy extends AggregateFuncNode {
  public ASTMaxy(int id) {
    super(id);
  }

  public ASTMaxy(Parser p, int id) {
    super(p, id);
  }

	protected int getIndex(Frame frame) {
		return frame.getY();
	}

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		int max = max(frame.getY(), frame);
		return new FormulaArray(max + frame.getYOffset());
	}

}
