/* Generated By:JJTree: Do not edit this line. ASTNCols.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.FormulaArray;

public class ASTNCols extends SimpleNode {

	public FormulaArray cols;

  public ASTNCols(int id) {
    super(id);
  }

  public ASTNCols(Parser p, int id) {
    super(p, id);
  }


	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return cols;
	}

	/**
	 * Performs any node level preprocessing prior
	 * to any evaluation. This should only be called
	 * once on the tree. 
	 *
	 * @param frame
	 */
	@Override
	public void preprocess(Frame frame) throws IllegalFormulaException {
		 cols = new FormulaArray(frame.getColumnCount());
	}
}
