/* Generated By:JJTree: Do not edit this line. ASTNeg.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.DoubleFunction;
import anl.verdi.util.FormulaArray;

public class ASTNeg extends SimpleNode {

	static class Neg implements DoubleFunction {
		public double apply(double val) {
			return  -val;
		}
	}

	public ASTNeg(int id) {
		super(id);
	}

	public ASTNeg(Parser p, int id) {
		super(p, id);
	}

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return jjtGetChild(0).evaluate(frame).foreach(new Neg());
	}
}
