/* Generated By:JJTree: Do not edit this line. ASTNRows.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.FormulaArray;

public class ASTNRows extends SimpleNode {

	private FormulaArray rows;

  public ASTNRows(int id) {
    super(id);
  }

  public ASTNRows(Parser p, int id) {
    super(p, id);
  }

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return rows;
	}

	/**
	 * Performs any node level preprocessing prior
	 * to any evaluation. This should only be called
	 * once on the tree. 
	 *
	 * @param frame
	 */
	@Override
	public void preprocess(Frame frame) throws IllegalFormulaException {
		 rows = new FormulaArray(frame.getRowCount());
	}

}
