/* Generated By:JJTree: Do not edit this line. ASTNLayers.java */
// 2015 changed "level" to "layer"

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.FormulaArray;

public class ASTNLayers extends SimpleNode {

	public FormulaArray layers;

  public ASTNLayers(int id) {
    super(id);
  }

  public ASTNLayers(Parser p, int id) {
    super(p, id);
  }

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return layers;
	}

	/**
	 * Performs any node  preprocessing prior
	 * to any evaluation. This should only be called
	 * once on the tree. 
	 *
	 * @param frame
	 */
	@Override
	public void preprocess(Frame frame) throws IllegalFormulaException {
		 layers = new FormulaArray(frame.getLayerCount());
	}

}
