/* Generated By:JJTree: Do not edit this line. ASTPI.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.FormulaArray;

public class ASTPI extends SimpleNode {

	private static final FormulaArray PI_ARRAY = new FormulaArray(Math.PI);

  public ASTPI(int id) {
    super(id);
  }

  public ASTPI(Parser p, int id) {
    super(p, id);
  }

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return PI_ARRAY;
	}
}
