/* Generated By:JJTree: Do not edit this line. ASTSin.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.DoubleFunction;
import anl.verdi.util.FormulaArray;

public class ASTSin extends SimpleNode {

	static class Sin implements DoubleFunction {
		public double apply(double val) {
			return Math.sin(val);
		}
	}

  public ASTSin(int id) {
    super(id);
  }

  public ASTSin(Parser p, int id) {
    super(p, id);
  }

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return jjtGetChild(0).evaluate(frame).foreach(new Sin());
	}

}
