/* Generated By:JJTree: Do not edit this line. ASTSqrt.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.DoubleFunction;
import anl.verdi.util.FormulaArray;

public class ASTSqrt extends SimpleNode {
	
  static class Sqrt implements DoubleFunction {
		public double apply(double val) {
			return Math.sqrt(val);
		}
	}

	public ASTSqrt(int id) {
		super(id);
	}

	public ASTSqrt(Parser p, int id) {
		super(p, id);
	}

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return jjtGetChild(0).evaluate(frame).foreach(new Sqrt());
	}
}
