/* Generated By:JJTree: Do not edit this line. ASTTan.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.DoubleFunction;
import anl.verdi.util.FormulaArray;

public class ASTTan extends SimpleNode {

 static class Tan implements DoubleFunction {
		public double apply(double val) {
			return Math.tan(val);
		}
	}

  public ASTTan(int id) {
    super(id);
  }

  public ASTTan(Parser p, int id) {
    super(p, id);
  }

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return jjtGetChild(0).evaluate(frame).foreach(new Tan());
	}
}
