/* Generated By:JJTree: Do not edit this line. ASTTand.java */

package anl.verdi.parser;

import anl.verdi.formula.IllegalFormulaException;
import anl.verdi.util.DoubleFunction;
import anl.verdi.util.FormulaArray;

public class ASTTand extends SimpleNode {

 static class Tand implements DoubleFunction {
		public double apply(double val) {
			return Math.tan(Math.toRadians(val));
		}
	}

  public ASTTand(int id) {
    super(id);
  }

  public ASTTand(Parser p, int id) {
    super(p, id);
  }

	/**
	 * Evaluates this Node.
	 *
	 * @param frame
	 * @return the result of the evaluation.
	 */
	@Override
	public FormulaArray evaluate(Frame frame) throws IllegalFormulaException {
		return jjtGetChild(0).evaluate(frame).foreach(new Tand());
	}

}
