/* Generated By:JJTree: Do not edit this line. .\ParserTreeConstants.java */

package anl.verdi.parser;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTOR = 2;
  public int JJTAND = 3;
  public int JJTEQEQUAL = 4;
  public int JJTNOTEQUAL = 5;
  public int JJTLESSTHAN = 6;
  public int JJTGREATERTHAN = 7;
  public int JJTLESSEQ = 8;
  public int JJTGREATEREQ = 9;
  public int JJTADD = 10;
  public int JJTSUBTRACT = 11;
  public int JJTMUL = 12;
  public int JJTDIV = 13;
  public int JJTMOD = 14;
  public int JJTPOW = 15;
  public int JJTE = 16;
  public int JJTPI = 17;
  public int JJTNROWS = 18;
  public int JJTNCOLS = 19;
  public int JJTNLEVELS = 20;
  public int JJTVAR = 21;
  public int JJTABS = 22;
  public int JJTSQRT = 23;
  public int JJTSQR = 24;
  public int JJTLOG = 25;
  public int JJTEXP = 26;
  public int JJTLN = 27;
  public int JJTSIN = 28;
  public int JJTCOS = 29;
  public int JJTTAN = 30;
  public int JJTSIND = 31;
  public int JJTCOSD = 32;
  public int JJTTAND = 33;
  public int JJTMEAN = 34;
  public int JJTSUM = 35;
  public int JJTMIN = 36;
  public int JJTMAX = 37;
  public int JJTMINT = 38;
  public int JJTMAXT = 39;
  public int JJTMAXX = 40;
  public int JJTMINX = 41;
  public int JJTMINY = 42;
  public int JJTMAXY = 43;
  public int JJTMINZ = 44;
  public int JJTMAXZ = 45;
  public int JJTNEG = 46;
  public int JJTNUMBER = 47;


  public String[] jjtNodeName = {
    "start",
    "void",
    "Or",
    "And",
    "EqEqual",
    "NotEqual",
    "LessThan",
    "GreaterThan",
    "LessEq",
    "GreaterEq",
    "Add",
    "Subtract",
    "Mul",
    "Div",
    "Mod",
    "Pow",
    "E",
    "PI",
    "NRows",
    "NCols",
    "NLevels",
    "Var",
    "Abs",
    "Sqrt",
    "Sqr",
    "Log",
    "Exp",
    "Ln",
    "Sin",
    "Cos",
    "Tan",
    "Sind",
    "Cosd",
    "Tand",
    "Mean",
    "Sum",
    "Min",
    "Max",
    "Mint",
    "Maxt",
    "Maxx",
    "Minx",
    "Miny",
    "Maxy",
    "Minz",
    "Maxz",
    "Neg",
    "Number",
  };
}
