VERDI: anl.verdi.gis.OverlayObject Class Reference
anl.verdi.gis.OverlayObject Class Reference
Public Member Functions
OverlayObject (Variable variable, Symbol sym, int stroke, int shape)
Variable getVariable ()
void setVariable (Variable variable)
Symbol getSymbol ()
void setSymbol (Symbol symbol)
int getStrokeSize ()
void setStrokeSize (int size)
int getShapeSize ()
void setShapeSize (int size)
boolean equals (Object other)
String toString ()
Detailed Description
Definition at line 7 of file OverlayObject.java.
Constructor & Destructor Documentation
anl.verdi.gis.OverlayObject.OverlayObject (Variable variable, Symbol sym, int stroke, int shape)
Definition at line 13 of file OverlayObject.java.
Referenced by anl.verdi.gis.OverlayObject.equals().
Member Function Documentation
boolean anl.verdi.gis.OverlayObject.equals (Object other)
Definition at line 53 of file OverlayObject.java.
References anl.verdi.gis.OverlayObject.getVariable(), and anl.verdi.gis.OverlayObject.OverlayObject().
int anl.verdi.gis.OverlayObject.getShapeSize ()
Definition at line 44 of file OverlayObject.java.
int anl.verdi.gis.OverlayObject.getStrokeSize ()
Definition at line 36 of file OverlayObject.java.
Symbol anl.verdi.gis.OverlayObject.getSymbol ()
Definition at line 28 of file OverlayObject.java.
Variable anl.verdi.gis.OverlayObject.getVariable ()
Definition at line 20 of file OverlayObject.java.
Referenced by anl.verdi.gis.OverlayObject.equals().
void anl.verdi.gis.OverlayObject.setShapeSize (int size)
Definition at line 48 of file OverlayObject.java.
void anl.verdi.gis.OverlayObject.setStrokeSize (int size)
Definition at line 40 of file OverlayObject.java.
void anl.verdi.gis.OverlayObject.setSymbol (Symbol symbol)
Definition at line 32 of file OverlayObject.java.
void anl.verdi.gis.OverlayObject.setVariable (Variable variable)
Definition at line 24 of file OverlayObject.java.
String anl.verdi.gis.OverlayObject.toString ()
Definition at line 69 of file OverlayObject.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/gis/OverlayObject.java