VERDI: anl.verdi.loaders.NetcdfBoxer Class Reference
anl.verdi.loaders.NetcdfBoxer Class Reference
Public Member Functions
NetcdfBoxer (GridDatatype grid)
Projection getProjection ()
Point2D axisPointToLatLonPoint (int x, int y)
Point2D latLonToAxisPoint (double lat, double lon)
Point2D CRSPointToAxis (double x, double y)
ReferencedEnvelope createBoundingBox (double xMin, double xMax, double yMin, double yMax, int netcdfConv)
CoordinateReferenceSystem getCRS ()
Detailed Description
Bounding boxer that uses netcdf to create the bounding box.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 41 of file NetcdfBoxer.java.
Constructor & Destructor Documentation
anl.verdi.loaders.NetcdfBoxer.NetcdfBoxer (GridDatatype grid)
Definition at line 54 of file NetcdfBoxer.java.
Member Function Documentation
Point2D anl.verdi.loaders.NetcdfBoxer.axisPointToLatLonPoint (int x, int y)
Converts the grid cell coordinate to a lat / lon coordinate.
Parameters
x the x value
y the y value
Returns
the lat / lon coordinate.
Implements anl.verdi.data.BoundingBoxer.
Definition at line 79 of file NetcdfBoxer.java.
References anl.verdi.loaders.NetcdfBoxer.getProjection().
ReferencedEnvelope anl.verdi.loaders.NetcdfBoxer.createBoundingBox (double xMin, double xMax, double yMin, double yMax, int netcdfConv)
Creates a bounding box from the specified ranges. The xRange and yRange are specified in terms of x / y cell coordinates.
Parameters
xMin
xMax
yMin
yMax
Returns
the created bounding box.
Implements anl.verdi.data.BoundingBoxer.
Definition at line 178 of file NetcdfBoxer.java.
References anl.verdi.loaders.NetcdfBoxer.getProjection(), and anl.verdi.core.VerdiConstants.NETCDF_CONV_ARW_WRF.
Point2D anl.verdi.loaders.NetcdfBoxer.CRSPointToAxis (double x, double y)
Converts the CRS coordinate to a grid Cell coordinate
Parameters
x
y
Returns
Implements anl.verdi.data.BoundingBoxer.
Definition at line 137 of file NetcdfBoxer.java.
CoordinateReferenceSystem anl.verdi.loaders.NetcdfBoxer.getCRS ()
Implements anl.verdi.data.BoundingBoxer.
Definition at line 315 of file NetcdfBoxer.java.
Projection anl.verdi.loaders.NetcdfBoxer.getProjection ()
Gets the Projection associated with this BoundingBoxer.
Returns
the Projection associated with this BoundingBoxer.
Implements anl.verdi.data.BoundingBoxer.
Definition at line 65 of file NetcdfBoxer.java.
Referenced by anl.verdi.loaders.NetcdfBoxer.axisPointToLatLonPoint(), anl.verdi.loaders.NetcdfBoxer.createBoundingBox(), and anl.verdi.loaders.NetcdfBoxer.latLonToAxisPoint().
Point2D anl.verdi.loaders.NetcdfBoxer.latLonToAxisPoint (double lat, double lon)
Parameters
lat latitude
lon longitude
Returns
the location on the x and y axis if the latLon is with the grid, otherwise (-1, -1).
Implements anl.verdi.data.BoundingBoxer.
Definition at line 106 of file NetcdfBoxer.java.
References anl.verdi.loaders.NetcdfBoxer.getProjection().
The documentation for this class was generated from the following file:
verdi_data_loaders/src/anl/verdi/loaders/NetcdfBoxer.java