VERDI: anl.verdi.parser.Parser Class Reference
anl.verdi.parser.Parser Class Reference
Public Member Functions
final ASTstart start () throws ParseException
final void ConditionalOrExpression () throws ParseException
final void ConditionalAndExpression () throws ParseException
final void EqualityExpression () throws ParseException
final void RelationalExpression () throws ParseException
final void AdditiveExpression () throws ParseException
final void MultiplicativeExpression () throws ParseException
final void powExpression () throws ParseException
final void UnaryExpression () throws ParseException
final void Var () throws ParseException
final void Func () throws ParseException
final void Number () throws ParseException
Parser (java.io.InputStream stream)
Parser (java.io.InputStream stream, String encoding)
void ReInit (java.io.InputStream stream)
void ReInit (java.io.InputStream stream, String encoding)
Parser (java.io.Reader stream)
void ReInit (java.io.Reader stream)
Parser (ParserTokenManager tm)
void ReInit (ParserTokenManager tm)
final Token getNextToken ()
final Token getToken (int index)
ParseException generateParseException ()
final void enable_tracing ()
final void disable_tracing ()
Static Public Member Functions
static void main (String args[])
Public Attributes
ParserTokenManager token_source
Token token
Public Attributes inherited from anl.verdi.parser.ParserTreeConstants
int JJTSTART = 0
int JJTVOID = 1
int JJTOR = 2
int JJTAND = 3
int JJTEQEQUAL = 4
int JJTNOTEQUAL = 5
int JJTLESSTHAN = 6
int JJTGREATERTHAN = 7
int JJTLESSEQ = 8
int JJTGREATEREQ = 9
int JJTADD = 10
int JJTSUBTRACT = 11
int JJTMUL = 12
int JJTDIV = 13
int JJTMOD = 14
int JJTPOW = 15
int JJTE = 16
int JJTPI = 17
int JJTNROWS = 18
int JJTNCOLS = 19
int JJTNLEVELS = 20
int JJTVAR = 21
int JJTABS = 22
int JJTSQRT = 23
int JJTSQR = 24
int JJTLOG = 25
int JJTEXP = 26
int JJTLN = 27
int JJTSIN = 28
int JJTCOS = 29
int JJTTAN = 30
int JJTSIND = 31
int JJTCOSD = 32
int JJTTAND = 33
int JJTMEAN = 34
int JJTSUM = 35
int JJTMIN = 36
int JJTMAX = 37
int JJTMINT = 38
int JJTMAXT = 39
int JJTMAXX = 40
int JJTMINX = 41
int JJTMINY = 42
int JJTMAXY = 43
int JJTMINZ = 44
int JJTMAXZ = 45
int JJTNEG = 46
int JJTNUMBER = 47
String[] jjtNodeName
Public Attributes inherited from anl.verdi.parser.ParserConstants
int EOF = 0
int INTEGER_LITERAL = 7
int FLOAT = 8
int EXPONENT = 9
int DECIMAL_LITERAL = 10
int GREATER = 11
int LESS = 12
int EQEQUAL = 13
int EQLESS = 14
int EQGREATER = 15
int NOT_EQUAL = 16
int OR = 17
int AND = 18
int PLUS = 19
int MINUS = 20
int TIMES = 21
int DIV = 22
int MOD = 23
int POW = 24
int ABS = 25
int SQRT = 26
int SQR = 27
int LOG = 28
int EXP = 29
int LN = 30
int SIN = 31
int COS = 32
int TAN = 33
int SIND = 34
int COSD = 35
int TAND = 36
int MEAN = 37
int SUM = 38
int MINT = 39
int MAXT = 40
int MINX = 41
int MAXX = 42
int MINY = 43
int MAXY = 44
int MINZ = 45
int MAXZ = 46
int MIN = 47
int MAX = 48
int E = 49
int PI = 50
int NROWS = 51
int NCOLS = 52
int NLAYERS = 53
int IDENTIFIER = 57
int LETTER = 58
int DIGIT = 59
int DEFAULT = 0
String[] tokenImage
Protected Attributes
JJTParserState jjtree = new JJTParserState()
Detailed Description
Definition at line 6 of file Parser.java.
Constructor & Destructor Documentation
anl.verdi.parser.Parser.Parser (java.io.InputStream stream)
Definition at line 1165 of file Parser.java.
Referenced by anl.verdi.parser.Parser.main().
anl.verdi.parser.Parser.Parser (java.io.InputStream stream, String encoding)
Definition at line 1168 of file Parser.java.
References anl.verdi.parser.Parser.token, and anl.verdi.parser.Parser.token_source.
anl.verdi.parser.Parser.Parser (java.io.Reader stream)
Definition at line 1190 of file Parser.java.
References anl.verdi.parser.Parser.token, and anl.verdi.parser.Parser.token_source.
anl.verdi.parser.Parser.Parser (ParserTokenManager tm)
Definition at line 1209 of file Parser.java.
References anl.verdi.parser.Parser.token, and anl.verdi.parser.Parser.token_source.
Member Function Documentation
final void anl.verdi.parser.Parser.AdditiveExpression () throws ParseException
Definition at line 352 of file Parser.java.
References anl.verdi.parser.ParserTreeConstants.JJTADD, anl.verdi.parser.ParserTreeConstants.JJTSUBTRACT, anl.verdi.parser.ParserConstants.MINUS, anl.verdi.parser.Parser.MultiplicativeExpression(), and anl.verdi.parser.ParserConstants.PLUS.
Referenced by anl.verdi.parser.Parser.RelationalExpression().
final void anl.verdi.parser.Parser.ConditionalAndExpression () throws ParseException
Definition at line 104 of file Parser.java.
References anl.verdi.parser.ParserConstants.AND, anl.verdi.parser.Parser.EqualityExpression(), and anl.verdi.parser.ParserTreeConstants.JJTAND.
Referenced by anl.verdi.parser.Parser.ConditionalOrExpression().
final void anl.verdi.parser.Parser.ConditionalOrExpression () throws ParseException
Definition at line 64 of file Parser.java.
References anl.verdi.parser.Parser.ConditionalAndExpression(), anl.verdi.parser.ParserTreeConstants.JJTOR, and anl.verdi.parser.ParserConstants.OR.
Referenced by anl.verdi.parser.Parser.Func(), anl.verdi.parser.Parser.start(), and anl.verdi.parser.Parser.UnaryExpression().
final void anl.verdi.parser.Parser.disable_tracing ()
Definition at line 1307 of file Parser.java.
final void anl.verdi.parser.Parser.enable_tracing ()
Definition at line 1304 of file Parser.java.
final void anl.verdi.parser.Parser.EqualityExpression () throws ParseException
Definition at line 144 of file Parser.java.
References anl.verdi.parser.ParserConstants.EQEQUAL, anl.verdi.parser.ParserTreeConstants.JJTEQEQUAL, anl.verdi.parser.ParserTreeConstants.JJTNOTEQUAL, anl.verdi.parser.ParserConstants.NOT_EQUAL, and anl.verdi.parser.Parser.RelationalExpression().
Referenced by anl.verdi.parser.Parser.ConditionalAndExpression().
final void anl.verdi.parser.Parser.Func () throws ParseException
Definition at line 710 of file Parser.java.
References anl.verdi.parser.ParserConstants.ABS, anl.verdi.parser.Parser.ConditionalOrExpression(), anl.verdi.parser.ParserConstants.COS, anl.verdi.parser.ParserConstants.COSD, anl.verdi.parser.ParserConstants.EXP, anl.verdi.parser.ParserTreeConstants.JJTABS, anl.verdi.parser.ParserTreeConstants.JJTCOS, anl.verdi.parser.ParserTreeConstants.JJTCOSD, anl.verdi.parser.ParserTreeConstants.JJTEXP, anl.verdi.parser.ParserTreeConstants.JJTLN, anl.verdi.parser.ParserTreeConstants.JJTLOG, anl.verdi.parser.ParserTreeConstants.JJTMAX, anl.verdi.parser.ParserTreeConstants.JJTMAXT, anl.verdi.parser.ParserTreeConstants.JJTMAXX, anl.verdi.parser.ParserTreeConstants.JJTMAXY, anl.verdi.parser.ParserTreeConstants.JJTMAXZ, anl.verdi.parser.ParserTreeConstants.JJTMEAN, anl.verdi.parser.ParserTreeConstants.JJTMIN, anl.verdi.parser.ParserTreeConstants.JJTMINT, anl.verdi.parser.ParserTreeConstants.JJTMINX, anl.verdi.parser.ParserTreeConstants.JJTMINY, anl.verdi.parser.ParserTreeConstants.JJTMINZ, anl.verdi.parser.ParserTreeConstants.JJTSIN, anl.verdi.parser.ParserTreeConstants.JJTSIND, anl.verdi.parser.ParserTreeConstants.JJTSQR, anl.verdi.parser.ParserTreeConstants.JJTSQRT, anl.verdi.parser.ParserTreeConstants.JJTSUM, anl.verdi.parser.ParserTreeConstants.JJTTAN, anl.verdi.parser.ParserTreeConstants.JJTTAND, anl.verdi.parser.ParserConstants.LN, anl.verdi.parser.ParserConstants.LOG, anl.verdi.parser.ParserConstants.MAX, anl.verdi.parser.ParserConstants.MAXT, anl.verdi.parser.ParserConstants.MAXX, anl.verdi.parser.ParserConstants.MAXY, anl.verdi.parser.ParserConstants.MAXZ, anl.verdi.parser.ParserConstants.MEAN, anl.verdi.parser.ParserConstants.MIN, anl.verdi.parser.ParserConstants.MINT, anl.verdi.parser.ParserConstants.MINX, anl.verdi.parser.ParserConstants.MINY, anl.verdi.parser.ParserConstants.MINZ, anl.verdi.parser.ParserConstants.SIN, anl.verdi.parser.ParserConstants.SIND, anl.verdi.parser.ParserConstants.SQR, anl.verdi.parser.ParserConstants.SQRT, anl.verdi.parser.ParserConstants.SUM, anl.verdi.parser.ParserConstants.TAN, and anl.verdi.parser.ParserConstants.TAND.
Referenced by anl.verdi.parser.Parser.UnaryExpression().
ParseException anl.verdi.parser.Parser.generateParseException ()
Definition at line 1268 of file Parser.java.
References anl.verdi.parser.Parser.token, and anl.verdi.parser.ParserConstants.tokenImage.
final Token anl.verdi.parser.Parser.getNextToken ()
Definition at line 1240 of file Parser.java.
References anl.verdi.parser.Token.next, and anl.verdi.parser.Parser.token.
final Token anl.verdi.parser.Parser.getToken (int index)
Definition at line 1248 of file Parser.java.
References anl.verdi.parser.Token.next, and anl.verdi.parser.Parser.token.
static void anl.verdi.parser.Parser.main (String args[]) static
Definition at line 9 of file Parser.java.
References anl.verdi.parser.Parser.Parser().
final void anl.verdi.parser.Parser.MultiplicativeExpression () throws ParseException
Definition at line 428 of file Parser.java.
References anl.verdi.parser.ParserConstants.DIV, anl.verdi.parser.ParserTreeConstants.JJTDIV, anl.verdi.parser.ParserTreeConstants.JJTMOD, anl.verdi.parser.ParserTreeConstants.JJTMUL, anl.verdi.parser.ParserConstants.MOD, anl.verdi.parser.Parser.powExpression(), and anl.verdi.parser.ParserConstants.TIMES.
Referenced by anl.verdi.parser.Parser.AdditiveExpression().
final void anl.verdi.parser.Parser.Number () throws ParseException
Definition at line 1079 of file Parser.java.
References anl.verdi.parser.ParserConstants.FLOAT, anl.verdi.parser.ParserConstants.INTEGER_LITERAL, anl.verdi.parser.ParserTreeConstants.JJTNEG, anl.verdi.parser.ParserTreeConstants.JJTNUMBER, and anl.verdi.parser.ParserConstants.MINUS.
Referenced by anl.verdi.parser.Parser.UnaryExpression().
final void anl.verdi.parser.Parser.powExpression () throws ParseException
Definition at line 532 of file Parser.java.
References anl.verdi.parser.ParserTreeConstants.JJTPOW, anl.verdi.parser.ParserConstants.POW, and anl.verdi.parser.Parser.UnaryExpression().
Referenced by anl.verdi.parser.Parser.MultiplicativeExpression().
void anl.verdi.parser.Parser.ReInit (java.io.InputStream stream)
Definition at line 1177 of file Parser.java.
void anl.verdi.parser.Parser.ReInit (java.io.InputStream stream, String encoding)
Definition at line 1180 of file Parser.java.
References anl.verdi.parser.Parser.token.
void anl.verdi.parser.Parser.ReInit (java.io.Reader stream)
Definition at line 1199 of file Parser.java.
References anl.verdi.parser.Parser.token.
void anl.verdi.parser.Parser.ReInit (ParserTokenManager tm)
Definition at line 1217 of file Parser.java.
References anl.verdi.parser.Parser.token, and anl.verdi.parser.Parser.token_source.
final void anl.verdi.parser.Parser.RelationalExpression () throws ParseException
Definition at line 220 of file Parser.java.
References anl.verdi.parser.Parser.AdditiveExpression(), anl.verdi.parser.ParserConstants.EQGREATER, anl.verdi.parser.ParserConstants.EQLESS, anl.verdi.parser.ParserConstants.GREATER, anl.verdi.parser.ParserTreeConstants.JJTGREATEREQ, anl.verdi.parser.ParserTreeConstants.JJTGREATERTHAN, anl.verdi.parser.ParserTreeConstants.JJTLESSEQ, anl.verdi.parser.ParserTreeConstants.JJTLESSTHAN, and anl.verdi.parser.ParserConstants.LESS.
Referenced by anl.verdi.parser.Parser.EqualityExpression().
final ASTstart anl.verdi.parser.Parser.start () throws ParseException
Definition at line 31 of file Parser.java.
References anl.verdi.parser.Parser.ConditionalOrExpression(), and anl.verdi.parser.ParserTreeConstants.JJTSTART.
final void anl.verdi.parser.Parser.UnaryExpression () throws ParseException
Definition at line 572 of file Parser.java.
References anl.verdi.parser.ParserConstants.ABS, anl.verdi.parser.Parser.ConditionalOrExpression(), anl.verdi.parser.ParserConstants.COS, anl.verdi.parser.ParserConstants.COSD, anl.verdi.parser.ParserConstants.E, anl.verdi.parser.ParserConstants.EXP, anl.verdi.parser.ParserConstants.FLOAT, anl.verdi.parser.Parser.Func(), anl.verdi.parser.ParserConstants.IDENTIFIER, anl.verdi.parser.ParserConstants.INTEGER_LITERAL, anl.verdi.parser.ParserConstants.LN, anl.verdi.parser.ParserConstants.LOG, anl.verdi.parser.ParserConstants.MAX, anl.verdi.parser.ParserConstants.MAXT, anl.verdi.parser.ParserConstants.MAXX, anl.verdi.parser.ParserConstants.MAXY, anl.verdi.parser.ParserConstants.MAXZ, anl.verdi.parser.ParserConstants.MEAN, anl.verdi.parser.ParserConstants.MIN, anl.verdi.parser.ParserConstants.MINT, anl.verdi.parser.ParserConstants.MINUS, anl.verdi.parser.ParserConstants.MINX, anl.verdi.parser.ParserConstants.MINY, anl.verdi.parser.ParserConstants.MINZ, anl.verdi.parser.ParserConstants.NCOLS, anl.verdi.parser.ParserConstants.NLAYERS, anl.verdi.parser.ParserConstants.NROWS, anl.verdi.parser.Parser.Number(), anl.verdi.parser.ParserConstants.PI, anl.verdi.parser.ParserConstants.SIN, anl.verdi.parser.ParserConstants.SIND, anl.verdi.parser.ParserConstants.SQR, anl.verdi.parser.ParserConstants.SQRT, anl.verdi.parser.ParserConstants.SUM, anl.verdi.parser.ParserConstants.TAN, anl.verdi.parser.ParserConstants.TAND, and anl.verdi.parser.Parser.Var().
Referenced by anl.verdi.parser.Parser.powExpression().
final void anl.verdi.parser.Parser.Var () throws ParseException
Definition at line 625 of file Parser.java.
References anl.verdi.parser.ParserConstants.E, anl.verdi.parser.ParserConstants.IDENTIFIER, anl.verdi.parser.ParserTreeConstants.JJTE, anl.verdi.parser.ParserTreeConstants.JJTNCOLS, anl.verdi.parser.ParserTreeConstants.JJTNLEVELS, anl.verdi.parser.ParserTreeConstants.JJTNROWS, anl.verdi.parser.ParserTreeConstants.JJTPI, anl.verdi.parser.ParserTreeConstants.JJTVAR, anl.verdi.parser.ParserConstants.NCOLS, anl.verdi.parser.ParserConstants.NLAYERS, anl.verdi.parser.ParserConstants.NROWS, and anl.verdi.parser.ParserConstants.PI.
Referenced by anl.verdi.parser.Parser.UnaryExpression().
Member Data Documentation
JJTParserState anl.verdi.parser.Parser.jjtree = new JJTParserState() protected
Definition at line 8 of file Parser.java.
Token anl.verdi.parser.Parser.token
Definition at line 1148 of file Parser.java.
Referenced by anl.verdi.parser.Parser.generateParseException(), anl.verdi.parser.Parser.getNextToken(), anl.verdi.parser.Parser.getToken(), anl.verdi.parser.Parser.Parser(), and anl.verdi.parser.Parser.ReInit().
ParserTokenManager anl.verdi.parser.Parser.token_source
Definition at line 1146 of file Parser.java.
Referenced by anl.verdi.parser.Parser.Parser(), and anl.verdi.parser.Parser.ReInit().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/parser/Parser.java