VERDI: org.libtiff.jai.util.JaiI18N Class Reference
org.libtiff.jai.util.JaiI18N Class Reference
Static Public Member Functions
static String getString (String key)
Detailed Description
Definition at line 25 of file JaiI18N.java.
Member Function Documentation
static String org.libtiff.jai.util.JaiI18N.getString (String key) static
Definition at line 27 of file JaiI18N.java.
Referenced by org.libtiff.jai.codecimpl.XTIFFFaxDecoder.decode2D(), org.libtiff.jai.codecimpl.XTIFFImageDecoder.decodeAsRenderedImage(), org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor(), org.libtiff.jai.codecimpl.XTIFFFaxDecoder.decodeNextScanline(), org.libtiff.jai.codecimpl.XTIFFFaxDecoder.decodeT6(), org.libtiff.jai.codec.XTIFFDirectory.getNumDirectories(), org.libtiff.jai.codecimpl.XTIFFImage.getTile(), org.libtiff.jai.codecimpl.XTIFFLZWTileCodec.initializeDecoding(), org.libtiff.jai.codec.XTIFFDirectory.readHeader(), org.libtiff.jai.codecimpl.XTIFFImage.setupImageParameters(), org.libtiff.jai.codecimpl.XTIFFImage.setupSamplesAndColor(), and org.libtiff.jai.codec.XTIFFDirectory.XTIFFDirectory().
The documentation for this class was generated from the following file:
verdi_core/src/org/libtiff/jai/util/JaiI18N.java