VERDI: simphony.util.messages.MessageCenter Class Reference
simphony.util.messages.MessageCenter Class Reference
Public Member Functions
void info (Object info, Object...metaData)
void trace (Object info, Object...metaData)
void debug (Object info, Object...metaData)
void warn (Object info, Object...metaData)
void warn (Object info, Throwable error, Object...metaData)
void error (Object info, Throwable error, Object...metaData)
void fatal (Object info, Throwable error, Object...metaData)
void fireMessageEvent (Level level, Object info, Throwable throwable, Object...metaData)
Log4jMessageListener getLogListener ()
void setLogListener (Log4jMessageListener logListener)
Static Public Member Functions
static MessageCenter getMessageCenter (Class clazz)
static MessageCenter getMessageCenter (String name)
static MessageCenter getMessageCenter (String name, boolean addLogger)
static MessageCenter getMessageCenter (Class clazz, Map properties)
static void addMessageListener (MessageEventListener listener)
static void removeMessageListener (MessageEventListener listener)
static Collection
< MessageEventListener > getMessageListeners ()
Detailed Description
A class for handling all sorts of messages. This class receives messages of different levels through it's different methods and passes these messages on to it's listeners.
To retrieve an instance of this class use getMessageCenter(Class) or getMessageCenter(Class, Map).
Author
Jerry Vos
See Also
getMessageCenter(Class)
getMessageCenter(Class, Map)
addMessageListener(MessageEventListener)
removeMessageListener(MessageEventListener)
Definition at line 24 of file MessageCenter.java.
Member Function Documentation
static void simphony.util.messages.MessageCenter.addMessageListener (MessageEventListener listener) static
Definition at line 151 of file MessageCenter.java.
void simphony.util.messages.MessageCenter.debug (Object info, Object... metaData)
Definition at line 117 of file MessageCenter.java.
References simphony.util.messages.MessageCenter.fireMessageEvent().
void simphony.util.messages.MessageCenter.error (Object info, Throwable error, Object... metaData)
Definition at line 129 of file MessageCenter.java.
References simphony.util.messages.MessageCenter.fireMessageEvent().
void simphony.util.messages.MessageCenter.fatal (Object info, Throwable error, Object... metaData)
Definition at line 133 of file MessageCenter.java.
References simphony.util.messages.MessageCenter.fireMessageEvent().
void simphony.util.messages.MessageCenter.fireMessageEvent (Level level, Object info, Throwable throwable, Object... metaData)
Definition at line 137 of file MessageCenter.java.
Referenced by simphony.util.messages.MessageCenter.debug(), simphony.util.messages.MessageCenter.error(), simphony.util.messages.MessageCenter.fatal(), simphony.util.messages.MessageCenter.info(), simphony.util.messages.MessageCenter.trace(), and simphony.util.messages.MessageCenter.warn().
Log4jMessageListener simphony.util.messages.MessageCenter.getLogListener ()
Retrieves the default message listener that forwards messages to log4j.
Returns
the logging message listener
Definition at line 172 of file MessageCenter.java.
static MessageCenter simphony.util.messages.MessageCenter.getMessageCenter (Class clazz) static
Creates a MessageCenter for the specified class.
Parameters
clazz
Returns
the created MessageCenter
Definition at line 34 of file MessageCenter.java.
Referenced by simphony.util.messages.MessageCenter.getMessageCenter().
static MessageCenter simphony.util.messages.MessageCenter.getMessageCenter (String name) static
Definition at line 47 of file MessageCenter.java.
References simphony.util.messages.MessageCenter.getMessageCenter().
static MessageCenter simphony.util.messages.MessageCenter.getMessageCenter (String name, boolean addLogger) static
TODO: fix this javadoc Creates a MessageCenter.
Parameters
name an id for the message center
addLogger whether or not to add an automatic logger to the MessageCenter
Returns
a created MessageCenter
See Also
Log4jMessageListener
Definition at line 61 of file MessageCenter.java.
static MessageCenter simphony.util.messages.MessageCenter.getMessageCenter (Class clazz, Map properties) static
Currently this method is no different then getMessageCenter(Class) but it is here in case at some point MessageCenter's can be setup with a variety of properties.
Parameters
clazz the class this message center is working for
properties properties for creation of the MessageCenter (ignored for now)
Returns
a newly created MessageCenter
See Also
getMessageCenter(Class)
Definition at line 91 of file MessageCenter.java.
References simphony.util.messages.MessageCenter.getMessageCenter().
static Collection<MessageEventListener> simphony.util.messages.MessageCenter.getMessageListeners () static
Definition at line 163 of file MessageCenter.java.
void simphony.util.messages.MessageCenter.info (Object info, Object... metaData)
Definition at line 109 of file MessageCenter.java.
References simphony.util.messages.MessageCenter.fireMessageEvent().
static void simphony.util.messages.MessageCenter.removeMessageListener (MessageEventListener listener) static
Definition at line 157 of file MessageCenter.java.
void simphony.util.messages.MessageCenter.setLogListener (Log4jMessageListener logListener)
Sets the default message listener that forwards messages to log4j.
Parameters
logListener the logging message listener (can be null, in which case no default log listener is set)
Definition at line 183 of file MessageCenter.java.
void simphony.util.messages.MessageCenter.trace (Object info, Object... metaData)
Definition at line 113 of file MessageCenter.java.
References simphony.util.messages.MessageCenter.fireMessageEvent().
void simphony.util.messages.MessageCenter.warn (Object info, Object... metaData)
Definition at line 121 of file MessageCenter.java.
References simphony.util.messages.MessageCenter.fireMessageEvent().
void simphony.util.messages.MessageCenter.warn (Object info, Throwable error, Object... metaData)
Definition at line 125 of file MessageCenter.java.
References simphony.util.messages.MessageCenter.fireMessageEvent().
The documentation for this class was generated from the following file:
verdi_saf_core_runtime/src/simphony/util/messages/MessageCenter.java