VERDI: anl.verdi.loaders.SpreadsheetReader Class Reference
anl.verdi.loaders.SpreadsheetReader Class Reference
Public Member Functions
SpreadsheetReader (final String fileName)
Dataset getDataset ()
DataFrame getValues (final SpreadsheetDataset dataset, final List< AxisRange > ranges, final Variable variable)
Static Public Member Functions
static String validateHeaderAndGetTimezone (String header) throws Exception
Detailed Description
Definition at line 31 of file SpreadsheetReader.java.
Constructor & Destructor Documentation
anl.verdi.loaders.SpreadsheetReader.SpreadsheetReader (final String fileName)
Definition at line 87 of file SpreadsheetReader.java.
References anl.verdi.util.VUnits.createUnit(), and anl.verdi.loaders.SpreadsheetReader.validateHeaderAndGetTimezone().
Member Function Documentation
Dataset anl.verdi.loaders.SpreadsheetReader.getDataset ()
Definition at line 164 of file SpreadsheetReader.java.
DataFrame anl.verdi.loaders.SpreadsheetReader.getValues (final SpreadsheetDataset dataset, final List< AxisRange > ranges, final Variable variable)
Definition at line 171 of file SpreadsheetReader.java.
References anl.verdi.loaders.SpreadsheetDataset.getCoordAxes().
static String anl.verdi.loaders.SpreadsheetReader.validateHeaderAndGetTimezone (String header) throws Exception static
Definition at line 47 of file SpreadsheetReader.java.
Referenced by anl.verdi.loaders.SpreadsheetReader.SpreadsheetReader().
The documentation for this class was generated from the following file:
verdi_data_loaders/src/anl/verdi/loaders/SpreadsheetReader.java