VERDI: anl.verdi.loaders.Models3ObsDataset Class Reference
anl.verdi.loaders.Models3ObsDataset Class Reference
Public Member Functions
Models3ObsDataset (URL url, NetcdfDataset dataset)
void close () throws IOException
Axes< CoordAxis > getCoordAxes ()
int getIndexInURL ()
Variable getVariable (String name)
String getName ()
void setAlias (String alias)
List< String > getVariableNames ()
List< Variable > getVariables ()
boolean hasTimeAxis ()
boolean hasXAxis ()
boolean hasYAxis ()
boolean hasZAxis ()
boolean isObs ()
DatasetMetadata getMetadata ()
int getNetcdfCovn ()
void setNetcdfConv (int conv)
Public Member Functions inherited from anl.verdi.data.AbstractDataset
URL getURL ()
String getAlias ()
void setAlias (String alias)
List< String > getVariableNames ()
Variable getVariable (String name)
List< Variable > getVariables ()
Axes< CoordAxis > getCoordAxes ()
boolean hasTimeAxis ()
boolean hasXAxis ()
boolean hasYAxis ()
boolean hasZAxis ()
String getName ()
void close () throws IOException
boolean isObs ()
Additional Inherited Members
Static Public Attributes inherited from anl.verdi.data.Dataset
static final String NULL_ALIAS = "anl.verdi.data.DataSet.NULL_ALIAS"
static final int SINGLE_DATASET = -1
Protected Member Functions inherited from anl.verdi.data.AbstractDataset
AbstractDataset (URL url)
Protected Attributes inherited from anl.verdi.data.AbstractDataset
String alias = NULL_ALIAS
URL url
Detailed Description
Dataset for Models3 format observation data files.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 43 of file Models3ObsDataset.java.
Constructor & Destructor Documentation
anl.verdi.loaders.Models3ObsDataset.Models3ObsDataset (URL url, NetcdfDataset dataset)
Definition at line 65 of file Models3ObsDataset.java.
Member Function Documentation
void anl.verdi.loaders.Models3ObsDataset.close () throws IOException
Closes this dataset. It will have to be recreated to be used again.
Exceptions
java.io.IOException if an error occurs while closing the dataset
Implements anl.verdi.data.Dataset.
Definition at line 213 of file Models3ObsDataset.java.
Axes<CoordAxis> anl.verdi.loaders.Models3ObsDataset.getCoordAxes ()
Gets the coordindate Axes for this Dataset.
Returns
the coordindate Axes for this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 223 of file Models3ObsDataset.java.
int anl.verdi.loaders.Models3ObsDataset.getIndexInURL ()
Gets the index of this Dataset inside its URL, or Dataset.SINGLE_DATASET if it is the only dataset inside the URL.
Returns
the index of this Dataset inside its URL
Implements anl.verdi.data.Dataset.
Definition at line 234 of file Models3ObsDataset.java.
References anl.verdi.data.Dataset.SINGLE_DATASET.
DatasetMetadata anl.verdi.loaders.Models3ObsDataset.getMetadata ()
Get the dataset meta data
Returns
the DatasetMetadata object
Implements anl.verdi.data.Dataset.
Definition at line 367 of file Models3ObsDataset.java.
String anl.verdi.loaders.Models3ObsDataset.getName ()
Gets the name of this Dataset.
Returns
the name of this Dataset;
Implements anl.verdi.data.Dataset.
Definition at line 259 of file Models3ObsDataset.java.
int anl.verdi.loaders.Models3ObsDataset.getNetcdfCovn ()
Implements anl.verdi.data.Dataset.
Definition at line 373 of file Models3ObsDataset.java.
Variable anl.verdi.loaders.Models3ObsDataset.getVariable (String name)
Gets the named variable.
Parameters
name the name of the variable to get
Returns
the named variable
Implements anl.verdi.data.Dataset.
Definition at line 244 of file Models3ObsDataset.java.
References anl.verdi.loaders.Models3ObsDataset.getVariables().
List<String> anl.verdi.loaders.Models3ObsDataset.getVariableNames ()
Gets the list of variable names in this Dataset.
Returns
the list of variable names in this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 302 of file Models3ObsDataset.java.
References anl.verdi.loaders.Models3ObsDataset.getVariables().
List<Variable> anl.verdi.loaders.Models3ObsDataset.getVariables ()
Gets the list of variables in this Dataset.
Returns
the list of variables in this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 316 of file Models3ObsDataset.java.
Referenced by anl.verdi.loaders.Models3ObsDataset.getVariable(), and anl.verdi.loaders.Models3ObsDataset.getVariableNames().
boolean anl.verdi.loaders.Models3ObsDataset.hasTimeAxis ()
Returns
true if there is a time axis, otherwise false
Implements anl.verdi.data.Dataset.
Definition at line 323 of file Models3ObsDataset.java.
boolean anl.verdi.loaders.Models3ObsDataset.hasXAxis ()
Returns
true if there is a X axis, otherwise false
Implements anl.verdi.data.Dataset.
Definition at line 330 of file Models3ObsDataset.java.
boolean anl.verdi.loaders.Models3ObsDataset.hasYAxis ()
Returns
true if there is a Y axis, otherwise false
Implements anl.verdi.data.Dataset.
Definition at line 337 of file Models3ObsDataset.java.
boolean anl.verdi.loaders.Models3ObsDataset.hasZAxis ()
See if there is a z (e.g. layer) axis
Returns
true if there is a Z axis, otherwise false
Implements anl.verdi.data.Dataset.
Definition at line 346 of file Models3ObsDataset.java.
boolean anl.verdi.loaders.Models3ObsDataset.isObs ()
Whether or not this dataset represents an observational dataset
Returns
true if this contains obs data, otherwise false.
Implements anl.verdi.data.Dataset.
Definition at line 357 of file Models3ObsDataset.java.
void anl.verdi.loaders.Models3ObsDataset.setAlias (String alias)
Sets the alias for this Dataset.
Parameters
alias the alias for this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 289 of file Models3ObsDataset.java.
References anl.verdi.data.AbstractDataset.alias, and anl.verdi.data.AbstractDataset.getAlias().
void anl.verdi.loaders.Models3ObsDataset.setNetcdfConv (int conv)
Implements anl.verdi.data.Dataset.
Definition at line 379 of file Models3ObsDataset.java.
The documentation for this class was generated from the following file:
verdi_data_loaders/src/anl/verdi/loaders/Models3ObsDataset.java