VERDI: anl.verdi.plot.probe.TimeSeriesProbeCreator Class Reference
anl.verdi.plot.probe.TimeSeriesProbeCreator Class Reference
Public Member Functions
TimeSeriesProbeCreator (DataFrame frame, Slice slice)
TableModel createTableModel ()
String getName ()
String getRangeAxisName ()
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 13 of file TimeSeriesProbeCreator.java.
Constructor & Destructor Documentation
anl.verdi.plot.probe.TimeSeriesProbeCreator.TimeSeriesProbeCreator (DataFrame frame, Slice slice)
Definition at line 18 of file TimeSeriesProbeCreator.java.
References anl.verdi.data.DataFrame.getAxes(), anl.verdi.plot.probe.TimeSeriesProbeCreator.getName(), and anl.verdi.data.Slice.getTimeRange().
Member Function Documentation
TableModel anl.verdi.plot.probe.TimeSeriesProbeCreator.createTableModel ()
Creates the probe.
Implements anl.verdi.plot.probe.ProbeCreator.
Definition at line 35 of file TimeSeriesProbeCreator.java.
String anl.verdi.plot.probe.TimeSeriesProbeCreator.getName ()
Gets the name of the probe.
Returns
the name of the probe.
Implements anl.verdi.plot.probe.ProbeCreator.
Definition at line 45 of file TimeSeriesProbeCreator.java.
Referenced by anl.verdi.plot.probe.TimeSeriesProbeCreator.TimeSeriesProbeCreator().
String anl.verdi.plot.probe.TimeSeriesProbeCreator.getRangeAxisName ()
Gets the name of the range axis.
Returns
the name of the range axis.
Implements anl.verdi.plot.probe.ProbeCreator.
Definition at line 54 of file TimeSeriesProbeCreator.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/probe/TimeSeriesProbeCreator.java