VERDI: ucar.unidata.geoloc.projection.Stereographic Class Reference
ucar.unidata.geoloc.projection.Stereographic Class Reference
Public Member Functions
ProjectionImpl constructCopy ()
Stereographic ()
Stereographic (double latt, double lont, double scale)
Stereographic (double latt, double lont, double scale, double false_easting, double false_northing)
Stereographic (double latt, double lont, double scale, double false_easting, double false_northing, double radius)
Stereographic (double lat_ts_deg, double latt_deg, double lont_deg, boolean north)
double getScaleFactor (double lat_ts, boolean north)
double getScale ()
double getNaturalOriginLat ()
double getCentralMeridian ()
double getTangentLon ()
double getTangentLat ()
double getEarthRadius ()
boolean isNorth ()
boolean isPolar ()
void setScale (double scale)
void setTangentLat (double latt)
void setTangentLon (double lont)
void setCentralMeridian (double cm)
void setFalseEasting (double falseEasting)
void setFalseNorthing (double falseNorthing)
String paramsToString ()
String toString ()
boolean crossSeam (ProjectionPoint pt1, ProjectionPoint pt2)
boolean equals (Object o)
int hashCode ()
double getFalseEasting ()
double getFalseNorthing ()
ProjectionPoint latLonToProj (LatLonPoint latLon, ProjectionPointImpl result)
LatLonPoint projToLatLon (ProjectionPoint world, LatLonPointImpl result)
float[][] latLonToProj (float[][] from, float[][] to, int latIndex, int lonIndex)
float[][] projToLatLon (float[][] from, float[][] to)
double[][] latLonToProj (double[][] from, double[][] to, int latIndex, int lonIndex)
double[][] projToLatLon (double[][] from, double[][] to)
Static Public Member Functions
static Stereographic factory (double latt, double lont, double latTrue)
Detailed Description
Stereographic projection, spherical earth. Projection plane is a plane tangent to the earth at latt, lont. see John Snyder, Map Projections used by the USGS, Bulletin 1532, 2nd edition (1983), p 153
Author
John Caron
Definition at line 47 of file Stereographic.java.
Constructor & Destructor Documentation
ucar.unidata.geoloc.projection.Stereographic.Stereographic ()
Constructor with default parameters = North Polar
Definition at line 92 of file Stereographic.java.
Referenced by ucar.unidata.geoloc.projection.Stereographic.constructCopy(), ucar.unidata.geoloc.projection.Stereographic.equals(), and ucar.unidata.geoloc.projection.Stereographic.factory().
ucar.unidata.geoloc.projection.Stereographic.Stereographic (double latt, double lont, double scale)
Construct a Stereographic Projection.
Parameters
latt tangent point of projection, also origin of projection coord system
lont tangent point of projection, also origin of projection coord system
scale scale factor at tangent point, "normally 1.0 but may be reduced"
Definition at line 103 of file Stereographic.java.
ucar.unidata.geoloc.projection.Stereographic.Stereographic (double latt, double lont, double scale, double false_easting, double false_northing)
Construct a Stereographic Projection.
Parameters
latt tangent point of projection, also origin of projection coord system
lont tangent point of projection, also origin of projection coord system
scale scale factor at tangent point, "normally 1.0 but may be reduced"
Definition at line 114 of file Stereographic.java.
ucar.unidata.geoloc.projection.Stereographic.Stereographic (double latt, double lont, double scale, double false_easting, double false_northing, double radius)
Construct a Stereographic Projection.
Parameters
latt tangent point of projection, also origin of projection coord system
lont tangent point of projection, also origin of projection coord system
scale scale factor at tangent point, "normally 1.0 but may be reduced"
false_easting false easting in units of x coords
false_northing false northing in units of y coords
radius earth radius in km
Definition at line 128 of file Stereographic.java.
ucar.unidata.geoloc.projection.Stereographic.Stereographic (double lat_ts_deg, double latt_deg, double lont_deg, boolean north)
Construct a polar Stereographic Projection, from the "natural origin" and the tangent point, calculating the scale factor.
Parameters
lat_ts_deg Latitude at natural origin (degrees_north)
latt_deg tangent point of projection (degrees_north)
lont_deg tangent point of projection, also origin of projection coord system ((degrees_east)
north true if north pole, false is south pole
Definition at line 161 of file Stereographic.java.
References ucar.unidata.geoloc.projection.Stereographic.getScaleFactor().
Member Function Documentation
ProjectionImpl ucar.unidata.geoloc.projection.Stereographic.constructCopy ()
Definition at line 75 of file Stereographic.java.
References ucar.unidata.geoloc.projection.Stereographic.getEarthRadius(), ucar.unidata.geoloc.projection.Stereographic.getFalseEasting(), ucar.unidata.geoloc.projection.Stereographic.getFalseNorthing(), ucar.unidata.geoloc.projection.Stereographic.getScale(), ucar.unidata.geoloc.projection.Stereographic.getTangentLat(), ucar.unidata.geoloc.projection.Stereographic.getTangentLon(), and ucar.unidata.geoloc.projection.Stereographic.Stereographic().
boolean ucar.unidata.geoloc.projection.Stereographic.crossSeam (ProjectionPoint pt1, ProjectionPoint pt2)
Does the line between these two points cross the projection "seam".
Parameters
pt1 the line goes between these two points
pt2 the line goes between these two points
Returns
false if there is no seam
Definition at line 373 of file Stereographic.java.
boolean ucar.unidata.geoloc.projection.Stereographic.equals (Object o)
Definition at line 378 of file Stereographic.java.
References ucar.unidata.geoloc.projection.Stereographic.equals(), and ucar.unidata.geoloc.projection.Stereographic.Stereographic().
Referenced by ucar.unidata.geoloc.projection.Stereographic.equals().
static Stereographic ucar.unidata.geoloc.projection.Stereographic.factory (double latt, double lont, double latTrue) static
Construct a Stereographic Projection using latitude of true scale and calculating scale factor.
Since the scale factor at lat = k = 2*k0/(1+sin(lat)) [Snyder,Working Manual p157] then to make scale = 1 at lat, set k0 = (1+sin(lat))/2
Parameters
latt tangent point of projection, also origin of projection coord system
lont tangent point of projection, also origin of projection coord system
latTrue latitude of true scale in degrees north; latitude where scale factor = 1.0
Returns
Stereographic projection
Definition at line 59 of file Stereographic.java.
References ucar.unidata.geoloc.projection.Stereographic.Stereographic().
double ucar.unidata.geoloc.projection.Stereographic.getCentralMeridian ()
Definition at line 241 of file Stereographic.java.
double ucar.unidata.geoloc.projection.Stereographic.getEarthRadius ()
Definition at line 264 of file Stereographic.java.
Referenced by ucar.unidata.geoloc.projection.Stereographic.constructCopy().
double ucar.unidata.geoloc.projection.Stereographic.getFalseEasting ()
Get the false easting, in km.
Returns
the false easting.
Definition at line 420 of file Stereographic.java.
Referenced by ucar.unidata.geoloc.projection.Stereographic.constructCopy().
double ucar.unidata.geoloc.projection.Stereographic.getFalseNorthing ()
Get the false northing, in km.
Returns
the false northing.
Definition at line 429 of file Stereographic.java.
Referenced by ucar.unidata.geoloc.projection.Stereographic.constructCopy().
double ucar.unidata.geoloc.projection.Stereographic.getNaturalOriginLat ()
Get the latitude at natural origin
Returns
latitude at natural origin
Definition at line 236 of file Stereographic.java.
double ucar.unidata.geoloc.projection.Stereographic.getScale ()
Get the scale
Returns
the scale
Definition at line 227 of file Stereographic.java.
Referenced by ucar.unidata.geoloc.projection.Stereographic.constructCopy().
double ucar.unidata.geoloc.projection.Stereographic.getScaleFactor (double lat_ts, boolean north)
Calculate polar stereographic scale factor based on the natural latitude and longitude of the original Ref: OGP Surveying and Positioning Guidance Note number 7, part 2 April 2009 http://www.epsg.org added by Qun He qunhe.nosp@m.@unc.nosp@m..edu
Parameters
lat_ts Latitude at natural origin
north Is it north polar?
Returns
scale factor
Definition at line 195 of file Stereographic.java.
Referenced by ucar.unidata.geoloc.projection.Stereographic.Stereographic().
double ucar.unidata.geoloc.projection.Stereographic.getTangentLat ()
Get the tangent latitude in degrees
Returns
the origin latitude.
Definition at line 260 of file Stereographic.java.
Referenced by ucar.unidata.geoloc.projection.Stereographic.constructCopy().
double ucar.unidata.geoloc.projection.Stereographic.getTangentLon ()
Get the tangent longitude in degrees
Returns
the origin longitude.
Definition at line 251 of file Stereographic.java.
Referenced by ucar.unidata.geoloc.projection.Stereographic.constructCopy().
int ucar.unidata.geoloc.projection.Stereographic.hashCode ()
Definition at line 397 of file Stereographic.java.
boolean ucar.unidata.geoloc.projection.Stereographic.isNorth ()
Definition at line 268 of file Stereographic.java.
boolean ucar.unidata.geoloc.projection.Stereographic.isPolar ()
Definition at line 272 of file Stereographic.java.
ProjectionPoint ucar.unidata.geoloc.projection.Stereographic.latLonToProj (LatLonPoint latLon, ProjectionPointImpl result)
Convert a LatLonPoint to projection coordinates
Parameters
latLon convert from these lat, lon coordinates
result the object to write to
Returns
the given result
Definition at line 496 of file Stereographic.java.
float [][] ucar.unidata.geoloc.projection.Stereographic.latLonToProj (float from[][], float to[][], int latIndex, int lonIndex)
Convert lat/lon coordinates to projection coordinates.
Parameters
from array of lat/lon coordinates: from[2][n], where (from[latIndex][i], from[lonIndex][i]) is the (lat,lon) coordinate of the ith point
to resulting array of projection coordinates: to[2][n] where (to[0][i], to[1][i]) is the (x,y) coordinate of the ith point
latIndex index of lat coordinate; must be 0 or 1
lonIndex index of lon coordinate; must be 0 or 1
Returns
the "to" array
Definition at line 584 of file Stereographic.java.
double [][] ucar.unidata.geoloc.projection.Stereographic.latLonToProj (double from[][], double to[][], int latIndex, int lonIndex)
Convert lat/lon coordinates to projection coordinates.
Parameters
from array of lat/lon coordinates: from[2][n], where (from[latIndex][i], from[lonIndex][i]) is the (lat,lon) coordinate of the ith point
to resulting array of projection coordinates: to[2][n] where (to[0][i], to[1][i]) is the (x,y) coordinate of the ith point
latIndex index of lat coordinate; must be 0 or 1
lonIndex index of lon coordinate; must be 0 or 1
Returns
the "to" array
Definition at line 692 of file Stereographic.java.
String ucar.unidata.geoloc.projection.Stereographic.paramsToString ()
Get the parameters as a String
Returns
the parameters as a String
Definition at line 348 of file Stereographic.java.
References ucar.unidata.geoloc.projection.Stereographic.toString().
LatLonPoint ucar.unidata.geoloc.projection.Stereographic.projToLatLon (ProjectionPoint world, LatLonPointImpl result)
Convert projection coordinates to a LatLonPoint Note: a new object is not created on each call for the return value.
Parameters
world convert from these projection coordinates
result the object to write to
Returns
LatLonPoint convert to these lat/lon coordinates
Definition at line 532 of file Stereographic.java.
float [][] ucar.unidata.geoloc.projection.Stereographic.projToLatLon (float from[][], float to[][])
Convert projection coordinates to lat/lon coordinate.
Parameters
from array of projection coordinates: from[2][n], where (from[0][i], from[1][i]) is the (x, y) coordinate of the ith point
to resulting array of lat/lon coordinates: to[2][n] where (to[0][i], to[1][i]) is the (lat, lon) coordinate of the ith point
Returns
the "to" array
Definition at line 631 of file Stereographic.java.
double [][] ucar.unidata.geoloc.projection.Stereographic.projToLatLon (double from[][], double to[][])
Convert projection coordinates to lat/lon coordinate.
Parameters
from array of projection coordinates: from[2][n], where (from[0][i], from[1][i]) is the (x, y) coordinate of the ith point
to resulting array of lat/lon coordinates: to[2][n] where (to[0][i], to[1][i]) is the (lat, lon) coordinate of the ith point
Returns
the "to" array
Definition at line 739 of file Stereographic.java.
void ucar.unidata.geoloc.projection.Stereographic.setCentralMeridian (double cm)
Get the central meridian in degrees, if it was set. depends on the zone Set the central meridian in degrees
Definition at line 316 of file Stereographic.java.
void ucar.unidata.geoloc.projection.Stereographic.setFalseEasting (double falseEasting)
Set the false_easting, in km. natural_x_coordinate + false_easting = x coordinate
Parameters
falseEasting x offset
Definition at line 329 of file Stereographic.java.
void ucar.unidata.geoloc.projection.Stereographic.setFalseNorthing (double falseNorthing)
Set the false northing, in km. natural_y_coordinate + false_northing = y coordinate
Parameters
falseNorthing y offset
Definition at line 339 of file Stereographic.java.
void ucar.unidata.geoloc.projection.Stereographic.setScale (double scale)
Definition at line 282 of file Stereographic.java.
void ucar.unidata.geoloc.projection.Stereographic.setTangentLat (double latt)
Definition at line 290 of file Stereographic.java.
void ucar.unidata.geoloc.projection.Stereographic.setTangentLon (double lont)
Definition at line 298 of file Stereographic.java.
String ucar.unidata.geoloc.projection.Stereographic.toString ()
Definition at line 355 of file Stereographic.java.
Referenced by ucar.unidata.geoloc.projection.Stereographic.paramsToString().
The documentation for this class was generated from the following file:
verdi_data_loaders/src/ucar/unidata/geoloc/projection/Stereographic.java