VERDI: anl.verdi.plot.util.VerdiCanvas3D Class Reference
anl.verdi.plot.util.VerdiCanvas3D Class Reference
Public Member Functions
VerdiCanvas3D (DisplayRendererJ3D renderer)
VerdiCanvas3D (DisplayRendererJ3D renderer, GraphicsConfiguration config)
VerdiCanvas3D (DisplayRendererJ3D renderer, int w, int h) throws VisADException
void setTitleText (String text)
void setTitleFont (Font font)
void setTitleColor (Color color)
void setTimeText (String text)
void setTimeFont (Font font)
void setTimeColor (Color color)
void setSub1Text (String text)
void setSub1Font (Font font)
void setSub1Color (Color color)
void setSub2Text (String text)
void setSub2Font (Font font)
void setSub2Color (Color color)
Title getSub1 ()
Title getSub2 ()
Title getTime ()
Title getTitle ()
void renderField (int i)
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 20 of file VerdiCanvas3D.java.
Constructor & Destructor Documentation
anl.verdi.plot.util.VerdiCanvas3D.VerdiCanvas3D (DisplayRendererJ3D renderer)
Definition at line 30 of file VerdiCanvas3D.java.
anl.verdi.plot.util.VerdiCanvas3D.VerdiCanvas3D (DisplayRendererJ3D renderer, GraphicsConfiguration config)
Definition at line 34 of file VerdiCanvas3D.java.
anl.verdi.plot.util.VerdiCanvas3D.VerdiCanvas3D (DisplayRendererJ3D renderer, int w, int h) throws VisADException
Definition at line 38 of file VerdiCanvas3D.java.
Member Function Documentation
Title anl.verdi.plot.util.VerdiCanvas3D.getSub1 ()
Definition at line 118 of file VerdiCanvas3D.java.
Referenced by anl.verdi.plot.types.Contour3D.configure().
Title anl.verdi.plot.util.VerdiCanvas3D.getSub2 ()
Definition at line 122 of file VerdiCanvas3D.java.
Referenced by anl.verdi.plot.types.Contour3D.configure().
Title anl.verdi.plot.util.VerdiCanvas3D.getTime ()
Definition at line 126 of file VerdiCanvas3D.java.
Title anl.verdi.plot.util.VerdiCanvas3D.getTitle ()
Definition at line 130 of file VerdiCanvas3D.java.
Referenced by anl.verdi.plot.types.Contour3D.configure().
void anl.verdi.plot.util.VerdiCanvas3D.renderField (int i)
Definition at line 134 of file VerdiCanvas3D.java.
void anl.verdi.plot.util.VerdiCanvas3D.setSub1Color (Color color)
Definition at line 93 of file VerdiCanvas3D.java.
void anl.verdi.plot.util.VerdiCanvas3D.setSub1Font (Font font)
Definition at line 87 of file VerdiCanvas3D.java.
void anl.verdi.plot.util.VerdiCanvas3D.setSub1Text (String text)
Definition at line 80 of file VerdiCanvas3D.java.
void anl.verdi.plot.util.VerdiCanvas3D.setSub2Color (Color color)
Definition at line 112 of file VerdiCanvas3D.java.
void anl.verdi.plot.util.VerdiCanvas3D.setSub2Font (Font font)
Definition at line 106 of file VerdiCanvas3D.java.
void anl.verdi.plot.util.VerdiCanvas3D.setSub2Text (String text)
Definition at line 99 of file VerdiCanvas3D.java.
void anl.verdi.plot.util.VerdiCanvas3D.setTimeColor (Color color)
Definition at line 74 of file VerdiCanvas3D.java.
void anl.verdi.plot.util.VerdiCanvas3D.setTimeFont (Font font)
Definition at line 68 of file VerdiCanvas3D.java.
void anl.verdi.plot.util.VerdiCanvas3D.setTimeText (String text)
Definition at line 61 of file VerdiCanvas3D.java.
void anl.verdi.plot.util.VerdiCanvas3D.setTitleColor (Color color)
Definition at line 55 of file VerdiCanvas3D.java.
void anl.verdi.plot.util.VerdiCanvas3D.setTitleFont (Font font)
Definition at line 49 of file VerdiCanvas3D.java.
void anl.verdi.plot.util.VerdiCanvas3D.setTitleText (String text)
Definition at line 42 of file VerdiCanvas3D.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/util/VerdiCanvas3D.java