VERDI: anl.verdi.plot.gui.FastTilePlot Class Reference
anl.verdi.plot.gui.FastTilePlot Class Reference
Classes
class AreaFinder
class EpsRenderer
Public Member Functions
void drawBatchImage (int wdth, int hght)
void stopThread ()
void componentHidden (ComponentEvent unused)
void componentShown (ComponentEvent unused)
void componentResized (ComponentEvent unused)
void componentMoved (ComponentEvent unused)
void mousePressed (MouseEvent unused_)
void mouseEntered (MouseEvent unused_)
void mouseExited (MouseEvent unused_)
void mouseReleased (MouseEvent unused_)
void mouseClicked (MouseEvent unused_)
void viewClosed ()
void viewFloated (DockableFrameEvent unused_)
void viewRestored (DockableFrameEvent unused_)
void paintComponent (final Graphics graphics)
void draw ()
void actionPerformed (ActionEvent event)
void resetRowsNColumns (int fRow, int lRow, int fColumn, int lColumn)
void processMouseMotionEvent (MouseEvent me)
void processMouseEvent (MouseEvent me)
void stateChanged (ChangeEvent event)
void setTimestep (int timestep)
void setLayer (int layer)
FastTilePlot (VerdiApplication app, DataFrame dataFrame)
void computeDataRange (double[] minmax, boolean log)
JPanel getPanel ()
JMenuBar getMenuBar ()
void setLayerMapLine (VerdiBoundaries aVerdiBoundaries)
void editChartProperties ()
JToolBar getToolBar ()
Formula.Type getType ()
List< DataFrame > getData ()
void exportImage (String format, File file, int width, int height) throws IOException
void configure (PlotConfiguration config)
void configure (PlotConfiguration config, Plot.ConfigSource source)
PlotConfiguration getPlotConfiguration ()
BufferedImage getBufferedImage ()
BufferedImage getBufferedImage (int width, int height)
void addPlotListener (PlotListener listener)
void removePlotListener (PlotListener listener)
int print (Graphics g, PageFormat pf, int pageIndex) throws PrinterException
void updateTimeStep (int step)
Decidegrees getLatLonFor (int screenx, int screeny)
String createAreaString (int[] point)
String formatPoint (Point4i point)
void exportShapefile (String baseFileName) throws IOException
void exportASCIIGrid (String baseFileName)
void exportEPSImage (String filename)
void exportEPSImage (String filename, int width, int height)
JMapPane getMapPane ()
void addVectorAnnotation (VectorEvaluator eval)
void addObservationData (DataManager manager, boolean showLegend)
List< OverlayObject > getObservationData ()
String getTitle ()
void showBusyCursor ()
void restoreCursor ()
Public Member Functions inherited from anl.verdi.plot.gui.Plot
void configure (PlotConfiguration config, ConfigSource source)
Public Attributes
final Runnable doubleBufferedRenderer
Static Public Attributes
static final int NO_VAL = Integer.MIN_VALUE
static final String PROPERTIES_COMMAND = "PROPERTIES"
static final String SAVE_COMMAND = "SAVE"
static final String PRINT_COMMAND = "PRINT"
static final String ZOOM_IN_BOTH_COMMAND = "ZOOM_IN_BOTH"
static final String ZOOM_OUT_BOTH_COMMAND = "ZOOM_OUT_BOTH"
static final String ZOOM_OUT_MAX_COMMAND = "ZOOM_OUT_MAX"
Protected Member Functions
void showPopup (MouseEvent me)
boolean isInDataArea (MouseEvent me)
int getRow (Point p)
int getCol (Point p)
void addObsOverlay ()
void addVectorOverlay ()
void activateRubberBand ()
void deactivateRubberBand ()
void resetMenuItems (JMenu addLayers)
FeatureLayer createControlLayer (String shapefile)
JPopupMenu createPopupMenu (boolean properties, boolean save, boolean print, boolean zoomable)
DataUtilities.MinMaxPoint getMinMaxPoints ()
void enableProbeItems (boolean val)
Point2D getLatLonForAxisPoint (Point axisPoint)
DataFrame getDataFrame ()
DataFrame getDataFrame (boolean log)
Protected Attributes
boolean log = false
int startDate
int startTime
int timestepSize
int timesteps
int layers
int rows
int columns
int rowOrigin
int columnOrigin
TilePlot tilePlot
int timestep = 0
int firstTimestep = 0
int lastTimestep = 0
int layer = 0
int firstLayer = 0
int lastLayer = 0
double[] legendLevels
Palette defaultPalette
ColorMap map
Projector projector
double[][] gridBounds = { { 0.0, 0.0 }, { 0.0, 0.0 } }
double[][] domain = { { 0.0, 0.0 }, { 0.0, 0.0 } }
String units
DataFrame dataFrame
DataFrame dataFrameLog
List< OverlayObject > obsData = new ArrayList<OverlayObject>()
List< ObsAnnotation > obsAnnotations
VectorAnnotation vectAnnotation
final Rubberband rubberband = new Rubberband(this)
boolean zoom = true
boolean probe = false
boolean showLatLon = false
boolean showObsLegend = false
java.util.List< JMenuItem > probeItems = new ArrayList<JMenuItem>()
Rectangle dataArea = new Rectangle()
Slice probedSlice
JCheckBoxMenuItem showGridLines
MinMax minMax
PlotConfiguration config
Action timeSeriesSelected
Action timeSeriesBarSelected
Action timeSeriesMin
Action timeSeriesMax
Detailed Description
Definition at line 155 of file FastTilePlot.java.
Constructor & Destructor Documentation
anl.verdi.plot.gui.FastTilePlot.FastTilePlot (VerdiApplication app, DataFrame dataFrame)
Definition at line 1282 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.columnOrigin, anl.verdi.plot.gui.FastTilePlot.columns, anl.verdi.plot.gui.FastTilePlot.computeDataRange(), anl.verdi.plot.gui.FastTilePlot.config, anl.verdi.plot.gui.FastTilePlot.dataFrame, anl.verdi.plot.gui.FastTilePlot.defaultPalette, anl.verdi.plot.gui.FastTilePlot.doubleBufferedRenderer, anl.verdi.plot.gui.FastTilePlot.draw(), anl.verdi.plot.gui.FastTilePlot.firstLayer, anl.verdi.plot.gui.FastTilePlot.firstTimestep, anl.verdi.plot.gui.FastTilePlot.getDataFrame(), anl.verdi.data.AxisRange.getExtent(), anl.verdi.plot.color.ColorMap.getPalette(), anl.verdi.plot.gui.FastTilePlot.lastLayer, anl.verdi.plot.gui.FastTilePlot.lastTimestep, anl.verdi.plot.gui.FastTilePlot.layer, anl.verdi.plot.gui.FastTilePlot.layers, anl.verdi.plot.gui.FastTilePlot.legendLevels, anl.verdi.plot.gui.FastTilePlot.log, anl.verdi.plot.gui.FastTilePlot.map, anl.verdi.plot.gui.FastTilePlot.minMax, anl.verdi.plot.gui.FastTilePlot.projector, anl.verdi.plot.gui.FastTilePlot.rowOrigin, anl.verdi.plot.gui.FastTilePlot.rows, anl.verdi.plot.gui.FastTilePlot.startDate, anl.verdi.plot.gui.FastTilePlot.startTime, anl.verdi.plot.gui.FastTilePlot.stateChanged(), gov.epa.emvl.GridCellStatistics.STATISTICS, anl.verdi.plot.gui.FastTilePlot.tilePlot, anl.verdi.plot.gui.FastTilePlot.timestep, anl.verdi.plot.gui.FastTilePlot.timesteps, anl.verdi.plot.gui.FastTilePlot.timestepSize, and anl.verdi.plot.gui.FastTilePlot.units.
Member Function Documentation
void anl.verdi.plot.gui.FastTilePlot.actionPerformed (ActionEvent event)
Definition at line 902 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.computeDataRange(), anl.verdi.plot.gui.FastTilePlot.defaultPalette, anl.verdi.plot.gui.FastTilePlot.draw(), anl.verdi.plot.gui.FastTilePlot.editChartProperties(), anl.verdi.plot.gui.FastTilePlot.getCol(), anl.verdi.plot.color.ColorMap.getPalette(), anl.verdi.plot.gui.FastTilePlot.getRow(), anl.verdi.plot.gui.FastTilePlot.legendLevels, anl.verdi.plot.gui.FastTilePlot.log, anl.verdi.plot.gui.FastTilePlot.map, anl.verdi.plot.gui.FastTilePlot.minMax, anl.verdi.plot.gui.FastTilePlot.print(), anl.verdi.plot.gui.FastTilePlot.PRINT_COMMAND, anl.verdi.plot.gui.FastTilePlot.PROPERTIES_COMMAND, anl.verdi.plot.gui.FastTilePlot.SAVE_COMMAND, anl.verdi.plot.gui.FastTilePlot.timestep, anl.verdi.plot.gui.FastTilePlot.zoom, anl.verdi.plot.gui.FastTilePlot.ZOOM_IN_BOTH_COMMAND, anl.verdi.plot.gui.FastTilePlot.ZOOM_OUT_BOTH_COMMAND, and anl.verdi.plot.gui.FastTilePlot.ZOOM_OUT_MAX_COMMAND.
Referenced by anl.verdi.plot.gui.FastTilePlot.getMenuBar().
void anl.verdi.plot.gui.FastTilePlot.activateRubberBand () protected
Definition at line 2075 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.getMenuBar().
void anl.verdi.plot.gui.FastTilePlot.addObservationData (DataManager manager, boolean showLegend)
Definition at line 3465 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.config, anl.verdi.plot.gui.FastTilePlot.draw(), anl.verdi.plot.gui.FastTilePlot.getDataFrame(), anl.verdi.plot.config.PlotConfiguration.getSubtitle1(), anl.verdi.plot.gui.FastTilePlot.layer, anl.verdi.plot.config.PlotConfiguration.OBS_SHOW_LEGEND, anl.verdi.plot.gui.FastTilePlot.obsAnnotations, anl.verdi.plot.gui.FastTilePlot.obsData, anl.verdi.plot.gui.FastTilePlot.showObsLegend, and anl.verdi.plot.gui.FastTilePlot.timestep.
void anl.verdi.plot.gui.FastTilePlot.addObsOverlay () protected
Definition at line 2065 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.getMenuBar().
void anl.verdi.plot.gui.FastTilePlot.addPlotListener (PlotListener listener)
Adds the specified PlotListener.
Parameters
listener the plot listener to add
Implements anl.verdi.plot.gui.Plot.
Definition at line 2626 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.addVectorAnnotation (VectorEvaluator eval)
Definition at line 3460 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.draw(), anl.verdi.plot.gui.FastTilePlot.getDataFrame(), anl.verdi.plot.gui.FastTilePlot.timestep, and anl.verdi.plot.gui.FastTilePlot.vectAnnotation.
void anl.verdi.plot.gui.FastTilePlot.addVectorOverlay () protected
Definition at line 2070 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.getMenuBar().
void anl.verdi.plot.gui.FastTilePlot.componentHidden (ComponentEvent unused)
Definition at line 800 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.componentMoved (ComponentEvent unused)
Definition at line 816 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.componentResized (ComponentEvent unused)
Definition at line 810 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.draw().
void anl.verdi.plot.gui.FastTilePlot.componentShown (ComponentEvent unused)
Definition at line 804 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.draw().
void anl.verdi.plot.gui.FastTilePlot.computeDataRange (double[] minmax, boolean log)
Definition at line 1812 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.columns, anl.verdi.plot.gui.FastTilePlot.dataFrame, anl.verdi.plot.gui.FastTilePlot.getDataFrame(), anl.verdi.plot.gui.FastTilePlot.layer, anl.verdi.plot.gui.FastTilePlot.layers, anl.verdi.plot.gui.FastTilePlot.log, anl.verdi.plot.gui.FastTilePlot.rows, anl.verdi.plot.gui.FastTilePlot.timestep, and anl.verdi.plot.gui.FastTilePlot.timesteps.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), anl.verdi.plot.gui.FastAreaTilePlot.calculateGridLevels(), anl.verdi.plot.gui.FastTilePlot.configure(), and anl.verdi.plot.gui.FastTilePlot.FastTilePlot().
void anl.verdi.plot.gui.FastTilePlot.configure (PlotConfiguration config)
Configure this Plot according to the specified PlotConfiguration.
Parameters
config the new plot configuration
Implements anl.verdi.plot.gui.Plot.
Definition at line 2432 of file FastTilePlot.java.
References anl.verdi.plot.config.TilePlotConfiguration.COLOR_MAP, anl.verdi.plot.gui.FastTilePlot.computeDataRange(), anl.verdi.plot.color.ColorMap.getLogBase(), anl.verdi.plot.config.PlotConfiguration.getObject(), anl.verdi.plot.gui.FastTilePlot.map, anl.verdi.plot.config.TilePlotConfiguration.SHOW_GRID_LINES, anl.verdi.plot.gui.FastTilePlot.showGridLines, and anl.verdi.plot.gui.FastTilePlot.tilePlot.
Referenced by anl.verdi.plot.gui.FastTilePlot.configure().
void anl.verdi.plot.gui.FastTilePlot.configure (PlotConfiguration config, Plot.ConfigSource source)
Definition at line 2488 of file FastTilePlot.java.
References anl.verdi.plot.config.TilePlotConfiguration.COLOR_MAP, anl.verdi.plot.gui.FastTilePlot.computeDataRange(), anl.verdi.plot.gui.FastTilePlot.configure(), anl.verdi.plot.color.ColorMap.getLogBase(), anl.verdi.plot.config.PlotConfiguration.getObject(), anl.verdi.plot.gui.FastTilePlot.map, anl.verdi.plot.config.TilePlotConfiguration.SHOW_GRID_LINES, anl.verdi.plot.gui.FastTilePlot.showGridLines, and anl.verdi.plot.gui.FastTilePlot.tilePlot.
String anl.verdi.plot.gui.FastTilePlot.createAreaString (int[] point)
Definition at line 3112 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.formatPoint(), and anl.verdi.plot.gui.FastTilePlot.showLatLon.
FeatureLayer anl.verdi.plot.gui.FastTilePlot.createControlLayer (String shapefile) protected
Definition at line 2214 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.getDataFrame().
JPopupMenu anl.verdi.plot.gui.FastTilePlot.createPopupMenu (boolean properties, boolean save, boolean print, boolean zoomable) protected
Creates a popup menu for the panel.
Parameters
properties include a menu item for the chart property editor.
save include a menu item for saving the chart.
print include a menu item for printing the chart.
zoom include menu items for zooming.
Returns
The popup menu.
Definition at line 2865 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.PRINT_COMMAND, anl.verdi.plot.gui.FastTilePlot.PROPERTIES_COMMAND, anl.verdi.plot.gui.FastTilePlot.SAVE_COMMAND, anl.verdi.plot.gui.FastTilePlot.ZOOM_IN_BOTH_COMMAND, anl.verdi.plot.gui.FastTilePlot.ZOOM_OUT_BOTH_COMMAND, and anl.verdi.plot.gui.FastTilePlot.ZOOM_OUT_MAX_COMMAND.
Referenced by anl.verdi.plot.gui.FastTilePlot.showPopup().
void anl.verdi.plot.gui.FastTilePlot.deactivateRubberBand () protected
Definition at line 2079 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.getMenuBar().
void anl.verdi.plot.gui.FastTilePlot.draw ()
Definition at line 889 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), anl.verdi.plot.gui.FastTilePlot.addObservationData(), anl.verdi.plot.gui.FastTilePlot.addVectorAnnotation(), anl.verdi.plot.gui.FastTilePlot.componentResized(), anl.verdi.plot.gui.FastTilePlot.componentShown(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar(), anl.verdi.plot.gui.FastTilePlot.getMenuBar(), anl.verdi.plot.gui.FastTilePlot.paintComponent(), anl.verdi.plot.gui.FastAreaTilePlot.repaintAll(), anl.verdi.plot.gui.FastTilePlot.setLayer(), anl.verdi.plot.gui.FastTilePlot.setTimestep(), and anl.verdi.plot.gui.FastTilePlot.stopThread().
void anl.verdi.plot.gui.FastTilePlot.drawBatchImage (int wdth, int hght)
Definition at line 690 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.config, anl.verdi.plot.gui.FastTilePlot.domain, anl.verdi.plot.gui.FastTilePlot.firstTimestep, anl.verdi.plot.config.PlotConfiguration.getObject(), anl.verdi.plot.config.TilePlotConfiguration.GRID_LINE_COLOR, anl.verdi.plot.gui.FastTilePlot.gridBounds, anl.verdi.plot.gui.FastTilePlot.layer, anl.verdi.plot.gui.FastTilePlot.legendLevels, anl.verdi.plot.gui.FastTilePlot.log, anl.verdi.plot.config.TilePlotConfiguration.SHOW_GRID_LINES, anl.verdi.plot.gui.FastTilePlot.showGridLines, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_FONT, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_FONT, anl.verdi.plot.gui.FastTilePlot.tilePlot, anl.verdi.plot.gui.FastTilePlot.timestep, anl.verdi.plot.config.PlotConfiguration.TITLE_FONT, and anl.verdi.plot.gui.FastTilePlot.units.
Referenced by anl.verdi.plot.gui.FastTilePlot.exportImage().
void anl.verdi.plot.gui.FastTilePlot.editChartProperties ()
Displays a dialog that allows the user to edit the properties for the current chart.
Since
1.0.5
Definition at line 2358 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.minMax.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), and anl.verdi.plot.gui.FastTilePlot.getMenuBar().
void anl.verdi.plot.gui.FastTilePlot.enableProbeItems (boolean val) protected
Enables / disables the menu items that work with the currently probed point.
Parameters
val true to enable
Definition at line 3081 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.probeItems.
void anl.verdi.plot.gui.FastTilePlot.exportASCIIGrid (String baseFileName)
Definition at line 3331 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.exportEPSImage (String filename)
Definition at line 3352 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.exportEPSImage (String filename, int width, int height)
Definition at line 3359 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.exportImage (String format, File file, int width, int height) throws IOException
Exports an image of this Plot to the specified file in the specified format.
Parameters
format the image format. One of PlotExporter.JPG, PlotExporter.TIF, PlotExporter.PNG, or PlotExporter.BMP
file the file to save the image to.
width width of image in pixels
height height of image in pixels
Exceptions
IOException if there is an error creating the image
Implements anl.verdi.plot.gui.Plot.
Definition at line 2419 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.drawBatchImage().
void anl.verdi.plot.gui.FastTilePlot.exportShapefile (String baseFileName) throws IOException
Definition at line 3309 of file FastTilePlot.java.
String anl.verdi.plot.gui.FastTilePlot.formatPoint (Point4i point)
Definition at line 3122 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.NO_VAL.
Referenced by anl.verdi.plot.gui.FastTilePlot.createAreaString().
BufferedImage anl.verdi.plot.gui.FastTilePlot.getBufferedImage ()
Gets a BufferedImage of the plot.
Returns
a BufferedImage of the plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 2600 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.print().
BufferedImage anl.verdi.plot.gui.FastTilePlot.getBufferedImage (int width, int height)
Gets a BufferedImage of the plot.
Parameters
width the width of the image in pixels
height the height of the image in pixels
Returns
a BufferedImage of the plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 2614 of file FastTilePlot.java.
int anl.verdi.plot.gui.FastTilePlot.getCol (Point p) protected
Definition at line 1141 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed().
List<DataFrame> anl.verdi.plot.gui.FastTilePlot.getData ()
Gets the data that this Plot plots.
Returns
the data that this Plot plots.
Implements anl.verdi.plot.gui.Plot.
Definition at line 2397 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.getDataFrame().
DataFrame anl.verdi.plot.gui.FastTilePlot.getDataFrame () protected
Definition at line 3580 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.actionPerformed(), anl.verdi.plot.gui.FastTilePlot.addObservationData(), anl.verdi.plot.gui.FastTilePlot.addVectorAnnotation(), anl.verdi.plot.gui.FastTilePlot.computeDataRange(), anl.verdi.plot.gui.FastTilePlot.createControlLayer(), anl.verdi.plot.gui.FastAreaTilePlot.createTableName(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.getAllLayerData(), anl.verdi.plot.gui.FastTilePlot.getData(), anl.verdi.plot.gui.FastTilePlot.getLatLonForAxisPoint(), anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar(), anl.verdi.plot.gui.FastTilePlot.getMenuBar(), anl.verdi.plot.gui.FastTilePlot.getMinMaxPoints(), anl.verdi.plot.gui.FastAreaTilePlot.processMouseMotionEvent(), and anl.verdi.plot.gui.FastAreaTilePlot.recalculateAreas().
DataFrame anl.verdi.plot.gui.FastTilePlot.getDataFrame (boolean log) protected
Definition at line 3588 of file FastTilePlot.java.
Decidegrees anl.verdi.plot.gui.FastTilePlot.getLatLonFor (int screenx, int screeny)
Definition at line 3087 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.dataArea, and anl.verdi.plot.gui.FastTilePlot.gridBounds.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.processMouseEvent(), anl.verdi.plot.gui.FastAreaTilePlot.processMouseMotionEvent(), and anl.verdi.plot.gui.FastTilePlot.processMouseMotionEvent().
Point2D anl.verdi.plot.gui.FastTilePlot.getLatLonForAxisPoint (Point axisPoint) protected
Definition at line 3171 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.getDataFrame().
JMapPane anl.verdi.plot.gui.FastTilePlot.getMapPane ()
Gets the JMapPane that contains the mapping portion of the plot component.
Returns
the mapping panel that contains the mapping portion of the plot component.
Implements anl.verdi.plot.gui.Plot.
Definition at line 3455 of file FastTilePlot.java.
JMenuBar anl.verdi.plot.gui.FastTilePlot.getMenuBar ()
Gets a menu bar for this Plot. This may return null if there is no menu bar.
Returns
a menu bar for this Plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 1894 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.actionPerformed(), anl.verdi.plot.gui.FastTilePlot.activateRubberBand(), anl.verdi.plot.gui.FastTilePlot.addObsOverlay(), anl.verdi.plot.gui.FastTilePlot.addVectorOverlay(), anl.verdi.plot.gui.FastTilePlot.config, anl.verdi.plot.gui.FastTilePlot.deactivateRubberBand(), anl.verdi.plot.gui.FastTilePlot.draw(), anl.verdi.plot.gui.FastTilePlot.editChartProperties(), anl.verdi.plot.gui.FastTilePlot.getDataFrame(), anl.verdi.plot.config.PlotConfiguration.getObject(), anl.verdi.plot.config.TilePlotConfiguration.GRID_LINE_COLOR, anl.verdi.plot.gui.FastTilePlot.probe, anl.verdi.plot.gui.FastTilePlot.showGridLines, anl.verdi.plot.gui.FastTilePlot.showLatLon, anl.verdi.plot.gui.FastTilePlot.timeSeriesBarSelected, anl.verdi.plot.gui.FastTilePlot.timeSeriesMax, anl.verdi.plot.gui.FastTilePlot.timeSeriesMin, anl.verdi.plot.gui.FastTilePlot.timeSeriesSelected, and anl.verdi.plot.gui.FastTilePlot.zoom.
DataUtilities.MinMaxPoint anl.verdi.plot.gui.FastTilePlot.getMinMaxPoints () protected
Gets the MinMax points for this plot.
Returns
the MinMax points for this plot.
Definition at line 2955 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.firstLayer, anl.verdi.plot.gui.FastTilePlot.firstTimestep, anl.verdi.plot.gui.FastTilePlot.getDataFrame(), anl.verdi.plot.gui.FastTilePlot.layer, and anl.verdi.plot.gui.FastTilePlot.timestep.
List<OverlayObject> anl.verdi.plot.gui.FastTilePlot.getObservationData ()
Definition at line 3517 of file FastTilePlot.java.
JPanel anl.verdi.plot.gui.FastTilePlot.getPanel ()
Gets the panel that contains the plot component.
Returns
the panel that contains the plot component.
Implements anl.verdi.plot.gui.Plot.
Definition at line 1883 of file FastTilePlot.java.
PlotConfiguration anl.verdi.plot.gui.FastTilePlot.getPlotConfiguration ()
Gets this Plot's configuration data.
Returns
this Plot's configuration data.
Implements anl.verdi.plot.gui.Plot.
Definition at line 2590 of file FastTilePlot.java.
int anl.verdi.plot.gui.FastTilePlot.getRow (Point p) protected
Definition at line 1132 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed().
String anl.verdi.plot.gui.FastTilePlot.getTitle ()
Gets this plot's current title.
Implements anl.verdi.plot.gui.Plot.
Definition at line 3542 of file FastTilePlot.java.
JToolBar anl.verdi.plot.gui.FastTilePlot.getToolBar ()
Gets a tool bar for this plot. This may return null if there is no tool bar.
Returns
a tool bar for this plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 2377 of file FastTilePlot.java.
Formula.Type anl.verdi.plot.gui.FastTilePlot.getType ()
Gets the type of the Plot.
Returns
the type of the Plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 2387 of file FastTilePlot.java.
boolean anl.verdi.plot.gui.FastTilePlot.isInDataArea (MouseEvent me) protected
Definition at line 1117 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.dataArea.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.processMouseEvent(), anl.verdi.plot.gui.FastTilePlot.processMouseEvent(), anl.verdi.plot.gui.FastAreaTilePlot.processMouseMotionEvent(), and anl.verdi.plot.gui.FastTilePlot.processMouseMotionEvent().
void anl.verdi.plot.gui.FastTilePlot.mouseClicked (MouseEvent unused_)
Definition at line 835 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.mouseEntered (MouseEvent unused_)
Definition at line 832 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.mouseExited (MouseEvent unused_)
Definition at line 833 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.mousePressed (MouseEvent unused_)
Definition at line 831 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.mouseReleased (MouseEvent unused_)
Definition at line 834 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.paintComponent (final Graphics graphics)
Definition at line 884 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.draw().
int anl.verdi.plot.gui.FastTilePlot.print (Graphics g, PageFormat pf, int pageIndex) throws PrinterException
Definition at line 2642 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.getBufferedImage().
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), and anl.verdi.plot.gui.FastAreaTilePlot.createPopupMenu().
void anl.verdi.plot.gui.FastTilePlot.processMouseEvent (MouseEvent me)
Definition at line 1103 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.isInDataArea(), and anl.verdi.plot.gui.FastTilePlot.showPopup().
void anl.verdi.plot.gui.FastTilePlot.processMouseMotionEvent (MouseEvent me)
Definition at line 1088 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.getLatLonFor(), anl.verdi.plot.gui.FastTilePlot.isInDataArea(), and anl.verdi.plot.gui.FastTilePlot.showLatLon.
void anl.verdi.plot.gui.FastTilePlot.removePlotListener (PlotListener listener)
Removes the specified PlotListener.
Parameters
listener the plot listener to remove
Implements anl.verdi.plot.gui.Plot.
Definition at line 2637 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.resetMenuItems (JMenu addLayers) protected
Definition at line 2175 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.resetRowsNColumns (int fRow, int lRow, int fColumn, int lColumn)
Definition at line 1040 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.columns, and anl.verdi.plot.gui.FastTilePlot.rows.
void anl.verdi.plot.gui.FastTilePlot.restoreCursor ()
Definition at line 3606 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.zoom.
void anl.verdi.plot.gui.FastTilePlot.setLayer (int layer)
Definition at line 1265 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.draw(), anl.verdi.plot.gui.FastTilePlot.firstLayer, anl.verdi.plot.gui.FastTilePlot.lastLayer, anl.verdi.plot.gui.FastTilePlot.layer, and anl.verdi.plot.gui.FastTilePlot.log.
Referenced by anl.verdi.plot.gui.FastTilePlot.stateChanged().
void anl.verdi.plot.gui.FastTilePlot.setLayerMapLine (VerdiBoundaries aVerdiBoundaries)
Definition at line 2267 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.setTimestep (int timestep)
Definition at line 1255 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.draw(), anl.verdi.plot.gui.FastTilePlot.firstTimestep, anl.verdi.plot.gui.FastTilePlot.lastTimestep, anl.verdi.plot.gui.FastTilePlot.log, and anl.verdi.plot.gui.FastTilePlot.timestep.
Referenced by anl.verdi.plot.gui.FastTilePlot.stateChanged().
void anl.verdi.plot.gui.FastTilePlot.showBusyCursor ()
Definition at line 3596 of file FastTilePlot.java.
References anl.verdi.core.VerdiApplication.getGui().
void anl.verdi.plot.gui.FastTilePlot.showPopup (MouseEvent me) protected
Definition at line 820 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.createPopupMenu(), and anl.verdi.plot.gui.FastTilePlot.zoom.
Referenced by anl.verdi.plot.gui.FastTilePlot.processMouseEvent().
void anl.verdi.plot.gui.FastTilePlot.stateChanged (ChangeEvent event)
Definition at line 1209 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.firstLayer, anl.verdi.plot.gui.FastTilePlot.firstTimestep, anl.verdi.plot.gui.FastTilePlot.lastLayer, anl.verdi.plot.gui.FastTilePlot.lastTimestep, anl.verdi.plot.gui.FastTilePlot.layer, anl.verdi.plot.gui.FastTilePlot.setLayer(), anl.verdi.plot.gui.FastTilePlot.setTimestep(), and anl.verdi.plot.gui.FastTilePlot.timestep.
Referenced by anl.verdi.plot.gui.FastTilePlot.FastTilePlot().
void anl.verdi.plot.gui.FastTilePlot.stopThread ()
Definition at line 793 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.draw().
void anl.verdi.plot.gui.FastTilePlot.updateTimeStep (int timestep)
Update this plot to the specified timestep.
Parameters
timestep the new timestep.
Implements anl.verdi.plot.types.TimeAnimatablePlot.
Definition at line 2929 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.firstTimestep, and anl.verdi.plot.gui.FastTilePlot.timestep.
void anl.verdi.plot.gui.FastTilePlot.viewClosed ()
Implements anl.verdi.plot.gui.Plot.
Definition at line 837 of file FastTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.config, anl.verdi.plot.gui.FastTilePlot.dataArea, anl.verdi.plot.gui.FastTilePlot.dataFrame, anl.verdi.plot.gui.FastTilePlot.dataFrameLog, anl.verdi.plot.gui.FastTilePlot.defaultPalette, anl.verdi.plot.gui.FastTilePlot.domain, anl.verdi.plot.gui.FastTilePlot.gridBounds, anl.verdi.plot.gui.FastTilePlot.legendLevels, anl.verdi.plot.gui.FastTilePlot.map, anl.verdi.plot.gui.FastTilePlot.minMax, anl.verdi.plot.gui.FastTilePlot.obsAnnotations, anl.verdi.plot.gui.FastTilePlot.obsData, anl.verdi.plot.gui.FastTilePlot.probedSlice, anl.verdi.plot.gui.FastTilePlot.probeItems, anl.verdi.plot.gui.FastTilePlot.showGridLines, anl.verdi.plot.gui.FastTilePlot.tilePlot, and anl.verdi.plot.gui.FastTilePlot.vectAnnotation.
void anl.verdi.plot.gui.FastTilePlot.viewFloated (DockableFrameEvent unused_)
Definition at line 879 of file FastTilePlot.java.
void anl.verdi.plot.gui.FastTilePlot.viewRestored (DockableFrameEvent unused_)
Definition at line 880 of file FastTilePlot.java.
Member Data Documentation
int anl.verdi.plot.gui.FastTilePlot.columnOrigin protected
Definition at line 202 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.FastTilePlot().
int anl.verdi.plot.gui.FastTilePlot.columns protected
Definition at line 200 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.computeDataRange(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.getAllLayerData(), anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar(), and anl.verdi.plot.gui.FastTilePlot.resetRowsNColumns().
PlotConfiguration anl.verdi.plot.gui.FastTilePlot.config protected
Definition at line 337 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.addObservationData(), anl.verdi.plot.gui.FastAreaTilePlot.configure(), anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastTilePlot.getMenuBar(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
Rectangle anl.verdi.plot.gui.FastTilePlot.dataArea = new Rectangle() protected
Definition at line 320 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.getLatLonFor(), anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar(), anl.verdi.plot.gui.FastTilePlot.isInDataArea(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
DataFrame anl.verdi.plot.gui.FastTilePlot.dataFrame protected
Definition at line 266 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.computeDataRange(), anl.verdi.plot.gui.FastAreaTilePlot.createTable(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
DataFrame anl.verdi.plot.gui.FastTilePlot.dataFrameLog protected
Definition at line 267 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.viewClosed().
Palette anl.verdi.plot.gui.FastTilePlot.defaultPalette protected
Definition at line 227 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), anl.verdi.plot.gui.FastAreaTilePlot.calculateAverageLevels(), anl.verdi.plot.gui.FastAreaTilePlot.calculateGridLevels(), anl.verdi.plot.gui.FastAreaTilePlot.calculateTotalLevels(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.init(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
double [][] anl.verdi.plot.gui.FastTilePlot.domain = { { 0.0, 0.0 }, { 0.0, 0.0 } } protected
Definition at line 256 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), anl.verdi.plot.gui.FastAreaTilePlot.FastAreaTilePlot(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
final Runnable anl.verdi.plot.gui.FastTilePlot.doubleBufferedRenderer
Definition at line 384 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.FastTilePlot().
int anl.verdi.plot.gui.FastTilePlot.firstLayer = 0 protected
Definition at line 218 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.getAllLayerData(), anl.verdi.plot.gui.FastTilePlot.getMinMaxPoints(), anl.verdi.plot.gui.FastTilePlot.setLayer(), and anl.verdi.plot.gui.FastTilePlot.stateChanged().
int anl.verdi.plot.gui.FastTilePlot.firstTimestep = 0 protected
Definition at line 215 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.getAllLayerData(), anl.verdi.plot.gui.FastTilePlot.getMinMaxPoints(), anl.verdi.plot.gui.FastTilePlot.setTimestep(), anl.verdi.plot.gui.FastTilePlot.stateChanged(), and anl.verdi.plot.gui.FastTilePlot.updateTimeStep().
double [][] anl.verdi.plot.gui.FastTilePlot.gridBounds = { { 0.0, 0.0 }, { 0.0, 0.0 } } protected
Definition at line 255 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), anl.verdi.plot.gui.FastAreaTilePlot.FastAreaTilePlot(), anl.verdi.plot.gui.FastTilePlot.getLatLonFor(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
int anl.verdi.plot.gui.FastTilePlot.lastLayer = 0 protected
Definition at line 219 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastTilePlot.setLayer(), and anl.verdi.plot.gui.FastTilePlot.stateChanged().
int anl.verdi.plot.gui.FastTilePlot.lastTimestep = 0 protected
Definition at line 216 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastTilePlot.setTimestep(), and anl.verdi.plot.gui.FastTilePlot.stateChanged().
int anl.verdi.plot.gui.FastTilePlot.layer = 0 protected
Definition at line 217 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.addObservationData(), anl.verdi.plot.gui.FastTilePlot.computeDataRange(), anl.verdi.plot.gui.FastAreaTilePlot.createTable(), anl.verdi.plot.gui.FastAreaTilePlot.createTableName(), anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.getAllLayerData(), anl.verdi.plot.gui.FastTilePlot.getMinMaxPoints(), anl.verdi.plot.gui.FastTilePlot.setLayer(), and anl.verdi.plot.gui.FastTilePlot.stateChanged().
int anl.verdi.plot.gui.FastTilePlot.layers protected
Definition at line 198 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.computeDataRange(), and anl.verdi.plot.gui.FastTilePlot.FastTilePlot().
double [] anl.verdi.plot.gui.FastTilePlot.legendLevels protected
Definition at line 225 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.setLegendLevels(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
boolean anl.verdi.plot.gui.FastTilePlot.log = false protected
Definition at line 188 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), anl.verdi.plot.gui.FastAreaTilePlot.calculateGridLevels(), anl.verdi.plot.gui.FastTilePlot.computeDataRange(), anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastTilePlot.setLayer(), and anl.verdi.plot.gui.FastTilePlot.setTimestep().
ColorMap anl.verdi.plot.gui.FastTilePlot.map protected
Definition at line 230 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), anl.verdi.plot.gui.FastAreaTilePlot.calculateAverageLevels(), anl.verdi.plot.gui.FastAreaTilePlot.calculateGridLevels(), anl.verdi.plot.gui.FastAreaTilePlot.calculateTotalLevels(), anl.verdi.plot.gui.FastTilePlot.configure(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.init(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
MinMax anl.verdi.plot.gui.FastTilePlot.minMax protected
Definition at line 336 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), anl.verdi.plot.gui.FastAreaTilePlot.calculateAverageLevels(), anl.verdi.plot.gui.FastAreaTilePlot.calculateGridLevels(), anl.verdi.plot.gui.FastAreaTilePlot.calculateTotalLevels(), anl.verdi.plot.gui.FastTilePlot.editChartProperties(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.init(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
final int anl.verdi.plot.gui.FastTilePlot.NO_VAL = Integer.MIN_VALUE static
Definition at line 161 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.formatPoint().
List<ObsAnnotation> anl.verdi.plot.gui.FastTilePlot.obsAnnotations protected
Definition at line 269 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.addObservationData(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
List<OverlayObject> anl.verdi.plot.gui.FastTilePlot.obsData = new ArrayList<OverlayObject>() protected
Definition at line 268 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.addObservationData(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
final String anl.verdi.plot.gui.FastTilePlot.PRINT_COMMAND = "PRINT" static
Definition at line 172 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), and anl.verdi.plot.gui.FastTilePlot.createPopupMenu().
boolean anl.verdi.plot.gui.FastTilePlot.probe = false protected
Definition at line 307 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar(), and anl.verdi.plot.gui.FastTilePlot.getMenuBar().
Slice anl.verdi.plot.gui.FastTilePlot.probedSlice protected
Definition at line 323 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.viewClosed().
java.util.List<JMenuItem> anl.verdi.plot.gui.FastTilePlot.probeItems = new ArrayList<JMenuItem>() protected
Definition at line 318 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.enableProbeItems(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
Projector anl.verdi.plot.gui.FastTilePlot.projector protected
Definition at line 253 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.FastAreaTilePlot(), and anl.verdi.plot.gui.FastTilePlot.FastTilePlot().
final String anl.verdi.plot.gui.FastTilePlot.PROPERTIES_COMMAND = "PROPERTIES" static
Definition at line 170 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), and anl.verdi.plot.gui.FastTilePlot.createPopupMenu().
int anl.verdi.plot.gui.FastTilePlot.rowOrigin protected
Definition at line 201 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.FastTilePlot().
int anl.verdi.plot.gui.FastTilePlot.rows protected
Definition at line 199 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.computeDataRange(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.getAllLayerData(), anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar(), and anl.verdi.plot.gui.FastTilePlot.resetRowsNColumns().
final Rubberband anl.verdi.plot.gui.FastTilePlot.rubberband = new Rubberband(this) protected
Definition at line 305 of file FastTilePlot.java.
final String anl.verdi.plot.gui.FastTilePlot.SAVE_COMMAND = "SAVE" static
Definition at line 171 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), and anl.verdi.plot.gui.FastTilePlot.createPopupMenu().
JCheckBoxMenuItem anl.verdi.plot.gui.FastTilePlot.showGridLines protected
Definition at line 324 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.configure(), anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), anl.verdi.plot.gui.FastTilePlot.getMenuBar(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
boolean anl.verdi.plot.gui.FastTilePlot.showLatLon = false protected
Definition at line 312 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.createAreaString(), anl.verdi.plot.gui.FastTilePlot.getMenuBar(), and anl.verdi.plot.gui.FastTilePlot.processMouseMotionEvent().
boolean anl.verdi.plot.gui.FastTilePlot.showObsLegend = false protected
Definition at line 313 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.addObservationData().
int anl.verdi.plot.gui.FastTilePlot.startDate protected
Definition at line 194 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.FastAreaTilePlot(), and anl.verdi.plot.gui.FastTilePlot.FastTilePlot().
int anl.verdi.plot.gui.FastTilePlot.startTime protected
Definition at line 195 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.FastAreaTilePlot(), and anl.verdi.plot.gui.FastTilePlot.FastTilePlot().
TilePlot anl.verdi.plot.gui.FastTilePlot.tilePlot protected
Definition at line 212 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.calculateAverageLevels(), anl.verdi.plot.gui.FastAreaTilePlot.calculateGridLevels(), anl.verdi.plot.gui.FastAreaTilePlot.calculateTotalLevels(), anl.verdi.plot.gui.FastTilePlot.configure(), anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.getTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.recalculateAreas(), anl.verdi.plot.gui.FastAreaTilePlot.showAverages(), anl.verdi.plot.gui.FastAreaTilePlot.showGrid(), anl.verdi.plot.gui.FastAreaTilePlot.showTotals(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
Action anl.verdi.plot.gui.FastTilePlot.timeSeriesBarSelected protected
Initial value:
= new AbstractAction(
            "Time Series Bar of Probed Cell(s)") {
        private static final long serialVersionUID = 2455217937515200807L;
        public void actionPerformed(ActionEvent e) {
            requestTimeSeries(Formula.Type.TIME_SERIES_BAR);
        }
    }
Definition at line 351 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.getMenuBar().
Action anl.verdi.plot.gui.FastTilePlot.timeSeriesMax protected
Initial value:
= new AbstractAction(
            "Time Series of Max. Cell(s)") {
        private static final long serialVersionUID = -4465758432397962782L;
        public void actionPerformed(ActionEvent e) {
            DataUtilities.MinMaxPoint points = getMinMaxPoints();
            requestTimeSeries(points.getMaxPoints(), "Max. cells ");
        }
    }
Definition at line 370 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.getMenuBar().
Action anl.verdi.plot.gui.FastTilePlot.timeSeriesMin protected
Initial value:
= new AbstractAction(
            "Time Series of Min. Cell(s)") {
        private static final long serialVersionUID = 5282480503103839989L;
        public void actionPerformed(ActionEvent e) {
            DataUtilities.MinMaxPoint points = getMinMaxPoints();
            requestTimeSeries(points.getMinPoints(), "Min. cells ");
        }
    }
Definition at line 360 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.getMenuBar().
Action anl.verdi.plot.gui.FastTilePlot.timeSeriesSelected protected
Initial value:
= new AbstractAction(
            "Time Series of Probed Cell(s)") {
        private static final long serialVersionUID = -2940008125642497962L;
        public void actionPerformed(ActionEvent e) {
            requestTimeSeries(Formula.Type.TIME_SERIES_LINE);
        }
    }
Definition at line 342 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.getMenuBar().
int anl.verdi.plot.gui.FastTilePlot.timestep = 0 protected
Definition at line 214 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), anl.verdi.plot.gui.FastTilePlot.addObservationData(), anl.verdi.plot.gui.FastTilePlot.addVectorAnnotation(), anl.verdi.plot.gui.FastTilePlot.computeDataRange(), anl.verdi.plot.gui.FastAreaTilePlot.createTable(), anl.verdi.plot.gui.FastAreaTilePlot.createTableName(), anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.gui.FastAreaTilePlot.getAllLayerData(), anl.verdi.plot.gui.FastTilePlot.getMinMaxPoints(), anl.verdi.plot.gui.FastTilePlot.setTimestep(), anl.verdi.plot.gui.FastTilePlot.stateChanged(), and anl.verdi.plot.gui.FastTilePlot.updateTimeStep().
int anl.verdi.plot.gui.FastTilePlot.timesteps protected
Definition at line 197 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.computeDataRange(), and anl.verdi.plot.gui.FastTilePlot.FastTilePlot().
int anl.verdi.plot.gui.FastTilePlot.timestepSize protected
Definition at line 196 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.FastAreaTilePlot(), and anl.verdi.plot.gui.FastTilePlot.FastTilePlot().
String anl.verdi.plot.gui.FastTilePlot.units protected
Definition at line 259 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), and anl.verdi.plot.gui.FastAreaTilePlot.processMouseMotionEvent().
VectorAnnotation anl.verdi.plot.gui.FastTilePlot.vectAnnotation protected
Definition at line 270 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.addVectorAnnotation(), and anl.verdi.plot.gui.FastTilePlot.viewClosed().
boolean anl.verdi.plot.gui.FastTilePlot.zoom = true protected
Definition at line 306 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar(), anl.verdi.plot.gui.FastTilePlot.getMenuBar(), anl.verdi.plot.gui.FastTilePlot.restoreCursor(), and anl.verdi.plot.gui.FastTilePlot.showPopup().
final String anl.verdi.plot.gui.FastTilePlot.ZOOM_IN_BOTH_COMMAND = "ZOOM_IN_BOTH" static
Definition at line 173 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), and anl.verdi.plot.gui.FastTilePlot.createPopupMenu().
final String anl.verdi.plot.gui.FastTilePlot.ZOOM_OUT_BOTH_COMMAND = "ZOOM_OUT_BOTH" static
Definition at line 174 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), and anl.verdi.plot.gui.FastTilePlot.createPopupMenu().
final String anl.verdi.plot.gui.FastTilePlot.ZOOM_OUT_MAX_COMMAND = "ZOOM_OUT_MAX" static
Definition at line 175 of file FastTilePlot.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), and anl.verdi.plot.gui.FastTilePlot.createPopupMenu().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/gui/FastTilePlot.java