VERDI: anl.verdi.loaders.CSVCoordAxis Class Reference
anl.verdi.loaders.CSVCoordAxis Class Reference
Public Member Functions
CSVCoordAxis (Double data[], String name, String description, AxisType type)
double getValue (int index)
Unit getUnits ()
boolean isCompatible (CoordAxis axis)
String getDescription ()
String getName ()
Range getRange ()
AxisType getAxisType ()
Protected Attributes
String name
Double data []
Detailed Description
CoordAxis that can be built from net cdf specific variables.
Author
Nick Collier
Eric Tatara
Version
$Revision$ $Date$
Definition at line 21 of file CSVCoordAxis.java.
Constructor & Destructor Documentation
anl.verdi.loaders.CSVCoordAxis.CSVCoordAxis (Double data[], String name, String description, AxisType type)
Definition at line 30 of file CSVCoordAxis.java.
References anl.verdi.loaders.CSVCoordAxis.data, anl.verdi.util.VUnits.MISSING_UNIT, and anl.verdi.loaders.CSVCoordAxis.name.
Member Function Documentation
AxisType anl.verdi.loaders.CSVCoordAxis.getAxisType ()
Gets the type of this axis.
Returns
the type of this axis.
Implements anl.verdi.data.CoordAxis.
Definition at line 117 of file CSVCoordAxis.java.
String anl.verdi.loaders.CSVCoordAxis.getDescription ()
Gets the description of this CoordAxis.
Returns
the description of this CoordAxis.
Implements anl.verdi.data.CoordAxis.
Definition at line 89 of file CSVCoordAxis.java.
String anl.verdi.loaders.CSVCoordAxis.getName ()
Gets the name of this CoordAxis.
Returns
the name of this CoordAxis.
Implements anl.verdi.data.CoordAxis.
Definition at line 98 of file CSVCoordAxis.java.
References anl.verdi.loaders.CSVCoordAxis.name.
Range anl.verdi.loaders.CSVCoordAxis.getRange ()
Gets the range of this axis.
Returns
the range of this axis.
Implements anl.verdi.data.CoordAxis.
Definition at line 107 of file CSVCoordAxis.java.
Unit anl.verdi.loaders.CSVCoordAxis.getUnits ()
Gets the unit of measurement for this coordinate axis.
Returns
the unit of measurement for this coordinate axis.
Implements anl.verdi.data.CoordAxis.
Definition at line 55 of file CSVCoordAxis.java.
double anl.verdi.loaders.CSVCoordAxis.getValue (int index)
Gets the value at the specified index.
Returns
the value at the specified index.
Implements anl.verdi.data.CoordAxis.
Definition at line 45 of file CSVCoordAxis.java.
References anl.verdi.loaders.CSVCoordAxis.data.
Referenced by anl.verdi.loaders.CSVCoordAxis.isCompatible().
boolean anl.verdi.loaders.CSVCoordAxis.isCompatible (CoordAxis axis)
Gets whether or not the this axis is compatible with the specified axis. Two axes are compatible if they can be used together in the same formula.
Parameters
axis the axis to check for compatibility
Returns
true if this axis is compatibility with the other axis, Otherwise false.
Implements anl.verdi.data.CoordAxis.
Definition at line 70 of file CSVCoordAxis.java.
References anl.verdi.data.CoordAxis.getAxisType(), and anl.verdi.loaders.CSVCoordAxis.getValue().
Member Data Documentation
Double anl.verdi.loaders.CSVCoordAxis.data[] protected
Definition at line 28 of file CSVCoordAxis.java.
Referenced by anl.verdi.loaders.CSVCoordAxis.CSVCoordAxis(), anl.verdi.loaders.CSVTimeAxis.getDate(), anl.verdi.loaders.CSVTimeAxis.getTimeStep(), and anl.verdi.loaders.CSVCoordAxis.getValue().
String anl.verdi.loaders.CSVCoordAxis.name protected
Definition at line 27 of file CSVCoordAxis.java.
Referenced by anl.verdi.loaders.CSVCoordAxis.CSVCoordAxis(), and anl.verdi.loaders.CSVCoordAxis.getName().
The documentation for this class was generated from the following file:
verdi_data_loaders/src/anl/verdi/loaders/CSVCoordAxis.java