VERDI: gov.epa.emvl.TilePlot Class Reference
gov.epa.emvl.TilePlot Class Reference
Public Member Functions
TilePlot (int startDate, int startTime, int timestepSize)
void setObsLegend (List< ObsAnnotation > obsAnnot, boolean showLegend)
synchronized void draw (final Graphics graphics, int xOffset, int yOffset, int width, int height, int steplapse, int layer, int firstRow, int lastRow, int firstColumn, int lastColumn, final double[] legendLevels, final Color[] legendColors, final Color axisColor, final Color labelColor, final String variable, final String units, PlotConfiguration config, NumberFormat format, final Color gridLineColor, final float[][] data)
synchronized void drawBatchImage (final Graphics graphics, int xOffset, int yOffset, int canvasWidth, int canvasHeight, int steplapse, int layer, int firstRow, int lastRow, int firstColumn, int lastColumn, final double[] legendLevels, final Color[] legendColors, final Color axisColor, final Color labelColor, final String variable, final String units, PlotConfiguration config, NumberFormat format, final Color gridLineColor, final float[][] data)
int getFootnoteHeight (final Graphics graphics)
int getLegendWidth (final Graphics graphics, final double[] legendLevels, final Color[] legendColors, final String units)
void drawGridCells (final Graphics graphics, int xMinimum, int xMaximum, int yMinimum, int yMaximum, int firstRow, int lastRow, int firstColumn, int lastColumn, final double[] legendLevels, final Color[] legendColors, final float[][] data)
void drawGridLines (final Graphics graphics, int xMinimum, int xMaximum, int yMinimum, int yMaximum, int firstRow, int lastRow, int firstColumn, int lastColumn, final Color gridLineColor)
PlotConfiguration getPlotConfiguration ()
String getTitle ()
void setLog (boolean log)
boolean isLog ()
void setLogBase (int logBase)
double getLogBase ()
int getPlotWidth ()
int getPlotHeight ()
Protected Member Functions
void drawGridBoundary (final Graphics graphics, int xMinimum, int xMaximum, int yMinimum, int yMaximum)
void drawAxis (final Graphics graphics, int xMinimum, int xMaximum, int yMinimum, int yMaximum, int firstRow, int lastRow, int firstColumn, int lastColumn)
void drawLabels (final Graphics graphics, Color labelColor, int xMinimum, int xMaximum, int yMinimum, int yMaximum, final String variable, int steplapse, int layer, int firstRow, int lastRow, int firstColumn, int lastColumn, final float[][] data)
void drawLegend (final Graphics graphics, int xMaximum, int yMinimum, int yMaximum, final double[] legendLevels, final Color[] legendColors, final String units)
Protected Attributes
PlotConfiguration config
NumberFormat numberFormat
Detailed Description
Invariant
startDate >= 1900001
startTime >= 0
timestepSize > 0
layers > 0
rows > 0
columns > 0
! Numerics.isNan(xMinimum)
! Numerics.isNan(yMinimum)
! Numerics.isNan(cellWidth)
! Numerics.isNan(cellHeight)
! Numerics.isNan(xMaximum)
! Numerics.isNan(yMaximum)
xMinimum > -1e30
yMinimum > -1e30
cellWidth >= 1.0
cellHeight >= 1.0
xMaximum = xMinimum + columns * cellWidth
yMaximum = yMinimum + rows * cellHeight
Definition at line 57 of file TilePlot.java.
Constructor & Destructor Documentation
gov.epa.emvl.TilePlot.TilePlot (int startDate, int startTime, int timestepSize)
Constructor - inputs 2D grid parameters.
Precondition
startDate >= 1900001
startTime >= 0
timestepSize > 0
Definition at line 95 of file TilePlot.java.
Member Function Documentation
synchronized void gov.epa.emvl.TilePlot.draw (final Graphics graphics, int xOffset, int yOffset, int width, int height, int steplapse, int layer, int firstRow, int lastRow, int firstColumn, int lastColumn, final double[] legendLevels, final Color[] legendColors, final Color axisColor, final Color labelColor, final String variable, final String units, PlotConfiguration config, NumberFormat format, final Color gridLineColor, final float data[][])
draw - Draw a tile plot: colored rectangles with labels and legend.
Parameters
numberFormat
Precondition
graphics != null
xOffset > 0
xOffset < width
yOffset > 0
yOffset < height
width > 0
width < 5000
height > 0
height < 5000
timestep >= 0
layer >= 0
firstRow >= 0
firstRow <= lastRow
firstColumn >= 0
firstColumn <= lastColumn
legendLevels != null
legendLevels.length >= 2
legendColors != null
legendColors.length == legendLevels.length - 1
axisColor != null
labelColor != null
variable != null
units != null
data != null
data.length == (1 + lastRow - firstRow) * (1 + lastColumn-firstColumn)
Definition at line 138 of file TilePlot.java.
References gov.epa.emvl.TilePlot.config, gov.epa.emvl.TilePlot.drawAxis(), gov.epa.emvl.TilePlot.drawGridBoundary(), gov.epa.emvl.TilePlot.drawGridCells(), gov.epa.emvl.TilePlot.drawGridLines(), gov.epa.emvl.TilePlot.drawLabels(), and gov.epa.emvl.TilePlot.drawLegend().
void gov.epa.emvl.TilePlot.drawAxis (final Graphics graphics, int xMinimum, int xMaximum, int yMinimum, int yMaximum, int firstRow, int lastRow, int firstColumn, int lastColumn) protected
drawAxis - draw row/column axis with tic marks and text labels.
Precondition
graphics != null
xMinimum > 0
yMinimum > 0
xMaximum > xMinimum
yMaximum > yMinimum
xMaximum < 5000
yMaximum < 5000
firstRow >= 0
firstRow <= lastRow
firstColumn >= 0
firstColumn <= lastColumn
Definition at line 299 of file TilePlot.java.
References gov.epa.emvl.TilePlot.config, anl.verdi.plot.config.PlotConfiguration.DOMAIN_COLOR, anl.verdi.plot.config.PlotConfiguration.DOMAIN_FONT, anl.verdi.plot.config.PlotConfiguration.DOMAIN_LABEL, anl.verdi.plot.config.PlotConfiguration.DOMAIN_SHOW_TICK, anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_COLOR, anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_FONT, anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_NUMBER, anl.verdi.plot.config.PlotConfiguration.getObject(), anl.verdi.plot.config.PlotConfiguration.RANGE_COLOR, anl.verdi.plot.config.PlotConfiguration.RANGE_FONT, anl.verdi.plot.config.PlotConfiguration.RANGE_LABEL, anl.verdi.plot.config.PlotConfiguration.RANGE_SHOW_TICK, anl.verdi.plot.config.PlotConfiguration.RANGE_TICK_COLOR, anl.verdi.plot.config.PlotConfiguration.RANGE_TICK_FONT, and anl.verdi.plot.config.PlotConfiguration.RANGE_TICK_NUMBER.
Referenced by anl.verdi.area.AreaTilePlot.draw(), gov.epa.emvl.TilePlot.draw(), and gov.epa.emvl.TilePlot.drawBatchImage().
synchronized void gov.epa.emvl.TilePlot.drawBatchImage (final Graphics graphics, int xOffset, int yOffset, int canvasWidth, int canvasHeight, int steplapse, int layer, int firstRow, int lastRow, int firstColumn, int lastColumn, final double[] legendLevels, final Color[] legendColors, final Color axisColor, final Color labelColor, final String variable, final String units, PlotConfiguration config, NumberFormat format, final Color gridLineColor, final float data[][])
Definition at line 195 of file TilePlot.java.
References gov.epa.emvl.TilePlot.config, gov.epa.emvl.TilePlot.drawAxis(), gov.epa.emvl.TilePlot.drawGridBoundary(), gov.epa.emvl.TilePlot.drawGridCells(), gov.epa.emvl.TilePlot.drawGridLines(), gov.epa.emvl.TilePlot.drawLabels(), gov.epa.emvl.TilePlot.drawLegend(), gov.epa.emvl.TilePlot.getFootnoteHeight(), and gov.epa.emvl.TilePlot.getLegendWidth().
void gov.epa.emvl.TilePlot.drawGridBoundary (final Graphics graphics, int xMinimum, int xMaximum, int yMinimum, int yMaximum) protected
drawGridBoundary - draw grid boundary (edges).
Precondition
graphics != null
xMinimum > 0
yMinimum > 0
xMaximum > xMinimum
yMaximum > yMinimum
xMaximum < 5000
yMaximum < 5000
Definition at line 274 of file TilePlot.java.
Referenced by anl.verdi.area.AreaTilePlot.draw(), gov.epa.emvl.TilePlot.draw(), and gov.epa.emvl.TilePlot.drawBatchImage().
void gov.epa.emvl.TilePlot.drawGridCells (final Graphics graphics, int xMinimum, int xMaximum, int yMinimum, int yMaximum, int firstRow, int lastRow, int firstColumn, int lastColumn, final double[] legendLevels, final Color[] legendColors, final float data[][])
drawGridCells - draw colored rectangles of the grid cells.
Precondition
graphics != null
xMinimum > 0
yMinimum > 0
xMaximum > xMinimum
yMaximum > yMinimum
xMaximum < 5000
yMaximum < 5000
firstRow >= 0
firstRow <= lastRow
firstColumn >= 0
firstColumn <= lastColumn
firstRow >= 0
firstRow <= lastRow
firstColumn >= 0
firstColumn <= lastColumn
legendLevels != null
legendLevels.length >= 2
legendColors != null
legendColors.length == legendLevels.length - 1
data != null
data.length == (1 + lastRow - firstRow) * (1 + lastColumn-firstColumn)
Definition at line 996 of file TilePlot.java.
Referenced by anl.verdi.area.AreaTilePlot.draw(), gov.epa.emvl.TilePlot.draw(), and gov.epa.emvl.TilePlot.drawBatchImage().
void gov.epa.emvl.TilePlot.drawGridLines (final Graphics graphics, int xMinimum, int xMaximum, int yMinimum, int yMaximum, int firstRow, int lastRow, int firstColumn, int lastColumn, final Color gridLineColor)
drawGridLines - draw grid lines.
Precondition
graphics != null
xMinimum > 0
yMinimum > 0
xMaximum > xMinimum
yMaximum > yMinimum
xMaximum < 5000
yMaximum < 5000
firstRow >= 0
firstRow <= lastRow
firstColumn >= 0
firstColumn <= lastColumn
firstRow >= 0
firstRow <= lastRow
firstColumn >= 0
firstColumn <= lastColumn
gridLineColor != null
Definition at line 1109 of file TilePlot.java.
Referenced by anl.verdi.area.AreaTilePlot.draw(), gov.epa.emvl.TilePlot.draw(), and gov.epa.emvl.TilePlot.drawBatchImage().
void gov.epa.emvl.TilePlot.drawLabels (final Graphics graphics, Color labelColor, int xMinimum, int xMaximum, int yMinimum, int yMaximum, final String variable, int steplapse, int layer, int firstRow, int lastRow, int firstColumn, int lastColumn, final float data[][]) protected
drawLabels - draw text label annotations.
Parameters
labelColor
Precondition
graphics != null
xMinimum > 0
yMinimum > 0
xMaximum > xMinimum
yMaximum > yMinimum
xMaximum < 5000
yMaximum < 5000
variable != null
timestep >= 0
layer >= 0
firstRow >= 0
firstRow <= lastRow
firstColumn >= 0
firstColumn <= lastColumn
data != null
data.length == (1 + lastRow - firstRow) * (1 + lastColumn-firstColumn)
Definition at line 520 of file TilePlot.java.
References gov.epa.emvl.TilePlot.config, anl.verdi.plot.config.PlotConfiguration.FOOTER1, anl.verdi.plot.config.PlotConfiguration.FOOTER1_AUTO_TEXT, anl.verdi.plot.config.PlotConfiguration.FOOTER1_COLOR, anl.verdi.plot.config.PlotConfiguration.FOOTER1_FONT, anl.verdi.plot.config.PlotConfiguration.FOOTER1_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.FOOTER2, anl.verdi.plot.config.PlotConfiguration.FOOTER2_AUTO_TEXT, anl.verdi.plot.config.PlotConfiguration.FOOTER2_COLOR, anl.verdi.plot.config.PlotConfiguration.FOOTER2_FONT, anl.verdi.plot.config.PlotConfiguration.FOOTER2_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.getObject(), anl.verdi.plot.config.PlotConfiguration.OBS_LEGEND_COLOR, anl.verdi.plot.config.PlotConfiguration.OBS_LEGEND_FONT, anl.verdi.plot.config.PlotConfiguration.OBS_SHOW_LEGEND, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_FONT, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_FONT, anl.verdi.plot.config.PlotConfiguration.TITLE, anl.verdi.plot.config.PlotConfiguration.TITLE_COLOR, and anl.verdi.plot.config.PlotConfiguration.TITLE_FONT.
Referenced by anl.verdi.area.AreaTilePlot.draw(), gov.epa.emvl.TilePlot.draw(), and gov.epa.emvl.TilePlot.drawBatchImage().
void gov.epa.emvl.TilePlot.drawLegend (final Graphics graphics, int xMaximum, int yMinimum, int yMaximum, final double[] legendLevels, final Color[] legendColors, final String units) protected
drawLegend - draw colorbar with text labels.
Precondition
graphics != null
yMinimum > 0
yMaximum > yMinimum
xMaximum < 5000
yMaximum < 5000
legendLevels != null
legendLevels.length >= 2
legendColors != null
legendColors.length == legendLevels.length - 1
units != null
Definition at line 807 of file TilePlot.java.
References gov.epa.emvl.TilePlot.config, anl.verdi.plot.config.PlotConfiguration.getObject(), anl.verdi.plot.config.PlotConfiguration.LEGEND_SHOW, anl.verdi.plot.config.PlotConfiguration.UNITS, anl.verdi.plot.config.PlotConfiguration.UNITS_COLOR, anl.verdi.plot.config.PlotConfiguration.UNITS_FONT, anl.verdi.plot.config.PlotConfiguration.UNITS_SHOW_TICK, anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_COLOR, anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_FONT, and anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_NUMBER.
Referenced by anl.verdi.area.AreaTilePlot.draw(), gov.epa.emvl.TilePlot.draw(), and gov.epa.emvl.TilePlot.drawBatchImage().
int gov.epa.emvl.TilePlot.getFootnoteHeight (final Graphics graphics)
Definition at line 448 of file TilePlot.java.
References gov.epa.emvl.TilePlot.config, anl.verdi.plot.config.PlotConfiguration.DOMAIN_FONT, anl.verdi.plot.config.PlotConfiguration.DOMAIN_LABEL, anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_FONT, anl.verdi.plot.config.PlotConfiguration.FOOTER1_FONT, anl.verdi.plot.config.PlotConfiguration.FOOTER1_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.FOOTER2_FONT, anl.verdi.plot.config.PlotConfiguration.FOOTER2_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.getObject(), anl.verdi.plot.config.PlotConfiguration.OBS_LEGEND_FONT, and anl.verdi.plot.config.PlotConfiguration.OBS_SHOW_LEGEND.
Referenced by gov.epa.emvl.TilePlot.drawBatchImage().
int gov.epa.emvl.TilePlot.getLegendWidth (final Graphics graphics, final double[] legendLevels, final Color[] legendColors, final String units)
Definition at line 759 of file TilePlot.java.
References gov.epa.emvl.TilePlot.config, anl.verdi.plot.config.PlotConfiguration.getObject(), anl.verdi.plot.config.PlotConfiguration.UNITS_FONT, anl.verdi.plot.config.PlotConfiguration.UNITS_SHOW_TICK, and anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_FONT.
Referenced by gov.epa.emvl.TilePlot.drawBatchImage().
double gov.epa.emvl.TilePlot.getLogBase ()
Definition at line 1407 of file TilePlot.java.
PlotConfiguration gov.epa.emvl.TilePlot.getPlotConfiguration ()
Definition at line 1387 of file TilePlot.java.
int gov.epa.emvl.TilePlot.getPlotHeight ()
Definition at line 1415 of file TilePlot.java.
int gov.epa.emvl.TilePlot.getPlotWidth ()
Definition at line 1411 of file TilePlot.java.
String gov.epa.emvl.TilePlot.getTitle ()
Definition at line 1391 of file TilePlot.java.
boolean gov.epa.emvl.TilePlot.isLog ()
Definition at line 1399 of file TilePlot.java.
void gov.epa.emvl.TilePlot.setLog (boolean log)
Definition at line 1395 of file TilePlot.java.
void gov.epa.emvl.TilePlot.setLogBase (int logBase)
Definition at line 1403 of file TilePlot.java.
void gov.epa.emvl.TilePlot.setObsLegend (List< ObsAnnotation > obsAnnot, boolean showLegend)
Definition at line 101 of file TilePlot.java.
Member Data Documentation
PlotConfiguration gov.epa.emvl.TilePlot.config protected
Definition at line 71 of file TilePlot.java.
Referenced by anl.verdi.area.AreaTilePlot.draw(), gov.epa.emvl.TilePlot.draw(), gov.epa.emvl.TilePlot.drawAxis(), gov.epa.emvl.TilePlot.drawBatchImage(), gov.epa.emvl.TilePlot.drawLabels(), gov.epa.emvl.TilePlot.drawLegend(), gov.epa.emvl.TilePlot.getFootnoteHeight(), and gov.epa.emvl.TilePlot.getLegendWidth().
NumberFormat gov.epa.emvl.TilePlot.numberFormat protected
Definition at line 72 of file TilePlot.java.
The documentation for this class was generated from the following file:
verdi_core/src/gov/epa/emvl/TilePlot.java