VERDI: anl.verdi.plot.gui.AbstractPlotRequest Class Reference
anl.verdi.plot.gui.AbstractPlotRequest Class Reference abstract
Public Member Functions
void init (VerdiApplication app)
Plot createPlot ()
abstract Plot doCreatePlot ()
Protected Member Functions
void preCreatePlot ()
void postCreatePlot ()
Protected Attributes
VerdiApplication app
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 12 of file AbstractPlotRequest.java.
Member Function Documentation
Plot anl.verdi.plot.gui.AbstractPlotRequest.createPlot ()
Creates the plot.
Implements anl.verdi.plot.gui.PlotCreator.
Definition at line 30 of file AbstractPlotRequest.java.
References anl.verdi.plot.gui.AbstractPlotRequest.doCreatePlot(), anl.verdi.plot.gui.AbstractPlotRequest.postCreatePlot(), and anl.verdi.plot.gui.AbstractPlotRequest.preCreatePlot().
abstract Plot anl.verdi.plot.gui.AbstractPlotRequest.doCreatePlot () abstract
Perform the actual plot creation.
Referenced by anl.verdi.plot.gui.AbstractPlotRequest.createPlot().
void anl.verdi.plot.gui.AbstractPlotRequest.init (VerdiApplication app)
Initializes this PlotRequest with the specified application.
Parameters
app the application object
Implements anl.verdi.plot.gui.PlotRequest.
Definition at line 22 of file AbstractPlotRequest.java.
References anl.verdi.plot.gui.AbstractPlotRequest.app.
void anl.verdi.plot.gui.AbstractPlotRequest.postCreatePlot () protected
Definition at line 47 of file AbstractPlotRequest.java.
Referenced by anl.verdi.plot.gui.AbstractPlotRequest.createPlot().
void anl.verdi.plot.gui.AbstractPlotRequest.preCreatePlot () protected
Definition at line 41 of file AbstractPlotRequest.java.
Referenced by anl.verdi.plot.gui.AbstractPlotRequest.createPlot().
Member Data Documentation
VerdiApplication anl.verdi.plot.gui.AbstractPlotRequest.app protected
Definition at line 14 of file AbstractPlotRequest.java.
Referenced by anl.verdi.plot.gui.MultiTimeSeriesPlotRequest.doCreatePlot(), anl.verdi.plot.gui.TimeSeriesPlotRequest.doCreatePlot(), and anl.verdi.plot.gui.AbstractPlotRequest.init().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/gui/AbstractPlotRequest.java