VERDI: org.libtiff.jai.codecimpl.XTIFFFaxDecoder Class Reference
org.libtiff.jai.codecimpl.XTIFFFaxDecoder Class Reference
Public Member Functions
XTIFFFaxDecoder (int fillOrder, int w, int h)
void decode1D (byte[] buffer, byte[] compData, int startX, int height)
void decodeNextScanline (byte[] buffer, int lineOffset, int bitOffset)
void decode2D (byte[] buffer, byte compData[], int startX, int height, long tiffT4Options)
synchronized void decodeT6 (byte[] buffer, byte[] compData, int startX, int height, long tiffT6Options)
Detailed Description
Definition at line 30 of file XTIFFFaxDecoder.java.
Constructor & Destructor Documentation
org.libtiff.jai.codecimpl.XTIFFFaxDecoder.XTIFFFaxDecoder (int fillOrder, int w, int h)
Parameters
fillOrder The fill order of the compressed data bytes.
compData Array containing compressed data.
w
h
Definition at line 543 of file XTIFFFaxDecoder.java.
Member Function Documentation
void org.libtiff.jai.codecimpl.XTIFFFaxDecoder.decode1D (byte[] buffer, byte[] compData, int startX, int height)
Definition at line 556 of file XTIFFFaxDecoder.java.
References org.libtiff.jai.codecimpl.XTIFFFaxDecoder.decodeNextScanline().
void org.libtiff.jai.codecimpl.XTIFFFaxDecoder.decode2D (byte[] buffer, byte compData[], int startX, int height, long tiffT4Options)
Definition at line 710 of file XTIFFFaxDecoder.java.
References org.libtiff.jai.codecimpl.XTIFFFaxDecoder.decodeNextScanline(), and org.libtiff.jai.util.JaiI18N.getString().
void org.libtiff.jai.codecimpl.XTIFFFaxDecoder.decodeNextScanline (byte[] buffer, int lineOffset, int bitOffset)
Definition at line 571 of file XTIFFFaxDecoder.java.
References org.libtiff.jai.util.JaiI18N.getString().
Referenced by org.libtiff.jai.codecimpl.XTIFFFaxDecoder.decode1D(), and org.libtiff.jai.codecimpl.XTIFFFaxDecoder.decode2D().
synchronized void org.libtiff.jai.codecimpl.XTIFFFaxDecoder.decodeT6 (byte[] buffer, byte[] compData, int startX, int height, long tiffT6Options)
Definition at line 858 of file XTIFFFaxDecoder.java.
References org.libtiff.jai.util.JaiI18N.getString().
The documentation for this class was generated from the following file:
verdi_core/src/org/libtiff/jai/codecimpl/XTIFFFaxDecoder.java