VERDI: anl.verdi.gui.OKWindow Class Reference
anl.verdi.gui.OKWindow Class Reference
Public Member Functions
OKWindow (Dialog fr, String title, boolean state)
OKWindow (Frame fr, String title, boolean state)
OKWindow (Frame fr, String title, boolean state, String[] buttons)
void actionPerformed (ActionEvent event)
void addPrintButton ()
void busy ()
boolean doAction ()
void doPrint ()
Frame getParentFrame ()
void notBusy ()
void oKAction ()
void centerOver (Component comp)
void setEnabled (boolean state)
void windowActivated (WindowEvent e)
void windowClosed (WindowEvent e)
void windowClosing (WindowEvent e)
void windowDeactivated (WindowEvent e)
void windowDeiconified (WindowEvent e)
void windowIconified (WindowEvent e)
void windowOpened (WindowEvent e)
Public Member Functions inherited from anl.verdi.gui.ExtendedDialog
ExtendedDialog (Frame owner) throws HeadlessException
ExtendedDialog (Frame owner, boolean modal) throws HeadlessException
ExtendedDialog (Frame owner, String title) throws HeadlessException
ExtendedDialog (Frame owner, String title, boolean modal) throws HeadlessException
ExtendedDialog (Frame owner, String title, boolean modal, GraphicsConfiguration gc)
void show ()
Static Public Member Functions
static void setChildrenEnabled (Component item, boolean state)
Static Public Member Functions inherited from anl.verdi.gui.ExtendedDialog
static void setDefaultParent (Frame win)
static Frame getDefaultParent ()
Protected Attributes
JPanel buttonPanel
Frame parentFrame
Detailed Description
A dialog window that contains an OK button.
Version
1.0 May 1997
Author
Mary Ann Bitz, ANL
Definition at line 64 of file OKWindow.java.
Constructor & Destructor Documentation
anl.verdi.gui.OKWindow.OKWindow (Dialog fr, String title, boolean state)
Definition at line 77 of file OKWindow.java.
References anl.verdi.gui.OKWindow.buttonPanel.
anl.verdi.gui.OKWindow.OKWindow (Frame fr, String title, boolean state)
Constructs an OKWindow beneath the given window, with the indicated title and modality
Parameters
fr parent frame of this window
title title of this window
state whether the window should be modal
Definition at line 99 of file OKWindow.java.
References anl.verdi.gui.OKWindow.buttonPanel, and anl.verdi.gui.OKWindow.parentFrame.
anl.verdi.gui.OKWindow.OKWindow (Frame fr, String title, boolean state, String[] buttons)
Constructs an OKWindow beneath the given window, with the indicated title and modality
Parameters
fr parent frame of this window
title title of this window
state whether the window should be modal
Definition at line 135 of file OKWindow.java.
References anl.verdi.gui.OKWindow.buttonPanel, and anl.verdi.gui.OKWindow.parentFrame.
Member Function Documentation
void anl.verdi.gui.OKWindow.actionPerformed (ActionEvent event)
Event handler that is called when a button is pressed.
Definition at line 174 of file OKWindow.java.
References anl.verdi.gui.OKWindow.doPrint(), and anl.verdi.gui.OKWindow.oKAction().
void anl.verdi.gui.OKWindow.addPrintButton ()
Definition at line 185 of file OKWindow.java.
References anl.verdi.gui.OKWindow.buttonPanel.
void anl.verdi.gui.OKWindow.busy ()
Definition at line 188 of file OKWindow.java.
void anl.verdi.gui.OKWindow.centerOver (Component comp)
Definition at line 232 of file OKWindow.java.
boolean anl.verdi.gui.OKWindow.doAction ()
Method called when a button is pressed indicating the action should be performed. Should be defined for all subclasses.
Definition at line 200 of file OKWindow.java.
Referenced by anl.verdi.gui.OKWindow.oKAction().
void anl.verdi.gui.OKWindow.doPrint ()
Definition at line 203 of file OKWindow.java.
Referenced by anl.verdi.gui.OKWindow.actionPerformed().
Frame anl.verdi.gui.OKWindow.getParentFrame ()
Definition at line 204 of file OKWindow.java.
References anl.verdi.gui.OKWindow.parentFrame.
void anl.verdi.gui.OKWindow.notBusy ()
Definition at line 207 of file OKWindow.java.
void anl.verdi.gui.OKWindow.oKAction ()
Method called when the OK button is pressed indicating the action should be performed, and the window should be disposed.
Definition at line 216 of file OKWindow.java.
References anl.verdi.gui.OKWindow.doAction().
Referenced by anl.verdi.gui.OKWindow.actionPerformed().
static void anl.verdi.gui.OKWindow.setChildrenEnabled (Component item, boolean state) static
Definition at line 219 of file OKWindow.java.
Referenced by anl.verdi.gui.OKWindow.setEnabled().
void anl.verdi.gui.OKWindow.setEnabled (boolean state)
Redefined setEnabled to change the contents of the window Allows the window to still be moved around
Parameters
state whether it is enabled or not
Definition at line 245 of file OKWindow.java.
References anl.verdi.gui.OKWindow.setChildrenEnabled().
void anl.verdi.gui.OKWindow.windowActivated (WindowEvent e)
Definition at line 250 of file OKWindow.java.
Referenced by anl.verdi.gui.HelpWindowWithContents.inits().
void anl.verdi.gui.OKWindow.windowClosed (WindowEvent e)
Definition at line 251 of file OKWindow.java.
void anl.verdi.gui.OKWindow.windowClosing (WindowEvent e)
Definition at line 252 of file OKWindow.java.
Referenced by anl.verdi.gui.HelpWindowWithContents.inits().
void anl.verdi.gui.OKWindow.windowDeactivated (WindowEvent e)
Definition at line 253 of file OKWindow.java.
void anl.verdi.gui.OKWindow.windowDeiconified (WindowEvent e)
Definition at line 254 of file OKWindow.java.
void anl.verdi.gui.OKWindow.windowIconified (WindowEvent e)
Definition at line 255 of file OKWindow.java.
void anl.verdi.gui.OKWindow.windowOpened (WindowEvent e)
Definition at line 256 of file OKWindow.java.
Member Data Documentation
JPanel anl.verdi.gui.OKWindow.buttonPanel protected
The panel in it that contains the button.
Definition at line 72 of file OKWindow.java.
Referenced by anl.verdi.gui.OKWindow.addPrintButton(), and anl.verdi.gui.OKWindow.OKWindow().
Frame anl.verdi.gui.OKWindow.parentFrame protected
Definition at line 73 of file OKWindow.java.
Referenced by anl.verdi.gui.OKWindow.getParentFrame(), and anl.verdi.gui.OKWindow.OKWindow().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/gui/OKWindow.java