VERDI: anl.verdi.plot.gui.PlotFactory Class Reference
anl.verdi.plot.gui.PlotFactory Class Reference
Public Member Functions
PlotPanel getScatterPlot (String xFormula, String yFormula, DataFrame xFrame, DataFrame yFrame)
PlotPanel getPlot (Formula.Type type, String formula, DataFrame frame)
PlotPanel getPlot (Formula.Type type, String formula, DataFrame frame, PlotConfiguration config)
PlotPanel getPlot (Formula.Type type, String formula, List< DataFrame > frames, PlotConfiguration config)
PlotPanel getVerticalCrossPlot (String formula, DataFrame frame, VertCrossPlotConfiguration config)
PlotPanel getVerticalCrossPlot (String formula, DataFrame frame, CrossSectionType type, int constAxisIndex)
Static Public Attributes
static final String TITLE_PREFIX = PlotFactory.class.getName() + ".TITLE_PREFIX"
static final String SUBTITLE = PlotFactory.class.getName() + ".SUBTITLE"
static final String LEGEND_MAP = PlotFactory.class.getName() + ".LEGEND_MAP"
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 32 of file PlotFactory.java.
Member Function Documentation
PlotPanel anl.verdi.plot.gui.PlotFactory.getPlot (Formula.Type type, String formula, DataFrame frame)
Definition at line 71 of file PlotFactory.java.
Referenced by anl.verdi.plot.gui.PlotFactory.getPlot().
PlotPanel anl.verdi.plot.gui.PlotFactory.getPlot (Formula.Type type, String formula, DataFrame frame, PlotConfiguration config)
Definition at line 75 of file PlotFactory.java.
References anl.verdi.plot.gui.PlotFactory.getPlot().
PlotPanel anl.verdi.plot.gui.PlotFactory.getPlot (Formula.Type type, String formula, List< DataFrame > frames, PlotConfiguration config)
Definition at line 81 of file PlotFactory.java.
References anl.verdi.formula.Formula.Type.CONTOUR, anl.verdi.formula.Formula.Type.TILE, anl.verdi.formula.Formula.Type.TIME_SERIES_BAR, and anl.verdi.formula.Formula.Type.TIME_SERIES_LINE.
PlotPanel anl.verdi.plot.gui.PlotFactory.getScatterPlot (String xFormula, String yFormula, DataFrame xFrame, DataFrame yFrame)
Definition at line 53 of file PlotFactory.java.
PlotPanel anl.verdi.plot.gui.PlotFactory.getVerticalCrossPlot (String formula, DataFrame frame, VertCrossPlotConfiguration config)
Definition at line 107 of file PlotFactory.java.
References anl.verdi.formula.Formula.Type.VERTICAL_CROSS_SECTION.
PlotPanel anl.verdi.plot.gui.PlotFactory.getVerticalCrossPlot (String formula, DataFrame frame, CrossSectionType type, int constAxisIndex)
Definition at line 113 of file PlotFactory.java.
References anl.verdi.formula.Formula.Type.VERTICAL_CROSS_SECTION.
Member Data Documentation
final String anl.verdi.plot.gui.PlotFactory.LEGEND_MAP = PlotFactory.class.getName() + ".LEGEND_MAP" static
Definition at line 39 of file PlotFactory.java.
final String anl.verdi.plot.gui.PlotFactory.SUBTITLE = PlotFactory.class.getName() + ".SUBTITLE" static
Definition at line 38 of file PlotFactory.java.
Referenced by anl.verdi.plot.gui.TimeSeriesPlotRequest.doCreatePlot().
final String anl.verdi.plot.gui.PlotFactory.TITLE_PREFIX = PlotFactory.class.getName() + ".TITLE_PREFIX" static
Definition at line 37 of file PlotFactory.java.
Referenced by anl.verdi.plot.gui.MultiTimeSeriesPlotRequest.doCreatePlot(), and anl.verdi.plot.gui.TimeSeriesPlotRequest.doCreatePlot().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/gui/PlotFactory.java