VERDI: anl.verdi.area.target.ProjectionInfo.PSProjectionGUIAdaptor Class Reference
anl.verdi.area.target.ProjectionInfo.PSProjectionGUIAdaptor Class Reference
Public Member Functions
PSProjectionGUIAdaptor ()
void initialize (ProjectionInfo d)
boolean validate (ProjectionInfo d)
CoordinateReferenceSystem getProjection (ProjectionInfo d)
String createWKT () throws IOException
Detailed Description
Polar stereographic adaptor
Author
Gordon Lurie
Version
Revision:
1.3
Definition at line 376 of file ProjectionInfo.java.
Constructor & Destructor Documentation
anl.verdi.area.target.ProjectionInfo.PSProjectionGUIAdaptor.PSProjectionGUIAdaptor ()
Constructor for GeoPSProjectionGUIAdaptor
Definition at line 381 of file ProjectionInfo.java.
Member Function Documentation
String anl.verdi.area.target.ProjectionInfo.PSProjectionGUIAdaptor.createWKT () throws IOException
Implements anl.verdi.area.target.ProjectionInfo.ProjectionGUIAdaptor.
Definition at line 483 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.doubleValueOf().
CoordinateReferenceSystem anl.verdi.area.target.ProjectionInfo.PSProjectionGUIAdaptor.getProjection (ProjectionInfo d)
Method getArgs
Parameters
d ProjectionInfo
Returns
Object[] Method getProjection
Parameters
d ProjectionInfo
Returns
GeoProjection
See Also
anl.jeoviewer.gui.ProjectionInfo$ProjectionGUIAdaptor::getProjection(ProjectionInfo)
Implements anl.verdi.area.target.ProjectionInfo.ProjectionGUIAdaptor.
Definition at line 470 of file ProjectionInfo.java.
void anl.verdi.area.target.ProjectionInfo.PSProjectionGUIAdaptor.initialize (ProjectionInfo d)
Method initialize
Parameters
d ProjectionInfo
See Also
anl.jeoviewer.gui.ProjectionInfo$ProjectionGUIAdaptor::initialize(ProjectionInfo)
Implements anl.verdi.area.target.ProjectionInfo.ProjectionGUIAdaptor.
Definition at line 390 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.getAllEllipseData().
boolean anl.verdi.area.target.ProjectionInfo.PSProjectionGUIAdaptor.validate (ProjectionInfo d)
Method validate
Parameters
d ProjectionInfo
Returns
boolean
See Also
anl.jeoviewer.gui.ProjectionInfo$ProjectionGUIAdaptor::validate(ProjectionInfo)
Implements anl.verdi.area.target.ProjectionInfo.ProjectionGUIAdaptor.
Definition at line 418 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.doubleValueOf().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/target/ProjectionInfo.java