VERDI: saf.core.ui.ActionDescriptor Class Reference
saf.core.ui.ActionDescriptor Class Reference
Public Member Functions
ActionDescriptor (String id, ISAFAction action)
String getLabel ()
void setLabel (String label)
String getMenuID ()
void setMenuID (String menuID)
String getToolbarGroupID ()
void setToolbarGroupID (String toolbarGroupID)
Icon getIcon ()
void setIcon (Icon icon)
void fillBars (GUIBarManager barManager, Workspace workspace)
JMenuItem createMenuItem (GUIBarManager barManager)
void setTooltip (String tip)
String getTooltip ()
String getActionCommand ()
void setActionCommand (String actionCommand)
Protected Attributes
ISAFAction action
Detailed Description
Describes an saf action as defined in the xml.
Author
Nick Collier
Definition at line 14 of file ActionDescriptor.java.
Constructor & Destructor Documentation
saf.core.ui.ActionDescriptor.ActionDescriptor (String id, ISAFAction action)
Definition at line 22 of file ActionDescriptor.java.
References saf.core.ui.ActionDescriptor.action.
Member Function Documentation
JMenuItem saf.core.ui.ActionDescriptor.createMenuItem (GUIBarManager barManager)
Definition at line 92 of file ActionDescriptor.java.
References saf.core.ui.ActionDescriptor.action.
Referenced by saf.core.ui.ActionDescriptor.fillBars().
void saf.core.ui.ActionDescriptor.fillBars (GUIBarManager barManager, Workspace workspace)
Implements saf.core.ui.BarItemDescriptor.
Definition at line 60 of file ActionDescriptor.java.
References saf.core.ui.ActionDescriptor.action, saf.core.ui.ActionDescriptor.createMenuItem(), and saf.core.ui.GUIConstants.WINDOW_MENU_ID.
String saf.core.ui.ActionDescriptor.getActionCommand ()
Definition at line 115 of file ActionDescriptor.java.
Icon saf.core.ui.ActionDescriptor.getIcon ()
Definition at line 52 of file ActionDescriptor.java.
String saf.core.ui.ActionDescriptor.getLabel ()
Definition at line 28 of file ActionDescriptor.java.
String saf.core.ui.ActionDescriptor.getMenuID ()
Implements saf.core.ui.BarItemDescriptor.
Definition at line 36 of file ActionDescriptor.java.
String saf.core.ui.ActionDescriptor.getToolbarGroupID ()
Implements saf.core.ui.BarItemDescriptor.
Definition at line 44 of file ActionDescriptor.java.
String saf.core.ui.ActionDescriptor.getTooltip ()
Definition at line 111 of file ActionDescriptor.java.
void saf.core.ui.ActionDescriptor.setActionCommand (String actionCommand)
Definition at line 119 of file ActionDescriptor.java.
void saf.core.ui.ActionDescriptor.setIcon (Icon icon)
Definition at line 56 of file ActionDescriptor.java.
void saf.core.ui.ActionDescriptor.setLabel (String label)
Definition at line 32 of file ActionDescriptor.java.
Referenced by saf.core.ui.ExitActionDescriptor.ExitActionDescriptor().
void saf.core.ui.ActionDescriptor.setMenuID (String menuID)
Definition at line 40 of file ActionDescriptor.java.
void saf.core.ui.ActionDescriptor.setToolbarGroupID (String toolbarGroupID)
Definition at line 48 of file ActionDescriptor.java.
void saf.core.ui.ActionDescriptor.setTooltip (String tip)
Definition at line 107 of file ActionDescriptor.java.
Member Data Documentation
ISAFAction saf.core.ui.ActionDescriptor.action protected
Definition at line 17 of file ActionDescriptor.java.
Referenced by saf.core.ui.ActionDescriptor.ActionDescriptor(), saf.core.ui.ActionDescriptor.createMenuItem(), saf.core.ui.ExitActionDescriptor.fillBars(), and saf.core.ui.ActionDescriptor.fillBars().
The documentation for this class was generated from the following file:
verdi_saf_ui/src/saf/core/ui/ActionDescriptor.java