VERDI: anl.verdi.gui.DatasetListModel Class Reference
anl.verdi.gui.DatasetListModel Class Reference
Public Member Functions
DatasetListModel ()
void addDatasetModelListener (DatasetModelListener listener)
void removeDatasetModelListener (DatasetModelListener listener)
Object getElementAt (int index)
Dataset getDatasetAt (int index)
int getSize ()
Iterable< DatasetListElement > elements ()
int addDataset (Dataset dataset)
void removeDataset (DatasetListElement item)
void removeDatasetAt (int index)
void clear ()
void addAll (List< DatasetListElement > elements)
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 17 of file DatasetListModel.java.
Constructor & Destructor Documentation
anl.verdi.gui.DatasetListModel.DatasetListModel ()
Definition at line 27 of file DatasetListModel.java.
Member Function Documentation
void anl.verdi.gui.DatasetListModel.addAll (List< DatasetListElement > elements)
Definition at line 134 of file DatasetListModel.java.
References anl.verdi.gui.DatasetListModel.elements().
int anl.verdi.gui.DatasetListModel.addDataset (Dataset dataset)
Definition at line 75 of file DatasetListModel.java.
void anl.verdi.gui.DatasetListModel.addDatasetModelListener (DatasetModelListener listener)
Definition at line 32 of file DatasetListModel.java.
void anl.verdi.gui.DatasetListModel.clear ()
Removes all the elements from this model.
Definition at line 122 of file DatasetListModel.java.
References anl.verdi.gui.DatasetListModel.removeDataset().
Iterable<DatasetListElement> anl.verdi.gui.DatasetListModel.elements ()
Definition at line 70 of file DatasetListModel.java.
Referenced by anl.verdi.gui.DatasetListModel.addAll(), and anl.verdi.core.Project.getDatasetsAsList().
Dataset anl.verdi.gui.DatasetListModel.getDatasetAt (int index)
Definition at line 47 of file DatasetListModel.java.
Object anl.verdi.gui.DatasetListModel.getElementAt (int index)
Definition at line 42 of file DatasetListModel.java.
Referenced by anl.verdi.commandline.ScriptHandler.constructMap(), and anl.verdi.commandline.task.TilePlotTask.run().
int anl.verdi.gui.DatasetListModel.getSize ()
Definition at line 52 of file DatasetListModel.java.
Referenced by anl.verdi.commandline.ScriptHandler.constructMap(), and anl.verdi.commandline.task.TilePlotTask.run().
void anl.verdi.gui.DatasetListModel.removeDataset (DatasetListElement item)
Definition at line 87 of file DatasetListModel.java.
References anl.verdi.gui.DatasetListElement.getDataset().
Referenced by anl.verdi.gui.DatasetListModel.clear().
void anl.verdi.gui.DatasetListModel.removeDatasetAt (int index)
Definition at line 95 of file DatasetListModel.java.
References anl.verdi.gui.DatasetListElement.getDataset().
void anl.verdi.gui.DatasetListModel.removeDatasetModelListener (DatasetModelListener listener)
Definition at line 37 of file DatasetListModel.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/gui/DatasetListModel.java