VERDI: anl.verdi.plot.gui.FastAreaTilePlot Class Reference
anl.verdi.plot.gui.FastAreaTilePlot Class Reference
Public Member Functions
FastAreaTilePlot (VerdiApplication app, DataFrame dataFrame)
void showAll ()
void showSelected ()
void showAverages ()
void showTotals ()
void showGrid ()
void configure (PlotConfiguration config)
void configure (PlotConfiguration config, Plot.ConfigSource source)
void init ()
void calculateAverageLevels ()
void calculateGridLevels ()
void setLegendLevels (MinMax minMax)
void calculateTotalLevels ()
boolean selectingAreas ()
String createTableName (Variable[] vars)
JTable createTable (String[] formula, boolean selectedOnly)
void actionPerformed (ActionEvent event)
JMenuBar getMenuBar ()
float[][] getAllLayerData ()
float[][] getAllLayerData (DataFrame dataFrame)
TilePlot getTilePlot ()
void recalculateAreas ()
void repaintAll ()
void processMouseEvent (MouseEvent me)
void processMouseMotionEvent (MouseEvent me)
void addProbe (final JTable table, String name, String rangeAxisName)
Public Member Functions inherited from anl.verdi.plot.gui.FastTilePlot
void drawBatchImage (int wdth, int hght)
void stopThread ()
void componentHidden (ComponentEvent unused)
void componentShown (ComponentEvent unused)
void componentResized (ComponentEvent unused)
void componentMoved (ComponentEvent unused)
void mousePressed (MouseEvent unused_)
void mouseEntered (MouseEvent unused_)
void mouseExited (MouseEvent unused_)
void mouseReleased (MouseEvent unused_)
void mouseClicked (MouseEvent unused_)
void viewClosed ()
void viewFloated (DockableFrameEvent unused_)
void viewRestored (DockableFrameEvent unused_)
void paintComponent (final Graphics graphics)
void draw ()
void actionPerformed (ActionEvent event)
void resetRowsNColumns (int fRow, int lRow, int fColumn, int lColumn)
void processMouseMotionEvent (MouseEvent me)
void processMouseEvent (MouseEvent me)
void stateChanged (ChangeEvent event)
void setTimestep (int timestep)
void setLayer (int layer)
FastTilePlot (VerdiApplication app, DataFrame dataFrame)
void computeDataRange (double[] minmax, boolean log)
JPanel getPanel ()
JMenuBar getMenuBar ()
void setLayerMapLine (VerdiBoundaries aVerdiBoundaries)
void editChartProperties ()
JToolBar getToolBar ()
Formula.Type getType ()
List< DataFrame > getData ()
void exportImage (String format, File file, int width, int height) throws IOException
void configure (PlotConfiguration config)
void configure (PlotConfiguration config, Plot.ConfigSource source)
PlotConfiguration getPlotConfiguration ()
BufferedImage getBufferedImage ()
BufferedImage getBufferedImage (int width, int height)
void addPlotListener (PlotListener listener)
void removePlotListener (PlotListener listener)
int print (Graphics g, PageFormat pf, int pageIndex) throws PrinterException
void updateTimeStep (int step)
Decidegrees getLatLonFor (int screenx, int screeny)
String createAreaString (int[] point)
String formatPoint (Point4i point)
void exportShapefile (String baseFileName) throws IOException
void exportASCIIGrid (String baseFileName)
void exportEPSImage (String filename)
void exportEPSImage (String filename, int width, int height)
JMapPane getMapPane ()
void addVectorAnnotation (VectorEvaluator eval)
void addObservationData (DataManager manager, boolean showLegend)
List< OverlayObject > getObservationData ()
String getTitle ()
void showBusyCursor ()
void restoreCursor ()
Public Member Functions inherited from anl.verdi.plot.gui.Plot
void configure (PlotConfiguration config, ConfigSource source)
Static Public Member Functions
static boolean isShowSelectedOnly ()
static void setShowSelectedOnly (boolean showSelectedOnly)
Static Public Attributes
static final String AREA_COMMAND = "Area Information"
Static Public Attributes inherited from anl.verdi.plot.gui.FastTilePlot
static final int NO_VAL = Integer.MIN_VALUE
static final String PROPERTIES_COMMAND = "PROPERTIES"
static final String SAVE_COMMAND = "SAVE"
static final String PRINT_COMMAND = "PRINT"
static final String ZOOM_IN_BOTH_COMMAND = "ZOOM_IN_BOTH"
static final String ZOOM_OUT_BOTH_COMMAND = "ZOOM_OUT_BOTH"
static final String ZOOM_OUT_MAX_COMMAND = "ZOOM_OUT_MAX"
Protected Member Functions
JPopupMenu createPopupMenu (boolean properties, boolean save, boolean print, boolean zoomable)
Protected Member Functions inherited from anl.verdi.plot.gui.FastTilePlot
void showPopup (MouseEvent me)
boolean isInDataArea (MouseEvent me)
int getRow (Point p)
int getCol (Point p)
void addObsOverlay ()
void addVectorOverlay ()
void activateRubberBand ()
void deactivateRubberBand ()
void resetMenuItems (JMenu addLayers)
FeatureLayer createControlLayer (String shapefile)
JPopupMenu createPopupMenu (boolean properties, boolean save, boolean print, boolean zoomable)
DataUtilities.MinMaxPoint getMinMaxPoints ()
void enableProbeItems (boolean val)
Point2D getLatLonForAxisPoint (Point axisPoint)
DataFrame getDataFrame ()
DataFrame getDataFrame (boolean log)
Additional Inherited Members
Public Attributes inherited from anl.verdi.plot.gui.FastTilePlot
final Runnable doubleBufferedRenderer
Protected Attributes inherited from anl.verdi.plot.gui.FastTilePlot
boolean log = false
int startDate
int startTime
int timestepSize
int timesteps
int layers
int rows
int columns
int rowOrigin
int columnOrigin
TilePlot tilePlot
int timestep = 0
int firstTimestep = 0
int lastTimestep = 0
int layer = 0
int firstLayer = 0
int lastLayer = 0
double[] legendLevels
Palette defaultPalette
ColorMap map
Projector projector
double[][] gridBounds = { { 0.0, 0.0 }, { 0.0, 0.0 } }
double[][] domain = { { 0.0, 0.0 }, { 0.0, 0.0 } }
String units
DataFrame dataFrame
DataFrame dataFrameLog
List< OverlayObject > obsData = new ArrayList<OverlayObject>()
List< ObsAnnotation > obsAnnotations
VectorAnnotation vectAnnotation
final Rubberband rubberband = new Rubberband(this)
boolean zoom = true
boolean probe = false
boolean showLatLon = false
boolean showObsLegend = false
java.util.List< JMenuItem > probeItems = new ArrayList<JMenuItem>()
Rectangle dataArea = new Rectangle()
Slice probedSlice
JCheckBoxMenuItem showGridLines
MinMax minMax
PlotConfiguration config
Action timeSeriesSelected
Action timeSeriesBarSelected
Action timeSeriesMin
Action timeSeriesMax
Detailed Description
Definition at line 63 of file FastAreaTilePlot.java.
Constructor & Destructor Documentation
anl.verdi.plot.gui.FastAreaTilePlot.FastAreaTilePlot (VerdiApplication app, DataFrame dataFrame)
Definition at line 72 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.domain, anl.verdi.plot.gui.FastTilePlot.gridBounds, anl.verdi.plot.gui.FastTilePlot.projector, anl.verdi.plot.gui.FastTilePlot.startDate, anl.verdi.plot.gui.FastTilePlot.startTime, and anl.verdi.plot.gui.FastTilePlot.timestepSize.
Member Function Documentation
void anl.verdi.plot.gui.FastAreaTilePlot.actionPerformed (ActionEvent event)
Definition at line 317 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastAreaTilePlot.addProbe(), anl.verdi.plot.gui.FastAreaTilePlot.AREA_COMMAND, anl.verdi.plot.gui.FastAreaTilePlot.createTable(), anl.verdi.plot.gui.FastTilePlot.getDataFrame(), and anl.verdi.core.VerdiApplication.getGui().
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar().
void anl.verdi.plot.gui.FastAreaTilePlot.addProbe (final JTable table, String name, String rangeAxisName)
Definition at line 697 of file FastAreaTilePlot.java.
References anl.verdi.core.VerdiConstants.MAIN_GROUP_ID, and anl.verdi.core.VerdiConstants.PERSPECTIVE_ID.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.actionPerformed().
void anl.verdi.plot.gui.FastAreaTilePlot.calculateAverageLevels ()
Definition at line 162 of file FastAreaTilePlot.java.
References anl.verdi.plot.config.TilePlotConfiguration.COLOR_MAP, anl.verdi.plot.gui.FastTilePlot.defaultPalette, anl.verdi.plot.gui.FastTilePlot.map, anl.verdi.plot.gui.FastTilePlot.minMax, anl.verdi.plot.gui.FastAreaTilePlot.setLegendLevels(), and anl.verdi.plot.gui.FastTilePlot.tilePlot.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.showAverages().
void anl.verdi.plot.gui.FastAreaTilePlot.calculateGridLevels ()
Definition at line 195 of file FastAreaTilePlot.java.
References anl.verdi.plot.config.TilePlotConfiguration.COLOR_MAP, anl.verdi.plot.gui.FastTilePlot.computeDataRange(), anl.verdi.plot.gui.FastTilePlot.defaultPalette, anl.verdi.plot.gui.FastTilePlot.log, anl.verdi.plot.gui.FastTilePlot.map, anl.verdi.plot.gui.FastTilePlot.minMax, anl.verdi.plot.gui.FastAreaTilePlot.setLegendLevels(), and anl.verdi.plot.gui.FastTilePlot.tilePlot.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.showGrid().
void anl.verdi.plot.gui.FastAreaTilePlot.calculateTotalLevels ()
Definition at line 234 of file FastAreaTilePlot.java.
References anl.verdi.plot.config.TilePlotConfiguration.COLOR_MAP, anl.verdi.plot.gui.FastTilePlot.defaultPalette, anl.verdi.plot.gui.FastTilePlot.map, anl.verdi.plot.gui.FastTilePlot.minMax, anl.verdi.plot.gui.FastAreaTilePlot.setLegendLevels(), and anl.verdi.plot.gui.FastTilePlot.tilePlot.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.showTotals().
void anl.verdi.plot.gui.FastAreaTilePlot.configure (PlotConfiguration config)
Configure this Plot according to the specified PlotConfiguration.
Parameters
config the new plot configuration
Implements anl.verdi.plot.gui.Plot.
Definition at line 110 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.config.
void anl.verdi.plot.gui.FastAreaTilePlot.configure (PlotConfiguration config, Plot.ConfigSource source)
Definition at line 113 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.config.
JPopupMenu anl.verdi.plot.gui.FastAreaTilePlot.createPopupMenu (boolean properties, boolean save, boolean print, boolean zoomable) protected
Definition at line 530 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastAreaTilePlot.AREA_COMMAND, and anl.verdi.plot.gui.FastTilePlot.print().
JTable anl.verdi.plot.gui.FastAreaTilePlot.createTable (String[] formula, boolean selectedOnly)
Definition at line 285 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastAreaTilePlot.createTableName(), anl.verdi.plot.gui.FastTilePlot.dataFrame, anl.verdi.area.target.Target.getDefaultUnits(), anl.verdi.area.target.Target.getTargets(), anl.verdi.plot.gui.FastTilePlot.layer, and anl.verdi.plot.gui.FastTilePlot.timestep.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.actionPerformed().
String anl.verdi.plot.gui.FastAreaTilePlot.createTableName (Variable[] vars)
Definition at line 269 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.getDataFrame(), anl.verdi.plot.gui.FastTilePlot.layer, and anl.verdi.plot.gui.FastTilePlot.timestep.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.createTable().
float [][] anl.verdi.plot.gui.FastAreaTilePlot.getAllLayerData ()
Definition at line 476 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.getDataFrame().
float [][] anl.verdi.plot.gui.FastAreaTilePlot.getAllLayerData (DataFrame dataFrame)
Definition at line 480 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.columns, anl.verdi.plot.gui.FastTilePlot.firstLayer, anl.verdi.plot.gui.FastTilePlot.firstTimestep, anl.verdi.plot.gui.FastTilePlot.layer, anl.verdi.plot.gui.FastTilePlot.rows, and anl.verdi.plot.gui.FastTilePlot.timestep.
JMenuBar anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar ()
Gets a menu bar for this Plot. This may return null if there is no menu bar.
Returns
a menu bar for this Plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 342 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastAreaTilePlot.actionPerformed(), anl.verdi.plot.gui.FastTilePlot.columns, anl.verdi.plot.gui.FastTilePlot.dataArea, anl.verdi.plot.gui.FastTilePlot.draw(), anl.verdi.plot.gui.FastTilePlot.getDataFrame(), anl.verdi.area.Units.isConcentration(), anl.verdi.plot.gui.FastTilePlot.probe, anl.verdi.plot.gui.FastTilePlot.rows, anl.verdi.plot.gui.FastAreaTilePlot.showAll(), anl.verdi.plot.gui.FastAreaTilePlot.showAverages(), anl.verdi.plot.gui.FastAreaTilePlot.showGrid(), anl.verdi.plot.gui.FastAreaTilePlot.showSelected(), anl.verdi.plot.gui.FastAreaTilePlot.showTotals(), and anl.verdi.plot.gui.FastTilePlot.zoom.
TilePlot anl.verdi.plot.gui.FastAreaTilePlot.getTilePlot ()
Definition at line 512 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.tilePlot.
void anl.verdi.plot.gui.FastAreaTilePlot.init ()
Definition at line 116 of file FastAreaTilePlot.java.
References anl.verdi.plot.config.TilePlotConfiguration.COLOR_MAP, anl.verdi.plot.gui.FastTilePlot.defaultPalette, anl.verdi.plot.gui.FastTilePlot.map, anl.verdi.plot.gui.FastTilePlot.minMax, and anl.verdi.plot.gui.FastAreaTilePlot.setLegendLevels().
static boolean anl.verdi.plot.gui.FastAreaTilePlot.isShowSelectedOnly () static
Definition at line 504 of file FastAreaTilePlot.java.
void anl.verdi.plot.gui.FastAreaTilePlot.processMouseEvent (MouseEvent me)
Definition at line 545 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.getLatLonFor(), anl.verdi.plot.gui.FastTilePlot.isInDataArea(), anl.verdi.plot.gui.FastAreaTilePlot.repaintAll(), and anl.verdi.plot.gui.FastAreaTilePlot.selectingAreas().
void anl.verdi.plot.gui.FastAreaTilePlot.processMouseMotionEvent (MouseEvent me)
Definition at line 606 of file FastAreaTilePlot.java.
References anl.verdi.area.target.Target.containsDeposition(), anl.verdi.area.Units.getAreaUnit(), anl.verdi.plot.gui.FastTilePlot.getDataFrame(), anl.verdi.plot.gui.FastTilePlot.getLatLonFor(), anl.verdi.area.Units.isConcentration(), anl.verdi.plot.gui.FastTilePlot.isInDataArea(), anl.verdi.area.target.Target.toString(), and anl.verdi.plot.gui.FastTilePlot.units.
void anl.verdi.plot.gui.FastAreaTilePlot.recalculateAreas ()
Definition at line 515 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.getDataFrame(), and anl.verdi.plot.gui.FastTilePlot.tilePlot.
void anl.verdi.plot.gui.FastAreaTilePlot.repaintAll ()
Definition at line 522 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.draw().
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.processMouseEvent().
boolean anl.verdi.plot.gui.FastAreaTilePlot.selectingAreas ()
Definition at line 266 of file FastAreaTilePlot.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.processMouseEvent().
void anl.verdi.plot.gui.FastAreaTilePlot.setLegendLevels (MinMax minMax)
Definition at line 226 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastTilePlot.legendLevels.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.calculateAverageLevels(), anl.verdi.plot.gui.FastAreaTilePlot.calculateGridLevels(), anl.verdi.plot.gui.FastAreaTilePlot.calculateTotalLevels(), and anl.verdi.plot.gui.FastAreaTilePlot.init().
static void anl.verdi.plot.gui.FastAreaTilePlot.setShowSelectedOnly (boolean showSelectedOnly) static
Definition at line 508 of file FastAreaTilePlot.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.showAll(), and anl.verdi.plot.gui.FastAreaTilePlot.showSelected().
void anl.verdi.plot.gui.FastAreaTilePlot.showAll ()
Definition at line 79 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastAreaTilePlot.setShowSelectedOnly().
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar().
void anl.verdi.plot.gui.FastAreaTilePlot.showAverages ()
Definition at line 89 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastAreaTilePlot.calculateAverageLevels(), and anl.verdi.plot.gui.FastTilePlot.tilePlot.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar().
void anl.verdi.plot.gui.FastAreaTilePlot.showGrid ()
Definition at line 103 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastAreaTilePlot.calculateGridLevels(), and anl.verdi.plot.gui.FastTilePlot.tilePlot.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar().
void anl.verdi.plot.gui.FastAreaTilePlot.showSelected ()
Definition at line 84 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastAreaTilePlot.setShowSelectedOnly().
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar().
void anl.verdi.plot.gui.FastAreaTilePlot.showTotals ()
Definition at line 96 of file FastAreaTilePlot.java.
References anl.verdi.plot.gui.FastAreaTilePlot.calculateTotalLevels(), and anl.verdi.plot.gui.FastTilePlot.tilePlot.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar().
Member Data Documentation
final String anl.verdi.plot.gui.FastAreaTilePlot.AREA_COMMAND = "Area Information" static
Definition at line 529 of file FastAreaTilePlot.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.actionPerformed(), and anl.verdi.plot.gui.FastAreaTilePlot.createPopupMenu().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/gui/FastAreaTilePlot.java