VERDI: anl.verdi.commandline.ScriptHandler Class Reference
anl.verdi.commandline.ScriptHandler Class Reference
Public Member Functions
ScriptHandler (String[] args, VerdiApplication vApp)
void run ()
Static Public Member Functions
static void constructMap ()
static HashMap getCommands ()
Static Protected Member Functions
static VerdiApplication getVerdiApp ()
Static Protected Attributes
static VerdiApplication verdiApp = null
Detailed Description
Class whose main purpose is to handle and carry out the commands received from the command line
Author
A. Wagner
Definition at line 55 of file ScriptHandler.java.
Constructor & Destructor Documentation
anl.verdi.commandline.ScriptHandler.ScriptHandler (String[] args, VerdiApplication vApp)
Definition at line 157 of file ScriptHandler.java.
References anl.verdi.commandline.ScriptHandler.constructMap(), and anl.verdi.commandline.ScriptHandler.verdiApp.
Member Function Documentation
static void anl.verdi.commandline.ScriptHandler.constructMap () static
Definition at line 171 of file ScriptHandler.java.
References anl.verdi.plot.config.TilePlotConfiguration.COLOR_MAP, anl.verdi.plot.config.PlotConfiguration.DOMAIN_SHOW_TICK, anl.verdi.gui.DatasetListModel.getElementAt(), anl.verdi.gui.FormulaListModel.getElementAt(), anl.verdi.core.VerdiApplication.getGui(), anl.verdi.core.VerdiApplication.getProject(), anl.verdi.gui.DatasetListModel.getSize(), anl.verdi.plot.config.PlotConfiguration.RANGE_SHOW_TICK, anl.verdi.commandline.ScriptHandler.run(), anl.verdi.plot.config.TilePlotConfiguration.SHOW_GRID_LINES, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_FONT, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_FONT, anl.verdi.plot.config.PlotConfiguration.TITLE_FONT, anl.verdi.plot.config.PlotConfiguration.UNITS_SHOW_TICK, and anl.verdi.commandline.ScriptHandler.verdiApp.
Referenced by anl.verdi.commandline.ScriptHandler.ScriptHandler().
static HashMap anl.verdi.commandline.ScriptHandler.getCommands () static
Definition at line 1600 of file ScriptHandler.java.
static VerdiApplication anl.verdi.commandline.ScriptHandler.getVerdiApp () static protected
Definition at line 1604 of file ScriptHandler.java.
References anl.verdi.commandline.ScriptHandler.verdiApp.
void anl.verdi.commandline.ScriptHandler.run ()
Definition at line 166 of file ScriptHandler.java.
Referenced by anl.verdi.commandline.ScriptHandler.constructMap().
Member Data Documentation
VerdiApplication anl.verdi.commandline.ScriptHandler.verdiApp = null static protected
Definition at line 59 of file ScriptHandler.java.
Referenced by anl.verdi.commandline.ScriptHandler.constructMap(), anl.verdi.commandline.ScriptHandler.getVerdiApp(), and anl.verdi.commandline.ScriptHandler.ScriptHandler().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/commandline/ScriptHandler.java