VERDI: simphony.util.error.ErrorCenter Class Reference
simphony.util.error.ErrorCenter Class Reference
Public Member Functions
boolean error (int errorCode, Object info, Throwable error, Object...metaData)
boolean fireErrorEvent (int errorCode, Object info, Throwable error, Object...metaData)
void addErrorHandler (ErrorHandler handler)
void removeErrorHandler (ErrorHandler handler)
Collection< ErrorHandler > getErrorHandlers ()
Static Public Member Functions
static ErrorCenter getErrorCenter ()
Detailed Description
Author
Jerry Vos
Version
Revision:
1.5
Date:
2005/11/14 21:58:40
Definition at line 13 of file ErrorCenter.java.
Member Function Documentation
void simphony.util.error.ErrorCenter.addErrorHandler (ErrorHandler handler)
Adds an ErrorHandler.
Parameters
handler the ErrorHandler to add
Definition at line 91 of file ErrorCenter.java.
boolean simphony.util.error.ErrorCenter.error (int errorCode, Object info, Throwable error, Object... metaData)
Fires an error event with the specified error information.
Parameters
errorCode a code for the error
info information on the error
error an error object (useful for getting a stack trace)
metaData extra meta data about the erro
Returns
if the error was handled or not by one of the ErrorHandlers
Definition at line 42 of file ErrorCenter.java.
References simphony.util.error.ErrorCenter.fireErrorEvent().
Referenced by simphony.util.error.ErrorCenter.fireErrorEvent().
boolean simphony.util.error.ErrorCenter.fireErrorEvent (int errorCode, Object info, Throwable error, Object... metaData)
Fires an error event with the specified error information.
Parameters
errorCode a code for the error
info information on the error
error an error object (useful for getting a stack trace)
metaData extra meta data about the erro
Returns
if the error was handled or not by one of the ErrorHandlers
Definition at line 60 of file ErrorCenter.java.
References simphony.util.error.ErrorCenter.error().
Referenced by simphony.util.error.ErrorCenter.error().
static ErrorCenter simphony.util.error.ErrorCenter.getErrorCenter () static
Gets an ErrorCenter.
Returns
Definition at line 22 of file ErrorCenter.java.
Collection<ErrorHandler> simphony.util.error.ErrorCenter.getErrorHandlers ()
Retrieves the ErrorHandlers this ErrorCenter contains.
Returns
the ErrorHandlers this ErrorCenter contains
Definition at line 114 of file ErrorCenter.java.
void simphony.util.error.ErrorCenter.removeErrorHandler (ErrorHandler handler)
Removes an ErrorHandler.
Parameters
handler the ErrorHandler to remove
Definition at line 103 of file ErrorCenter.java.
The documentation for this class was generated from the following file:
verdi_saf_core_runtime/src/simphony/util/error/ErrorCenter.java