VERDI: anl.verdi.plot.types.TimeSeriesBarPlot Class Reference
anl.verdi.plot.types.TimeSeriesBarPlot Class Reference
Classes
class AreaFinder
Public Member Functions
void viewClosed ()
TimeSeriesBarPlot (DataFrame frame, PlotConfiguration config)
List< DataFrame > getData ()
JToolBar getToolBar ()
void updateLayer (int layer)
JMenuBar getMenuBar ()
void addPlotListener (PlotListener listener)
void removePlotListener (PlotListener listener)
JPanel getPanel ()
Formula.Type getType ()
void configure (PlotConfiguration config)
PlotConfiguration getPlotConfiguration ()
String getTitle ()
JMapPane getMapPane ()
Public Member Functions inherited from anl.verdi.plot.types.AbstractPlot
void exportImage (String format, File file, int width, int height) throws IOException
BufferedImage getBufferedImage ()
BufferedImage getBufferedImage (int width, int height)
void configure (PlotConfiguration config)
void configure (PlotConfiguration config, Plot.ConfigSource source)
PlotConfiguration getPlotConfiguration ()
Public Member Functions inherited from anl.verdi.plot.gui.Plot
void configure (PlotConfiguration config, ConfigSource source)
Additional Inherited Members
Protected Attributes inherited from anl.verdi.plot.types.AbstractPlot
VerdiChartPanel panel
Detailed Description
Definition at line 87 of file TimeSeriesBarPlot.java.
Constructor & Destructor Documentation
anl.verdi.plot.types.TimeSeriesBarPlot.TimeSeriesBarPlot (DataFrame frame, PlotConfiguration config)
Check if a chart theme has been loaded.
Definition at line 119 of file TimeSeriesBarPlot.java.
References anl.verdi.plot.types.TimeSeriesBarPlot.configure(), anl.verdi.plot.types.TimeSeriesBarPlot.getPlotConfiguration(), anl.verdi.plot.config.PlotConfiguration.getSubtitle1(), and anl.verdi.plot.types.AbstractPlot.panel.
Member Function Documentation
void anl.verdi.plot.types.TimeSeriesBarPlot.addPlotListener (PlotListener listener)
Adds the specified PlotListener.
Parameters
listener the plot listener to add
Implements anl.verdi.plot.gui.Plot.
Definition at line 350 of file TimeSeriesBarPlot.java.
void anl.verdi.plot.types.TimeSeriesBarPlot.configure (PlotConfiguration config)
Configure this Plot according to the specified PlotConfiguration.
Parameters
config the new plot configuration
Implements anl.verdi.plot.gui.Plot.
Definition at line 589 of file TimeSeriesBarPlot.java.
References anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_LABEL_FORMAT_4CAT, anl.verdi.plot.types.JChartTitlesLabels.getTitleConfigurator(), and anl.verdi.plot.config.TimeSeriesPlotConfiguration.SERIES_COLOR.
Referenced by anl.verdi.plot.types.TimeSeriesBarPlot.TimeSeriesBarPlot().
List<DataFrame> anl.verdi.plot.types.TimeSeriesBarPlot.getData ()
Gets the data that this Plot plots.
Returns
the data that this Plot plots.
Implements anl.verdi.plot.gui.Plot.
Definition at line 152 of file TimeSeriesBarPlot.java.
JMapPane anl.verdi.plot.types.TimeSeriesBarPlot.getMapPane ()
Gets the JMapPane that contains the mapping portion of the plot component.
Returns
the mapping panel that contains the mapping portion of the plot component.
Implements anl.verdi.plot.gui.Plot.
Definition at line 679 of file TimeSeriesBarPlot.java.
JMenuBar anl.verdi.plot.types.TimeSeriesBarPlot.getMenuBar ()
Gets a menu bar for this Plot.
Returns
a menu bar for this Plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 232 of file TimeSeriesBarPlot.java.
References anl.verdi.plot.types.AbstractPlot.panel, anl.verdi.plot.types.AbstractPlot.ControlAction.PROBE, and anl.verdi.plot.types.AbstractPlot.ControlAction.ZOOM.
JPanel anl.verdi.plot.types.TimeSeriesBarPlot.getPanel ()
Gets the entire panel that contains the plot component.
Returns
the entire panel that contains the plot component.
Implements anl.verdi.plot.gui.Plot.
Definition at line 437 of file TimeSeriesBarPlot.java.
References anl.verdi.plot.types.AbstractPlot.panel.
PlotConfiguration anl.verdi.plot.types.TimeSeriesBarPlot.getPlotConfiguration ()
Gets this Plot's configuration data.
Returns
this Plot's configuration data.
Implements anl.verdi.plot.gui.Plot.
Definition at line 655 of file TimeSeriesBarPlot.java.
References anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_LABEL_FORMAT_4CAT, anl.verdi.plot.config.PlotConfiguration.FOOTER1_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.FOOTER2_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.LEGEND_SHOW, anl.verdi.plot.config.PlotConfiguration.OBS_SHOW_LEGEND, anl.verdi.plot.config.PlotConfiguration.PLOT_TYPE, anl.verdi.plot.config.TimeSeriesPlotConfiguration.SERIES_COLOR, anl.verdi.formula.Formula.Type.TIME_SERIES_BAR, anl.verdi.plot.config.PlotConfiguration.UNITS, anl.verdi.plot.config.PlotConfiguration.UNITS_COLOR, and anl.verdi.plot.config.PlotConfiguration.UNITS_FONT.
Referenced by anl.verdi.plot.types.TimeSeriesBarPlot.TimeSeriesBarPlot().
String anl.verdi.plot.types.TimeSeriesBarPlot.getTitle ()
Gets this plot's current title.
Implements anl.verdi.plot.gui.Plot.
Definition at line 675 of file TimeSeriesBarPlot.java.
JToolBar anl.verdi.plot.types.TimeSeriesBarPlot.getToolBar ()
Gets a tool bar for this plot. This may return null if there is no tool bar.
Returns
a tool bar for this plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 164 of file TimeSeriesBarPlot.java.
References anl.verdi.data.DataFrame.getAxes(), anl.verdi.plot.gui.LayerChartPanel.NO_LAYER, and anl.verdi.plot.types.TimeSeriesBarPlot.updateLayer().
Formula.Type anl.verdi.plot.types.TimeSeriesBarPlot.getType ()
Gets the type of the Plot.
Returns
the type of the Plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 579 of file TimeSeriesBarPlot.java.
void anl.verdi.plot.types.TimeSeriesBarPlot.removePlotListener (PlotListener listener)
Removes the specified PlotListener.
Parameters
listener the plot listener to remove
Implements anl.verdi.plot.gui.Plot.
Definition at line 359 of file TimeSeriesBarPlot.java.
void anl.verdi.plot.types.TimeSeriesBarPlot.updateLayer (int layer)
Definition at line 197 of file TimeSeriesBarPlot.java.
Referenced by anl.verdi.plot.types.TimeSeriesBarPlot.getToolBar().
void anl.verdi.plot.types.TimeSeriesBarPlot.viewClosed ()
Implements anl.verdi.plot.gui.Plot.
Definition at line 105 of file TimeSeriesBarPlot.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/types/TimeSeriesBarPlot.java