VERDI: anl.verdi.gui.FormulaListModel Class Reference
anl.verdi.gui.FormulaListModel Class Reference
Public Member Functions
FormulaListModel ()
ListSelectionModel getSelectionModel ()
void setSelectionModel (ListSelectionModel selectionModel)
Object getElementAt (int index)
String getFormulaAt (int index)
int getSize ()
int addFormula (String formula)
int addFormula (FormulaListElement element)
Iterable< FormulaListElement > elements ()
void removeFormulaAt (int index)
void removeFormula (FormulaListElement element)
void clear ()
void addAll (List< FormulaListElement > elements)
void setSelectedItem (int index)
void setSelectedItem (FormulaListElement element)
Detailed Description
Backing model for the formulas gui.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 18 of file FormulaListModel.java.
Constructor & Destructor Documentation
anl.verdi.gui.FormulaListModel.FormulaListModel ()
Definition at line 28 of file FormulaListModel.java.
Member Function Documentation
void anl.verdi.gui.FormulaListModel.addAll (List< FormulaListElement > elements)
Definition at line 115 of file FormulaListModel.java.
References anl.verdi.gui.FormulaListModel.elements().
int anl.verdi.gui.FormulaListModel.addFormula (String formula)
Definition at line 70 of file FormulaListModel.java.
int anl.verdi.gui.FormulaListModel.addFormula (FormulaListElement element)
Definition at line 75 of file FormulaListModel.java.
References anl.verdi.gui.FormulaListElement.getFormula().
void anl.verdi.gui.FormulaListModel.clear ()
Removes all the elements from this model.
Definition at line 108 of file FormulaListModel.java.
Iterable<FormulaListElement> anl.verdi.gui.FormulaListModel.elements ()
Definition at line 86 of file FormulaListModel.java.
Referenced by anl.verdi.gui.FormulaListModel.addAll(), anl.verdi.core.Project.getFormulaFor(), anl.verdi.core.Project.getFormulas(), and anl.verdi.core.Project.getFormulasAsList().
Object anl.verdi.gui.FormulaListModel.getElementAt (int index)
Definition at line 44 of file FormulaListModel.java.
Referenced by anl.verdi.commandline.ScriptHandler.constructMap().
String anl.verdi.gui.FormulaListModel.getFormulaAt (int index)
Definition at line 49 of file FormulaListModel.java.
ListSelectionModel anl.verdi.gui.FormulaListModel.getSelectionModel ()
Definition at line 34 of file FormulaListModel.java.
int anl.verdi.gui.FormulaListModel.getSize ()
Definition at line 54 of file FormulaListModel.java.
void anl.verdi.gui.FormulaListModel.removeFormula (FormulaListElement element)
Definition at line 98 of file FormulaListModel.java.
void anl.verdi.gui.FormulaListModel.removeFormulaAt (int index)
Definition at line 91 of file FormulaListModel.java.
void anl.verdi.gui.FormulaListModel.setSelectedItem (int index)
Definition at line 124 of file FormulaListModel.java.
Referenced by anl.verdi.gui.FormulaListModel.setSelectedItem().
void anl.verdi.gui.FormulaListModel.setSelectedItem (FormulaListElement element)
Definition at line 129 of file FormulaListModel.java.
References anl.verdi.gui.FormulaListElement.getFormula(), and anl.verdi.gui.FormulaListModel.setSelectedItem().
void anl.verdi.gui.FormulaListModel.setSelectionModel (ListSelectionModel selectionModel)
Definition at line 39 of file FormulaListModel.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/gui/FormulaListModel.java