VERDI: anl.verdi.plot.types.TilePlot Class Reference
anl.verdi.plot.types.TilePlot Class Reference
Classes
class AreaFinder
Public Member Functions
TilePlot (DataFrame frame)
TilePlot (DataFrame frame, PlotConfiguration config)
void addVectorAnnotation (VectorEvaluator eval)
void addObsAnnotation (ObsEvaluator eval, int shapeSize, int strokeSize)
void addObsAnnotation (ObsEvaluator eval, int shapeSize, int strokeSize, ObsAnnotation.Symbol symbol)
JToolBar getToolBar ()
void updateTimeStep (int step)
void updateTimeStepLayer (int timeStep, int layer)
Formula.Type getType ()
String getTitle ()
JMapPane getMapPane ()
Public Member Functions inherited from anl.verdi.plot.types.AbstractTilePlot
void viewClosed ()
AbstractTilePlot (DataFrame frame)
List< DataFrame > getData ()
void configure (PlotConfiguration config)
DataUtilities.MinMax getGlobalMinMax ()
DataUtilities.MinMax getCurrentMinMax ()
BufferedImage getBufferedImage ()
BufferedImage getBufferedImage (int width, int height)
ColorMap getColorMap ()
String createAreaString (int[] point)
String formatPoint (Point4i point)
JPanel getPanel ()
JMenuBar getMenuBar ()
void addPlotListener (PlotListener listener)
void removePlotListener (PlotListener listener)
void updateColorMap (ColorMap map)
PlotConfiguration getPlotConfiguration ()
int getLayer ()
void setLayer (int layer)
Public Member Functions inherited from anl.verdi.plot.types.AbstractPlot
void exportImage (String format, File file, int width, int height) throws IOException
BufferedImage getBufferedImage ()
BufferedImage getBufferedImage (int width, int height)
void configure (PlotConfiguration config)
void configure (PlotConfiguration config, Plot.ConfigSource source)
PlotConfiguration getPlotConfiguration ()
Public Member Functions inherited from anl.verdi.plot.gui.Plot
void configure (PlotConfiguration config, ConfigSource source)
Protected Member Functions
void addObsOverlay ()
void addVectorsOverlay ()
DataUtilities.MinMaxPoint getMinMaxPoints ()
DataUtilities.MinMax getMinMax ()
void createSubtitle ()
Point4i[] rectToPoints (Rectangle rect)
Protected Member Functions inherited from anl.verdi.plot.types.AbstractTilePlot
void updateTextTitle (TextTitle title, String text, Color color, Font font)
GridCoverage2D getCoverage (DataFrame frame)
FeatureLayer createLayer (File file, File styleFile) throws IOException
void createSubtitles ()
Point2D getLatLonForAxisPoint (Point axisPoint)
abstract Point4i[] rectToPoints (Rectangle rect)
String createAreaString (Rectangle rect)
String createLonLatAreaString (Point4i[] points)
void createMapAnnotation ()
void enableProbeItems (boolean val)
abstract void createSubtitle ()
abstract DataUtilities.MinMaxPoint getMinMaxPoints ()
void addObsOverlay ()
void addVectorsOverlay ()
abstract DataUtilities.MinMax getMinMax ()
void updateScaleAxis (XYPlot plot)
LookupPaintScale createPaintScale (ColorMap map, double min, double max)
PlotConfiguration getTitlesLabelsConfig (PlotConfiguration config)
Additional Inherited Members
Static Public Attributes inherited from anl.verdi.plot.types.AbstractTilePlot
static final int NO_VAL = Integer.MIN_VALUE
Protected Attributes inherited from anl.verdi.plot.types.AbstractTilePlot
DataFrame frame
int timeStep
int layer
JFreeChart chart
PlotEventProducer eventProducer = new PlotEventProducer()
ColorMap map
Slice probedSlice
List< JMenuItem > probeItems = new ArrayList<JMenuItem>()
MapAnnotation mapAnnotation
ControlAction controlAction = ControlAction.ZOOM
boolean showLatLon = false
PlotConfiguration config
int subTitle1Index
int legendIndex = -1
String units
Map< String, FeatureLayer > mapLayers = new HashMap<String, FeatureLayer>()
Action timeSeriesSelected
Action timeSeriesBarSelected
Action timeSeriesMin
Action timeSeriesMax
Protected Attributes inherited from anl.verdi.plot.types.AbstractPlot
VerdiChartPanel panel
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 62 of file TilePlot.java.
Constructor & Destructor Documentation
anl.verdi.plot.types.TilePlot.TilePlot (DataFrame frame)
Definition at line 70 of file TilePlot.java.
References anl.verdi.plot.types.AbstractTilePlot.frame.
anl.verdi.plot.types.TilePlot.TilePlot (DataFrame frame, PlotConfiguration config)
Definition at line 75 of file TilePlot.java.
References anl.verdi.plot.types.AbstractTilePlot.chart, anl.verdi.plot.types.AbstractTilePlot.config, anl.verdi.plot.types.AbstractTilePlot.configure(), anl.verdi.plot.types.AbstractTilePlot.frame, anl.verdi.plot.types.AbstractTilePlot.getPlotConfiguration(), anl.verdi.plot.config.PlotConfiguration.getSubtitle1(), anl.verdi.plot.types.AbstractTilePlot.layer, anl.verdi.plot.types.AbstractPlot.panel, anl.verdi.plot.config.PlotConfiguration.PLOT_TYPE, anl.verdi.formula.Formula.Type.TILE, and anl.verdi.plot.types.AbstractTilePlot.timeStep.
Member Function Documentation
void anl.verdi.plot.types.TilePlot.addObsAnnotation (ObsEvaluator eval, int shapeSize, int strokeSize)
Definition at line 101 of file TilePlot.java.
void anl.verdi.plot.types.TilePlot.addObsAnnotation (ObsEvaluator eval, int shapeSize, int strokeSize, ObsAnnotation.Symbol symbol)
Definition at line 105 of file TilePlot.java.
References anl.verdi.plot.types.AbstractTilePlot.chart, anl.verdi.plot.types.AbstractTilePlot.frame, anl.verdi.data.DataFrame.getAxes(), anl.verdi.plot.types.AbstractTilePlot.layer, anl.verdi.plot.types.AbstractTilePlot.map, and anl.verdi.plot.types.AbstractTilePlot.timeStep.
void anl.verdi.plot.types.TilePlot.addObsOverlay () protected
Definition at line 112 of file TilePlot.java.
void anl.verdi.plot.types.TilePlot.addVectorAnnotation (VectorEvaluator eval)
Definition at line 96 of file TilePlot.java.
References anl.verdi.plot.types.AbstractTilePlot.chart, anl.verdi.plot.types.AbstractTilePlot.frame, anl.verdi.data.DataFrame.getAxes(), and anl.verdi.plot.types.AbstractTilePlot.timeStep.
void anl.verdi.plot.types.TilePlot.addVectorsOverlay () protected
Definition at line 117 of file TilePlot.java.
void anl.verdi.plot.types.TilePlot.createSubtitle () protected
Definition at line 358 of file TilePlot.java.
References anl.verdi.plot.types.AbstractTilePlot.chart, anl.verdi.plot.types.AbstractTilePlot.frame, anl.verdi.data.DataFrame.getAxes(), anl.verdi.plot.types.AbstractTilePlot.getLatLonForAxisPoint(), anl.verdi.plot.types.TilePlot.getMinMaxPoints(), anl.verdi.plot.types.AbstractTilePlot.showLatLon, anl.verdi.plot.types.AbstractTilePlot.subTitle1Index, and anl.verdi.plot.types.AbstractTilePlot.timeStep.
Referenced by anl.verdi.plot.types.TilePlot.updateTimeStepLayer().
JMapPane anl.verdi.plot.types.TilePlot.getMapPane ()
Gets the JMapPane that contains the mapping portion of the plot component.
Returns
the mapping panel that contains the mapping portion of the plot component.
Implements anl.verdi.plot.gui.Plot.
Definition at line 521 of file TilePlot.java.
DataUtilities.MinMax anl.verdi.plot.types.TilePlot.getMinMax () protected
Definition at line 309 of file TilePlot.java.
References anl.verdi.plot.types.AbstractTilePlot.frame, anl.verdi.plot.types.AbstractTilePlot.layer, and anl.verdi.plot.types.AbstractTilePlot.timeStep.
DataUtilities.MinMaxPoint anl.verdi.plot.types.TilePlot.getMinMaxPoints () protected
Gets the MinMax points for this plot.
Returns
the MinMax points for this plot.
Definition at line 164 of file TilePlot.java.
References anl.verdi.plot.types.AbstractTilePlot.frame, anl.verdi.plot.types.AbstractTilePlot.layer, and anl.verdi.plot.types.AbstractTilePlot.timeStep.
Referenced by anl.verdi.plot.types.TilePlot.createSubtitle().
String anl.verdi.plot.types.TilePlot.getTitle ()
Gets this plot's current title.
Implements anl.verdi.plot.gui.Plot.
Definition at line 517 of file TilePlot.java.
JToolBar anl.verdi.plot.types.TilePlot.getToolBar ()
Gets a tool bar for this plot. This may return null if there is no tool bar.
Returns
a tool bar for this plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 128 of file TilePlot.java.
References anl.verdi.plot.types.AbstractTilePlot.frame, anl.verdi.data.DataFrame.getAxes(), anl.verdi.data.AxisRange.getExtent(), anl.verdi.data.AxisRange.getOrigin(), anl.verdi.plot.types.AbstractTilePlot.layer, anl.verdi.plot.types.AbstractTilePlot.timeStep, and anl.verdi.plot.types.TilePlot.updateTimeStepLayer().
Formula.Type anl.verdi.plot.types.TilePlot.getType ()
Gets the type of the Plot.
Returns
the type of the Plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 512 of file TilePlot.java.
Point4i [] anl.verdi.plot.types.TilePlot.rectToPoints (Rectangle rect) protected
Definition at line 413 of file TilePlot.java.
References anl.verdi.plot.types.AbstractTilePlot.NO_VAL.
void anl.verdi.plot.types.TilePlot.updateTimeStep (int step)
Updates the plot to show the data at the new timestep.
Parameters
step the new step index
Implements anl.verdi.plot.types.TimeAnimatablePlot.
Definition at line 273 of file TilePlot.java.
References anl.verdi.plot.types.AbstractTilePlot.layer, and anl.verdi.plot.types.TilePlot.updateTimeStepLayer().
void anl.verdi.plot.types.TilePlot.updateTimeStepLayer (int timeStep, int layer)
Definition at line 281 of file TilePlot.java.
References anl.verdi.plot.types.AbstractTilePlot.chart, anl.verdi.plot.types.TilePlot.createSubtitle(), anl.verdi.plot.types.AbstractTilePlot.frame, anl.verdi.plot.types.AbstractTilePlot.layer, and anl.verdi.plot.types.AbstractTilePlot.timeStep.
Referenced by anl.verdi.plot.types.TilePlot.getToolBar(), and anl.verdi.plot.types.TilePlot.updateTimeStep().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/types/TilePlot.java