VERDI: anl.verdi.plot.types.ScatterPlot Class Reference
anl.verdi.plot.types.ScatterPlot Class Reference
Public Member Functions
void viewClosed ()
ScatterPlot (DataFrame xFrame, DataFrame yFrame)
ScatterPlot (DataFrame xFrame, DataFrame yFrame, PlotConfiguration config)
List< DataFrame > getData ()
JToolBar getToolBar ()
JMenuBar getMenuBar ()
void addPlotListener (PlotListener listener)
void removePlotListener (PlotListener listener)
void updateTimeStepLayer (int timeStep, int layer)
JPanel getPanel ()
Formula.Type getType ()
void configure (PlotConfiguration config)
PlotConfiguration getPlotConfiguration ()
void exportData ()
void showSaveDialog (boolean allSteps, boolean allLayers)
String getTitle ()
JMapPane getMapPane ()
Public Member Functions inherited from anl.verdi.plot.types.AbstractPlot
void exportImage (String format, File file, int width, int height) throws IOException
BufferedImage getBufferedImage ()
BufferedImage getBufferedImage (int width, int height)
void configure (PlotConfiguration config)
void configure (PlotConfiguration config, Plot.ConfigSource source)
PlotConfiguration getPlotConfiguration ()
Public Member Functions inherited from anl.verdi.plot.gui.Plot
void configure (PlotConfiguration config, ConfigSource source)
Additional Inherited Members
Protected Attributes inherited from anl.verdi.plot.types.AbstractPlot
VerdiChartPanel panel
Detailed Description
Definition at line 86 of file ScatterPlot.java.
Constructor & Destructor Documentation
anl.verdi.plot.types.ScatterPlot.ScatterPlot (DataFrame xFrame, DataFrame yFrame)
Definition at line 123 of file ScatterPlot.java.
anl.verdi.plot.types.ScatterPlot.ScatterPlot (DataFrame xFrame, DataFrame yFrame, PlotConfiguration config)
Check if a chart theme has been loaded.
Definition at line 128 of file ScatterPlot.java.
References anl.verdi.plot.types.ScatterPlot.configure(), anl.verdi.plot.types.ScatterPlot.getPlotConfiguration(), anl.verdi.plot.config.PlotConfiguration.getSubtitle1(), and anl.verdi.plot.types.AbstractPlot.panel.
Member Function Documentation
void anl.verdi.plot.types.ScatterPlot.addPlotListener (PlotListener listener)
Adds the specified PlotListener.
Parameters
listener the plot listener to add
Implements anl.verdi.plot.gui.Plot.
Definition at line 289 of file ScatterPlot.java.
void anl.verdi.plot.types.ScatterPlot.configure (PlotConfiguration config)
Configure this Plot according to the specified PlotConfiguration.
Parameters
config the new plot configuration
Implements anl.verdi.plot.gui.Plot.
Definition at line 456 of file ScatterPlot.java.
References anl.verdi.plot.types.JChartTitlesLabels.getTitleConfigurator(), and anl.verdi.plot.config.TimeSeriesPlotConfiguration.SERIES_COLOR.
Referenced by anl.verdi.plot.types.ScatterPlot.ScatterPlot().
void anl.verdi.plot.types.ScatterPlot.exportData ()
Export this plot's XY values to a file
Definition at line 529 of file ScatterPlot.java.
References anl.verdi.plot.types.AbstractPlot.panel, and anl.verdi.plot.types.ScatterPlot.showSaveDialog().
Referenced by anl.verdi.plot.types.ScatterPlot.getMenuBar().
List<DataFrame> anl.verdi.plot.types.ScatterPlot.getData ()
Gets the data that this Plot plots.
Returns
the data that this Plot plots.
Implements anl.verdi.plot.gui.Plot.
Definition at line 159 of file ScatterPlot.java.
JMapPane anl.verdi.plot.types.ScatterPlot.getMapPane ()
Gets the JMapPane that contains the mapping portion of the plot component.
Returns
the mapping panel that contains the mapping portion of the plot component.
Implements anl.verdi.plot.gui.Plot.
Definition at line 820 of file ScatterPlot.java.
JMenuBar anl.verdi.plot.types.ScatterPlot.getMenuBar ()
Gets a menu bar for this Plot.
Returns
a menu bar for this Plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 215 of file ScatterPlot.java.
References anl.verdi.plot.types.ScatterPlot.exportData(), and anl.verdi.plot.types.AbstractPlot.panel.
JPanel anl.verdi.plot.types.ScatterPlot.getPanel ()
Gets the entire panel that contains the plot component.
Returns
the entire panel that contains the plot component.
Implements anl.verdi.plot.gui.Plot.
Definition at line 436 of file ScatterPlot.java.
References anl.verdi.plot.types.AbstractPlot.panel.
PlotConfiguration anl.verdi.plot.types.ScatterPlot.getPlotConfiguration ()
Gets this Plot's configuration data.
Returns
this Plot's configuration data.
Implements anl.verdi.plot.gui.Plot.
Definition at line 505 of file ScatterPlot.java.
References anl.verdi.plot.config.PlotConfiguration.FOOTER1_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.FOOTER2_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.LEGEND_SHOW, anl.verdi.plot.config.PlotConfiguration.OBS_SHOW_LEGEND, anl.verdi.plot.config.TimeSeriesPlotConfiguration.SERIES_COLOR, anl.verdi.plot.config.PlotConfiguration.UNITS, anl.verdi.plot.config.PlotConfiguration.UNITS_COLOR, and anl.verdi.plot.config.PlotConfiguration.UNITS_FONT.
Referenced by anl.verdi.plot.types.ScatterPlot.ScatterPlot().
String anl.verdi.plot.types.ScatterPlot.getTitle ()
Gets this plot's current title.
Implements anl.verdi.plot.gui.Plot.
Definition at line 816 of file ScatterPlot.java.
JToolBar anl.verdi.plot.types.ScatterPlot.getToolBar ()
Gets a tool bar for this plot. This may return null if there is no tool bar.
Returns
a tool bar for this plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 172 of file ScatterPlot.java.
References anl.verdi.data.DataFrame.getAxes(), and anl.verdi.plot.types.ScatterPlot.updateTimeStepLayer().
Formula.Type anl.verdi.plot.types.ScatterPlot.getType ()
Gets the type of the Plot.
Returns
the type of the Plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 445 of file ScatterPlot.java.
void anl.verdi.plot.types.ScatterPlot.removePlotListener (PlotListener listener)
Removes the specified PlotListener.
Parameters
listener the plot listener to remove
Implements anl.verdi.plot.gui.Plot.
Definition at line 299 of file ScatterPlot.java.
void anl.verdi.plot.types.ScatterPlot.showSaveDialog (boolean allSteps, boolean allLayers)
Definition at line 564 of file ScatterPlot.java.
References anl.verdi.plot.types.AbstractPlot.panel.
Referenced by anl.verdi.plot.types.ScatterPlot.exportData().
void anl.verdi.plot.types.ScatterPlot.updateTimeStepLayer (int timeStep, int layer)
Definition at line 303 of file ScatterPlot.java.
Referenced by anl.verdi.plot.types.ScatterPlot.getToolBar().
void anl.verdi.plot.types.ScatterPlot.viewClosed ()
Implements anl.verdi.plot.gui.Plot.
Definition at line 106 of file ScatterPlot.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/types/ScatterPlot.java