VERDI: saf.core.ui.dock.DefaultPerspective Class Reference
saf.core.ui.dock.DefaultPerspective Class Reference
Classes
class AddActivation
class DockableActivation
class DockingActivation
class LayoutActivation
class ModeSetActivation
class SelectActivation
class StackActivation
class WorkingAreaActivation
Public Member Functions
DefaultPerspective (String id, String name, CControl control)
boolean isActive ()
void addDockableFrame (String groupId, DockableFrame dockable, boolean show)
void dock (DockableFrame dockable, DockableFrame target)
void dock (DockableFrame dockable, DockableFrame relativeTo, Location location, float fillPercent)
void createGroup (String id, Location location, String relativeTo, float fillPercentage)
void createRootGroup (String id)
void activate ()
boolean reset (File file)
boolean reset (InputStream stream)
void deactivate ()
List< DockableFrame > getDockables ()
Set< DockableFrame > getDockables (String groupID)
Set< String > getGroupIDs ()
String getID ()
String getName ()
void loadLayout (Preferences prefs)
void saveLayout (Preferences prefs)
void saveLayout (File file)
void removeDockable (DockableFrame dockable)
Detailed Description
Default implementation of a perspective. This uses the DockingFrames library for docking.
Author
Nick Collier
Definition at line 47 of file DefaultPerspective.java.
Constructor & Destructor Documentation
saf.core.ui.dock.DefaultPerspective.DefaultPerspective (String id, String name, CControl control)
Creates a DefaultPerspective.
Parameters
name the name of the perspective
id the unique id of the perspective
control the CControl used for the docking of the frame's within the perspective
Definition at line 79 of file DefaultPerspective.java.
Member Function Documentation
void saf.core.ui.dock.DefaultPerspective.activate ()
Activates this Perspective.
Implements saf.core.ui.dock.Perspective.
Definition at line 215 of file DefaultPerspective.java.
References saf.core.ui.dock.DefaultPerspective.isActive(), and saf.core.ui.dock.DefaultPerspective.reset().
void saf.core.ui.dock.DefaultPerspective.addDockableFrame (String groupId, DockableFrame dockable, boolean show)
Adds the specified DockableFrame into the specified group.
Parameters
groupId the id of the group
dockable the DockableFrame to add
show whether or not to display the frame
Implements saf.core.ui.dock.Perspective.
Definition at line 112 of file DefaultPerspective.java.
void saf.core.ui.dock.DefaultPerspective.createGroup (String id, Location location, String relativeTo, float fillPercentage)
Creates group with the specified parameters.
Parameters
id the id of the group
location the location of the group
relativeTo the id of the parent of the created group
fillPercentage the fill percentage of the created group.
Implements saf.core.ui.dock.Perspective.
Definition at line 196 of file DefaultPerspective.java.
void saf.core.ui.dock.DefaultPerspective.createRootGroup (String id)
Creates the root or main group of this Perspective. The root group will have the specified id.
Parameters
id the id of the root group
Implements saf.core.ui.dock.Perspective.
Definition at line 207 of file DefaultPerspective.java.
void saf.core.ui.dock.DefaultPerspective.deactivate ()
Deactivates this Perspective.
Implements saf.core.ui.dock.Perspective.
Definition at line 309 of file DefaultPerspective.java.
References saf.core.ui.dock.DefaultPerspective.getDockables(), and saf.core.ui.dock.DefaultPerspective.isActive().
void saf.core.ui.dock.DefaultPerspective.dock (DockableFrame dockable, DockableFrame target)
Attempts to dock the specified dockable to the target, stacking the dockable on top of the target. This will do nothing if the target is minimized or the dockable has not been added to a group.
Parameters
dockable the dockable to dock
target the target to dock to
Definition at line 152 of file DefaultPerspective.java.
References saf.core.ui.dock.DefaultPerspective.isActive().
void saf.core.ui.dock.DefaultPerspective.dock (DockableFrame dockable, DockableFrame relativeTo, Location location, float fillPercent)
Attempts to dock the specified dockable in some location relative to another dockable. This will not work if relativeTo is minimized or maximized, or if the dockable hasn't been added to a group yet.
Parameters
dockable the dockable to dock
relativeTo the dockable to dock relative to
location the relative location
fillPercent the fill percent that the dockable should take up
Definition at line 174 of file DefaultPerspective.java.
References saf.core.ui.dock.DefaultPerspective.isActive().
List<DockableFrame> saf.core.ui.dock.DefaultPerspective.getDockables ()
Gets all the DockableFrames currently in this perspective.
Returns
all the DockableFrames currently in this perspective.
Implements saf.core.ui.dock.Perspective.
Definition at line 359 of file DefaultPerspective.java.
Referenced by saf.core.ui.dock.DefaultPerspective.deactivate().
Set<DockableFrame> saf.core.ui.dock.DefaultPerspective.getDockables (String groupID)
Gets all the DockableFrames in the specified group.
Parameters
groupID the id of the group whose dockables should be returned
Returns
all the DockableFrames in the specified group.
Implements saf.core.ui.dock.Perspective.
Definition at line 375 of file DefaultPerspective.java.
Set<String> saf.core.ui.dock.DefaultPerspective.getGroupIDs ()
Gets the ids of all the groups in this Perspective.
Returns
the ids of all the groups in this Perspective.
Implements saf.core.ui.dock.Perspective.
Definition at line 391 of file DefaultPerspective.java.
String saf.core.ui.dock.DefaultPerspective.getID ()
Gets the id of this Perspective.
Returns
the id of this Perspective.
Implements saf.core.ui.dock.Perspective.
Definition at line 400 of file DefaultPerspective.java.
Referenced by saf.core.ui.dock.DefaultDockingManager.init(), and saf.core.ui.dock.DefaultDockingManager.setPerspective().
String saf.core.ui.dock.DefaultPerspective.getName ()
Gets the name of this Perspective.
Returns
the name of this Perspective.
Implements saf.core.ui.dock.Perspective.
Definition at line 409 of file DefaultPerspective.java.
boolean saf.core.ui.dock.DefaultPerspective.isActive ()
Gets whether or not this Perspective is the active perspective.
Returns
true if this perspective is active, otherwise false.
Implements saf.core.ui.dock.Perspective.
Definition at line 98 of file DefaultPerspective.java.
Referenced by saf.core.ui.dock.DefaultPerspective.activate(), saf.core.ui.dock.DefaultPerspective.deactivate(), saf.core.ui.dock.DefaultPerspective.dock(), saf.core.ui.dock.DefaultPerspective.removeDockable(), and saf.core.ui.dock.DefaultPerspective.saveLayout().
void saf.core.ui.dock.DefaultPerspective.loadLayout (Preferences prefs)
Loads a layout. Depending on whether this Perspective uses the Preferences to store the layout, the prefs object may contain the layout data.
Parameters
prefs repository of the layout data
Implements saf.core.ui.dock.Perspective.
Definition at line 420 of file DefaultPerspective.java.
void saf.core.ui.dock.DefaultPerspective.removeDockable (DockableFrame dockable)
Removes the specified dockable from this Perspective.
Parameters
dockable the dockable to remove
Implements saf.core.ui.dock.Perspective.
Definition at line 504 of file DefaultPerspective.java.
References saf.core.ui.dock.DockableCommand.getSubjects(), and saf.core.ui.dock.DefaultPerspective.isActive().
boolean saf.core.ui.dock.DefaultPerspective.reset (File file)
Resets the layout from a layout stored in a file.
Parameters
file the file to reset the layout from.
Implements saf.core.ui.dock.Perspective.
Definition at line 243 of file DefaultPerspective.java.
Referenced by saf.core.ui.dock.DefaultPerspective.activate().
boolean saf.core.ui.dock.DefaultPerspective.reset (InputStream stream)
Resets the layout from a layout stored in a stream.
Parameters
stream the stream to reset the layout from.
Implements saf.core.ui.dock.Perspective.
Definition at line 257 of file DefaultPerspective.java.
void saf.core.ui.dock.DefaultPerspective.saveLayout (Preferences prefs)
Saves the frame layout.
Parameters
prefs optional preferences repository where the layout can be saved
Implements saf.core.ui.dock.Perspective.
Definition at line 462 of file DefaultPerspective.java.
void saf.core.ui.dock.DefaultPerspective.saveLayout (File file)
Saves the current layout to the specified file.
Parameters
file the file to save the layout to
Implements saf.core.ui.dock.Perspective.
Definition at line 473 of file DefaultPerspective.java.
References saf.core.ui.dock.DefaultPerspective.isActive().
The documentation for this class was generated from the following file:
verdi_saf_ui/src/saf/core/ui/dock/DefaultPerspective.java