VERDI: saf.core.ui.dock.StateChanger Class Reference
saf.core.ui.dock.StateChanger Class Reference
Public Member Functions
StateChanger (CControl control, DefaultDockingManager dockingManager)
void addDockableFrameListener (DockableFrameListener listener)
void removeDockableFrameListener (DockableFrameListener listener)
void closeDockable (String perspectiveID, CDockable dockable)
void closeDockable (CDockable dockable)
void fixFocusPolicy (DockableFrame frame)
void restoreDockable (CDockable dockable)
void floatDockable (CDockable dockable)
void maximizeDockable (CDockable dockable)
void minimizeDockable (CDockable dockable, DockingManager.MinimizeLocation minLocation)
Detailed Description
Changes a dockable's state – minimized, normalized, etc.
Author
Nick Collier
Definition at line 41 of file StateChanger.java.
Constructor & Destructor Documentation
saf.core.ui.dock.StateChanger.StateChanger (CControl control, DefaultDockingManager dockingManager)
Creates a StateChanger that uses the specified control to effect the state changes.
Parameters
control the control to use to change the state
dockingManager the dockingManger used by this StateChanger
Definition at line 62 of file StateChanger.java.
Member Function Documentation
void saf.core.ui.dock.StateChanger.addDockableFrameListener (DockableFrameListener listener)
Adds the specified DockableFrameListener to listener for state changes fired by this StateChanger.
Parameters
listener the listener to add
Definition at line 74 of file StateChanger.java.
void saf.core.ui.dock.StateChanger.closeDockable (String perspectiveID, CDockable dockable)
Attempts to close the specified dockable in the specified perspective.
Parameters
perspectiveID the perspective id
dockable the dockable to close
Definition at line 96 of file StateChanger.java.
References saf.core.ui.dock.StateChanger.fixFocusPolicy(), saf.core.ui.event.DockableFrameEvent.getDockable(), and saf.core.ui.event.DockableFrameEvent.isHandled().
void saf.core.ui.dock.StateChanger.closeDockable (CDockable dockable)
Attempts to close the specified dockable in the current perspective.
Parameters
dockable the dockable to close
Definition at line 128 of file StateChanger.java.
References saf.core.ui.dock.StateChanger.fixFocusPolicy(), saf.core.ui.event.DockableFrameEvent.getDockable(), and saf.core.ui.event.DockableFrameEvent.isHandled().
void saf.core.ui.dock.StateChanger.fixFocusPolicy (DockableFrame frame)
Fixes the focus policy of any components in the frame's container hierarchy, if necessary. This works around an error arising from Swing's focus policies interacting with the dockable frames library.
Parameters
frame the frame that may need fixing
Definition at line 163 of file StateChanger.java.
Referenced by saf.core.ui.dock.StateChanger.closeDockable(), saf.core.ui.dock.StateChanger.floatDockable(), saf.core.ui.dock.StateChanger.maximizeDockable(), saf.core.ui.dock.StateChanger.minimizeDockable(), and saf.core.ui.dock.StateChanger.restoreDockable().
void saf.core.ui.dock.StateChanger.floatDockable (CDockable dockable)
Attempts to float the specified dockable.
Parameters
dockable the dockable to float
Definition at line 219 of file StateChanger.java.
References saf.core.ui.dock.StateChanger.fixFocusPolicy(), saf.core.ui.event.DockableFrameEvent.getDockable(), and saf.core.ui.event.DockableFrameEvent.isHandled().
void saf.core.ui.dock.StateChanger.maximizeDockable (CDockable dockable)
Attempts to maximize the specified dockable.
Parameters
dockable the dockable to maximize
Definition at line 257 of file StateChanger.java.
References saf.core.ui.dock.StateChanger.fixFocusPolicy(), saf.core.ui.event.DockableFrameEvent.getDockable(), and saf.core.ui.event.DockableFrameEvent.isHandled().
void saf.core.ui.dock.StateChanger.minimizeDockable (CDockable dockable, DockingManager.MinimizeLocation minLocation)
Attempts to minimize the specified dockable to the specified location.
Parameters
dockable the dockable to minimize
minLocation the location to minimize to
Definition at line 288 of file StateChanger.java.
References saf.core.ui.dock.StateChanger.fixFocusPolicy(), saf.core.ui.event.DockableFrameEvent.getDockable(), and saf.core.ui.event.DockableFrameEvent.isHandled().
void saf.core.ui.dock.StateChanger.removeDockableFrameListener (DockableFrameListener listener)
Removes the specified DockableFrameListener.
Parameters
listener the listener to remove
Definition at line 84 of file StateChanger.java.
void saf.core.ui.dock.StateChanger.restoreDockable (CDockable dockable)
Attempts to restore the specified dockable.
Parameters
dockable the dockable to restore
Definition at line 189 of file StateChanger.java.
References saf.core.ui.dock.StateChanger.fixFocusPolicy(), saf.core.ui.event.DockableFrameEvent.getDockable(), and saf.core.ui.event.DockableFrameEvent.isHandled().
The documentation for this class was generated from the following file:
verdi_saf_ui/src/saf/core/ui/dock/StateChanger.java