VERDI: anl.verdi.area.WDTWizardWindow Class Reference
anl.verdi.area.WDTWizardWindow Class Reference
Public Member Functions
WDTWizardWindow (Frame fr, String title, boolean state)
String[] getCardNames ()
String[] getCardTitles ()
String getTitleFor (String card)
Protected Member Functions
void showCard (CardChoice card)
Protected Attributes
String preTitle
Detailed Description
File Name:OpenModelFileWindow.java Description:
Version
April 2004
Author
Mary Ann Bitz
Argonne National Laboratory
Definition at line 18 of file WDTWizardWindow.java.
Constructor & Destructor Documentation
anl.verdi.area.WDTWizardWindow.WDTWizardWindow (Frame fr, String title, boolean state)
Constructor for the window to open model files
Parameters
fr the parent window
title the title of the window
state whether the window should be blocking
Definition at line 31 of file WDTWizardWindow.java.
References anl.verdi.area.WDTWizardWindow.preTitle.
Member Function Documentation
String [] anl.verdi.area.WDTWizardWindow.getCardNames ()
Definition at line 41 of file WDTWizardWindow.java.
Referenced by anl.verdi.area.WDTWizardWindow.getTitleFor().
String [] anl.verdi.area.WDTWizardWindow.getCardTitles ()
Definition at line 42 of file WDTWizardWindow.java.
Referenced by anl.verdi.area.WDTWizardWindow.getTitleFor().
String anl.verdi.area.WDTWizardWindow.getTitleFor (String card)
Definition at line 43 of file WDTWizardWindow.java.
References anl.verdi.area.WDTWizardWindow.getCardNames(), anl.verdi.area.WDTWizardWindow.getCardTitles(), and anl.verdi.area.WDTWizardWindow.preTitle.
Referenced by anl.verdi.area.WDTWizardWindow.showCard().
void anl.verdi.area.WDTWizardWindow.showCard (CardChoice card) protected
Definition at line 37 of file WDTWizardWindow.java.
References anl.verdi.area.WDTWizardWindow.getTitleFor().
Member Data Documentation
String anl.verdi.area.WDTWizardWindow.preTitle protected
Definition at line 23 of file WDTWizardWindow.java.
Referenced by anl.verdi.area.WDTWizardWindow.getTitleFor(), and anl.verdi.area.WDTWizardWindow.WDTWizardWindow().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/WDTWizardWindow.java