VERDI: anl.verdi.gui.DatasetListElement Class Reference
anl.verdi.gui.DatasetListElement Class Reference
Public Member Functions
DatasetListElement (Dataset dataset)
Dataset getDataset ()
String toString ()
Axes< CoordAxis > getAxes ()
Public Member Functions inherited from anl.verdi.gui.AbstractListElement
boolean isLayerUsed ()
void setLayerUsed (boolean layerUsed)
boolean isTimeUsed ()
void setTimeUsed (boolean timeUsed)
int getLayerMax ()
void setLayerMax (int layerMax)
int getLayerMin ()
void setLayerMin (int layerMin)
int getTimeMax ()
void setTimeMax (int timeMax)
int getTimeMin ()
void setTimeMin (int timeMin)
int getXMax ()
void setXMax (int xMax)
int getXMin ()
void setXMin (int xMin)
int getYMax ()
void setYMax (int yMax)
int getYMin ()
void setYMin (int yMin)
boolean isXYUsed ()
void setXYUsed (boolean xyUsed)
void setDomain (int xMin, int xMax, int yMin, int yMax)
abstract Axes< CoordAxis > getAxes ()
abstract Dataset getDataset ()
Additional Inherited Members
Static Public Attributes inherited from anl.verdi.gui.AbstractListElement
static int NO_TIME_VALUE = -1
static int NO_LAYER_VALUE = -1
Protected Attributes inherited from anl.verdi.gui.AbstractListElement
int timeMin
int timeMax
int layerMin
int layerMax
Detailed Description
Element in the dataset list model. Stores info about the dataset and its current ranges.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 13 of file DatasetListElement.java.
Constructor & Destructor Documentation
anl.verdi.gui.DatasetListElement.DatasetListElement (Dataset dataset)
Definition at line 17 of file DatasetListElement.java.
References anl.verdi.data.CoordAxis.getRange(), anl.verdi.gui.AbstractListElement.layerMax, anl.verdi.gui.AbstractListElement.layerMin, anl.verdi.gui.AbstractListElement.NO_LAYER_VALUE, anl.verdi.gui.AbstractListElement.NO_TIME_VALUE, anl.verdi.gui.AbstractListElement.timeMax, and anl.verdi.gui.AbstractListElement.timeMin.
Member Function Documentation
Axes<CoordAxis> anl.verdi.gui.DatasetListElement.getAxes ()
Definition at line 48 of file DatasetListElement.java.
Dataset anl.verdi.gui.DatasetListElement.getDataset ()
Definition at line 36 of file DatasetListElement.java.
Referenced by anl.verdi.gui.DatasetListModel.removeDataset(), and anl.verdi.gui.DatasetListModel.removeDatasetAt().
String anl.verdi.gui.DatasetListElement.toString ()
Definition at line 40 of file DatasetListElement.java.
References anl.verdi.data.Dataset.isObs().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/gui/DatasetListElement.java