VERDI: anl.verdi.area.target.TargetFileCard Class Reference
anl.verdi.area.target.TargetFileCard Class Reference
Classes
class TargetPanel
Public Member Functions
TargetFileCard (WizardWindow win)
File[] getSelectedFiles ()
boolean doAction (String nameString, CoordinateReferenceSystem proj)
boolean backAction ()
boolean nextAction ()
void setMustSelectOne (boolean mustSelectOne)
Static Public Member Functions
static String getDefaultPath ()
Detailed Description
Definition at line 28 of file TargetFileCard.java.
Constructor & Destructor Documentation
anl.verdi.area.target.TargetFileCard.TargetFileCard (WizardWindow win)
Definition at line 94 of file TargetFileCard.java.
References anl.verdi.area.target.Target.NAME.
Member Function Documentation
boolean anl.verdi.area.target.TargetFileCard.backAction ()
Definition at line 146 of file TargetFileCard.java.
boolean anl.verdi.area.target.TargetFileCard.doAction (String nameString, CoordinateReferenceSystem proj)
Definition at line 128 of file TargetFileCard.java.
static String anl.verdi.area.target.TargetFileCard.getDefaultPath () static
Returns
Returns the defaultPath.
Definition at line 162 of file TargetFileCard.java.
File [] anl.verdi.area.target.TargetFileCard.getSelectedFiles ()
Definition at line 124 of file TargetFileCard.java.
Referenced by anl.verdi.area.target.TargetFileCard.nextAction().
boolean anl.verdi.area.target.TargetFileCard.nextAction ()
Definition at line 150 of file TargetFileCard.java.
References anl.verdi.area.target.TargetFileCard.getSelectedFiles().
Referenced by anl.verdi.area.target.OpenTargetWindow.nextAction().
void anl.verdi.area.target.TargetFileCard.setMustSelectOne (boolean mustSelectOne)
Definition at line 166 of file TargetFileCard.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/target/TargetFileCard.java