VERDI: anl.verdi.plot.config.VertCrossPlotConfiguration Class Reference
anl.verdi.plot.config.VertCrossPlotConfiguration Class Reference
Public Member Functions
VertCrossPlotConfiguration ()
VertCrossPlotConfiguration (PlotConfiguration config)
void setCrossSectionType (VerticalCrossSectionPlot.CrossSectionType type)
VerticalCrossSectionPlot.CrossSectionType getCrossSectionType ()
void setCrossSectionRowCol (int rowOrCol)
Integer getCrossSectionRowCol ()
Public Member Functions inherited from anl.verdi.plot.config.TilePlotConfiguration
TilePlotConfiguration ()
TilePlotConfiguration (PlotConfiguration config)
ColorMap getColorMap ()
void setColorMap (ColorMap map)
void setGridLines (boolean enable, Color lineColor)
Public Member Functions inherited from anl.verdi.plot.config.PlotConfiguration
PlotConfiguration ()
PlotConfiguration (File file) throws IOException
PlotConfiguration (PlotConfiguration config)
void initTilePlotConf ()
void putObject (Object key, Object value)
void removeObject (Object key)
Object getObject (Object key)
void setProperty (String name, String value)
String getProperty (String name)
void setSubtitle1 (String val)
void setSubtitle2 (String val)
void setTitle (String val)
void setUnits (String val)
String getSubtitle1 ()
String getSubtitle2 ()
String getTitle ()
String getShowTitle ()
String getShowSubtitle1 ()
String getShowSubtitle2 ()
String getShowFooter1 ()
String getShowFooter2 ()
String getUnits ()
String getConfigFileName ()
void setConfigFileName (String fileName)
String getString (String key)
Color getColor (String key)
Font getFont (String key)
File getPreviousFolder ()
void setPreviousFolder (File file)
void merge (PlotConfiguration config)
void setShowTitle (String show)
void setShowTitle (Boolean aBool)
void setShowSubtitle1 (String show)
void setShowSubtitle2 (String show)
void save (File file, boolean saveTitle) throws IOException
Static Public Attributes
static final String CROSS_SECTION_TYPE
static final String CROSS_SECTION_INDEX
Static Public Attributes inherited from anl.verdi.plot.config.TilePlotConfiguration
static final String COLOR_MAP = TilePlotConfiguration.class.getName() + "_color_map"
static final String SHOW_GRID_LINES = TilePlotConfiguration.class.getName() + "_show_grid_lines"
static final String GRID_LINE_COLOR = TilePlotConfiguration.class.getName() + "_grid_line_color"
static final String OBS_SHAPE_SIZE = TilePlotConfiguration.class.getName() + "_obs_shape_size"
static final String OBS_STROKE_SIZE = TilePlotConfiguration.class.getName() + "_obs_stroke_size"
Static Public Attributes inherited from anl.verdi.plot.config.PlotConfiguration
static final String PLOT_TYPE = PlotConfiguration.class.getName() + ".plot_type"
static final String TITLE = PlotConfiguration.class.getName() + ".title"
static final String TITLE_FONT = PlotConfiguration.class.getName() + ".title_font"
static final String TITLE_COLOR = PlotConfiguration.class.getName() + ".title_color"
static final String TITLE_SIZE = PlotConfiguration.class.getName() + ".title_size"
static final String TITLE_SHOW_LINE = PlotConfiguration.class.getName() + ".title_show_line"
static final String SUBTITLE_1 = PlotConfiguration.class.getName() + ".subtitle1"
static final String SUBTITLE_1_FONT = PlotConfiguration.class.getName() + ".subtitle1_font"
static final String SUBTITLE_1_COLOR = PlotConfiguration.class.getName() + ".subtitle1_color"
static final String SUBTITLE_1_SIZE = PlotConfiguration.class.getName() + ".subtitle1_size"
static final String SUBTITLE_1_SHOW_LINE = PlotConfiguration.class.getName() + ".subtitle1_show_line"
static final String SUBTITLE_2 = PlotConfiguration.class.getName() + ".subtitle2"
static final String SUBTITLE_2_FONT = PlotConfiguration.class.getName() + ".subtitle2_font"
static final String SUBTITLE_2_COLOR = PlotConfiguration.class.getName() + ".subtitle2_color"
static final String SUBTITLE_2_SIZE = PlotConfiguration.class.getName() + ".subtitle2_size"
static final String SUBTITLE_2_SHOW_LINE = PlotConfiguration.class.getName() + ".subtitle2_show_line"
static final String LEGEND_SHOW = PlotConfiguration.class.getName() + ".legend_show"
static final String UNITS = PlotConfiguration.class.getName() + ".units"
static final String UNITS_FONT = PlotConfiguration.class.getName() + ".units_font"
static final String UNITS_COLOR = PlotConfiguration.class.getName() + ".units_color"
static final String UNITS_SIZE = PlotConfiguration.class.getName() + ".units_size"
static final String UNITS_SHOW_TICK = PlotConfiguration.class.getName() + ".units_show_tick"
static final String UNITS_TICK_COLOR = PlotConfiguration.class.getName() + ".units_tick_color"
static final String UNITS_TICK_FONT = PlotConfiguration.class.getName() + ".units_tick_font"
static final String UNITS_TICK_SIZE = PlotConfiguration.class.getName() + ".units_tick_size"
static final String UNITS_TICK_NUMBER = PlotConfiguration.class.getName() + ".units_tick_number"
static final String DOMAIN_LABEL = PlotConfiguration.class.getName() + ".domain"
static final String DOMAIN_FONT = PlotConfiguration.class.getName() + ".domain_font"
static final String DOMAIN_COLOR = PlotConfiguration.class.getName() + ".domain_color"
static final String DOMAIN_SIZE = PlotConfiguration.class.getName() + ".domain_size"
static final String DOMAIN_SHOW_TICK = PlotConfiguration.class.getName() + ".domain_show_tick"
static final String DOMAIN_TICK_COLOR = PlotConfiguration.class.getName() + ".domain_tick_color"
static final String DOMAIN_TICK_FONT = PlotConfiguration.class.getName() + ".domain_tick_font"
static final String DOMAIN_TICK_SIZE = PlotConfiguration.class.getName() + ".domain_tick_size"
static final String DOMAIN_TICK_NUMBER = PlotConfiguration.class.getName() + ".domain_tick_number"
static final String DOMAIN_TICK_LABEL_FORMAT = PlotConfiguration.class.getName() + ".domain_tick_label_format"
static final String DOMAIN_TICK_LABEL_FORMAT_4CAT = PlotConfiguration.class.getName() + ".domain_tick_label_format_4cat"
static final String DOMAIN_TICK_LABEL_ORIENTATION = PlotConfiguration.class.getName() + ".domain_tick_label_orientation"
static final String RANGE_LABEL = PlotConfiguration.class.getName() + ".range"
static final String RANGE_FONT = PlotConfiguration.class.getName() + ".range_font"
static final String RANGE_COLOR = PlotConfiguration.class.getName() + ".range_color"
static final String RANGE_SIZE = PlotConfiguration.class.getName() + ".range_size"
static final String RANGE_SHOW_TICK = PlotConfiguration.class.getName() + ".range_show_tick"
static final String RANGE_TICK_COLOR = PlotConfiguration.class.getName() + ".range_tick_color"
static final String RANGE_TICK_FONT = PlotConfiguration.class.getName() + ".range_tick_font"
static final String RANGE_TICK_SIZE = PlotConfiguration.class.getName() + ".range_tick_size"
static final String RANGE_TICK_NUMBER = PlotConfiguration.class.getName() + ".range_tick_number"
static final String Z_LABEL = PlotConfiguration.class.getName() + ".z"
static final String Z_FONT = PlotConfiguration.class.getName() + ".z_font"
static final String Z_COLOR = PlotConfiguration.class.getName() + ".z_color"
static final String Z_SHOW_TICK = PlotConfiguration.class.getName() + ".z_show_tick"
static final String Z_TICK_COLOR = PlotConfiguration.class.getName() + ".z_tick_color"
static final String Z_TICK_FONT = PlotConfiguration.class.getName() + ".z_tick_font"
static final String Z_TICK_NUMBER = PlotConfiguration.class.getName() + ".z_tick_number"
static final String FOOTER1 = PlotConfiguration.class.getName() + ".footer_line_1"
static final String FOOTER1_SHOW_LINE = PlotConfiguration.class.getName() + ".footer_show_line_1"
static final String FOOTER1_AUTO_TEXT = PlotConfiguration.class.getName() + ".footer_line_1_auto_text"
static final String FOOTER1_COLOR = PlotConfiguration.class.getName() + ".footer_line_1_color"
static final String FOOTER1_FONT = PlotConfiguration.class.getName() + ".footer_line_1_font"
static final String FOOTER1_SIZE = PlotConfiguration.class.getName() + ".footer_line_1_size"
static final String FOOTER2 = PlotConfiguration.class.getName() + ".footer_line_2"
static final String FOOTER2_SHOW_LINE = PlotConfiguration.class.getName() + ".footer_show_line_2"
static final String FOOTER2_AUTO_TEXT = PlotConfiguration.class.getName() + ".footer_line_2_auto_text"
static final String FOOTER2_COLOR = PlotConfiguration.class.getName() + ".footer_line_2_color"
static final String FOOTER2_FONT = PlotConfiguration.class.getName() + ".footer_line_2_font"
static final String FOOTER2_SIZE = PlotConfiguration.class.getName() + ".footer_line_2_size"
static final String OBS_SHOW_LEGEND = PlotConfiguration.class.getName() + ".obs_show_legend"
static final String OBS_LEGEND_COLOR = PlotConfiguration.class.getName() + ".obs_legend_color"
static final String OBS_LEGEND_FONT = PlotConfiguration.class.getName() + ".obs_legend_font"
static final String OBS_LEGEND_SIZE = PlotConfiguration.class.getName() + ".obs_legend_size"
static final String CONFIG_FILE = PlotConfiguration.class.getName() + ".config_file"
Additional Inherited Members
Protected Attributes inherited from anl.verdi.plot.config.PlotConfiguration
Properties props = new Properties()
Detailed Description
Configuration info for vertical cross section plots.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 11 of file VertCrossPlotConfiguration.java.
Constructor & Destructor Documentation
anl.verdi.plot.config.VertCrossPlotConfiguration.VertCrossPlotConfiguration ()
Definition at line 18 of file VertCrossPlotConfiguration.java.
anl.verdi.plot.config.VertCrossPlotConfiguration.VertCrossPlotConfiguration (PlotConfiguration config)
Definition at line 22 of file VertCrossPlotConfiguration.java.
Member Function Documentation
Integer anl.verdi.plot.config.VertCrossPlotConfiguration.getCrossSectionRowCol ()
Definition at line 38 of file VertCrossPlotConfiguration.java.
References anl.verdi.plot.config.VertCrossPlotConfiguration.CROSS_SECTION_INDEX, and anl.verdi.plot.config.PlotConfiguration.getObject().
Referenced by anl.verdi.plot.types.VerticalCrossSectionPlot.VerticalCrossSectionPlot().
VerticalCrossSectionPlot.CrossSectionType anl.verdi.plot.config.VertCrossPlotConfiguration.getCrossSectionType ()
Definition at line 30 of file VertCrossPlotConfiguration.java.
References anl.verdi.plot.config.VertCrossPlotConfiguration.CROSS_SECTION_TYPE, and anl.verdi.plot.config.PlotConfiguration.getObject().
void anl.verdi.plot.config.VertCrossPlotConfiguration.setCrossSectionRowCol (int rowOrCol)
Definition at line 34 of file VertCrossPlotConfiguration.java.
References anl.verdi.plot.config.VertCrossPlotConfiguration.CROSS_SECTION_INDEX, and anl.verdi.plot.config.PlotConfiguration.putObject().
void anl.verdi.plot.config.VertCrossPlotConfiguration.setCrossSectionType (VerticalCrossSectionPlot.CrossSectionType type)
Definition at line 26 of file VertCrossPlotConfiguration.java.
References anl.verdi.plot.config.VertCrossPlotConfiguration.CROSS_SECTION_TYPE, and anl.verdi.plot.config.PlotConfiguration.putObject().
Member Data Documentation
final String anl.verdi.plot.config.VertCrossPlotConfiguration.CROSS_SECTION_INDEX static
Initial value:
=
                    VertCrossPlotConfiguration.class.getName() + ".cross_section_index"
Definition at line 15 of file VertCrossPlotConfiguration.java.
Referenced by anl.verdi.plot.config.VertCrossPlotConfiguration.getCrossSectionRowCol(), and anl.verdi.plot.config.VertCrossPlotConfiguration.setCrossSectionRowCol().
final String anl.verdi.plot.config.VertCrossPlotConfiguration.CROSS_SECTION_TYPE static
Initial value:
=
                    VertCrossPlotConfiguration.class.getName() + ".cross_section_type"
Definition at line 13 of file VertCrossPlotConfiguration.java.
Referenced by anl.verdi.plot.config.VertCrossPlotConfiguration.getCrossSectionType(), and anl.verdi.plot.config.VertCrossPlotConfiguration.setCrossSectionType().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/config/VertCrossPlotConfiguration.java