VERDI: anl.verdi.plot.util.NeuQuant Class Reference
anl.verdi.plot.util.NeuQuant Class Reference
Public Member Functions
NeuQuant (byte[] thepic, int len, int sample)
byte[] colorMap ()
void inxbuild ()
void learn ()
int map (int b, int g, int r)
byte[] process ()
void unbiasnet ()
Protected Member Functions
void alterneigh (int rad, int i, int b, int g, int r)
void altersingle (int alpha, int i, int b, int g, int r)
int contest (int b, int g, int r)
Protected Attributes
int alphadec
byte[] thepicture
int lengthcount
int samplefac
int[][] network
int[] netindex = new int[256]
int[] bias = new int[netsize]
int[] freq = new int[netsize]
int[] radpower = new int[initrad]
Static Protected Attributes
static final int netsize = 256
static final int prime1 = 499
static final int prime2 = 491
static final int prime3 = 487
static final int prime4 = 503
static final int minpicturebytes = (3 * prime4)
static final int maxnetpos = (netsize - 1)
static final int netbiasshift = 4
static final int ncycles = 100
static final int intbiasshift = 16
static final int intbias = (((int) 1) << intbiasshift)
static final int gammashift = 10
static final int gamma = (((int) 1) << gammashift)
static final int betashift = 10
static final int beta = (intbias >> betashift)
static final int betagamma
static final int initrad = (netsize >> 3)
static final int radiusbiasshift = 6
static final int radiusbias = (((int) 1) << radiusbiasshift)
static final int initradius = (initrad * radiusbias)
static final int radiusdec = 30
static final int alphabiasshift = 10
static final int initalpha = (((int) 1) << alphabiasshift)
static final int radbiasshift = 8
static final int radbias = (((int) 1) << radbiasshift)
static final int alpharadbshift = (alphabiasshift + radbiasshift)
static final int alpharadbias = (((int) 1) << alpharadbshift)
Detailed Description
Definition at line 25 of file NeuQuant.java.
Constructor & Destructor Documentation
anl.verdi.plot.util.NeuQuant.NeuQuant (byte[] thepic, int len, int sample)
Definition at line 109 of file NeuQuant.java.
References anl.verdi.plot.util.NeuQuant.bias, anl.verdi.plot.util.NeuQuant.freq, anl.verdi.plot.util.NeuQuant.intbias, anl.verdi.plot.util.NeuQuant.lengthcount, anl.verdi.plot.util.NeuQuant.netbiasshift, anl.verdi.plot.util.NeuQuant.netsize, anl.verdi.plot.util.NeuQuant.network, anl.verdi.plot.util.NeuQuant.samplefac, and anl.verdi.plot.util.NeuQuant.thepicture.
Member Function Documentation
void anl.verdi.plot.util.NeuQuant.alterneigh (int rad, int i, int b, int g, int r) protected
Definition at line 362 of file NeuQuant.java.
References anl.verdi.plot.util.NeuQuant.alpharadbias, anl.verdi.plot.util.NeuQuant.netsize, anl.verdi.plot.util.NeuQuant.network, and anl.verdi.plot.util.NeuQuant.radpower.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
void anl.verdi.plot.util.NeuQuant.altersingle (int alpha, int i, int b, int g, int r) protected
Definition at line 402 of file NeuQuant.java.
References anl.verdi.plot.util.NeuQuant.initalpha, and anl.verdi.plot.util.NeuQuant.network.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
byte [] anl.verdi.plot.util.NeuQuant.colorMap ()
Definition at line 128 of file NeuQuant.java.
References anl.verdi.plot.util.NeuQuant.map(), anl.verdi.plot.util.NeuQuant.netsize, and anl.verdi.plot.util.NeuQuant.network.
Referenced by anl.verdi.plot.util.NeuQuant.process().
int anl.verdi.plot.util.NeuQuant.contest (int b, int g, int r) protected
Definition at line 413 of file NeuQuant.java.
References anl.verdi.plot.util.NeuQuant.beta, anl.verdi.plot.util.NeuQuant.betagamma, anl.verdi.plot.util.NeuQuant.betashift, anl.verdi.plot.util.NeuQuant.bias, anl.verdi.plot.util.NeuQuant.freq, anl.verdi.plot.util.NeuQuant.gammashift, anl.verdi.plot.util.NeuQuant.intbiasshift, anl.verdi.plot.util.NeuQuant.netbiasshift, anl.verdi.plot.util.NeuQuant.netsize, and anl.verdi.plot.util.NeuQuant.network.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
void anl.verdi.plot.util.NeuQuant.inxbuild ()
Definition at line 145 of file NeuQuant.java.
References anl.verdi.plot.util.NeuQuant.maxnetpos, anl.verdi.plot.util.NeuQuant.netindex, anl.verdi.plot.util.NeuQuant.netsize, and anl.verdi.plot.util.NeuQuant.network.
Referenced by anl.verdi.plot.util.NeuQuant.process().
void anl.verdi.plot.util.NeuQuant.learn ()
Definition at line 198 of file NeuQuant.java.
References anl.verdi.plot.util.NeuQuant.alphadec, anl.verdi.plot.util.NeuQuant.alterneigh(), anl.verdi.plot.util.NeuQuant.altersingle(), anl.verdi.plot.util.NeuQuant.contest(), anl.verdi.plot.util.NeuQuant.initalpha, anl.verdi.plot.util.NeuQuant.initradius, anl.verdi.plot.util.NeuQuant.lengthcount, anl.verdi.plot.util.NeuQuant.minpicturebytes, anl.verdi.plot.util.NeuQuant.ncycles, anl.verdi.plot.util.NeuQuant.netbiasshift, anl.verdi.plot.util.NeuQuant.prime1, anl.verdi.plot.util.NeuQuant.prime2, anl.verdi.plot.util.NeuQuant.prime3, anl.verdi.plot.util.NeuQuant.prime4, anl.verdi.plot.util.NeuQuant.radbias, anl.verdi.plot.util.NeuQuant.radiusbiasshift, anl.verdi.plot.util.NeuQuant.radiusdec, anl.verdi.plot.util.NeuQuant.radpower, anl.verdi.plot.util.NeuQuant.samplefac, and anl.verdi.plot.util.NeuQuant.thepicture.
Referenced by anl.verdi.plot.util.NeuQuant.process().
int anl.verdi.plot.util.NeuQuant.map (int b, int g, int r)
Definition at line 274 of file NeuQuant.java.
References anl.verdi.plot.util.NeuQuant.netindex, anl.verdi.plot.util.NeuQuant.netsize, and anl.verdi.plot.util.NeuQuant.network.
Referenced by anl.verdi.plot.util.NeuQuant.colorMap().
byte [] anl.verdi.plot.util.NeuQuant.process ()
Definition at line 339 of file NeuQuant.java.
References anl.verdi.plot.util.NeuQuant.colorMap(), anl.verdi.plot.util.NeuQuant.inxbuild(), anl.verdi.plot.util.NeuQuant.learn(), and anl.verdi.plot.util.NeuQuant.unbiasnet().
void anl.verdi.plot.util.NeuQuant.unbiasnet ()
Definition at line 348 of file NeuQuant.java.
References anl.verdi.plot.util.NeuQuant.netbiasshift, anl.verdi.plot.util.NeuQuant.netsize, and anl.verdi.plot.util.NeuQuant.network.
Referenced by anl.verdi.plot.util.NeuQuant.process().
Member Data Documentation
final int anl.verdi.plot.util.NeuQuant.alphabiasshift = 10 static protected
Definition at line 76 of file NeuQuant.java.
int anl.verdi.plot.util.NeuQuant.alphadec protected
Definition at line 79 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
final int anl.verdi.plot.util.NeuQuant.alpharadbias = (((int) 1) << alpharadbshift) static protected
Definition at line 85 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.alterneigh().
final int anl.verdi.plot.util.NeuQuant.alpharadbshift = (alphabiasshift + radbiasshift) static protected
Definition at line 84 of file NeuQuant.java.
final int anl.verdi.plot.util.NeuQuant.beta = (intbias >> betashift) static protected
Definition at line 64 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.contest().
final int anl.verdi.plot.util.NeuQuant.betagamma static protected
Initial value:
=
        (intbias << (gammashift - betashift))
Definition at line 65 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.contest().
final int anl.verdi.plot.util.NeuQuant.betashift = 10 static protected
Definition at line 63 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.contest().
int [] anl.verdi.plot.util.NeuQuant.bias = new int[netsize] protected
Definition at line 101 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.contest(), and anl.verdi.plot.util.NeuQuant.NeuQuant().
int [] anl.verdi.plot.util.NeuQuant.freq = new int[netsize] protected
Definition at line 103 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.contest(), and anl.verdi.plot.util.NeuQuant.NeuQuant().
final int anl.verdi.plot.util.NeuQuant.gamma = (((int) 1) << gammashift) static protected
Definition at line 62 of file NeuQuant.java.
final int anl.verdi.plot.util.NeuQuant.gammashift = 10 static protected
Definition at line 61 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.contest().
final int anl.verdi.plot.util.NeuQuant.initalpha = (((int) 1) << alphabiasshift) static protected
Definition at line 77 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.altersingle(), and anl.verdi.plot.util.NeuQuant.learn().
final int anl.verdi.plot.util.NeuQuant.initrad = (netsize >> 3) static protected
Definition at line 69 of file NeuQuant.java.
final int anl.verdi.plot.util.NeuQuant.initradius = (initrad * radiusbias) static protected
Definition at line 72 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
final int anl.verdi.plot.util.NeuQuant.intbias = (((int) 1) << intbiasshift) static protected
Definition at line 60 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.NeuQuant().
final int anl.verdi.plot.util.NeuQuant.intbiasshift = 16 static protected
Definition at line 59 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.contest().
int anl.verdi.plot.util.NeuQuant.lengthcount protected
Definition at line 91 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn(), and anl.verdi.plot.util.NeuQuant.NeuQuant().
final int anl.verdi.plot.util.NeuQuant.maxnetpos = (netsize - 1) static protected
Definition at line 54 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.inxbuild().
final int anl.verdi.plot.util.NeuQuant.minpicturebytes = (3 * prime4) static protected
Definition at line 36 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
final int anl.verdi.plot.util.NeuQuant.ncycles = 100 static protected
Definition at line 56 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
final int anl.verdi.plot.util.NeuQuant.netbiasshift = 4 static protected
Definition at line 55 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.contest(), anl.verdi.plot.util.NeuQuant.learn(), anl.verdi.plot.util.NeuQuant.NeuQuant(), and anl.verdi.plot.util.NeuQuant.unbiasnet().
int [] anl.verdi.plot.util.NeuQuant.netindex = new int[256] protected
Definition at line 98 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.inxbuild(), and anl.verdi.plot.util.NeuQuant.map().
final int anl.verdi.plot.util.NeuQuant.netsize = 256 static protected
Definition at line 27 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.alterneigh(), anl.verdi.plot.util.NeuQuant.colorMap(), anl.verdi.plot.util.NeuQuant.contest(), anl.verdi.plot.util.NeuQuant.inxbuild(), anl.verdi.plot.util.NeuQuant.map(), anl.verdi.plot.util.NeuQuant.NeuQuant(), and anl.verdi.plot.util.NeuQuant.unbiasnet().
int [][] anl.verdi.plot.util.NeuQuant.network protected
Definition at line 96 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.alterneigh(), anl.verdi.plot.util.NeuQuant.altersingle(), anl.verdi.plot.util.NeuQuant.colorMap(), anl.verdi.plot.util.NeuQuant.contest(), anl.verdi.plot.util.NeuQuant.inxbuild(), anl.verdi.plot.util.NeuQuant.map(), anl.verdi.plot.util.NeuQuant.NeuQuant(), and anl.verdi.plot.util.NeuQuant.unbiasnet().
final int anl.verdi.plot.util.NeuQuant.prime1 = 499 static protected
Definition at line 31 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
final int anl.verdi.plot.util.NeuQuant.prime2 = 491 static protected
Definition at line 32 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
final int anl.verdi.plot.util.NeuQuant.prime3 = 487 static protected
Definition at line 33 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
final int anl.verdi.plot.util.NeuQuant.prime4 = 503 static protected
Definition at line 34 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
final int anl.verdi.plot.util.NeuQuant.radbias = (((int) 1) << radbiasshift) static protected
Definition at line 83 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
final int anl.verdi.plot.util.NeuQuant.radbiasshift = 8 static protected
Definition at line 82 of file NeuQuant.java.
final int anl.verdi.plot.util.NeuQuant.radiusbias = (((int) 1) << radiusbiasshift) static protected
Definition at line 71 of file NeuQuant.java.
final int anl.verdi.plot.util.NeuQuant.radiusbiasshift = 6 static protected
Definition at line 70 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
final int anl.verdi.plot.util.NeuQuant.radiusdec = 30 static protected
Definition at line 73 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn().
int [] anl.verdi.plot.util.NeuQuant.radpower = new int[initrad] protected
Definition at line 104 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.alterneigh(), and anl.verdi.plot.util.NeuQuant.learn().
int anl.verdi.plot.util.NeuQuant.samplefac protected
Definition at line 93 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn(), and anl.verdi.plot.util.NeuQuant.NeuQuant().
byte [] anl.verdi.plot.util.NeuQuant.thepicture protected
Definition at line 90 of file NeuQuant.java.
Referenced by anl.verdi.plot.util.NeuQuant.learn(), and anl.verdi.plot.util.NeuQuant.NeuQuant().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/util/NeuQuant.java