VERDI: anl.verdi.util.Utilities Class Reference
anl.verdi.util.Utilities Class Reference
Static Public Member Functions
static String formatDate (Date date)
static String formatDate (GregorianCalendar date)
static String formatShortDate (Date date)
static String formatShortDate (GregorianCalendar date)
static String formatNumber (double val)
static String formatLat (double latitude, int fractions)
static String formatLon (double longitude, int fractions)
static boolean is64bitWindows ()
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 14 of file Utilities.java.
Member Function Documentation
static String anl.verdi.util.Utilities.formatDate (Date date) static
Definition at line 23 of file Utilities.java.
static String anl.verdi.util.Utilities.formatDate (GregorianCalendar date) static
Definition at line 28 of file Utilities.java.
static String anl.verdi.util.Utilities.formatLat (double latitude, int fractions) static
Definition at line 57 of file Utilities.java.
References anl.verdi.util.Utilities.formatNumber().
static String anl.verdi.util.Utilities.formatLon (double longitude, int fractions) static
Definition at line 65 of file Utilities.java.
References anl.verdi.util.Utilities.formatNumber().
static String anl.verdi.util.Utilities.formatNumber (double val) static
Definition at line 52 of file Utilities.java.
Referenced by anl.verdi.util.Utilities.formatLat(), and anl.verdi.util.Utilities.formatLon().
static String anl.verdi.util.Utilities.formatShortDate (Date date) static
Definition at line 36 of file Utilities.java.
static String anl.verdi.util.Utilities.formatShortDate (GregorianCalendar date) static
Definition at line 42 of file Utilities.java.
static boolean anl.verdi.util.Utilities.is64bitWindows () static
Definition at line 73 of file Utilities.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/util/Utilities.java