VERDI: anl.verdi.plot.types.JChartTitlesLabels Class Reference
anl.verdi.plot.types.JChartTitlesLabels Class Reference
Public Member Functions
JChartTitlesLabels (JFreeChart chart)
void setTitle (String text)
PlotConfiguration getConfiguration (PlotConfiguration config)
TitleConfigurator getTitleConfigurator ()
Protected Attributes
int subTitle1Index
Detailed Description
Encapsulates the titles in a JFreeChart.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 27 of file JChartTitlesLabels.java.
Constructor & Destructor Documentation
anl.verdi.plot.types.JChartTitlesLabels.JChartTitlesLabels (JFreeChart chart)
Definition at line 32 of file JChartTitlesLabels.java.
References anl.verdi.plot.types.JChartTitlesLabels.subTitle1Index.
Member Function Documentation
PlotConfiguration anl.verdi.plot.types.JChartTitlesLabels.getConfiguration (PlotConfiguration config)
Definition at line 61 of file JChartTitlesLabels.java.
References anl.verdi.plot.config.PlotConfiguration.DOMAIN_COLOR, anl.verdi.plot.config.PlotConfiguration.DOMAIN_FONT, anl.verdi.plot.config.PlotConfiguration.DOMAIN_LABEL, anl.verdi.plot.config.PlotConfiguration.DOMAIN_SHOW_TICK, anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_COLOR, anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_FONT, anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_LABEL_FORMAT, anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_LABEL_ORIENTATION, anl.verdi.plot.config.PlotConfiguration.RANGE_COLOR, anl.verdi.plot.config.PlotConfiguration.RANGE_FONT, anl.verdi.plot.config.PlotConfiguration.RANGE_LABEL, anl.verdi.plot.config.PlotConfiguration.RANGE_SHOW_TICK, anl.verdi.plot.config.PlotConfiguration.RANGE_TICK_COLOR, anl.verdi.plot.config.PlotConfiguration.RANGE_TICK_FONT, anl.verdi.plot.types.JChartTitlesLabels.subTitle1Index, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_FONT, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_FONT, anl.verdi.plot.config.PlotConfiguration.TITLE_COLOR, and anl.verdi.plot.config.PlotConfiguration.TITLE_FONT.
TitleConfigurator anl.verdi.plot.types.JChartTitlesLabels.getTitleConfigurator ()
Definition at line 148 of file JChartTitlesLabels.java.
References anl.verdi.plot.types.JChartTitlesLabels.subTitle1Index.
Referenced by anl.verdi.plot.types.ScatterPlot.configure(), anl.verdi.plot.types.TimeSeriesBarPlot.configure(), and anl.verdi.plot.types.LinePlot.configure().
void anl.verdi.plot.types.JChartTitlesLabels.setTitle (String text)
Definition at line 57 of file JChartTitlesLabels.java.
Member Data Documentation
int anl.verdi.plot.types.JChartTitlesLabels.subTitle1Index protected
Definition at line 30 of file JChartTitlesLabels.java.
Referenced by anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getTitleConfigurator(), and anl.verdi.plot.types.JChartTitlesLabels.JChartTitlesLabels().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/types/JChartTitlesLabels.java