VERDI: anl.verdi.area.MapPolygon Class Reference
anl.verdi.area.MapPolygon Class Reference
Public Member Functions
MapPolygon ()
void draw (AreaTilePlot plot, final double[][] domain, final double[][] gridBounds, final Projector projector, double[] legendLevels, Color[] legendColors, final Graphics graphics, float[][] data, String units, int firstColumn, int firstRow, int xOffset, int yOffset, int width, int height, int currentView, boolean showSelectedOnly)
void calculateValues (AreaTilePlot plot, final double[][] domain, final double[][] gridBounds, final Projector projector, double[] legendLevels, Color[] legendColors, final Graphics graphics, float[][] data, String units, int firstColumn, int firstRow, int xOffset, int yOffset, int width, int height, int currentView, boolean showSelectedOnly)
boolean equalsCachedParameters (final double[][] domain, final double[][] gridBounds, final Projector projector, int xOffset, int yOffset, int width, int height)
void cacheParameters (final double[][] domain, final double[][] gridBounds, final Projector projector, int xOffset, int yOffset, int width, int height)
Static Public Member Functions
static Target getTargetWithin (double lat, double lon)
static ArrayList< Target > getTargetsWithin (Rectangle rect)
Detailed Description
Definition at line 35 of file MapPolygon.java.
Constructor & Destructor Documentation
anl.verdi.area.MapPolygon.MapPolygon ()
Definition at line 63 of file MapPolygon.java.
Member Function Documentation
void anl.verdi.area.MapPolygon.cacheParameters (final double domain[][], final double gridBounds[][], final Projector projector, int xOffset, int yOffset, int width, int height)
Definition at line 310 of file MapPolygon.java.
Referenced by anl.verdi.area.MapPolygon.calculateValues(), and anl.verdi.area.MapPolygon.draw().
void anl.verdi.area.MapPolygon.calculateValues (AreaTilePlot plot, final double domain[][], final double gridBounds[][], final Projector projector, double[] legendLevels, Color[] legendColors, final Graphics graphics, float data[][], String units, int firstColumn, int firstRow, int xOffset, int yOffset, int width, int height, int currentView, boolean showSelectedOnly)
Definition at line 176 of file MapPolygon.java.
References anl.verdi.area.AreaTilePlot.AVERAGES, anl.verdi.area.MapPolygon.cacheParameters(), anl.verdi.area.MapPolygon.equalsCachedParameters(), anl.verdi.area.AreaTilePlot.GRID, and anl.verdi.area.AreaTilePlot.TOTALS.
void anl.verdi.area.MapPolygon.draw (AreaTilePlot plot, final double domain[][], final double gridBounds[][], final Projector projector, double[] legendLevels, Color[] legendColors, final Graphics graphics, float data[][], String units, int firstColumn, int firstRow, int xOffset, int yOffset, int width, int height, int currentView, boolean showSelectedOnly)
Definition at line 68 of file MapPolygon.java.
References anl.verdi.area.AreaTilePlot.AVERAGES, anl.verdi.area.MapPolygon.cacheParameters(), anl.verdi.area.MapPolygon.equalsCachedParameters(), anl.verdi.area.AreaTilePlot.GRID, and anl.verdi.area.AreaTilePlot.TOTALS.
boolean anl.verdi.area.MapPolygon.equalsCachedParameters (final double domain[][], final double gridBounds[][], final Projector projector, int xOffset, int yOffset, int width, int height)
Definition at line 284 of file MapPolygon.java.
Referenced by anl.verdi.area.MapPolygon.calculateValues(), and anl.verdi.area.MapPolygon.draw().
static ArrayList<Target> anl.verdi.area.MapPolygon.getTargetsWithin (Rectangle rect) static
Definition at line 354 of file MapPolygon.java.
static Target anl.verdi.area.MapPolygon.getTargetWithin (double lat, double lon) static
Definition at line 331 of file MapPolygon.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/MapPolygon.java