VERDI: anl.verdi.plot.util.LegendPanel Class Reference
anl.verdi.plot.util.LegendPanel Class Reference
Public Member Functions
LegendPanel (ColorMap map, double min, double max, String units)
Dimension getPreferredSize ()
Dimension getMinimumSize ()
void initLegend (ColorMap map, double min, double max, String units)
PaintScaleLegend getLegend ()
Static Public Member Functions
static void main (String[] args)
Protected Member Functions
void paintComponent (Graphics g)
LookupPaintScale createPaintScale (ColorMap map, double min, double max)
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 30 of file LegendPanel.java.
Constructor & Destructor Documentation
anl.verdi.plot.util.LegendPanel.LegendPanel (ColorMap map, double min, double max, String units)
Definition at line 36 of file LegendPanel.java.
References anl.verdi.plot.util.LegendPanel.initLegend().
Referenced by anl.verdi.plot.util.LegendPanel.main().
Member Function Documentation
LookupPaintScale anl.verdi.plot.util.LegendPanel.createPaintScale (ColorMap map, double min, double max) protected
Definition at line 92 of file LegendPanel.java.
References anl.verdi.plot.color.ColorMap.getColor(), and anl.verdi.plot.color.ColorMap.getIntervalType().
Referenced by anl.verdi.plot.util.LegendPanel.initLegend().
PaintScaleLegend anl.verdi.plot.util.LegendPanel.getLegend ()
Definition at line 86 of file LegendPanel.java.
Dimension anl.verdi.plot.util.LegendPanel.getMinimumSize ()
Definition at line 58 of file LegendPanel.java.
Dimension anl.verdi.plot.util.LegendPanel.getPreferredSize ()
Definition at line 54 of file LegendPanel.java.
void anl.verdi.plot.util.LegendPanel.initLegend (ColorMap map, double min, double max, String units)
Definition at line 62 of file LegendPanel.java.
References anl.verdi.plot.util.LegendPanel.createPaintScale().
Referenced by anl.verdi.plot.util.LegendPanel.LegendPanel().
static void anl.verdi.plot.util.LegendPanel.main (String[] args) static
Definition at line 124 of file LegendPanel.java.
References anl.verdi.plot.util.LegendPanel.LegendPanel().
void anl.verdi.plot.util.LegendPanel.paintComponent (Graphics g) protected
Definition at line 43 of file LegendPanel.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/util/LegendPanel.java