VERDI: anl.verdi.gui.RowHeaderModel Class Reference
anl.verdi.gui.RowHeaderModel Class Reference
Classes
class RowItem
Public Member Functions
RowHeaderModel (java.util.List< String > labels)
int getSize ()
void addItem (String label)
Object getElementAt (int index)
void removeItems (Set toRemove)
Detailed Description
Version
$Revision$ $Date$
Author
Nick Collier
Definition at line 19 of file RowHeaderModel.java.
Constructor & Destructor Documentation
anl.verdi.gui.RowHeaderModel.RowHeaderModel (java.util.List< String > labels)
Definition at line 27 of file RowHeaderModel.java.
Member Function Documentation
void anl.verdi.gui.RowHeaderModel.addItem (String label)
Definition at line 46 of file RowHeaderModel.java.
Object anl.verdi.gui.RowHeaderModel.getElementAt (int index)
Definition at line 53 of file RowHeaderModel.java.
Referenced by anl.verdi.gui.RowHeader.deleteNamedRows(), anl.verdi.gui.RowHeader.getLabel(), anl.verdi.gui.RowHeader.getRowLabels(), anl.verdi.gui.RowHeader.setHeaderColor(), and anl.verdi.gui.RowHeader.unstitch().
int anl.verdi.gui.RowHeaderModel.getSize ()
Definition at line 34 of file RowHeaderModel.java.
Referenced by anl.verdi.gui.RowHeader.deleteNamedRows(), and anl.verdi.gui.RowHeader.setHeaderColor().
void anl.verdi.gui.RowHeaderModel.removeItems (Set toRemove)
Definition at line 57 of file RowHeaderModel.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/gui/RowHeaderModel.java