VERDI: anl.verdi.loaders.ExtendSyntheticTimeAxis Class Reference
anl.verdi.loaders.ExtendSyntheticTimeAxis Class Reference
Public Member Functions
ExtendSyntheticTimeAxis (CoordinateAxis axis)
GregorianCalendar getDate (int timestep)
int getTimeStep (Date date)
int getTimeStep (GregorianCalendar date)
AxisType getAxisType ()
String getDescription ()
String getName ()
Range getRange ()
Unit getUnits ()
Object getValue (int index)
boolean isCompatible (ExtendCoordAxis axis)
Static Public Attributes
static final int TIME_STEP_NOT_FOUND = -1
Detailed Description
Definition at line 21 of file ExtendSyntheticTimeAxis.java.
Constructor & Destructor Documentation
anl.verdi.loaders.ExtendSyntheticTimeAxis.ExtendSyntheticTimeAxis (CoordinateAxis axis)
Definition at line 32 of file ExtendSyntheticTimeAxis.java.
References anl.verdi.data.AxisType.TIME.
Member Function Documentation
AxisType anl.verdi.loaders.ExtendSyntheticTimeAxis.getAxisType ()
Gets the type of this axis.
Returns
the type of this axis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 122 of file ExtendSyntheticTimeAxis.java.
GregorianCalendar anl.verdi.loaders.ExtendSyntheticTimeAxis.getDate (int timestep)
Returns the Date for the specified timestep. If the we are unable to parse the time step axis sufficient to create a date then this returns null.
Parameters
timestep the time step we want the date for.
Returns
the Date for the specified timestep, or null if there is no time axis, or null if unable to parse the time axis units.
Implements anl.verdi.data.ExtendTimeCoordAxis.
Definition at line 68 of file ExtendSyntheticTimeAxis.java.
References anl.verdi.loaders.ExtendNetCdfCoordAxis.getValue().
Referenced by anl.verdi.loaders.ExtendSyntheticTimeAxis.getTimeStep().
String anl.verdi.loaders.ExtendSyntheticTimeAxis.getDescription ()
Gets the description of this CoordAxis.
Returns
the description of this CoordAxis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 131 of file ExtendSyntheticTimeAxis.java.
String anl.verdi.loaders.ExtendSyntheticTimeAxis.getName ()
Gets the name of this CoordAxis.
Returns
the name of this CoordAxis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 140 of file ExtendSyntheticTimeAxis.java.
Range anl.verdi.loaders.ExtendSyntheticTimeAxis.getRange ()
Gets the range of this axis.
Returns
the range of this axis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 149 of file ExtendSyntheticTimeAxis.java.
int anl.verdi.loaders.ExtendSyntheticTimeAxis.getTimeStep (Date date)
Gets the timestep that corresponds to the specified date. If no such timestep is found then return TIME_STEP_NOT_FOUND.
Parameters
date the date whose time step we want
Returns
the timestep that corresponds to the specified date. If no such timestep is found then return TIME_STEP_NOT_FOUND.
Implements anl.verdi.data.ExtendTimeCoordAxis.
Definition at line 84 of file ExtendSyntheticTimeAxis.java.
References anl.verdi.loaders.ExtendSyntheticTimeAxis.getDate(), anl.verdi.data.Range.getOrigin(), and anl.verdi.loaders.ExtendSyntheticTimeAxis.TIME_STEP_NOT_FOUND.
int anl.verdi.loaders.ExtendSyntheticTimeAxis.getTimeStep (GregorianCalendar date)
Gets the timestep that corresponds to the specified GregorianCalendar (date). If no such timestep is found then return TIME_STEP_NOT_FOUND.
Parameters
GregorianCalendar date the date whose time step we want
Returns
the timestep that corresponds to the specified date. If no such timestep is found then return TIME_STEP_NOT_FOUND.
Implements anl.verdi.data.ExtendTimeCoordAxis.
Definition at line 105 of file ExtendSyntheticTimeAxis.java.
References anl.verdi.loaders.ExtendSyntheticTimeAxis.getDate(), anl.verdi.data.Range.getOrigin(), and anl.verdi.loaders.ExtendSyntheticTimeAxis.TIME_STEP_NOT_FOUND.
Unit anl.verdi.loaders.ExtendSyntheticTimeAxis.getUnits ()
Gets the unit of measurement for this coordinate axis.
Returns
the unit of measurement for this coordinate axis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 158 of file ExtendSyntheticTimeAxis.java.
Object anl.verdi.loaders.ExtendSyntheticTimeAxis.getValue (int index)
Gets the value at the specified index.
Parameters
index the index
Returns
the value at the specified index.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 169 of file ExtendSyntheticTimeAxis.java.
boolean anl.verdi.loaders.ExtendSyntheticTimeAxis.isCompatible (ExtendCoordAxis axis)
Gets whether or not the this axis is compatible with the specified axis. Two axes are compatible if they can be used together in the same formula.
Parameters
axis the axis to check for compatibility
Returns
true if this axis is compatibilty with the other axis, otherise false.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 182 of file ExtendSyntheticTimeAxis.java.
Member Data Documentation
final int anl.verdi.loaders.ExtendSyntheticTimeAxis.TIME_STEP_NOT_FOUND = -1 static
Definition at line 25 of file ExtendSyntheticTimeAxis.java.
Referenced by anl.verdi.loaders.ExtendSyntheticTimeAxis.getTimeStep().
The documentation for this class was generated from the following file:
verdi_data_loaders/src/anl/verdi/loaders/ExtendSyntheticTimeAxis.java