VERDI: anl.verdi.area.target.ExportWindow Class Reference
anl.verdi.area.target.ExportWindow Class Reference
Public Member Functions
String getFilterDescription ()
void approveSelection ()
void cancelSelection ()
void closeWindow ()
Static Public Member Functions
static boolean exportFile (Frame frame, String title, String extension)
Static Protected Attributes
static String defaultPath = FilePanel.currentPath
Detailed Description
File Name:ExportWindow.java Description: This file is used to pick a file for exporting results.
Version
June 8, 2004
Author
Mary Ann Bitz
Argonne National Lab
Definition at line 24 of file ExportWindow.java.
Member Function Documentation
void anl.verdi.area.target.ExportWindow.approveSelection ()
Definition at line 81 of file ExportWindow.java.
References anl.verdi.area.target.ExportWindow.closeWindow(), and anl.verdi.area.target.ExportWindow.defaultPath.
void anl.verdi.area.target.ExportWindow.cancelSelection ()
Called when the user cancels a selection.
Definition at line 96 of file ExportWindow.java.
References anl.verdi.area.target.ExportWindow.closeWindow().
void anl.verdi.area.target.ExportWindow.closeWindow ()
Called when the user wants to close the window.
Definition at line 104 of file ExportWindow.java.
Referenced by anl.verdi.area.target.ExportWindow.approveSelection(), and anl.verdi.area.target.ExportWindow.cancelSelection().
static boolean anl.verdi.area.target.ExportWindow.exportFile (Frame frame, String title, String extension) static
Gets the name of the export file selected by the user.
Parameters
frame parent window
name title to show in the file window
Returns
the name of the file selected
Definition at line 115 of file ExportWindow.java.
References anl.verdi.area.target.ExportWindow.defaultPath.
String anl.verdi.area.target.ExportWindow.getFilterDescription ()
Definition at line 77 of file ExportWindow.java.
Member Data Documentation
String anl.verdi.area.target.ExportWindow.defaultPath = FilePanel.currentPath static protected
the default path to the options file
Definition at line 30 of file ExportWindow.java.
Referenced by anl.verdi.area.target.ExportWindow.approveSelection(), and anl.verdi.area.target.ExportWindow.exportFile().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/target/ExportWindow.java