VERDI: saf.core.ui.actions.ExitAction Class Reference
saf.core.ui.actions.ExitAction Class Reference
Public Member Functions
ExitAction (IAppConfigurator configurator, JFrame frame, AppPreferences prefs)
void actionPerformed (ActionEvent e)
Detailed Description
Author
Nick Collier
Definition at line 13 of file ExitAction.java.
Constructor & Destructor Documentation
saf.core.ui.actions.ExitAction.ExitAction (IAppConfigurator configurator, JFrame frame, AppPreferences prefs)
Definition at line 22 of file ExitAction.java.
Member Function Documentation
void saf.core.ui.actions.ExitAction.actionPerformed (ActionEvent e)
Definition at line 27 of file ExitAction.java.
References saf.core.ui.IAppConfigurator.preWindowClose(), saf.core.ui.AppPreferences.saveViewLayout(), and saf.core.ui.AppPreferences.usingSavedViewLayout().
The documentation for this class was generated from the following file:
verdi_saf_ui/src/saf/core/ui/actions/ExitAction.java