VERDI: anl.verdi.area.Units Class Reference
anl.verdi.area.Units Class Reference
Static Public Member Functions
static double convertLength (String inUnit, double val)
static String getAreaFromLength (String length)
static String getMassFromMassAreaString (String inUnit)
static int getMassFromMassArea (String inUnit)
static String getAreaFromMassAreaString (String inUnit)
static int getAreaFromMassArea (String inUnit)
static double conversionMass (String inUnit)
static double conversionMass (int inIndex)
static double convertMass (String inUnit, String outUnit, double val)
static double convertArea (String inUnit, String outUnit, double val)
static double convertMass (String inUnit, double val)
static double convertMass (int inIndex, double val)
static double convertMass (int inIndex, int outIndex, double val)
static double convertArea (int inIndex, int outIndex, double val)
static double convertArea (String inUnit, double val)
static double convertArea (int inIndex, double val)
static double conversionArea (String inUnit)
static double conversionArea (int inIndex)
static double conversionMassArea (String inUnit)
static double convertMassArea (String inUnit, double val)
static int getMassIndex (String unit)
static int getAreaIndex (String unit)
static void setCurrentMass (String val)
static void setCurrentMass (int val)
static void setCurrentArea (String val)
static void setCurrentArea (int val)
static String getCurrentAreaString ()
static String getCurrentMassString ()
static String getCurrentMassAreaString ()
static String getCurrentTypeString ()
static String getCurrentTypeString (int type)
static double getConversion (String unitString)
static int getCurrentArea ()
static int getCurrentMass ()
static int getCurrentType ()
static void setCurrentType (int i)
static Number prettyNum (float num)
static void save (Vector data)
static void export (String fileName)
static boolean isUnitPerArea (String gridUnit)
static boolean isConcentration (String gridUnit)
static String getTotalVariable (String gridUnit)
static boolean isLength (String gridUnit)
static Unit getTopUnit (String gridUnit)
static Unit getAreaUnit (String gridUnit)
Static Public Attributes
static final int MASS_AREA = 0
static final int MASS = 1
static final int PERCENT = 2
Detailed Description
File Name:Units.java Description: Converts between units.
Version
April 2004
Author
Mary Ann Bitz
Argonne National Lab
Definition at line 31 of file Units.java.
Member Function Documentation
static double anl.verdi.area.Units.conversionArea (String inUnit) static
Definition at line 128 of file Units.java.
References anl.verdi.area.Units.getAreaIndex().
Referenced by anl.verdi.area.Units.conversionMassArea().
static double anl.verdi.area.Units.conversionArea (int inIndex) static
Definition at line 132 of file Units.java.
static double anl.verdi.area.Units.conversionMass (String inUnit) static
Definition at line 84 of file Units.java.
References anl.verdi.area.Units.getMassIndex().
Referenced by anl.verdi.area.Units.conversionMassArea(), and anl.verdi.area.Units.getConversion().
static double anl.verdi.area.Units.conversionMass (int inIndex) static
Definition at line 88 of file Units.java.
static double anl.verdi.area.Units.conversionMassArea (String inUnit) static
Definition at line 135 of file Units.java.
References anl.verdi.area.Units.conversionArea(), anl.verdi.area.Units.conversionMass(), anl.verdi.area.Units.getAreaFromMassArea(), and anl.verdi.area.Units.getMassFromMassArea().
Referenced by anl.verdi.area.Units.convertMassArea(), and anl.verdi.area.Units.getConversion().
static double anl.verdi.area.Units.convertArea (String inUnit, String outUnit, double val) static
Definition at line 96 of file Units.java.
References anl.verdi.area.Units.getAreaIndex().
Referenced by anl.verdi.area.Units.convertArea().
static double anl.verdi.area.Units.convertArea (int inIndex, int outIndex, double val) static
Definition at line 115 of file Units.java.
static double anl.verdi.area.Units.convertArea (String inUnit, double val) static
Definition at line 121 of file Units.java.
References anl.verdi.area.Units.convertArea(), and anl.verdi.area.Units.getAreaIndex().
static double anl.verdi.area.Units.convertArea (int inIndex, double val) static
Definition at line 125 of file Units.java.
References anl.verdi.area.Units.convertArea().
static double anl.verdi.area.Units.convertLength (String inUnit, double val) static
convert a length to km
Definition at line 59 of file Units.java.
static double anl.verdi.area.Units.convertMass (String inUnit, String outUnit, double val) static
Definition at line 91 of file Units.java.
References anl.verdi.area.Units.getMassIndex().
Referenced by anl.verdi.area.Units.convertMass().
static double anl.verdi.area.Units.convertMass (String inUnit, double val) static
Definition at line 101 of file Units.java.
References anl.verdi.area.Units.convertMass(), and anl.verdi.area.Units.getMassIndex().
static double anl.verdi.area.Units.convertMass (int inIndex, double val) static
Definition at line 105 of file Units.java.
References anl.verdi.area.Units.convertMass().
static double anl.verdi.area.Units.convertMass (int inIndex, int outIndex, double val) static
Definition at line 108 of file Units.java.
static double anl.verdi.area.Units.convertMassArea (String inUnit, double val) static
Definition at line 140 of file Units.java.
References anl.verdi.area.Units.conversionMassArea().
static void anl.verdi.area.Units.export (String fileName) static
Definition at line 349 of file Units.java.
References anl.verdi.area.Units.getCurrentAreaString(), and anl.verdi.area.Units.getCurrentMassString().
static String anl.verdi.area.Units.getAreaFromLength (String length) static
Definition at line 64 of file Units.java.
static int anl.verdi.area.Units.getAreaFromMassArea (String inUnit) static
Definition at line 81 of file Units.java.
References anl.verdi.area.Units.getAreaFromMassAreaString(), and anl.verdi.area.Units.getAreaIndex().
Referenced by anl.verdi.area.Units.conversionMassArea().
static String anl.verdi.area.Units.getAreaFromMassAreaString (String inUnit) static
Definition at line 77 of file Units.java.
Referenced by anl.verdi.area.Units.getAreaFromMassArea().
static int anl.verdi.area.Units.getAreaIndex (String unit) static
Get the index of the area
Parameters
unit input value
Returns
Definition at line 161 of file Units.java.
Referenced by anl.verdi.area.Units.conversionArea(), anl.verdi.area.Units.convertArea(), anl.verdi.area.Units.getAreaFromMassArea(), and anl.verdi.area.Units.setCurrentArea().
static Unit anl.verdi.area.Units.getAreaUnit (String gridUnit) static
Definition at line 469 of file Units.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.processMouseMotionEvent(), and anl.verdi.area.target.Target.setUnitConverters().
static double anl.verdi.area.Units.getConversion (String unitString) static
Get the value to convert the current type
Parameters
unitString the input type
Returns
Definition at line 260 of file Units.java.
References anl.verdi.area.Units.conversionMass(), and anl.verdi.area.Units.conversionMassArea().
static int anl.verdi.area.Units.getCurrentArea () static
Get the current area index
Returns
the index
Definition at line 272 of file Units.java.
static String anl.verdi.area.Units.getCurrentAreaString () static
Get the currently used area as a string
Returns
the value
Definition at line 207 of file Units.java.
Referenced by anl.verdi.area.Units.export(), anl.verdi.area.Units.getCurrentMassAreaString(), and anl.verdi.area.Units.save().
static int anl.verdi.area.Units.getCurrentMass () static
Get the current mass index
Returns
the index
Definition at line 280 of file Units.java.
static String anl.verdi.area.Units.getCurrentMassAreaString () static
Get the current used values for mass/area as a string
Returns
the value
Definition at line 222 of file Units.java.
References anl.verdi.area.Units.getCurrentAreaString(), and anl.verdi.area.Units.getCurrentMassString().
Referenced by anl.verdi.area.Units.getCurrentTypeString().
static String anl.verdi.area.Units.getCurrentMassString () static
Get the currently used mass as a string
Returns
the value
Definition at line 215 of file Units.java.
Referenced by anl.verdi.area.Units.export(), anl.verdi.area.Units.getCurrentMassAreaString(), anl.verdi.area.Units.getCurrentTypeString(), and anl.verdi.area.Units.save().
static int anl.verdi.area.Units.getCurrentType () static
Get the current type being displayed
Returns
the type index
Definition at line 288 of file Units.java.
static String anl.verdi.area.Units.getCurrentTypeString () static
Get the current type of unit being shown in the range
Returns
Definition at line 229 of file Units.java.
References anl.verdi.area.Units.getCurrentMassAreaString(), anl.verdi.area.Units.getCurrentMassString(), anl.verdi.area.Units.MASS, anl.verdi.area.Units.MASS_AREA, and anl.verdi.area.Units.PERCENT.
static String anl.verdi.area.Units.getCurrentTypeString (int type) static
Get the current type of unit being shown in the range
Returns
Definition at line 244 of file Units.java.
References anl.verdi.area.Units.getCurrentMassAreaString(), anl.verdi.area.Units.getCurrentMassString(), anl.verdi.area.Units.MASS, anl.verdi.area.Units.MASS_AREA, and anl.verdi.area.Units.PERCENT.
static int anl.verdi.area.Units.getMassFromMassArea (String inUnit) static
Definition at line 74 of file Units.java.
References anl.verdi.area.Units.getMassFromMassAreaString(), and anl.verdi.area.Units.getMassIndex().
Referenced by anl.verdi.area.Units.conversionMassArea().
static String anl.verdi.area.Units.getMassFromMassAreaString (String inUnit) static
Definition at line 69 of file Units.java.
Referenced by anl.verdi.area.Units.getMassFromMassArea(), and anl.verdi.area.Units.getTotalVariable().
static int anl.verdi.area.Units.getMassIndex (String unit) static
Get the index of the mass
Parameters
unit input value
Returns
Definition at line 149 of file Units.java.
Referenced by anl.verdi.area.Units.conversionMass(), anl.verdi.area.Units.convertMass(), anl.verdi.area.Units.getMassFromMassArea(), and anl.verdi.area.Units.setCurrentMass().
static Unit anl.verdi.area.Units.getTopUnit (String gridUnit) static
Definition at line 448 of file Units.java.
Referenced by anl.verdi.area.target.Target.setUnitConverters().
static String anl.verdi.area.Units.getTotalVariable (String gridUnit) static
Definition at line 427 of file Units.java.
References anl.verdi.area.Units.getMassFromMassAreaString(), and anl.verdi.area.Units.isLength().
static boolean anl.verdi.area.Units.isConcentration (String gridUnit) static
Definition at line 390 of file Units.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.getMenuBar(), anl.verdi.plot.gui.FastAreaTilePlot.processMouseMotionEvent(), and anl.verdi.area.target.Target.setUnitConverters().
static boolean anl.verdi.area.Units.isLength (String gridUnit) static
Definition at line 439 of file Units.java.
Referenced by anl.verdi.area.Units.getTotalVariable(), and anl.verdi.area.target.Target.setUnitConverters().
static boolean anl.verdi.area.Units.isUnitPerArea (String gridUnit) static
Definition at line 355 of file Units.java.
Referenced by anl.verdi.area.target.Target.setUnitConverters().
static Number anl.verdi.area.Units.prettyNum (float num) static
Converts the number to one of a pretty format
Parameters
num the original number
Returns
the prettied up one
Definition at line 304 of file Units.java.
static void anl.verdi.area.Units.save (Vector data) static
Load the data from the vector of options
Parameters
data the vector containing the file data
offset the current offset
Returns
if it was successful
Exceptions
IOException Save the data to the options file
Parameters
data the vector to save it to
Definition at line 342 of file Units.java.
References anl.verdi.area.Units.getCurrentAreaString(), and anl.verdi.area.Units.getCurrentMassString().
static void anl.verdi.area.Units.setCurrentArea (String val) static
Set the currently used area unit
Parameters
val the type of the unit
Definition at line 190 of file Units.java.
References anl.verdi.area.Units.getAreaIndex().
static void anl.verdi.area.Units.setCurrentArea (int val) static
Set the currently used area unit
Parameters
val the type of the unit
Definition at line 199 of file Units.java.
static void anl.verdi.area.Units.setCurrentMass (String val) static
Set the currently used mass unit
Parameters
val the type of the unit
Definition at line 174 of file Units.java.
References anl.verdi.area.Units.getMassIndex().
static void anl.verdi.area.Units.setCurrentMass (int val) static
Set the currently used mass unit
Parameters
val the type of the unit
Definition at line 183 of file Units.java.
static void anl.verdi.area.Units.setCurrentType (int i) static
Set the current type to this one
Parameters
i the new type
Definition at line 296 of file Units.java.
Member Data Documentation
final int anl.verdi.area.Units.MASS = 1 static
show units as mass
Definition at line 35 of file Units.java.
Referenced by anl.verdi.area.Units.getCurrentTypeString().
final int anl.verdi.area.Units.MASS_AREA = 0 static
show units as mass/area
Definition at line 33 of file Units.java.
Referenced by anl.verdi.area.Units.getCurrentTypeString().
final int anl.verdi.area.Units.PERCENT = 2 static
show units as percentages
Definition at line 37 of file Units.java.
Referenced by anl.verdi.area.Units.getCurrentTypeString().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/Units.java