VERDI: anl.verdi.data.ExtendAxisRange Class Reference
anl.verdi.data.ExtendAxisRange Class Reference
Public Member Functions
ExtendAxisRange (ExtendCoordAxis axis)
ExtendAxisRange (ExtendCoordAxis axis, int origin, int extent)
ExtendCoordAxis getAxis ()
Unit getUnits ()
boolean isCompatible (ExtendCoordAxis axis)
Object getValue (int index)
String getDescription ()
String getName ()
Range getRange ()
int getExtent ()
int getOrigin ()
AxisType getAxisType ()
Protected Attributes
ExtendCoordAxis axis
Range range
Detailed Description
Definition at line 9 of file ExtendAxisRange.java.
Constructor & Destructor Documentation
anl.verdi.data.ExtendAxisRange.ExtendAxisRange (ExtendCoordAxis axis)
Creates an AxisRange for the specified axis with origin and extent equal to that of the axis.
Parameters
axis the axis
Definition at line 20 of file ExtendAxisRange.java.
References anl.verdi.data.ExtendAxisRange.axis, anl.verdi.data.ExtendAxisRange.getExtent(), and anl.verdi.data.ExtendCoordAxis.getRange().
anl.verdi.data.ExtendAxisRange.ExtendAxisRange (ExtendCoordAxis axis, int origin, int extent)
Creates an AxisRange for the specified axis with the specified origin and extent.
Parameters
origin the origin of the range
extent the extent of the range
axis the axis
Definition at line 31 of file ExtendAxisRange.java.
References anl.verdi.data.ExtendAxisRange.axis.
Member Function Documentation
ExtendCoordAxis anl.verdi.data.ExtendAxisRange.getAxis ()
Gets the coordinate axis for which this is a range.
Returns
the coordinate axis for which this is a range.
Definition at line 41 of file ExtendAxisRange.java.
References anl.verdi.data.ExtendAxisRange.axis.
AxisType anl.verdi.data.ExtendAxisRange.getAxisType ()
Gets the type of this axis.
Returns
the type of this axis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 143 of file ExtendAxisRange.java.
String anl.verdi.data.ExtendAxisRange.getDescription ()
Gets the description of this CoordAxis.
Returns
the description of this CoordAxis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 98 of file ExtendAxisRange.java.
int anl.verdi.data.ExtendAxisRange.getExtent ()
Gets the extent of the range.
Returns
the extent of the range.
Definition at line 125 of file ExtendAxisRange.java.
Referenced by anl.verdi.data.ExtendDataFrameAxis.createDataFrameAxis(), anl.verdi.data.ExtendAxisRange.ExtendAxisRange(), and anl.verdi.data.ExtendDataFrameAxis.ExtendDataFrameAxis().
String anl.verdi.data.ExtendAxisRange.getName ()
Gets the name of this CoordAxis.
Returns
the name of this CoordAxis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 107 of file ExtendAxisRange.java.
int anl.verdi.data.ExtendAxisRange.getOrigin ()
Gets the origin of the range.
Returns
the origin of the range.
Definition at line 134 of file ExtendAxisRange.java.
Range anl.verdi.data.ExtendAxisRange.getRange ()
Gets the range of this axis.
Returns
the range of this axis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 116 of file ExtendAxisRange.java.
References anl.verdi.data.ExtendAxisRange.range.
Unit anl.verdi.data.ExtendAxisRange.getUnits ()
Gets the unit of measurement for this coordinate axis.
Returns
the unit of measurement for this coordinate axis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 51 of file ExtendAxisRange.java.
Object anl.verdi.data.ExtendAxisRange.getValue (int index)
Gets the value at the specified index.
Parameters
index the index
Returns
the value at the specified index.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 89 of file ExtendAxisRange.java.
boolean anl.verdi.data.ExtendAxisRange.isCompatible (ExtendCoordAxis axis)
Gets whether or not the this axis is compatible with the specified axis. Two axes are compatible if they can be used together in the same formula.
Parameters
axis the axis to check for compatibility
Returns
true if this axis is compatible with the other axis, otherwise false.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 66 of file ExtendAxisRange.java.
References anl.verdi.data.ExtendCoordAxis.isCompatible(), and anl.verdi.data.ExtendAxisRange.range.
Member Data Documentation
ExtendCoordAxis anl.verdi.data.ExtendAxisRange.axis protected
Definition at line 11 of file ExtendAxisRange.java.
Referenced by anl.verdi.data.ExtendAxisRange.ExtendAxisRange(), anl.verdi.data.ExtendDataFrameAxis.ExtendDataFrameAxis(), and anl.verdi.data.ExtendAxisRange.getAxis().
Range anl.verdi.data.ExtendAxisRange.range protected
Definition at line 12 of file ExtendAxisRange.java.
Referenced by anl.verdi.data.ExtendAxisRange.getRange(), and anl.verdi.data.ExtendAxisRange.isCompatible().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/data/ExtendAxisRange.java