VERDI: anl.verdi.plot.gui.FooterPanel Class Reference
anl.verdi.plot.gui.FooterPanel Class Reference
Public Member Functions
FooterPanel ()
void disableText ()
void init (boolean enabled, String title, Font font, Color color)
Font getSelectedFont ()
Color getSelectedColor ()
String getTextFieldContent ()
boolean useTextField ()
boolean textFieldModified ()
Detailed Description
Author
User #2
Definition at line 31 of file FooterPanel.java.
Constructor & Destructor Documentation
anl.verdi.plot.gui.FooterPanel.FooterPanel ()
Definition at line 37 of file FooterPanel.java.
Member Function Documentation
void anl.verdi.plot.gui.FooterPanel.disableText ()
Definition at line 100 of file FooterPanel.java.
Referenced by anl.verdi.plot.gui.FooterPanel.init().
Color anl.verdi.plot.gui.FooterPanel.getSelectedColor ()
Definition at line 135 of file FooterPanel.java.
Font anl.verdi.plot.gui.FooterPanel.getSelectedFont ()
Definition at line 131 of file FooterPanel.java.
String anl.verdi.plot.gui.FooterPanel.getTextFieldContent ()
Definition at line 139 of file FooterPanel.java.
void anl.verdi.plot.gui.FooterPanel.init (boolean enabled, String title, Font font, Color color)
Definition at line 105 of file FooterPanel.java.
References anl.verdi.plot.gui.FooterPanel.disableText().
boolean anl.verdi.plot.gui.FooterPanel.textFieldModified ()
Definition at line 147 of file FooterPanel.java.
boolean anl.verdi.plot.gui.FooterPanel.useTextField ()
Definition at line 143 of file FooterPanel.java.
Referenced by anl.verdi.plot.gui.FootersPanel.fillConfiguration().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/gui/FooterPanel.java