VERDI: anl.verdi.data.AxisRange Class Reference
anl.verdi.data.AxisRange Class Reference
Public Member Functions
AxisRange (CoordAxis axis)
AxisRange (CoordAxis axis, int origin, int extent)
CoordAxis getAxis ()
Unit getUnits ()
boolean isCompatible (CoordAxis axis)
double getValue (int index)
String getDescription ()
String getName ()
Range getRange ()
int getExtent ()
int getOrigin ()
AxisType getAxisType ()
Protected Attributes
CoordAxis axis
Range range
Detailed Description
Defines a range along some coordinate axis.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 13 of file AxisRange.java.
Constructor & Destructor Documentation
anl.verdi.data.AxisRange.AxisRange (CoordAxis axis)
Creates an AxisRange for the specified axis with origin and extent equal to that of the axis.
Parameters
axis the axis
Definition at line 24 of file AxisRange.java.
References anl.verdi.data.AxisRange.axis, anl.verdi.data.AxisRange.getExtent(), and anl.verdi.data.CoordAxis.getRange().
anl.verdi.data.AxisRange.AxisRange (CoordAxis axis, int origin, int extent)
Creates an AxisRange for the specified axis with the specified origin and extent.
Parameters
origin the origin of the range
extent the extent of the range
axis the axis
Definition at line 35 of file AxisRange.java.
References anl.verdi.data.AxisRange.axis.
Member Function Documentation
CoordAxis anl.verdi.data.AxisRange.getAxis ()
Gets the coordinate axis for which this is a range.
Returns
the coordinate axis for which this is a range.
Definition at line 45 of file AxisRange.java.
References anl.verdi.data.AxisRange.axis.
AxisType anl.verdi.data.AxisRange.getAxisType ()
Gets the type of this axis.
Returns
the type of this axis.
Implements anl.verdi.data.CoordAxis.
Definition at line 142 of file AxisRange.java.
String anl.verdi.data.AxisRange.getDescription ()
Gets the description of this CoordAxis.
Returns
the description of this CoordAxis.
Implements anl.verdi.data.CoordAxis.
Definition at line 97 of file AxisRange.java.
int anl.verdi.data.AxisRange.getExtent ()
Gets the extent of the range.
Returns
the extent of the range.
Definition at line 124 of file AxisRange.java.
Referenced by anl.verdi.data.AxisRange.AxisRange(), anl.verdi.data.DataFrameAxis.createDataFrameAxis(), anl.verdi.data.DataFrameAxis.DataFrameAxis(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), anl.verdi.plot.types.TilePlot.getToolBar(), anl.verdi.plot.types.Contour3D.getToolBar(), anl.verdi.data.DataUtilities.minMax(), anl.verdi.data.DataUtilities.minMaxForTimeLayer(), anl.verdi.data.DataUtilities.minMaxTX(), and anl.verdi.data.DataUtilities.minMaxTY().
String anl.verdi.data.AxisRange.getName ()
Gets the name of this CoordAxis.
Returns
the name of this CoordAxis.
Implements anl.verdi.data.CoordAxis.
Definition at line 106 of file AxisRange.java.
int anl.verdi.data.AxisRange.getOrigin ()
Gets the origin of the range.
Returns
the origin of the range.
Definition at line 133 of file AxisRange.java.
Referenced by anl.verdi.plot.types.TilePlot.getToolBar(), anl.verdi.plot.types.VerticalCrossSectionPlot.getToolBar(), and anl.verdi.plot.types.Contour3D.getToolBar().
Range anl.verdi.data.AxisRange.getRange ()
Gets the range of this axis.
Returns
the range of this axis.
Implements anl.verdi.data.CoordAxis.
Definition at line 115 of file AxisRange.java.
References anl.verdi.data.AxisRange.range.
Referenced by anl.verdi.plot.gui.VerticalCrossDialog.init(), anl.verdi.plot.gui.TimeConstantAxisPanel.init(), anl.verdi.plot.anim.AnimationPanel.init(), and anl.verdi.plot.anim.AnimationPanelContour3D.init().
Unit anl.verdi.data.AxisRange.getUnits ()
Gets the unit of measurement for this coordinate axis.
Returns
the unit of measurement for this coordinate axis.
Implements anl.verdi.data.CoordAxis.
Definition at line 55 of file AxisRange.java.
double anl.verdi.data.AxisRange.getValue (int index)
Gets the value at the specified index.
Parameters
index the index
Returns
the value at the specified index.
Implements anl.verdi.data.CoordAxis.
Definition at line 88 of file AxisRange.java.
boolean anl.verdi.data.AxisRange.isCompatible (CoordAxis axis)
Gets whether or not the this axis is compatible with the specified axis. Two axes are compatible if they can be used together in the same formula.
Parameters
axis the axis to check for compatibility
Returns
true if this axis is compatible with the other axis, otherwise false.
Implements anl.verdi.data.CoordAxis.
Definition at line 69 of file AxisRange.java.
References anl.verdi.data.CoordAxis.isCompatible().
Member Data Documentation
CoordAxis anl.verdi.data.AxisRange.axis protected
Definition at line 15 of file AxisRange.java.
Referenced by anl.verdi.data.AxisRange.AxisRange(), anl.verdi.data.DataFrameAxis.DataFrameAxis(), and anl.verdi.data.AxisRange.getAxis().
Range anl.verdi.data.AxisRange.range protected
Definition at line 16 of file AxisRange.java.
Referenced by anl.verdi.data.AxisRange.getRange().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/data/AxisRange.java