VERDI: anl.verdi.plot.probe.TileProbeCreator Class Reference
anl.verdi.plot.probe.TileProbeCreator Class Reference
Public Member Functions
TileProbeCreator (DataFrame frame, Slice slice)
TableModel createTableModel ()
String getName ()
String getRangeAxisName ()
void setLog (boolean isLog)
boolean isLog ()
void setLogBase (double logBase)
double getLogBase ()
Detailed Description
A probe creator for Tile probing Tile plots.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 17 of file TileProbeCreator.java.
Constructor & Destructor Documentation
anl.verdi.plot.probe.TileProbeCreator.TileProbeCreator (DataFrame frame, Slice slice)
Definition at line 25 of file TileProbeCreator.java.
References anl.verdi.plot.probe.TileProbeCreator.getName(), anl.verdi.data.Slice.getXRange(), and anl.verdi.data.Slice.getYRange().
Member Function Documentation
TableModel anl.verdi.plot.probe.TileProbeCreator.createTableModel ()
Creates the probe.
Implements anl.verdi.plot.probe.ProbeCreator.
Definition at line 58 of file TileProbeCreator.java.
double anl.verdi.plot.probe.TileProbeCreator.getLogBase ()
Definition at line 96 of file TileProbeCreator.java.
String anl.verdi.plot.probe.TileProbeCreator.getName ()
Gets the name of the probe.
Returns
the name of the probe.
Implements anl.verdi.plot.probe.ProbeCreator.
Definition at line 71 of file TileProbeCreator.java.
Referenced by anl.verdi.plot.probe.TileProbeCreator.TileProbeCreator().
String anl.verdi.plot.probe.TileProbeCreator.getRangeAxisName ()
Gets the name of the range axis.
Returns
the name of the range axis.
Implements anl.verdi.plot.probe.ProbeCreator.
Definition at line 80 of file TileProbeCreator.java.
boolean anl.verdi.plot.probe.TileProbeCreator.isLog ()
Definition at line 88 of file TileProbeCreator.java.
Referenced by anl.verdi.plot.probe.TileProbeCreator.setLog().
void anl.verdi.plot.probe.TileProbeCreator.setLog (boolean isLog)
Definition at line 84 of file TileProbeCreator.java.
References anl.verdi.plot.probe.TileProbeCreator.isLog().
void anl.verdi.plot.probe.TileProbeCreator.setLogBase (double logBase)
Definition at line 92 of file TileProbeCreator.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/probe/TileProbeCreator.java