VERDI: saf.core.ui.actions.WindowMenuAction Class Reference
saf.core.ui.actions.WindowMenuAction Class Reference
Public Member Functions
WindowMenuAction (DockableFrame dockable)
void actionPerformed (ActionEvent e)
Detailed Description
Action that is triggered when selecting a frame from the "window" menu. If the dockable is minimized it will be restored and selected. If the dockable is hidden it will be restored and selected. Otherwise, the dockable will just be selected.
Author
Nick Collier
Definition at line 21 of file WindowMenuAction.java.
Constructor & Destructor Documentation
saf.core.ui.actions.WindowMenuAction.WindowMenuAction (DockableFrame dockable)
Creates a WindowMenuAction that will work on the the specified dockable.
Parameters
dockable the dockable that is the subject of this action
Definition at line 31 of file WindowMenuAction.java.
References saf.core.ui.dock.DockableFrame.getTitle().
Member Function Documentation
void saf.core.ui.actions.WindowMenuAction.actionPerformed (ActionEvent e)
Definition at line 36 of file WindowMenuAction.java.
References saf.core.ui.dock.DockableFrame.isMinimized(), and saf.core.ui.dock.DockableFrame.restore().
The documentation for this class was generated from the following file:
verdi_saf_ui/src/saf/core/ui/actions/WindowMenuAction.java