VERDI: org.libtiff.jai.codec.XTIFFDirectory Class Reference
org.libtiff.jai.codec.XTIFFDirectory Class Reference
Public Member Functions
XTIFFDirectory ()
boolean isTiled ()
int sizeOfType (int type) throws ArrayIndexOutOfBoundsException
void addField (int tag, int type, int count, Object obj)
void addField (XTIFFField field)
int getNumEntries ()
XTIFFField getField (int tag)
boolean isTagPresent (int tag)
int[] getTags ()
XTIFFField[] getFields ()
byte getFieldAsByte (int tag, int index)
byte getFieldAsByte (int tag)
long getFieldAsLong (int tag, int index)
long getFieldAsLong (int tag)
float getFieldAsFloat (int tag, int index)
float getFieldAsFloat (int tag)
double getFieldAsDouble (int tag, int index)
double getFieldAsDouble (int tag)
Object readFieldValue (int tag, int type, int count) throws IOException, ArrayIndexOutOfBoundsException
boolean isBigEndian ()
void setCompression (int compression)
int getCompression ()
void setIsTiled (boolean isTiled)
XTIFFTileCodec createTileCodec (XTIFFDecodeParam param) throws IOException
XTIFFTileCodec createTileCodec (XTIFFEncodeParam param) throws IOException
int getImageType ()
void setImageType (int image_type)
Static Public Member Functions
static XTIFFField createField (int tag, int type, int count, Object obj)
static int getNumDirectories (SeekableStream stream) throws IOException
static void setFactory (XTIFFFactory fact)
static XTIFFDirectory create (SeekableStream stream, int directory) throws IOException
static XTIFFDirectory create (SeekableStream stream, long ifd_offset) throws IOException
static XTIFFDirectory create ()
static XTIFFTileCodec getTileCodec (int comp)
static void unRegisterTileCodec (int comp)
static void registerTileCodec (int comp, XTIFFTileCodec codec)
Protected Member Functions
void readHeader () throws IOException
XTIFFDirectory (SeekableStream stream, int directory) throws IOException
XTIFFDirectory (SeekableStream stream, long ifd_offset) throws IOException
void initialize () throws IOException
short readShort (SeekableStream stream) throws IOException
int readUnsignedShort (SeekableStream stream) throws IOException
int readInt (SeekableStream stream) throws IOException
long readUnsignedInt (SeekableStream stream) throws IOException
long readLong (SeekableStream stream) throws IOException
float readFloat (SeekableStream stream) throws IOException
double readDouble (SeekableStream stream) throws IOException
Protected Attributes
transient SeekableStream stream
Static Protected Attributes
static XTIFFFactory factory = new XTIFFFactory()
static Hashtable tileCodecs = new Hashtable()
Detailed Description
XTIFFDirectory is an extensible TIFF directory object. This class may be extended without changing the XTIFF codec by overriding the XTIFFFactory instance registered in this class. In addition, this class is the repository of all XTIFFTileCodec's which may be augmented with new codecs, again without overriding the ImageCodec. If the jai "tiff" codec has been overridden through the XTIFFDescriptor.register() method, each XTIFF image will possess a property called "tiff.directory" which will be an object of the type created by the factory. The class is declared as serializable to permit its transmission to remote images as a set of parameters to the codec, and to be able to survive as an instantiated property of the RenderedImage.
Author
Niles Ritter
See Also
XTIFFDescriptor
XTIFFField
XTIFFTileCodec
XTIFFFactory
Definition at line 58 of file XTIFFDirectory.java.
Constructor & Destructor Documentation
org.libtiff.jai.codec.XTIFFDirectory.XTIFFDirectory ()
The default constructor. Publicized for Serializability
Definition at line 79 of file XTIFFDirectory.java.
org.libtiff.jai.codec.XTIFFDirectory.XTIFFDirectory (SeekableStream stream, int directory) throws IOException protected
Constructs a XTIFFDirectory from a SeekableStream. The directory parameter specifies which directory to read from the linked list present in the stream; directory 0 is normally read but it is possible to store multiple images in a single TIFF file by maintaing multiple directories.
Parameters
stream a SeekableStream to read from.
directory the index of the directory to read.
Definition at line 122 of file XTIFFDirectory.java.
References org.libtiff.jai.util.JaiI18N.getString(), org.libtiff.jai.codec.XTIFFDirectory.initialize(), org.libtiff.jai.codec.XTIFFDirectory.readHeader(), org.libtiff.jai.codec.XTIFFDirectory.readUnsignedInt(), org.libtiff.jai.codec.XTIFFDirectory.readUnsignedShort(), and org.libtiff.jai.codec.XTIFFDirectory.stream.
org.libtiff.jai.codec.XTIFFDirectory.XTIFFDirectory (SeekableStream stream, long ifd_offset) throws IOException protected
Constructs a XTIFFDirectory by reading a SeekableStream. The ifd_offset parameter specifies the stream offset from which to begin reading; this mechanism is sometimes used to store private IFDs within a TIFF file that are not part of the normal sequence of IFDs.
Parameters
stream a SeekableStream to read from.
ifd_offset the long byte offset of the directory.
Definition at line 160 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.initialize(), org.libtiff.jai.codec.XTIFFDirectory.readHeader(), and org.libtiff.jai.codec.XTIFFDirectory.stream.
Member Function Documentation
void org.libtiff.jai.codec.XTIFFDirectory.addField (int tag, int type, int count, Object obj)
Create and add a TIFF field to this directory.
Parameters
tag the TIFF tag listed in XTIFF
type the TIFF field type listed in XTIFFField
count the number of values in array obj
obj the array of values
See Also
XTIFFField
XTIFF
Definition at line 210 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFFactory.createField(), and org.libtiff.jai.codec.XTIFFDirectory.factory.
Referenced by org.libtiff.jai.codec.XTIFFDirectory.initialize(), and org.libtiff.jai.codec.XTIFFDirectory.setCompression().
void org.libtiff.jai.codec.XTIFFDirectory.addField (XTIFFField field)
Add an existing TIFF field to this directory.
Parameters
type the XTIFFField type code
See Also
XTIFFField
Definition at line 235 of file XTIFFDirectory.java.
static XTIFFDirectory org.libtiff.jai.codec.XTIFFDirectory.create (SeekableStream stream, int directory) throws IOException static
Constructs a XTIFFDirectory from a SeekableStream. The directory parameter specifies which directory to read from the linked list present in the stream; directory 0 is normally read but it is possible to store multiple images in a single TIFF file by maintaing multiple directories.
Parameters
stream a SeekableStream to read from.
directory the index of the directory to read.
See Also
XTIFFFactory
Definition at line 765 of file XTIFFDirectory.java.
static XTIFFDirectory org.libtiff.jai.codec.XTIFFDirectory.create (SeekableStream stream, long ifd_offset) throws IOException static
Constructs a TIFFDirectory by reading a SeekableStream. The ifd_offset parameter specifies the stream offset from which to begin reading; this mechanism is sometimes used to store private IFDs within a TIFF file that are not part of the normal sequence of IFDs. Uses the XTIFFFactory to do this, so to extend the directory class, the factory method should be extended and registered instead of this one.
Parameters
stream a SeekableStream to read from.
ifd_offset the long byte offset of the directory.
See Also
XTIFFFactory
Definition at line 782 of file XTIFFDirectory.java.
static XTIFFDirectory org.libtiff.jai.codec.XTIFFDirectory.create () static
Constructs an XTIFFDirectory from the currently. registered XTIFFDirectory factory.
See Also
XTIFFFactory
Definition at line 793 of file XTIFFDirectory.java.
static XTIFFField org.libtiff.jai.codec.XTIFFDirectory.createField (int tag, int type, int count, Object obj) static
Create a TIFF field
Parameters
tag the TIFF tag listed in XTIFF
type the TIFF field type listed in XTIFFField
count the number of values in array obj
obj the array of values
See Also
XTIFFField
XTIFF
Definition at line 224 of file XTIFFDirectory.java.
Referenced by org.geotiff.image.jai.GeoTIFFDirectory.addGeoKey().
XTIFFTileCodec org.libtiff.jai.codec.XTIFFDirectory.createTileCodec (XTIFFDecodeParam param) throws IOException
Constructs a tile codec for decoding data, using the compression defined in the current directory.
Parameters
param the encoding param
See Also
XTIFFTileCodec
Definition at line 711 of file XTIFFDirectory.java.
XTIFFTileCodec org.libtiff.jai.codec.XTIFFDirectory.createTileCodec (XTIFFEncodeParam param) throws IOException
Constructs a tile codec for encoding data, using the compression defined in the current directory.
Parameters
param the encoding param
See Also
XTIFFTileCodec
Definition at line 728 of file XTIFFDirectory.java.
int org.libtiff.jai.codec.XTIFFDirectory.getCompression ()
Return the type of compression indicated in the TIFF fields, or XTIFF.COMPRESSION_NON if not specified.
Definition at line 687 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFF.COMPRESSION_NONE, and org.libtiff.jai.codec.XTIFF.TIFFTAG_COMPRESSION.
XTIFFField org.libtiff.jai.codec.XTIFFDirectory.getField (int tag)
Returns the value of a given tag as a XTIFFField, or null if the tag is not present.
Definition at line 269 of file XTIFFDirectory.java.
Referenced by org.libtiff.jai.codec.XTIFFDirectory.getFieldAsByte(), org.libtiff.jai.codec.XTIFFDirectory.getFieldAsDouble(), org.libtiff.jai.codec.XTIFFDirectory.getFieldAsFloat(), org.libtiff.jai.codec.XTIFFDirectory.getFieldAsLong(), and org.libtiff.jai.codecimpl.XTIFFImage.setupImageParameters().
byte org.libtiff.jai.codec.XTIFFDirectory.getFieldAsByte (int tag, int index)
Returns the value of a particular index of a given tag as a byte. The caller is responsible for ensuring that the tag is present and has type XTIFFField.TIFF_SBYTE, TIFF_BYTE, or TIFF_UNDEFINED.
Definition at line 312 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.getField().
Referenced by org.libtiff.jai.codec.XTIFFDirectory.getFieldAsByte().
byte org.libtiff.jai.codec.XTIFFDirectory.getFieldAsByte (int tag)
Returns the value of index 0 of a given tag as a byte. The caller is responsible for ensuring that the tag is present and has type XTIFFField.TIFF_SBYTE, TIFF_BYTE, or TIFF_UNDEFINED.
Definition at line 321 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.getFieldAsByte().
double org.libtiff.jai.codec.XTIFFDirectory.getFieldAsDouble (int tag, int index)
Returns the value of a particular index of a given tag as a double. The caller is responsible for ensuring that the tag is present and has numeric type (all but TIFF_UNDEFINED and TIFF_ASCII).
Definition at line 368 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.getField().
Referenced by org.libtiff.jai.codec.XTIFFDirectory.getFieldAsDouble().
double org.libtiff.jai.codec.XTIFFDirectory.getFieldAsDouble (int tag)
Returns the value of index 0 of a given tag as a double. The caller is responsible for ensuring that the tag is present and has numeric type (all but TIFF_UNDEFINED and TIFF_ASCII).
Definition at line 377 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.getFieldAsDouble().
float org.libtiff.jai.codec.XTIFFDirectory.getFieldAsFloat (int tag, int index)
Returns the value of a particular index of a given tag as a float. The caller is responsible for ensuring that the tag is present and has numeric type (all but TIFF_UNDEFINED and TIFF_ASCII).
Definition at line 350 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.getField().
Referenced by org.libtiff.jai.codec.XTIFFDirectory.getFieldAsFloat().
float org.libtiff.jai.codec.XTIFFDirectory.getFieldAsFloat (int tag)
Returns the value of index 0 of a given tag as a float. The caller is responsible for ensuring that the tag is present and has numeric type (all but TIFF_UNDEFINED and TIFF_ASCII).
Definition at line 359 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.getFieldAsFloat().
long org.libtiff.jai.codec.XTIFFDirectory.getFieldAsLong (int tag, int index)
Returns the value of a particular index of a given tag as a long. The caller is responsible for ensuring that the tag is present and has type TIFF_BYTE, TIFF_SBYTE, TIFF_UNDEFINED, TIFF_SHORT, TIFF_SSHORT, TIFF_SLONG or TIFF_LONG.
Definition at line 331 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.getField().
Referenced by org.libtiff.jai.codec.XTIFFDirectory.getFieldAsLong(), and org.libtiff.jai.codecimpl.XTIFFImage.setupImageParameters().
long org.libtiff.jai.codec.XTIFFDirectory.getFieldAsLong (int tag)
Returns the value of index 0 of a given tag as a long. The caller is responsible for ensuring that the tag is present and has type TIFF_BYTE, TIFF_SBYTE, TIFF_UNDEFINED, TIFF_SHORT, TIFF_SSHORT, TIFF_SLONG or TIFF_LONG.
Definition at line 341 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.getFieldAsLong().
XTIFFField [] org.libtiff.jai.codec.XTIFFDirectory.getFields ()
Returns an array of XTIFFFields containing all the fields in this directory.
Definition at line 297 of file XTIFFDirectory.java.
Referenced by org.libtiff.jai.codecimpl.XTIFFImageEncoder.encode().
int org.libtiff.jai.codec.XTIFFDirectory.getImageType ()
Get the JAI Image decoded type. This method is called by the XTIFFTileCodeImpl object during the decode() method to determine what type of colorspace and sample model to use.
Definition at line 834 of file XTIFFDirectory.java.
static int org.libtiff.jai.codec.XTIFFDirectory.getNumDirectories (SeekableStream stream) throws IOException static
Returns the number of image directories (subimages) stored in a given TIFF file, represented by a SeekableStream.
Definition at line 625 of file XTIFFDirectory.java.
References org.libtiff.jai.util.JaiI18N.getString(), org.libtiff.jai.codec.XTIFFDirectory.isBigEndian(), org.libtiff.jai.codec.XTIFFDirectory.readUnsignedInt(), org.libtiff.jai.codec.XTIFFDirectory.readUnsignedShort(), and org.libtiff.jai.codec.XTIFFDirectory.stream.
int org.libtiff.jai.codec.XTIFFDirectory.getNumEntries ()
Returns the number of directory entries.
Definition at line 261 of file XTIFFDirectory.java.
int [] org.libtiff.jai.codec.XTIFFDirectory.getTags ()
Returns an ordered array of ints indicating the tag values.
Definition at line 283 of file XTIFFDirectory.java.
static XTIFFTileCodec org.libtiff.jai.codec.XTIFFDirectory.getTileCodec (int comp) static
Return the currently registered XTIFFTileCodec for this compression type. Used by the XTIFFImage to decode the compression data.
See Also
XTIFFTileCodec
Definition at line 803 of file XTIFFDirectory.java.
void org.libtiff.jai.codec.XTIFFDirectory.initialize () throws IOException protected
Initialize the directory from a stream
Definition at line 242 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.addField(), org.libtiff.jai.codec.XTIFFDirectory.readUnsignedShort(), and org.libtiff.jai.codec.XTIFFDirectory.stream.
Referenced by org.libtiff.jai.codec.XTIFFDirectory.XTIFFDirectory().
boolean org.libtiff.jai.codec.XTIFFDirectory.isBigEndian ()
Returns a boolean indicating whether the byte order used in the the TIFF file is big-endian (i.e. whether the byte order is from the most significant to the least significant)
Definition at line 662 of file XTIFFDirectory.java.
Referenced by org.libtiff.jai.codec.XTIFFDirectory.getNumDirectories(), org.libtiff.jai.codec.XTIFFDirectory.readDouble(), org.libtiff.jai.codec.XTIFFDirectory.readFloat(), org.libtiff.jai.codec.XTIFFDirectory.readHeader(), org.libtiff.jai.codec.XTIFFDirectory.readInt(), org.libtiff.jai.codec.XTIFFDirectory.readLong(), org.libtiff.jai.codec.XTIFFDirectory.readShort(), org.libtiff.jai.codec.XTIFFDirectory.readUnsignedInt(), and org.libtiff.jai.codec.XTIFFDirectory.readUnsignedShort().
boolean org.libtiff.jai.codec.XTIFFDirectory.isTagPresent (int tag)
Returns true if a tag appears in the directory.
Definition at line 276 of file XTIFFDirectory.java.
boolean org.libtiff.jai.codec.XTIFFDirectory.isTiled ()
If true this image uses TIFF 6.0 tiling
Definition at line 88 of file XTIFFDirectory.java.
double org.libtiff.jai.codec.XTIFFDirectory.readDouble (SeekableStream stream) throws IOException protected
Definition at line 590 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.isBigEndian().
Referenced by org.libtiff.jai.codec.XTIFFDirectory.readFieldValue().
Object org.libtiff.jai.codec.XTIFFDirectory.readFieldValue (int tag, int type, int count) throws IOException, ArrayIndexOutOfBoundsException
TIFF field-value reader. Override if there are new field types. Also override sizeOfType() and, possibly the createField method of the factory, if the field needs new accessors.
Definition at line 386 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.readDouble(), org.libtiff.jai.codec.XTIFFDirectory.readFloat(), org.libtiff.jai.codec.XTIFFDirectory.readInt(), org.libtiff.jai.codec.XTIFFDirectory.readShort(), org.libtiff.jai.codec.XTIFFDirectory.readUnsignedInt(), org.libtiff.jai.codec.XTIFFDirectory.readUnsignedShort(), org.libtiff.jai.codec.XTIFFDirectory.stream, and org.libtiff.jai.codec.XTIFFField.TIFF_ASCII.
float org.libtiff.jai.codec.XTIFFDirectory.readFloat (SeekableStream stream) throws IOException protected
Definition at line 582 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.isBigEndian().
Referenced by org.libtiff.jai.codec.XTIFFDirectory.readFieldValue().
void org.libtiff.jai.codec.XTIFFDirectory.readHeader () throws IOException protected
reads the TIFF header. Not likely to be overridden.
Definition at line 95 of file XTIFFDirectory.java.
References org.libtiff.jai.util.JaiI18N.getString(), org.libtiff.jai.codec.XTIFFDirectory.isBigEndian(), org.libtiff.jai.codec.XTIFFDirectory.readUnsignedShort(), and org.libtiff.jai.codec.XTIFFDirectory.stream.
Referenced by org.libtiff.jai.codec.XTIFFDirectory.XTIFFDirectory().
int org.libtiff.jai.codec.XTIFFDirectory.readInt (SeekableStream stream) throws IOException protected
Definition at line 558 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.isBigEndian().
Referenced by org.libtiff.jai.codec.XTIFFDirectory.readFieldValue().
long org.libtiff.jai.codec.XTIFFDirectory.readLong (SeekableStream stream) throws IOException protected
Definition at line 574 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.isBigEndian().
short org.libtiff.jai.codec.XTIFFDirectory.readShort (SeekableStream stream) throws IOException protected
Definition at line 540 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.isBigEndian().
Referenced by org.libtiff.jai.codec.XTIFFDirectory.readFieldValue().
long org.libtiff.jai.codec.XTIFFDirectory.readUnsignedInt (SeekableStream stream) throws IOException protected
Definition at line 566 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.isBigEndian().
Referenced by org.libtiff.jai.codec.XTIFFDirectory.getNumDirectories(), org.libtiff.jai.codec.XTIFFDirectory.readFieldValue(), and org.libtiff.jai.codec.XTIFFDirectory.XTIFFDirectory().
int org.libtiff.jai.codec.XTIFFDirectory.readUnsignedShort (SeekableStream stream) throws IOException protected
Definition at line 548 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.isBigEndian().
Referenced by org.libtiff.jai.codec.XTIFFDirectory.getNumDirectories(), org.libtiff.jai.codec.XTIFFDirectory.initialize(), org.libtiff.jai.codec.XTIFFDirectory.readFieldValue(), org.libtiff.jai.codec.XTIFFDirectory.readHeader(), and org.libtiff.jai.codec.XTIFFDirectory.XTIFFDirectory().
static void org.libtiff.jai.codec.XTIFFDirectory.registerTileCodec (int comp, XTIFFTileCodec codec) static
Register a new XTIFFTileCodec for encoding and decoding compressed TIFF image data. This overrides any existing codec previously registered.
Parameters
comp The TIFF compression code indicated by the
codec The codec to register. XTIFF.TIFFTAG_COMPRESSION field.
See Also
XTIFFTileCodec
Definition at line 825 of file XTIFFDirectory.java.
void org.libtiff.jai.codec.XTIFFDirectory.setCompression (int compression)
Specifies the type of compression to be used. The compression type specified will be honored only if it is compatible with the image being written out.
Parameters
compression The compression type.
Definition at line 673 of file XTIFFDirectory.java.
References org.libtiff.jai.codec.XTIFFDirectory.addField(), org.libtiff.jai.codec.XTIFFField.TIFF_SHORT, and org.libtiff.jai.codec.XTIFF.TIFFTAG_COMPRESSION.
static void org.libtiff.jai.codec.XTIFFDirectory.setFactory (XTIFFFactory fact) static
Set the XTIFFFactory, which is used to construct the XTIFFDirectory object assigned as a "tiff.directory" property in the resulting jai image.
Parameters
fact the factory to register. The factory is guaranteed to always be non-null; if a null is passed in then the default XTIFFFactory is used. a null object is passed in
See Also
XTIFFFactory
Definition at line 748 of file XTIFFDirectory.java.
void org.libtiff.jai.codec.XTIFFDirectory.setImageType (int image_type)
Set the JAI Image decoded type. This method is called by the XTIFFImage constructor to indicate to the XTIFFTileCodec what type of colorspace and sample model to use. The types are enumerated in the XTIFF class.
See Also
XTIFF
XTIFFImage
XTIFFTileCodec
Definition at line 847 of file XTIFFDirectory.java.
void org.libtiff.jai.codec.XTIFFDirectory.setIsTiled (boolean isTiled)
If set, the data will be written out in tiled format, instead of in strips.
Parameters
isTiled Specifies whether the image data should be wriiten out in tiled format.
Definition at line 700 of file XTIFFDirectory.java.
int org.libtiff.jai.codec.XTIFFDirectory.sizeOfType (int type) throws ArrayIndexOutOfBoundsException
Return the size of a data type. Extend if you need to define new TIFF field types. Also override the createField() method of the XTIFFFactory, the XTIFFField class, and the readFieldValue() method here.
Parameters
type the XTIFFField type code
See Also
XTIFFField
XTIFFFactory
Definition at line 196 of file XTIFFDirectory.java.
static void org.libtiff.jai.codec.XTIFFDirectory.unRegisterTileCodec (int comp) static
UnRegister the XTIFFTileCodec corresponding to the TIFF compression type.
Parameters
comp The TIFF compression code indicated
Definition at line 812 of file XTIFFDirectory.java.
Member Data Documentation
XTIFFFactory org.libtiff.jai.codec.XTIFFDirectory.factory = new XTIFFFactory() static protected
default directory factory
Definition at line 62 of file XTIFFDirectory.java.
Referenced by org.libtiff.jai.codec.XTIFFDirectory.addField().
transient SeekableStream org.libtiff.jai.codec.XTIFFDirectory.stream protected
The stream being read. Not persisted
Definition at line 67 of file XTIFFDirectory.java.
Referenced by org.geotiff.image.jai.GeoTIFFDirectory.GeoTIFFDirectory(), org.libtiff.jai.codec.XTIFFDirectory.getNumDirectories(), org.libtiff.jai.codec.XTIFFDirectory.initialize(), org.libtiff.jai.codec.XTIFFDirectory.readFieldValue(), org.libtiff.jai.codec.XTIFFDirectory.readHeader(), and org.libtiff.jai.codec.XTIFFDirectory.XTIFFDirectory().
Hashtable org.libtiff.jai.codec.XTIFFDirectory.tileCodecs = new Hashtable() static protected
Definition at line 64 of file XTIFFDirectory.java.
The documentation for this class was generated from the following file:
verdi_core/src/org/libtiff/jai/codec/XTIFFDirectory.java