VERDI: anl.verdi.data.ExtendAbstractDataset Class Reference
anl.verdi.data.ExtendAbstractDataset Class Reference abstract
Public Member Functions
URL getURL ()
String getAlias ()
void setAlias (String alias)
List< String > getVariableNames ()
Variable getVariable (String name)
List< Variable > getVariables ()
ExtendAxes< ExtendCoordAxis > getCoordAxes ()
boolean hasTimeAxis ()
boolean hasXAxis ()
boolean hasYAxis ()
boolean hasZAxis ()
String getName ()
void close () throws IOException
boolean isObs ()
Public Member Functions inherited from anl.verdi.data.ExtendDataset
int getIndexInURL ()
DatasetMetadata getMetadata ()
int getNumDimensions ()
boolean isStandardGrid ()
Protected Member Functions
ExtendAbstractDataset (URL url)
Protected Attributes
String alias = NULL_ALIAS
URL url
Additional Inherited Members
Static Public Attributes inherited from anl.verdi.data.ExtendDataset
static final String NULL_ALIAS = "anl.verdi.data.DataSet.NULL_ALIAS"
static final int SINGLE_DATASET = -1
Detailed Description
Definition at line 8 of file ExtendAbstractDataset.java.
Constructor & Destructor Documentation
anl.verdi.data.ExtendAbstractDataset.ExtendAbstractDataset (URL url) protected
Creates an AbstractDataset.
Parameters
url the url of the dataset
Definition at line 19 of file ExtendAbstractDataset.java.
References anl.verdi.data.ExtendAbstractDataset.url.
Member Function Documentation
void anl.verdi.data.ExtendAbstractDataset.close () throws IOException
Closes this dataset. It will have to be recreated to be used again. NOTE: Empty body for this method.
Implements anl.verdi.data.ExtendDataset.
Definition at line 122 of file ExtendAbstractDataset.java.
String anl.verdi.data.ExtendAbstractDataset.getAlias ()
Gets the alias of this Dataset. If no alias has been assigned the alias will be NULL_ALIAS.
Returns
the alias of this Dataset.
Implements anl.verdi.data.ExtendDataset.
Definition at line 38 of file ExtendAbstractDataset.java.
References anl.verdi.data.ExtendAbstractDataset.alias.
ExtendAxes<ExtendCoordAxis> anl.verdi.data.ExtendAbstractDataset.getCoordAxes ()
Gets the coordinate Axes for this Dataset.
Returns
the coordinate Axes for this Dataset.
Implements anl.verdi.data.ExtendDataset.
Definition at line 74 of file ExtendAbstractDataset.java.
Referenced by anl.verdi.data.ExtendAbstractDataset.hasTimeAxis(), anl.verdi.data.ExtendAbstractDataset.hasXAxis(), anl.verdi.data.ExtendAbstractDataset.hasYAxis(), and anl.verdi.data.ExtendAbstractDataset.hasZAxis().
String anl.verdi.data.ExtendAbstractDataset.getName ()
Gets the name of this Dataset. NOTE: Always returns an empty String.
Returns
the name of this Dataset;
Implements anl.verdi.data.ExtendDataset.
Definition at line 114 of file ExtendAbstractDataset.java.
URL anl.verdi.data.ExtendAbstractDataset.getURL ()
Gets the url of this Dataset.
Returns
the url of this Dataset.
Implements anl.verdi.data.ExtendDataset.
Definition at line 28 of file ExtendAbstractDataset.java.
References anl.verdi.data.ExtendAbstractDataset.url.
Variable anl.verdi.data.ExtendAbstractDataset.getVariable (String name)
Gets the named variable. NOTE: Always returns NULL.
Parameters
name the name of the variable to get
Returns
the named variable
Implements anl.verdi.data.ExtendDataset.
Definition at line 61 of file ExtendAbstractDataset.java.
List<String> anl.verdi.data.ExtendAbstractDataset.getVariableNames ()
Gets the list of variable names in this Dataset.
Returns
the list of variable names in this Dataset.
Implements anl.verdi.data.ExtendDataset.
Definition at line 51 of file ExtendAbstractDataset.java.
List<Variable> anl.verdi.data.ExtendAbstractDataset.getVariables ()
Gets the list of variables in this Dataset.
Returns
the list of variables in this Dataset.
Implements anl.verdi.data.ExtendDataset.
Definition at line 65 of file ExtendAbstractDataset.java.
Referenced by anl.verdi.loaders.ExtendAbstractNetcdfDataset.getVariable(), and anl.verdi.loaders.ExtendAbstractNetcdfDataset.getVariableNames().
boolean anl.verdi.data.ExtendAbstractDataset.hasTimeAxis ()
Returns
true if there is a time axis, otherwise false
Implements anl.verdi.data.ExtendDataset.
Definition at line 81 of file ExtendAbstractDataset.java.
References anl.verdi.data.ExtendAbstractDataset.getCoordAxes().
boolean anl.verdi.data.ExtendAbstractDataset.hasXAxis ()
Returns
true if there is a X axis, otherwise false
Implements anl.verdi.data.ExtendDataset.
Definition at line 88 of file ExtendAbstractDataset.java.
References anl.verdi.data.ExtendAbstractDataset.getCoordAxes().
boolean anl.verdi.data.ExtendAbstractDataset.hasYAxis ()
Returns
true if there is a Y axis, otherwise false
Implements anl.verdi.data.ExtendDataset.
Definition at line 95 of file ExtendAbstractDataset.java.
References anl.verdi.data.ExtendAbstractDataset.getCoordAxes().
boolean anl.verdi.data.ExtendAbstractDataset.hasZAxis ()
See if there is a z (e.g. layer) axis
Returns
true if there is a Z axis, otherwise false
Implements anl.verdi.data.ExtendDataset.
Definition at line 104 of file ExtendAbstractDataset.java.
References anl.verdi.data.ExtendAbstractDataset.getCoordAxes().
boolean anl.verdi.data.ExtendAbstractDataset.isObs ()
Whether or not this dataset represents an observational dataset. NOTE: Always returns FALSE.
Returns
true if this contains obs data, otherwise false.
Implements anl.verdi.data.ExtendDataset.
Definition at line 130 of file ExtendAbstractDataset.java.
void anl.verdi.data.ExtendAbstractDataset.setAlias (String alias)
Sets the alias for this Dataset.
Parameters
alias the alias for this Dataset.
Implements anl.verdi.data.ExtendDataset.
Definition at line 47 of file ExtendAbstractDataset.java.
References anl.verdi.data.ExtendAbstractDataset.alias.
Member Data Documentation
String anl.verdi.data.ExtendAbstractDataset.alias = NULL_ALIAS protected
Definition at line 10 of file ExtendAbstractDataset.java.
Referenced by anl.verdi.data.ExtendAbstractDataset.getAlias(), and anl.verdi.data.ExtendAbstractDataset.setAlias().
URL anl.verdi.data.ExtendAbstractDataset.url protected
Definition at line 11 of file ExtendAbstractDataset.java.
Referenced by anl.verdi.data.ExtendAbstractDataset.ExtendAbstractDataset(), and anl.verdi.data.ExtendAbstractDataset.getURL().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/data/ExtendAbstractDataset.java