VERDI: anl.verdi.plot.config.PlotConfigurationIO Class Reference
anl.verdi.plot.config.PlotConfigurationIO Class Reference
Public Member Functions
PlotConfigurationIO ()
void addConvertor (String className, StringConvertor convertor)
void startElement (String uri, String localName, String qName, Attributes attributes) throws SAXException
PlotConfiguration loadConfiguration (File file) throws IOException
Detailed Description
Interface for classes that represent a plot configuration and can save and load the configuration data.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 34 of file PlotConfigurationIO.java.
Constructor & Destructor Documentation
anl.verdi.plot.config.PlotConfigurationIO.PlotConfigurationIO ()
Definition at line 131 of file PlotConfigurationIO.java.
References anl.verdi.plot.config.PlotConfigurationIO.addConvertor().
Member Function Documentation
void anl.verdi.plot.config.PlotConfigurationIO.addConvertor (String className, StringConvertor convertor)
Adds a converter to convert some class to and from a String representation.
Parameters
className the class this converter operates on
convertor the converter
Definition at line 148 of file PlotConfigurationIO.java.
Referenced by anl.verdi.plot.config.PlotConfigurationIO.PlotConfigurationIO().
PlotConfiguration anl.verdi.plot.config.PlotConfigurationIO.loadConfiguration (File file) throws IOException
Loads the configuration data from the specified file into a PlotConfiguration and returns that configuration.
Parameters
file contains the configuration data
Returns
the loaded PlotConfiguration
Exceptions
IOException if an error occurs during loading.
Definition at line 218 of file PlotConfigurationIO.java.
References anl.verdi.plot.config.TilePlotConfiguration.COLOR_MAP, anl.verdi.plot.config.PlotConfiguration.getObject(), and anl.verdi.plot.config.PlotConfiguration.LEGEND_SHOW.
void anl.verdi.plot.config.PlotConfigurationIO.startElement (String uri, String localName, String qName, Attributes attributes) throws SAXException
Definition at line 197 of file PlotConfigurationIO.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/config/PlotConfigurationIO.java