VERDI: anl.verdi.util.FormulaArray Class Reference
anl.verdi.util.FormulaArray Class Reference
Public Member Functions
FormulaArray (double val)
FormulaArray (double val, boolean isTmp)
FormulaArray (Array array)
FormulaArray (Array array, boolean isTmp)
FormulaArray foreach (DoubleFunction func)
void foreach (DoubleFunction func, FormulaArray result)
Array getArray ()
boolean isTmp ()
FormulaArray times (FormulaArray other)
void times (FormulaArray other, FormulaArray result)
FormulaArray divide (FormulaArray other)
void divide (FormulaArray other, FormulaArray result)
FormulaArray minus (FormulaArray other)
void minus (FormulaArray other, FormulaArray result)
FormulaArray plus (FormulaArray other)
void plus (FormulaArray other, FormulaArray result)
FormulaArray lessThan (FormulaArray other)
void lessThan (FormulaArray other, FormulaArray result)
FormulaArray lessThanEq (FormulaArray other)
void lessThanEq (FormulaArray other, FormulaArray result)
FormulaArray greaterThan (FormulaArray other)
void greaterThan (FormulaArray other, FormulaArray result)
FormulaArray greaterThanEq (FormulaArray other)
void greaterThanEq (FormulaArray other, FormulaArray result)
FormulaArray notEqual (FormulaArray other)
void notEqual (FormulaArray other, FormulaArray result)
FormulaArray equal (FormulaArray other)
void equal (FormulaArray other, FormulaArray result)
FormulaArray and (FormulaArray other)
void and (FormulaArray other, FormulaArray result)
FormulaArray or (FormulaArray other)
void or (FormulaArray other, FormulaArray result)
FormulaArray mod (FormulaArray other)
void mod (FormulaArray other, FormulaArray result)
FormulaArray pow (FormulaArray other)
void pow (FormulaArray other, FormulaArray result)
boolean equals (FormulaArray other)
double min ()
double max ()
int[] minIndices ()
int[] maxIndices ()
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 11 of file FormulaArray.java.
Constructor & Destructor Documentation
anl.verdi.util.FormulaArray.FormulaArray (double val)
Definition at line 140 of file FormulaArray.java.
Referenced by anl.verdi.util.FormulaArray.foreach().
anl.verdi.util.FormulaArray.FormulaArray (double val, boolean isTmp)
Definition at line 144 of file FormulaArray.java.
References anl.verdi.util.FormulaArray.isTmp().
anl.verdi.util.FormulaArray.FormulaArray (Array array)
Definition at line 153 of file FormulaArray.java.
anl.verdi.util.FormulaArray.FormulaArray (Array array, boolean isTmp)
Definition at line 157 of file FormulaArray.java.
References anl.verdi.util.FormulaArray.isTmp().
Member Function Documentation
FormulaArray anl.verdi.util.FormulaArray.and (FormulaArray other)
Definition at line 294 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.and (FormulaArray other, FormulaArray result)
Definition at line 300 of file FormulaArray.java.
FormulaArray anl.verdi.util.FormulaArray.divide (FormulaArray other)
Definition at line 204 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.divide (FormulaArray other, FormulaArray result)
Definition at line 210 of file FormulaArray.java.
FormulaArray anl.verdi.util.FormulaArray.equal (FormulaArray other)
Definition at line 284 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.equal (FormulaArray other, FormulaArray result)
Definition at line 290 of file FormulaArray.java.
boolean anl.verdi.util.FormulaArray.equals (FormulaArray other)
Definition at line 334 of file FormulaArray.java.
References anl.verdi.util.FormulaArray.isTmp().
FormulaArray anl.verdi.util.FormulaArray.foreach (DoubleFunction func)
Definition at line 164 of file FormulaArray.java.
References anl.verdi.util.ArrayFactory.createDoubleArray(), and anl.verdi.util.FormulaArray.FormulaArray().
void anl.verdi.util.FormulaArray.foreach (DoubleFunction func, FormulaArray result)
Definition at line 170 of file FormulaArray.java.
Array anl.verdi.util.FormulaArray.getArray ()
Definition at line 178 of file FormulaArray.java.
FormulaArray anl.verdi.util.FormulaArray.greaterThan (FormulaArray other)
Definition at line 254 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.greaterThan (FormulaArray other, FormulaArray result)
Definition at line 260 of file FormulaArray.java.
FormulaArray anl.verdi.util.FormulaArray.greaterThanEq (FormulaArray other)
Definition at line 264 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.greaterThanEq (FormulaArray other, FormulaArray result)
Definition at line 270 of file FormulaArray.java.
boolean anl.verdi.util.FormulaArray.isTmp ()
Definition at line 182 of file FormulaArray.java.
Referenced by anl.verdi.util.FormulaArray.equals(), and anl.verdi.util.FormulaArray.FormulaArray().
FormulaArray anl.verdi.util.FormulaArray.lessThan (FormulaArray other)
Definition at line 234 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.lessThan (FormulaArray other, FormulaArray result)
Definition at line 240 of file FormulaArray.java.
FormulaArray anl.verdi.util.FormulaArray.lessThanEq (FormulaArray other)
Definition at line 244 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.lessThanEq (FormulaArray other, FormulaArray result)
Definition at line 250 of file FormulaArray.java.
double anl.verdi.util.FormulaArray.max ()
Gets the maximum value in this formula array.
Returns
the maximum value in this formula array.
Definition at line 353 of file FormulaArray.java.
int [] anl.verdi.util.FormulaArray.maxIndices ()
Gets the indices where the max value occurs.
Returns
the indices where the max value occurs.
Definition at line 373 of file FormulaArray.java.
double anl.verdi.util.FormulaArray.min ()
Gets the minimum value in this formula array.
Returns
the minimum value in this formula array.
Definition at line 343 of file FormulaArray.java.
int [] anl.verdi.util.FormulaArray.minIndices ()
Gets the indices where the min value occurs.
Returns
the indices where the min value occurs.
Definition at line 363 of file FormulaArray.java.
FormulaArray anl.verdi.util.FormulaArray.minus (FormulaArray other)
Definition at line 214 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.minus (FormulaArray other, FormulaArray result)
Definition at line 220 of file FormulaArray.java.
FormulaArray anl.verdi.util.FormulaArray.mod (FormulaArray other)
Definition at line 314 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.mod (FormulaArray other, FormulaArray result)
Definition at line 320 of file FormulaArray.java.
FormulaArray anl.verdi.util.FormulaArray.notEqual (FormulaArray other)
Definition at line 274 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.notEqual (FormulaArray other, FormulaArray result)
Definition at line 280 of file FormulaArray.java.
FormulaArray anl.verdi.util.FormulaArray.or (FormulaArray other)
Definition at line 304 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.or (FormulaArray other, FormulaArray result)
Definition at line 310 of file FormulaArray.java.
FormulaArray anl.verdi.util.FormulaArray.plus (FormulaArray other)
Definition at line 224 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.plus (FormulaArray other, FormulaArray result)
Definition at line 230 of file FormulaArray.java.
FormulaArray anl.verdi.util.FormulaArray.pow (FormulaArray other)
Definition at line 324 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.pow (FormulaArray other, FormulaArray result)
Definition at line 330 of file FormulaArray.java.
FormulaArray anl.verdi.util.FormulaArray.times (FormulaArray other)
Definition at line 194 of file FormulaArray.java.
void anl.verdi.util.FormulaArray.times (FormulaArray other, FormulaArray result)
Definition at line 200 of file FormulaArray.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/util/FormulaArray.java