VERDI: anl.verdi.plot.gui.FastObsOverlayDialog Class Reference
anl.verdi.plot.gui.FastObsOverlayDialog Class Reference
Public Member Functions
FastObsOverlayDialog (Dialog owner)
FastObsOverlayDialog (Frame owner)
void propertyChange (PropertyChangeEvent evt)
void addListeners ()
void setObservationData (List obsData)
boolean showLegend ()
void initComponents ()
Public Member Functions inherited from anl.verdi.plot.gui.ObsOverlayDialog
ObsOverlayDialog (Frame owner)
ObsOverlayDialog (Dialog owner)
Symbol getSymbol ()
int getShapeSize ()
int getStrokeSize ()
boolean isCanceled ()
Variable getSelectedVar ()
boolean showLegend ()
void init (java.util.List< Variable > vars, ObsTimeChecker checker)
Protected Attributes
JComponent separator2
Protected Attributes inherited from anl.verdi.plot.gui.ObsOverlayDialog
boolean canceled = true
int strokeSize
Variable selectedVar
ObsTimeChecker checker
ObsAnnotation.Symbol symbol
JPanel dialogPane
JPanel contentPanel
JLabel statusLbl
JComponent separator1
JScrollPane scrollPane1
JList varList
JLabel label1
JSpinner strokeSpn
JLabel label2
JSpinner shapeSpn
JLabel label3
Symbol[] names
Icon[] symbols
JComboBox symList
JLabel selectedImg
JPanel symPanel
JPanel buttonBar
JButton okButton
JButton cancelButton
Additional Inherited Members
Protected Member Functions inherited from anl.verdi.plot.gui.ObsOverlayDialog
void addListeners ()
Symbol getSelectedSymbol ()
void initComponents ()
Detailed Description
Definition at line 50 of file FastObsOverlayDialog.java.
Constructor & Destructor Documentation
anl.verdi.plot.gui.FastObsOverlayDialog.FastObsOverlayDialog (Dialog owner)
Definition at line 55 of file FastObsOverlayDialog.java.
anl.verdi.plot.gui.FastObsOverlayDialog.FastObsOverlayDialog (Frame owner)
Definition at line 60 of file FastObsOverlayDialog.java.
Member Function Documentation
void anl.verdi.plot.gui.FastObsOverlayDialog.addListeners ()
Definition at line 88 of file FastObsOverlayDialog.java.
References anl.verdi.plot.gui.ObsOverlayDialog.canceled, anl.verdi.plot.gui.ObsOverlayDialog.checker, anl.verdi.util.ObsTimeChecker.isCompatible(), and anl.verdi.plot.gui.ObsOverlayDialog.varList.
void anl.verdi.plot.gui.FastObsOverlayDialog.initComponents ()
Definition at line 145 of file FastObsOverlayDialog.java.
References anl.verdi.plot.gui.ObsOverlayDialog.buttonBar, anl.verdi.plot.gui.ObsOverlayDialog.cancelButton, anl.verdi.plot.gui.ObsAnnotation.Symbol.CIRCLE, anl.verdi.plot.gui.ObsOverlayDialog.contentPanel, anl.verdi.plot.gui.ObsOverlayDialog.dialogPane, anl.verdi.plot.gui.ObsAnnotation.Symbol.DIAMOND, anl.verdi.plot.gui.ObsOverlayDialog.label1, anl.verdi.plot.gui.ObsOverlayDialog.label2, anl.verdi.plot.gui.ObsOverlayDialog.label3, anl.verdi.plot.gui.ObsOverlayDialog.names, anl.verdi.plot.gui.ObsOverlayDialog.okButton, anl.verdi.plot.gui.ObsOverlayDialog.scrollPane1, anl.verdi.plot.gui.ObsOverlayDialog.selectedImg, anl.verdi.plot.gui.ObsOverlayDialog.separator1, anl.verdi.plot.gui.FastObsOverlayDialog.separator2, anl.verdi.plot.gui.ObsOverlayDialog.shapeSpn, anl.verdi.plot.gui.FastObsOverlayDialog.showLegend(), anl.verdi.plot.gui.ObsAnnotation.Symbol.SQUARE, anl.verdi.plot.gui.ObsAnnotation.Symbol.STAR, anl.verdi.plot.gui.ObsOverlayDialog.statusLbl, anl.verdi.plot.gui.ObsOverlayDialog.strokeSpn, anl.verdi.plot.gui.ObsAnnotation.Symbol.SUN, anl.verdi.plot.gui.ObsOverlayDialog.symbols, anl.verdi.plot.gui.ObsOverlayDialog.symList, anl.verdi.plot.gui.ObsOverlayDialog.symPanel, anl.verdi.plot.gui.ObsOverlayDialog.varList, anl.verdi.core.VerdiConstants.VERDI_LIST_OBJECT, and anl.verdi.core.VerdiConstants.VERDI_LIST_OBJECT_NUMBER.
void anl.verdi.plot.gui.FastObsOverlayDialog.propertyChange (PropertyChangeEvent evt)
Definition at line 65 of file FastObsOverlayDialog.java.
References anl.verdi.core.VerdiConstants.VERDI_LIST_OBJECT, and anl.verdi.core.VerdiConstants.VERDI_LIST_OBJECT_NUMBER.
void anl.verdi.plot.gui.FastObsOverlayDialog.setObservationData (List obsData)
Definition at line 137 of file FastObsOverlayDialog.java.
boolean anl.verdi.plot.gui.FastObsOverlayDialog.showLegend ()
Definition at line 141 of file FastObsOverlayDialog.java.
Referenced by anl.verdi.plot.gui.FastObsOverlayDialog.initComponents().
Member Data Documentation
JComponent anl.verdi.plot.gui.FastObsOverlayDialog.separator2 protected
Definition at line 390 of file FastObsOverlayDialog.java.
Referenced by anl.verdi.plot.gui.FastObsOverlayDialog.initComponents().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/gui/FastObsOverlayDialog.java