VERDI: anl.verdi.gui.OKCancelWindow Class Reference
anl.verdi.gui.OKCancelWindow Class Reference
Public Member Functions
OKCancelWindow (Dialog fr, String title, boolean state)
OKCancelWindow (Frame fr, String title, boolean state)
void actionPerformed (ActionEvent event)
void cancelAction ()
void windowClosing (WindowEvent e)
Public Member Functions inherited from anl.verdi.gui.OKWindow
OKWindow (Dialog fr, String title, boolean state)
OKWindow (Frame fr, String title, boolean state)
OKWindow (Frame fr, String title, boolean state, String[] buttons)
void actionPerformed (ActionEvent event)
void addPrintButton ()
void busy ()
boolean doAction ()
void doPrint ()
Frame getParentFrame ()
void notBusy ()
void oKAction ()
void centerOver (Component comp)
void setEnabled (boolean state)
void windowActivated (WindowEvent e)
void windowClosed (WindowEvent e)
void windowClosing (WindowEvent e)
void windowDeactivated (WindowEvent e)
void windowDeiconified (WindowEvent e)
void windowIconified (WindowEvent e)
void windowOpened (WindowEvent e)
Public Member Functions inherited from anl.verdi.gui.ExtendedDialog
ExtendedDialog (Frame owner) throws HeadlessException
ExtendedDialog (Frame owner, boolean modal) throws HeadlessException
ExtendedDialog (Frame owner, String title) throws HeadlessException
ExtendedDialog (Frame owner, String title, boolean modal) throws HeadlessException
ExtendedDialog (Frame owner, String title, boolean modal, GraphicsConfiguration gc)
void show ()
Additional Inherited Members
Static Public Member Functions inherited from anl.verdi.gui.OKWindow
static void setChildrenEnabled (Component item, boolean state)
Static Public Member Functions inherited from anl.verdi.gui.ExtendedDialog
static void setDefaultParent (Frame win)
static Frame getDefaultParent ()
Protected Attributes inherited from anl.verdi.gui.OKWindow
JPanel buttonPanel
Frame parentFrame
Detailed Description
A dialog window that contains an OK and a Cancel button.
Version
1.0 May 1997
Author
Mary Ann Bitz, ANL
Definition at line 54 of file OKCancelWindow.java.
Constructor & Destructor Documentation
anl.verdi.gui.OKCancelWindow.OKCancelWindow (Dialog fr, String title, boolean state)
Definition at line 59 of file OKCancelWindow.java.
anl.verdi.gui.OKCancelWindow.OKCancelWindow (Frame fr, String title, boolean state)
Constructs an OKCancelWindow beneath the given window, with the indicated title and modality
Parameters
fr parent frame of this window
title title of this window
state whether the window should be modal
Definition at line 73 of file OKCancelWindow.java.
Member Function Documentation
void anl.verdi.gui.OKCancelWindow.actionPerformed (ActionEvent event)
Event handler that is called when a button is pressed.
Definition at line 84 of file OKCancelWindow.java.
References anl.verdi.gui.OKCancelWindow.cancelAction().
void anl.verdi.gui.OKCancelWindow.cancelAction ()
Method called when the cancel button is pressed indicating the action should not be performed and the window should be disposed.
Definition at line 97 of file OKCancelWindow.java.
Referenced by anl.verdi.gui.OKCancelWindow.actionPerformed(), and anl.verdi.gui.OKCancelWindow.windowClosing().
void anl.verdi.gui.OKCancelWindow.windowClosing (WindowEvent e)
Definition at line 100 of file OKCancelWindow.java.
References anl.verdi.gui.OKCancelWindow.cancelAction().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/gui/OKCancelWindow.java