VERDI: saf.core.ui.DefaultDockingFactory Class Reference
saf.core.ui.DefaultDockingFactory Class Reference
Public Member Functions
DockingManager getViewManager (GUIBarManager barManager, List< Perspective > perspectives)
ISAFDisplay getDisplay ()
Perspective createPerspective (String id, String name)
Detailed Description
Default implementation of docking factory that uses the Docking Frames library for its docking behavior.
Author
Nick Collier
Definition at line 14 of file DefaultDockingFactory.java.
Member Function Documentation
Perspective saf.core.ui.DefaultDockingFactory.createPerspective (String id, String name)
Creates a Perspective.
Parameters
id the unique id of the perspective
name the name of the perspective.
Returns
the created Perspective.
Implements saf.core.ui.dock.DockingFactory.
Definition at line 62 of file DefaultDockingFactory.java.
References saf.core.ui.DefaultSAFDisplay.getCControl(), and saf.core.ui.DefaultDockingFactory.getDisplay().
ISAFDisplay saf.core.ui.DefaultDockingFactory.getDisplay ()
Gets the display.
Returns
the display.
Implements saf.core.ui.dock.DockingFactory.
Definition at line 46 of file DefaultDockingFactory.java.
Referenced by saf.core.ui.DefaultDockingFactory.createPerspective(), and saf.core.ui.DefaultDockingFactory.getViewManager().
DockingManager saf.core.ui.DefaultDockingFactory.getViewManager (GUIBarManager barManager, List< Perspective > perspectives)
Gets the DockingManager. If the docking manager has not yet been created this should create one using the specified barManager and perspectives.
Parameters
barManager the bar manager
perspectives list of user-defined perspectives
Returns
the ViewManager.
Implements saf.core.ui.dock.DockingFactory.
Definition at line 28 of file DefaultDockingFactory.java.
References saf.core.ui.DefaultSAFDisplay.getCControl(), and saf.core.ui.DefaultDockingFactory.getDisplay().
The documentation for this class was generated from the following file:
verdi_saf_ui/src/saf/core/ui/DefaultDockingFactory.java