VERDI: anl.verdi.util.VUnits Class Reference
anl.verdi.util.VUnits Class Reference
Static Public Member Functions
static Unit createUnit (String unitString)
static Unit createConvUnit (String unitString)
static String getFormattedName (Unit unit)
Static Public Attributes
static final Unit MISSING_UNIT = new BaseUnit("_MISSING_UNIT_")
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 69 of file VUnits.java.
Member Function Documentation
static Unit anl.verdi.util.VUnits.createConvUnit (String unitString) static
Parses the unit string into a Unit object. When possible a known unit (e.g. kg, kg / m2, etc.) will be returned otherwise a unit unique to the string will be returned.
Parameters
unitString the string to parse
Returns
the created Unit.
Definition at line 139 of file VUnits.java.
static Unit anl.verdi.util.VUnits.createUnit (String unitString) static
Parses the unit string into a Unit object. A unit unique to the string will be returned.
Parameters
unitString the string to parse
Returns
the created Unit.
Definition at line 127 of file VUnits.java.
Referenced by anl.verdi.loaders.SpreadsheetReader.SpreadsheetReader().
static String anl.verdi.util.VUnits.getFormattedName (Unit unit) static
Definition at line 143 of file VUnits.java.
Referenced by anl.verdi.data.DefaultVariable.DefaultVariable().
Member Data Documentation
final Unit anl.verdi.util.VUnits.MISSING_UNIT = new BaseUnit("_MISSING_UNIT_") static
Definition at line 76 of file VUnits.java.
Referenced by anl.verdi.loaders.CSVCoordAxis.CSVCoordAxis(), and anl.verdi.loaders.ExtendCSVCoordAxis.ExtendCSVCoordAxis().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/util/VUnits.java