VERDI: anl.verdi.util.DateRange Class Reference
anl.verdi.util.DateRange Class Reference
Public Member Functions
DateRange (GregorianCalendar gregorianCalendar, GregorianCalendar gregorianCalendar2)
DateRange (long start, long end)
long getEnd ()
long getStart ()
DateRange overlap (DateRange other)
boolean equals (Object obj)
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 12 of file DateRange.java.
Constructor & Destructor Documentation
anl.verdi.util.DateRange.DateRange (GregorianCalendar gregorianCalendar, GregorianCalendar gregorianCalendar2)
Definition at line 16 of file DateRange.java.
Referenced by anl.verdi.util.DateRange.equals(), and anl.verdi.util.DateRange.overlap().
anl.verdi.util.DateRange.DateRange (long start, long end)
Definition at line 22 of file DateRange.java.
Member Function Documentation
boolean anl.verdi.util.DateRange.equals (Object obj)
Definition at line 61 of file DateRange.java.
References anl.verdi.util.DateRange.DateRange().
long anl.verdi.util.DateRange.getEnd ()
Definition at line 29 of file DateRange.java.
long anl.verdi.util.DateRange.getStart ()
Definition at line 33 of file DateRange.java.
DateRange anl.verdi.util.DateRange.overlap (DateRange other)
Definition at line 37 of file DateRange.java.
References anl.verdi.util.DateRange.DateRange().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/util/DateRange.java