VERDI: saf.core.ui.GUIBarManager Class Reference
saf.core.ui.GUIBarManager Class Reference
Public Member Functions
GUIBarManager (JToolBar toolBar, JMenuBar menuBar)
void createHelpMenu ()
void createWindowMenu ()
void createPerspectiveMenu (DockingManager vManager)
void addToolBarSeparator ()
void addToolBarSeparator (Dimension size)
void addToolBarSeparator (String groupID)
Component addToolBarComponent (String groupID, String id, Component component)
JButton addToolBarAction (String groupID, String id, Action action)
Component getToolBarComponent (String id)
Collection< Component > getComponents (String groupId)
JMenu addMenu (String id, String menuName)
void updateWindowMenu ()
void addWindowItem (ActionDescriptor descriptor)
JMenu addMenu (JMenu parentMenu, String id, String menuName)
void selectMenuItem (String id)
JMenuItem addMenuItem (String id, String menuID, Action action)
JMenuItem addMenuItem (String id, String menuID, String menuItemLabel)
JMenuItem addMenuItem (String id, String menuId, JMenuItem item)
JMenuItem addMenuItem (String id, JMenu menu, Action action)
JMenuItem addMenuItem (String id, JMenu menu, String menuItemLabel)
void sortMenu (String menuID)
JMenu getMenu (String menuID)
JMenuItem getMenuItem (String id)
void addMenuSeparator (String menuID)
JToolBar getToolBar ()
JMenuBar getMenuBar ()
void removeMenu (String menuID)
JMenu clearMenu (String menuID)
void removeMenuItem (String id)
JPanel getStatusBar ()
JComponent getStatusBarComponent (String statusFieldName)
void setStatusBarComponent (String statusFieldName, JComponent comp)
void setStatusBarTextColor (String statusFieldName, Color color)
void setStatusBarFont (String statusFieldName, Font font)
Color getStatusBarTextColor (String statusFieldName)
void setStatusBarText (String statusFieldName, String text)
String getStatusBarText (String statusFieldName)
Detailed Description
Managers menu, tool and status bar configuration and manipulation. The toolbar is divided into named groups divided by separators. This allows buttons to be grouped in the toolbar.
Author
Nick Collier
Definition at line 22 of file GUIBarManager.java.
Constructor & Destructor Documentation
saf.core.ui.GUIBarManager.GUIBarManager (JToolBar toolBar, JMenuBar menuBar)
Creates a GUIBarManager managing the specified tool and menu bars.
Parameters
toolBar the toolbar to manage
menuBar the menubar to manage
Definition at line 119 of file GUIBarManager.java.
Member Function Documentation
JMenu saf.core.ui.GUIBarManager.addMenu (String id, String menuName)
Adds a menu with the specified id and name.
Parameters
id the id that uniquely identifies the menu
menuName the name or label of the mnu
Returns
the created JMenu
Definition at line 334 of file GUIBarManager.java.
Referenced by saf.core.ui.GUIBarManager.createHelpMenu(), saf.core.ui.GUIBarManager.createPerspectiveMenu(), and saf.core.ui.GUIBarManager.createWindowMenu().
JMenu saf.core.ui.GUIBarManager.addMenu (JMenu parentMenu, String id, String menuName)
Adds a menu to the specified parent menu as a submenu.
Parameters
parentMenu the parent menu
id the id uniquely identifying the submenu
menuName the name or label of the submenu
Returns
the created JMenu
Definition at line 385 of file GUIBarManager.java.
JMenuItem saf.core.ui.GUIBarManager.addMenuItem (String id, String menuID, Action action)
Adds the specified action as a menu item to the specified menu.
Parameters
id an id that will uniquely identify the menu item
menuID the id of the menu to add the item to
action the action that will occur when the menu item is clicked
Returns
the created menu item.
Definition at line 413 of file GUIBarManager.java.
Referenced by saf.core.ui.GUIBarManager.addMenuItem(), and saf.core.ui.GUIBarManager.createPerspectiveMenu().
JMenuItem saf.core.ui.GUIBarManager.addMenuItem (String id, String menuID, String menuItemLabel)
Adds a menu item to the specified menu.
Parameters
id an id that will uniquely identify the menu item
menuID the id of the menu to add the item to
menuItemLabel the label of the menu item
Returns
the created menu item.
Definition at line 433 of file GUIBarManager.java.
References saf.core.ui.GUIBarManager.addMenuItem().
JMenuItem saf.core.ui.GUIBarManager.addMenuItem (String id, String menuId, JMenuItem item)
Adds the specified menu item to the specified menu.
Parameters
id an id that will uniquely identify the menu item
menuId the id of the menu to add the item to
item the menu item to add
Returns
the menu item
Definition at line 446 of file GUIBarManager.java.
References saf.core.ui.GUIBarManager.addMenuItem().
JMenuItem saf.core.ui.GUIBarManager.addMenuItem (String id, JMenu menu, Action action)
Adds the specified action as a menu item to the specified menu.
Parameters
id an id that will uniquely identify the menu item
menu the menu to add the item to
action the action that will occur when the menu item is clicked
Returns
the created menu item.
Definition at line 466 of file GUIBarManager.java.
References saf.core.ui.GUIBarManager.addMenuItem().
JMenuItem saf.core.ui.GUIBarManager.addMenuItem (String id, JMenu menu, String menuItemLabel)
Adds a menu item to the specified menu.
Parameters
id an id that will uniquely identify the menu item
menu the menu to add the item to
menuItemLabel the label of the menu item
Returns
the created menu item.
Definition at line 478 of file GUIBarManager.java.
References saf.core.ui.GUIBarManager.addMenuItem().
void saf.core.ui.GUIBarManager.addMenuSeparator (String menuID)
Adds a separator to the specified menu.
Parameters
menuID the id of the menu
Definition at line 535 of file GUIBarManager.java.
JButton saf.core.ui.GUIBarManager.addToolBarAction (String groupID, String id, Action action)
Adds the specified action to the toolbar as part of the specified group.
Parameters
groupID the group to add the action to
id the id of the action
action the action to
Returns
the JButton associated with the action
Definition at line 296 of file GUIBarManager.java.
References saf.core.ui.GUIBarManager.addToolBarComponent().
Component saf.core.ui.GUIBarManager.addToolBarComponent (String groupID, String id, Component component)
Adds the specified component to the specified group.
Parameters
groupID the group to add the component to
id the id of the component
component the component to add
Returns
the added component
Definition at line 275 of file GUIBarManager.java.
Referenced by saf.core.ui.GUIBarManager.addToolBarAction().
void saf.core.ui.GUIBarManager.addToolBarSeparator ()
Adds a separator to the toolbar.
Definition at line 240 of file GUIBarManager.java.
void saf.core.ui.GUIBarManager.addToolBarSeparator (Dimension size)
Adds a separator of the specified size to the toolbar.
Parameters
size the size of the separator
Definition at line 249 of file GUIBarManager.java.
void saf.core.ui.GUIBarManager.addToolBarSeparator (String groupID)
Adds a tool bar separator to the specified tool bar group.
Parameters
groupID the name of the group
Definition at line 258 of file GUIBarManager.java.
void saf.core.ui.GUIBarManager.addWindowItem (ActionDescriptor descriptor)
Adds an action to be added to the window menu. If the window menu does not yet exist, then the item will be added when its created.
Parameters
descriptor the action
Definition at line 369 of file GUIBarManager.java.
JMenu saf.core.ui.GUIBarManager.clearMenu (String menuID)
Empties the specified menu of any menu items.
Parameters
menuID the id of the menu clear
Returns
the cleared menu
Definition at line 575 of file GUIBarManager.java.
References saf.core.ui.GUIBarManager.removeMenu().
void saf.core.ui.GUIBarManager.createHelpMenu ()
Creates the help menu.
Definition at line 141 of file GUIBarManager.java.
References saf.core.ui.GUIBarManager.addMenu(), saf.core.ui.GUIBarManager.getMenu(), and saf.core.ui.GUIConstants.HELP_MENU_ID.
void saf.core.ui.GUIBarManager.createPerspectiveMenu (DockingManager vManager)
Creates the perspective menu.
Parameters
vManager the docking manager that contains the perspectiv einfo
Definition at line 166 of file GUIBarManager.java.
References saf.core.ui.GUIBarManager.addMenu(), saf.core.ui.GUIBarManager.addMenuItem(), saf.core.ui.dock.Perspective.getID(), saf.core.ui.GUIBarManager.getMenu(), saf.core.ui.dock.DockingManager.getPerspective(), saf.core.ui.dock.DockingManager.getPerspectiveIDs(), saf.core.ui.GUIConstants.PERSPECTIVE_MENU_ID, and saf.core.ui.GUIBarManager.sortMenu().
void saf.core.ui.GUIBarManager.createWindowMenu ()
Creates the window menu.
Definition at line 152 of file GUIBarManager.java.
References saf.core.ui.GUIBarManager.addMenu(), saf.core.ui.GUIBarManager.getMenu(), and saf.core.ui.GUIConstants.WINDOW_MENU_ID.
Collection<Component> saf.core.ui.GUIBarManager.getComponents (String groupId)
Gets all the toolbar components in the specified group.
Parameters
groupId the id of the group of components to return
Returns
all the toolbar components in the specified group.
Definition at line 322 of file GUIBarManager.java.
JMenu saf.core.ui.GUIBarManager.getMenu (String menuID)
Gets the menu with the specified id.
Parameters
menuID the id of the menu to return
Returns
the menu with the specified id.
Definition at line 516 of file GUIBarManager.java.
Referenced by saf.core.ui.GUIBarManager.createHelpMenu(), saf.core.ui.GUIBarManager.createPerspectiveMenu(), saf.core.ui.GUIBarManager.createWindowMenu(), and saf.core.ui.GUIBarManager.sortMenu().
JMenuBar saf.core.ui.GUIBarManager.getMenuBar ()
Gets the managed menu.
Returns
the managed menu.
Definition at line 553 of file GUIBarManager.java.
JMenuItem saf.core.ui.GUIBarManager.getMenuItem (String id)
Gets the menu item with the specified id.
Parameters
id the id of the menu to return
Returns
the menu item with the specified id.
Definition at line 526 of file GUIBarManager.java.
JPanel saf.core.ui.GUIBarManager.getStatusBar ()
Gets the status bar that contains all the user defined status fields.
Returns
the status bar that contains all the user defined status fields.
Definition at line 642 of file GUIBarManager.java.
JComponent saf.core.ui.GUIBarManager.getStatusBarComponent (String statusFieldName)
Gets the named status bar component.
Parameters
statusFieldName the status field name
Returns
the named status bar component.
Definition at line 657 of file GUIBarManager.java.
String saf.core.ui.GUIBarManager.getStatusBarText (String statusFieldName)
Returns a String containing the current text in a status bar. added as part of the VERDI 2016 update Jo Ellen Brandmeyer, Institute for the Environment, 1/12/2016
Parameters
statusFieldName the name of the status field
Returns
a String containing the contents of the status field or null
Definition at line 756 of file GUIBarManager.java.
Color saf.core.ui.GUIBarManager.getStatusBarTextColor (String statusFieldName)
Gets the foreground (eg text color) of the specified status field.
Parameters
statusFieldName the status field whose color we want to get
Returns
the foreground (eg text color) of the specified status field, or null if the name status field is not found
Definition at line 719 of file GUIBarManager.java.
JToolBar saf.core.ui.GUIBarManager.getToolBar ()
Gets the managed tool bar.
Returns
the managed tool bar.
Definition at line 544 of file GUIBarManager.java.
Component saf.core.ui.GUIBarManager.getToolBarComponent (String id)
Gets the toolbar component with the specified id. The id is specified when the component is added.
Parameters
id the id of the component to return
Returns
the toolbar component with the specified id.
Definition at line 312 of file GUIBarManager.java.
void saf.core.ui.GUIBarManager.removeMenu (String menuID)
Removes the specified menu.
Parameters
menuID the id of the menu to remove
Definition at line 563 of file GUIBarManager.java.
Referenced by saf.core.ui.GUIBarManager.clearMenu().
void saf.core.ui.GUIBarManager.removeMenuItem (String id)
Removes the specified menu item.
Parameters
id the id of the menu item.
Definition at line 627 of file GUIBarManager.java.
void saf.core.ui.GUIBarManager.selectMenuItem (String id)
Selects the specified menu item. Note that depending on the item, this may have the same effect as clicking that menu item.
Parameters
id the id of the item to select
Definition at line 399 of file GUIBarManager.java.
void saf.core.ui.GUIBarManager.setStatusBarComponent (String statusFieldName, JComponent comp)
Sets the status bar field to contain the specified component.
Parameters
statusFieldName the name (id) of the status field
comp the component to use
Definition at line 672 of file GUIBarManager.java.
References saf.core.ui.StatusBarItem.getName().
void saf.core.ui.GUIBarManager.setStatusBarFont (String statusFieldName, Font font)
Sets the font of the specified status field.
Parameters
statusFieldName the status field whose color we want to set
font the new font for the status bar field
Definition at line 704 of file GUIBarManager.java.
void saf.core.ui.GUIBarManager.setStatusBarText (String statusFieldName, String text)
Sets the text of the specified status field. If the actual status bar component is not a text field this will do nothing.
Parameters
statusFieldName the status field whose text we want to set.
text the text to put in the status field
Definition at line 736 of file GUIBarManager.java.
void saf.core.ui.GUIBarManager.setStatusBarTextColor (String statusFieldName, Color color)
Sets the foreground (eg text color) of the specified status field.
Parameters
statusFieldName the status field whose color we want to set
color the color to set the field to
Definition at line 690 of file GUIBarManager.java.
void saf.core.ui.GUIBarManager.sortMenu (String menuID)
Alphabetically sorts the menu entries in the specified menu.
Parameters
menuID the id of the menu to sort
Definition at line 487 of file GUIBarManager.java.
References saf.core.ui.GUIBarManager.getMenu().
Referenced by saf.core.ui.GUIBarManager.createPerspectiveMenu().
void saf.core.ui.GUIBarManager.updateWindowMenu ()
Updates the window menu, adding the user's window actions.
Definition at line 347 of file GUIBarManager.java.
The documentation for this class was generated from the following file:
verdi_saf_ui/src/saf/core/ui/GUIBarManager.java