VERDI: org.libtiff.jai.codec.XTIFFEncodeParam Class Reference
org.libtiff.jai.codec.XTIFFEncodeParam Class Reference
Public Member Functions
XTIFFEncodeParam (TIFFEncodeParam param)
XTIFFEncodeParam ()
void initialize ()
XTIFFDirectory getDirectory ()
void setCompression (int compression)
int getCompression ()
boolean getWriteTiled ()
void setWriteTiled (boolean writeTiled)
Detailed Description
Definition at line 37 of file XTIFFEncodeParam.java.
Constructor & Destructor Documentation
org.libtiff.jai.codec.XTIFFEncodeParam.XTIFFEncodeParam (TIFFEncodeParam param)
Promotes an XTIFFEncodeParam object from simpler one
Definition at line 49 of file XTIFFEncodeParam.java.
References org.libtiff.jai.codec.XTIFFEncodeParam.initialize(), org.libtiff.jai.codec.XTIFFEncodeParam.setCompression(), and org.libtiff.jai.codec.XTIFFEncodeParam.setWriteTiled().
org.libtiff.jai.codec.XTIFFEncodeParam.XTIFFEncodeParam ()
Constructs an XTIFFEncodeParam object with default values for parameters.
Definition at line 60 of file XTIFFEncodeParam.java.
References org.libtiff.jai.codec.XTIFFEncodeParam.initialize().
Member Function Documentation
int org.libtiff.jai.codec.XTIFFEncodeParam.getCompression ()
Specifies the type of compression to be used. The compression type specified will be honored only if it is compatible with the image being written out.
Definition at line 95 of file XTIFFEncodeParam.java.
XTIFFDirectory org.libtiff.jai.codec.XTIFFEncodeParam.getDirectory ()
Definition at line 73 of file XTIFFEncodeParam.java.
boolean org.libtiff.jai.codec.XTIFFEncodeParam.getWriteTiled ()
If set, the data is in tiled format, instead of in strips.
Definition at line 102 of file XTIFFEncodeParam.java.
void org.libtiff.jai.codec.XTIFFEncodeParam.initialize ()
Initializes an XTIFFEncodeParam with default values for parameters.
Definition at line 67 of file XTIFFEncodeParam.java.
References org.libtiff.jai.codec.XTIFFEncodeParam.setCompression(), and org.libtiff.jai.codec.XTIFFEncodeParam.setWriteTiled().
Referenced by org.libtiff.jai.codec.XTIFFEncodeParam.XTIFFEncodeParam().
void org.libtiff.jai.codec.XTIFFEncodeParam.setCompression (int compression)
Specifies the type of compression to be used. The compression type specified will be honored only if it is compatible with the image being written out.
Parameters
compression The compression type.
Definition at line 84 of file XTIFFEncodeParam.java.
Referenced by org.libtiff.jai.codec.XTIFFEncodeParam.initialize(), and org.libtiff.jai.codec.XTIFFEncodeParam.XTIFFEncodeParam().
void org.libtiff.jai.codec.XTIFFEncodeParam.setWriteTiled (boolean writeTiled)
If set, the data will be written out in tiled format, instead of in strips.
Parameters
writeTiled Specifies whether the image data should be wriiten out in tiled format.
Definition at line 113 of file XTIFFEncodeParam.java.
Referenced by org.libtiff.jai.codec.XTIFFEncodeParam.initialize(), and org.libtiff.jai.codec.XTIFFEncodeParam.XTIFFEncodeParam().
The documentation for this class was generated from the following file:
verdi_core/src/org/libtiff/jai/codec/XTIFFEncodeParam.java