VERDI: org.geotiff.image.KeyRegistry Class Reference
org.geotiff.image.KeyRegistry Class Reference
Static Public Member Functions
static KeyRegistry getKeyRegistry ()
static void addKeyMap (String name, KeyMap map) throws IOException
static void addKeyMap (String name, String resource) throws IOException
static KeyMap getKeyMap (String name)
static int getCode (String map, String key)
static String getKey (String map, int code)
Static Public Attributes
static String GEOKEY = "geokey"
static String GEO_CTRANS = "ProjCoordTransGeoKey"
static String EPSG_PCS = "ProjectedCSTypeGeoKey"
static String EPSG_DATUM = "GeogGeodeticDatumGeoKey"
static String EPSG_ELLIPSE = "GeogEllipsoidGeoKey"
static String EPSG_GCS = "GeogGeographicTypeGeoKey"
static String EPSG_PM = "GeogPrimeMeridianGeoKey"
static String EPSG_PROJ = "ProjectionGeoKey"
static String EPSG_VERTCS = "VerticalCSTypeGeoKey"
static String UNIT_GEOG = "GeogLinearUnitsGeoKey"
static String UNIT_PROJ = "ProjLinearUnitsGeoKey"
static String UNIT_VERTCS = "VerticalUnitsGeoKey"
static KeyRegistry instance = new KeyRegistry()
Detailed Description
The KeyRegistry provides the global registry for all sets of KeyMaps. All methods are static.
Definition at line 10 of file KeyRegistry.java.
Member Function Documentation
static void org.geotiff.image.KeyRegistry.addKeyMap (String name, KeyMap map) throws IOException static
Definition at line 55 of file KeyRegistry.java.
Referenced by org.geotiff.image.KeyRegistry.addKeyMap().
static void org.geotiff.image.KeyRegistry.addKeyMap (String name, String resource) throws IOException static
Definition at line 59 of file KeyRegistry.java.
References org.geotiff.image.KeyRegistry.addKeyMap().
static int org.geotiff.image.KeyRegistry.getCode (String map, String key) static
Definition at line 69 of file KeyRegistry.java.
References org.geotiff.image.KeyRegistry.getKeyMap().
static String org.geotiff.image.KeyRegistry.getKey (String map, int code) static
Definition at line 76 of file KeyRegistry.java.
References org.geotiff.image.KeyRegistry.getKeyMap().
static KeyMap org.geotiff.image.KeyRegistry.getKeyMap (String name) static
Definition at line 64 of file KeyRegistry.java.
Referenced by org.geotiff.image.KeyRegistry.getCode(), and org.geotiff.image.KeyRegistry.getKey().
static KeyRegistry org.geotiff.image.KeyRegistry.getKeyRegistry () static
Definition at line 51 of file KeyRegistry.java.
References org.geotiff.image.KeyRegistry.instance.
Member Data Documentation
String org.geotiff.image.KeyRegistry.EPSG_DATUM = "GeogGeodeticDatumGeoKey" static
Definition at line 16 of file KeyRegistry.java.
String org.geotiff.image.KeyRegistry.EPSG_ELLIPSE = "GeogEllipsoidGeoKey" static
Definition at line 17 of file KeyRegistry.java.
String org.geotiff.image.KeyRegistry.EPSG_GCS = "GeogGeographicTypeGeoKey" static
Definition at line 18 of file KeyRegistry.java.
String org.geotiff.image.KeyRegistry.EPSG_PCS = "ProjectedCSTypeGeoKey" static
Definition at line 15 of file KeyRegistry.java.
String org.geotiff.image.KeyRegistry.EPSG_PM = "GeogPrimeMeridianGeoKey" static
Definition at line 19 of file KeyRegistry.java.
String org.geotiff.image.KeyRegistry.EPSG_PROJ = "ProjectionGeoKey" static
Definition at line 20 of file KeyRegistry.java.
String org.geotiff.image.KeyRegistry.EPSG_VERTCS = "VerticalCSTypeGeoKey" static
Definition at line 21 of file KeyRegistry.java.
String org.geotiff.image.KeyRegistry.GEO_CTRANS = "ProjCoordTransGeoKey" static
Definition at line 14 of file KeyRegistry.java.
String org.geotiff.image.KeyRegistry.GEOKEY = "geokey" static
Definition at line 13 of file KeyRegistry.java.
KeyRegistry org.geotiff.image.KeyRegistry.instance = new KeyRegistry() static
Definition at line 27 of file KeyRegistry.java.
Referenced by org.geotiff.image.KeyRegistry.getKeyRegistry().
String org.geotiff.image.KeyRegistry.UNIT_GEOG = "GeogLinearUnitsGeoKey" static
Definition at line 23 of file KeyRegistry.java.
String org.geotiff.image.KeyRegistry.UNIT_PROJ = "ProjLinearUnitsGeoKey" static
Definition at line 24 of file KeyRegistry.java.
String org.geotiff.image.KeyRegistry.UNIT_VERTCS = "VerticalUnitsGeoKey" static
Definition at line 25 of file KeyRegistry.java.
The documentation for this class was generated from the following file:
verdi_core/src/org/geotiff/image/KeyRegistry.java