VERDI: anl.verdi.formula.FormulaFactory Class Reference
anl.verdi.formula.FormulaFactory Class Reference
Public Member Functions
Formula createFormula (Formula.Type type, String formula, Unit commonUnit)
Formula createTileFormula (String formula, Unit commonUnit)
Formula createTimeStepFormula (String formula, Unit commonUnit)
Detailed Description
Factory for producing formulas for different type data plots.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 18 of file FormulaFactory.java.
Member Function Documentation
Formula anl.verdi.formula.FormulaFactory.createFormula (Formula.Type type, String formula, Unit commonUnit)
Definition at line 32 of file FormulaFactory.java.
References anl.verdi.formula.FormulaFactory.createTileFormula(), and anl.verdi.formula.FormulaFactory.createTimeStepFormula().
Formula anl.verdi.formula.FormulaFactory.createTileFormula (String formula, Unit commonUnit)
Creates a formula that produces data appropriate for a tile plot. The data produced by the formula will contain individual values for each x,y cell in the domain for each layer and timestep.
Parameters
formula the formula to evaluate
commonUnit the desired unit for the result
Returns
a Formula that will produce tile-style data.
Definition at line 59 of file FormulaFactory.java.
Referenced by anl.verdi.formula.FormulaFactory.createFormula().
Formula anl.verdi.formula.FormulaFactory.createTimeStepFormula (String formula, Unit commonUnit)
Creates a formula that produces data appropriate for a time step plot. The data produced by the formula will contain an average of the data at each time step. For each time step, first each layer's x,y domain data is averaged into a value of each layer. Then these layer values are themselves averaged.
Parameters
formula the formula to evaluate
commonUnit the desired unit for the result
Returns
a Formula that will produce tile-style data.
Definition at line 73 of file FormulaFactory.java.
Referenced by anl.verdi.formula.FormulaFactory.createFormula().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/formula/FormulaFactory.java