VERDI: org.libtiff.jai.codecimpl.XTIFFImage Class Reference
org.libtiff.jai.codecimpl.XTIFFImage Class Reference
Public Member Functions
XTIFFImage (SeekableStream stream, TIFFDecodeParam param, int directory) throws IOException
XTIFFDirectory getPrivateIFD (long offset) throws IOException
synchronized Raster getTile (int tileX, int tileY)
Protected Member Functions
void setupImageParameters ()
void setupSamplesAndColor ()
Detailed Description
Definition at line 52 of file XTIFFImage.java.
Constructor & Destructor Documentation
org.libtiff.jai.codecimpl.XTIFFImage.XTIFFImage (SeekableStream stream, TIFFDecodeParam param, int directory) throws IOException
Constructs a XTIFFImage that acquires its data from a given SeekableStream and reads from a particular IFD of the stream. The index of the first IFD is 0.
Parameters
stream the SeekableStream to read from.
param an instance of TIFFDecodeParam, or null.
directory the index of the IFD to read from.
Definition at line 88 of file XTIFFImage.java.
References org.libtiff.jai.codecimpl.XTIFFImage.setupImageParameters(), and org.libtiff.jai.codecimpl.XTIFFImage.setupSamplesAndColor().
Member Function Documentation
XTIFFDirectory org.libtiff.jai.codecimpl.XTIFFImage.getPrivateIFD (long offset) throws IOException
Reads a private IFD from a given offset in the stream. This method may be used to obtain IFDs that are referenced only by private tag values.
Definition at line 588 of file XTIFFImage.java.
synchronized Raster org.libtiff.jai.codecimpl.XTIFFImage.getTile (int tileX, int tileY)
Returns tile (tileX, tileY) as a Raster.
Definition at line 597 of file XTIFFImage.java.
References org.libtiff.jai.util.JaiI18N.getString().
void org.libtiff.jai.codecimpl.XTIFFImage.setupImageParameters () protected
This method gets the image parameters from fields
Definition at line 127 of file XTIFFImage.java.
References org.libtiff.jai.codec.XTIFFField.getAsLong(), org.libtiff.jai.codec.XTIFFDirectory.getField(), org.libtiff.jai.codec.XTIFFDirectory.getFieldAsLong(), org.libtiff.jai.util.JaiI18N.getString(), org.libtiff.jai.codec.XTIFF.TIFFTAG_BITS_PER_SAMPLE, org.libtiff.jai.codec.XTIFF.TIFFTAG_EXTRA_SAMPLES, org.libtiff.jai.codec.XTIFF.TIFFTAG_IMAGE_LENGTH, org.libtiff.jai.codec.XTIFF.TIFFTAG_IMAGE_WIDTH, org.libtiff.jai.codec.XTIFF.TIFFTAG_PHOTOMETRIC_INTERPRETATION, org.libtiff.jai.codec.XTIFF.TIFFTAG_ROWS_PER_STRIP, org.libtiff.jai.codec.XTIFF.TIFFTAG_SAMPLE_FORMAT, org.libtiff.jai.codec.XTIFF.TIFFTAG_SAMPLES_PER_PIXEL, org.libtiff.jai.codec.XTIFF.TIFFTAG_STRIP_BYTE_COUNTS, org.libtiff.jai.codec.XTIFF.TIFFTAG_STRIP_OFFSETS, org.libtiff.jai.codec.XTIFF.TIFFTAG_TILE_BYTE_COUNTS, org.libtiff.jai.codec.XTIFF.TIFFTAG_TILE_LENGTH, org.libtiff.jai.codec.XTIFF.TIFFTAG_TILE_OFFSETS, and org.libtiff.jai.codec.XTIFF.TIFFTAG_TILE_WIDTH.
Referenced by org.libtiff.jai.codecimpl.XTIFFImage.XTIFFImage().
void org.libtiff.jai.codecimpl.XTIFFImage.setupSamplesAndColor () protected
This method constructs the sampleModel, colorModel, determines the image_type and the bands parameter.
Definition at line 267 of file XTIFFImage.java.
References org.libtiff.jai.util.JaiI18N.getString(), org.libtiff.jai.codec.XTIFF.TIFFTAG_COLORMAP, org.libtiff.jai.codec.XTIFF.TYPE_ARGB, org.libtiff.jai.codec.XTIFF.TYPE_ARGB_PRE, org.libtiff.jai.codec.XTIFF.TYPE_BILEVEL_BLACK_IS_ZERO, org.libtiff.jai.codec.XTIFF.TYPE_BILEVEL_WHITE_IS_ZERO, org.libtiff.jai.codec.XTIFF.TYPE_GREYSCALE_BLACK_IS_ZERO, org.libtiff.jai.codec.XTIFF.TYPE_GREYSCALE_WHITE_IS_ZERO, org.libtiff.jai.codec.XTIFF.TYPE_ORGB, org.libtiff.jai.codec.XTIFF.TYPE_PALETTE, org.libtiff.jai.codec.XTIFF.TYPE_RGB, org.libtiff.jai.codec.XTIFF.TYPE_RGB_EXTRA, and org.libtiff.jai.codec.XTIFF.TYPE_TRANS.
Referenced by org.libtiff.jai.codecimpl.XTIFFImage.XTIFFImage().
The documentation for this class was generated from the following file:
verdi_core/src/org/libtiff/jai/codecimpl/XTIFFImage.java