VERDI: anl.verdi.plot.color.Palette Class Reference
anl.verdi.plot.color.Palette Class Reference
Public Member Functions
Palette (Palette pal)
Palette (Color[] colors, String description, boolean reverseColors)
String getDescription ()
Color[] getColors ()
Color[] getOriginalColors ()
void setColor (int index, Color color)
int getColorCount ()
Color getColor (int index)
void setReverseColors (boolean reverseColors)
boolean isReverseColors ()
Static Public Member Functions
static Palette getDefaultPalette ()
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 19 of file Palette.java.
Constructor & Destructor Documentation
anl.verdi.plot.color.Palette.Palette (Palette pal)
Definition at line 27 of file Palette.java.
Referenced by anl.verdi.plot.color.Palette.getDefaultPalette().
anl.verdi.plot.color.Palette.Palette (Color[] colors, String description, boolean reverseColors)
Definition at line 34 of file Palette.java.
Member Function Documentation
Color anl.verdi.plot.color.Palette.getColor (int index)
Definition at line 74 of file Palette.java.
References anl.verdi.plot.color.Palette.getColorCount().
int anl.verdi.plot.color.Palette.getColorCount ()
Definition at line 69 of file Palette.java.
Referenced by anl.verdi.plot.color.Palette.getColor().
Color [] anl.verdi.plot.color.Palette.getColors ()
Definition at line 44 of file Palette.java.
static Palette anl.verdi.plot.color.Palette.getDefaultPalette () static
Definition at line 79 of file Palette.java.
References anl.verdi.plot.color.Palette.Palette().
String anl.verdi.plot.color.Palette.getDescription ()
Definition at line 40 of file Palette.java.
Color [] anl.verdi.plot.color.Palette.getOriginalColors ()
Definition at line 52 of file Palette.java.
boolean anl.verdi.plot.color.Palette.isReverseColors ()
Definition at line 99 of file Palette.java.
void anl.verdi.plot.color.Palette.setColor (int index, Color color)
Definition at line 64 of file Palette.java.
void anl.verdi.plot.color.Palette.setReverseColors (boolean reverseColors)
Definition at line 95 of file Palette.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/color/Palette.java