VERDI: anl.verdi.core.Project Class Reference
anl.verdi.core.Project Class Reference
Public Member Functions
Project (DatasetListModel datasets, FormulaListModel formulas, AreaFileListModel areaFiles)
Project (DatasetListModel datasets, FormulaListModel formulas)
FormulaListElement getSelectedFormula ()
void setSelectedFormula (FormulaListElement selectedFormula)
DatasetListModel getDatasets ()
FormulaListModel getFormulas ()
AreaFileListModel getAreaFiles ()
List< DatasetListElement > getDatasetsAsList ()
List< FormulaListElement > getFormulasAsList ()
FormulaListElement getFormulaFor (String formulaString)
List< AreaFileListElement > getAreaFilesAsList ()
List< AxisRange > createRanges () throws IllegalFormulaException
List< AxisRange > createRanges (FormulaListElement selectedFormula) throws IllegalFormulaException
Set< FormulaListElement > getFormulas (Dataset dataset)
void removeFormulas (Set< FormulaListElement > formulas)
void addAsFormula (FormulaElementCreator fCreator, Variable var)
Detailed Description
Encapsulates the current dataset and formula.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 35 of file Project.java.
Constructor & Destructor Documentation
anl.verdi.core.Project.Project (DatasetListModel datasets, FormulaListModel formulas, AreaFileListModel areaFiles)
Definition at line 42 of file Project.java.
anl.verdi.core.Project.Project (DatasetListModel datasets, FormulaListModel formulas)
Definition at line 48 of file Project.java.
Member Function Documentation
void anl.verdi.core.Project.addAsFormula (FormulaElementCreator fCreator, Variable var)
Adds the specified variable as a single variable formula using the specified formula element creator.
Parameters
fCreator the creator to use
var the variable to add as a formula.
Definition at line 349 of file Project.java.
List<AxisRange> anl.verdi.core.Project.createRanges () throws IllegalFormulaException
Creates the ranges for the currently selected formula given the current project information.
Returns
the ranges for the currently selected formula given the current project information.
Exceptions
IllegalFormulaException if the ranges specified by dataset or by formula are invalid
Definition at line 141 of file Project.java.
List<AxisRange> anl.verdi.core.Project.createRanges (FormulaListElement selectedFormula) throws IllegalFormulaException
Creates the ranges for the currently selected formula given the current project information.
Returns
the ranges for the currently selected formula given the current project information.
Exceptions
IllegalFormulaException if the ranges specified by dataset or by formula are invalid
Definition at line 154 of file Project.java.
References anl.verdi.gui.AbstractListElement.getLayerMax(), anl.verdi.gui.AbstractListElement.getTimeMax(), anl.verdi.gui.AbstractListElement.getXMax(), anl.verdi.gui.AbstractListElement.getYMax(), anl.verdi.gui.AbstractListElement.isLayerUsed(), anl.verdi.gui.AbstractListElement.isTimeUsed(), anl.verdi.gui.AbstractListElement.isXYUsed(), anl.verdi.data.AxisType.LAYER, anl.verdi.data.AxisType.TIME, anl.verdi.data.AxisType.X_AXIS, and anl.verdi.data.AxisType.Y_AXIS.
AreaFileListModel anl.verdi.core.Project.getAreaFiles ()
Definition at line 76 of file Project.java.
List<AreaFileListElement> anl.verdi.core.Project.getAreaFilesAsList ()
Gets the area file list elements as a list.
Returns
the area file list elements as a list.
Definition at line 124 of file Project.java.
References anl.verdi.area.AreaFileListModel.elements().
Referenced by anl.verdi.core.VerdiApplication.loadAreaFile().
DatasetListModel anl.verdi.core.Project.getDatasets ()
Definition at line 66 of file Project.java.
List<DatasetListElement> anl.verdi.core.Project.getDatasetsAsList ()
Definition at line 81 of file Project.java.
References anl.verdi.gui.DatasetListModel.elements().
Referenced by anl.verdi.core.VerdiApplication.loadDataset(), and anl.verdi.core.VerdiApplication.overlayRequested().
FormulaListElement anl.verdi.core.Project.getFormulaFor (String formulaString)
Gets the formula list elements for a particular formula string.
Returns
the formula list elements as a list.
Definition at line 110 of file Project.java.
References anl.verdi.gui.FormulaListModel.elements().
FormulaListModel anl.verdi.core.Project.getFormulas ()
Definition at line 71 of file Project.java.
Set<FormulaListElement> anl.verdi.core.Project.getFormulas (Dataset dataset)
Gets the set of formulas that reference the specified dataset.
Parameters
dataset the dataset
Returns
the set of formulas that reference the specified dataset.
Definition at line 322 of file Project.java.
References anl.verdi.gui.FormulaListModel.elements().
List<FormulaListElement> anl.verdi.core.Project.getFormulasAsList ()
Gets the formula list elements as a list.
Returns
the formula list elements as a list.
Definition at line 96 of file Project.java.
References anl.verdi.gui.FormulaListModel.elements().
FormulaListElement anl.verdi.core.Project.getSelectedFormula ()
Definition at line 55 of file Project.java.
void anl.verdi.core.Project.removeFormulas (Set< FormulaListElement > formulas)
Definition at line 335 of file Project.java.
void anl.verdi.core.Project.setSelectedFormula (FormulaListElement selectedFormula)
Definition at line 60 of file Project.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/core/Project.java