VERDI: anl.verdi.core.VerdiGUI Class Reference
anl.verdi.core.VerdiGUI Class Reference
Public Member Functions
VerdiGUI (DockingManager manager, DataSetPanel datasets, FormulasPanel formulas, AreaFilePanel areaPanel)
void windowActivated (WindowEvent unused)
void windowClosed (WindowEvent unused)
void windowClosing (WindowEvent unused)
void windowDeactivated (WindowEvent unused)
void windowDeiconified (WindowEvent unused)
void windowIconified (WindowEvent unused)
void windowOpened (WindowEvent unused)
void undockAllPlots ()
java.util.List< Plot > getDisplayedPlots (Formula.Type type)
java.util.List< Plot > getDisplayedPlots ()
void setSaveEnabled (boolean enabled)
void addPlot (PlotPanel plotPanel)
void addScriptPane (JPanel scriptPanel)
void addProbe (final JTable table, String name, String rangeAxisName)
void setStatusTwoText (String text)
void setStatusOneText (String text)
JFrame getFrame ()
void setFrame (JFrame frame)
DockingManager getViewManager ()
void setDualElementPlotsEnabled (boolean enabled)
void setVertCrossPlotEnabled (boolean enabled)
void setOtherPlotsEnabled (boolean enabled)
void loadDataset (Dataset dataset)
void loadAreaFile (AreaFile dataset)
void showMessage (String title, String message)
void showBusyCursor ()
void restoreCursor ()
void busyCursor ()
void defaultCursor ()
void setCurrentFormula (String formula)
boolean askMessage (String title, String message)
void dockableClosed (DockableFrameEvent evt)
java.util.List< String > getViewList ()
AreaFilePanel getAreaPanel ()
void dockableClosing (DockableFrameEvent evt)
void dockableFloating (DockableFrameEvent evt)
void dockableRestoring (DockableFrameEvent evt)
void dockableMinimizing (DockableFrameEvent evt)
void dockableMinimized (DockableFrameEvent evt)
void dockableFloated (DockableFrameEvent evt)
void dockableMaximizing (DockableFrameEvent evt)
void dockableMaximized (DockableFrameEvent evt)
void dockableRestored (DockableFrameEvent evt)
Static Public Member Functions
static boolean isIconified ()
static boolean isHidden (Plot plot)
Detailed Description
Facade for gui related application operations.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 60 of file VerdiGUI.java.
Constructor & Destructor Documentation
anl.verdi.core.VerdiGUI.VerdiGUI (DockingManager manager, DataSetPanel datasets, FormulasPanel formulas, AreaFilePanel areaPanel)
Definition at line 83 of file VerdiGUI.java.
Member Function Documentation
void anl.verdi.core.VerdiGUI.addPlot (PlotPanel plotPanel)
Definition at line 165 of file VerdiGUI.java.
References saf.core.ui.dock.DockableFrame.getID(), anl.verdi.plot.gui.PlotPanel.getPlotType(), anl.verdi.core.VerdiConstants.MAIN_GROUP_ID, anl.verdi.core.VerdiConstants.PERSPECTIVE_ID, and anl.verdi.core.VerdiGUI.setStatusTwoText().
void anl.verdi.core.VerdiGUI.addProbe (final JTable table, String name, String rangeAxisName)
Definition at line 341 of file VerdiGUI.java.
References anl.verdi.core.VerdiConstants.MAIN_GROUP_ID, and anl.verdi.core.VerdiConstants.PERSPECTIVE_ID.
void anl.verdi.core.VerdiGUI.addScriptPane (JPanel scriptPanel)
Definition at line 247 of file VerdiGUI.java.
References anl.verdi.core.VerdiConstants.MAIN_GROUP_ID, anl.verdi.core.VerdiConstants.PERSPECTIVE_ID, and anl.verdi.core.VerdiGUI.setStatusTwoText().
boolean anl.verdi.core.VerdiGUI.askMessage (String title, String message)
Displays a confirmation message and returns true if the user clicks yes.
Parameters
title the title of the message
message the message itself
Returns
true if the user clicks yes, otherwise false.
Definition at line 512 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.busyCursor ()
Definition at line 478 of file VerdiGUI.java.
References anl.verdi.core.VerdiGUI.getFrame().
void anl.verdi.core.VerdiGUI.defaultCursor ()
Definition at line 483 of file VerdiGUI.java.
References anl.verdi.core.VerdiGUI.getFrame().
void anl.verdi.core.VerdiGUI.dockableClosed (DockableFrameEvent evt)
Invoked when a view is closed.
Parameters
evt
Implements saf.core.ui.event.DockableFrameListener.
Definition at line 523 of file VerdiGUI.java.
References saf.core.ui.dock.DockableFrame.getID(), and anl.verdi.gui.ScriptPanel.hasChanges().
void anl.verdi.core.VerdiGUI.dockableClosing (DockableFrameEvent evt)
Invoked when a dockable receives a close request. The close can be overriden by setting the events handled property to true.
Parameters
evt details the close request
Implements saf.core.ui.event.DockableFrameListener.
Definition at line 577 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.dockableFloated (DockableFrameEvent evt)
Invoked when a dockable is floated.
Parameters
evt details of the event
Implements saf.core.ui.event.DockableFrameListener.
Definition at line 602 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.dockableFloating (DockableFrameEvent evt)
Invoked when a dockable receives a float request. The float can be overriden by setting the events handled property to true.
Parameters
evt details the float request
Implements saf.core.ui.event.DockableFrameListener.
Definition at line 582 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.dockableMaximized (DockableFrameEvent evt)
Invoked when a dockable is maximized.
Parameters
evt details of the event
Implements saf.core.ui.event.DockableFrameListener.
Definition at line 612 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.dockableMaximizing (DockableFrameEvent evt)
Invoked when a dockable receives a maxmizing request. The maximize can be overriden by setting the events handled property to true.
Parameters
evt details the maximize request
Implements saf.core.ui.event.DockableFrameListener.
Definition at line 607 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.dockableMinimized (DockableFrameEvent evt)
Invoked when a dockable is minimized.
Parameters
evt details of the event
Implements saf.core.ui.event.DockableFrameListener.
Definition at line 597 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.dockableMinimizing (DockableFrameEvent evt)
Invoked when a dockable receives a minimizing request. The minimize can be overriden by setting the events handled property to true.
Parameters
evt details the minimize request
Implements saf.core.ui.event.DockableFrameListener.
Definition at line 592 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.dockableRestored (DockableFrameEvent evt)
Invoked when a dockable is restored to its default docking position from a floated, minimized, or maximized state.
Parameters
evt details of the event
Implements saf.core.ui.event.DockableFrameListener.
Definition at line 617 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.dockableRestoring (DockableFrameEvent evt)
Invoked when a dockable receives a restore request. The restore can be overriden by setting the events handled property to true.
Parameters
evt details the restore request
Implements saf.core.ui.event.DockableFrameListener.
Definition at line 587 of file VerdiGUI.java.
AreaFilePanel anl.verdi.core.VerdiGUI.getAreaPanel ()
Definition at line 572 of file VerdiGUI.java.
java.util.List<Plot> anl.verdi.core.VerdiGUI.getDisplayedPlots (Formula.Type type)
Gets all the displayed plots of the specified type.
Parameters
type the type of plot
Returns
all the displayed plots of the specified type.
Definition at line 131 of file VerdiGUI.java.
References anl.verdi.plot.gui.Plot.getType(), anl.verdi.core.VerdiConstants.MAIN_GROUP_ID, and anl.verdi.core.VerdiConstants.PERSPECTIVE_ID.
java.util.List<Plot> anl.verdi.core.VerdiGUI.getDisplayedPlots ()
Gets all the displayed plots.
Returns
all the displayed plots.
Definition at line 154 of file VerdiGUI.java.
JFrame anl.verdi.core.VerdiGUI.getFrame ()
Definition at line 383 of file VerdiGUI.java.
Referenced by anl.verdi.core.VerdiApplication.animateTilePlots(), anl.verdi.core.VerdiGUI.busyCursor(), anl.verdi.core.VerdiGUI.defaultCursor(), anl.verdi.plot.gui.ScatterPlotCreator.doCreatePlot(), anl.verdi.plot.gui.VerticalCrossPlotCreator.doCreatePlot(), anl.verdi.core.VerdiApplication.init(), anl.verdi.core.VerdiApplication.overlayRequested(), anl.verdi.core.VerdiGUI.restoreCursor(), and anl.verdi.core.VerdiGUI.showBusyCursor().
java.util.List<String> anl.verdi.core.VerdiGUI.getViewList ()
Returns the list of open plot view ids
Returns
ArrayList<String>
Definition at line 568 of file VerdiGUI.java.
DockingManager anl.verdi.core.VerdiGUI.getViewManager ()
Definition at line 401 of file VerdiGUI.java.
static boolean anl.verdi.core.VerdiGUI.isHidden (Plot plot) static
Definition at line 231 of file VerdiGUI.java.
References saf.core.ui.dock.DockableFrame.isHidden().
static boolean anl.verdi.core.VerdiGUI.isIconified () static
Definition at line 225 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.loadAreaFile (AreaFile dataset)
Loads the specified area file into the area file GUI: NOTE: Not yet implemented.
Parameters
dataset the area file to load
Definition at line 441 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.loadDataset (Dataset dataset)
Loads the specified dataset into the dataset GUI.
Parameters
dataset the dataset to load
Definition at line 433 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.restoreCursor ()
Definition at line 467 of file VerdiGUI.java.
References anl.verdi.core.VerdiGUI.getFrame().
void anl.verdi.core.VerdiGUI.setCurrentFormula (String formula)
Sets the current formula label in the toolbar to the specified formula.
Parameters
formula the formula to show in the toolbar
Definition at line 496 of file VerdiGUI.java.
References anl.verdi.core.VerdiConstants.FORMULA_LABEL, and saf.core.ui.dock.DockingManager.getBarManager().
void anl.verdi.core.VerdiGUI.setDualElementPlotsEnabled (boolean enabled)
Definition at line 405 of file VerdiGUI.java.
References anl.verdi.core.VerdiConstants.SCATTER_BUTTON_ID.
void anl.verdi.core.VerdiGUI.setFrame (JFrame frame)
Definition at line 387 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.setOtherPlotsEnabled (boolean enabled)
Definition at line 414 of file VerdiGUI.java.
References anl.verdi.core.VerdiConstants.AREAL_INTERPOLATION_BUTTON_ID, anl.verdi.core.VerdiConstants.CONTOUR_BUTTON_ID, anl.verdi.core.VerdiConstants.FAST_TILE_BUTTON_ID, anl.verdi.core.VerdiConstants.TIME_SERIES_BAR_BUTTON_ID, and anl.verdi.core.VerdiConstants.TIME_SERIES_LINE_BUTTON_ID.
void anl.verdi.core.VerdiGUI.setSaveEnabled (boolean enabled)
Definition at line 158 of file VerdiGUI.java.
References anl.verdi.core.VerdiConstants.SAVE_AS_ID, and anl.verdi.core.VerdiConstants.SAVE_ID.
void anl.verdi.core.VerdiGUI.setStatusOneText (String text)
Definition at line 374 of file VerdiGUI.java.
Referenced by anl.verdi.core.VerdiGUI.showBusyCursor().
void anl.verdi.core.VerdiGUI.setStatusTwoText (String text)
Definition at line 365 of file VerdiGUI.java.
Referenced by anl.verdi.core.VerdiGUI.addPlot(), and anl.verdi.core.VerdiGUI.addScriptPane().
void anl.verdi.core.VerdiGUI.setVertCrossPlotEnabled (boolean enabled)
Definition at line 410 of file VerdiGUI.java.
References anl.verdi.core.VerdiConstants.VERT_CROSS_BUTTON_ID.
void anl.verdi.core.VerdiGUI.showBusyCursor ()
Definition at line 460 of file VerdiGUI.java.
References anl.verdi.core.VerdiGUI.getFrame(), and anl.verdi.core.VerdiGUI.setStatusOneText().
void anl.verdi.core.VerdiGUI.showMessage (String title, String message)
Displays a message to the user.
Parameters
title the title of the message
message the content of the message
Definition at line 454 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.undockAllPlots ()
Definition at line 113 of file VerdiGUI.java.
References saf.core.ui.dock.Perspective.isActive(), anl.verdi.core.VerdiConstants.MAIN_GROUP_ID, and anl.verdi.core.VerdiConstants.PERSPECTIVE_ID.
void anl.verdi.core.VerdiGUI.windowActivated (WindowEvent unused)
Definition at line 90 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.windowClosed (WindowEvent unused)
Definition at line 93 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.windowClosing (WindowEvent unused)
Definition at line 96 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.windowDeactivated (WindowEvent unused)
Definition at line 99 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.windowDeiconified (WindowEvent unused)
Definition at line 102 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.windowIconified (WindowEvent unused)
Definition at line 106 of file VerdiGUI.java.
void anl.verdi.core.VerdiGUI.windowOpened (WindowEvent unused)
Definition at line 110 of file VerdiGUI.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/core/VerdiGUI.java