VERDI: anl.verdi.area.target.TargetSet Class Reference
anl.verdi.area.target.TargetSet Class Reference
Public Member Functions
TargetSet (TargetSet data)
TargetSet (String n)
void setTargets (ArrayList list)
String toString ()
String getName ()
Static Public Member Functions
static ArrayList getTargetSets ()
static TargetSet findTargetSet (String name)
static TargetSet getTargetSetWithin (Target data)
static void setTargetSets (ArrayList list)
static ArrayList copyTargetSets ()
static ArrayList includedTargets (ArrayList inList)
static void unload ()
static int load (Vector data, int offset) throws IOException
Detailed Description
File Name:TargetSet.java Description: A set of related targets
Version
April 2004
Author
Mary Ann Bitz
Argonne National Lab
Definition at line 21 of file TargetSet.java.
Constructor & Destructor Documentation
anl.verdi.area.target.TargetSet.TargetSet (TargetSet data)
Copy constructor for a set of targets
Parameters
data target set to copy
Definition at line 40 of file TargetSet.java.
Referenced by anl.verdi.area.target.TargetSet.copyTargetSets(), anl.verdi.area.target.TargetSet.findTargetSet(), anl.verdi.area.target.TargetSet.getTargetSetWithin(), anl.verdi.area.target.TargetSet.includedTargets(), anl.verdi.area.target.TargetSet.load(), and anl.verdi.area.target.TargetSet.setTargetSets().
anl.verdi.area.target.TargetSet.TargetSet (String n)
Constructor for a set of targets
Parameters
n name of the target set
Definition at line 49 of file TargetSet.java.
Member Function Documentation
static ArrayList anl.verdi.area.target.TargetSet.copyTargetSets () static
Copy all target sets to a new list of them
Returns
the copy list
Definition at line 108 of file TargetSet.java.
References anl.verdi.area.target.TargetSet.TargetSet().
static TargetSet anl.verdi.area.target.TargetSet.findTargetSet (String name) static
Find a target set with the given name
Parameters
name the name of the target set to look for
Returns
the target set that matches
Definition at line 73 of file TargetSet.java.
References anl.verdi.area.target.TargetSet.TargetSet().
Referenced by anl.verdi.area.target.TargetSet.load().
String anl.verdi.area.target.TargetSet.getName ()
Get the name of the target set
Returns
Definition at line 217 of file TargetSet.java.
static ArrayList anl.verdi.area.target.TargetSet.getTargetSets () static
Get the list of all target sets
Returns
all target sets
Definition at line 65 of file TargetSet.java.
static TargetSet anl.verdi.area.target.TargetSet.getTargetSetWithin (Target data) static
Get the first target set containing the target
Parameters
data
Returns
Definition at line 85 of file TargetSet.java.
References anl.verdi.area.target.TargetSet.TargetSet().
static ArrayList anl.verdi.area.target.TargetSet.includedTargets (ArrayList inList) static
Returns a list of all targets in the passed in list
Parameters
inList list of target sets and targets
Returns
list of included targets
Definition at line 120 of file TargetSet.java.
References anl.verdi.area.target.TargetSet.TargetSet().
Referenced by anl.verdi.area.target.Target.load(), and anl.verdi.area.target.Target.syncSelectedTargetSets().
static int anl.verdi.area.target.TargetSet.load (Vector data, int offset) throws IOException static
Load the target sets from a vector
Parameters
data the vector of data
offset the current place in the vector
Returns
the new offset
Exceptions
IOException
Definition at line 143 of file TargetSet.java.
References anl.verdi.area.target.TargetSet.findTargetSet(), and anl.verdi.area.target.TargetSet.TargetSet().
void anl.verdi.area.target.TargetSet.setTargets (ArrayList list)
Sets the list of targets in the target set
Parameters
list the targets
Definition at line 57 of file TargetSet.java.
static void anl.verdi.area.target.TargetSet.setTargetSets (ArrayList list) static
Set the target set list to the passed in one does a deep copy
Parameters
list list of targets to be copied
Definition at line 98 of file TargetSet.java.
References anl.verdi.area.target.TargetSet.TargetSet().
String anl.verdi.area.target.TargetSet.toString ()
Save the target sets to a vector
Parameters
data Gets a string representing the target set
Definition at line 210 of file TargetSet.java.
static void anl.verdi.area.target.TargetSet.unload () static
Unload all target sets
Definition at line 133 of file TargetSet.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/target/TargetSet.java