VERDI: anl.verdi.plot.data.ScatterXYDataset Class Reference
anl.verdi.plot.data.ScatterXYDataset Class Reference
Public Member Functions
void addSeries (DataFrame xFrame, DataFrame yFrame, int timeStep, int layer)
DomainOrder getDomainOrder ()
int getItemCount (int series)
Number getX (int series, int item)
double getXValue (int series, int item)
Number getY (int series, int item)
double getYValue (int series, int item)
int getSeriesCount ()
Comparable getSeriesKey (int series)
void setSeriesKey (int series, String key)
int indexOf (Comparable seriesKey)
Detailed Description
Dataset appropriate for a scatter plot. Each series has two frames. The xValue is the value from one frame and the yValue from another.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 21 of file ScatterXYDataset.java.
Member Function Documentation
void anl.verdi.plot.data.ScatterXYDataset.addSeries (DataFrame xFrame, DataFrame yFrame, int timeStep, int layer)
Definition at line 96 of file ScatterXYDataset.java.
References anl.verdi.plot.data.ScatterXYDataset.indexOf().
DomainOrder anl.verdi.plot.data.ScatterXYDataset.getDomainOrder ()
Returns the order of the domain (or X) values returned by the dataset.
Returns
The order (never null).
Definition at line 113 of file ScatterXYDataset.java.
int anl.verdi.plot.data.ScatterXYDataset.getItemCount (int series)
Returns the number of items in a series.
It is recommended that classes that implement this method should throw an IllegalArgumentException if the series argument is outside the specified range.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
Returns
The item count.
Definition at line 128 of file ScatterXYDataset.java.
int anl.verdi.plot.data.ScatterXYDataset.getSeriesCount ()
Returns the number of series in the dataset.
Returns
The series count.
Definition at line 193 of file ScatterXYDataset.java.
Referenced by anl.verdi.plot.data.ScatterXYDataset.getSeriesKey(), and anl.verdi.plot.data.ScatterXYDataset.setSeriesKey().
Comparable anl.verdi.plot.data.ScatterXYDataset.getSeriesKey (int series)
Returns the key for a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
Returns
The key for the series.
Definition at line 204 of file ScatterXYDataset.java.
References anl.verdi.plot.data.ScatterXYDataset.getSeriesCount().
Number anl.verdi.plot.data.ScatterXYDataset.getX (int series, int item)
Returns the x-value for an item within a series. The x-values may or may not be returned in ascending order, that is up to the class implementing the interface.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The x-value (never null).
Definition at line 143 of file ScatterXYDataset.java.
References anl.verdi.plot.data.ScatterXYDataset.getXValue().
double anl.verdi.plot.data.ScatterXYDataset.getXValue (int series, int item)
Returns the x-value for an item within a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The x-value.
Definition at line 156 of file ScatterXYDataset.java.
Referenced by anl.verdi.plot.data.ScatterXYDataset.getX().
Number anl.verdi.plot.data.ScatterXYDataset.getY (int series, int item)
Returns the y-value for an item within a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The y-value (possibly null).
Definition at line 170 of file ScatterXYDataset.java.
References anl.verdi.plot.data.ScatterXYDataset.getYValue().
double anl.verdi.plot.data.ScatterXYDataset.getYValue (int series, int item)
Returns the y-value (as a double primitive) for an item within a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The y-value.
Definition at line 183 of file ScatterXYDataset.java.
Referenced by anl.verdi.plot.data.ScatterXYDataset.getY().
int anl.verdi.plot.data.ScatterXYDataset.indexOf (Comparable seriesKey)
Returns the index of the series with the specified key, or -1 if there is no such series in the dataset.
Parameters
seriesKey the series key (null permitted).
Returns
The index, or -1.
Definition at line 228 of file ScatterXYDataset.java.
Referenced by anl.verdi.plot.data.ScatterXYDataset.addSeries().
void anl.verdi.plot.data.ScatterXYDataset.setSeriesKey (int series, String key)
Definition at line 212 of file ScatterXYDataset.java.
References anl.verdi.plot.data.ScatterXYDataset.getSeriesCount().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/data/ScatterXYDataset.java