VERDI: org.libtiff.jai.codecimpl.XTIFFLZWTileCodec Class Reference
org.libtiff.jai.codecimpl.XTIFFLZWTileCodec Class Reference
Public Member Functions
XTIFFLZWTileCodec ()
XTIFFTileCodec create ()
void register ()
void initializeDecoding ()
void decodeTilePixels (byte[] input, Rectangle newRect, byte[] bdata)
void decodeTilePixels (byte[] input, Rectangle newRect, short[] sdata)
Public Member Functions inherited from org.libtiff.jai.codec.XTIFFTileCodecImpl
abstract void register ()
abstract XTIFFTileCodec create ()
boolean canEncode ()
void initializeDecoding ()
void initializeEncoding ()
abstract void decodeTilePixels (byte[] bpixels, Rectangle rect, byte[] pixels)
abstract void decodeTilePixels (byte[] bpixels, Rectangle rect, short[] pixels)
int encodeTilePixels (int[] pixels, Rectangle rect, byte[] bpixels)
XTIFFTileCodecImpl ()
void initialize ()
void register (int comp)
int getCompression ()
XTIFFTileCodec create (XTIFFEncodeParam param) throws IOException
int encode (RenderedImage img, Rectangle rect, byte[] bpixels)
int getCompressedTileSize (RenderedImage im)
XTIFFTileCodec create (XTIFFDecodeParam param) throws IOException
WritableRaster decode (RenderedImage img, Rectangle newRect, byte[] bpixels)
Additional Inherited Members
Protected Member Functions inherited from org.libtiff.jai.codec.XTIFFTileCodecImpl
long getLongField (int fld)
void setupSourceImage (RenderedImage img)
void initialize (XTIFFEncodeParam param) throws IOException
void setupBufferForEncoding ()
void getTilePixels (Rectangle rect)
void initialize (XTIFFDecodeParam param) throws IOException
void setupBufferForDecoding ()
void decodeColor (Rectangle newRect)
void decodeTilePixels (byte[] bpixels, Rectangle newRect)
WritableRaster setTilePixels (Rectangle rect)
void unpackShorts (byte byteArray[], short output[], int shortCount)
void decodeColor (byte[] bpix, short[] sdata, Rectangle newRect)
void decodeColor (short[] spix, short[] sdata, Rectangle newRect)
void decodeColor (byte[] bpix, byte[] bdata, Rectangle newRect)
Protected Attributes inherited from org.libtiff.jai.codec.XTIFFTileCodecImpl
XTIFFDirectory directory = null
RenderedImage image = null
int minY
int minX
int width
int length
int numBands
int tileLength
int tileWidth
int compression
SampleModel sampleModel
int[] sampleSize
char[] bitsPerSample
char[] colormap = null
XTIFFEncodeParam encodeParam = null
boolean isTiled
XTIFFDecodeParam decodeParam = null
boolean decodePaletteAsShorts = false
int unitsInThisTile
byte _bdata [] = null
short _sdata [] = null
byte[] bpixvals = null
short[] spixvals = null
DataBuffer buffer = null
int dataType
int image_type
Detailed Description
This codec encapsulates all the logic for the TIFF "lzw" decoding codec algorithm.
Definition at line 17 of file XTIFFLZWTileCodec.java.
Constructor & Destructor Documentation
org.libtiff.jai.codecimpl.XTIFFLZWTileCodec.XTIFFLZWTileCodec ()
Public constructor
Definition at line 28 of file XTIFFLZWTileCodec.java.
Referenced by org.libtiff.jai.codecimpl.XTIFFLZWTileCodec.create().
Member Function Documentation
XTIFFTileCodec org.libtiff.jai.codecimpl.XTIFFLZWTileCodec.create ()
Creation method
Definition at line 33 of file XTIFFLZWTileCodec.java.
References org.libtiff.jai.codecimpl.XTIFFLZWTileCodec.XTIFFLZWTileCodec().
void org.libtiff.jai.codecimpl.XTIFFLZWTileCodec.decodeTilePixels (byte[] input, Rectangle newRect, byte[] bdata)
Decode a rectangle of pixels
Definition at line 77 of file XTIFFLZWTileCodec.java.
void org.libtiff.jai.codecimpl.XTIFFLZWTileCodec.decodeTilePixels (byte[] input, Rectangle newRect, short[] sdata)
Decode a rectangle of pixels
Definition at line 84 of file XTIFFLZWTileCodec.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.unitsInThisTile, and org.libtiff.jai.codec.XTIFFTileCodecImpl.unpackShorts().
void org.libtiff.jai.codecimpl.XTIFFLZWTileCodec.initializeDecoding ()
The initialization method particular to LZW decoding.
Definition at line 49 of file XTIFFLZWTileCodec.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.bitsPerSample, org.libtiff.jai.codec.XTIFFField.getAsLong(), org.libtiff.jai.util.JaiI18N.getString(), org.libtiff.jai.codec.XTIFF.TIFFTAG_PREDICTOR, org.libtiff.jai.codec.XTIFF.TIFFTAG_SAMPLES_PER_PIXEL, and org.libtiff.jai.codec.XTIFFTileCodecImpl.tileWidth.
void org.libtiff.jai.codecimpl.XTIFFLZWTileCodec.register ()
Registration method
Implements org.libtiff.jai.codec.XTIFFTileCodec.
Definition at line 42 of file XTIFFLZWTileCodec.java.
References org.libtiff.jai.codec.XTIFF.COMPRESSION_LZW.
The documentation for this class was generated from the following file:
verdi_core/src/org/libtiff/jai/codecimpl/XTIFFLZWTileCodec.java