VERDI: anl.verdi.plot.data.DFVectorXYDataset Class Reference
anl.verdi.plot.data.DFVectorXYDataset Class Reference
Public Member Functions
void addSeries (DataFrame xVect, DataFrame yVect, int timeStep, int layer)
Number getDeltaX (int series, int item)
double getDeltaXValue (int series, int item)
Number getDeltaY (int series, int item)
double getDeltaYValue (int series, int item)
DomainOrder getDomainOrder ()
int getItemCount (int series)
Number getX (int series, int item)
double getXValue (int series, int item)
Number getY (int series, int item)
double getYValue (int series, int item)
int getSeriesCount ()
Comparable getSeriesKey (int series)
int indexOf (Comparable seriesKey)
double getVectorXValue (int series, int item)
double getVectorYValue (int series, int item)
Vector getVector (int series, int item)
Detailed Description
Adapts data frame data to VectorXYDataset
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 24 of file DFVectorXYDataset.java.
Member Function Documentation
void anl.verdi.plot.data.DFVectorXYDataset.addSeries (DataFrame xVect, DataFrame yVect, int timeStep, int layer)
Definition at line 101 of file DFVectorXYDataset.java.
References anl.verdi.plot.data.DFVectorXYDataset.indexOf().
Number anl.verdi.plot.data.DFVectorXYDataset.getDeltaX (int series, int item)
Returns the x-component of the vector.
Parameters
series the series index.
item the item index.
Returns
The x-component of the vector.
Definition at line 120 of file DFVectorXYDataset.java.
References anl.verdi.plot.data.DFVectorXYDataset.getXValue().
double anl.verdi.plot.data.DFVectorXYDataset.getDeltaXValue (int series, int item)
Returns the x-component of the vector.
Parameters
series the series index.
item the item index.
Returns
The x-component of the vector.
Definition at line 131 of file DFVectorXYDataset.java.
Number anl.verdi.plot.data.DFVectorXYDataset.getDeltaY (int series, int item)
Returns the y-component of the vector.
Parameters
series the series index.
item the item index.
Returns
The y-component of the vector.
Definition at line 150 of file DFVectorXYDataset.java.
References anl.verdi.plot.data.DFVectorXYDataset.getYValue().
double anl.verdi.plot.data.DFVectorXYDataset.getDeltaYValue (int series, int item)
Returns the y-component of the vector.
Parameters
series the series index.
item the item index.
Returns
The y-component of the vector.
Definition at line 161 of file DFVectorXYDataset.java.
DomainOrder anl.verdi.plot.data.DFVectorXYDataset.getDomainOrder ()
Returns the order of the domain (or X) values returned by the dataset.
Returns
The order (never null).
Definition at line 178 of file DFVectorXYDataset.java.
int anl.verdi.plot.data.DFVectorXYDataset.getItemCount (int series)
Returns the number of items in a series.
It is recommended that classes that implement this method should throw an IllegalArgumentException if the series argument is outside the specified range.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
Returns
The item count.
Definition at line 193 of file DFVectorXYDataset.java.
int anl.verdi.plot.data.DFVectorXYDataset.getSeriesCount ()
Returns the number of series in the dataset.
Returns
The series count.
Definition at line 267 of file DFVectorXYDataset.java.
Referenced by anl.verdi.plot.data.DFVectorXYDataset.getSeriesKey().
Comparable anl.verdi.plot.data.DFVectorXYDataset.getSeriesKey (int series)
Returns the key for a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
Returns
The key for the series.
Definition at line 278 of file DFVectorXYDataset.java.
References anl.verdi.plot.data.DFVectorXYDataset.getSeriesCount().
Vector anl.verdi.plot.data.DFVectorXYDataset.getVector (int series, int item)
Definition at line 314 of file DFVectorXYDataset.java.
double anl.verdi.plot.data.DFVectorXYDataset.getVectorXValue (int series, int item)
Definition at line 302 of file DFVectorXYDataset.java.
double anl.verdi.plot.data.DFVectorXYDataset.getVectorYValue (int series, int item)
Definition at line 308 of file DFVectorXYDataset.java.
Number anl.verdi.plot.data.DFVectorXYDataset.getX (int series, int item)
Returns the x-value for an item within a series. The x-values may or may not be returned in ascending order, that is up to the class implementing the interface.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The x-value (never null).
Definition at line 208 of file DFVectorXYDataset.java.
References anl.verdi.plot.data.DFVectorXYDataset.getXValue().
double anl.verdi.plot.data.DFVectorXYDataset.getXValue (int series, int item)
Returns the x-value for an item within a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The x-value.
Definition at line 221 of file DFVectorXYDataset.java.
Referenced by anl.verdi.plot.data.DFVectorXYDataset.getDeltaX(), and anl.verdi.plot.data.DFVectorXYDataset.getX().
Number anl.verdi.plot.data.DFVectorXYDataset.getY (int series, int item)
Returns the y-value for an item within a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The y-value (possibly null).
Definition at line 242 of file DFVectorXYDataset.java.
References anl.verdi.plot.data.DFVectorXYDataset.getYValue().
double anl.verdi.plot.data.DFVectorXYDataset.getYValue (int series, int item)
Returns the y-value (as a double primitive) for an item within a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The y-value.
Definition at line 255 of file DFVectorXYDataset.java.
Referenced by anl.verdi.plot.data.DFVectorXYDataset.getDeltaY(), and anl.verdi.plot.data.DFVectorXYDataset.getY().
int anl.verdi.plot.data.DFVectorXYDataset.indexOf (Comparable seriesKey)
Returns the index of the series with the specified key, or -1 if there is no such series in the dataset.
Parameters
seriesKey the series key (null permitted).
Returns
The index, or -1.
Definition at line 293 of file DFVectorXYDataset.java.
Referenced by anl.verdi.plot.data.DFVectorXYDataset.addSeries().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/data/DFVectorXYDataset.java