VERDI: anl.verdi.area.target.ProjectionInfo Class Reference
anl.verdi.area.target.ProjectionInfo Class Reference
Classes
class EllipseData
class IvjEventHandler
class LambertCCProjectionGUIAdaptor
class MercatorProjectionGUIAdaptor
interface ProjectionGUIAdaptor
class PSProjectionGUIAdaptor
class TransverseMercatorProjectionGUIAdaptor
class XYProjectionGUIAdaptor
Public Member Functions
ProjectionInfo ()
synchronized void addPropertyChangeListener (String propertyName, PropertyChangeListener listener)
void any_KeyReleased (java.awt.event.KeyEvent keyEvent)
void booleanCheckBox_ItemStateChanged (java.awt.event.ItemEvent itemEvent)
void dataComboBox2_ItemStateChanged (java.awt.event.ItemEvent itemEvent)
Double doubleValueOf (String str)
ProjectionGUIAdaptor getAdaptor (int projType)
int getProjectionClass ()
javax.swing.JTextField getStatusTextField ()
void initialize (int proj)
Integer integerValueOf (String str)
boolean isMod ()
synchronized void removePropertyChangeListener (String propertyName, PropertyChangeListener listener)
void setMod (boolean b)
void setProjectionClass (int class1)
void setStatusTextField (javax.swing.JTextField field)
Short shortValueOf (String str)
boolean update ()
CoordinateReferenceSystem getProjection ()
boolean validate (int proj)
boolean isAllowAutoCM ()
boolean isAllowAutoZone ()
void setAllowAutoCM (boolean b)
void setAllowAutoZone (boolean b)
Static Public Member Functions
static void main (java.lang.String[] args)
static List getAllEllipseData ()
static void writePRJFile (String fileName, CoordinateReferenceSystem crs, boolean overwrite)
Static Public Attributes
static final String PARAMETERS_CHANGED_PROPERTY ="ParametersChanged"
Detailed Description
Generic GUI widget that allows user to enter parameters for the selected projection.
Supported projections: Lambert Conformal Conic Mercator Transverse Mercator Polar Stereographic XY (Simple Scaling)
Definition at line 39 of file ProjectionInfo.java.
Constructor & Destructor Documentation
anl.verdi.area.target.ProjectionInfo.ProjectionInfo ()
Constructor for ProjectionInfo
Definition at line 979 of file ProjectionInfo.java.
Referenced by anl.verdi.area.target.ProjectionInfo.main().
Member Function Documentation
synchronized void anl.verdi.area.target.ProjectionInfo.addPropertyChangeListener (String propertyName, PropertyChangeListener listener)
Method addPropertyChangeListener
Parameters
propertyName String
listener PropertyChangeListener
Definition at line 990 of file ProjectionInfo.java.
void anl.verdi.area.target.ProjectionInfo.any_KeyReleased (java.awt.event.KeyEvent keyEvent)
User released a key
Parameters
keyEvent java.awt.event.KeyEvent
Definition at line 1001 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.getAdaptor(), anl.verdi.area.target.ProjectionInfo.PARAMETERS_CHANGED_PROPERTY, and anl.verdi.area.target.ProjectionInfo.update().
void anl.verdi.area.target.ProjectionInfo.booleanCheckBox_ItemStateChanged (java.awt.event.ItemEvent itemEvent)
Boolean checkbox changed
Parameters
itemEvent java.awt.event.ItemEvent
Definition at line 1016 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.PARAMETERS_CHANGED_PROPERTY, anl.verdi.area.target.ProjectionInfo.update(), and anl.verdi.area.target.ProjectionInfo.validate().
void anl.verdi.area.target.ProjectionInfo.dataComboBox2_ItemStateChanged (java.awt.event.ItemEvent itemEvent)
Data 2 changed
Parameters
itemEvent java.awt.event.ItemEvent
Definition at line 1209 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.PARAMETERS_CHANGED_PROPERTY, and anl.verdi.area.target.ProjectionInfo.update().
Double anl.verdi.area.target.ProjectionInfo.doubleValueOf (String str)
MConvert string to a double
Parameters
str String
Returns
Double
Definition at line 1222 of file ProjectionInfo.java.
Referenced by anl.verdi.area.target.ProjectionInfo.LambertCCProjectionGUIAdaptor.createWKT(), anl.verdi.area.target.ProjectionInfo.MercatorProjectionGUIAdaptor.createWKT(), anl.verdi.area.target.ProjectionInfo.PSProjectionGUIAdaptor.createWKT(), anl.verdi.area.target.ProjectionInfo.TransverseMercatorProjectionGUIAdaptor.createWKT(), anl.verdi.area.target.ProjectionInfo.LambertCCProjectionGUIAdaptor.validate(), anl.verdi.area.target.ProjectionInfo.MercatorProjectionGUIAdaptor.validate(), anl.verdi.area.target.ProjectionInfo.PSProjectionGUIAdaptor.validate(), and anl.verdi.area.target.ProjectionInfo.TransverseMercatorProjectionGUIAdaptor.validate().
ProjectionGUIAdaptor anl.verdi.area.target.ProjectionInfo.getAdaptor (int projType)
Get the adaptor for the current projection class
Returns
ProjectionGUIAdaptor Get the adaptor for a class
Parameters
projType
Returns
ProjectionGUIAdaptor
Definition at line 1257 of file ProjectionInfo.java.
Referenced by anl.verdi.area.target.ProjectionInfo.any_KeyReleased(), anl.verdi.area.target.ProjectionInfo.getProjection(), anl.verdi.area.target.ProjectionInfo.initialize(), anl.verdi.area.target.ProjectionInfo.update(), and anl.verdi.area.target.ProjectionInfo.validate().
static List anl.verdi.area.target.ProjectionInfo.getAllEllipseData () static
return all the ellipse data
Returns
all Ellipse data as a List
Definition at line 2219 of file ProjectionInfo.java.
Referenced by anl.verdi.area.target.ProjectionInfo.LambertCCProjectionGUIAdaptor.initialize(), anl.verdi.area.target.ProjectionInfo.MercatorProjectionGUIAdaptor.initialize(), anl.verdi.area.target.ProjectionInfo.PSProjectionGUIAdaptor.initialize(), and anl.verdi.area.target.ProjectionInfo.TransverseMercatorProjectionGUIAdaptor.initialize().
CoordinateReferenceSystem anl.verdi.area.target.ProjectionInfo.getProjection ()
Definition at line 2010 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.getAdaptor().
int anl.verdi.area.target.ProjectionInfo.getProjectionClass ()
Returns
Class
Definition at line 1691 of file ProjectionInfo.java.
javax.swing.JTextField anl.verdi.area.target.ProjectionInfo.getStatusTextField ()
Return status field
Returns
javax.swing.JTextField
Definition at line 1700 of file ProjectionInfo.java.
void anl.verdi.area.target.ProjectionInfo.initialize (int proj)
Initialize
Parameters
proj GeoProjection
Definition at line 1886 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.getAdaptor().
Integer anl.verdi.area.target.ProjectionInfo.integerValueOf (String str)
Convert string to integer
Parameters
str String
Returns
Integer
Definition at line 1898 of file ProjectionInfo.java.
boolean anl.verdi.area.target.ProjectionInfo.isAllowAutoCM ()
Return true if auto central meridian
Returns
boolean
Definition at line 2033 of file ProjectionInfo.java.
boolean anl.verdi.area.target.ProjectionInfo.isAllowAutoZone ()
Return true if auto zone
Returns
boolean
Definition at line 2041 of file ProjectionInfo.java.
boolean anl.verdi.area.target.ProjectionInfo.isMod ()
Return true if modified
Returns
boolean
Definition at line 1911 of file ProjectionInfo.java.
static void anl.verdi.area.target.ProjectionInfo.main (java.lang.String[] args) static
main entrypoint - starts the part when it is run as an application
Parameters
args java.lang.String[]
Definition at line 1920 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.ProjectionInfo().
synchronized void anl.verdi.area.target.ProjectionInfo.removePropertyChangeListener (String propertyName, PropertyChangeListener listener)
Remove a PropertyChangeListener for a specific property.
Parameters
propertyName The name of the property that was listened on.
listener The PropertyChangeListener to be removed
Definition at line 1951 of file ProjectionInfo.java.
void anl.verdi.area.target.ProjectionInfo.setAllowAutoCM (boolean b)
Set allow auto central meridian
Parameters
b
Definition at line 2049 of file ProjectionInfo.java.
void anl.verdi.area.target.ProjectionInfo.setAllowAutoZone (boolean b)
Set allow auto zone
Parameters
b
Definition at line 2057 of file ProjectionInfo.java.
void anl.verdi.area.target.ProjectionInfo.setMod (boolean b)
Set modified
Parameters
b
Definition at line 1962 of file ProjectionInfo.java.
void anl.verdi.area.target.ProjectionInfo.setProjectionClass (int class1)
Set projection class
Parameters
class1
Definition at line 1971 of file ProjectionInfo.java.
void anl.verdi.area.target.ProjectionInfo.setStatusTextField (javax.swing.JTextField field)
Set status field
Parameters
field
Definition at line 1980 of file ProjectionInfo.java.
Short anl.verdi.area.target.ProjectionInfo.shortValueOf (String str)
Convert string to short
Parameters
str String
Returns
Short
Definition at line 1990 of file ProjectionInfo.java.
boolean anl.verdi.area.target.ProjectionInfo.update ()
update state of GUI, return true if valid
Returns
boolean
Definition at line 2003 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.getAdaptor().
Referenced by anl.verdi.area.target.ProjectionInfo.any_KeyReleased(), anl.verdi.area.target.ProjectionInfo.booleanCheckBox_ItemStateChanged(), anl.verdi.area.target.ProjectionInfo.dataComboBox2_ItemStateChanged(), and anl.verdi.area.target.ProjectionPanel.getProjection().
boolean anl.verdi.area.target.ProjectionInfo.validate (int proj)
Return true if projection parameters are valid
Parameters
proj GeoProjection
Returns
boolean
Definition at line 2024 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.getAdaptor().
Referenced by anl.verdi.area.target.ProjectionInfo.booleanCheckBox_ItemStateChanged().
static void anl.verdi.area.target.ProjectionInfo.writePRJFile (String fileName, CoordinateReferenceSystem crs, boolean overwrite) static
Definition at line 2227 of file ProjectionInfo.java.
Member Data Documentation
final String anl.verdi.area.target.ProjectionInfo.PARAMETERS_CHANGED_PROPERTY ="ParametersChanged" static
Field PARAMETERS_CHANGED_PROPERTY
Definition at line 828 of file ProjectionInfo.java.
Referenced by anl.verdi.area.target.ProjectionInfo.any_KeyReleased(), anl.verdi.area.target.ProjectionInfo.booleanCheckBox_ItemStateChanged(), and anl.verdi.area.target.ProjectionInfo.dataComboBox2_ItemStateChanged().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/target/ProjectionInfo.java