VERDI: anl.verdi.loaders.GridNetcdfDataset Class Reference
anl.verdi.loaders.GridNetcdfDataset Class Reference
Public Member Functions
List< String > getVariableNames ()
Variable getVariable (String name)
Axes< CoordAxis > getCoordAxes ()
List< Variable > getVariables ()
void setAlias (String alias)
int getIndexInURL ()
String getName ()
void close () throws IOException
DatasetMetadata getMetadata ()
int getNetcdfCovn ()
void setNetcdfConv (int conv)
Public Member Functions inherited from anl.verdi.data.AbstractDataset
URL getURL ()
String getAlias ()
void setAlias (String alias)
List< String > getVariableNames ()
Variable getVariable (String name)
List< Variable > getVariables ()
Axes< CoordAxis > getCoordAxes ()
boolean hasTimeAxis ()
boolean hasXAxis ()
boolean hasYAxis ()
boolean hasZAxis ()
String getName ()
void close () throws IOException
boolean isObs ()
Protected Member Functions
GridNetcdfDataset (URL url, List< GridDatatype > grids, GridDataset gridDataset)
GridNetcdfDataset (URL url, List< GridDatatype > grids, GridDataset gridDataset, int urlIndex)
Protected Member Functions inherited from anl.verdi.data.AbstractDataset
AbstractDataset (URL url)
Additional Inherited Members
Static Public Attributes inherited from anl.verdi.data.Dataset
static final String NULL_ALIAS = "anl.verdi.data.DataSet.NULL_ALIAS"
static final int SINGLE_DATASET = -1
Protected Attributes inherited from anl.verdi.data.AbstractDataset
String alias = NULL_ALIAS
URL url
Detailed Description
Dataset implementation for those datasets that are read using the netcdf library and represent a collection of GridDatatypes having the same coordindate system.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 45 of file GridNetcdfDataset.java.
Constructor & Destructor Documentation
anl.verdi.loaders.GridNetcdfDataset.GridNetcdfDataset (URL url, List< GridDatatype > grids, GridDataset gridDataset) protected
Creates a GridNetcdfDataset from the specified url, grids and grid dataset
Parameters
url the url of the dataset
grids the grids that make up this dataset
gridDataset the source of the data
Definition at line 80 of file GridNetcdfDataset.java.
References anl.verdi.data.Dataset.SINGLE_DATASET, and anl.verdi.data.AbstractDataset.url.
anl.verdi.loaders.GridNetcdfDataset.GridNetcdfDataset (URL url, List< GridDatatype > grids, GridDataset gridDataset, int urlIndex) protected
Creates a GridNetcdfDataset from the specified url, grids, grid dataset and suffix. The suffix will be appended to the datasets name.
Parameters
url the url of the dataset
grids the grids that make up this dataset
gridDataset the source of the data
urlIndex the cardinality of this Dataset inside the specified URL.
Definition at line 98 of file GridNetcdfDataset.java.
Member Function Documentation
void anl.verdi.loaders.GridNetcdfDataset.close () throws IOException
Closes this dataset. It will have to be recreated to be used again.
Implements anl.verdi.data.Dataset.
Definition at line 278 of file GridNetcdfDataset.java.
Axes<CoordAxis> anl.verdi.loaders.GridNetcdfDataset.getCoordAxes ()
Gets the coordinate Axes for this Dataset.
Returns
the coordinate Axes for this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 205 of file GridNetcdfDataset.java.
int anl.verdi.loaders.GridNetcdfDataset.getIndexInURL ()
Gets the index of this Dataset inside its URL, or Dataset.SINGLE_DATASET if it is the only dataset inside the URL.
Returns
the index of this Dataset inside its URL
Implements anl.verdi.data.Dataset.
Definition at line 241 of file GridNetcdfDataset.java.
DatasetMetadata anl.verdi.loaders.GridNetcdfDataset.getMetadata ()
Get the netcdf dataset meta data
Returns
the DatasetMetadata object
Implements anl.verdi.data.Dataset.
Definition at line 291 of file GridNetcdfDataset.java.
String anl.verdi.loaders.GridNetcdfDataset.getName ()
Gets the name of this Dataset.
Returns
the name of this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 250 of file GridNetcdfDataset.java.
int anl.verdi.loaders.GridNetcdfDataset.getNetcdfCovn ()
Implements anl.verdi.data.Dataset.
Definition at line 296 of file GridNetcdfDataset.java.
Variable anl.verdi.loaders.GridNetcdfDataset.getVariable (String name)
Gets the named variable.
Parameters
name the name of the variable to get
Returns
the named variable
Implements anl.verdi.data.Dataset.
Definition at line 129 of file GridNetcdfDataset.java.
References anl.verdi.loaders.GridNetcdfDataset.getVariables().
List<String> anl.verdi.loaders.GridNetcdfDataset.getVariableNames ()
Gets the list of variable names in this Dataset.
Returns
the list of variable names in this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 112 of file GridNetcdfDataset.java.
References anl.verdi.loaders.GridNetcdfDataset.getVariables().
List<Variable> anl.verdi.loaders.GridNetcdfDataset.getVariables ()
Gets the variables contained by this dataset.
Returns
the variables contained by this dataset.
Implements anl.verdi.data.Dataset.
Definition at line 215 of file GridNetcdfDataset.java.
Referenced by anl.verdi.loaders.GridNetcdfDataset.getVariable(), and anl.verdi.loaders.GridNetcdfDataset.getVariableNames().
void anl.verdi.loaders.GridNetcdfDataset.setAlias (String alias)
Sets the alias for this Dataset.
Parameters
alias the alias for this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 226 of file GridNetcdfDataset.java.
References anl.verdi.data.AbstractDataset.alias, anl.verdi.data.AbstractDataset.getAlias(), and anl.verdi.data.Dataset.SINGLE_DATASET.
void anl.verdi.loaders.GridNetcdfDataset.setNetcdfConv (int conv)
Implements anl.verdi.data.Dataset.
Definition at line 302 of file GridNetcdfDataset.java.
The documentation for this class was generated from the following file:
verdi_data_loaders/src/anl/verdi/loaders/GridNetcdfDataset.java