VERDI: anl.verdi.plot.color.ColorMap Class Reference
anl.verdi.plot.color.ColorMap Class Reference
Classes
enum IntervalType
enum PaletteType
enum PlotType
enum ScaleType
Public Member Functions
ColorMap ()
ColorMap (Palette palette, double min, double max)
ColorMap (Palette palette, List< Double > steps, List< Double > logSteps, ScaleType scaleType)
int getMaxIndex ()
double getStep (int index) throws Exception
double getMax () throws Exception
double getMin () throws Exception
double[] getIntervals () throws Exception
PaletteType getPaletteType ()
void setPaletteType (PaletteType paletteType)
Palette getPalette ()
void setPalette (Palette palette)
Color getColor (int index)
void setColor (int index, Color color)
int getColorCount ()
double getIntervalStart (int index) throws Exception
void setIntervalStart (int index, double start) throws Exception
IntervalType getIntervalType ()
void setIntervalType (IntervalType intervalType)
ScaleType getScaleType ()
void setScaleType (ScaleType scaleType)
double getLogBase ()
void setLogBase (double base)
NumberFormat getNumberFormat () throws Exception
void setNumberFormat (NumberFormat format) throws Exception
void setNumberFormat (DecimalFormat myFormat)
void setPlotType (PlotType plotType)
PlotType getPlotType ()
void setMinMax (double min, double max)
void setMinMax (double min, double max, boolean keepOverridenIntervals)
void setLogMinMax (double min, double max)
void setLogMinMax (double min, double max, boolean keepOverridenIntervals)
Static Public Member Functions
static IntervalType getIntervalType (String type)
static PaletteType getPaletteType (String type)
static ScaleType getScaleType (String type)
Detailed Description
Maps colors to a range of values.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 19 of file ColorMap.java.
Constructor & Destructor Documentation
anl.verdi.plot.color.ColorMap.ColorMap ()
Definition at line 85 of file ColorMap.java.
anl.verdi.plot.color.ColorMap.ColorMap (Palette palette, double min, double max)
Definition at line 89 of file ColorMap.java.
anl.verdi.plot.color.ColorMap.ColorMap (Palette palette, List< Double > steps, List< Double > logSteps, ScaleType scaleType)
Definition at line 120 of file ColorMap.java.
References anl.verdi.plot.color.ColorMap.ScaleType.LOGARITHM.
Member Function Documentation
Color anl.verdi.plot.color.ColorMap.getColor (int index)
Definition at line 264 of file ColorMap.java.
Referenced by anl.verdi.plot.util.LegendPanel.createPaintScale(), and anl.verdi.plot.types.AbstractTilePlot.createPaintScale().
int anl.verdi.plot.color.ColorMap.getColorCount ()
Definition at line 272 of file ColorMap.java.
Referenced by anl.verdi.plot.color.PaletteSelectionPanel.init().
double [] anl.verdi.plot.color.ColorMap.getIntervals () throws Exception
Definition at line 224 of file ColorMap.java.
References anl.verdi.plot.color.ColorMap.PlotType.FAST_TILE, and anl.verdi.plot.color.ColorMap.ScaleType.LOGARITHM.
double anl.verdi.plot.color.ColorMap.getIntervalStart (int index) throws Exception
Definition at line 276 of file ColorMap.java.
References anl.verdi.plot.color.ColorMap.PlotType.FAST_TILE, and anl.verdi.plot.color.ColorMap.ScaleType.LOGARITHM.
static IntervalType anl.verdi.plot.color.ColorMap.getIntervalType (String type) static
Definition at line 43 of file ColorMap.java.
Referenced by anl.verdi.plot.util.LegendPanel.createPaintScale().
IntervalType anl.verdi.plot.color.ColorMap.getIntervalType ()
Definition at line 358 of file ColorMap.java.
double anl.verdi.plot.color.ColorMap.getLogBase ()
Definition at line 374 of file ColorMap.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.configure().
double anl.verdi.plot.color.ColorMap.getMax () throws Exception
Definition at line 195 of file ColorMap.java.
References anl.verdi.plot.color.ColorMap.PlotType.FAST_TILE, and anl.verdi.plot.color.ColorMap.ScaleType.LOGARITHM.
Referenced by anl.verdi.plot.types.AbstractTilePlot.getCurrentMinMax().
int anl.verdi.plot.color.ColorMap.getMaxIndex ()
Definition at line 151 of file ColorMap.java.
References anl.verdi.plot.color.ColorMap.ScaleType.LOGARITHM.
double anl.verdi.plot.color.ColorMap.getMin () throws Exception
Definition at line 210 of file ColorMap.java.
References anl.verdi.plot.color.ColorMap.PlotType.FAST_TILE, and anl.verdi.plot.color.ColorMap.ScaleType.LOGARITHM.
NumberFormat anl.verdi.plot.color.ColorMap.getNumberFormat () throws Exception
Definition at line 383 of file ColorMap.java.
References anl.verdi.plot.color.ColorMap.PlotType.FAST_TILE, and anl.verdi.plot.color.ColorMap.ScaleType.LOGARITHM.
Referenced by anl.verdi.plot.color.PalettePanel.initMap(), and anl.verdi.plot.types.LegendAxis.LegendAxis().
Palette anl.verdi.plot.color.ColorMap.getPalette ()
Definition at line 248 of file ColorMap.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.actionPerformed(), anl.verdi.plot.gui.FastTilePlot.FastTilePlot(), and anl.verdi.plot.color.PalettePanel.initMap().
static PaletteType anl.verdi.plot.color.ColorMap.getPaletteType (String type) static
Definition at line 52 of file ColorMap.java.
PaletteType anl.verdi.plot.color.ColorMap.getPaletteType ()
Definition at line 238 of file ColorMap.java.
PlotType anl.verdi.plot.color.ColorMap.getPlotType ()
Definition at line 453 of file ColorMap.java.
static ScaleType anl.verdi.plot.color.ColorMap.getScaleType (String type) static
Definition at line 61 of file ColorMap.java.
Referenced by anl.verdi.plot.color.ColorMapLoader.characters(), and anl.verdi.plot.color.ColorMapLoader.endElement().
ScaleType anl.verdi.plot.color.ColorMap.getScaleType ()
Definition at line 366 of file ColorMap.java.
double anl.verdi.plot.color.ColorMap.getStep (int index) throws Exception
Definition at line 159 of file ColorMap.java.
References anl.verdi.plot.color.ColorMap.PlotType.FAST_TILE, and anl.verdi.plot.color.ColorMap.ScaleType.LOGARITHM.
void anl.verdi.plot.color.ColorMap.setColor (int index, Color color)
Definition at line 268 of file ColorMap.java.
void anl.verdi.plot.color.ColorMap.setIntervalStart (int index, double start) throws Exception
Definition at line 290 of file ColorMap.java.
References anl.verdi.plot.color.ColorMap.PlotType.FAST_TILE, anl.verdi.plot.color.ColorMap.ScaleType.LOGARITHM, and anl.verdi.plot.color.ColorMap.PaletteType.SEQUENTIAL.
void anl.verdi.plot.color.ColorMap.setIntervalType (IntervalType intervalType)
Definition at line 362 of file ColorMap.java.
void anl.verdi.plot.color.ColorMap.setLogBase (double base)
Definition at line 378 of file ColorMap.java.
void anl.verdi.plot.color.ColorMap.setLogMinMax (double min, double max)
Definition at line 472 of file ColorMap.java.
void anl.verdi.plot.color.ColorMap.setLogMinMax (double min, double max, boolean keepOverridenIntervals)
Definition at line 478 of file ColorMap.java.
void anl.verdi.plot.color.ColorMap.setMinMax (double min, double max)
Definition at line 457 of file ColorMap.java.
void anl.verdi.plot.color.ColorMap.setMinMax (double min, double max, boolean keepOverridenIntervals)
Definition at line 463 of file ColorMap.java.
void anl.verdi.plot.color.ColorMap.setNumberFormat (NumberFormat format) throws Exception
Definition at line 422 of file ColorMap.java.
void anl.verdi.plot.color.ColorMap.setNumberFormat (DecimalFormat myFormat)
setNumberFormat set the DecimalFormat in the colorMap to what the user entered
Parameters
aNumberFormat
Definition at line 436 of file ColorMap.java.
void anl.verdi.plot.color.ColorMap.setPalette (Palette palette)
Definition at line 253 of file ColorMap.java.
void anl.verdi.plot.color.ColorMap.setPaletteType (PaletteType paletteType)
Definition at line 243 of file ColorMap.java.
void anl.verdi.plot.color.ColorMap.setPlotType (PlotType plotType)
Definition at line 449 of file ColorMap.java.
void anl.verdi.plot.color.ColorMap.setScaleType (ScaleType scaleType)
Definition at line 370 of file ColorMap.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/color/ColorMap.java