VERDI: anl.verdi.gui.FormulasPanel Class Reference
anl.verdi.gui.FormulasPanel Class Reference
Public Member Functions
FormulasPanel ()
FormulasPanel (FormulaListModel model)
void setLayerValues (FormulaListElement element)
FormulaEditor getFormulaEditor ()
void addFormulaSelectionListener (ListSelectionListener listener)
void setFormulaCreator (FormulaElementCreator validator)
void setDomainValues (AbstractListElement element)
Detailed Description
Author
User #1
Definition at line 32 of file FormulasPanel.java.
Constructor & Destructor Documentation
anl.verdi.gui.FormulasPanel.FormulasPanel ()
Definition at line 40 of file FormulasPanel.java.
anl.verdi.gui.FormulasPanel.FormulasPanel (FormulaListModel model)
Definition at line 44 of file FormulasPanel.java.
References anl.verdi.gui.FormulasPanel.addFormulaSelectionListener(), anl.verdi.gui.FormulasPanel.setDomainValues(), and anl.verdi.gui.FormulasPanel.setLayerValues().
Member Function Documentation
void anl.verdi.gui.FormulasPanel.addFormulaSelectionListener (ListSelectionListener listener)
Definition at line 161 of file FormulasPanel.java.
Referenced by anl.verdi.gui.FormulasPanel.FormulasPanel().
FormulaEditor anl.verdi.gui.FormulasPanel.getFormulaEditor ()
Definition at line 156 of file FormulasPanel.java.
void anl.verdi.gui.FormulasPanel.setDomainValues (AbstractListElement element)
Definition at line 171 of file FormulasPanel.java.
References anl.verdi.gui.AbstractListElement.getAxes().
Referenced by anl.verdi.gui.FormulasPanel.FormulasPanel().
void anl.verdi.gui.FormulasPanel.setFormulaCreator (FormulaElementCreator validator)
Definition at line 166 of file FormulasPanel.java.
void anl.verdi.gui.FormulasPanel.setLayerValues (FormulaListElement element)
Definition at line 145 of file FormulasPanel.java.
References anl.verdi.gui.AbstractListElement.getLayerMin(), anl.verdi.gui.AbstractListElement.isLayerUsed(), and anl.verdi.gui.AbstractListElement.NO_LAYER_VALUE.
Referenced by anl.verdi.gui.FormulasPanel.FormulasPanel().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/gui/FormulasPanel.java