VERDI: anl.verdi.data.Range Class Reference
anl.verdi.data.Range Class Reference
Public Member Functions
Range (long origin, long extent)
Range (Range range)
long getLowerBound ()
long getUpperBound ()
long getExtent ()
void setExtent (long extent)
long getOrigin ()
void setOrigin (long origin)
String toString ()
int hashCode ()
boolean equals (Object other)
Protected Attributes
long origin
long extent
Detailed Description
class that stores a range of values along a coordinate axis
Author
Mary Ann Bitz
Version
$Revision$ $Date$
See Also
Range
Definition at line 10 of file Range.java.
Constructor & Destructor Documentation
anl.verdi.data.Range.Range (long origin, long extent)
Constructs a range for a given set of values
Parameters
Definition at line 25 of file Range.java.
References anl.verdi.data.Range.extent, and anl.verdi.data.Range.origin.
Referenced by anl.verdi.data.Range.equals().
anl.verdi.data.Range.Range (Range range)
Copy constructor.
Parameters
range
Definition at line 35 of file Range.java.
Member Function Documentation
boolean anl.verdi.data.Range.equals (Object other)
Definition at line 105 of file Range.java.
References anl.verdi.data.Range.Range().
long anl.verdi.data.Range.getExtent ()
Get the extent of the cells in the set of values
Returns
the extent of the cells
Definition at line 63 of file Range.java.
References anl.verdi.data.Range.extent.
Referenced by anl.verdi.data.Axes< T extends CoordAxis >.getEndDate(), and anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getEndDate().
long anl.verdi.data.Range.getLowerBound ()
Gets the lower bound of this range.
Returns
the lower bound of this range.
Definition at line 45 of file Range.java.
References anl.verdi.data.Range.origin.
long anl.verdi.data.Range.getOrigin ()
Get the origin or initial location of the cells in the set of values
Returns
the origin of the cells
Definition at line 81 of file Range.java.
References anl.verdi.data.Range.origin.
Referenced by anl.verdi.data.Axes< T extends CoordAxis >.getEndDate(), anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getEndDate(), anl.verdi.loaders.ExtendSyntheticTimeAxis.getTimeStep(), and anl.verdi.loaders.SyntheticTimeAxis.getTimeStep().
long anl.verdi.data.Range.getUpperBound ()
Gets upper bound of this range.
Returns
upper bound of this range.
Definition at line 54 of file Range.java.
References anl.verdi.data.Range.extent, and anl.verdi.data.Range.origin.
Referenced by anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getBoundingBox(), and anl.verdi.data.Axes< T extends CoordAxis >.getBoundingBox().
int anl.verdi.data.Range.hashCode ()
Definition at line 98 of file Range.java.
References anl.verdi.data.Range.extent, and anl.verdi.data.Range.origin.
void anl.verdi.data.Range.setExtent (long extent)
Set the extent of the cells in the set of values
Parameters
extent of the cells desired
Definition at line 72 of file Range.java.
References anl.verdi.data.Range.extent.
void anl.verdi.data.Range.setOrigin (long origin)
Set the origin or initial location of the cells in the set of values
Parameters
origin of the cells desired
Definition at line 90 of file Range.java.
References anl.verdi.data.Range.origin.
String anl.verdi.data.Range.toString ()
Definition at line 94 of file Range.java.
References anl.verdi.data.Range.extent, and anl.verdi.data.Range.origin.
Member Data Documentation
long anl.verdi.data.Range.extent protected
the extent or number of cells in the set of values
Definition at line 18 of file Range.java.
Referenced by anl.verdi.data.Range.getExtent(), anl.verdi.data.Range.getUpperBound(), anl.verdi.data.Range.hashCode(), anl.verdi.data.Range.Range(), anl.verdi.data.Range.setExtent(), and anl.verdi.data.Range.toString().
long anl.verdi.data.Range.origin protected
the initial cell in the set of values
Definition at line 14 of file Range.java.
Referenced by anl.verdi.data.Range.getLowerBound(), anl.verdi.data.Range.getOrigin(), anl.verdi.data.Range.getUpperBound(), anl.verdi.data.Range.hashCode(), anl.verdi.data.Range.Range(), anl.verdi.data.Range.setOrigin(), and anl.verdi.data.Range.toString().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/data/Range.java