VERDI: anl.verdi.plot.gui.TimeController Class Reference
anl.verdi.plot.gui.TimeController Class Reference
Public Member Functions
TimeController ()
TimeController (AbstractTilePlot plot)
void setPlot (AbstractTilePlot plot)
void addSpinerDetails ()
JFormattedTextField getTextField (JSpinner spinner)
void stateChanged (ChangeEvent e)
void actionPerformed (ActionEvent e)
Static Protected Member Functions
static JSpinner addLabeledSpinner (Container c, String label, SpinnerModel model)
Detailed Description
Class for controlling time inputs to animate plots
Author
Mark Altaweel
Definition at line 34 of file TimeController.java.
Constructor & Destructor Documentation
anl.verdi.plot.gui.TimeController.TimeController ()
Default constructor
Definition at line 53 of file TimeController.java.
References anl.verdi.plot.gui.TimeController.addSpinerDetails().
anl.verdi.plot.gui.TimeController.TimeController (AbstractTilePlot plot)
Constructor that takes a specific tile plot object
Parameters
plot a tile plot object
Definition at line 63 of file TimeController.java.
References anl.verdi.plot.gui.TimeController.addSpinerDetails().
Member Function Documentation
void anl.verdi.plot.gui.TimeController.actionPerformed (ActionEvent e)
Action to update the time of the plot
Definition at line 212 of file TimeController.java.
static JSpinner anl.verdi.plot.gui.TimeController.addLabeledSpinner (Container c, String label, SpinnerModel model) static protected
Method to add spinner model
Parameters
c the container swing object
label the label of the spinner to add
model the spinner model to add
Returns
a JSpinner object with added spinner
Definition at line 147 of file TimeController.java.
Referenced by anl.verdi.plot.gui.TimeController.addSpinerDetails().
void anl.verdi.plot.gui.TimeController.addSpinerDetails ()
Method to setup details of spinner
Definition at line 78 of file TimeController.java.
References anl.verdi.plot.gui.TimeController.addLabeledSpinner(), and anl.verdi.plot.gui.TimeController.getTextField().
Referenced by anl.verdi.plot.gui.TimeController.TimeController().
JFormattedTextField anl.verdi.plot.gui.TimeController.getTextField (JSpinner spinner)
Return the formatted text field used by the editor, or null if the editor doesn't descend from JSpinner.DefaultEditor.
Definition at line 127 of file TimeController.java.
Referenced by anl.verdi.plot.gui.TimeController.addSpinerDetails().
void anl.verdi.plot.gui.TimeController.setPlot (AbstractTilePlot plot)
Definition at line 70 of file TimeController.java.
void anl.verdi.plot.gui.TimeController.stateChanged (ChangeEvent e)
Respond to state change with updating the time step layer
Definition at line 180 of file TimeController.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/gui/TimeController.java