VERDI: anl.verdi.loaders.SyntheticTimeAxis Class Reference
anl.verdi.loaders.SyntheticTimeAxis Class Reference
Public Member Functions
SyntheticTimeAxis (CoordinateAxis axis)
GregorianCalendar getDate (int timestep)
int getTimeStep (Date date)
int getTimeStep (GregorianCalendar aCalendar)
AxisType getAxisType ()
String getDescription ()
String getName ()
Range getRange ()
Unit getUnits ()
double getValue (int index)
boolean isCompatible (CoordAxis axis)
CoordinateReferenceSystem getCRS ()
Static Public Attributes
static final int TIME_STEP_NOT_FOUND = -1
Detailed Description
Creates a Time axis from an ordinate CoordAxis, assuming the units of that axis are "seconds since" some date.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 29 of file SyntheticTimeAxis.java.
Constructor & Destructor Documentation
anl.verdi.loaders.SyntheticTimeAxis.SyntheticTimeAxis (CoordinateAxis axis)
Definition at line 40 of file SyntheticTimeAxis.java.
References anl.verdi.data.AxisType.TIME.
Member Function Documentation
AxisType anl.verdi.loaders.SyntheticTimeAxis.getAxisType ()
Gets the type of this axis.
Returns
the type of this axis.
Implements anl.verdi.data.CoordAxis.
Definition at line 137 of file SyntheticTimeAxis.java.
CoordinateReferenceSystem anl.verdi.loaders.SyntheticTimeAxis.getCRS ()
Does not apply to a time axis.
Definition at line 204 of file SyntheticTimeAxis.java.
GregorianCalendar anl.verdi.loaders.SyntheticTimeAxis.getDate (int timestep)
Returns the GregorianCalendar date for the specified timestep. If the we are unable to parse the time step axis sufficient to create a date then this returns null.
Parameters
timestep the time step we want the date for.
Returns
the GregorianCalendar date for the specified timestep, or null if there is no time axis, or null if unable to parse the time axis units.
Implements anl.verdi.data.TimeCoordAxis.
Definition at line 77 of file SyntheticTimeAxis.java.
References anl.verdi.loaders.NetCdfCoordAxis.getValue().
Referenced by anl.verdi.loaders.SyntheticTimeAxis.getTimeStep().
String anl.verdi.loaders.SyntheticTimeAxis.getDescription ()
Gets the description of this CoordAxis.
Returns
the description of this CoordAxis.
Implements anl.verdi.data.CoordAxis.
Definition at line 146 of file SyntheticTimeAxis.java.
String anl.verdi.loaders.SyntheticTimeAxis.getName ()
Gets the name of this CoordAxis.
Returns
the name of this CoordAxis.
Implements anl.verdi.data.CoordAxis.
Definition at line 155 of file SyntheticTimeAxis.java.
Range anl.verdi.loaders.SyntheticTimeAxis.getRange ()
Gets the range of this axis.
Returns
the range of this axis.
Implements anl.verdi.data.CoordAxis.
Definition at line 164 of file SyntheticTimeAxis.java.
int anl.verdi.loaders.SyntheticTimeAxis.getTimeStep (Date date)
Gets the timestep that corresponds to the specified date. If no such timestep is found then return TIME_STEP_NOT_FOUND.
Parameters
date the date whose time step we want
Returns
the timestep that corresponds to the specified date. If no such timestep is found then return TIME_STEP_NOT_FOUND.
Implements anl.verdi.data.TimeCoordAxis.
Definition at line 94 of file SyntheticTimeAxis.java.
References anl.verdi.loaders.SyntheticTimeAxis.getDate(), anl.verdi.data.Range.getOrigin(), and anl.verdi.loaders.SyntheticTimeAxis.TIME_STEP_NOT_FOUND.
int anl.verdi.loaders.SyntheticTimeAxis.getTimeStep (GregorianCalendar aCalendar)
Gets the timestep that corresponds to the specified GregorianCalendar date. If no such timestep is found then return TIME_STEP_NOT_FOUND.
Parameters
date the GregorianCalendar (date) whose time step we want
Returns
the timestep that corresponds to the specified date. If no such timestep is found then return TIME_STEP_NOT_FOUND.
Implements anl.verdi.data.TimeCoordAxis.
Definition at line 117 of file SyntheticTimeAxis.java.
References anl.verdi.loaders.SyntheticTimeAxis.getDate(), anl.verdi.data.Range.getOrigin(), and anl.verdi.loaders.SyntheticTimeAxis.TIME_STEP_NOT_FOUND.
Unit anl.verdi.loaders.SyntheticTimeAxis.getUnits ()
Gets the unit of measurement for this coordinate axis.
Returns
the unit of measurement for this coordinate axis.
Implements anl.verdi.data.CoordAxis.
Definition at line 173 of file SyntheticTimeAxis.java.
double anl.verdi.loaders.SyntheticTimeAxis.getValue (int index)
Gets the value at the specified index.
Parameters
index the index
Returns
the value at the specified index.
Implements anl.verdi.data.CoordAxis.
Definition at line 184 of file SyntheticTimeAxis.java.
boolean anl.verdi.loaders.SyntheticTimeAxis.isCompatible (CoordAxis axis)
Gets whether or not the this axis is compatible with the specified axis. Two axes are compatible if they can be used together in the same formula.
Parameters
axis the axis to check for compatibility
Returns
true if this axis is compatibility with the other axis, Otherwise false.
Implements anl.verdi.data.CoordAxis.
Definition at line 197 of file SyntheticTimeAxis.java.
Member Data Documentation
final int anl.verdi.loaders.SyntheticTimeAxis.TIME_STEP_NOT_FOUND = -1 static
Definition at line 33 of file SyntheticTimeAxis.java.
Referenced by anl.verdi.loaders.SyntheticTimeAxis.getTimeStep().
The documentation for this class was generated from the following file:
verdi_data_loaders/src/anl/verdi/loaders/SyntheticTimeAxis.java