VERDI: gov.epa.emvl.Mapper Class Reference
gov.epa.emvl.Mapper Class Reference
Public Member Functions
Mapper (String directoryName)
void draw (final double[][] domain, final double[][] gridBounds, final CoordinateReferenceSystem gridCRS, final Graphics graphics, int xOffset, int yOffset, int width, int height, boolean withHucs, boolean withRivers, boolean withRoads)
VerdiBoundaries getUSHucMap ()
void removeUSHucMap ()
VerdiBoundaries getUSRoadsMap ()
void removeUSRoadsMap ()
VerdiBoundaries getUSRiversMap ()
void removeUSRiversMap ()
VerdiBoundaries getUsaStatesMap () throws Exception
void removeUsaStates () throws Exception
VerdiBoundaries getUsaCountiesMap () throws Exception
void removeUsaCounties () throws Exception
VerdiBoundaries getWorldMap () throws Exception
void removeWorld () throws Exception
VerdiBoundaries getNorthAmericaMap () throws Exception
void removeNorthAmerica () throws Exception
void addLayer (String path) throws Exception
void removeLayer (String path) throws Exception
List< VerdiBoundaries > getLayers ()
void resetLayers ()
boolean naMapIncluded ()
boolean usStatesMapIncluded ()
boolean usCountiesMapIncluded ()
boolean worldMapIncluded ()
boolean usHucsMapIncluded ()
boolean usRiversMapIncluded ()
boolean usRoadsMapIncluded ()
Detailed Description
Definition at line 25 of file Mapper.java.
Constructor & Destructor Documentation
gov.epa.emvl.Mapper.Mapper (String directoryName)
Definition at line 55 of file Mapper.java.
References gov.epa.emvl.Mapper.getNorthAmericaMap(), gov.epa.emvl.Mapper.getUsaCountiesMap(), gov.epa.emvl.Mapper.getUsaStatesMap(), gov.epa.emvl.Mapper.getUSHucMap(), gov.epa.emvl.Mapper.getUSRiversMap(), gov.epa.emvl.Mapper.getUSRoadsMap(), and gov.epa.emvl.Mapper.getWorldMap().
Member Function Documentation
void gov.epa.emvl.Mapper.addLayer (String path) throws Exception
Definition at line 407 of file Mapper.java.
void gov.epa.emvl.Mapper.draw (final double domain[][], final double gridBounds[][], final CoordinateReferenceSystem gridCRS, final Graphics graphics, int xOffset, int yOffset, int width, int height, boolean withHucs, boolean withRivers, boolean withRoads)
Definition at line 77 of file Mapper.java.
List<VerdiBoundaries> gov.epa.emvl.Mapper.getLayers ()
Definition at line 432 of file Mapper.java.
VerdiBoundaries gov.epa.emvl.Mapper.getNorthAmericaMap () throws Exception
Definition at line 381 of file Mapper.java.
Referenced by gov.epa.emvl.Mapper.Mapper().
VerdiBoundaries gov.epa.emvl.Mapper.getUsaCountiesMap () throws Exception
Definition at line 328 of file Mapper.java.
Referenced by gov.epa.emvl.Mapper.Mapper().
VerdiBoundaries gov.epa.emvl.Mapper.getUsaStatesMap () throws Exception
Definition at line 301 of file Mapper.java.
Referenced by gov.epa.emvl.Mapper.Mapper().
VerdiBoundaries gov.epa.emvl.Mapper.getUSHucMap ()
Definition at line 247 of file Mapper.java.
Referenced by gov.epa.emvl.Mapper.Mapper().
VerdiBoundaries gov.epa.emvl.Mapper.getUSRiversMap ()
Definition at line 283 of file Mapper.java.
Referenced by gov.epa.emvl.Mapper.Mapper().
VerdiBoundaries gov.epa.emvl.Mapper.getUSRoadsMap ()
Definition at line 265 of file Mapper.java.
Referenced by gov.epa.emvl.Mapper.Mapper().
VerdiBoundaries gov.epa.emvl.Mapper.getWorldMap () throws Exception
Definition at line 355 of file Mapper.java.
Referenced by gov.epa.emvl.Mapper.Mapper().
boolean gov.epa.emvl.Mapper.naMapIncluded ()
Definition at line 441 of file Mapper.java.
void gov.epa.emvl.Mapper.removeLayer (String path) throws Exception
Definition at line 420 of file Mapper.java.
void gov.epa.emvl.Mapper.removeNorthAmerica () throws Exception
Definition at line 396 of file Mapper.java.
void gov.epa.emvl.Mapper.removeUsaCounties () throws Exception
Definition at line 344 of file Mapper.java.
void gov.epa.emvl.Mapper.removeUsaStates () throws Exception
Definition at line 317 of file Mapper.java.
void gov.epa.emvl.Mapper.removeUSHucMap ()
Definition at line 259 of file Mapper.java.
void gov.epa.emvl.Mapper.removeUSRiversMap ()
Definition at line 295 of file Mapper.java.
void gov.epa.emvl.Mapper.removeUSRoadsMap ()
Definition at line 277 of file Mapper.java.
void gov.epa.emvl.Mapper.removeWorld () throws Exception
Definition at line 370 of file Mapper.java.
void gov.epa.emvl.Mapper.resetLayers ()
Definition at line 436 of file Mapper.java.
boolean gov.epa.emvl.Mapper.usCountiesMapIncluded ()
Definition at line 449 of file Mapper.java.
boolean gov.epa.emvl.Mapper.usHucsMapIncluded ()
Definition at line 457 of file Mapper.java.
boolean gov.epa.emvl.Mapper.usRiversMapIncluded ()
Definition at line 461 of file Mapper.java.
boolean gov.epa.emvl.Mapper.usRoadsMapIncluded ()
Definition at line 465 of file Mapper.java.
boolean gov.epa.emvl.Mapper.usStatesMapIncluded ()
Definition at line 445 of file Mapper.java.
boolean gov.epa.emvl.Mapper.worldMapIncluded ()
Definition at line 453 of file Mapper.java.
The documentation for this class was generated from the following file:
verdi_core/src/gov/epa/emvl/Mapper.java