VERDI: anl.verdi.data.DataFrameIndex Class Reference
anl.verdi.data.DataFrameIndex Class Reference
Public Member Functions
DataFrameIndex (DataFrame frame)
void setTime (int timeStep)
void setLayer (int layer)
void setXY (int x, int y)
void set (int timeStep, int layer, int x, int y)
Detailed Description
Encapsulates an index into a DataFrame data array.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 11 of file DataFrameIndex.java.
Constructor & Destructor Documentation
anl.verdi.data.DataFrameIndex.DataFrameIndex (DataFrame frame)
Creates a DataFrameIndex for the specified DataFrame.
Parameters
frame the DataFrame that this is an index for
Definition at line 22 of file DataFrameIndex.java.
Member Function Documentation
void anl.verdi.data.DataFrameIndex.set (int timeStep, int layer, int x, int y)
Sets all the indices for all the coordinate axes.
Parameters
timeStep the time set p index
layer the layer index
x the x index
y the y index
Definition at line 136 of file DataFrameIndex.java.
References anl.verdi.data.DataFrameIndex.setLayer(), anl.verdi.data.DataFrameIndex.setTime(), and anl.verdi.data.DataFrameIndex.setXY().
void anl.verdi.data.DataFrameIndex.setLayer (int layer)
Sets the layer index value.
Parameters
layer the layer index value
Definition at line 81 of file DataFrameIndex.java.
Referenced by anl.verdi.data.DataFrameIndex.set().
void anl.verdi.data.DataFrameIndex.setTime (int timeStep)
Sets the time step index value.
Parameters
timeStep the time step.
Definition at line 63 of file DataFrameIndex.java.
Referenced by anl.verdi.data.DataFrameIndex.set().
void anl.verdi.data.DataFrameIndex.setXY (int x, int y)
Sets the x and y index value
Parameters
x the x value
y the y value
Definition at line 100 of file DataFrameIndex.java.
Referenced by anl.verdi.data.DataFrameIndex.set().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/data/DataFrameIndex.java