VERDI: anl.verdi.data.Slice Class Reference
anl.verdi.data.Slice Class Reference
Public Member Functions
void setTimeRange (int origin, int extent)
void setTimeRange (long origin, long extent)
void setTimeRange (Range range)
void setLayerRange (int origin, int extent)
void setLayerRange (Range range)
void setXRange (int origin, int extent)
void setXRange (Range range)
void setYRange (Range range)
void setYRange (int origin, int extent)
Range getLayerRange ()
Range getTimeRange ()
Range getXRange ()
Range getYRange ()
Detailed Description
Describes a slice along 4 dimensions. Not all the ranges need to be set.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 10 of file Slice.java.
Member Function Documentation
Range anl.verdi.data.Slice.getLayerRange ()
Gets the range of slice along the layer dimension.
Returns
the range of slice along the layer dimension. May be null.
Definition at line 106 of file Slice.java.
Referenced by anl.verdi.plot.probe.VerticalCrossProbeCreator.VerticalCrossProbeCreator().
Range anl.verdi.data.Slice.getTimeRange ()
Gets the range of slice along the time dimension.
Returns
the range of slice along the time dimension. May be null.
Definition at line 115 of file Slice.java.
Referenced by anl.verdi.data.DataFrameTableModel.DataFrameTableModel(), and anl.verdi.plot.probe.TimeSeriesProbeCreator.TimeSeriesProbeCreator().
Range anl.verdi.data.Slice.getXRange ()
Gets the range of slice along the x dimension.
Returns
the range of slice along the x dimension. May be null.
Definition at line 124 of file Slice.java.
Referenced by anl.verdi.data.DataFrameTableModel.DataFrameTableModel(), anl.verdi.plot.probe.TileProbeCreator.TileProbeCreator(), anl.verdi.plot.gui.TimeSeriesPlotRequest.TimeSeriesPlotRequest(), and anl.verdi.plot.probe.VerticalCrossProbeCreator.VerticalCrossProbeCreator().
Range anl.verdi.data.Slice.getYRange ()
Gets the range of slice along the y dimension.
Returns
the range of slice along the y dimension. May be null.
Definition at line 133 of file Slice.java.
Referenced by anl.verdi.plot.probe.TileProbeCreator.TileProbeCreator(), anl.verdi.plot.gui.TimeSeriesPlotRequest.TimeSeriesPlotRequest(), and anl.verdi.plot.probe.VerticalCrossProbeCreator.VerticalCrossProbeCreator().
void anl.verdi.data.Slice.setLayerRange (int origin, int extent)
Sets the layer range of this Slice.
Parameters
origin the origin of the layer range
extent the extent of the layer range
Definition at line 49 of file Slice.java.
void anl.verdi.data.Slice.setLayerRange (Range range)
Sets the layer range of this Slice.
Parameters
range the layer range
Definition at line 58 of file Slice.java.
void anl.verdi.data.Slice.setTimeRange (int origin, int extent)
Sets the time range of this Slice.
Parameters
origin the origin of the time range
extent the extent of the time range
Definition at line 20 of file Slice.java.
void anl.verdi.data.Slice.setTimeRange (long origin, long extent)
Sets the time range of this Slice. // 2014 added setTimeRange from long data types, part of change from Date to GregorianCalendar
Parameters
origin the origin of the time range
extent the extent of the time range
Definition at line 30 of file Slice.java.
void anl.verdi.data.Slice.setTimeRange (Range range)
Sets the time range of this Slice.
Parameters
range the time range
Definition at line 39 of file Slice.java.
void anl.verdi.data.Slice.setXRange (int origin, int extent)
Sets the x range of this Slice.
Parameters
origin the origin of the x range
extent the extent of the x range
Definition at line 68 of file Slice.java.
void anl.verdi.data.Slice.setXRange (Range range)
Sets the x range of this Slice.
Parameters
range the x range
Definition at line 77 of file Slice.java.
void anl.verdi.data.Slice.setYRange (Range range)
Sets the y range of this Slice.
Parameters
range the y range
Definition at line 86 of file Slice.java.
void anl.verdi.data.Slice.setYRange (int origin, int extent)
Sets the y range of this Slice.
Parameters
origin the origin of the y range
extent the extent of the y range
Definition at line 96 of file Slice.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/data/Slice.java