VERDI: anl.verdi.plot.jfree.ChartPanel Class Reference
anl.verdi.plot.jfree.ChartPanel Class Reference
Public Member Functions
ChartPanel (JFreeChart chart)
ChartPanel (JFreeChart chart, boolean useBuffer)
ChartPanel (JFreeChart chart, boolean properties, boolean save, boolean print, boolean zoom, boolean tooltips)
ChartPanel (JFreeChart chart, int width, int height, int minimumDrawWidth, int minimumDrawHeight, int maximumDrawWidth, int maximumDrawHeight, boolean useBuffer, boolean properties, boolean save, boolean print, boolean zoom, boolean tooltips)
JFreeChart getChart ()
void setChart (JFreeChart chart)
int getMinimumDrawWidth ()
void setMinimumDrawWidth (int width)
int getMaximumDrawWidth ()
void setMaximumDrawWidth (int width)
int getMinimumDrawHeight ()
void setMinimumDrawHeight (int height)
int getMaximumDrawHeight ()
void setMaximumDrawHeight (int height)
double getScaleX ()
double getScaleY ()
Point2D getAnchor ()
JPopupMenu getPopupMenu ()
void setPopupMenu (JPopupMenu popup)
ChartRenderingInfo getChartRenderingInfo ()
void setMouseZoomable (boolean flag)
void setMouseZoomable (boolean flag, boolean fillRectangle)
boolean isDomainZoomable ()
void setDomainZoomable (boolean flag)
boolean isRangeZoomable ()
void setRangeZoomable (boolean flag)
boolean getFillZoomRectangle ()
void setFillZoomRectangle (boolean flag)
int getZoomTriggerDistance ()
void setZoomTriggerDistance (int distance)
boolean getHorizontalAxisTrace ()
void setHorizontalAxisTrace (boolean flag)
boolean getVerticalAxisTrace ()
void setVerticalAxisTrace (boolean flag)
boolean isEnforceFileExtensions ()
void setEnforceFileExtensions (boolean enforce)
void setDisplayToolTips (boolean flag)
String getToolTipText (MouseEvent e)
Point translateJava2DToScreen (Point2D java2DPoint)
Point2D translateScreenToJava2D (Point screenPoint)
Rectangle2D scale (Rectangle2D rect)
ChartEntity getEntityForPoint (int viewX, int viewY)
boolean getRefreshBuffer ()
void setRefreshBuffer (boolean flag)
void paintComponent (Graphics g)
void chartChanged (ChartChangeEvent event)
void chartProgress (ChartProgressEvent event)
void actionPerformed (ActionEvent event)
void mouseEntered (MouseEvent e)
void mouseExited (MouseEvent e)
void mousePressed (MouseEvent e)
void mouseDragged (MouseEvent e)
void mouseReleased (MouseEvent e)
void mouseClicked (MouseEvent event)
void mouseMoved (MouseEvent e)
void zoomInBoth (double x, double y)
void zoomInDomain (double x, double y)
void zoomInRange (double x, double y)
void zoomOutBoth (double x, double y)
void zoomOutDomain (double x, double y)
void zoomOutRange (double x, double y)
void zoom (Rectangle2D selection)
void restoreAutoBounds ()
void restoreAutoDomainBounds ()
void restoreAutoRangeBounds ()
Rectangle2D getScreenDataArea ()
Rectangle2D getScreenDataArea (int x, int y)
int getInitialDelay ()
int getReshowDelay ()
int getDismissDelay ()
void setInitialDelay (int delay)
void setReshowDelay (int delay)
void setDismissDelay (int delay)
double getZoomInFactor ()
void setZoomInFactor (double factor)
double getZoomOutFactor ()
void setZoomOutFactor (double factor)
void doEditChartProperties ()
void doSaveAs () throws IOException
void createChartPrintJob ()
int print (Graphics g, PageFormat pf, int pageIndex)
void addChartMouseListener (ChartMouseListener listener)
void removeChartMouseListener (ChartMouseListener listener)
EventListener[] getListeners (Class listenerType)
Static Public Attributes
static final boolean DEFAULT_BUFFER_USED = false
static final int DEFAULT_WIDTH = 680
static final int DEFAULT_HEIGHT = 420
static final int DEFAULT_MINIMUM_DRAW_WIDTH = 300
static final int DEFAULT_MINIMUM_DRAW_HEIGHT = 200
static final int DEFAULT_MAXIMUM_DRAW_WIDTH = 800
static final int DEFAULT_MAXIMUM_DRAW_HEIGHT = 600
static final int DEFAULT_ZOOM_TRIGGER_DISTANCE = 10
static final String PROPERTIES_COMMAND = "PROPERTIES"
static final String SAVE_COMMAND = "SAVE"
static final String PRINT_COMMAND = "PRINT"
static final String ZOOM_IN_BOTH_COMMAND = "ZOOM_IN_BOTH"
static final String ZOOM_IN_DOMAIN_COMMAND = "ZOOM_IN_DOMAIN"
static final String ZOOM_IN_RANGE_COMMAND = "ZOOM_IN_RANGE"
static final String ZOOM_OUT_BOTH_COMMAND = "ZOOM_OUT_BOTH"
static final String ZOOM_OUT_DOMAIN_COMMAND = "ZOOM_DOMAIN_BOTH"
static final String ZOOM_OUT_RANGE_COMMAND = "ZOOM_RANGE_BOTH"
static final String ZOOM_RESET_BOTH_COMMAND = "ZOOM_RESET_BOTH"
static final String ZOOM_RESET_DOMAIN_COMMAND = "ZOOM_RESET_DOMAIN"
static final String ZOOM_RESET_RANGE_COMMAND = "ZOOM_RESET_RANGE"
Protected Member Functions
void setAnchor (Point2D anchor)
Line2D getHorizontalTraceLine ()
void setHorizontalTraceLine (Line2D line)
Line2D getVerticalTraceLine ()
void setVerticalTraceLine (Line2D line)
JPopupMenu createPopupMenu (boolean properties, boolean save, boolean print, boolean zoom)
void displayPopupMenu (int x, int y)
Static Protected Attributes
static ResourceBundle localizationResources = ResourceBundle.getBundle("org.jfree.chart.LocalizationBundle")
Detailed Description
A Swing GUI component for displaying a org.jfree.chart.JFreeChart object.
The panel registers with the chart to receive notification of changes to any component of the chart. The chart is redrawn automatically whenever this notification is received.
Definition at line 69 of file ChartPanel.java.
Constructor & Destructor Documentation
anl.verdi.plot.jfree.ChartPanel.ChartPanel (JFreeChart chart)
Constructs a panel that displays the specified chart.
Parameters
chart the chart.
Definition at line 430 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.DEFAULT_BUFFER_USED, anl.verdi.plot.jfree.ChartPanel.DEFAULT_HEIGHT, anl.verdi.plot.jfree.ChartPanel.DEFAULT_MAXIMUM_DRAW_HEIGHT, anl.verdi.plot.jfree.ChartPanel.DEFAULT_MAXIMUM_DRAW_WIDTH, anl.verdi.plot.jfree.ChartPanel.DEFAULT_MINIMUM_DRAW_HEIGHT, anl.verdi.plot.jfree.ChartPanel.DEFAULT_MINIMUM_DRAW_WIDTH, and anl.verdi.plot.jfree.ChartPanel.DEFAULT_WIDTH.
anl.verdi.plot.jfree.ChartPanel.ChartPanel (JFreeChart chart, boolean useBuffer)
Constructs a panel containing a chart.
Parameters
chart the chart.
useBuffer a flag controlling whether or not an off-screen buffer is used.
Definition at line 457 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.DEFAULT_HEIGHT, anl.verdi.plot.jfree.ChartPanel.DEFAULT_MAXIMUM_DRAW_HEIGHT, anl.verdi.plot.jfree.ChartPanel.DEFAULT_MAXIMUM_DRAW_WIDTH, anl.verdi.plot.jfree.ChartPanel.DEFAULT_MINIMUM_DRAW_HEIGHT, anl.verdi.plot.jfree.ChartPanel.DEFAULT_MINIMUM_DRAW_WIDTH, and anl.verdi.plot.jfree.ChartPanel.DEFAULT_WIDTH.
anl.verdi.plot.jfree.ChartPanel.ChartPanel (JFreeChart chart, boolean properties, boolean save, boolean print, boolean zoom, boolean tooltips)
Constructs a JFreeChart panel.
Parameters
chart the chart.
properties a flag indicating whether or not the chart property editor should be available via the popup menu.
save a flag indicating whether or not save options should be available via the popup menu.
print a flag indicating whether or not the print option should be available via the popup menu.
zoom a flag indicating whether or not zoom options should be added to the popup menu.
tooltips a flag indicating whether or not tooltips should be enabled for the chart.
Definition at line 491 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.DEFAULT_BUFFER_USED, anl.verdi.plot.jfree.ChartPanel.DEFAULT_HEIGHT, anl.verdi.plot.jfree.ChartPanel.DEFAULT_MAXIMUM_DRAW_HEIGHT, anl.verdi.plot.jfree.ChartPanel.DEFAULT_MAXIMUM_DRAW_WIDTH, anl.verdi.plot.jfree.ChartPanel.DEFAULT_MINIMUM_DRAW_HEIGHT, anl.verdi.plot.jfree.ChartPanel.DEFAULT_MINIMUM_DRAW_WIDTH, anl.verdi.plot.jfree.ChartPanel.DEFAULT_WIDTH, anl.verdi.plot.jfree.ChartPanel.print(), and anl.verdi.plot.jfree.ChartPanel.zoom().
anl.verdi.plot.jfree.ChartPanel.ChartPanel (JFreeChart chart, int width, int height, int minimumDrawWidth, int minimumDrawHeight, int maximumDrawWidth, int maximumDrawHeight, boolean useBuffer, boolean properties, boolean save, boolean print, boolean zoom, boolean tooltips)
Constructs a JFreeChart panel.
Parameters
chart the chart.
width the preferred width of the panel.
height the preferred height of the panel.
minimumDrawWidth the minimum drawing width.
minimumDrawHeight the minimum drawing height.
maximumDrawWidth the maximum drawing width.
maximumDrawHeight the maximum drawing height.
useBuffer a flag that indicates whether to use the off-screen buffer to improve performance (at the expense of memory).
properties a flag indicating whether or not the chart property editor should be available via the popup menu.
save a flag indicating whether or not save options should be available via the popup menu.
print a flag indicating whether or not the print option should be available via the popup menu.
zoom a flag indicating whether or not zoom options should be added to the popup menu.
tooltips a flag indicating whether or not tooltips should be enabled for the chart.
Definition at line 539 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.createPopupMenu(), anl.verdi.plot.jfree.ChartPanel.DEFAULT_ZOOM_TRIGGER_DISTANCE, and anl.verdi.plot.jfree.ChartPanel.setDisplayToolTips().
Member Function Documentation
void anl.verdi.plot.jfree.ChartPanel.actionPerformed (ActionEvent event)
Handles action events generated by the popup menu.
Parameters
event the event.
Definition at line 1289 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.createChartPrintJob(), anl.verdi.plot.jfree.ChartPanel.doEditChartProperties(), anl.verdi.plot.jfree.ChartPanel.doSaveAs(), anl.verdi.plot.jfree.ChartPanel.PRINT_COMMAND, anl.verdi.plot.jfree.ChartPanel.PROPERTIES_COMMAND, anl.verdi.plot.jfree.ChartPanel.restoreAutoBounds(), anl.verdi.plot.jfree.ChartPanel.restoreAutoDomainBounds(), anl.verdi.plot.jfree.ChartPanel.restoreAutoRangeBounds(), anl.verdi.plot.jfree.ChartPanel.SAVE_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_IN_BOTH_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_IN_DOMAIN_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_IN_RANGE_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_OUT_BOTH_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_OUT_DOMAIN_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_OUT_RANGE_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_RESET_BOTH_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_RESET_DOMAIN_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_RESET_RANGE_COMMAND, anl.verdi.plot.jfree.ChartPanel.zoomInBoth(), anl.verdi.plot.jfree.ChartPanel.zoomInDomain(), anl.verdi.plot.jfree.ChartPanel.zoomInRange(), anl.verdi.plot.jfree.ChartPanel.zoomOutBoth(), anl.verdi.plot.jfree.ChartPanel.zoomOutDomain(), and anl.verdi.plot.jfree.ChartPanel.zoomOutRange().
void anl.verdi.plot.jfree.ChartPanel.addChartMouseListener (ChartMouseListener listener)
Adds a listener to the list of objects listening for chart mouse events.
Parameters
listener the listener (null not permitted).
Definition at line 2117 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.chartChanged (ChartChangeEvent event)
Receives notification of changes to the chart, and redraws the chart.
Parameters
event details of the chart change event.
Definition at line 1265 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.chartProgress (ChartProgressEvent event)
Receives notification of a chart progress event.
Parameters
event the event.
Definition at line 1280 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.createChartPrintJob ()
Creates a print job for the chart.
Definition at line 2068 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed().
JPopupMenu anl.verdi.plot.jfree.ChartPanel.createPopupMenu (boolean properties, boolean save, boolean print, boolean zoom) protected
Creates a popup menu for the panel.
Parameters
properties include a menu item for the chart property editor.
save include a menu item for saving the chart.
print include a menu item for printing the chart.
zoom include menu items for zooming.
Returns
The popup menu.
Definition at line 2159 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.localizationResources, anl.verdi.plot.jfree.ChartPanel.PRINT_COMMAND, anl.verdi.plot.jfree.ChartPanel.PROPERTIES_COMMAND, anl.verdi.plot.jfree.ChartPanel.SAVE_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_IN_BOTH_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_IN_DOMAIN_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_IN_RANGE_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_OUT_BOTH_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_OUT_DOMAIN_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_OUT_RANGE_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_RESET_BOTH_COMMAND, anl.verdi.plot.jfree.ChartPanel.ZOOM_RESET_DOMAIN_COMMAND, and anl.verdi.plot.jfree.ChartPanel.ZOOM_RESET_RANGE_COMMAND.
Referenced by anl.verdi.plot.jfree.ChartPanel.ChartPanel().
void anl.verdi.plot.jfree.ChartPanel.displayPopupMenu (int x, int y) protected
The idea is to modify the zooming options depending on the type of chart being displayed by the panel.
Parameters
x horizontal position of the popup.
y vertical position of the popup.
Definition at line 2300 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.isDomainZoomable(), and anl.verdi.plot.jfree.ChartPanel.isRangeZoomable().
Referenced by anl.verdi.plot.jfree.ChartPanel.mousePressed(), and anl.verdi.plot.jfree.ChartPanel.mouseReleased().
void anl.verdi.plot.jfree.ChartPanel.doEditChartProperties ()
Displays a dialog that allows the user to edit the properties for the current chart.
Since
1.0.3
Definition at line 2027 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed().
void anl.verdi.plot.jfree.ChartPanel.doSaveAs () throws IOException
Opens a file chooser and gives the user an opportunity to save the chart in PNG format.
Exceptions
IOException if there is an I/O error.
Definition at line 2044 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.isEnforceFileExtensions(), and anl.verdi.plot.jfree.ChartPanel.localizationResources.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed().
Point2D anl.verdi.plot.jfree.ChartPanel.getAnchor ()
Returns the anchor point.
Returns
The anchor point (possibly null).
Definition at line 760 of file ChartPanel.java.
JFreeChart anl.verdi.plot.jfree.ChartPanel.getChart ()
Returns the chart contained in the panel.
Returns
The chart (possibly null).
Definition at line 593 of file ChartPanel.java.
Referenced by anl.verdi.plot.types.AbstractPlot.VerdiChartPanel.doEditChartTheme(), anl.verdi.plot.jfree.ChartPanel.mouseClicked(), and anl.verdi.plot.jfree.ChartPanel.mouseMoved().
ChartRenderingInfo anl.verdi.plot.jfree.ChartPanel.getChartRenderingInfo ()
Returns the chart rendering info from the most recent chart redraw.
Returns
The chart rendering info.
Definition at line 797 of file ChartPanel.java.
int anl.verdi.plot.jfree.ChartPanel.getDismissDelay ()
Returns the dismissal tooltip delay value used inside this chart panel.
Returns
An integer representing the dismissal delay value, in milliseconds.
See Also
javax.swing.ToolTipManager::getDismissDelay()
Definition at line 1862 of file ChartPanel.java.
ChartEntity anl.verdi.plot.jfree.ChartPanel.getEntityForPoint (int viewX, int viewY)
Returns the chart entity at a given point.
This method will return null if there is (a) no entity at the given point, or (b) no entity collection has been generated.
Parameters
viewX the x-coordinate.
viewY the y-coordinate.
Returns
The chart entity (possibly null).
Definition at line 1108 of file ChartPanel.java.
boolean anl.verdi.plot.jfree.ChartPanel.getFillZoomRectangle ()
Returns the flag that controls whether or not the zoom rectangle is filled when drawn.
Returns
A boolean.
Definition at line 886 of file ChartPanel.java.
boolean anl.verdi.plot.jfree.ChartPanel.getHorizontalAxisTrace ()
Returns the flag that controls whether or not a horizontal axis trace line is drawn over the plot area at the current mouse location.
Returns
A boolean.
Definition at line 926 of file ChartPanel.java.
Line2D anl.verdi.plot.jfree.ChartPanel.getHorizontalTraceLine () protected
Returns the horizontal trace line.
Returns
The horizontal trace line (possibly null).
Definition at line 945 of file ChartPanel.java.
int anl.verdi.plot.jfree.ChartPanel.getInitialDelay ()
Returns the initial tooltip delay value used inside this chart panel.
Returns
An integer representing the initial delay value, in milliseconds.
See Also
javax.swing.ToolTipManager::getInitialDelay()
Definition at line 1841 of file ChartPanel.java.
EventListener [] anl.verdi.plot.jfree.ChartPanel.getListeners (Class listenerType)
Returns an array of the listeners of the given type registered with the panel.
Parameters
listenerType the listener type.
Returns
An array of listeners.
Definition at line 2141 of file ChartPanel.java.
int anl.verdi.plot.jfree.ChartPanel.getMaximumDrawHeight ()
Returns the maximum drawing height for charts.
If the height available on the panel is greater than this, then the chart is drawn at the maximum height then scaled up to fit.
Returns
The maximum drawing height.
Definition at line 718 of file ChartPanel.java.
int anl.verdi.plot.jfree.ChartPanel.getMaximumDrawWidth ()
Returns the maximum drawing width for charts.
If the width available on the panel is greater than this, then the chart is drawn at the maximum width then scaled up to fit.
Returns
The maximum drawing width.
Definition at line 668 of file ChartPanel.java.
int anl.verdi.plot.jfree.ChartPanel.getMinimumDrawHeight ()
Returns the minimum drawing height for charts.
If the height available on the panel is less than this, then the chart is drawn at the minimum height then scaled down to fit.
Returns
The minimum drawing height.
Definition at line 693 of file ChartPanel.java.
int anl.verdi.plot.jfree.ChartPanel.getMinimumDrawWidth ()
Returns the minimum drawing width for charts.
If the width available on the panel is less than this, then the chart is drawn at the minimum width then scaled down to fit.
Returns
The minimum drawing width.
Definition at line 643 of file ChartPanel.java.
JPopupMenu anl.verdi.plot.jfree.ChartPanel.getPopupMenu ()
Returns the popup menu.
Returns
The popup menu.
Definition at line 779 of file ChartPanel.java.
boolean anl.verdi.plot.jfree.ChartPanel.getRefreshBuffer ()
Returns the flag that controls whether or not the offscreen buffer needs to be refreshed.
Returns
A boolean.
Definition at line 1128 of file ChartPanel.java.
int anl.verdi.plot.jfree.ChartPanel.getReshowDelay ()
Returns the reshow tooltip delay value used inside this chart panel.
Returns
An integer representing the reshow delay value, in milliseconds.
See Also
javax.swing.ToolTipManager::getReshowDelay()
Definition at line 1851 of file ChartPanel.java.
double anl.verdi.plot.jfree.ChartPanel.getScaleX ()
Returns the X scale factor for the chart. This will be 1.0 if no scaling has been used.
Returns
The scale factor.
Definition at line 741 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.scale().
double anl.verdi.plot.jfree.ChartPanel.getScaleY ()
Returns the Y scale factory for the chart. This will be 1.0 if no scaling has been used.
Returns
The scale factor.
Definition at line 751 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.scale().
Rectangle2D anl.verdi.plot.jfree.ChartPanel.getScreenDataArea ()
Returns the data area for the chart (the area inside the axes) with the current scaling applied (that is, the area as it appears on screen).
Returns
The scaled data area.
Definition at line 1799 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.getScreenDataArea(), anl.verdi.plot.jfree.ChartPanel.mouseDragged(), anl.verdi.plot.jfree.ChartPanel.mousePressed(), anl.verdi.plot.jfree.ChartPanel.mouseReleased(), and anl.verdi.plot.jfree.ChartPanel.zoom().
Rectangle2D anl.verdi.plot.jfree.ChartPanel.getScreenDataArea (int x, int y)
Returns the data area (the area inside the axes) for the plot or subplot, with the current scaling applied.
Parameters
x the x-coordinate (for subplot selection).
y the y-coordinate (for subplot selection).
Returns
The scaled data area.
Definition at line 1817 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.getScreenDataArea(), anl.verdi.plot.jfree.ChartPanel.scale(), and anl.verdi.plot.jfree.ChartPanel.translateScreenToJava2D().
String anl.verdi.plot.jfree.ChartPanel.getToolTipText (MouseEvent e)
Returns a string for the tooltip.
Parameters
e the mouse event.
Returns
A tool tip or null if no tooltip is available.
Definition at line 1037 of file ChartPanel.java.
boolean anl.verdi.plot.jfree.ChartPanel.getVerticalAxisTrace ()
Returns the flag that controls whether or not a vertical axis trace line is drawn over the plot area at the current mouse location.
Returns
A boolean.
Definition at line 964 of file ChartPanel.java.
Line2D anl.verdi.plot.jfree.ChartPanel.getVerticalTraceLine () protected
Returns the vertical trace line.
Returns
The vertical trace line (possibly null).
Definition at line 983 of file ChartPanel.java.
double anl.verdi.plot.jfree.ChartPanel.getZoomInFactor ()
Returns the zoom in factor.
Returns
The zoom in factor.
See Also
setZoomInFactor(double)
Definition at line 1905 of file ChartPanel.java.
double anl.verdi.plot.jfree.ChartPanel.getZoomOutFactor ()
Returns the zoom out factor.
Returns
The zoom out factor.
See Also
setZoomOutFactor(double)
Definition at line 1925 of file ChartPanel.java.
int anl.verdi.plot.jfree.ChartPanel.getZoomTriggerDistance ()
Returns the zoom trigger distance. This controls how far the mouse must move before a zoom action is triggered.
Returns
The distance (in Java2D units).
Definition at line 906 of file ChartPanel.java.
boolean anl.verdi.plot.jfree.ChartPanel.isDomainZoomable ()
Returns the flag that determines whether or not zooming is enabled for the domain axis.
Returns
A boolean.
Definition at line 830 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.displayPopupMenu().
boolean anl.verdi.plot.jfree.ChartPanel.isEnforceFileExtensions ()
Returns true if file extensions should be enforced, and false otherwise.
Returns
The flag.
Definition at line 1002 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.doSaveAs().
boolean anl.verdi.plot.jfree.ChartPanel.isRangeZoomable ()
Returns the flag that determines whether or not zooming is enabled for the range axis.
Returns
A boolean.
Definition at line 859 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.displayPopupMenu().
void anl.verdi.plot.jfree.ChartPanel.mouseClicked (MouseEvent event)
Receives notification of mouse clicks on the panel. These are translated and passed on to any registered chart mouse click listeners.
Parameters
event Information about the mouse event.
Definition at line 1555 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.getChart().
void anl.verdi.plot.jfree.ChartPanel.mouseDragged (MouseEvent e)
Handles a 'mouse dragged' event.
Parameters
e the mouse event.
Definition at line 1415 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.getScreenDataArea().
void anl.verdi.plot.jfree.ChartPanel.mouseEntered (MouseEvent e)
Handles a 'mouse entered' event. This method changes the tooltip delays of ToolTipManager.sharedInstance() to the possibly different values set for this chart panel.
Parameters
e the mouse event.
Definition at line 1333 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.mouseExited (MouseEvent e)
Handles a 'mouse exited' event. This method resets the tooltip delays of ToolTipManager.sharedInstance() to their original values in effect before mouseEntered()
Parameters
e the mouse event.
Definition at line 1357 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.mouseMoved (MouseEvent e)
Implementation of the MouseMotionListener's method.
Parameters
e the event.
Definition at line 1593 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.getChart().
void anl.verdi.plot.jfree.ChartPanel.mousePressed (MouseEvent e)
Handles a 'mouse pressed' event.
This event is the popup trigger on Unix/Linux. For Windows, the popup trigger is the 'mouse released' event.
Parameters
e The mouse event.
Definition at line 1376 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.displayPopupMenu(), and anl.verdi.plot.jfree.ChartPanel.getScreenDataArea().
void anl.verdi.plot.jfree.ChartPanel.mouseReleased (MouseEvent e)
Handles a 'mouse released' event. On Windows, we need to check if this is a popup trigger, but only if we haven't already been tracking a zoom rectangle.
Parameters
e information about the event.
Definition at line 1474 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.displayPopupMenu(), anl.verdi.plot.jfree.ChartPanel.getScreenDataArea(), anl.verdi.plot.jfree.ChartPanel.restoreAutoBounds(), and anl.verdi.plot.jfree.ChartPanel.zoom().
void anl.verdi.plot.jfree.ChartPanel.paintComponent (Graphics g)
Paints the component by drawing the chart to fill the entire component, but allowing for the insets (which will be non-zero if a border has been set for this component). To increase performance (at the expense of memory), an off-screen buffer image can be used.
Parameters
g the graphics device for drawing on.
Definition at line 1182 of file ChartPanel.java.
int anl.verdi.plot.jfree.ChartPanel.print (Graphics g, PageFormat pf, int pageIndex)
Prints the chart on a single page.
Parameters
g the graphics context.
pf the page format to use.
pageIndex the index of the page. If not 0, nothing gets print.
Returns
The result of printing.
Definition at line 2096 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.ChartPanel().
void anl.verdi.plot.jfree.ChartPanel.removeChartMouseListener (ChartMouseListener listener)
Removes a listener from the list of objects listening for chart mouse events.
Parameters
listener the listener.
Definition at line 2130 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.restoreAutoBounds ()
Restores the auto-range calculation on both axes.
Definition at line 1766 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.restoreAutoDomainBounds(), and anl.verdi.plot.jfree.ChartPanel.restoreAutoRangeBounds().
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.mouseReleased().
void anl.verdi.plot.jfree.ChartPanel.restoreAutoDomainBounds ()
Restores the auto-range calculation on the domain axis.
Definition at line 1774 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.restoreAutoBounds().
void anl.verdi.plot.jfree.ChartPanel.restoreAutoRangeBounds ()
Restores the auto-range calculation on the range axis.
Definition at line 1785 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.restoreAutoBounds().
Rectangle2D anl.verdi.plot.jfree.ChartPanel.scale (Rectangle2D rect)
Applies any scaling that is in effect for the chart drawing to the given rectangle.
Parameters
rect the rectangle.
Returns
A new scaled rectangle.
Definition at line 1089 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.getScaleX(), and anl.verdi.plot.jfree.ChartPanel.getScaleY().
Referenced by anl.verdi.plot.jfree.ChartPanel.getScreenDataArea().
void anl.verdi.plot.jfree.ChartPanel.setAnchor (Point2D anchor) protected
Sets the anchor point. This method is provided for the use of subclasses, not end users.
Parameters
anchor the anchor point (null permitted).
Definition at line 770 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setChart (JFreeChart chart)
Sets the chart that is displayed in the panel.
Parameters
chart the chart (null permitted).
Definition at line 602 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setDismissDelay (int delay)
Specifies the dismissal delay value for this chart panel.
Parameters
delay the number of milliseconds to delay before taking away the tooltip
See Also
javax.swing.ToolTipManager::setDismissDelay(int)
Definition at line 1895 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setDisplayToolTips (boolean flag)
Switches the display of tooltips for the panel on or off. Note that tooltips can only be displayed if the chart has been configured to generate tooltip items.
Parameters
flag true to enable tooltips, false to disable tooltips.
Definition at line 1023 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.ChartPanel().
void anl.verdi.plot.jfree.ChartPanel.setDomainZoomable (boolean flag)
Sets the flag that controls whether or not zooming is enable for the domain axis. A check is made to ensure that the current plot supports zooming for the domain values.
Parameters
flag true enables zooming if possible.
Definition at line 841 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.setMouseZoomable().
void anl.verdi.plot.jfree.ChartPanel.setEnforceFileExtensions (boolean enforce)
Sets a flag that controls whether or not file extensions are enforced.
Parameters
enforce the new flag value.
Definition at line 1011 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setFillZoomRectangle (boolean flag)
A flag that controls how the zoom rectangle is drawn.
Parameters
flag true instructs to fill the rectangle on zoom, otherwise it will be outlined.
Definition at line 896 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.setMouseZoomable().
void anl.verdi.plot.jfree.ChartPanel.setHorizontalAxisTrace (boolean flag)
A flag that controls trace lines on the horizontal axis.
Parameters
flag true enables trace lines for the mouse pointer on the horizontal axis.
Definition at line 936 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setHorizontalTraceLine (Line2D line) protected
Sets the horizontal trace line.
Parameters
line the line (null permitted).
Definition at line 954 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setInitialDelay (int delay)
Specifies the initial delay value for this chart panel.
Parameters
delay the number of milliseconds to delay (after the cursor has paused) before displaying.
See Also
javax.swing.ToolTipManager::setInitialDelay(int)
Definition at line 1873 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setMaximumDrawHeight (int height)
Sets the maximum drawing height for the chart on this panel.
At the time the chart is drawn on the panel, if the available height is greater than this amount, the chart will be drawn using the maximum height then scaled up to fit the available space.
Parameters
height The height.
Definition at line 731 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setMaximumDrawWidth (int width)
Sets the maximum drawing width for the chart on this panel.
At the time the chart is drawn on the panel, if the available width is greater than this amount, the chart will be drawn using the maximum width then scaled up to fit the available space.
Parameters
width The width.
Definition at line 681 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setMinimumDrawHeight (int height)
Sets the minimum drawing height for the chart on this panel.
At the time the chart is drawn on the panel, if the available height is less than this amount, the chart will be drawn using the minimum height then scaled down to fit the available space.
Parameters
height The height.
Definition at line 706 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setMinimumDrawWidth (int width)
Sets the minimum drawing width for the chart on this panel.
At the time the chart is drawn on the panel, if the available width is less than this amount, the chart will be drawn using the minimum width then scaled down to fit the available space.
Parameters
width The width.
Definition at line 656 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setMouseZoomable (boolean flag)
A convenience method that switches on mouse-based zooming.
Parameters
flag true enables zooming and rectangle fill on zoom.
Definition at line 807 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setMouseZoomable (boolean flag, boolean fillRectangle)
A convenience method that switches on mouse-based zooming.
Parameters
flag true if zooming enabled
fillRectangle true if zoom rectangle is filled, false if rectangle is shown as outline only.
Definition at line 818 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.setDomainZoomable(), anl.verdi.plot.jfree.ChartPanel.setFillZoomRectangle(), and anl.verdi.plot.jfree.ChartPanel.setRangeZoomable().
void anl.verdi.plot.jfree.ChartPanel.setPopupMenu (JPopupMenu popup)
Sets the popup menu for the panel.
Parameters
popup the popup menu (null permitted).
Definition at line 788 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setRangeZoomable (boolean flag)
A flag that controls mouse-based zooming on the vertical axis.
Parameters
flag true enables zooming.
Definition at line 868 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.setMouseZoomable().
void anl.verdi.plot.jfree.ChartPanel.setRefreshBuffer (boolean flag)
Sets the refresh buffer flag. This flag is used to avoid unnecessary redrawing of the chart when the offscreen image buffer is used.
Parameters
flag true indicate, that the buffer should be refreshed.
Definition at line 1139 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setReshowDelay (int delay)
Specifies the amount of time before the user has to wait initialDelay milliseconds before a tooltip will be shown.
Parameters
delay time in milliseconds
See Also
javax.swing.ToolTipManager::setReshowDelay(int)
Definition at line 1884 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setVerticalAxisTrace (boolean flag)
A flag that controls trace lines on the vertical axis.
Parameters
flag true enables trace lines for the mouse pointer on the vertical axis.
Definition at line 974 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setVerticalTraceLine (Line2D line) protected
Sets the vertical trace line.
Parameters
line the line (null permitted).
Definition at line 992 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setZoomInFactor (double factor)
Sets the zoom in factor.
Parameters
factor the factor.
See Also
getZoomInFactor()
Definition at line 1915 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setZoomOutFactor (double factor)
Sets the zoom out factor.
Parameters
factor the factor.
See Also
getZoomOutFactor()
Definition at line 1935 of file ChartPanel.java.
void anl.verdi.plot.jfree.ChartPanel.setZoomTriggerDistance (int distance)
Sets the zoom trigger distance. This controls how far the mouse must move before a zoom action is triggered.
Parameters
distance the distance (in Java2D units).
Definition at line 916 of file ChartPanel.java.
Point anl.verdi.plot.jfree.ChartPanel.translateJava2DToScreen (Point2D java2DPoint)
Translates a Java2D point on the chart to a screen location.
Parameters
java2DPoint the Java2D point.
Returns
The screen location.
Definition at line 1062 of file ChartPanel.java.
Point2D anl.verdi.plot.jfree.ChartPanel.translateScreenToJava2D (Point screenPoint)
Translates a screen location to a Java2D point.
Parameters
screenPoint the screen location.
Returns
The Java2D coordinates.
Definition at line 1075 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.getScreenDataArea(), anl.verdi.plot.jfree.ChartPanel.zoom(), anl.verdi.plot.jfree.ChartPanel.zoomInDomain(), anl.verdi.plot.jfree.ChartPanel.zoomInRange(), anl.verdi.plot.jfree.ChartPanel.zoomOutDomain(), and anl.verdi.plot.jfree.ChartPanel.zoomOutRange().
void anl.verdi.plot.jfree.ChartPanel.zoom (Rectangle2D selection)
Zooms in on a selected region.
Parameters
selection the selected region.
Definition at line 1726 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.getScreenDataArea(), and anl.verdi.plot.jfree.ChartPanel.translateScreenToJava2D().
Referenced by anl.verdi.plot.jfree.ChartPanel.ChartPanel(), and anl.verdi.plot.jfree.ChartPanel.mouseReleased().
void anl.verdi.plot.jfree.ChartPanel.zoomInBoth (double x, double y)
Zooms in on an anchor point (specified in screen coordinate space).
Parameters
x the x value (in screen coordinates).
y the y value (in screen coordinates).
Definition at line 1637 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.zoomInDomain(), and anl.verdi.plot.jfree.ChartPanel.zoomInRange().
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed().
void anl.verdi.plot.jfree.ChartPanel.zoomInDomain (double x, double y)
Decreases the length of the domain axis, centered about the given coordinate on the screen. The length of the domain axis is reduced by the value of getZoomInFactor().
Parameters
x the x coordinate (in screen coordinates).
y the y-coordinate (in screen coordinates).
Definition at line 1650 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.translateScreenToJava2D().
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.zoomInBoth().
void anl.verdi.plot.jfree.ChartPanel.zoomInRange (double x, double y)
Decreases the length of the range axis, centered about the given coordinate on the screen. The length of the range axis is reduced by the value of getZoomInFactor().
Parameters
x the x-coordinate (in screen coordinates).
y the y coordinate (in screen coordinates).
Definition at line 1667 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.translateScreenToJava2D().
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.zoomInBoth().
void anl.verdi.plot.jfree.ChartPanel.zoomOutBoth (double x, double y)
Zooms out on an anchor point (specified in screen coordinate space).
Parameters
x the x value (in screen coordinates).
y the y value (in screen coordinates).
Definition at line 1682 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.zoomOutDomain(), and anl.verdi.plot.jfree.ChartPanel.zoomOutRange().
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed().
void anl.verdi.plot.jfree.ChartPanel.zoomOutDomain (double x, double y)
Increases the length of the domain axis, centered about the given coordinate on the screen. The length of the domain axis is increased by the value of getZoomOutFactor().
Parameters
x the x coordinate (in screen coordinates).
y the y-coordinate (in screen coordinates).
Definition at line 1695 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.translateScreenToJava2D().
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.zoomOutBoth().
void anl.verdi.plot.jfree.ChartPanel.zoomOutRange (double x, double y)
Increases the length the range axis, centered about the given coordinate on the screen. The length of the range axis is increased by the value of getZoomOutFactor().
Parameters
x the x coordinate (in screen coordinates).
y the y-coordinate (in screen coordinates).
Definition at line 1712 of file ChartPanel.java.
References anl.verdi.plot.jfree.ChartPanel.translateScreenToJava2D().
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.zoomOutBoth().
Member Data Documentation
final boolean anl.verdi.plot.jfree.ChartPanel.DEFAULT_BUFFER_USED = false static
Default setting for buffer usage.
Definition at line 87 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.ChartPanel().
final int anl.verdi.plot.jfree.ChartPanel.DEFAULT_HEIGHT = 420 static
The default panel height.
Definition at line 97 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.ChartPanel().
final int anl.verdi.plot.jfree.ChartPanel.DEFAULT_MAXIMUM_DRAW_HEIGHT = 600 static
The default limit below which chart scaling kicks in.
Definition at line 117 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.ChartPanel().
final int anl.verdi.plot.jfree.ChartPanel.DEFAULT_MAXIMUM_DRAW_WIDTH = 800 static
The default limit below which chart scaling kicks in.
Definition at line 112 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.ChartPanel().
final int anl.verdi.plot.jfree.ChartPanel.DEFAULT_MINIMUM_DRAW_HEIGHT = 200 static
The default limit below which chart scaling kicks in.
Definition at line 107 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.ChartPanel().
final int anl.verdi.plot.jfree.ChartPanel.DEFAULT_MINIMUM_DRAW_WIDTH = 300 static
The default limit below which chart scaling kicks in.
Definition at line 102 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.ChartPanel().
final int anl.verdi.plot.jfree.ChartPanel.DEFAULT_WIDTH = 680 static
The default panel width.
Definition at line 92 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.ChartPanel().
final int anl.verdi.plot.jfree.ChartPanel.DEFAULT_ZOOM_TRIGGER_DISTANCE = 10 static
The minimum size required to perform a zoom on a rectangle
Definition at line 122 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.ChartPanel().
ResourceBundle anl.verdi.plot.jfree.ChartPanel.localizationResources = ResourceBundle.getBundle("org.jfree.chart.LocalizationBundle") static protected
The resourceBundle for the localization.
Definition at line 423 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.createPopupMenu(), and anl.verdi.plot.jfree.ChartPanel.doSaveAs().
final String anl.verdi.plot.jfree.ChartPanel.PRINT_COMMAND = "PRINT" static
Print action command.
Definition at line 137 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.createPopupMenu().
final String anl.verdi.plot.jfree.ChartPanel.PROPERTIES_COMMAND = "PROPERTIES" static
Properties action command.
Definition at line 127 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.createPopupMenu().
final String anl.verdi.plot.jfree.ChartPanel.SAVE_COMMAND = "SAVE" static
Save action command.
Definition at line 132 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.createPopupMenu().
final String anl.verdi.plot.jfree.ChartPanel.ZOOM_IN_BOTH_COMMAND = "ZOOM_IN_BOTH" static
Zoom in (both axes) action command.
Definition at line 142 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.createPopupMenu().
final String anl.verdi.plot.jfree.ChartPanel.ZOOM_IN_DOMAIN_COMMAND = "ZOOM_IN_DOMAIN" static
Zoom in (domain axis only) action command.
Definition at line 147 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.createPopupMenu().
final String anl.verdi.plot.jfree.ChartPanel.ZOOM_IN_RANGE_COMMAND = "ZOOM_IN_RANGE" static
Zoom in (range axis only) action command.
Definition at line 152 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.createPopupMenu().
final String anl.verdi.plot.jfree.ChartPanel.ZOOM_OUT_BOTH_COMMAND = "ZOOM_OUT_BOTH" static
Zoom out (both axes) action command.
Definition at line 157 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.createPopupMenu().
final String anl.verdi.plot.jfree.ChartPanel.ZOOM_OUT_DOMAIN_COMMAND = "ZOOM_DOMAIN_BOTH" static
Zoom out (domain axis only) action command.
Definition at line 162 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.createPopupMenu().
final String anl.verdi.plot.jfree.ChartPanel.ZOOM_OUT_RANGE_COMMAND = "ZOOM_RANGE_BOTH" static
Zoom out (range axis only) action command.
Definition at line 167 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.createPopupMenu().
final String anl.verdi.plot.jfree.ChartPanel.ZOOM_RESET_BOTH_COMMAND = "ZOOM_RESET_BOTH" static
Zoom reset (both axes) action command.
Definition at line 172 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.createPopupMenu().
final String anl.verdi.plot.jfree.ChartPanel.ZOOM_RESET_DOMAIN_COMMAND = "ZOOM_RESET_DOMAIN" static
Zoom reset (domain axis only) action command.
Definition at line 177 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.createPopupMenu().
final String anl.verdi.plot.jfree.ChartPanel.ZOOM_RESET_RANGE_COMMAND = "ZOOM_RESET_RANGE" static
Zoom reset (range axis only) action command.
Definition at line 182 of file ChartPanel.java.
Referenced by anl.verdi.plot.jfree.ChartPanel.actionPerformed(), and anl.verdi.plot.jfree.ChartPanel.createPopupMenu().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/jfree/ChartPanel.java