VERDI: anl.verdi.area.target.ProjectionPanel Class Reference
anl.verdi.area.target.ProjectionPanel Class Reference
Public Member Functions
ProjectionPanel ()
boolean isModified ()
void setup ()
CoordinateReferenceSystem getProjection ()
String getErrorString ()
void setProjectionInfo (String coordString)
Public Attributes
JComboBox projBox
Detailed Description
File Name:ProjectionPanel.java Description: A panel that lets the user pick projection information
Version
March 2004
Author
Mary Ann Bitz
Argonne National Lab
Definition at line 32 of file ProjectionPanel.java.
Constructor & Destructor Documentation
anl.verdi.area.target.ProjectionPanel.ProjectionPanel ()
Constructs the panel
Definition at line 49 of file ProjectionPanel.java.
Member Function Documentation
String anl.verdi.area.target.ProjectionPanel.getErrorString ()
Get the error string in the projection panel
Returns
Definition at line 124 of file ProjectionPanel.java.
CoordinateReferenceSystem anl.verdi.area.target.ProjectionPanel.getProjection ()
Get the string representing a given projection
Returns
the string corresponding to the projection
Definition at line 113 of file ProjectionPanel.java.
References anl.verdi.area.target.ProjectionInfo.update().
boolean anl.verdi.area.target.ProjectionPanel.isModified ()
Whether the projection has been changed
Returns
if it has been modified
Definition at line 57 of file ProjectionPanel.java.
void anl.verdi.area.target.ProjectionPanel.setProjectionInfo (String coordString)
Get the projection object from the panel
Returns
the projection entered by the user Update the projection panel based on the selected coordinate system
Parameters
coordString the coordinate system they picked
Definition at line 140 of file ProjectionPanel.java.
Referenced by anl.verdi.area.target.ProjectionPanel.setup().
void anl.verdi.area.target.ProjectionPanel.setup ()
Initial setup of the panel
Definition at line 65 of file ProjectionPanel.java.
References anl.verdi.area.target.ProjectionPanel.projBox, and anl.verdi.area.target.ProjectionPanel.setProjectionInfo().
Member Data Documentation
JComboBox anl.verdi.area.target.ProjectionPanel.projBox
Definition at line 40 of file ProjectionPanel.java.
Referenced by anl.verdi.area.target.ProjectionCard.setProjectionPanelInfo(), and anl.verdi.area.target.ProjectionPanel.setup().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/target/ProjectionPanel.java