VERDI: anl.verdi.plot.data.DataFrameXYZDataset Class Reference
anl.verdi.plot.data.DataFrameXYZDataset Class Reference
Public Member Functions
double getValue (int series, int x, int y)
void addSeries (DataFrame frame, int timeStep, int layer)
Number getZ (int series, int item)
double getZValue (int series, int item)
DomainOrder getDomainOrder ()
int getItemCount (int series)
Number getX (int series, int item)
double getXValue (int series, int item)
Number getY (int series, int item)
double getYValue (int series, int item)
int getSeriesCount ()
Comparable getSeriesKey (int series)
int indexOf (Comparable seriesKey)
Detailed Description
JChart XYZDataset implemented in terms of a DataFrame.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 21 of file DataFrameXYZDataset.java.
Member Function Documentation
void anl.verdi.plot.data.DataFrameXYZDataset.addSeries (DataFrame frame, int timeStep, int layer)
Definition at line 83 of file DataFrameXYZDataset.java.
References anl.verdi.data.DataFrame.getVariable(), and anl.verdi.plot.data.DataFrameXYZDataset.indexOf().
DomainOrder anl.verdi.plot.data.DataFrameXYZDataset.getDomainOrder ()
Returns the order of the domain (or X) values returned by the dataset.
Returns
The order (never null).
Definition at line 123 of file DataFrameXYZDataset.java.
int anl.verdi.plot.data.DataFrameXYZDataset.getItemCount (int series)
Returns the number of items in a series.
It is recommended that classes that implement this method should throw an IllegalArgumentException if the series argument is outside the specified range.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
Returns
The item count.
Definition at line 138 of file DataFrameXYZDataset.java.
int anl.verdi.plot.data.DataFrameXYZDataset.getSeriesCount ()
Returns the number of series in the dataset.
Returns
The series count.
Definition at line 208 of file DataFrameXYZDataset.java.
Referenced by anl.verdi.plot.data.DataFrameXYZDataset.getSeriesKey().
Comparable anl.verdi.plot.data.DataFrameXYZDataset.getSeriesKey (int series)
Returns the key for a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
Returns
The key for the series.
Definition at line 219 of file DataFrameXYZDataset.java.
References anl.verdi.plot.data.DataFrameXYZDataset.getSeriesCount().
double anl.verdi.plot.data.DataFrameXYZDataset.getValue (int series, int x, int y)
Gets the value for the series at the specified x, y coordinate.
Parameters
series the series
x x coordinate
y y coordinate
Returns
the value for the series at the specified x, y coordinate.
Definition at line 78 of file DataFrameXYZDataset.java.
Number anl.verdi.plot.data.DataFrameXYZDataset.getX (int series, int item)
Returns the x-value for an item within a series. The x-values may or may not be returned in ascending order, that is up to the class implementing the interface.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The x-value (never null).
Definition at line 153 of file DataFrameXYZDataset.java.
References anl.verdi.plot.data.DataFrameXYZDataset.getXValue().
double anl.verdi.plot.data.DataFrameXYZDataset.getXValue (int series, int item)
Returns the x-value for an item within a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The x-value.
Definition at line 166 of file DataFrameXYZDataset.java.
Referenced by anl.verdi.plot.data.DataFrameXYZDataset.getX().
Number anl.verdi.plot.data.DataFrameXYZDataset.getY (int series, int item)
Returns the y-value for an item within a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The y-value (possibly null).
Definition at line 185 of file DataFrameXYZDataset.java.
References anl.verdi.plot.data.DataFrameXYZDataset.getYValue().
double anl.verdi.plot.data.DataFrameXYZDataset.getYValue (int series, int item)
Returns the y-value (as a double primitive) for an item within a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The y-value.
Definition at line 198 of file DataFrameXYZDataset.java.
Referenced by anl.verdi.plot.data.DataFrameXYZDataset.getY().
Number anl.verdi.plot.data.DataFrameXYZDataset.getZ (int series, int item)
Returns the z-value for the specified series and item.
Parameters
series the series index (zero-based).
item the item index (zero-based).
Returns
The z-value (possibly null).
Definition at line 102 of file DataFrameXYZDataset.java.
References anl.verdi.plot.data.DataFrameXYZDataset.getZValue().
double anl.verdi.plot.data.DataFrameXYZDataset.getZValue (int series, int item)
Returns the z-value (as a double primitive) for an item within a series.
Parameters
series the series (zero-based index).
item the item (zero-based index).
Returns
The z-value.
Definition at line 113 of file DataFrameXYZDataset.java.
Referenced by anl.verdi.plot.data.DataFrameXYZDataset.getZ().
int anl.verdi.plot.data.DataFrameXYZDataset.indexOf (Comparable seriesKey)
Returns the index of the series with the specified key, or -1 if there is no such series in the dataset.
Parameters
seriesKey the series key (null permitted).
Returns
The index, or -1.
Definition at line 234 of file DataFrameXYZDataset.java.
Referenced by anl.verdi.plot.data.DataFrameXYZDataset.addSeries().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/data/DataFrameXYZDataset.java