VERDI: anl.verdi.area.target.GridInfo Class Reference
anl.verdi.area.target.GridInfo Class Reference
Public Member Functions
GridInfo (double[][] gridBounds, double[][] domain)
boolean equals (Object obj)
Static Public Member Functions
static int getGridNumber (GridInfo grid)
static GridInfo formGridInfo (DataFrame dataFrame, int firstColumn, int lastColumn, int firstRow, int lastRow)
Detailed Description
File Name:GridInfo.java Description: This object stores grid information for areas.
Version
May, 2009
Author
Mary Ann Bitz
Argonne National Lab
Definition at line 33 of file GridInfo.java.
Constructor & Destructor Documentation
anl.verdi.area.target.GridInfo.GridInfo (double gridBounds[][], double domain[][])
Definition at line 44 of file GridInfo.java.
Referenced by anl.verdi.area.target.GridInfo.equals(), and anl.verdi.area.target.GridInfo.formGridInfo().
Member Function Documentation
boolean anl.verdi.area.target.GridInfo.equals (Object obj)
Definition at line 56 of file GridInfo.java.
References anl.verdi.area.target.GridInfo.GridInfo().
static GridInfo anl.verdi.area.target.GridInfo.formGridInfo (DataFrame dataFrame, int firstColumn, int lastColumn, int firstRow, int lastRow) static
Definition at line 86 of file GridInfo.java.
References anl.verdi.area.target.GridInfo.GridInfo().
static int anl.verdi.area.target.GridInfo.getGridNumber (GridInfo grid) static
Definition at line 77 of file GridInfo.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/target/GridInfo.java