VERDI: ucar.nc2.dataset.conv.M3IOConvention Class Reference
ucar.nc2.dataset.conv.M3IOConvention Class Reference
Public Member Functions
M3IOConvention ()
void augmentDataset (NetcdfDataset ncd, CancelTask cancelTask)
Static Public Member Functions
static boolean isMine (NetcdfFile ncfile)
Protected Member Functions
void constructCoordAxes (NetcdfDataset ds)
AxisType getAxisType (NetcdfDataset ds, VariableEnhanced ve)
void makeCoordinateTransforms (NetcdfDataset ds)
Detailed Description
Models-3/EDSS Input/Output netcf format.
The Models-3/EDSS Input/Output Applications Programming Interface (I/O API) is the standard data access library for both NCSC's EDSS project and EPA's Models-3.
6/24/09: Modified to support multiple projection types of data by Qun He qunhe.nosp@m.@unc.nosp@m..edu and Alexis Zubrow azubr.nosp@m.ow@u.nosp@m.nc.ed.nosp@m.u added makePolarStereographicProjection, UTM, and modified latlon
09/2010 pless.nosp@m.el.t.nosp@m.odd@e.nosp@m.pa.g.nosp@m.ov add projections 7,8,9,10
Author
pless.nosp@m.el.t.nosp@m.odd@e.nosp@m.pa.g.nosp@m.ov
caron
See Also
http://www.baronams.com/products/ioapi/index.html
Definition at line 63 of file M3IOConvention.java.
Constructor & Destructor Documentation
ucar.nc2.dataset.conv.M3IOConvention.M3IOConvention ()
Definition at line 87 of file M3IOConvention.java.
Member Function Documentation
void ucar.nc2.dataset.conv.M3IOConvention.augmentDataset (NetcdfDataset ncd, CancelTask cancelTask)
Definition at line 91 of file M3IOConvention.java.
References ucar.nc2.dataset.conv.M3IOConvention.constructCoordAxes().
void ucar.nc2.dataset.conv.M3IOConvention.constructCoordAxes (NetcdfDataset ds) protected
Definition at line 103 of file M3IOConvention.java.
Referenced by ucar.nc2.dataset.conv.M3IOConvention.augmentDataset().
AxisType ucar.nc2.dataset.conv.M3IOConvention.getAxisType (NetcdfDataset ds, VariableEnhanced ve) protected
Definition at line 419 of file M3IOConvention.java.
static boolean ucar.nc2.dataset.conv.M3IOConvention.isMine (NetcdfFile ncfile) static
Do we think this is a M3IO file.
Parameters
ncfile the NetcdfFile to test
Returns
true if we think this is a M3IO file.
Definition at line 73 of file M3IOConvention.java.
Referenced by anl.verdi.loaders.NetcdfDatasetFactory.createModels3Datasets(), and anl.verdi.loaders.Models3Dataset.Models3Dataset().
void ucar.nc2.dataset.conv.M3IOConvention.makeCoordinateTransforms (NetcdfDataset ds) protected
Definition at line 444 of file M3IOConvention.java.
The documentation for this class was generated from the following file:
verdi_data_loaders/src/ucar/nc2/dataset/conv/M3IOConvention.java