VERDI: anl.verdi.area.target.OpenTargetWindow Class Reference
anl.verdi.area.target.OpenTargetWindow Class Reference
Public Member Functions
OpenTargetWindow (Frame fr, AreaFilePanel panel, String title, boolean state)
void nextAction ()
boolean doAction ()
Public Member Functions inherited from anl.verdi.area.WDTWizardWindow
WDTWizardWindow (Frame fr, String title, boolean state)
String[] getCardNames ()
String[] getCardTitles ()
String getTitleFor (String card)
Additional Inherited Members
Protected Member Functions inherited from anl.verdi.area.WDTWizardWindow
void showCard (CardChoice card)
Protected Attributes inherited from anl.verdi.area.WDTWizardWindow
String preTitle
Detailed Description
File Name:OpenTargetWindow.java Description: The class shows a window for selecting a target file
Version
March 2004
Author
Mary Ann Bitz
Argonne National Lab
Definition at line 24 of file OpenTargetWindow.java.
Constructor & Destructor Documentation
anl.verdi.area.target.OpenTargetWindow.OpenTargetWindow (Frame fr, AreaFilePanel panel, String title, boolean state)
Constructs a window to select a target file
Parameters
fr parent window
title the title of the window
state whether the window should be blocking
Definition at line 44 of file OpenTargetWindow.java.
Member Function Documentation
boolean anl.verdi.area.target.OpenTargetWindow.doAction ()
Called when the window is done
Definition at line 98 of file OpenTargetWindow.java.
References anl.verdi.area.target.ProjectionCard.getProjection(), and anl.verdi.area.target.ProjectionCard.nextAction().
void anl.verdi.area.target.OpenTargetWindow.nextAction ()
Move to the next panel
Definition at line 68 of file OpenTargetWindow.java.
References anl.verdi.area.target.TargetFileCard.nextAction().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/target/OpenTargetWindow.java