VERDI: anl.verdi.data.ExtendDataFrameAxis Class Reference
anl.verdi.data.ExtendDataFrameAxis Class Reference
Public Member Functions
int getArrayIndex ()
Public Member Functions inherited from anl.verdi.data.ExtendAxisRange
ExtendAxisRange (ExtendCoordAxis axis)
ExtendAxisRange (ExtendCoordAxis axis, int origin, int extent)
ExtendCoordAxis getAxis ()
Unit getUnits ()
boolean isCompatible (ExtendCoordAxis axis)
Object getValue (int index)
String getDescription ()
String getName ()
Range getRange ()
int getExtent ()
int getOrigin ()
AxisType getAxisType ()
Static Public Member Functions
static ExtendDataFrameAxis createDataFrameAxis (ExtendCoordAxis axis, int index)
static ExtendDataFrameAxis createDataFrameAxis (ExtendCoordAxis axis, int origin, int extent, int index)
static ExtendDataFrameAxis createDataFrameAxis (ExtendDataFrameAxis axis, int index)
Protected Member Functions
ExtendDataFrameAxis (ExtendCoordAxis axis, int index)
ExtendDataFrameAxis (ExtendCoordAxis axis, int origin, int extent, int index)
ExtendDataFrameAxis (ExtendDataFrameAxis axis, int index)
Additional Inherited Members
Protected Attributes inherited from anl.verdi.data.ExtendAxisRange
ExtendCoordAxis axis
Range range
Detailed Description
Definition at line 3 of file ExtendDataFrameAxis.java.
Constructor & Destructor Documentation
anl.verdi.data.ExtendDataFrameAxis.ExtendDataFrameAxis (ExtendCoordAxis axis, int index) protected
Creates a DataFrameAxis for the specified axis with origin and extent equal to that of the axis.
Parameters
axis the axis
index the array index of this axis
Definition at line 59 of file ExtendDataFrameAxis.java.
References anl.verdi.data.ExtendAxisRange.axis, anl.verdi.data.ExtendAxisRange.getExtent(), and anl.verdi.data.ExtendCoordAxis.getRange().
Referenced by anl.verdi.data.ExtendDataFrameAxis.createDataFrameAxis().
anl.verdi.data.ExtendDataFrameAxis.ExtendDataFrameAxis (ExtendCoordAxis axis, int origin, int extent, int index) protected
Creates a DataFrameAxis for the specified axis with the specified origin and extent.
Parameters
origin the origin of the range
extent the extent of the range
axis the axis
index the array index of this axis
Definition at line 71 of file ExtendDataFrameAxis.java.
anl.verdi.data.ExtendDataFrameAxis.ExtendDataFrameAxis (ExtendDataFrameAxis axis, int index) protected
Creates a DataFrameAxis from the specified axis and index. This DataFrameAxis will have the same origin and extent as the specified axis.
Parameters
axis the axis to create this DataFrameAxis from
index the array index of this axis
Definition at line 84 of file ExtendDataFrameAxis.java.
References anl.verdi.data.ExtendAxisRange.getExtent().
Member Function Documentation
static ExtendDataFrameAxis anl.verdi.data.ExtendDataFrameAxis.createDataFrameAxis (ExtendCoordAxis axis, int index) static
Creates a DataFrameAxis for the specified axis with origin and extent equal to that of the axis.
Parameters
axis the axis
index the array index of this axis
Returns
the created DataFrameAxis
Definition at line 14 of file ExtendDataFrameAxis.java.
References anl.verdi.data.ExtendDataFrameAxis.ExtendDataFrameAxis(), anl.verdi.data.ExtendCoordAxis.getAxisType(), and anl.verdi.data.AxisType.TIME.
static ExtendDataFrameAxis anl.verdi.data.ExtendDataFrameAxis.createDataFrameAxis (ExtendCoordAxis axis, int origin, int extent, int index) static
Creates a DataFrameAxis for the specified axis with the specified origin and extent.
Parameters
origin the origin of the range
extent the extent of the range
axis the axis
index the array index of this axis
Returns
the create axis.
Definition at line 31 of file ExtendDataFrameAxis.java.
References anl.verdi.data.ExtendDataFrameAxis.ExtendDataFrameAxis(), anl.verdi.data.ExtendCoordAxis.getAxisType(), and anl.verdi.data.AxisType.TIME.
static ExtendDataFrameAxis anl.verdi.data.ExtendDataFrameAxis.createDataFrameAxis (ExtendDataFrameAxis axis, int index) static
Creates a DataFrameAxis from the specified axis and index. This DataFrameAxis will have the same origin and extent as the specified axis.
Parameters
axis the axis to create this DataFrameAxis from
index the array index of this axis
Returns
the create axis
Definition at line 48 of file ExtendDataFrameAxis.java.
References anl.verdi.data.ExtendAxisRange.getExtent().
int anl.verdi.data.ExtendDataFrameAxis.getArrayIndex ()
Gets the index of the array dimension that corresponds to this axis.
Returns
the index of the array dimension that corresponds to this axis.
Definition at line 93 of file ExtendDataFrameAxis.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/data/ExtendDataFrameAxis.java