VERDI: anl.verdi.area.AreaFileListModel Class Reference
anl.verdi.area.AreaFileListModel Class Reference
Public Member Functions
void addAreaFileModelListener (AreaFileModelListener listener)
void removeAreaFileModelListener (AreaFileModelListener listener)
Object getElementAt (int index)
AreaFile getAreaFileAt (int index)
int getSize ()
Iterable< AreaFileListElement > elements ()
int addAreaFile (AreaFile areaFile)
void removeAreaFile (AreaFileListElement item)
void removeAreaFileAt (int index)
void clear ()
void addAll (List< AreaFileListElement > elements)
Detailed Description
Author
Mary Ann Bitz
Version
$Revision$ $Date$
Definition at line 13 of file AreaFileListModel.java.
Member Function Documentation
void anl.verdi.area.AreaFileListModel.addAll (List< AreaFileListElement > elements)
Definition at line 103 of file AreaFileListModel.java.
References anl.verdi.area.AreaFileListModel.elements().
int anl.verdi.area.AreaFileListModel.addAreaFile (AreaFile areaFile)
Definition at line 58 of file AreaFileListModel.java.
void anl.verdi.area.AreaFileListModel.addAreaFileModelListener (AreaFileModelListener listener)
Definition at line 22 of file AreaFileListModel.java.
void anl.verdi.area.AreaFileListModel.clear ()
Removes all the elements from this model.
Definition at line 97 of file AreaFileListModel.java.
Iterable<AreaFileListElement> anl.verdi.area.AreaFileListModel.elements ()
Definition at line 54 of file AreaFileListModel.java.
Referenced by anl.verdi.area.AreaFileListModel.addAll(), and anl.verdi.core.Project.getAreaFilesAsList().
AreaFile anl.verdi.area.AreaFileListModel.getAreaFileAt (int index)
Definition at line 34 of file AreaFileListModel.java.
Object anl.verdi.area.AreaFileListModel.getElementAt (int index)
Definition at line 30 of file AreaFileListModel.java.
int anl.verdi.area.AreaFileListModel.getSize ()
Definition at line 38 of file AreaFileListModel.java.
void anl.verdi.area.AreaFileListModel.removeAreaFile (AreaFileListElement item)
Definition at line 69 of file AreaFileListModel.java.
References anl.verdi.area.AreaFileListElement.getAreaFile().
void anl.verdi.area.AreaFileListModel.removeAreaFileAt (int index)
Definition at line 76 of file AreaFileListModel.java.
References anl.verdi.area.AreaFileListElement.getAreaFile().
void anl.verdi.area.AreaFileListModel.removeAreaFileModelListener (AreaFileModelListener listener)
Definition at line 26 of file AreaFileListModel.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/AreaFileListModel.java