VERDI: anl.verdi.plot.gui.VerticalCrossDialog Class Reference
anl.verdi.plot.gui.VerticalCrossDialog Class Reference
Public Member Functions
VerticalCrossDialog (Frame owner)
VerticalCrossDialog (Dialog owner)
boolean isCanceled ()
void init (Axes< DataFrameAxis > axes)
int getColumn ()
int getRow ()
boolean isXSelected ()
Detailed Description
Author
User #2
Definition at line 37 of file VerticalCrossDialog.java.
Constructor & Destructor Documentation
anl.verdi.plot.gui.VerticalCrossDialog.VerticalCrossDialog (Frame owner)
Definition at line 45 of file VerticalCrossDialog.java.
anl.verdi.plot.gui.VerticalCrossDialog.VerticalCrossDialog (Dialog owner)
Definition at line 52 of file VerticalCrossDialog.java.
Member Function Documentation
int anl.verdi.plot.gui.VerticalCrossDialog.getColumn ()
Definition at line 125 of file VerticalCrossDialog.java.
int anl.verdi.plot.gui.VerticalCrossDialog.getRow ()
Definition at line 130 of file VerticalCrossDialog.java.
void anl.verdi.plot.gui.VerticalCrossDialog.init (Axes< DataFrameAxis > axes)
Definition at line 104 of file VerticalCrossDialog.java.
References anl.verdi.data.AxisRange.getRange().
boolean anl.verdi.plot.gui.VerticalCrossDialog.isCanceled ()
Definition at line 100 of file VerticalCrossDialog.java.
Referenced by anl.verdi.plot.gui.VerticalCrossPlotCreator.doCreatePlot().
boolean anl.verdi.plot.gui.VerticalCrossDialog.isXSelected ()
Definition at line 134 of file VerticalCrossDialog.java.
Referenced by anl.verdi.plot.gui.VerticalCrossPlotCreator.doCreatePlot().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/gui/VerticalCrossDialog.java