VERDI: gov.epa.emvl.RemoteFileReader Class Reference
gov.epa.emvl.RemoteFileReader Class Reference
Public Member Functions
String getLocalCopyFileName ()
File getLocalCopyFile ()
void setVisible (final boolean visible)
RemoteFileReader (final String remoteHosts)
void actionPerformed (final ActionEvent event)
void mouseReleased (final MouseEvent event)
void mouseEntered (final MouseEvent unused_)
void mouseExited (final MouseEvent unused_)
void mouseClicked (final MouseEvent unused_)
void mousePressed (final MouseEvent unused_)
void valueChanged (final ListSelectionEvent event)
Static Public Member Functions
static void readRemoteHostNames (final String remoteHosts)
Static Public Attributes
static List< String > TEMP_REMOTE_FILE_LIST = new ArrayList<String>()
Protected Member Functions
void close ()
void finalize () throws Throwable
Detailed Description
Definition at line 59 of file RemoteFileReader.java.
Constructor & Destructor Documentation
gov.epa.emvl.RemoteFileReader.RemoteFileReader (final String remoteHosts)
Definition at line 184 of file RemoteFileReader.java.
References gov.epa.emvl.RemoteFileReader.readRemoteHostNames().
Member Function Documentation
void gov.epa.emvl.RemoteFileReader.actionPerformed (final ActionEvent event)
Definition at line 268 of file RemoteFileReader.java.
References gov.epa.emvl.RemoteFileReader.setVisible().
void gov.epa.emvl.RemoteFileReader.close () protected
Definition at line 136 of file RemoteFileReader.java.
Referenced by gov.epa.emvl.RemoteFileReader.finalize().
void gov.epa.emvl.RemoteFileReader.finalize () throws Throwable protected
Definition at line 149 of file RemoteFileReader.java.
References gov.epa.emvl.RemoteFileReader.close().
File gov.epa.emvl.RemoteFileReader.getLocalCopyFile ()
Definition at line 162 of file RemoteFileReader.java.
References gov.epa.emvl.RemoteFileReader.getLocalCopyFileName().
String gov.epa.emvl.RemoteFileReader.getLocalCopyFileName ()
Definition at line 154 of file RemoteFileReader.java.
References anl.verdi.util.Tools.getPropertyFile(), and anl.verdi.util.Tools.TEMP_DIR.
Referenced by gov.epa.emvl.RemoteFileReader.getLocalCopyFile().
void gov.epa.emvl.RemoteFileReader.mouseClicked (final MouseEvent unused_)
Definition at line 338 of file RemoteFileReader.java.
void gov.epa.emvl.RemoteFileReader.mouseEntered (final MouseEvent unused_)
Definition at line 336 of file RemoteFileReader.java.
void gov.epa.emvl.RemoteFileReader.mouseExited (final MouseEvent unused_)
Definition at line 337 of file RemoteFileReader.java.
void gov.epa.emvl.RemoteFileReader.mousePressed (final MouseEvent unused_)
Definition at line 339 of file RemoteFileReader.java.
void gov.epa.emvl.RemoteFileReader.mouseReleased (final MouseEvent event)
Definition at line 297 of file RemoteFileReader.java.
static void gov.epa.emvl.RemoteFileReader.readRemoteHostNames (final String remoteHosts) static
Definition at line 104 of file RemoteFileReader.java.
Referenced by gov.epa.emvl.RemoteFileReader.RemoteFileReader().
void gov.epa.emvl.RemoteFileReader.setVisible (final boolean visible)
Definition at line 168 of file RemoteFileReader.java.
Referenced by gov.epa.emvl.RemoteFileReader.actionPerformed().
void gov.epa.emvl.RemoteFileReader.valueChanged (final ListSelectionEvent event)
Definition at line 343 of file RemoteFileReader.java.
Member Data Documentation
List<String> gov.epa.emvl.RemoteFileReader.TEMP_REMOTE_FILE_LIST = new ArrayList<String>() static
Definition at line 62 of file RemoteFileReader.java.
Referenced by anl.verdi.core.VerdiApplication.exit().
The documentation for this class was generated from the following file:
verdi_core/src/gov/epa/emvl/RemoteFileReader.java