VERDI: anl.verdi.gui.DomainPanel Class Reference
anl.verdi.gui.DomainPanel Class Reference
Classes
class DomainPan
class DomainZoomer
class DomainZoomIn
class DomainZoomOut
class EditDomainWindow
class ProjectInfoWindow
Public Member Functions
DomainPanel ()
DomainPanel (MapContent context)
void setDomainValues (AbstractListElement element)
void editDomain ()
PGISCanvas getCanvas ()
void update ()
void loadData (URL url) throws Exception
Static Public Member Functions
static Cursor createCursor (ImageIcon icon, Point hotSpot, String name)
static Cursor createCursor (File imageInputFile, Point hotSpot, String name)
static void main (String[] args) throws Exception
Protected Member Functions
void addMapBackground (MapContent context)
FeatureLayer createLayer (URL url, File styleFile) throws IOException
Detailed Description
Author
User #2
Definition at line 96 of file DomainPanel.java.
Constructor & Destructor Documentation
anl.verdi.gui.DomainPanel.DomainPanel ()
Definition at line 116 of file DomainPanel.java.
Referenced by anl.verdi.gui.DomainPanel.main().
anl.verdi.gui.DomainPanel.DomainPanel (MapContent context)
Definition at line 129 of file DomainPanel.java.
References anl.verdi.gui.DomainPanel.editDomain().
Member Function Documentation
void anl.verdi.gui.DomainPanel.addMapBackground (MapContent context) protected
Definition at line 237 of file DomainPanel.java.
References anl.verdi.gui.DomainPanel.createLayer().
Referenced by anl.verdi.gui.DomainPanel.editDomain().
static Cursor anl.verdi.gui.DomainPanel.createCursor (ImageIcon icon, Point hotSpot, String name) static
Definition at line 376 of file DomainPanel.java.
static Cursor anl.verdi.gui.DomainPanel.createCursor (File imageInputFile, Point hotSpot, String name) static
Definition at line 395 of file DomainPanel.java.
FeatureLayer anl.verdi.gui.DomainPanel.createLayer (URL url, File styleFile) throws IOException protected
Definition at line 260 of file DomainPanel.java.
Referenced by anl.verdi.gui.DomainPanel.addMapBackground().
void anl.verdi.gui.DomainPanel.editDomain ()
Definition at line 441 of file DomainPanel.java.
References anl.verdi.gui.DomainPanel.addMapBackground(), anl.verdi.gui.AbstractListElement.getDataset(), and anl.verdi.gui.AbstractListElement.getXMax().
Referenced by anl.verdi.gui.DomainPanel.DomainPanel().
PGISCanvas anl.verdi.gui.DomainPanel.getCanvas ()
Definition at line 661 of file DomainPanel.java.
Referenced by anl.verdi.gui.DomainPanel.setDomainValues().
void anl.verdi.gui.DomainPanel.loadData (URL url) throws Exception
Definition at line 678 of file DomainPanel.java.
static void anl.verdi.gui.DomainPanel.main (String[] args) throws Exception static
Definition at line 735 of file DomainPanel.java.
References anl.verdi.gui.DomainPanel.DomainPanel().
void anl.verdi.gui.DomainPanel.setDomainValues (AbstractListElement element)
Definition at line 191 of file DomainPanel.java.
References anl.verdi.gui.DomainPanel.getCanvas(), anl.verdi.gui.AbstractListElement.getDataset(), anl.verdi.gui.AbstractListElement.getXMax(), anl.verdi.gui.AbstractListElement.getXMin(), anl.verdi.gui.AbstractListElement.getYMax(), and anl.verdi.gui.AbstractListElement.getYMin().
void anl.verdi.gui.DomainPanel.update ()
Definition at line 674 of file DomainPanel.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/gui/DomainPanel.java