VERDI: anl.verdi.plot.gui.Rubberband Class Reference
anl.verdi.plot.gui.Rubberband Class Reference
Public Member Functions
void drawLast (Graphics graphics)
void drawNext (Graphics graphics)
Rubberband ()
Rubberband (Component c)
void setActive (boolean b)
void setComponent (Component c)
boolean isActive ()
Point getAnchor ()
Point getStretched ()
Point getLast ()
Point getEnd ()
void anchor (Point p)
void stretch (Point p)
void end (Point p)
Rectangle getBounds ()
Rectangle lastBounds ()
Rectangle getAxisBounds ()
void setDataArea (Rectangle rect, float scaleX, float scaleY)
Protected Attributes
Point anchorPt = new Point(0, 0)
Point stretchedPt = new Point(0, 0)
Point lastPt = new Point(0, 0)
Point endPt = new Point(0, 0)
Detailed Description
Definition at line 17 of file Rubberband.java.
Constructor & Destructor Documentation
anl.verdi.plot.gui.Rubberband.Rubberband ()
Definition at line 48 of file Rubberband.java.
anl.verdi.plot.gui.Rubberband.Rubberband (Component c)
Definition at line 51 of file Rubberband.java.
References anl.verdi.plot.gui.Rubberband.setComponent().
Member Function Documentation
void anl.verdi.plot.gui.Rubberband.anchor (Point p)
Definition at line 107 of file Rubberband.java.
Referenced by anl.verdi.plot.gui.Rubberband.setComponent().
void anl.verdi.plot.gui.Rubberband.drawLast (Graphics graphics)
Definition at line 32 of file Rubberband.java.
References anl.verdi.plot.gui.Rubberband.anchorPt, anl.verdi.plot.gui.Rubberband.lastBounds(), and anl.verdi.plot.gui.Rubberband.lastPt.
Referenced by anl.verdi.plot.gui.Rubberband.end(), and anl.verdi.plot.gui.Rubberband.stretch().
void anl.verdi.plot.gui.Rubberband.drawNext (Graphics graphics)
Definition at line 40 of file Rubberband.java.
References anl.verdi.plot.gui.Rubberband.anchorPt, anl.verdi.plot.gui.Rubberband.getBounds(), and anl.verdi.plot.gui.Rubberband.stretchedPt.
Referenced by anl.verdi.plot.gui.Rubberband.stretch().
void anl.verdi.plot.gui.Rubberband.end (Point p)
Definition at line 135 of file Rubberband.java.
References anl.verdi.plot.gui.Rubberband.drawLast().
Referenced by anl.verdi.plot.gui.Rubberband.setComponent().
Point anl.verdi.plot.gui.Rubberband.getAnchor ()
Definition at line 91 of file Rubberband.java.
References anl.verdi.plot.gui.Rubberband.anchorPt.
Rectangle anl.verdi.plot.gui.Rubberband.getAxisBounds ()
Definition at line 163 of file Rubberband.java.
References anl.verdi.plot.gui.Rubberband.anchorPt, and anl.verdi.plot.gui.Rubberband.stretchedPt.
Rectangle anl.verdi.plot.gui.Rubberband.getBounds ()
Definition at line 149 of file Rubberband.java.
References anl.verdi.plot.gui.Rubberband.anchorPt, and anl.verdi.plot.gui.Rubberband.stretchedPt.
Referenced by anl.verdi.plot.gui.Rubberband.drawNext().
Point anl.verdi.plot.gui.Rubberband.getEnd ()
Definition at line 103 of file Rubberband.java.
References anl.verdi.plot.gui.Rubberband.endPt.
Point anl.verdi.plot.gui.Rubberband.getLast ()
Definition at line 99 of file Rubberband.java.
References anl.verdi.plot.gui.Rubberband.lastPt.
Point anl.verdi.plot.gui.Rubberband.getStretched ()
Definition at line 95 of file Rubberband.java.
References anl.verdi.plot.gui.Rubberband.stretchedPt.
boolean anl.verdi.plot.gui.Rubberband.isActive ()
Definition at line 87 of file Rubberband.java.
Referenced by anl.verdi.plot.gui.Rubberband.setComponent().
Rectangle anl.verdi.plot.gui.Rubberband.lastBounds ()
Definition at line 156 of file Rubberband.java.
References anl.verdi.plot.gui.Rubberband.anchorPt, and anl.verdi.plot.gui.Rubberband.lastPt.
Referenced by anl.verdi.plot.gui.Rubberband.drawLast().
void anl.verdi.plot.gui.Rubberband.setActive (boolean b)
Definition at line 55 of file Rubberband.java.
void anl.verdi.plot.gui.Rubberband.setComponent (Component c)
Definition at line 59 of file Rubberband.java.
References anl.verdi.plot.gui.Rubberband.anchor(), anl.verdi.plot.gui.Rubberband.end(), anl.verdi.plot.gui.Rubberband.isActive(), and anl.verdi.plot.gui.Rubberband.stretch().
Referenced by anl.verdi.plot.gui.Rubberband.Rubberband().
void anl.verdi.plot.gui.Rubberband.setDataArea (Rectangle rect, float scaleX, float scaleY)
Definition at line 176 of file Rubberband.java.
void anl.verdi.plot.gui.Rubberband.stretch (Point p)
Definition at line 115 of file Rubberband.java.
References anl.verdi.plot.gui.Rubberband.drawLast(), and anl.verdi.plot.gui.Rubberband.drawNext().
Referenced by anl.verdi.plot.gui.Rubberband.setComponent().
Member Data Documentation
Point anl.verdi.plot.gui.Rubberband.anchorPt = new Point(0, 0) protected
Definition at line 20 of file Rubberband.java.
Referenced by anl.verdi.plot.gui.Rubberband.drawLast(), anl.verdi.plot.gui.Rubberband.drawNext(), anl.verdi.plot.gui.Rubberband.getAnchor(), anl.verdi.plot.gui.Rubberband.getAxisBounds(), anl.verdi.plot.gui.Rubberband.getBounds(), and anl.verdi.plot.gui.Rubberband.lastBounds().
Point anl.verdi.plot.gui.Rubberband.endPt = new Point(0, 0) protected
Definition at line 23 of file Rubberband.java.
Referenced by anl.verdi.plot.gui.Rubberband.getEnd().
Point anl.verdi.plot.gui.Rubberband.lastPt = new Point(0, 0) protected
Definition at line 22 of file Rubberband.java.
Referenced by anl.verdi.plot.gui.Rubberband.drawLast(), anl.verdi.plot.gui.Rubberband.getLast(), and anl.verdi.plot.gui.Rubberband.lastBounds().
Point anl.verdi.plot.gui.Rubberband.stretchedPt = new Point(0, 0) protected
Definition at line 21 of file Rubberband.java.
Referenced by anl.verdi.plot.gui.Rubberband.drawNext(), anl.verdi.plot.gui.Rubberband.getAxisBounds(), anl.verdi.plot.gui.Rubberband.getBounds(), and anl.verdi.plot.gui.Rubberband.getStretched().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/gui/Rubberband.java