VERDI: anl.verdi.gui.RowHeader Class Reference
anl.verdi.gui.RowHeader Class Reference
Classes
class RowHeaderRenderer
Public Member Functions
RowHeader (List< String > headers, JTable table)
void setHeaderColor (int row, Color color)
void setHeaderColor (String label, Color color)
void unstitch (int[] assetList)
int[] deleteSelected ()
void addNamedRows (List names)
int[] deleteNamedRows (List names)
void deleteRows (int[] rows)
void addRow (String label)
void selectAll ()
void unselectAll ()
List getSelectedRowLabels ()
int[] getSelectedRows ()
String getLabel (int row)
List getRowLabels ()
Detailed Description
Version
$Revision$ $Date$
Author
Nick Collier
Definition at line 27 of file RowHeader.java.
Constructor & Destructor Documentation
anl.verdi.gui.RowHeader.RowHeader (List< String > headers, JTable table)
Definition at line 36 of file RowHeader.java.
Member Function Documentation
void anl.verdi.gui.RowHeader.addNamedRows (List names)
Definition at line 76 of file RowHeader.java.
void anl.verdi.gui.RowHeader.addRow (String label)
Definition at line 109 of file RowHeader.java.
int [] anl.verdi.gui.RowHeader.deleteNamedRows (List names)
Definition at line 82 of file RowHeader.java.
References anl.verdi.gui.RowHeader.deleteRows(), anl.verdi.gui.RowHeaderModel.getElementAt(), and anl.verdi.gui.RowHeaderModel.getSize().
void anl.verdi.gui.RowHeader.deleteRows (int[] rows)
Definition at line 99 of file RowHeader.java.
Referenced by anl.verdi.gui.RowHeader.deleteNamedRows(), and anl.verdi.gui.RowHeader.deleteSelected().
int [] anl.verdi.gui.RowHeader.deleteSelected ()
Definition at line 69 of file RowHeader.java.
References anl.verdi.gui.RowHeader.deleteRows().
String anl.verdi.gui.RowHeader.getLabel (int row)
Definition at line 148 of file RowHeader.java.
References anl.verdi.gui.RowHeaderModel.getElementAt().
List anl.verdi.gui.RowHeader.getRowLabels ()
Definition at line 153 of file RowHeader.java.
References anl.verdi.gui.RowHeaderModel.getElementAt().
List anl.verdi.gui.RowHeader.getSelectedRowLabels ()
Definition at line 121 of file RowHeader.java.
int [] anl.verdi.gui.RowHeader.getSelectedRows ()
Definition at line 134 of file RowHeader.java.
void anl.verdi.gui.RowHeader.selectAll ()
Definition at line 113 of file RowHeader.java.
void anl.verdi.gui.RowHeader.setHeaderColor (int row, Color color)
Definition at line 47 of file RowHeader.java.
References anl.verdi.gui.RowHeaderModel.getElementAt().
void anl.verdi.gui.RowHeader.setHeaderColor (String label, Color color)
Definition at line 52 of file RowHeader.java.
References anl.verdi.gui.RowHeaderModel.getElementAt(), and anl.verdi.gui.RowHeaderModel.getSize().
void anl.verdi.gui.RowHeader.unselectAll ()
Definition at line 117 of file RowHeader.java.
void anl.verdi.gui.RowHeader.unstitch (int[] assetList)
Definition at line 62 of file RowHeader.java.
References anl.verdi.gui.RowHeaderModel.getElementAt().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/gui/RowHeader.java