VERDI: anl.verdi.data.DataManager Class Reference
anl.verdi.data.DataManager Class Reference
Public Member Functions
DataManager (Collection< DataLoader > dataLoaders)
DataManager (PluginManager manager) throws PluginLifecycleException
List< Dataset > createDatasets (URL url) throws IOException
void replaceAliases (Map< Dataset, String > aliasMap)
DataReader getDataReader (Dataset set)
int getDatasetCount ()
Dataset getDataset (String alias)
String[] splitVarName (String variableName)
void closeDataset (String alias) throws IOException
void closeAllDatasets () throws IOException
Static Public Attributes
static List< Dataset > NULL_DATASETS = new ArrayList<Dataset>()
Detailed Description
Manages the loading of data and the creation of data sets.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 28 of file DataManager.java.
Constructor & Destructor Documentation
anl.verdi.data.DataManager.DataManager (Collection< DataLoader > dataLoaders)
Creates a DataManager that uses the specified DataLoaders to do the data loading.
Parameters
dataLoaders the data loaders to use
Definition at line 50 of file DataManager.java.
anl.verdi.data.DataManager.DataManager (PluginManager manager) throws PluginLifecycleException
Creates a DataManager that creates its data loaders via plugin extensions.
Parameters
manager the plugin manager to used to find the plugin extensions.
Exceptions
PluginLifecycleException on a plugin error
Definition at line 60 of file DataManager.java.
Member Function Documentation
void anl.verdi.data.DataManager.closeAllDatasets () throws IOException
Closes all the datasets managed by this manager and clears the list of datasets managed by the DatasetManager.
Exceptions
IOException if there is an error closing a dataset.
Definition at line 254 of file DataManager.java.
void anl.verdi.data.DataManager.closeDataset (String alias) throws IOException
Closes the specified dataset and removes it from the datasets managed by this manager.
Parameters
alias the alias of the dataset to close
Exceptions
IOException if there is an error closing the dataset.
Definition at line 242 of file DataManager.java.
References anl.verdi.util.AliasGenerator.clearAlias().
List<Dataset> anl.verdi.data.DataManager.createDatasets (URL url) throws IOException
Creates a Dataset from the data at the specified URL. This DataManager iterate through its collection of DataLoaders and use the first one that can handle the data at the specified URL to create the Dataset. It will also assign the Dataset an alias.
Parameters
url the url of the data
Returns
a Dataset created from the data at the specified URL. If no Dataset can be created the null object DataManager.NULL_DATASET will be returned.
Exceptions
Exception
Definition at line 97 of file DataManager.java.
References anl.verdi.data.DataManager.NULL_DATASETS.
DataReader anl.verdi.data.DataManager.getDataReader (Dataset set)
Creates a Dataset from the data at the specified URL. This DataManager iterate through its collection of DataLoaders and use the first one that can handle the data at the specified URL to create the Dataset. The dataset is assigned the specified alias. This method of creating a dataset should be only used when creating Datasets as part of loading a scenario file.
Parameters
url the url of the data
alias alias of the dataset.
Returns
a Dataset created from the data at the specified URL. If no Dataset can be created the null object DataManager.NULL_DATASET will be returned.
public List<Dataset> createDatasets(URL url, String alias) { for (DataLoader loader : dataLoaders) { if (loader.canHandle(url)) { try { List<Dataset> data = loader.createDatasets(url); for (Dataset dataset : data) { setLoaderMap.put(dataset, loader); dataset.setAlias(alias); aliasGenerator.markAliasUsed(alias); datasets.put(alias, dataset); } return data; } catch (IOException e) { Logger.warn("Error while creating a Dataset " + e.getMessage()); } } } return NULL_DATASETS; } Gets the datareader appropriate for reading the specified dataset.
Parameters
set the set that we want to read.
Returns
the datareader appropriate for reading the specified dataset.
Definition at line 199 of file DataManager.java.
Dataset anl.verdi.data.DataManager.getDataset (String alias)
Gets the dataset with the specified alias.
Parameters
alias the alias of the dataset to get.
Returns
the dataset with the specified alias.
Definition at line 218 of file DataManager.java.
int anl.verdi.data.DataManager.getDatasetCount ()
Gets the number of datasets currently loaded.
Returns
the number of datasets currently loaded.
Definition at line 208 of file DataManager.java.
Referenced by anl.verdi.core.VerdiApplication.openProject().
void anl.verdi.data.DataManager.replaceAliases (Map< Dataset, String > aliasMap)
Replaces the specified datasets current alias with the new one. This does not effect formulas in any way.
Parameters
aliasMap key is the dataset and value is the new alias.
Definition at line 145 of file DataManager.java.
String [] anl.verdi.data.DataManager.splitVarName (String variableName)
Splits a formula variable name into the dataset alias and variable name.
Parameters
variableName the name to split
Returns
a string array whose first element is the alias and whose second element is the unaliased variable name.
Definition at line 231 of file DataManager.java.
Member Data Documentation
List<Dataset> anl.verdi.data.DataManager.NULL_DATASETS = new ArrayList<Dataset>() static
Definition at line 33 of file DataManager.java.
Referenced by anl.verdi.data.DataManager.createDatasets(), anl.verdi.io.IO.load(), and anl.verdi.core.VerdiApplication.loadDataset().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/data/DataManager.java