VERDI: simphony.util.messages.StackTaskMessageListener Class Reference
simphony.util.messages.StackTaskMessageListener Class Reference
Public Member Functions
StackTaskMessageListener (TaskMessageCallback callback)
void messageReceived (MessageEvent arg0)
Public Member Functions inherited from simphony.util.messages.TaskMessageListener
TaskMessageListener ()
void messageReceived (MessageEvent arg0)
Protected Member Functions
synchronized void processTaskMessage (TaskMessage message)
Protected Member Functions inherited from simphony.util.messages.TaskMessageListener
abstract void processTaskMessage (TaskMessage message)
Detailed Description
Definition at line 7 of file StackTaskMessageListener.java.
Constructor & Destructor Documentation
simphony.util.messages.StackTaskMessageListener.StackTaskMessageListener (TaskMessageCallback callback)
Definition at line 15 of file StackTaskMessageListener.java.
Member Function Documentation
void simphony.util.messages.StackTaskMessageListener.messageReceived (MessageEvent event)
Called when a message was received in the MessageCenter.
Parameters
event the message event
Implements simphony.util.messages.MessageEventListener.
Definition at line 57 of file StackTaskMessageListener.java.
References simphony.util.messages.MessageEvent.getMessage(), and simphony.util.messages.StackTaskMessageListener.processTaskMessage().
synchronized void simphony.util.messages.StackTaskMessageListener.processTaskMessage (TaskMessage message) protected
Definition at line 19 of file StackTaskMessageListener.java.
References simphony.util.messages.TaskMessage.getStatus().
Referenced by simphony.util.messages.StackTaskMessageListener.messageReceived().
The documentation for this class was generated from the following file:
verdi_saf_core_runtime/src/simphony/util/messages/StackTaskMessageListener.java