VERDI: anl.verdi.loaders.AbstractNetcdfDataset Class Reference
anl.verdi.loaders.AbstractNetcdfDataset Class Reference abstract
Public Member Functions
int getIndexInURL ()
List< String > getVariableNames ()
Variable getVariable (String name)
Iterable< Axes< CoordAxis > > getAllCoordAxes ()
int getCoordAxesCount ()
Axes< CoordAxis > getCoordAxes ()
List< Variable > getVariables ()
void close () throws IOException
Public Member Functions inherited from anl.verdi.data.AbstractDataset
URL getURL ()
String getAlias ()
void setAlias (String alias)
List< String > getVariableNames ()
Variable getVariable (String name)
List< Variable > getVariables ()
Axes< CoordAxis > getCoordAxes ()
boolean hasTimeAxis ()
boolean hasXAxis ()
boolean hasYAxis ()
boolean hasZAxis ()
String getName ()
void close () throws IOException
boolean isObs ()
Public Member Functions inherited from anl.verdi.data.Dataset
DatasetMetadata getMetadata ()
int getNetcdfCovn ()
void setNetcdfConv (int conv)
Protected Member Functions
AbstractNetcdfDataset (URL url)
Protected Member Functions inherited from anl.verdi.data.AbstractDataset
AbstractDataset (URL url)
Protected Attributes
GridDataset gridDataset
List< Axes< CoordAxis > > axesList = null
Axes< CoordAxis > coordAxes
Protected Attributes inherited from anl.verdi.data.AbstractDataset
String alias = NULL_ALIAS
URL url
Static Protected Attributes
static Map
< ucar.nc2.constants.AxisType,
AxisType > types = new HashMap<ucar.nc2.constants.AxisType, AxisType>()
Additional Inherited Members
Static Public Attributes inherited from anl.verdi.data.Dataset
static final String NULL_ALIAS = "anl.verdi.data.DataSet.NULL_ALIAS"
static final int SINGLE_DATASET = -1
Detailed Description
Abstract Dataset implementation for those datasets that are read using the netcdf library.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 37 of file AbstractNetcdfDataset.java.
Constructor & Destructor Documentation
anl.verdi.loaders.AbstractNetcdfDataset.AbstractNetcdfDataset (URL url) protected
Creates an AbstractNetcdfDataset for the dataset at the specified url.
Parameters
url the url of the dataset
Definition at line 62 of file AbstractNetcdfDataset.java.
Member Function Documentation
void anl.verdi.loaders.AbstractNetcdfDataset.close () throws IOException
Closes this dataset. It will have to be recreated to be used again.
Implements anl.verdi.data.Dataset.
Definition at line 228 of file AbstractNetcdfDataset.java.
Iterable<Axes<CoordAxis> > anl.verdi.loaders.AbstractNetcdfDataset.getAllCoordAxes ()
Gets an iterable over all the Axes in this dataset.
Returns
an iterable over all the Axes in this dataset.
Definition at line 165 of file AbstractNetcdfDataset.java.
References anl.verdi.loaders.AbstractNetcdfDataset.axesList.
Axes<CoordAxis> anl.verdi.loaders.AbstractNetcdfDataset.getCoordAxes ()
Gets the coordindate Axes for this Dataset.
Returns
the coordindate Axes for this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 180 of file AbstractNetcdfDataset.java.
References anl.verdi.loaders.AbstractNetcdfDataset.coordAxes, anl.verdi.loaders.AbstractNetcdfDataset.gridDataset, and anl.verdi.data.AxisType.OTHER.
int anl.verdi.loaders.AbstractNetcdfDataset.getCoordAxesCount ()
Gets the number of coordinate Axes in this dataset.
Returns
the number of coordinate Axes in this dataset.
Definition at line 175 of file AbstractNetcdfDataset.java.
References anl.verdi.loaders.AbstractNetcdfDataset.axesList.
int anl.verdi.loaders.AbstractNetcdfDataset.getIndexInURL ()
Gets the index of this Dataset inside its URL, or Dataset.SINGLE_DATASET if it is the only dataset inside the URL.
Returns
the index of this Dataset inside its URL
Implements anl.verdi.data.Dataset.
Definition at line 74 of file AbstractNetcdfDataset.java.
Variable anl.verdi.loaders.AbstractNetcdfDataset.getVariable (String name)
Gets the named variable.
Parameters
name the name of the variable to get
Returns
the named variable
Implements anl.verdi.data.Dataset.
Definition at line 100 of file AbstractNetcdfDataset.java.
References anl.verdi.loaders.AbstractNetcdfDataset.getVariables().
List<String> anl.verdi.loaders.AbstractNetcdfDataset.getVariableNames ()
Gets the list of variable names in this Dataset.
Returns
the list of variable names in this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 84 of file AbstractNetcdfDataset.java.
References anl.verdi.loaders.AbstractNetcdfDataset.getVariables().
Referenced by anl.verdi.loaders.EnvelopeUtility.getReferencedEnvelope().
List<Variable> anl.verdi.loaders.AbstractNetcdfDataset.getVariables ()
Gets the list of variables in this Dataset.
Returns
the list of variables in this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 200 of file AbstractNetcdfDataset.java.
Referenced by anl.verdi.loaders.AbstractNetcdfDataset.getVariable(), and anl.verdi.loaders.AbstractNetcdfDataset.getVariableNames().
Member Data Documentation
List<Axes<CoordAxis> > anl.verdi.loaders.AbstractNetcdfDataset.axesList = null protected
Definition at line 52 of file AbstractNetcdfDataset.java.
Referenced by anl.verdi.loaders.AbstractNetcdfDataset.getAllCoordAxes(), and anl.verdi.loaders.AbstractNetcdfDataset.getCoordAxesCount().
Axes<CoordAxis> anl.verdi.loaders.AbstractNetcdfDataset.coordAxes protected
Definition at line 53 of file AbstractNetcdfDataset.java.
Referenced by anl.verdi.loaders.AbstractNetcdfDataset.getCoordAxes().
GridDataset anl.verdi.loaders.AbstractNetcdfDataset.gridDataset protected
Definition at line 51 of file AbstractNetcdfDataset.java.
Referenced by anl.verdi.loaders.AbstractNetcdfDataset.getCoordAxes(), anl.verdi.loaders.Models3Dataset.Models3Dataset(), and anl.verdi.loaders.WRFDataset.WRFDataset().
Map<ucar.nc2.constants.AxisType, AxisType> anl.verdi.loaders.AbstractNetcdfDataset.types = new HashMap<ucar.nc2.constants.AxisType, AxisType>() static protected
Definition at line 41 of file AbstractNetcdfDataset.java.
The documentation for this class was generated from the following file:
verdi_data_loaders/src/anl/verdi/loaders/AbstractNetcdfDataset.java