VERDI: anl.verdi.core.VerdiApplication Class Reference
anl.verdi.core.VerdiApplication Class Reference
Public Member Functions
boolean skipSplash ()
void setSkipSplash (boolean skipSplash)
VerdiApplication (DataManager manager)
VerdiGUI getGui ()
void init (VerdiGUI gui, Project project)
Project getProject ()
DataManager getDataManager ()
boolean exit ()
void openProject ()
void openProject (File file)
void saveProject ()
void saveProjectAs ()
void runBatchScript ()
void setCurrentScriptFile (File file)
DataFrame evaluateFormula (Formula.Type type)
DataFrame evaluateFormula (Formula.Type type, DateRange dateRange)
DataFrame evaluateFormula (String strFormula, Formula.Type type, DateRange dateRange)
void areaSelected (AreaSelectionEvent event)
void plotProbed (ProbeEvent event)
void loadDataset (File[] files) throws Exception
void loadAreaFile (File[] files)
void addDataset ()
void valueChanged (ListSelectionEvent e)
void datasetRemoved (Dataset set, DatasetListModel model)
void datasetAdded (Dataset set, DatasetListModel model)
FormulaListElement create (String strFormula)
void plotRequested (PlotRequest request)
void overlayRequested (OverlayRequest request)
MapContent getDomainPanelContext ()
void setDomainPanelContext (MapContent domainPanelContext)
void contentsChanged (ListDataEvent e)
void intervalAdded (ListDataEvent e)
void intervalRemoved (ListDataEvent e)
void animateTilePlots ()
void showHelp ()
Static Public Member Functions
static VerdiApplication getInstance ()
Detailed Description
Main verdi application facade.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 84 of file VerdiApplication.java.
Constructor & Destructor Documentation
anl.verdi.core.VerdiApplication.VerdiApplication (DataManager manager)
Definition at line 120 of file VerdiApplication.java.
Member Function Documentation
void anl.verdi.core.VerdiApplication.addDataset ()
Opens a dataset.
Definition at line 640 of file VerdiApplication.java.
References anl.verdi.core.VerdiApplication.loadDataset().
void anl.verdi.core.VerdiApplication.animateTilePlots ()
Definition at line 892 of file VerdiApplication.java.
References anl.verdi.core.VerdiGUI.getFrame().
void anl.verdi.core.VerdiApplication.areaSelected (AreaSelectionEvent event)
Called whenever an area in a plot is being selected.
Parameters
event contains the details of the area selection
Implements anl.verdi.plot.gui.PlotListener.
Definition at line 451 of file VerdiApplication.java.
void anl.verdi.core.VerdiApplication.contentsChanged (ListDataEvent e)
Definition at line 876 of file VerdiApplication.java.
FormulaListElement anl.verdi.core.VerdiApplication.create (String strFormula)
Validates the specified formula and displays the appropriate error messages if necessary.
Parameters
strFormula the formula to evaluate
Returns
true if the validation was a success otherwise false.
Implements anl.verdi.gui.FormulaElementCreator.
Definition at line 722 of file VerdiApplication.java.
void anl.verdi.core.VerdiApplication.datasetAdded (Dataset set, DatasetListModel model)
Called when the specified dataset has been added.
Parameters
set the added dataset
model the DatasetListModel from which the set was removed
Implements anl.verdi.gui.DatasetModelListener.
Definition at line 710 of file VerdiApplication.java.
void anl.verdi.core.VerdiApplication.datasetRemoved (Dataset set, DatasetListModel model)
Called when the specified dataset has been removed. This closes the dataset.
Parameters
set the removed dataset
model
Implements anl.verdi.gui.DatasetModelListener.
Definition at line 694 of file VerdiApplication.java.
DataFrame anl.verdi.core.VerdiApplication.evaluateFormula (Formula.Type type)
Evaluates the current formula and returns the result. If there is no current formula then returns null. Then will evaluate the formula against the date range calculated by resolving the various date constraints and trying to find the largest legal overlapping segment.
Parameters
type the type of formula (e.g. Tile, TimeSeries etc.) to evaluate
Returns
the result of the evaluation or null if the evaluation fails.
Definition at line 337 of file VerdiApplication.java.
Referenced by anl.verdi.core.VerdiApplication.overlayRequested().
DataFrame anl.verdi.core.VerdiApplication.evaluateFormula (Formula.Type type, DateRange dateRange)
Evaluates the current formula and returns the result. If there is no current formula then returns null. The evaluation will ignore the the date range calculated by resolving the various date constraints and trying to find the largest legal overlapping segment and use the passed-in parameter instead.
Parameters
type the type of formula (e.g. Tile, TimeSeries etc.) to evaluate
dateRange the dateRange to evaluate the formula against
Returns
the result of the evaluation or null if the evaluation fails
Definition at line 352 of file VerdiApplication.java.
References anl.verdi.gui.FormulaListElement.getDataset(), and anl.verdi.formula.FormulaValidator.UNITS_WARN.
DataFrame anl.verdi.core.VerdiApplication.evaluateFormula (String strFormula, Formula.Type type, DateRange dateRange)
Evaluates the current formula and returns the result. If there is no current formula then returns null. The evaluation will ignore the the date range calculated by resolving the various date constraints and trying to find the largest legal overlapping segment and use the passed in parameter instead.
Parameters
type the type of formula (e.g. Tile, TimeSeries etc.) to evaluate
dateRange the dateRange to evaluate the formula against
Returns
the result of the evaluation or null if the evaluation fails.
Definition at line 409 of file VerdiApplication.java.
References anl.verdi.formula.FormulaValidator.UNITS_WARN.
boolean anl.verdi.core.VerdiApplication.exit ()
Exits the application.
Returns
true if the exit was successful and the application should be terminated, otherwise false.
Definition at line 209 of file VerdiApplication.java.
References gov.epa.emvl.RemoteFileReader.TEMP_REMOTE_FILE_LIST.
DataManager anl.verdi.core.VerdiApplication.getDataManager ()
Gets the DataManager.
Returns
the DataManager.
Definition at line 198 of file VerdiApplication.java.
MapContent anl.verdi.core.VerdiApplication.getDomainPanelContext ()
Definition at line 865 of file VerdiApplication.java.
Referenced by anl.verdi.core.VerdiAppConfigurator.createLayout().
VerdiGUI anl.verdi.core.VerdiApplication.getGui ()
Definition at line 131 of file VerdiApplication.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.actionPerformed(), anl.verdi.commandline.ScriptHandler.constructMap(), and anl.verdi.plot.gui.FastTilePlot.showBusyCursor().
static VerdiApplication anl.verdi.core.VerdiApplication.getInstance () static
Definition at line 126 of file VerdiApplication.java.
Project anl.verdi.core.VerdiApplication.getProject ()
Gets the currently loaded Project.
Returns
the currently loaded Project.
Definition at line 188 of file VerdiApplication.java.
Referenced by anl.verdi.plot.gui.action.ArealInterpolation.actionPerformed(), anl.verdi.commandline.ScriptHandler.constructMap(), anl.verdi.plot.gui.DefaultPlotCreator.doCreatePlot(), anl.verdi.core.VerdiAppConfigurator.postWindowOpen(), anl.verdi.commandline.task.TimeSeriesPlotTask.run(), and anl.verdi.commandline.task.TilePlotTask.run().
void anl.verdi.core.VerdiApplication.init (VerdiGUI gui, Project project)
Definition at line 135 of file VerdiApplication.java.
References anl.verdi.util.Tools.DATASET_HOME, anl.verdi.core.VerdiGUI.getFrame(), simphony.util.messages.MessageEvent.getLevel(), simphony.util.messages.MessageEvent.getThrowable(), anl.verdi.util.Tools.PROJECT_HOME, and anl.verdi.util.Tools.SCRIPT_HOME.
void anl.verdi.core.VerdiApplication.intervalAdded (ListDataEvent e)
Definition at line 880 of file VerdiApplication.java.
void anl.verdi.core.VerdiApplication.intervalRemoved (ListDataEvent e)
Definition at line 886 of file VerdiApplication.java.
void anl.verdi.core.VerdiApplication.loadAreaFile (File[] files)
Loads the specified area files.
Parameters
files the area files to load
Definition at line 610 of file VerdiApplication.java.
References anl.verdi.core.Project.getAreaFilesAsList().
void anl.verdi.core.VerdiApplication.loadDataset (File[] files) throws Exception
Loads the specified datasets.
Parameters
files the datasets to load
Exceptions
IllegalFormulaException
Definition at line 567 of file VerdiApplication.java.
References anl.verdi.core.Project.getDatasetsAsList(), and anl.verdi.data.DataManager.NULL_DATASETS.
Referenced by anl.verdi.core.VerdiApplication.addDataset().
void anl.verdi.core.VerdiApplication.openProject ()
Opens a saved project – a set of datasets and formulas. This opens a file dialog.
Definition at line 238 of file VerdiApplication.java.
References anl.verdi.data.DataManager.getDatasetCount().
void anl.verdi.core.VerdiApplication.openProject (File file)
Opens the specified file as a project.
Parameters
file the project file
Definition at line 261 of file VerdiApplication.java.
void anl.verdi.core.VerdiApplication.overlayRequested (OverlayRequest request)
Notifies the PlotListener of a request to create an overlay for the sending plot. The listener should add the appropriate overlay evaluator to the request
Parameters
request the overlay request
Implements anl.verdi.plot.gui.PlotListener.
Definition at line 769 of file VerdiApplication.java.
References anl.verdi.core.VerdiApplication.evaluateFormula(), anl.verdi.core.Project.getDatasetsAsList(), and anl.verdi.core.VerdiGUI.getFrame().
void anl.verdi.core.VerdiApplication.plotProbed (ProbeEvent event)
Notifies this PlotListener when a plot has been probed.
Implements anl.verdi.plot.gui.PlotListener.
Definition at line 462 of file VerdiApplication.java.
References anl.verdi.plot.probe.ProbeCreator.createTableModel(), anl.verdi.plot.probe.ProbeEvent.getLogBase(), anl.verdi.plot.probe.ProbeCreator.getRangeAxisName(), and anl.verdi.plot.probe.ProbeEvent.getSource().
void anl.verdi.core.VerdiApplication.plotRequested (PlotRequest request)
Notifies this PlotListener of a request to create a plot fired from a another plot.
Parameters
request the request
Implements anl.verdi.plot.gui.PlotListener.
Definition at line 757 of file VerdiApplication.java.
void anl.verdi.core.VerdiApplication.runBatchScript ()
Choose the batch script file to run verdi and save the images.
Definition at line 313 of file VerdiApplication.java.
void anl.verdi.core.VerdiApplication.saveProject ()
Saves the current project – the current set of datasets and formulas.
Definition at line 277 of file VerdiApplication.java.
References anl.verdi.core.VerdiApplication.saveProjectAs().
void anl.verdi.core.VerdiApplication.saveProjectAs ()
Saves the current project as – the current set of datasets and formulas .
Definition at line 302 of file VerdiApplication.java.
Referenced by anl.verdi.core.VerdiApplication.saveProject().
void anl.verdi.core.VerdiApplication.setCurrentScriptFile (File file)
Definition at line 324 of file VerdiApplication.java.
void anl.verdi.core.VerdiApplication.setDomainPanelContext (MapContent domainPanelContext)
Definition at line 870 of file VerdiApplication.java.
void anl.verdi.core.VerdiApplication.setSkipSplash (boolean skipSplash)
Definition at line 116 of file VerdiApplication.java.
References anl.verdi.core.VerdiApplication.skipSplash().
void anl.verdi.core.VerdiApplication.showHelp ()
Shows help.
Definition at line 904 of file VerdiApplication.java.
boolean anl.verdi.core.VerdiApplication.skipSplash ()
Definition at line 112 of file VerdiApplication.java.
Referenced by anl.verdi.core.VerdiAppConfigurator.preWindowOpen(), and anl.verdi.core.VerdiApplication.setSkipSplash().
void anl.verdi.core.VerdiApplication.valueChanged (ListSelectionEvent e)
// 2014 appears to never be used Opens area files. Called whenever a formula is selected.
Parameters
e the event that characterizes the change.
Definition at line 669 of file VerdiApplication.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/core/VerdiApplication.java