VERDI: ucar.nc2.geotiff.GeotiffWriterUnc Class Reference
ucar.nc2.geotiff.GeotiffWriterUnc Class Reference
Public Member Functions
GeotiffWriterUnc (String fileOut)
void writeGrid (GridDataset dataset, GridDatatype grid, Array data, boolean greyScale) throws IOException
void writeGrid (String fileName, String gridName, int time, int layer, boolean greyScale, LatLonRect pt) throws IOException
Array getYXDataInBox (Array data, int x1, int x2, int y1, int y2) throws java.io.IOException
void writeGrid (GridDatatype grid, Array data, boolean greyScale, double xStart, double yStart, double xInc, double yInc, int imageNumber) throws IOException
void close () throws IOException
void setResolution_unit (short resolution_unit)
short getResolution_unit ()
void setResolution_x (int resolution_x)
long getResolution_x ()
void setResolution_y (int resolution_y)
long getResolution_y ()
Static Public Member Functions
static void main (String args[]) throws IOException
Detailed Description
Author
caron, yuan
Version
Revision:
3
Date:
006-07-12 21:50:51Z
Definition at line 49 of file GeotiffWriterUnc.java.
Constructor & Destructor Documentation
ucar.nc2.geotiff.GeotiffWriterUnc.GeotiffWriterUnc (String fileOut)
Geotiff writer.
Parameters
fileOut name of output file.
Definition at line 69 of file GeotiffWriterUnc.java.
Referenced by ucar.nc2.geotiff.GeotiffWriterUnc.main().
Member Function Documentation
void ucar.nc2.geotiff.GeotiffWriterUnc.close () throws IOException
Definition at line 416 of file GeotiffWriterUnc.java.
short ucar.nc2.geotiff.GeotiffWriterUnc.getResolution_unit ()
Definition at line 718 of file GeotiffWriterUnc.java.
long ucar.nc2.geotiff.GeotiffWriterUnc.getResolution_x ()
Definition at line 726 of file GeotiffWriterUnc.java.
long ucar.nc2.geotiff.GeotiffWriterUnc.getResolution_y ()
Definition at line 734 of file GeotiffWriterUnc.java.
Array ucar.nc2.geotiff.GeotiffWriterUnc.getYXDataInBox (Array data, int x1, int x2, int y1, int y2) throws java.io.IOException
Definition at line 247 of file GeotiffWriterUnc.java.
Referenced by ucar.nc2.geotiff.GeotiffWriterUnc.writeGrid().
static void ucar.nc2.geotiff.GeotiffWriterUnc.main (String args[]) throws IOException static
test
Definition at line 690 of file GeotiffWriterUnc.java.
References ucar.nc2.geotiff.GeotiffWriterUnc.GeotiffWriterUnc().
void ucar.nc2.geotiff.GeotiffWriterUnc.setResolution_unit (short resolution_unit)
Definition at line 714 of file GeotiffWriterUnc.java.
void ucar.nc2.geotiff.GeotiffWriterUnc.setResolution_x (int resolution_x)
Definition at line 722 of file GeotiffWriterUnc.java.
void ucar.nc2.geotiff.GeotiffWriterUnc.setResolution_y (int resolution_y)
Definition at line 730 of file GeotiffWriterUnc.java.
void ucar.nc2.geotiff.GeotiffWriterUnc.writeGrid (GridDataset dataset, GridDatatype grid, Array data, boolean greyScale) throws IOException
Write Grid data to the geotiff file.
Parameters
dataset
grid
data 2D array in YX order
greyScale if true, write greyScale image, else dataSample.
Exceptions
IOException
Definition at line 85 of file GeotiffWriterUnc.java.
Referenced by ucar.nc2.geotiff.GeotiffWriterUnc.writeGrid().
void ucar.nc2.geotiff.GeotiffWriterUnc.writeGrid (String fileName, String gridName, int time, int layer, boolean greyScale, LatLonRect pt) throws IOException
Definition at line 126 of file GeotiffWriterUnc.java.
References ucar.nc2.geotiff.GeotiffWriterUnc.getYXDataInBox(), and ucar.nc2.geotiff.GeotiffWriterUnc.writeGrid().
void ucar.nc2.geotiff.GeotiffWriterUnc.writeGrid (GridDatatype grid, Array data, boolean greyScale, double xStart, double yStart, double xInc, double yInc, int imageNumber) throws IOException
Write Grid data to the geotiff file. Grid currently must:
have a 1D X and Y coordinate axes.
be lat/lon or Lambert Conformal Projection
be equally spaced
Parameters
grid original grid
data 2D array in YX order
greyScale if true, write greyScale image, else dataSample.
xStart
yStart
xInc
yInc
imageNumber
Exceptions
IOException
IllegalArgumentException if above assumptions not valid
Definition at line 299 of file GeotiffWriterUnc.java.
The documentation for this class was generated from the following file:
verdi_data_loaders/src/ucar/nc2/geotiff/GeotiffWriterUnc.java