VERDI: org.libtiff.jai.codec.XTIFFTileCodecImpl Class Reference
org.libtiff.jai.codec.XTIFFTileCodecImpl Class Reference abstract
Public Member Functions
abstract void register ()
abstract XTIFFTileCodec create ()
boolean canEncode ()
void initializeDecoding ()
void initializeEncoding ()
abstract void decodeTilePixels (byte[] bpixels, Rectangle rect, byte[] pixels)
abstract void decodeTilePixels (byte[] bpixels, Rectangle rect, short[] pixels)
int encodeTilePixels (int[] pixels, Rectangle rect, byte[] bpixels)
XTIFFTileCodecImpl ()
void initialize ()
void register (int comp)
int getCompression ()
XTIFFTileCodec create (XTIFFEncodeParam param) throws IOException
int encode (RenderedImage img, Rectangle rect, byte[] bpixels)
int getCompressedTileSize (RenderedImage im)
XTIFFTileCodec create (XTIFFDecodeParam param) throws IOException
WritableRaster decode (RenderedImage img, Rectangle newRect, byte[] bpixels)
Protected Member Functions
long getLongField (int fld)
void setupSourceImage (RenderedImage img)
void initialize (XTIFFEncodeParam param) throws IOException
void setupBufferForEncoding ()
void getTilePixels (Rectangle rect)
void initialize (XTIFFDecodeParam param) throws IOException
void setupBufferForDecoding ()
void decodeColor (Rectangle newRect)
void decodeTilePixels (byte[] bpixels, Rectangle newRect)
WritableRaster setTilePixels (Rectangle rect)
void unpackShorts (byte byteArray[], short output[], int shortCount)
void decodeColor (byte[] bpix, short[] sdata, Rectangle newRect)
void decodeColor (short[] spix, short[] sdata, Rectangle newRect)
void decodeColor (byte[] bpix, byte[] bdata, Rectangle newRect)
Protected Attributes
XTIFFDirectory directory = null
RenderedImage image = null
int minY
int minX
int width
int length
int numBands
int tileLength
int tileWidth
int compression
SampleModel sampleModel
int[] sampleSize
char[] bitsPerSample
char[] colormap = null
XTIFFEncodeParam encodeParam = null
boolean isTiled
XTIFFDecodeParam decodeParam = null
boolean decodePaletteAsShorts = false
int unitsInThisTile
byte _bdata [] = null
short _sdata [] = null
byte[] bpixvals = null
short[] spixvals = null
DataBuffer buffer = null
int dataType
int image_type
Detailed Description
Provides a base class for writing TIFF tile codecs, to be registered with the XTIFFDirectory. This codec allows for both decoding and (optionally) encoding of tiles, and also handles the colorspace conversion in decoding.
At the minimum you will need to implement the two methods decodeTilePixels() for byte and short data, as well as the methods register() and create(). If your decoder requires additional parameters from the tags, set them up in initializeDecoding(), and initializeEncoding() for encoding.
To implement encoding, you must override the canEncode() method to return true, and implement encodeTilePixels().
Author
Niles Ritter
See Also
XTIFFTileCodec
Definition at line 37 of file XTIFFTileCodecImpl.java.
Constructor & Destructor Documentation
org.libtiff.jai.codec.XTIFFTileCodecImpl.XTIFFTileCodecImpl ()
The empty constructor.
Definition at line 141 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.create().
Member Function Documentation
boolean org.libtiff.jai.codec.XTIFFTileCodecImpl.canEncode ()
Indicate whether this codec can encode data. Override to return true only if your codec implments encoding.
Definition at line 62 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize().
abstract XTIFFTileCodec org.libtiff.jai.codec.XTIFFTileCodecImpl.create () abstract
Implement this to return the corresponding empty codec object.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.create().
XTIFFTileCodec org.libtiff.jai.codec.XTIFFTileCodecImpl.create (XTIFFEncodeParam param) throws IOException
The method for creating an encoder from the XTIFFEncodeParam information.
Implements org.libtiff.jai.codec.XTIFFTileCodec.
Definition at line 240 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.create(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.XTIFFTileCodecImpl().
XTIFFTileCodec org.libtiff.jai.codec.XTIFFTileCodecImpl.create (XTIFFDecodeParam param) throws IOException
The standard decoder creation method
Implements org.libtiff.jai.codec.XTIFFTileCodec.
Definition at line 348 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.create(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.XTIFFTileCodecImpl().
WritableRaster org.libtiff.jai.codec.XTIFFTileCodecImpl.decode (RenderedImage img, Rectangle newRect, byte[] bpixels)
Decode a rectangle of data stored in bpixels into a raster tile. Usually you will not need to override this, but instead implement the decodeTilePixels methods.
Implements org.libtiff.jai.codec.XTIFFTileCodec.
Definition at line 398 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor(), org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeTilePixels(), org.libtiff.jai.codec.XTIFFTileCodecImpl.image, org.libtiff.jai.codec.XTIFFTileCodecImpl.numBands, org.libtiff.jai.codec.XTIFFTileCodecImpl.setTilePixels(), org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForDecoding(), org.libtiff.jai.codec.XTIFFTileCodecImpl.setupSourceImage(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.unitsInThisTile.
void org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor (Rectangle newRect) protected
Postprocess the uncompressed color data into the appropriate display color model. This implementation Does a number of things:
For RGB color, reverse to BGR which apparently is faster for Java 2D display
For one-bit WHITE_IS_ZERO data, flip the values so that they will look correct
If the decodePaletteAsShorts flag is true then unpack the bits and apply the lookup table, as 16-bit lookup is not supported in JAI.
Override this if you have other color types.
See Also
XTIFFDecodeParam
Definition at line 433 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl._bdata, org.libtiff.jai.codec.XTIFFTileCodecImpl._sdata, org.libtiff.jai.codec.XTIFFTileCodecImpl.bpixvals, org.libtiff.jai.codec.XTIFFTileCodecImpl.dataType, and org.libtiff.jai.codec.XTIFFTileCodecImpl.spixvals.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decode().
void org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor (byte[] bpix, short[] sdata, Rectangle newRect) protected
Decode short pixel data, or interpret palette data as short from byte.
Definition at line 507 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.bitsPerSample, org.libtiff.jai.codec.XTIFFTileCodecImpl.colormap, org.libtiff.jai.util.JaiI18N.getString(), org.libtiff.jai.codec.XTIFFTileCodecImpl.image_type, and org.libtiff.jai.codec.XTIFFTileCodecImpl.unitsInThisTile.
void org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor (short[] spix, short[] sdata, Rectangle newRect) protected
Decode short color data, or interpret palette data as short.
Definition at line 585 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.colormap, org.libtiff.jai.codec.XTIFFTileCodecImpl.dataType, org.libtiff.jai.codec.XTIFFTileCodecImpl.decodePaletteAsShorts, org.libtiff.jai.codec.XTIFFTileCodecImpl.image_type, org.libtiff.jai.codec.XTIFF.TYPE_GREYSCALE_WHITE_IS_ZERO, and org.libtiff.jai.codec.XTIFFTileCodecImpl.unitsInThisTile.
void org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor (byte[] bpix, byte[] bdata, Rectangle newRect) protected
Decode byte color data
Definition at line 709 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.bitsPerSample, org.libtiff.jai.codec.XTIFFTileCodecImpl.image_type, and org.libtiff.jai.codec.XTIFFTileCodecImpl.unitsInThisTile.
abstract void org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeTilePixels (byte[] bpixels, Rectangle rect, byte[] pixels) abstract
decode bpixel byte array of data into pixels, packed for 1,2,4 8 bit pixels. Must implment this.
Parameters
bpixels the byte array of compressed input data
rect the rectangular shape of the target pixels
pixels the target decompressed pixels.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decode(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeTilePixels().
abstract void org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeTilePixels (byte[] bpixels, Rectangle rect, short[] pixels) abstract
decode bpixel byte array of data into pixels, packed for 16 bit pixels. Must implment this.
Parameters
bpixels the byte array of compressed input data
rect the rectangular shape of the target pixels
pixels the target decompressed pixels.
void org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeTilePixels (byte[] bpixels, Rectangle newRect) protected
Decode a tile of data into either byte or short pixel buffers. Override this if you have other buffer types (e.g. int)
Definition at line 451 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.bpixvals, org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeTilePixels(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.spixvals.
int org.libtiff.jai.codec.XTIFFTileCodecImpl.encode (RenderedImage img, Rectangle rect, byte[] bpixels)
Encode the data into buffer and return byte count Normally you will not need to override this method, but instead implement the encodeTilePixels() method.
Implements org.libtiff.jai.codec.XTIFFTileCodec.
Definition at line 260 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.encodeTilePixels(), org.libtiff.jai.codec.XTIFFTileCodecImpl.getTilePixels(), org.libtiff.jai.codec.XTIFFTileCodecImpl.image, org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForEncoding(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupSourceImage().
int org.libtiff.jai.codec.XTIFFTileCodecImpl.encodeTilePixels (int[] pixels, Rectangle rect, byte[] bpixels)
encode the tile in pixels into bpixels and return the byte size of the compressed data. Override this method if canEncode() = true;
Parameters
pixels input pixels
rect the array dimensions of samples
bpixels the target array of compressed byte data
Definition at line 115 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.encode().
int org.libtiff.jai.codec.XTIFFTileCodecImpl.getCompressedTileSize (RenderedImage im)
If derived classes can make a better estimate for the maximum size of a compressed tile, they should override this, which assumes conservatively that it won't be worse than twice the original size.
Parameters
im the rendered image containing the image data
Implements org.libtiff.jai.codec.XTIFFTileCodec.
Definition at line 322 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.numBands, org.libtiff.jai.codec.XTIFFTileCodecImpl.sampleModel, org.libtiff.jai.codec.XTIFFTileCodecImpl.sampleSize, org.libtiff.jai.codec.XTIFFTileCodecImpl.tileLength, and org.libtiff.jai.codec.XTIFFTileCodecImpl.tileWidth.
int org.libtiff.jai.codec.XTIFFTileCodecImpl.getCompression ()
Returns the TIFF compression type
Implements org.libtiff.jai.codec.XTIFFTileCodec.
Definition at line 225 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.compression.
long org.libtiff.jai.codec.XTIFFTileCodecImpl.getLongField (int fld) protected
A common utility method for accessing the XTIFFFields in the current image directory.
Definition at line 186 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize().
void org.libtiff.jai.codec.XTIFFTileCodecImpl.getTilePixels (Rectangle rect) protected
Get the portion of tile fitting into buffer. You probably won't need to override this.
Parameters
rect the region to extract from image.
Definition at line 305 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.encode().
void org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize ()
The method for initializing information common to both encoder and decoder.
Definition at line 147 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.bitsPerSample, org.libtiff.jai.codec.XTIFFTileCodecImpl.colormap, org.libtiff.jai.codec.XTIFFTileCodecImpl.compression, org.libtiff.jai.codec.XTIFF.COMPRESSION_NONE, org.libtiff.jai.codec.XTIFFTileCodecImpl.getLongField(), org.libtiff.jai.codec.XTIFFTileCodecImpl.image_type, org.libtiff.jai.codec.XTIFFTileCodecImpl.isTiled, org.libtiff.jai.codec.XTIFFTileCodecImpl.length, org.libtiff.jai.codec.XTIFF.TIFFTAG_BITS_PER_SAMPLE, org.libtiff.jai.codec.XTIFF.TIFFTAG_COLORMAP, org.libtiff.jai.codec.XTIFF.TIFFTAG_COMPRESSION, org.libtiff.jai.codec.XTIFF.TIFFTAG_IMAGE_LENGTH, org.libtiff.jai.codec.XTIFF.TIFFTAG_IMAGE_WIDTH, org.libtiff.jai.codec.XTIFF.TIFFTAG_ROWS_PER_STRIP, org.libtiff.jai.codec.XTIFF.TIFFTAG_TILE_LENGTH, org.libtiff.jai.codec.XTIFF.TIFFTAG_TILE_WIDTH, org.libtiff.jai.codec.XTIFFTileCodecImpl.tileLength, org.libtiff.jai.codec.XTIFFTileCodecImpl.tileWidth, and org.libtiff.jai.codec.XTIFFTileCodecImpl.width.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize().
void org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize (XTIFFEncodeParam param) throws IOException protected
Definition at line 246 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.canEncode(), org.libtiff.jai.codec.XTIFFTileCodecImpl.directory, org.libtiff.jai.codec.XTIFFTileCodecImpl.encodeParam, org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.initializeEncoding().
void org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize (XTIFFDecodeParam param) throws IOException protected
Definition at line 354 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.decodePaletteAsShorts, org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeParam, org.libtiff.jai.codec.XTIFFTileCodecImpl.directory, org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.initializeDecoding().
void org.libtiff.jai.codec.XTIFFTileCodecImpl.initializeDecoding ()
The initialization method particular to decoding. Extend for whatever compression-specific information or parameters is needed. The decoding parameter has already been assigned at this point, as well as the XTIFFDirectory parsed from the input stream, and so all XTIFFFields are available.
Definition at line 73 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize().
void org.libtiff.jai.codec.XTIFFTileCodecImpl.initializeEncoding ()
The initialization method particular to encoding. Extend for whatever compression-specific information or parameters is needed. The decoding parameter has already been assigned at this point, as well as the XTIFFDirectory parsed from the input stream, and so all XTIFFFields are available.
Definition at line 82 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize().
abstract void org.libtiff.jai.codec.XTIFFTileCodecImpl.register () abstract
Registration method. Must be implemented by the extended class to register itself with the XTIFFDirectory for all compression codes it supports (e.g Fax codec supports 3 codes).
See Also
XTIFFDirectory
Implements org.libtiff.jai.codec.XTIFFTileCodec.
void org.libtiff.jai.codec.XTIFFTileCodecImpl.register (int comp)
This method may be used by the implementations register() method to register itself with the XTIFFDirectory.
See Also
XTIFFDirectory
Definition at line 200 of file XTIFFTileCodecImpl.java.
WritableRaster org.libtiff.jai.codec.XTIFFTileCodecImpl.setTilePixels (Rectangle rect) protected
Take the values from the buffer and store them in a WritableRaster object.
Definition at line 464 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.buffer, and org.libtiff.jai.codec.XTIFFTileCodecImpl.sampleModel.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decode().
void org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForDecoding () protected
One-time setup for encoding. Some configurations require a temp array for unpacking 16-bit palette data.
Definition at line 366 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl._bdata, org.libtiff.jai.codec.XTIFFTileCodecImpl._sdata, org.libtiff.jai.codec.XTIFFTileCodecImpl.bitsPerSample, org.libtiff.jai.codec.XTIFFTileCodecImpl.bpixvals, org.libtiff.jai.codec.XTIFFTileCodecImpl.buffer, org.libtiff.jai.codec.XTIFFTileCodecImpl.dataType, org.libtiff.jai.codec.XTIFFTileCodecImpl.decodePaletteAsShorts, and org.libtiff.jai.codec.XTIFFTileCodecImpl.spixvals.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decode().
void org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForEncoding () protected
One-time setup for encoding
Definition at line 276 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.image, org.libtiff.jai.codec.XTIFFTileCodecImpl.isTiled, org.libtiff.jai.codec.XTIFFTileCodecImpl.length, org.libtiff.jai.codec.XTIFFTileCodecImpl.numBands, org.libtiff.jai.codec.XTIFFTileCodecImpl.tileLength, org.libtiff.jai.codec.XTIFFTileCodecImpl.tileWidth, and org.libtiff.jai.codec.XTIFFTileCodecImpl.width.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.encode().
void org.libtiff.jai.codec.XTIFFTileCodecImpl.setupSourceImage (RenderedImage img) protected
One-time common image parameter setup
Parameters
img the source image that will be encoded into a TIFF formatted stream, or the TIFF image from which Raster tiles will be decoded.
Definition at line 210 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.image, org.libtiff.jai.codec.XTIFFTileCodecImpl.minX, org.libtiff.jai.codec.XTIFFTileCodecImpl.minY, org.libtiff.jai.codec.XTIFFTileCodecImpl.numBands, org.libtiff.jai.codec.XTIFFTileCodecImpl.sampleModel, and org.libtiff.jai.codec.XTIFFTileCodecImpl.sampleSize.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decode(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.encode().
void org.libtiff.jai.codec.XTIFFTileCodecImpl.unpackShorts (byte byteArray[], short output[], int shortCount) protected
A useful Method to interpret a byte array as shorts. Method depends on whether the bytes are stored in a big endian or little endian format.
Definition at line 475 of file XTIFFTileCodecImpl.java.
References org.libtiff.jai.codec.XTIFFTileCodecImpl.directory.
Referenced by org.libtiff.jai.codecimpl.XTIFFPackTileCodec.decodeTilePixels(), org.libtiff.jai.codecimpl.XTIFFLZWTileCodec.decodeTilePixels(), and org.libtiff.jai.codecimpl.XTIFFUncompTileCodec.decodeTilePixels().
Member Data Documentation
byte org.libtiff.jai.codec.XTIFFTileCodecImpl._bdata[] = null protected
Definition at line 337 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForDecoding().
short org.libtiff.jai.codec.XTIFFTileCodecImpl._sdata[] = null protected
Definition at line 338 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForDecoding().
char [] org.libtiff.jai.codec.XTIFFTileCodecImpl.bitsPerSample protected
Definition at line 135 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor(), org.libtiff.jai.codecimpl.XTIFFPackTileCodec.decodeTilePixels(), org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize(), org.libtiff.jai.codecimpl.XTIFFLZWTileCodec.initializeDecoding(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForDecoding().
byte [] org.libtiff.jai.codec.XTIFFTileCodecImpl.bpixvals = null protected
Definition at line 339 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor(), org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeTilePixels(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForDecoding().
DataBuffer org.libtiff.jai.codec.XTIFFTileCodecImpl.buffer = null protected
Definition at line 341 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.setTilePixels(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForDecoding().
char [] org.libtiff.jai.codec.XTIFFTileCodecImpl.colormap = null protected
Definition at line 136 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize().
int org.libtiff.jai.codec.XTIFFTileCodecImpl.compression protected
Definition at line 132 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codecimpl.XTIFFFaxTileCodec.decodeTilePixels(), org.libtiff.jai.codec.XTIFFTileCodecImpl.getCompression(), org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize(), and org.libtiff.jai.codecimpl.XTIFFFaxTileCodec.initializeDecoding().
int org.libtiff.jai.codec.XTIFFTileCodecImpl.dataType protected
Definition at line 342 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForDecoding().
boolean org.libtiff.jai.codec.XTIFFTileCodecImpl.decodePaletteAsShorts = false protected
Definition at line 335 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor(), org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForDecoding().
XTIFFDecodeParam org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeParam = null protected
Definition at line 334 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize().
XTIFFDirectory org.libtiff.jai.codec.XTIFFTileCodecImpl.directory = null protected
Definition at line 123 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.unpackShorts().
XTIFFEncodeParam org.libtiff.jai.codec.XTIFFTileCodecImpl.encodeParam = null protected
Definition at line 233 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize().
RenderedImage org.libtiff.jai.codec.XTIFFTileCodecImpl.image = null protected
Definition at line 124 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decode(), org.libtiff.jai.codec.XTIFFTileCodecImpl.encode(), org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForEncoding(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupSourceImage().
int org.libtiff.jai.codec.XTIFFTileCodecImpl.image_type protected
Definition at line 343 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize().
boolean org.libtiff.jai.codec.XTIFFTileCodecImpl.isTiled protected
Definition at line 235 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForEncoding().
int org.libtiff.jai.codec.XTIFFTileCodecImpl.length protected
Definition at line 128 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForEncoding().
int org.libtiff.jai.codec.XTIFFTileCodecImpl.minX protected
Definition at line 126 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.setupSourceImage().
int org.libtiff.jai.codec.XTIFFTileCodecImpl.minY protected
Definition at line 125 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.setupSourceImage().
int org.libtiff.jai.codec.XTIFFTileCodecImpl.numBands protected
Definition at line 129 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decode(), org.libtiff.jai.codecimpl.XTIFFUncompTileCodec.encodeTilePixels(), org.libtiff.jai.codec.XTIFFTileCodecImpl.getCompressedTileSize(), org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForEncoding(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupSourceImage().
SampleModel org.libtiff.jai.codec.XTIFFTileCodecImpl.sampleModel protected
Definition at line 133 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.getCompressedTileSize(), org.libtiff.jai.codec.XTIFFTileCodecImpl.setTilePixels(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupSourceImage().
int [] org.libtiff.jai.codec.XTIFFTileCodecImpl.sampleSize protected
Definition at line 134 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codecimpl.XTIFFUncompTileCodec.encodeTilePixels(), org.libtiff.jai.codec.XTIFFTileCodecImpl.getCompressedTileSize(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupSourceImage().
short [] org.libtiff.jai.codec.XTIFFTileCodecImpl.spixvals = null protected
Definition at line 340 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor(), org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeTilePixels(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForDecoding().
int org.libtiff.jai.codec.XTIFFTileCodecImpl.tileLength protected
Definition at line 130 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.getCompressedTileSize(), org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize(), org.libtiff.jai.codecimpl.XTIFFFaxTileCodec.initializeDecoding(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForEncoding().
int org.libtiff.jai.codec.XTIFFTileCodecImpl.tileWidth protected
Definition at line 131 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.getCompressedTileSize(), org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize(), org.libtiff.jai.codecimpl.XTIFFLZWTileCodec.initializeDecoding(), org.libtiff.jai.codecimpl.XTIFFFaxTileCodec.initializeDecoding(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForEncoding().
int org.libtiff.jai.codec.XTIFFTileCodecImpl.unitsInThisTile protected
Definition at line 336 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.decode(), org.libtiff.jai.codec.XTIFFTileCodecImpl.decodeColor(), org.libtiff.jai.codecimpl.XTIFFPackTileCodec.decodeTilePixels(), org.libtiff.jai.codecimpl.XTIFFLZWTileCodec.decodeTilePixels(), and org.libtiff.jai.codecimpl.XTIFFUncompTileCodec.decodeTilePixels().
int org.libtiff.jai.codec.XTIFFTileCodecImpl.width protected
Definition at line 127 of file XTIFFTileCodecImpl.java.
Referenced by org.libtiff.jai.codec.XTIFFTileCodecImpl.initialize(), and org.libtiff.jai.codec.XTIFFTileCodecImpl.setupBufferForEncoding().
The documentation for this class was generated from the following file:
verdi_core/src/org/libtiff/jai/codec/XTIFFTileCodecImpl.java