VERDI: anl.verdi.gui.TimePanel Class Reference
anl.verdi.gui.TimePanel Class Reference
Public Member Functions
TimePanel ()
void addListeners (ChangeListener minListener, ChangeListener maxListener, ActionListener useListener)
void reset (Axes< CoordAxis > axes, int timeMin, int timeMax, boolean isUsed)
void setEnabled (boolean val)
Detailed Description
Author
User #2
Definition at line 37 of file TimePanel.java.
Constructor & Destructor Documentation
anl.verdi.gui.TimePanel.TimePanel ()
Definition at line 66 of file TimePanel.java.
References anl.verdi.gui.TimePanel.setEnabled().
Member Function Documentation
void anl.verdi.gui.TimePanel.addListeners (ChangeListener minListener, ChangeListener maxListener, ActionListener useListener)
Definition at line 76 of file TimePanel.java.
void anl.verdi.gui.TimePanel.reset (Axes< CoordAxis > axes, int timeMin, int timeMax, boolean isUsed)
Resets the spinners according to the time axis, and sets their values to the specified min and max.
Parameters
axes the current dataset axes
timeMin the min time
timeMax the max time
Definition at line 90 of file TimePanel.java.
References anl.verdi.data.CoordAxis.getRange().
void anl.verdi.gui.TimePanel.setEnabled (boolean val)
Definition at line 117 of file TimePanel.java.
Referenced by anl.verdi.gui.TimePanel.TimePanel().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/gui/TimePanel.java