VERDI: anl.verdi.plot.io.TIFConvertImage Class Reference
anl.verdi.plot.io.TIFConvertImage Class Reference
Static Public Member Functions
static void convert (String image, String tif) throws IOException
static void convert (String image, String tif, int dpi, int color, int compression, float quality) throws IOException
static byte[] convert (String image, int dpi, int color, int compression, float quality) throws IOException
static void convert (byte[] image, String tif, int dpi, int color, int compression, float quality) throws IOException
static byte[] convert (byte[] image, int dpi, int color, int compression, float quality) throws IOException
static byte[] convert (BufferedImage image, int dpi, int color, int compression, float quality) throws IOException
static void convert (BufferedImage image, String tif, int dpi, int color, int compression, float quality) throws IOException
static void convert (BufferedImage image, String tif) throws IOException
Additional Inherited Members
Static Public Attributes inherited from anl.verdi.plot.io.TIFConvert
static final int CLR_RGB = BufferedImage.TYPE_INT_RGB
static final int CLR_GRAY_SCALE = BufferedImage.TYPE_BYTE_GRAY
static final int CLR_BLACK_WHITE = BufferedImage.TYPE_BYTE_BINARY
static final int COMPRESSION_NONE = BaselineTIFFTagSet.COMPRESSION_NONE
static final int COMPRESSION_CCITT_RLE = BaselineTIFFTagSet.COMPRESSION_CCITT_RLE
static final int COMPRESSION_CCITT_T_4 = BaselineTIFFTagSet.COMPRESSION_CCITT_T_4
static final int COMPRESSION_CCITT_T_6 = BaselineTIFFTagSet.COMPRESSION_CCITT_T_6
static final int COMPRESSION_LZW = BaselineTIFFTagSet.COMPRESSION_LZW
static final int COMPRESSION_JPEG = BaselineTIFFTagSet.COMPRESSION_JPEG
static final int COMPRESSION_PACKBITS = BaselineTIFFTagSet.COMPRESSION_PACKBITS
static final int COMPRESSION_DEFLATE = BaselineTIFFTagSet.COMPRESSION_DEFLATE
Static Protected Member Functions inherited from anl.verdi.plot.io.TIFConvert
static void convert (BufferedImage[] image, String tif, int dpi, int compression, float quality) throws IOException
static byte[] convert (BufferedImage[] image, int dpi, int compression, float quality) throws IOException
static void convert (BufferedImage[] image, Object os, int dpi, int compression, float quality) throws IOException
static BufferedImage getBufferedImage (int color, int compression, int width, int height)
static String getCompression (int compression)
static boolean isCompressionLossless (int compression)
static TIFFImageMetadata createImageMetadata (TIFFImageMetadata imageMetadata, int height, int width, int dpi, int compression, int type) throws IIOInvalidTreeException
Static Protected Attributes inherited from anl.verdi.plot.io.TIFConvert
static final int DEFAULT_DPI = 300
static final int DEFAULT_COLOR = CLR_RGB
static final int DEFAULT_COMPRESSION = COMPRESSION_LZW
static final float DEFAULT_COMPRESSION_QUALITY = 0.25f
Detailed Description
Utility class to convert images to TIF images
Author
Pedro J Rivera
Definition at line 26 of file TIFConvertImage.java.
Member Function Documentation
static void anl.verdi.plot.io.TIFConvertImage.convert (String image, String tif) throws IOException static
Convert an image to a TIF and save as file
Parameters
image
tif
Returns
Exceptions
IOException
Definition at line 35 of file TIFConvertImage.java.
References anl.verdi.plot.io.TIFConvert.DEFAULT_COLOR, anl.verdi.plot.io.TIFConvert.DEFAULT_COMPRESSION, and anl.verdi.plot.io.TIFConvert.DEFAULT_DPI.
Referenced by anl.verdi.plot.io.TIFConvertImage.convert().
static void anl.verdi.plot.io.TIFConvertImage.convert (String image, String tif, int dpi, int color, int compression, float quality) throws IOException static
Convert an image to a TIF and save as file
Parameters
image
tif
dpi
color
compression
quality
Returns
Exceptions
IOException
Definition at line 50 of file TIFConvertImage.java.
References anl.verdi.plot.io.TIFConvertImage.convert().
static byte [] anl.verdi.plot.io.TIFConvertImage.convert (String image, int dpi, int color, int compression, float quality) throws IOException static
Convert an image to a TIF and return as byte array
Parameters
image
dpi
color
compression
quality
Returns
Exceptions
IOException
Definition at line 64 of file TIFConvertImage.java.
References anl.verdi.plot.io.TIFConvertImage.convert().
static void anl.verdi.plot.io.TIFConvertImage.convert (byte[] image, String tif, int dpi, int color, int compression, float quality) throws IOException static
Convert a byte array image type to a TIF and save to file
Parameters
image
tif
dpi
color
compression
quality
Returns
Exceptions
IOException
Definition at line 79 of file TIFConvertImage.java.
References anl.verdi.plot.io.TIFConvertImage.convert().
static byte [] anl.verdi.plot.io.TIFConvertImage.convert (byte[] image, int dpi, int color, int compression, float quality) throws IOException static
Convert a byte array image type to a TIF and return as byte array
Parameters
image
dpi
color
compression
quality
Returns
Exceptions
IOException
Definition at line 93 of file TIFConvertImage.java.
References anl.verdi.plot.io.TIFConvertImage.convert().
static byte [] anl.verdi.plot.io.TIFConvertImage.convert (BufferedImage image, int dpi, int color, int compression, float quality) throws IOException static
Convert a buffered image type to a TIF and return as byte array
Parameters
image
dpi
color
compression
quality
Returns
Exceptions
IOException
Definition at line 107 of file TIFConvertImage.java.
References anl.verdi.plot.io.TIFConvertImage.convert().
static void anl.verdi.plot.io.TIFConvertImage.convert (BufferedImage image, String tif, int dpi, int color, int compression, float quality) throws IOException static
Convert a buffered image type to a TIF and save to file
Parameters
image
tif
dpi
color
compression
quality
Exceptions
IOException
Definition at line 121 of file TIFConvertImage.java.
References anl.verdi.plot.io.TIFConvertImage.convert().
static void anl.verdi.plot.io.TIFConvertImage.convert (BufferedImage image, String tif) throws IOException static
Convert a buffered image type to a TIF and save to file
Parameters
image
tif
dpi
color
compression
quality
Exceptions
IOException
Definition at line 135 of file TIFConvertImage.java.
References anl.verdi.plot.io.TIFConvertImage.convert(), anl.verdi.plot.io.TIFConvert.DEFAULT_COLOR, anl.verdi.plot.io.TIFConvert.DEFAULT_COMPRESSION, anl.verdi.plot.io.TIFConvert.DEFAULT_COMPRESSION_QUALITY, and anl.verdi.plot.io.TIFConvert.DEFAULT_DPI.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/io/TIFConvertImage.java