VERDI: anl.verdi.data.DataUtilities Class Reference
anl.verdi.data.DataUtilities Class Reference
Classes
class MinMax
class MinMaxPoint
Static Public Member Functions
static MinMax minMax (DataFrame frame)
static MinMax minMaxTX (DataFrame frame, int timeStep, int x) throws InvalidRangeException
static MinMax minMaxTY (DataFrame frame, int timeStep, int y) throws InvalidRangeException
static MinMax minMax (DataFrame frame, int timeStep, int layer) throws InvalidRangeException
static MinMaxPoint minMaxTYPoint (DataFrame frame, int timestep, int y) throws InvalidRangeException
static MinMaxPoint minMaxPoint (DataFrame frame, int timestep) throws InvalidRangeException
static MinMaxPoint minMaxTXPoint (DataFrame frame, int timestep, int x) throws InvalidRangeException
static MinMaxPoint minMaxTLPoint (DataFrame frame, int timeStep, int layer) throws InvalidRangeException
static MinMax minMaxForTimeLayer (DataFrame frame, int layer) throws InvalidRangeException
static MinMax minMax (DataFrame frame, int timeStep) throws InvalidRangeException
static DataFrame createDataFrame (DataFrame frame)
static DataFrame[] unitVectorTransform (DataFrame xFrame, DataFrame yFrame)
static DataFrame[] unitVectorTransform (DataFrame xFrame, DataFrame yFrame, int vectorSamplingInc)
Static Public Attributes
static final int NO_LAYER = -1
static double BADVAL3 = VerdiConstants.BADVAL3
static double AMISS3 = VerdiConstants.AMISS3
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 24 of file DataUtilities.java.
Member Function Documentation
static DataFrame anl.verdi.data.DataUtilities.createDataFrame (DataFrame frame) static
Definition at line 358 of file DataUtilities.java.
References anl.verdi.data.DataFrameBuilder.addAxis(), and anl.verdi.data.DataFrameAxis.createDataFrameAxis().
Referenced by anl.verdi.data.DataUtilities.unitVectorTransform().
static MinMax anl.verdi.data.DataUtilities.minMax (DataFrame frame) static
Gets the minimum value contained by the specified DataFrame.
Parameters
frame the DataFrame to get the value from
Returns
the minimum value contained by the specified DataFrame.
Definition at line 102 of file DataUtilities.java.
References anl.verdi.data.DataFrame.getArray().
Referenced by anl.verdi.data.DataUtilities.minMax(), anl.verdi.data.DataUtilities.minMaxForTimeLayer(), anl.verdi.data.DataUtilities.minMaxTX(), and anl.verdi.data.DataUtilities.minMaxTY().
static MinMax anl.verdi.data.DataUtilities.minMax (DataFrame frame, int timeStep, int layer) throws InvalidRangeException static
Definition at line 175 of file DataUtilities.java.
References anl.verdi.data.AxisRange.getExtent(), and anl.verdi.data.DataUtilities.minMax().
static MinMax anl.verdi.data.DataUtilities.minMax (DataFrame frame, int timeStep) throws InvalidRangeException static
Gets the min max value from the DataFrame at the specified time step. The range for the other axes will be their existing range.
Parameters
frame the frame whose min max we want
timeStep the timestep for the min max
Returns
the min max value from the DataFrame at the specified time step. The range for the other axes will be their existing range.
Exceptions
InvalidRangeException if the range is invalid.
Definition at line 327 of file DataUtilities.java.
References anl.verdi.data.AxisRange.getExtent(), and anl.verdi.data.DataUtilities.minMax().
static MinMax anl.verdi.data.DataUtilities.minMaxForTimeLayer (DataFrame frame, int layer) throws InvalidRangeException static
Gets the min max for the specified layer over the frame's entire time range.
Parameters
frame the frame
layer the index of the layer whose min max is desired
Returns
the min max for the specified layer over the frame's entire time range.
Exceptions
InvalidRangeException if the range is invalid.
Definition at line 287 of file DataUtilities.java.
References anl.verdi.data.AxisRange.getExtent(), and anl.verdi.data.DataUtilities.minMax().
static MinMaxPoint anl.verdi.data.DataUtilities.minMaxPoint (DataFrame frame, int timestep) throws InvalidRangeException static
Definition at line 206 of file DataUtilities.java.
static MinMaxPoint anl.verdi.data.DataUtilities.minMaxTLPoint (DataFrame frame, int timeStep, int layer) throws InvalidRangeException static
Gets the min max point at the specified time step and layer over all the x,y cells.
Parameters
frame the frame containing the data
timeStep the timestep
layer the layer
Returns
the min max point at the specified time step and layer over all the x,y cells.
Exceptions
InvalidRangeException if the frame's rank does not equal four.
Definition at line 261 of file DataUtilities.java.
static MinMax anl.verdi.data.DataUtilities.minMaxTX (DataFrame frame, int timeStep, int x) throws InvalidRangeException static
Gets the min max of the frame data for the specified time step and x value over all the layers and y range.
Parameters
frame the data
timeStep the timestep
x the x value
Returns
the min max of the frame data for the specified time step and x value over all the layers and y range.
Exceptions
InvalidRangeException if the timestep or x value is out of range.
Definition at line 134 of file DataUtilities.java.
References anl.verdi.data.AxisRange.getExtent(), and anl.verdi.data.DataUtilities.minMax().
static MinMaxPoint anl.verdi.data.DataUtilities.minMaxTXPoint (DataFrame frame, int timestep, int x) throws InvalidRangeException static
Definition at line 233 of file DataUtilities.java.
static MinMax anl.verdi.data.DataUtilities.minMaxTY (DataFrame frame, int timeStep, int y) throws InvalidRangeException static
Gets the min max of the frame data for the specified time step and y value over all the layers and x range.
Parameters
frame the data
timeStep the timestep
y the y value
Returns
the min max of the frame data for the specified time step and x value over all the layers and y range.
Exceptions
InvalidRangeException if the timestep or x value is out of range.
Definition at line 160 of file DataUtilities.java.
References anl.verdi.data.AxisRange.getExtent(), and anl.verdi.data.DataUtilities.minMax().
static MinMaxPoint anl.verdi.data.DataUtilities.minMaxTYPoint (DataFrame frame, int timestep, int y) throws InvalidRangeException static
Definition at line 189 of file DataUtilities.java.
static DataFrame [] anl.verdi.data.DataUtilities.unitVectorTransform (DataFrame xFrame, DataFrame yFrame) static
Normalizes the xFrame and yFrame data into normalized wind vectors i.e., uwind / max_uwind
Parameters
xFrame
yFrame
Returns
Definition at line 383 of file DataUtilities.java.
References anl.verdi.data.DataUtilities.createDataFrame().
static DataFrame [] anl.verdi.data.DataUtilities.unitVectorTransform (DataFrame xFrame, DataFrame yFrame, int vectorSamplingInc) static
Definition at line 417 of file DataUtilities.java.
References anl.verdi.data.DataUtilities.createDataFrame(), and anl.verdi.data.DataFrame.getArray().
Member Data Documentation
double anl.verdi.data.DataUtilities.AMISS3 = VerdiConstants.AMISS3 static
Definition at line 28 of file DataUtilities.java.
Referenced by anl.verdi.area.target.Target.calcTotalDeposition().
double anl.verdi.data.DataUtilities.BADVAL3 = VerdiConstants.BADVAL3 static
Definition at line 27 of file DataUtilities.java.
Referenced by anl.verdi.data.TLDataFrameTableModel.getValueAt(), anl.verdi.data.XYDataFrameTableModel.getValueAt(), and anl.verdi.data.XYLDataFrameTableModel.getValueAt().
final int anl.verdi.data.DataUtilities.NO_LAYER = -1 static
Definition at line 26 of file DataUtilities.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/data/DataUtilities.java