VERDI: gov.epa.emvl.Numerics Class Reference
gov.epa.emvl.Numerics Class Reference
Static Public Member Functions
static boolean isNan (double x)
static boolean inRange (double value, double minimum, double maximum)
static double square (double x)
static double sign (double x)
static double clamp (double value, double minimum, double maximum)
static int clampInt (int value, int minimum, int maximum)
static double round1 (double value)
static double safeSum (double x, double y)
static double safeDifference (double x, double y)
static double safeProduct (double x, double y)
static double safeQuotient (double numerator, double denominator)
static boolean withinTolerance (double x, double y, double tolerance)
static boolean aboutEqual (double x, double y)
Static Public Attributes
static final double DBL_MIN = 2.2250738585072014E-308
static final double DBL_MAX = 1.7976931348623157E+308
static final double PI_OVER_2 = 1.57079632679489661923
static final double PI_OVER_4 = 0.78539816339744830962
static final double TOLERANCE = 1e-6
Detailed Description
Definition at line 7 of file Numerics.java.
Member Function Documentation
static boolean gov.epa.emvl.Numerics.aboutEqual (double x, double y) static
Definition at line 232 of file Numerics.java.
References gov.epa.emvl.Numerics.TOLERANCE, and gov.epa.emvl.Numerics.withinTolerance().
static double gov.epa.emvl.Numerics.clamp (double value, double minimum, double maximum) static
clamp - clamp value between minimum and maximum.
Precondition
! isNan(value)
! isNan(minimum)
! isNan(maximum)
minimum <= maximum
Postcondition
return >= minimum
return <= maximum
Definition at line 79 of file Numerics.java.
static int gov.epa.emvl.Numerics.clampInt (int value, int minimum, int maximum) static
clamp - clamp value between minimum and maximum.
Precondition
minimum <= maximum
Postcondition
return >= minimum
return <= maximum
Definition at line 99 of file Numerics.java.
static boolean gov.epa.emvl.Numerics.inRange (double value, double minimum, double maximum) static
inRange - is minimum <= x <= maximum?
Precondition
! isNan(x)
! isNan(minimum)
! isNan(maximum)
Definition at line 37 of file Numerics.java.
Referenced by gov.epa.emvl.Numerics.withinTolerance().
static boolean gov.epa.emvl.Numerics.isNan (double x) static
isNan - is x not-a-number?
Definition at line 23 of file Numerics.java.
Referenced by gov.epa.emvl.Numerics.withinTolerance().
static double gov.epa.emvl.Numerics.round1 (double value) static
round1 - round x to 1 decimal place.
Precondition
! isNan(value)
Postcondition
! isNan(return)
Math.abs(value - return) < 0.11
Definition at line 118 of file Numerics.java.
static double gov.epa.emvl.Numerics.safeDifference (double x, double y) static
safeDifference - x - y.
Precondition
! isNan(x)
! isNan(y)
Postcondition
! isNan(return)
x == y implies return == 0.0
Definition at line 147 of file Numerics.java.
static double gov.epa.emvl.Numerics.safeProduct (double x, double y) static
safeProduct - x * y.
Precondition
! isNan(x)
! isNan(y)
Postcondition
! isNan(return)
x == 0.0 implies return == 0.0
y == 0.0 implies return == 0.0
Definition at line 162 of file Numerics.java.
static double gov.epa.emvl.Numerics.safeQuotient (double numerator, double denominator) static
safeQuotient - numerator / denominator.
Precondition
! isNan(numerator)
! isNan(denominator)
denominator != 0.0
Postcondition
! isNan(return)
numerator == 0.0 implies return == 0.0
numerator == denominator implies return == 1.0
numerator == -denominator implies return == -1.0
Definition at line 179 of file Numerics.java.
static double gov.epa.emvl.Numerics.safeSum (double x, double y) static
safeSum - x + y.
Precondition
! isNan(x)
! isNan(y)
Postcondition
! isNan(return)
x == -y implies return == 0.0
Definition at line 133 of file Numerics.java.
static double gov.epa.emvl.Numerics.sign (double x) static
sign - sign (1.0 or -1.0) of x.
Precondition
! isNan(x)
Postcondition
x >= 0.0 implies return == 1.0
x < 0.0 implies return == -1.0
Definition at line 63 of file Numerics.java.
static double gov.epa.emvl.Numerics.square (double x) static
square - x * x.
Precondition
! isNan(x)
Postcondition
! isNan(return)
Definition at line 50 of file Numerics.java.
static boolean gov.epa.emvl.Numerics.withinTolerance (double x, double y, double tolerance) static
withinTolerance - Do x and y differ by less than tolerance?
Precondition
! isNan(tolerance)
tolerance <= 0.1
tolerance >= 0.0
Definition at line 198 of file Numerics.java.
References gov.epa.emvl.Numerics.DBL_MAX, gov.epa.emvl.Numerics.DBL_MIN, gov.epa.emvl.Numerics.inRange(), and gov.epa.emvl.Numerics.isNan().
Referenced by gov.epa.emvl.Numerics.aboutEqual().
Member Data Documentation
final double gov.epa.emvl.Numerics.DBL_MAX = 1.7976931348623157E+308 static
Definition at line 12 of file Numerics.java.
Referenced by gov.epa.emvl.Numerics.withinTolerance().
final double gov.epa.emvl.Numerics.DBL_MIN = 2.2250738585072014E-308 static
Definition at line 11 of file Numerics.java.
Referenced by gov.epa.emvl.Numerics.withinTolerance().
final double gov.epa.emvl.Numerics.PI_OVER_2 = 1.57079632679489661923 static
Definition at line 13 of file Numerics.java.
final double gov.epa.emvl.Numerics.PI_OVER_4 = 0.78539816339744830962 static
Definition at line 14 of file Numerics.java.
final double gov.epa.emvl.Numerics.TOLERANCE = 1e-6 static
Definition at line 15 of file Numerics.java.
Referenced by gov.epa.emvl.Numerics.aboutEqual().
The documentation for this class was generated from the following file:
verdi_core/src/gov/epa/emvl/Numerics.java