VERDI: anl.verdi.plot.util.AnimatedGifEncoder Class Reference
anl.verdi.plot.util.AnimatedGifEncoder Class Reference
Public Member Functions
void setDelay (int ms)
void setDispose (int code)
void setRepeat (int iter)
void setTransparent (Color c)
boolean addFrame (BufferedImage im)
boolean finish ()
void setFrameRate (float fps)
void setQuality (int quality)
void setSize (int w, int h)
boolean start (OutputStream os)
boolean start (String file)
Protected Member Functions
void analyzePixels ()
int findClosest (Color c)
void getImagePixels ()
void writeGraphicCtrlExt () throws IOException
void writeImageDesc () throws IOException
void writeLSD () throws IOException
void writeNetscapeExt () throws IOException
void writePalette () throws IOException
void writePixels () throws IOException
void writeShort (int value) throws IOException
void writeString (String s) throws IOException
Protected Attributes
int width
int height
Color transparent = null
int transIndex
int repeat = 0
int delay = 0
boolean started = false
OutputStream out
BufferedImage image
byte[] pixels
byte[] indexedPixels
int colorDepth
byte[] colorTab
boolean[] usedEntry = new boolean[256]
int palSize = 7
int dispose = -1
boolean closeStream = false
boolean firstFrame = true
boolean sizeSet = false
int sample = 10
Detailed Description
Class AnimatedGifEncoder - Encodes a GIF file consisting of one or more frames.
Example:
   AnimatedGifEncoder e = new AnimatedGifEncoder();
   e.start(outputFileName);
   e.setDelay(1000);   // 1 frame per sec
   e.addFrame(image1);
   e.addFrame(image2);
   e.finish();
No copyright asserted on the source code of this class. May be used for any purpose, however, refer to the Unisys LZW patent for restrictions on use of the associated LZWEncoder class. Please forward any corrections to kwein.nosp@m.er@f.nosp@m.mswar.nosp@m.e.co.nosp@m.m.
Author
Kevin Weiner, FM Software
Version
1.03 November 2003
Definition at line 34 of file AnimatedGifEncoder.java.
Member Function Documentation
boolean anl.verdi.plot.util.AnimatedGifEncoder.addFrame (BufferedImage im)
Adds next GIF frame. The frame is not written immediately, but is actually deferred until the next frame is received so that timing data can be inserted. Invoking finish() flushes all frames. If setSize was not invoked, the size of the first image is used for all subsequent frames.
Parameters
im BufferedImage containing frame to write.
Returns
true if successful.
Definition at line 119 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.analyzePixels(), anl.verdi.plot.util.AnimatedGifEncoder.firstFrame, anl.verdi.plot.util.AnimatedGifEncoder.getImagePixels(), anl.verdi.plot.util.AnimatedGifEncoder.image, anl.verdi.plot.util.AnimatedGifEncoder.repeat, anl.verdi.plot.util.AnimatedGifEncoder.setSize(), anl.verdi.plot.util.AnimatedGifEncoder.sizeSet, anl.verdi.plot.util.AnimatedGifEncoder.started, anl.verdi.plot.util.AnimatedGifEncoder.writeGraphicCtrlExt(), anl.verdi.plot.util.AnimatedGifEncoder.writeImageDesc(), anl.verdi.plot.util.AnimatedGifEncoder.writeLSD(), anl.verdi.plot.util.AnimatedGifEncoder.writeNetscapeExt(), anl.verdi.plot.util.AnimatedGifEncoder.writePalette(), and anl.verdi.plot.util.AnimatedGifEncoder.writePixels().
void anl.verdi.plot.util.AnimatedGifEncoder.analyzePixels () protected
Analyzes image colors and creates color map.
Definition at line 272 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.colorDepth, anl.verdi.plot.util.AnimatedGifEncoder.colorTab, anl.verdi.plot.util.AnimatedGifEncoder.findClosest(), anl.verdi.plot.util.AnimatedGifEncoder.indexedPixels, anl.verdi.plot.util.AnimatedGifEncoder.palSize, anl.verdi.plot.util.AnimatedGifEncoder.pixels, anl.verdi.plot.util.AnimatedGifEncoder.sample, anl.verdi.plot.util.AnimatedGifEncoder.transIndex, anl.verdi.plot.util.AnimatedGifEncoder.transparent, and anl.verdi.plot.util.AnimatedGifEncoder.usedEntry.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame().
int anl.verdi.plot.util.AnimatedGifEncoder.findClosest (Color c) protected
Returns index of palette color closest to c
Definition at line 309 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.colorTab, and anl.verdi.plot.util.AnimatedGifEncoder.usedEntry.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.analyzePixels().
boolean anl.verdi.plot.util.AnimatedGifEncoder.finish ()
Flushes any pending data and closes output file. If writing to an OutputStream, the stream is not closed.
Definition at line 159 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.closeStream, anl.verdi.plot.util.AnimatedGifEncoder.colorTab, anl.verdi.plot.util.AnimatedGifEncoder.firstFrame, anl.verdi.plot.util.AnimatedGifEncoder.image, anl.verdi.plot.util.AnimatedGifEncoder.indexedPixels, anl.verdi.plot.util.AnimatedGifEncoder.out, anl.verdi.plot.util.AnimatedGifEncoder.pixels, anl.verdi.plot.util.AnimatedGifEncoder.started, and anl.verdi.plot.util.AnimatedGifEncoder.transIndex.
void anl.verdi.plot.util.AnimatedGifEncoder.getImagePixels () protected
Extracts image pixels into byte array "pixels"
Definition at line 335 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.height, anl.verdi.plot.util.AnimatedGifEncoder.image, anl.verdi.plot.util.AnimatedGifEncoder.pixels, and anl.verdi.plot.util.AnimatedGifEncoder.width.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame().
void anl.verdi.plot.util.AnimatedGifEncoder.setDelay (int ms)
Sets the delay time between each frame, or changes it for subsequent frames (applies to last frame added).
Parameters
ms int delay time in milliseconds
Definition at line 63 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.delay.
void anl.verdi.plot.util.AnimatedGifEncoder.setDispose (int code)
Sets the GIF frame disposal code for the last added frame and any subsequent frames. Default is 0 if no transparent color has been set, otherwise 2.
Parameters
code int disposal code.
Definition at line 73 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.dispose.
void anl.verdi.plot.util.AnimatedGifEncoder.setFrameRate (float fps)
Sets frame rate in frames per second. Equivalent to setDelay(1000/fps).
Parameters
fps float frame rate (frames per second)
Definition at line 192 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.delay.
void anl.verdi.plot.util.AnimatedGifEncoder.setQuality (int quality)
Sets quality of color quantization (conversion of images to the maximum 256 colors allowed by the GIF specification). Lower values (minimum = 1) produce better colors, but slow processing significantly. 10 is the default, and produces good color mapping at reasonable speeds. Values greater than 20 do not yield significant improvements in speed.
Parameters
quality int greater than 0.
Returns
Definition at line 209 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.sample.
void anl.verdi.plot.util.AnimatedGifEncoder.setRepeat (int iter)
Sets the number of times the set of GIF frames should be played. Default is 1; 0 means play indefinitely. Must be invoked before the first image is added.
Parameters
iter int number of iterations.
Returns
Definition at line 88 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.repeat.
void anl.verdi.plot.util.AnimatedGifEncoder.setSize (int w, int h)
Sets the GIF frame size. The default size is the size of the first frame added if this method is not invoked.
Parameters
w int frame width.
h int frame width.
Definition at line 222 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.firstFrame, anl.verdi.plot.util.AnimatedGifEncoder.height, anl.verdi.plot.util.AnimatedGifEncoder.sizeSet, anl.verdi.plot.util.AnimatedGifEncoder.started, and anl.verdi.plot.util.AnimatedGifEncoder.width.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame().
void anl.verdi.plot.util.AnimatedGifEncoder.setTransparent (Color c)
Sets the transparent color for the last added frame and any subsequent frames. Since all colors are subject to modification in the quantization process, the color in the final palette for each frame closest to the given color becomes the transparent color for that frame. May be set to null to indicate no transparent color.
Parameters
c Color to be treated as transparent on display.
Definition at line 105 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.transparent.
boolean anl.verdi.plot.util.AnimatedGifEncoder.start (OutputStream os)
Initiates GIF file creation on the given stream. The stream is not closed automatically.
Parameters
os OutputStream on which GIF images are written.
Returns
false if initial write failed.
Definition at line 238 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.closeStream, anl.verdi.plot.util.AnimatedGifEncoder.out, anl.verdi.plot.util.AnimatedGifEncoder.started, and anl.verdi.plot.util.AnimatedGifEncoder.writeString().
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.start().
boolean anl.verdi.plot.util.AnimatedGifEncoder.start (String file)
Initiates writing of a GIF file with the specified name.
Parameters
file String containing output file name.
Returns
false if open or initial write failed.
Definition at line 257 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.closeStream, anl.verdi.plot.util.AnimatedGifEncoder.out, anl.verdi.plot.util.AnimatedGifEncoder.start(), and anl.verdi.plot.util.AnimatedGifEncoder.started.
void anl.verdi.plot.util.AnimatedGifEncoder.writeGraphicCtrlExt () throws IOException protected
Writes Graphic Control Extension
Definition at line 355 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.delay, anl.verdi.plot.util.AnimatedGifEncoder.dispose, anl.verdi.plot.util.AnimatedGifEncoder.transIndex, anl.verdi.plot.util.AnimatedGifEncoder.transparent, and anl.verdi.plot.util.AnimatedGifEncoder.writeShort().
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame().
void anl.verdi.plot.util.AnimatedGifEncoder.writeImageDesc () throws IOException protected
Writes Image Descriptor
Definition at line 386 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.firstFrame, anl.verdi.plot.util.AnimatedGifEncoder.height, anl.verdi.plot.util.AnimatedGifEncoder.palSize, anl.verdi.plot.util.AnimatedGifEncoder.width, and anl.verdi.plot.util.AnimatedGifEncoder.writeShort().
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame().
void anl.verdi.plot.util.AnimatedGifEncoder.writeLSD () throws IOException protected
Writes Logical Screen Descriptor
Definition at line 409 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.height, anl.verdi.plot.util.AnimatedGifEncoder.palSize, anl.verdi.plot.util.AnimatedGifEncoder.width, and anl.verdi.plot.util.AnimatedGifEncoder.writeShort().
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame().
void anl.verdi.plot.util.AnimatedGifEncoder.writeNetscapeExt () throws IOException protected
Writes Netscape application extension to define repeat count.
Definition at line 427 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.repeat, anl.verdi.plot.util.AnimatedGifEncoder.writeShort(), and anl.verdi.plot.util.AnimatedGifEncoder.writeString().
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame().
void anl.verdi.plot.util.AnimatedGifEncoder.writePalette () throws IOException protected
Writes color table
Definition at line 441 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.colorTab.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame().
void anl.verdi.plot.util.AnimatedGifEncoder.writePixels () throws IOException protected
Encodes and writes pixel data
Definition at line 452 of file AnimatedGifEncoder.java.
References anl.verdi.plot.util.AnimatedGifEncoder.colorDepth, anl.verdi.plot.util.AnimatedGifEncoder.height, anl.verdi.plot.util.AnimatedGifEncoder.indexedPixels, anl.verdi.plot.util.AnimatedGifEncoder.out, and anl.verdi.plot.util.AnimatedGifEncoder.width.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame().
void anl.verdi.plot.util.AnimatedGifEncoder.writeShort (int value) throws IOException protected
Write 16-bit value to output stream, LSB first
Definition at line 461 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.writeGraphicCtrlExt(), anl.verdi.plot.util.AnimatedGifEncoder.writeImageDesc(), anl.verdi.plot.util.AnimatedGifEncoder.writeLSD(), and anl.verdi.plot.util.AnimatedGifEncoder.writeNetscapeExt().
void anl.verdi.plot.util.AnimatedGifEncoder.writeString (String s) throws IOException protected
Writes string to output stream
Definition at line 469 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.start(), and anl.verdi.plot.util.AnimatedGifEncoder.writeNetscapeExt().
Member Data Documentation
boolean anl.verdi.plot.util.AnimatedGifEncoder.closeStream = false protected
Definition at line 52 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.finish(), and anl.verdi.plot.util.AnimatedGifEncoder.start().
int anl.verdi.plot.util.AnimatedGifEncoder.colorDepth protected
Definition at line 47 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.analyzePixels(), and anl.verdi.plot.util.AnimatedGifEncoder.writePixels().
byte [] anl.verdi.plot.util.AnimatedGifEncoder.colorTab protected
Definition at line 48 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.analyzePixels(), anl.verdi.plot.util.AnimatedGifEncoder.findClosest(), anl.verdi.plot.util.AnimatedGifEncoder.finish(), and anl.verdi.plot.util.AnimatedGifEncoder.writePalette().
int anl.verdi.plot.util.AnimatedGifEncoder.delay = 0 protected
Definition at line 41 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.setDelay(), anl.verdi.plot.util.AnimatedGifEncoder.setFrameRate(), and anl.verdi.plot.util.AnimatedGifEncoder.writeGraphicCtrlExt().
int anl.verdi.plot.util.AnimatedGifEncoder.dispose = -1 protected
Definition at line 51 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.setDispose(), and anl.verdi.plot.util.AnimatedGifEncoder.writeGraphicCtrlExt().
boolean anl.verdi.plot.util.AnimatedGifEncoder.firstFrame = true protected
Definition at line 53 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame(), anl.verdi.plot.util.AnimatedGifEncoder.finish(), anl.verdi.plot.util.AnimatedGifEncoder.setSize(), and anl.verdi.plot.util.AnimatedGifEncoder.writeImageDesc().
int anl.verdi.plot.util.AnimatedGifEncoder.height protected
Definition at line 37 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.getImagePixels(), anl.verdi.plot.util.AnimatedGifEncoder.setSize(), anl.verdi.plot.util.AnimatedGifEncoder.writeImageDesc(), anl.verdi.plot.util.AnimatedGifEncoder.writeLSD(), and anl.verdi.plot.util.AnimatedGifEncoder.writePixels().
BufferedImage anl.verdi.plot.util.AnimatedGifEncoder.image protected
Definition at line 44 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame(), anl.verdi.plot.util.AnimatedGifEncoder.finish(), and anl.verdi.plot.util.AnimatedGifEncoder.getImagePixels().
byte [] anl.verdi.plot.util.AnimatedGifEncoder.indexedPixels protected
Definition at line 46 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.analyzePixels(), anl.verdi.plot.util.AnimatedGifEncoder.finish(), and anl.verdi.plot.util.AnimatedGifEncoder.writePixels().
OutputStream anl.verdi.plot.util.AnimatedGifEncoder.out protected
Definition at line 43 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.finish(), anl.verdi.plot.util.AnimatedGifEncoder.start(), and anl.verdi.plot.util.AnimatedGifEncoder.writePixels().
int anl.verdi.plot.util.AnimatedGifEncoder.palSize = 7 protected
Definition at line 50 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.analyzePixels(), anl.verdi.plot.util.AnimatedGifEncoder.writeImageDesc(), and anl.verdi.plot.util.AnimatedGifEncoder.writeLSD().
byte [] anl.verdi.plot.util.AnimatedGifEncoder.pixels protected
Definition at line 45 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.analyzePixels(), anl.verdi.plot.util.AnimatedGifEncoder.finish(), and anl.verdi.plot.util.AnimatedGifEncoder.getImagePixels().
int anl.verdi.plot.util.AnimatedGifEncoder.repeat = 0 protected
Definition at line 40 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame(), anl.verdi.plot.util.AnimatedGifEncoder.setRepeat(), and anl.verdi.plot.util.AnimatedGifEncoder.writeNetscapeExt().
int anl.verdi.plot.util.AnimatedGifEncoder.sample = 10 protected
Definition at line 55 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.analyzePixels(), and anl.verdi.plot.util.AnimatedGifEncoder.setQuality().
boolean anl.verdi.plot.util.AnimatedGifEncoder.sizeSet = false protected
Definition at line 54 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame(), and anl.verdi.plot.util.AnimatedGifEncoder.setSize().
boolean anl.verdi.plot.util.AnimatedGifEncoder.started = false protected
Definition at line 42 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.addFrame(), anl.verdi.plot.util.AnimatedGifEncoder.finish(), anl.verdi.plot.util.AnimatedGifEncoder.setSize(), and anl.verdi.plot.util.AnimatedGifEncoder.start().
int anl.verdi.plot.util.AnimatedGifEncoder.transIndex protected
Definition at line 39 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.analyzePixels(), anl.verdi.plot.util.AnimatedGifEncoder.finish(), and anl.verdi.plot.util.AnimatedGifEncoder.writeGraphicCtrlExt().
Color anl.verdi.plot.util.AnimatedGifEncoder.transparent = null protected
Definition at line 38 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.analyzePixels(), anl.verdi.plot.util.AnimatedGifEncoder.setTransparent(), and anl.verdi.plot.util.AnimatedGifEncoder.writeGraphicCtrlExt().
boolean [] anl.verdi.plot.util.AnimatedGifEncoder.usedEntry = new boolean[256] protected
Definition at line 49 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.analyzePixels(), and anl.verdi.plot.util.AnimatedGifEncoder.findClosest().
int anl.verdi.plot.util.AnimatedGifEncoder.width protected
Definition at line 36 of file AnimatedGifEncoder.java.
Referenced by anl.verdi.plot.util.AnimatedGifEncoder.getImagePixels(), anl.verdi.plot.util.AnimatedGifEncoder.setSize(), anl.verdi.plot.util.AnimatedGifEncoder.writeImageDesc(), anl.verdi.plot.util.AnimatedGifEncoder.writeLSD(), and anl.verdi.plot.util.AnimatedGifEncoder.writePixels().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/util/AnimatedGifEncoder.java