VERDI: anl.verdi.plot.io.TIFConvert Class Reference
anl.verdi.plot.io.TIFConvert Class Reference abstract
Static Public Attributes
static final int CLR_RGB = BufferedImage.TYPE_INT_RGB
static final int CLR_GRAY_SCALE = BufferedImage.TYPE_BYTE_GRAY
static final int CLR_BLACK_WHITE = BufferedImage.TYPE_BYTE_BINARY
static final int COMPRESSION_NONE = BaselineTIFFTagSet.COMPRESSION_NONE
static final int COMPRESSION_CCITT_RLE = BaselineTIFFTagSet.COMPRESSION_CCITT_RLE
static final int COMPRESSION_CCITT_T_4 = BaselineTIFFTagSet.COMPRESSION_CCITT_T_4
static final int COMPRESSION_CCITT_T_6 = BaselineTIFFTagSet.COMPRESSION_CCITT_T_6
static final int COMPRESSION_LZW = BaselineTIFFTagSet.COMPRESSION_LZW
static final int COMPRESSION_JPEG = BaselineTIFFTagSet.COMPRESSION_JPEG
static final int COMPRESSION_PACKBITS = BaselineTIFFTagSet.COMPRESSION_PACKBITS
static final int COMPRESSION_DEFLATE = BaselineTIFFTagSet.COMPRESSION_DEFLATE
Static Protected Member Functions
static void convert (BufferedImage[] image, String tif, int dpi, int compression, float quality) throws IOException
static byte[] convert (BufferedImage[] image, int dpi, int compression, float quality) throws IOException
static void convert (BufferedImage[] image, Object os, int dpi, int compression, float quality) throws IOException
static BufferedImage getBufferedImage (int color, int compression, int width, int height)
static String getCompression (int compression)
static boolean isCompressionLossless (int compression)
static TIFFImageMetadata createImageMetadata (TIFFImageMetadata imageMetadata, int height, int width, int dpi, int compression, int type) throws IIOInvalidTreeException
Static Protected Attributes
static final int DEFAULT_DPI = 300
static final int DEFAULT_COLOR = CLR_RGB
static final int DEFAULT_COMPRESSION = COMPRESSION_LZW
static final float DEFAULT_COMPRESSION_QUALITY = 0.25f
Detailed Description
Abstract Class TIFConvert
Author
Pedro J Rivera
Definition at line 39 of file TIFConvert.java.
Member Function Documentation
static void anl.verdi.plot.io.TIFConvert.convert (BufferedImage[] image, String tif, int dpi, int compression, float quality) throws IOException static protected
Convert buffered image to a TIF and save to file
Parameters
image
tif
dpi
compression
quality
Exceptions
IOException
Definition at line 68 of file TIFConvert.java.
Referenced by anl.verdi.plot.io.TIFConvert.convert().
static byte [] anl.verdi.plot.io.TIFConvert.convert (BufferedImage[] image, int dpi, int compression, float quality) throws IOException static protected
Convert buffered image and return TIF as a byte array
Parameters
image
dpi
compression
quality
Returns
Exceptions
IOException
Definition at line 96 of file TIFConvert.java.
References anl.verdi.plot.io.TIFConvert.convert().
static void anl.verdi.plot.io.TIFConvert.convert (BufferedImage[] image, Object os, int dpi, int compression, float quality) throws IOException static protected
Convert buffered image to TIF format
Parameters
image
os
dpi
compression
quality
Exceptions
IOException
Definition at line 118 of file TIFConvert.java.
References anl.verdi.plot.io.TIFConvert.createImageMetadata(), anl.verdi.plot.io.TIFConvert.DEFAULT_COMPRESSION_QUALITY, anl.verdi.plot.io.TIFConvert.getCompression(), and anl.verdi.plot.io.TIFConvert.isCompressionLossless().
static TIFFImageMetadata anl.verdi.plot.io.TIFConvert.createImageMetadata (TIFFImageMetadata imageMetadata, int height, int width, int dpi, int compression, int type) throws IIOInvalidTreeException static protected
Return the image meta data for the new TIF image
Parameters
imageMetadata
Returns
Exceptions
IIOInvalidTreeException Based on TIFF V6.0 specifications.
See Also
TIFF 6.0 Specification
Definition at line 208 of file TIFConvert.java.
Referenced by anl.verdi.plot.io.TIFConvert.convert().
static BufferedImage anl.verdi.plot.io.TIFConvert.getBufferedImage (int color, int compression, int width, int height) static protected
Get an appropriate buffered image
Parameters
color
compression
width
height
Returns
Definition at line 154 of file TIFConvert.java.
References anl.verdi.plot.io.TIFConvert.CLR_BLACK_WHITE, anl.verdi.plot.io.TIFConvert.CLR_GRAY_SCALE, anl.verdi.plot.io.TIFConvert.COMPRESSION_CCITT_RLE, anl.verdi.plot.io.TIFConvert.COMPRESSION_CCITT_T_4, and anl.verdi.plot.io.TIFConvert.COMPRESSION_CCITT_T_6.
static String anl.verdi.plot.io.TIFConvert.getCompression (int compression) static protected
Get compression string
Parameters
compression
Returns
Definition at line 174 of file TIFConvert.java.
Referenced by anl.verdi.plot.io.TIFConvert.convert().
static boolean anl.verdi.plot.io.TIFConvert.isCompressionLossless (int compression) static protected
Get loss less flag
Parameters
compression
Returns
Definition at line 189 of file TIFConvert.java.
Referenced by anl.verdi.plot.io.TIFConvert.convert().
Member Data Documentation
final int anl.verdi.plot.io.TIFConvert.CLR_BLACK_WHITE = BufferedImage.TYPE_BYTE_BINARY static
Definition at line 42 of file TIFConvert.java.
Referenced by anl.verdi.plot.io.TIFConvert.getBufferedImage().
final int anl.verdi.plot.io.TIFConvert.CLR_GRAY_SCALE = BufferedImage.TYPE_BYTE_GRAY static
Definition at line 41 of file TIFConvert.java.
Referenced by anl.verdi.plot.io.TIFConvert.getBufferedImage().
final int anl.verdi.plot.io.TIFConvert.CLR_RGB = BufferedImage.TYPE_INT_RGB static
Definition at line 40 of file TIFConvert.java.
final int anl.verdi.plot.io.TIFConvert.COMPRESSION_CCITT_RLE = BaselineTIFFTagSet.COMPRESSION_CCITT_RLE static
Definition at line 45 of file TIFConvert.java.
Referenced by anl.verdi.plot.io.TIFConvert.getBufferedImage().
final int anl.verdi.plot.io.TIFConvert.COMPRESSION_CCITT_T_4 = BaselineTIFFTagSet.COMPRESSION_CCITT_T_4 static
Definition at line 46 of file TIFConvert.java.
Referenced by anl.verdi.plot.io.TIFConvert.getBufferedImage().
final int anl.verdi.plot.io.TIFConvert.COMPRESSION_CCITT_T_6 = BaselineTIFFTagSet.COMPRESSION_CCITT_T_6 static
Definition at line 47 of file TIFConvert.java.
Referenced by anl.verdi.plot.io.TIFConvert.getBufferedImage().
final int anl.verdi.plot.io.TIFConvert.COMPRESSION_DEFLATE = BaselineTIFFTagSet.COMPRESSION_DEFLATE static
Definition at line 52 of file TIFConvert.java.
final int anl.verdi.plot.io.TIFConvert.COMPRESSION_JPEG = BaselineTIFFTagSet.COMPRESSION_JPEG static
Definition at line 49 of file TIFConvert.java.
final int anl.verdi.plot.io.TIFConvert.COMPRESSION_LZW = BaselineTIFFTagSet.COMPRESSION_LZW static
Definition at line 48 of file TIFConvert.java.
final int anl.verdi.plot.io.TIFConvert.COMPRESSION_NONE = BaselineTIFFTagSet.COMPRESSION_NONE static
Definition at line 44 of file TIFConvert.java.
final int anl.verdi.plot.io.TIFConvert.COMPRESSION_PACKBITS = BaselineTIFFTagSet.COMPRESSION_PACKBITS static
Definition at line 51 of file TIFConvert.java.
final int anl.verdi.plot.io.TIFConvert.DEFAULT_COLOR = CLR_RGB static protected
Definition at line 55 of file TIFConvert.java.
Referenced by anl.verdi.plot.io.TIFConvertImage.convert().
final int anl.verdi.plot.io.TIFConvert.DEFAULT_COMPRESSION = COMPRESSION_LZW static protected
Definition at line 56 of file TIFConvert.java.
Referenced by anl.verdi.plot.io.TIFConvertImage.convert().
final float anl.verdi.plot.io.TIFConvert.DEFAULT_COMPRESSION_QUALITY = 0.25f static protected
Definition at line 57 of file TIFConvert.java.
Referenced by anl.verdi.plot.io.TIFConvert.convert(), and anl.verdi.plot.io.TIFConvertImage.convert().
final int anl.verdi.plot.io.TIFConvert.DEFAULT_DPI = 300 static protected
Definition at line 54 of file TIFConvert.java.
Referenced by anl.verdi.plot.io.TIFConvertImage.convert().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/io/TIFConvert.java