VERDI: saf.core.ui.dock.DefaultDockingManager Class Reference
saf.core.ui.dock.DefaultDockingManager Class Reference
Public Member Functions
DefaultDockingManager (GUIBarManager barManager, CControl dockingControl, List< DefaultPerspective > perspectives)
void dock (DockableFrame dockable, DockableFrame target)
void dock (DockableFrame dockable, DockableFrame relativeTo, Location location, float fillPercent)
void addDockableToGroup (String perspectiveID, String groupID, DockableFrame dockable)
Set< String > getGroupIDs (String perspectiveID)
List< DockableFrame > getDockableFrames (String perspectiveID, String groupID)
DockableFrame createDockable (String id, JComponent comp)
DockableFrame createDockable (String id, JComponent comp, MinimizeLocation hideLocation)
DockableFrame createDockable (String id, JComponent comp, MinimizeLocation location, int dockableControls)
DockableFrame getDockableFrameFor (CDockable dockable)
void init ()
void setPerspective (String perspectiveID)
List< String > getPerspectiveIDs ()
Perspective getPerspective (String id)
Perspective getPerspective ()
GUIBarManager getBarManager ()
DockableFrame getDockable (String id)
void setActiveDockable (String id)
void addDockableListener (DockableFrameListener listener)
void removeDockableListener (DockableFrameListener listener)
void addDockableSelectionListener (DockableSelectionListener listener)
void removeDockableSelectionListener (DockableSelectionListener listener)
void addPerspectiveSelectionListener (PerspectiveSelectionListener listener)
void removePerspectiveSelectionListener (PerspectiveSelectionListener listener)
Public Member Functions inherited from saf.core.ui.event.DockableFrameAdapter
void dockableClosed (DockableFrameEvent evt)
void dockableClosing (DockableFrameEvent evt)
void dockableFloated (DockableFrameEvent evt)
void dockableFloating (DockableFrameEvent evt)
void dockableMaximized (DockableFrameEvent evt)
void dockableMaximizing (DockableFrameEvent evt)
void dockableMinimized (DockableFrameEvent evt)
void dockableMinimizing (DockableFrameEvent evt)
void dockableRestored (DockableFrameEvent evt)
void dockableRestoring (DockableFrameEvent evt)
Additional Inherited Members
Public Attributes inherited from saf.core.ui.dock.DockingManager
int CLOSE = 1
int MINIMIZE = 2
int MAXIMIZE = 4
int FLOAT = 8
Detailed Description
Default implementation of a DockingManager that uses docking frames docking framework.
Author
Nick Collier
Definition at line 51 of file DefaultDockingManager.java.
Constructor & Destructor Documentation
saf.core.ui.dock.DefaultDockingManager.DefaultDockingManager (GUIBarManager barManager, CControl dockingControl, List< DefaultPerspective > perspectives)
Creates a DockingManager from the specified GUIBarManager, viewport and list of perspectives.
Parameters
barManager the bar manager used by this DockingManager
dockingControl the CControl used by this DockingManager
perspectives the list of perspectives managed by this DockingManager
Definition at line 69 of file DefaultDockingManager.java.
Member Function Documentation
void saf.core.ui.dock.DefaultDockingManager.addDockableListener (DockableFrameListener listener)
Adds a dockable frame listener to this DockingManager to listen for dockable frame events.
Parameters
listener the listener to add.
Implements saf.core.ui.dock.DockingManager.
Definition at line 381 of file DefaultDockingManager.java.
void saf.core.ui.dock.DefaultDockingManager.addDockableSelectionListener (DockableSelectionListener listener)
Adds a dockable frame selection listener to this DockingManager to listen for dockable frame selection events.
Parameters
listener the listener to add.
Implements saf.core.ui.dock.DockingManager.
Definition at line 400 of file DefaultDockingManager.java.
void saf.core.ui.dock.DefaultDockingManager.addDockableToGroup (String perspectiveID, String groupID, DockableFrame dockable)
Adds the specified dockable frame to the specified group in the specified perspective.
Parameters
perspectiveID the id of the perspective to add the dockable frame to
groupID the id of the group to add the dockable frame to
dockable the dockable frame to add
Implements saf.core.ui.dock.DockingManager.
Definition at line 137 of file DefaultDockingManager.java.
void saf.core.ui.dock.DefaultDockingManager.addPerspectiveSelectionListener (PerspectiveSelectionListener listener)
Adds a perspective selection listener to this DockingManager to listen for perspective selection events.
Parameters
listener the listener to add.
Implements saf.core.ui.dock.DockingManager.
Definition at line 418 of file DefaultDockingManager.java.
DockableFrame saf.core.ui.dock.DefaultDockingManager.createDockable (String id, JComponent comp)
Creates a Dockable frame with the specified id containing the specified component. This only creates the dockable frame. To add a created dockable frame into a window use the addDockableToGroup method.
Parameters
id the id that uniquely identifies the created Dockable frame
comp the component displayed by the dockable frame
Returns
the created dockable frame
See Also
addDockableToGroup
Implements saf.core.ui.dock.DockingManager.
Definition at line 186 of file DefaultDockingManager.java.
References saf.core.ui.dock.DockingManager.CLOSE, saf.core.ui.dock.DockingManager.FLOAT, saf.core.ui.dock.DockingManager.MAXIMIZE, saf.core.ui.dock.DockingManager.MINIMIZE, and saf.core.ui.dock.DockingManager.MinimizeLocation.UNSPECIFIED.
Referenced by saf.core.ui.dock.DefaultDockingManager.createDockable().
DockableFrame saf.core.ui.dock.DefaultDockingManager.createDockable (String id, JComponent comp, MinimizeLocation hideLocation)
Creates a dockable frame with the specified id, hide location and containing the specified component. This only creates the dockable frame. To add a created dockable frame into a window use the addDockableToGroup method.
Parameters
id the id that uniquely identifies the created Dockable frame
comp the component displayed by the dockable frame
hideLocation the location where the dockable frame is minimized to
Returns
the created dockable frame
Implements saf.core.ui.dock.DockingManager.
Definition at line 199 of file DefaultDockingManager.java.
References saf.core.ui.dock.DockingManager.CLOSE, saf.core.ui.dock.DefaultDockingManager.createDockable(), saf.core.ui.dock.DockingManager.FLOAT, saf.core.ui.dock.DockingManager.MAXIMIZE, and saf.core.ui.dock.DockingManager.MINIMIZE.
DockableFrame saf.core.ui.dock.DefaultDockingManager.createDockable (String id, JComponent comp, MinimizeLocation location, int dockableControls)
Creates a dockable frame with the specified id, hide location, window controls and containing the specified component. This only creates the dockable frame. To add a created dockable frame into a window use the addDockableToGroup method.
The dockable frame controls are:
DockingManager.CLOSE
DockingManager.HIDE
DockingManager.MAXIMIZE
DockingManager.FLOAT
These can be logically or'ed together.
Parameters
id the id that uniquely identifies the created Dockable frame
comp the component displayed by the dockable frame
location the location where the dockable frame is minimized to
dockableControls specifies what controls (close, maximize, float etc.) are displayed on the dockable frame's title bar
Returns
the created dockable frame
Implements saf.core.ui.dock.DockingManager.
Definition at line 224 of file DefaultDockingManager.java.
void saf.core.ui.dock.DefaultDockingManager.dock (DockableFrame dockable, DockableFrame target)
Attempts to dock the specified dockable to the target, stacking the dockable on top of the target. This will do nothing if the target is minimized or the dockable has not been added to a group.
Parameters
dockable the dockable to dock
target the target to dock to
Implements saf.core.ui.dock.DockingManager.
Definition at line 113 of file DefaultDockingManager.java.
void saf.core.ui.dock.DefaultDockingManager.dock (DockableFrame dockable, DockableFrame relativeTo, Location location, float fillPercent)
Attempts to dock the specified dockable in some location relative to another dockable. This will not work if relativeTo is minimized or maximized, or if the dockable hasn't been added to a group yet.
Parameters
dockable the dockable to dock
relativeTo the dockable to dock relative to
location the relative location
fillPercent the fill percent that the dockable should take up
Implements saf.core.ui.dock.DockingManager.
Definition at line 126 of file DefaultDockingManager.java.
GUIBarManager saf.core.ui.dock.DefaultDockingManager.getBarManager ()
Gets the bar manager that managers the tool, menu and status bars.
Returns
the bar manager that managers the tool, menu and status bars.
Implements saf.core.ui.dock.DockingManager.
Definition at line 317 of file DefaultDockingManager.java.
DockableFrame saf.core.ui.dock.DefaultDockingManager.getDockable (String id)
Gets the specified dockable frame by its id.
Parameters
id the id of the dockable frame to get
Returns
the specified dockable frame by its id.
Implements saf.core.ui.dock.DockingManager.
Definition at line 347 of file DefaultDockingManager.java.
DockableFrame saf.core.ui.dock.DefaultDockingManager.getDockableFrameFor (CDockable dockable)
Gets the DockableFrame associated with the specified CDockable.
Parameters
dockable the CDockable whose associated DockableFrame we want
Returns
the DockableFrame associated with the specified CDockable.
Definition at line 238 of file DefaultDockingManager.java.
List<DockableFrame> saf.core.ui.dock.DefaultDockingManager.getDockableFrames (String perspectiveID, String groupID)
Gets all the dockable frames in the specified group in the specified perspective.
Parameters
perspectiveID the id of the perspective
groupID the id the group
Returns
all the dockable frames in the specified group in the specified perspective.
Implements saf.core.ui.dock.DockingManager.
Definition at line 169 of file DefaultDockingManager.java.
Set<String> saf.core.ui.dock.DefaultDockingManager.getGroupIDs (String perspectiveID)
Gets the group ids of the groups in the specified perspective.
Parameters
perspectiveID the perspective whose groups are of interest
Returns
group ids of the groups in the specified perspective
Implements saf.core.ui.dock.DockingManager.
Definition at line 159 of file DefaultDockingManager.java.
Perspective saf.core.ui.dock.DefaultDockingManager.getPerspective (String id)
Gets the specified perspective.
Parameters
id the id of the perspective to get
Returns
the specified perspective.
Implements saf.core.ui.dock.DockingManager.
Definition at line 288 of file DefaultDockingManager.java.
Perspective saf.core.ui.dock.DefaultDockingManager.getPerspective ()
Gets the current perspective.
Returns
the current perspective
Implements saf.core.ui.dock.DockingManager.
Definition at line 296 of file DefaultDockingManager.java.
List<String> saf.core.ui.dock.DefaultDockingManager.getPerspectiveIDs ()
Gets a list of all the perspective ids.
Returns
a list of all the perspective ids.
Implements saf.core.ui.dock.DockingManager.
Definition at line 279 of file DefaultDockingManager.java.
void saf.core.ui.dock.DefaultDockingManager.init ()
Initializes the dockable frame manger by activitating the current perpspective.
Implements saf.core.ui.dock.DockingManager.
Definition at line 245 of file DefaultDockingManager.java.
References saf.core.ui.dock.DefaultPerspective.getID().
void saf.core.ui.dock.DefaultDockingManager.removeDockableListener (DockableFrameListener listener)
Removes the specified dockable frame listener.
Parameters
listener the listener to remove
Implements saf.core.ui.dock.DockingManager.
Definition at line 390 of file DefaultDockingManager.java.
void saf.core.ui.dock.DefaultDockingManager.removeDockableSelectionListener (DockableSelectionListener listener)
Removes the specified dockable frame selection listener.
Parameters
listener the listener to remove
Implements saf.core.ui.dock.DockingManager.
Definition at line 408 of file DefaultDockingManager.java.
void saf.core.ui.dock.DefaultDockingManager.removePerspectiveSelectionListener (PerspectiveSelectionListener listener)
Removes the specified perspective selection listener.
Parameters
listener the listener to remove
Implements saf.core.ui.dock.DockingManager.
Definition at line 426 of file DefaultDockingManager.java.
void saf.core.ui.dock.DefaultDockingManager.setActiveDockable (String id)
Sets the specified dockable frame as the active dockable frame.
Parameters
id the id of the dockable frame to make the active dockable frame
Definition at line 355 of file DefaultDockingManager.java.
void saf.core.ui.dock.DefaultDockingManager.setPerspective (String perspectiveID)
Sets the specified perspective as the currently active perspective.
Parameters
perspectiveID the id of the perspective to set
Implements saf.core.ui.dock.DockingManager.
Definition at line 271 of file DefaultDockingManager.java.
References saf.core.ui.dock.DefaultPerspective.getID().
The documentation for this class was generated from the following file:
verdi_saf_ui/src/saf/core/ui/dock/DefaultDockingManager.java