VERDI: anl.verdi.data.AbstractDataset Class Reference
anl.verdi.data.AbstractDataset Class Reference abstract
Public Member Functions
URL getURL ()
String getAlias ()
void setAlias (String alias)
List< String > getVariableNames ()
Variable getVariable (String name)
List< Variable > getVariables ()
Axes< CoordAxis > getCoordAxes ()
boolean hasTimeAxis ()
boolean hasXAxis ()
boolean hasYAxis ()
boolean hasZAxis ()
String getName ()
void close () throws IOException
boolean isObs ()
Public Member Functions inherited from anl.verdi.data.Dataset
int getIndexInURL ()
DatasetMetadata getMetadata ()
int getNetcdfCovn ()
void setNetcdfConv (int conv)
Protected Member Functions
AbstractDataset (URL url)
Protected Attributes
String alias = NULL_ALIAS
URL url
Additional Inherited Members
Static Public Attributes inherited from anl.verdi.data.Dataset
static final String NULL_ALIAS = "anl.verdi.data.DataSet.NULL_ALIAS"
static final int SINGLE_DATASET = -1
Detailed Description
Abstract implementation of a Dataset
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 14 of file AbstractDataset.java.
Constructor & Destructor Documentation
anl.verdi.data.AbstractDataset.AbstractDataset (URL url) protected
Creates an AbstractDataset.
Parameters
url the url of the dataset
Definition at line 25 of file AbstractDataset.java.
References anl.verdi.data.AbstractDataset.url.
Member Function Documentation
void anl.verdi.data.AbstractDataset.close () throws IOException
Closes this dataset. It will have to be recreated to be used again.
Implements anl.verdi.data.Dataset.
Definition at line 128 of file AbstractDataset.java.
String anl.verdi.data.AbstractDataset.getAlias ()
Gets the alias of this Dataset. If no alias has been assigned the alias will be NULL_ALIAS.
Returns
the alias of this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 44 of file AbstractDataset.java.
References anl.verdi.data.AbstractDataset.alias.
Referenced by anl.verdi.loaders.GridNetcdfDataset.setAlias(), anl.verdi.loaders.Models3ObsDataset.setAlias(), and anl.verdi.loaders.CSVDataset.setAlias().
Axes<CoordAxis> anl.verdi.data.AbstractDataset.getCoordAxes ()
Gets the coordindate Axes for this Dataset.
Returns
the coordindate Axes for this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 80 of file AbstractDataset.java.
Referenced by anl.verdi.data.AbstractDataset.hasTimeAxis(), anl.verdi.data.AbstractDataset.hasXAxis(), anl.verdi.data.AbstractDataset.hasYAxis(), and anl.verdi.data.AbstractDataset.hasZAxis().
String anl.verdi.data.AbstractDataset.getName ()
Gets the name of this Dataset. NOTE: Always returns an empty String.
Returns
the name of this Dataset;
Implements anl.verdi.data.Dataset.
Definition at line 120 of file AbstractDataset.java.
URL anl.verdi.data.AbstractDataset.getURL ()
Gets the url of this Dataset.
Returns
the url of this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 34 of file AbstractDataset.java.
References anl.verdi.data.AbstractDataset.url.
Variable anl.verdi.data.AbstractDataset.getVariable (String name)
Gets the named variable. NOTE: Always returns NULL.
Parameters
name the name of the variable to get
Returns
the named variable
Implements anl.verdi.data.Dataset.
Definition at line 67 of file AbstractDataset.java.
List<String> anl.verdi.data.AbstractDataset.getVariableNames ()
Gets the list of variable names in this Dataset.
Returns
the list of variable names in this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 57 of file AbstractDataset.java.
List<Variable> anl.verdi.data.AbstractDataset.getVariables ()
Gets the list of variables in this Dataset.
Returns
the list of variables in this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 71 of file AbstractDataset.java.
boolean anl.verdi.data.AbstractDataset.hasTimeAxis ()
Returns
true if there is a time axis, otherwise false
Implements anl.verdi.data.Dataset.
Definition at line 87 of file AbstractDataset.java.
References anl.verdi.data.AbstractDataset.getCoordAxes().
boolean anl.verdi.data.AbstractDataset.hasXAxis ()
Returns
true if there is a X axis, otherwise false
Implements anl.verdi.data.Dataset.
Definition at line 94 of file AbstractDataset.java.
References anl.verdi.data.AbstractDataset.getCoordAxes().
boolean anl.verdi.data.AbstractDataset.hasYAxis ()
Returns
true if there is a Y axis, otherwise false
Implements anl.verdi.data.Dataset.
Definition at line 101 of file AbstractDataset.java.
References anl.verdi.data.AbstractDataset.getCoordAxes().
boolean anl.verdi.data.AbstractDataset.hasZAxis ()
See if there is a z (e.g. layer) axis
Returns
true if there is a Z axis, otherwise false
Implements anl.verdi.data.Dataset.
Definition at line 110 of file AbstractDataset.java.
References anl.verdi.data.AbstractDataset.getCoordAxes().
boolean anl.verdi.data.AbstractDataset.isObs ()
Whether or not this dataset represents an observational dataset. NOTE: Always returns FALSE.
Returns
true if this contains obs data, otherwise false.
Implements anl.verdi.data.Dataset.
Definition at line 136 of file AbstractDataset.java.
void anl.verdi.data.AbstractDataset.setAlias (String alias)
Sets the alias for this Dataset.
Parameters
alias the alias for this Dataset.
Implements anl.verdi.data.Dataset.
Definition at line 53 of file AbstractDataset.java.
References anl.verdi.data.AbstractDataset.alias.
Member Data Documentation
String anl.verdi.data.AbstractDataset.alias = NULL_ALIAS protected
Definition at line 16 of file AbstractDataset.java.
Referenced by anl.verdi.data.AbstractDataset.getAlias(), anl.verdi.data.AbstractDataset.setAlias(), anl.verdi.loaders.GridNetcdfDataset.setAlias(), anl.verdi.loaders.Models3ObsDataset.setAlias(), and anl.verdi.loaders.CSVDataset.setAlias().
URL anl.verdi.data.AbstractDataset.url protected
Definition at line 17 of file AbstractDataset.java.
Referenced by anl.verdi.data.AbstractDataset.AbstractDataset(), anl.verdi.loaders.CSVDataset.CSVDataset(), anl.verdi.data.AbstractDataset.getURL(), and anl.verdi.loaders.GridNetcdfDataset.GridNetcdfDataset().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/data/AbstractDataset.java