VERDI: anl.verdi.plot.data.CrossSectionXYZDataset Class Reference
anl.verdi.plot.data.CrossSectionXYZDataset Class Reference
Public Member Functions
double getValue (int series, int x, int y)
void addColSeries (DataFrame frame, int timeStep, int constantCol)
void addRowSeries (DataFrame frame, int timeStep, int constantRow)
Number getZ (int series, int item)
double getZValue (int series, int item)
DomainOrder getDomainOrder ()
int getItemCount (int series)
Number getX (int series, int item)
double getXValue (int series, int item)
Number getY (int series, int item)
double getYValue (int series, int item)
int getSeriesCount ()
Comparable getSeriesKey (int series)
int indexOf (Comparable seriesKey)
Detailed Description
JChart XYZDataset implemented in terms of a DataFrame for a vertical cross-section. Vertical cross section shows the values at each layer for some constant row or col value.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 22 of file CrossSectionXYZDataset.java.
Member Function Documentation
void anl.verdi.plot.data.CrossSectionXYZDataset.addColSeries (DataFrame frame, int timeStep, int constantCol)
Definition at line 190 of file CrossSectionXYZDataset.java.
void anl.verdi.plot.data.CrossSectionXYZDataset.addRowSeries (DataFrame frame, int timeStep, int constantRow)
Definition at line 206 of file CrossSectionXYZDataset.java.
DomainOrder anl.verdi.plot.data.CrossSectionXYZDataset.getDomainOrder ()
Returns the order of the domain (or X) values returned by the dataset.
Returns
The order (never null).
Definition at line 239 of file CrossSectionXYZDataset.java.
int anl.verdi.plot.data.CrossSectionXYZDataset.getItemCount (int series)
Returns the number of items in a series.
It is recommended that classes that implement this method should throw an IllegalArgumentException if the series argument is outside the specified range.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
Returns
The item count.
Definition at line 254 of file CrossSectionXYZDataset.java.
int anl.verdi.plot.data.CrossSectionXYZDataset.getSeriesCount ()
Returns the number of series in the dataset.
Returns
The series count.
Definition at line 324 of file CrossSectionXYZDataset.java.
Referenced by anl.verdi.plot.data.CrossSectionXYZDataset.getSeriesKey().
Comparable anl.verdi.plot.data.CrossSectionXYZDataset.getSeriesKey (int series)
Returns the key for a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
Returns
The key for the series.
Definition at line 335 of file CrossSectionXYZDataset.java.
References anl.verdi.plot.data.CrossSectionXYZDataset.getSeriesCount().
double anl.verdi.plot.data.CrossSectionXYZDataset.getValue (int series, int x, int y)
Gets the value for the series at the specified x, y coordinate.
Parameters
series the series
x x coordinate
y y coordinate
Returns
the value for the series at the specified x, y coordinate.
Definition at line 185 of file CrossSectionXYZDataset.java.
Number anl.verdi.plot.data.CrossSectionXYZDataset.getX (int series, int item)
Returns the x-value for an item within a series. The x-values may or may not be returned in ascending order, that is up to the class implementing the interface.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The x-value (never null).
Definition at line 269 of file CrossSectionXYZDataset.java.
References anl.verdi.plot.data.CrossSectionXYZDataset.getXValue().
double anl.verdi.plot.data.CrossSectionXYZDataset.getXValue (int series, int item)
Returns the x-value for an item within a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The x-value.
Definition at line 282 of file CrossSectionXYZDataset.java.
Referenced by anl.verdi.plot.data.CrossSectionXYZDataset.getX().
Number anl.verdi.plot.data.CrossSectionXYZDataset.getY (int series, int item)
Returns the y-value for an item within a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The y-value (possibly null).
Definition at line 301 of file CrossSectionXYZDataset.java.
References anl.verdi.plot.data.CrossSectionXYZDataset.getYValue().
double anl.verdi.plot.data.CrossSectionXYZDataset.getYValue (int series, int item)
Returns the y-value (as a double primitive) for an item within a series.
Parameters
series the series index (in the range 0 to getSeriesCount() - 1).
item the item index (in the range 0 to getItemCount(series)).
Returns
The y-value.
Definition at line 314 of file CrossSectionXYZDataset.java.
Referenced by anl.verdi.plot.data.CrossSectionXYZDataset.getY().
Number anl.verdi.plot.data.CrossSectionXYZDataset.getZ (int series, int item)
Returns the z-value for the specified series and item.
Parameters
series the series index (zero-based).
item the item index (zero-based).
Returns
The z-value (possibly null).
Definition at line 218 of file CrossSectionXYZDataset.java.
References anl.verdi.plot.data.CrossSectionXYZDataset.getZValue().
double anl.verdi.plot.data.CrossSectionXYZDataset.getZValue (int series, int item)
Returns the z-value (as a double primitive) for an item within a series.
Parameters
series the series (zero-based index).
item the item (zero-based index).
Returns
The z-value.
Definition at line 229 of file CrossSectionXYZDataset.java.
Referenced by anl.verdi.plot.data.CrossSectionXYZDataset.getZ().
int anl.verdi.plot.data.CrossSectionXYZDataset.indexOf (Comparable seriesKey)
Returns the index of the series with the specified key, or -1 if there is no such series in the dataset.
Parameters
seriesKey the series key (null permitted).
Returns
The index, or -1.
Definition at line 350 of file CrossSectionXYZDataset.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/data/CrossSectionXYZDataset.java