VERDI: anl.verdi.plot.gui.ObsAnnotation Class Reference
anl.verdi.plot.gui.ObsAnnotation Class Reference
Classes
enum Symbol
Public Member Functions
ObsAnnotation (ObsEvaluator eval, Axes< DataFrameAxis > axes, int timeStep, int layer)
ObsAnnotation (ObsEvaluator eval, Axes< DataFrameAxis > axes, Date date, int layer)
ObsAnnotation (ObsEvaluator eval, Axes< DataFrameAxis > axes, GregorianCalendar aCalendar, int layer)
void setDrawingParams (int stroke, int size, ColorMap cMap)
void setDrawingParams (Symbol symb, int stroke, int size, ColorMap cMap)
synchronized void update (int timeStep)
synchronized void update (Date date)
void draw (Graphics2D g2d, XYPlot plot, Rectangle2D rect, ValueAxis domainAxis, ValueAxis rangeAxis, int rendererIndex, PlotRenderingInfo info)
synchronized void draw (Graphics graphics, int xOffset, int yOffset, int width, int height, double[] legendLevels, Color[] legendColors, final CoordinateReferenceSystem gridCRS, final double[][] domain, final double[][] gridBounds)
void updateMap (ColorMap map)
int getShapeSize ()
int getStrokeSize ()
Symbol getSymbol ()
List< ObsData > getData ()
void setID (String id)
String getID ()
String getVarString ()
boolean equals (ObsAnnotation other)
Detailed Description
Definition at line 41 of file ObsAnnotation.java.
Constructor & Destructor Documentation
anl.verdi.plot.gui.ObsAnnotation.ObsAnnotation (ObsEvaluator eval, Axes< DataFrameAxis > axes, int timeStep, int layer)
Definition at line 64 of file ObsAnnotation.java.
References anl.verdi.plot.gui.ObsAnnotation.update().
anl.verdi.plot.gui.ObsAnnotation.ObsAnnotation (ObsEvaluator eval, Axes< DataFrameAxis > axes, Date date, int layer)
Definition at line 72 of file ObsAnnotation.java.
References anl.verdi.plot.gui.ObsAnnotation.update().
anl.verdi.plot.gui.ObsAnnotation.ObsAnnotation (ObsEvaluator eval, Axes< DataFrameAxis > axes, GregorianCalendar aCalendar, int layer)
Definition at line 79 of file ObsAnnotation.java.
References anl.verdi.plot.gui.ObsAnnotation.update().
Member Function Documentation
void anl.verdi.plot.gui.ObsAnnotation.draw (Graphics2D g2d, XYPlot plot, Rectangle2D rect, ValueAxis domainAxis, ValueAxis rangeAxis, int rendererIndex, PlotRenderingInfo info)
Definition at line 141 of file ObsAnnotation.java.
synchronized void anl.verdi.plot.gui.ObsAnnotation.draw (Graphics graphics, int xOffset, int yOffset, int width, int height, double[] legendLevels, Color[] legendColors, final CoordinateReferenceSystem gridCRS, final double domain[][], final double gridBounds[][])
drawObsData - draw observational data
Parameters
graphics
xminimum
xmaximum
yminimum
ymaximum
legendLevels
legendColors
Definition at line 198 of file ObsAnnotation.java.
boolean anl.verdi.plot.gui.ObsAnnotation.equals (ObsAnnotation other)
Definition at line 346 of file ObsAnnotation.java.
References anl.verdi.plot.gui.ObsAnnotation.getID().
List<ObsData> anl.verdi.plot.gui.ObsAnnotation.getData ()
Definition at line 327 of file ObsAnnotation.java.
String anl.verdi.plot.gui.ObsAnnotation.getID ()
Definition at line 335 of file ObsAnnotation.java.
Referenced by anl.verdi.plot.gui.ObsAnnotation.equals().
int anl.verdi.plot.gui.ObsAnnotation.getShapeSize ()
Definition at line 315 of file ObsAnnotation.java.
int anl.verdi.plot.gui.ObsAnnotation.getStrokeSize ()
Definition at line 319 of file ObsAnnotation.java.
Symbol anl.verdi.plot.gui.ObsAnnotation.getSymbol ()
Definition at line 323 of file ObsAnnotation.java.
String anl.verdi.plot.gui.ObsAnnotation.getVarString ()
Definition at line 339 of file ObsAnnotation.java.
References anl.verdi.data.Dataset.getAlias().
void anl.verdi.plot.gui.ObsAnnotation.setDrawingParams (int stroke, int size, ColorMap cMap)
Definition at line 87 of file ObsAnnotation.java.
References anl.verdi.plot.gui.ObsAnnotation.Symbol.CIRCLE.
Referenced by anl.verdi.plot.gui.ObsAnnotation.updateMap().
void anl.verdi.plot.gui.ObsAnnotation.setDrawingParams (Symbol symb, int stroke, int size, ColorMap cMap)
Definition at line 94 of file ObsAnnotation.java.
void anl.verdi.plot.gui.ObsAnnotation.setID (String id)
Definition at line 331 of file ObsAnnotation.java.
synchronized void anl.verdi.plot.gui.ObsAnnotation.update (int timeStep)
Definition at line 116 of file ObsAnnotation.java.
Referenced by anl.verdi.plot.gui.ObsAnnotation.ObsAnnotation().
synchronized void anl.verdi.plot.gui.ObsAnnotation.update (Date date)
Definition at line 121 of file ObsAnnotation.java.
void anl.verdi.plot.gui.ObsAnnotation.updateMap (ColorMap map)
Definition at line 311 of file ObsAnnotation.java.
References anl.verdi.plot.gui.ObsAnnotation.setDrawingParams().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/gui/ObsAnnotation.java