VERDI: anl.verdi.area.FileHelper Class Reference
anl.verdi.area.FileHelper Class Reference
Static Public Member Functions
static String convertMultiLineString (String string)
static String convertDoubleToString (double number)
static String getFileBaseName (String fileName)
static String formDatabaseString (String string)
static String formQuoteString (String string, char quoteChar)
static String formString (String string)
static Vector readData (File filename)
static Vector readData (String filename)
static Vector readDataLines (String filename)
static Vector readDataLines (File filename)
static Vector readDataLines (BufferedReader input)
static Vector readDataStream (Reader is)
static void writeDataLines (String filename, Vector data)
static void writeFixedDataLines (String filename, Vector data)
Detailed Description
Definition at line 29 of file FileHelper.java.
Member Function Documentation
static String anl.verdi.area.FileHelper.convertDoubleToString (double number) static
Definition at line 48 of file FileHelper.java.
static String anl.verdi.area.FileHelper.convertMultiLineString (String string) static
Definition at line 32 of file FileHelper.java.
static String anl.verdi.area.FileHelper.formDatabaseString (String string) static
Definition at line 80 of file FileHelper.java.
References anl.verdi.area.FileHelper.formQuoteString().
static String anl.verdi.area.FileHelper.formQuoteString (String string, char quoteChar) static
Definition at line 83 of file FileHelper.java.
Referenced by anl.verdi.area.FileHelper.formDatabaseString(), and anl.verdi.area.FileHelper.formString().
static String anl.verdi.area.FileHelper.formString (String string) static
Definition at line 107 of file FileHelper.java.
References anl.verdi.area.FileHelper.formQuoteString().
static String anl.verdi.area.FileHelper.getFileBaseName (String fileName) static
Gets the main part of the filename without path or final extension
Parameters
fileName String holding the complete name of the file
Returns
the basename of the filename
Definition at line 62 of file FileHelper.java.
static Vector anl.verdi.area.FileHelper.readData (File filename) static
Definition at line 110 of file FileHelper.java.
References anl.verdi.area.FileHelper.readDataStream().
static Vector anl.verdi.area.FileHelper.readData (String filename) static
Definition at line 121 of file FileHelper.java.
References anl.verdi.area.FileHelper.readDataStream().
static Vector anl.verdi.area.FileHelper.readDataLines (String filename) static
Definition at line 132 of file FileHelper.java.
Referenced by anl.verdi.area.target.RegionNames.loadData(), anl.verdi.area.target.RegionNames.loadDefaultData(), and anl.verdi.area.FileHelper.readDataLines().
static Vector anl.verdi.area.FileHelper.readDataLines (File filename) static
Definition at line 145 of file FileHelper.java.
References anl.verdi.area.FileHelper.readDataLines().
static Vector anl.verdi.area.FileHelper.readDataLines (BufferedReader input) static
Definition at line 158 of file FileHelper.java.
static Vector anl.verdi.area.FileHelper.readDataStream (Reader is) static
Definition at line 186 of file FileHelper.java.
Referenced by anl.verdi.area.FileHelper.readData().
static void anl.verdi.area.FileHelper.writeDataLines (String filename, Vector data) static
Definition at line 285 of file FileHelper.java.
static void anl.verdi.area.FileHelper.writeFixedDataLines (String filename, Vector data) static
Definition at line 317 of file FileHelper.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/FileHelper.java