VERDI: anl.verdi.loaders.ExtendCSVCoordAxis Class Reference
anl.verdi.loaders.ExtendCSVCoordAxis Class Reference
Public Member Functions
ExtendCSVCoordAxis (Object data[], String name, String description, AxisType type)
Object getValue (int index)
Unit getUnits ()
boolean isCompatible (ExtendCoordAxis axis)
String getDescription ()
String getName ()
Range getRange ()
AxisType getAxisType ()
Protected Attributes
String name
Object data []
Detailed Description
Definition at line 14 of file ExtendCSVCoordAxis.java.
Constructor & Destructor Documentation
anl.verdi.loaders.ExtendCSVCoordAxis.ExtendCSVCoordAxis (Object data[], String name, String description, AxisType type)
Definition at line 23 of file ExtendCSVCoordAxis.java.
References anl.verdi.loaders.ExtendCSVCoordAxis.data, anl.verdi.util.VUnits.MISSING_UNIT, and anl.verdi.loaders.ExtendCSVCoordAxis.name.
Member Function Documentation
AxisType anl.verdi.loaders.ExtendCSVCoordAxis.getAxisType ()
Gets the type of this axis.
Returns
the type of this axis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 114 of file ExtendCSVCoordAxis.java.
String anl.verdi.loaders.ExtendCSVCoordAxis.getDescription ()
Gets the description of this CoordAxis.
Returns
the description of this CoordAxis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 86 of file ExtendCSVCoordAxis.java.
String anl.verdi.loaders.ExtendCSVCoordAxis.getName ()
Gets the name of this CoordAxis.
Returns
the name of this CoordAxis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 95 of file ExtendCSVCoordAxis.java.
References anl.verdi.loaders.ExtendCSVCoordAxis.name.
Range anl.verdi.loaders.ExtendCSVCoordAxis.getRange ()
Gets the range of this axis.
Returns
the range of this axis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 104 of file ExtendCSVCoordAxis.java.
Unit anl.verdi.loaders.ExtendCSVCoordAxis.getUnits ()
Gets the unit of measurement for this coordinate axis.
Returns
the unit of measurement for this coordinate axis.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 49 of file ExtendCSVCoordAxis.java.
Object anl.verdi.loaders.ExtendCSVCoordAxis.getValue (int index)
Gets the value at the specified index.
Returns
the value at the specified index.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 40 of file ExtendCSVCoordAxis.java.
References anl.verdi.loaders.ExtendCSVCoordAxis.data.
Referenced by anl.verdi.loaders.ExtendCSVCoordAxis.isCompatible().
boolean anl.verdi.loaders.ExtendCSVCoordAxis.isCompatible (ExtendCoordAxis axis)
Gets whether or not the this axis is compatible with the specified axis. Two axes are compatible if they can be used together in the same formula.
Parameters
axis the axis to check for compatibility
Returns
true if this axis is compatibilty with the other axis, otherise false.
Implements anl.verdi.data.ExtendCoordAxis.
Definition at line 63 of file ExtendCSVCoordAxis.java.
References anl.verdi.data.ExtendCoordAxis.getAxisType(), anl.verdi.data.ExtendCoordAxis.getRange(), and anl.verdi.loaders.ExtendCSVCoordAxis.getValue().
Member Data Documentation
Object anl.verdi.loaders.ExtendCSVCoordAxis.data[] protected
Definition at line 21 of file ExtendCSVCoordAxis.java.
Referenced by anl.verdi.loaders.ExtendCSVCoordAxis.ExtendCSVCoordAxis(), anl.verdi.loaders.ExtendCSVTimeAxis.getDate(), anl.verdi.loaders.ExtendCSVTimeAxis.getTimeStep(), and anl.verdi.loaders.ExtendCSVCoordAxis.getValue().
String anl.verdi.loaders.ExtendCSVCoordAxis.name protected
Definition at line 20 of file ExtendCSVCoordAxis.java.
Referenced by anl.verdi.loaders.ExtendCSVCoordAxis.ExtendCSVCoordAxis(), and anl.verdi.loaders.ExtendCSVCoordAxis.getName().
The documentation for this class was generated from the following file:
verdi_data_loaders/src/anl/verdi/loaders/ExtendCSVCoordAxis.java