VERDI: saf.core.ui.event.DockableFrameEvent Class Reference
saf.core.ui.event.DockableFrameEvent Class Reference
Classes
enum Type
Public Member Functions
DockableFrameEvent (Type type, DockableFrame dockable)
Type getType ()
DockableFrame getDockable ()
boolean isHandled ()
void setHandled (boolean handled)
Detailed Description
Encapsulates an event that occured on DockableFrame.
Author
Nick Collier
Version
Revision:
1.2
Date:
2005/11/21 18:55:17
Definition at line 11 of file DockableFrameEvent.java.
Constructor & Destructor Documentation
saf.core.ui.event.DockableFrameEvent.DockableFrameEvent (Type type, DockableFrame dockable)
Creates a DockableFrameEvent of the specified type occuring on the specified dockable frame.
Parameters
type the event type
dockable the dockable the event occured on
Definition at line 26 of file DockableFrameEvent.java.
Member Function Documentation
DockableFrame saf.core.ui.event.DockableFrameEvent.getDockable ()
Gets the dockable that is the subject of this event.
Returns
the dockable that is the subject of this event.
Definition at line 47 of file DockableFrameEvent.java.
Referenced by saf.core.ui.dock.StateChanger.closeDockable(), saf.core.ui.dock.StateChanger.floatDockable(), saf.core.ui.dock.StateChanger.maximizeDockable(), saf.core.ui.dock.StateChanger.minimizeDockable(), and saf.core.ui.dock.StateChanger.restoreDockable().
Type saf.core.ui.event.DockableFrameEvent.getType ()
Gets the type of event.
Returns
the type of event.
Definition at line 36 of file DockableFrameEvent.java.
boolean saf.core.ui.event.DockableFrameEvent.isHandled ()
Gets whether or not this event has been handled.
Returns
whether or not this event has been handled.
Definition at line 56 of file DockableFrameEvent.java.
Referenced by saf.core.ui.dock.StateChanger.closeDockable(), saf.core.ui.dock.StateChanger.floatDockable(), saf.core.ui.dock.StateChanger.maximizeDockable(), saf.core.ui.dock.StateChanger.minimizeDockable(), and saf.core.ui.dock.StateChanger.restoreDockable().
void saf.core.ui.event.DockableFrameEvent.setHandled (boolean handled)
Sets whether or not this event has been handled.
Parameters
handled whether or not this event has been handled.
Definition at line 65 of file DockableFrameEvent.java.
The documentation for this class was generated from the following file:
verdi_saf_ui/src/saf/core/ui/event/DockableFrameEvent.java