VERDI: anl.verdi.plot.probe.VerticalCrossProbeCreator Class Reference
anl.verdi.plot.probe.VerticalCrossProbeCreator Class Reference
Public Member Functions
VerticalCrossProbeCreator (DataFrame frame, Slice slice, boolean isXConst)
TableModel createTableModel ()
String getName ()
String getRangeAxisName ()
Detailed Description
A probe creator for probing VerticalCrossSection plots.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 17 of file VerticalCrossProbeCreator.java.
Constructor & Destructor Documentation
anl.verdi.plot.probe.VerticalCrossProbeCreator.VerticalCrossProbeCreator (DataFrame frame, Slice slice, boolean isXConst)
Definition at line 23 of file VerticalCrossProbeCreator.java.
References anl.verdi.data.Slice.getLayerRange(), anl.verdi.plot.probe.VerticalCrossProbeCreator.getName(), anl.verdi.data.Slice.getXRange(), and anl.verdi.data.Slice.getYRange().
Member Function Documentation
TableModel anl.verdi.plot.probe.VerticalCrossProbeCreator.createTableModel ()
Creates the probe.
Implements anl.verdi.plot.probe.ProbeCreator.
Definition at line 66 of file VerticalCrossProbeCreator.java.
String anl.verdi.plot.probe.VerticalCrossProbeCreator.getName ()
Gets the name of the probe.
Returns
the name of the probe.
Implements anl.verdi.plot.probe.ProbeCreator.
Definition at line 76 of file VerticalCrossProbeCreator.java.
Referenced by anl.verdi.plot.probe.VerticalCrossProbeCreator.VerticalCrossProbeCreator().
String anl.verdi.plot.probe.VerticalCrossProbeCreator.getRangeAxisName ()
Gets the name of the range axis.
Returns
the name of the range axis.
Implements anl.verdi.plot.probe.ProbeCreator.
Definition at line 86 of file VerticalCrossProbeCreator.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/probe/VerticalCrossProbeCreator.java