VERDI: anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis > Class Reference
anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis > Class Reference
Public Member Functions
ExtendAxes ()
ExtendAxes (List< T > axes, BoundingBoxer boxer)
ExtendAxes (List< T > axes)
ReferencedEnvelope getBoundingBox (int netcdfConv)
BoundingBoxer getBoundingBoxer ()
ReferencedEnvelope getBoundingBox (Range xRange, Range yRange, int netcdfConv)
Projection getProjection ()
Date getDate (int timestep)
Date getStartDate ()
Date getEndDate ()
int getTimeStep (Date date)
List< T > getAxes ()
T getZAxis ()
T getTimeAxis ()
T getXAxis ()
T getYAxis ()
T getAxis (int index)
T getAxis (String name)
Static Public Attributes
static final int TIME_STEP_NOT_FOUND = -1
Detailed Description
Definition at line 14 of file ExtendAxes.java.
Constructor & Destructor Documentation
anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.ExtendAxes ()
Creates an empty set of axes.
Definition at line 26 of file ExtendAxes.java.
anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.ExtendAxes (List< T > axes, BoundingBoxer boxer)
Definition at line 28 of file ExtendAxes.java.
anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.ExtendAxes (List< T > axes)
Definition at line 33 of file ExtendAxes.java.
References anl.verdi.data.AxisType.LAYER, anl.verdi.data.AxisType.TIME, anl.verdi.data.AxisType.X_AXIS, and anl.verdi.data.AxisType.Y_AXIS.
Member Function Documentation
List<T> anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getAxes ()
Gets all the axis in this Axes object.
Returns
all the axis in this Axes object.
Definition at line 177 of file ExtendAxes.java.
T anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getAxis (int index)
Definition at line 217 of file ExtendAxes.java.
T anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getAxis (String name)
Definition at line 221 of file ExtendAxes.java.
ReferencedEnvelope anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getBoundingBox (int netcdfConv)
Gets the geographical bounding box as defined by the x and y axis. This may be null if the individual axes contained by this Axes do not define a bounding box.
Parameters
netcdfConv TODO
Returns
the geographical bounding box as defined by the x and y axis. This may be null if the individual axes contained by this Axes do not define a bounding box.
Definition at line 57 of file ExtendAxes.java.
References anl.verdi.data.Range.getUpperBound().
ReferencedEnvelope anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getBoundingBox (Range xRange, Range yRange, int netcdfConv)
Gets the geographical bounding box as defined by the specified ranges. This may be null if the individual axes contained by this Axes do not define a bounding box. The ranges are in grid cell coordinates.
Parameters
xRange the range along the x dimension in grid cell coordinates
yRange the range along the y dimension in grid cell coordinates
netcdfConv TODO
Returns
the geographical bounding box as defined by specified ranges.
Definition at line 90 of file ExtendAxes.java.
References anl.verdi.data.Range.getUpperBound().
BoundingBoxer anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getBoundingBoxer ()
Gets the bounding boxer that this Axes uses to create its bounding box.
Returns
the bounding boxer that this Axes uses to create its bounding box.
Definition at line 75 of file ExtendAxes.java.
Date anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getDate (int timestep)
Returns the Date for the specified timestep. If we are unable to parse the time step axis sufficient to create a date then this returns null.
Parameters
timestep the time step we want the date for.
Returns
the Date for the specified timestep, or null if there is no time axis, or null if unable to parse the time axis units.
Definition at line 116 of file ExtendAxes.java.
Date anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getEndDate ()
Gets the ending date of the time axis.
Returns
the ending date of the time axis.
Definition at line 149 of file ExtendAxes.java.
References anl.verdi.data.Range.getExtent(), and anl.verdi.data.Range.getOrigin().
Projection anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getProjection ()
Gets the projection, if any, associated with the current Data.
Definition at line 102 of file ExtendAxes.java.
Date anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getStartDate ()
Gets the starting date of the time axis.
Returns
the starting date of the time axis.
Definition at line 134 of file ExtendAxes.java.
T anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getTimeAxis ()
Gets meta data for the time axis.
Returns
the metadata for the time axis or null if it doesn't exist.
Definition at line 195 of file ExtendAxes.java.
int anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getTimeStep (Date date)
Gets the timestep that corresponds to the specified date. If no such timestep is found then return TIME_STEP_NOT_FOUND.
Parameters
date the date whose time step we want
Returns
the timestep that corresponds to the specified date. If no such timestep is found then return TIME_STEP_NOT_FOUND.
Definition at line 166 of file ExtendAxes.java.
T anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getXAxis ()
Gets meta data for the x-axis.
Returns
the metadata for the x-axis or null if it doesn't exist.
Definition at line 204 of file ExtendAxes.java.
T anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getYAxis ()
Gets meta data for the y-axis.
Returns
the metadata for the y-axis or null if it doesn't exist.
Definition at line 213 of file ExtendAxes.java.
T anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.getZAxis ()
Gets meta data for the z or layer axis.
Returns
the metadata for the z axis or null if it doesn't exist.
Definition at line 186 of file ExtendAxes.java.
Member Data Documentation
final int anl.verdi.data.ExtendAxes< T extends ExtendCoordAxis >.TIME_STEP_NOT_FOUND = -1 static
Definition at line 16 of file ExtendAxes.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/data/ExtendAxes.java