VERDI: anl.verdi.parser.ParserTokenManager Class Reference
anl.verdi.parser.ParserTokenManager Class Reference
Public Member Functions
ParserTokenManager (SimpleCharStream stream)
ParserTokenManager (SimpleCharStream stream, int lexState)
void ReInit (SimpleCharStream stream)
void ReInit (SimpleCharStream stream, int lexState)
void SwitchTo (int lexState)
Token getNextToken ()
Static Public Attributes
static final String[] jjstrLiteralImages
static final String[] lexStateNames
Protected Member Functions
Token jjFillToken ()
Protected Attributes
SimpleCharStream input_stream
char curChar
Additional Inherited Members
Public Attributes inherited from anl.verdi.parser.ParserConstants
int EOF = 0
int INTEGER_LITERAL = 7
int FLOAT = 8
int EXPONENT = 9
int DECIMAL_LITERAL = 10
int GREATER = 11
int LESS = 12
int EQEQUAL = 13
int EQLESS = 14
int EQGREATER = 15
int NOT_EQUAL = 16
int OR = 17
int AND = 18
int PLUS = 19
int MINUS = 20
int TIMES = 21
int DIV = 22
int MOD = 23
int POW = 24
int ABS = 25
int SQRT = 26
int SQR = 27
int LOG = 28
int EXP = 29
int LN = 30
int SIN = 31
int COS = 32
int TAN = 33
int SIND = 34
int COSD = 35
int TAND = 36
int MEAN = 37
int SUM = 38
int MINT = 39
int MAXT = 40
int MINX = 41
int MAXX = 42
int MINY = 43
int MAXY = 44
int MINZ = 45
int MAXZ = 46
int MIN = 47
int MAX = 48
int E = 49
int PI = 50
int NROWS = 51
int NCOLS = 52
int NLAYERS = 53
int IDENTIFIER = 57
int LETTER = 58
int DIGIT = 59
int DEFAULT = 0
String[] tokenImage
Detailed Description
Definition at line 4 of file ParserTokenManager.java.
Constructor & Destructor Documentation
anl.verdi.parser.ParserTokenManager.ParserTokenManager (SimpleCharStream stream)
Definition at line 777 of file ParserTokenManager.java.
References anl.verdi.parser.ParserTokenManager.input_stream, and anl.verdi.parser.SimpleCharStream.staticFlag.
anl.verdi.parser.ParserTokenManager.ParserTokenManager (SimpleCharStream stream, int lexState)
Definition at line 782 of file ParserTokenManager.java.
References anl.verdi.parser.ParserTokenManager.SwitchTo().
Member Function Documentation
Token anl.verdi.parser.ParserTokenManager.getNextToken ()
Definition at line 833 of file ParserTokenManager.java.
References anl.verdi.parser.SimpleCharStream.BeginToken(), anl.verdi.parser.ParserTokenManager.curChar, anl.verdi.parser.ParserTokenManager.input_stream, and anl.verdi.parser.ParserTokenManager.jjFillToken().
Token anl.verdi.parser.ParserTokenManager.jjFillToken () protected
Definition at line 813 of file ParserTokenManager.java.
References anl.verdi.parser.SimpleCharStream.GetImage(), anl.verdi.parser.ParserTokenManager.input_stream, and anl.verdi.parser.ParserTokenManager.jjstrLiteralImages.
Referenced by anl.verdi.parser.ParserTokenManager.getNextToken().
void anl.verdi.parser.ParserTokenManager.ReInit (SimpleCharStream stream)
Definition at line 786 of file ParserTokenManager.java.
References anl.verdi.parser.ParserTokenManager.input_stream.
Referenced by anl.verdi.parser.ParserTokenManager.ReInit().
void anl.verdi.parser.ParserTokenManager.ReInit (SimpleCharStream stream, int lexState)
Definition at line 800 of file ParserTokenManager.java.
References anl.verdi.parser.ParserTokenManager.ReInit(), and anl.verdi.parser.ParserTokenManager.SwitchTo().
void anl.verdi.parser.ParserTokenManager.SwitchTo (int lexState)
Definition at line 805 of file ParserTokenManager.java.
Referenced by anl.verdi.parser.ParserTokenManager.ParserTokenManager(), and anl.verdi.parser.ParserTokenManager.ReInit().
Member Data Documentation
char anl.verdi.parser.ParserTokenManager.curChar protected
Definition at line 776 of file ParserTokenManager.java.
Referenced by anl.verdi.parser.ParserTokenManager.getNextToken().
SimpleCharStream anl.verdi.parser.ParserTokenManager.input_stream protected
Definition at line 773 of file ParserTokenManager.java.
Referenced by anl.verdi.parser.ParserTokenManager.getNextToken(), anl.verdi.parser.ParserTokenManager.jjFillToken(), anl.verdi.parser.ParserTokenManager.ParserTokenManager(), and anl.verdi.parser.ParserTokenManager.ReInit().
final String [] anl.verdi.parser.ParserTokenManager.jjstrLiteralImages static
Initial value:
= {
"", null, null, null, null, null, null, null, null, null, null, "\76", "\74",
"\75\75", "\74\75", "\76\75", "\41\75", "\174\174", "\46\46", "\53", "\55", "\52",
"\57", "\45", "\52\52", "\141\142\163", "\163\161\162\164", "\163\161\162",
"\154\157\147", "\145\170\160", "\154\156", "\163\151\156", "\143\157\163", "\164\141\156",
"\163\151\156\144", "\143\157\163\144", "\164\141\156\144", "\155\145\141\156", "\163\165\155",
"\155\151\156\164", "\155\141\170\164", "\155\151\156\170", "\155\141\170\170",
"\155\151\156\171", "\155\141\170\171", "\155\151\156\172", "\155\141\170\172", "\155\151\156",
"\155\141\170", "\105", "\120\111", "\116\122\117\127\123", "\116\103\117\114\123",
"\116\114\105\126\105\114\123", "\73", "\50", "\51", null, null, null, }
Definition at line 754 of file ParserTokenManager.java.
Referenced by anl.verdi.parser.ParserTokenManager.jjFillToken().
final String [] anl.verdi.parser.ParserTokenManager.lexStateNames static
Initial value:
= {
   "DEFAULT",
}
Definition at line 764 of file ParserTokenManager.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/parser/ParserTokenManager.java