VERDI: anl.verdi.area.target.Target Class Reference
anl.verdi.area.target.Target Class Reference
Classes
class SourceData
Public Member Functions
void setAreaInfo (int gridNum, int[] rowIndex, int[] colIndex, float[] overlapArea)
boolean areaCalculatedForGrid (int num)
String toString ()
Geometry getDataObject ()
void setSelected (boolean state)
boolean isSelectedPolygon ()
boolean containsDeposition ()
float calculateAverageDeposition (float[][] data)
float calcAverageDeposition (float[][] data)
float getAverageDeposition ()
float calcTotalDeposition (float[][] data)
float calculateTotalDeposition (float[][] data)
float getDeposition ()
double getArea ()
double getConvertedArea ()
double getConvertedArea (double conversionFactor)
String getKeyName ()
AreaFile getSource ()
AreaFile getAreaFile ()
String getDescription ()
String getName ()
void computeAverageDeposition (float[][] data, int gridIndex, TargetDeposition deposition)
Static Public Member Functions
static void syncSelectedTargetSets ()
static void loadData (File file, String nameField, CoordinateReferenceSystem proj, boolean redrawIt)
static void removeSource (AreaFile source)
static CoordinateReferenceSystem loadProjectionInfo (String fileName)
static String indexFileName (String sourceName)
static ArrayList< AreaFile > getSources ()
static ArrayList getSourceNames ()
static ArrayList getTargets ()
static Target getTarget (Geometry obj)
static ArrayList getTargetsForSource (AreaFile sourceFile)
static Target findTarget (String name)
static Target findTargetByFullName (String name)
static void setTargets (ArrayList list)
static ArrayList getSelectedTargets ()
static void setSelectedTargets (ArrayList list)
static void setCurrentSelectedTargets (List list)
static void updateSelectedTargetsLayer ()
static void hideSelectedTargetsLayer ()
static String getDefaultUnits ()
static void setUnitConverters (String gridUnit)
static ArrayList getSelectedSets ()
static ArrayList getSelectedTargetsAndSets ()
static void setSelectedTargetsAndSets (ArrayList list)
static int load (Vector data, int offset) throws IOException
static void unloadAll ()
static void clearGridIntersections ()
static void computeDepositionRange (AreaTilePlot plot, double[] minmax, boolean selectedOnly)
static void computeAverageDepositionRange (AreaTilePlot plot, double[] minmax, boolean selectedOnly)
static boolean setCurrentTilePlot (AreaTilePlot currentTilePlot)
static void setCurrentGridInfo (double[][]gridBounds, double[][] domain)
static void setCurrentGridInfo (GridInfo grid)
static int getCurrentGridNum ()
static void setCurrentGridNum (int currentGridNum)
Static Public Attributes
static boolean useFixedWidth =false
static final String NAME ="Watershed Segment"
static int currentGridNum =-1
static UnitConverter converterGrid =null
static UnitConverter converterTargetStandard =null
static UnitConverter converterTargetGrid =null
static String targetLayer = "Watershed Segments"
static String selectedTargetLayer = "Selected Watershed Segments"
static String loadLayer = "Load Objects"
Detailed Description
File Name:Target.java Description: This object stores a polygon used to show hydrological regions (watersheds). These targets can be selected or organized into sets.
Version
March, 2004
Author
Mary Ann Bitz
Argonne National Lab
Definition at line 62 of file Target.java.
Member Function Documentation
boolean anl.verdi.area.target.Target.areaCalculatedForGrid (int num)
Definition at line 193 of file Target.java.
Referenced by anl.verdi.area.target.TargetCalculator.calculateIntersections().
float anl.verdi.area.target.Target.calcAverageDeposition (float data[][])
Definition at line 626 of file Target.java.
References anl.verdi.area.target.Target.calcTotalDeposition(), and anl.verdi.area.target.Target.converterTargetGrid.
float anl.verdi.area.target.Target.calcTotalDeposition (float data[][])
Definition at line 643 of file Target.java.
References anl.verdi.data.DataUtilities.AMISS3, anl.verdi.area.target.Target.converterTargetStandard, and anl.verdi.area.target.Target.getCurrentGridNum().
Referenced by anl.verdi.area.target.Target.calcAverageDeposition(), and anl.verdi.area.target.Target.calculateTotalDeposition().
float anl.verdi.area.target.Target.calculateAverageDeposition (float data[][])
Calculate the deposition in a target using the grid intersection areas and the value for selected variables at each grid location.
Definition at line 618 of file Target.java.
References anl.verdi.area.target.Target.calculateTotalDeposition(), and anl.verdi.area.target.Target.converterTargetGrid.
float anl.verdi.area.target.Target.calculateTotalDeposition (float data[][])
Definition at line 682 of file Target.java.
References anl.verdi.area.target.Target.calcTotalDeposition().
Referenced by anl.verdi.area.target.Target.calculateAverageDeposition().
static void anl.verdi.area.target.Target.clearGridIntersections () static
Clear out the grid intersection data for all of the targets
Definition at line 910 of file Target.java.
void anl.verdi.area.target.Target.computeAverageDeposition (float data[][], int gridIndex, TargetDeposition deposition)
Definition at line 1057 of file Target.java.
References anl.verdi.area.target.Target.converterTargetGrid.
static void anl.verdi.area.target.Target.computeAverageDepositionRange (AreaTilePlot plot, double[] minmax, boolean selectedOnly) static
Definition at line 955 of file Target.java.
References anl.verdi.area.AreaTilePlot.getGridInfo(), anl.verdi.area.target.Target.setCurrentGridInfo(), and anl.verdi.area.target.Target.setCurrentTilePlot().
static void anl.verdi.area.target.Target.computeDepositionRange (AreaTilePlot plot, double[] minmax, boolean selectedOnly) static
Definition at line 941 of file Target.java.
References anl.verdi.area.AreaTilePlot.getGridInfo(), anl.verdi.area.target.Target.setCurrentGridInfo(), and anl.verdi.area.target.Target.setCurrentTilePlot().
boolean anl.verdi.area.target.Target.containsDeposition ()
Definition at line 561 of file Target.java.
References anl.verdi.area.target.Target.getCurrentGridNum().
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.processMouseMotionEvent().
static Target anl.verdi.area.target.Target.findTarget (String name) static
Find a target with the given name
Parameters
name the name of the target to look for
Returns
the target that matches
Definition at line 430 of file Target.java.
static Target anl.verdi.area.target.Target.findTargetByFullName (String name) static
Definition at line 433 of file Target.java.
double anl.verdi.area.target.Target.getArea ()
Get the area of the entire polygon
Returns
the area
Definition at line 737 of file Target.java.
AreaFile anl.verdi.area.target.Target.getAreaFile ()
Definition at line 927 of file Target.java.
float anl.verdi.area.target.Target.getAverageDeposition ()
Definition at line 634 of file Target.java.
References anl.verdi.area.target.Target.converterTargetGrid, and anl.verdi.area.target.Target.getDeposition().
double anl.verdi.area.target.Target.getConvertedArea ()
Get the area converted into default units
Returns
Definition at line 744 of file Target.java.
double anl.verdi.area.target.Target.getConvertedArea (double conversionFactor)
Definition at line 747 of file Target.java.
static int anl.verdi.area.target.Target.getCurrentGridNum () static
Definition at line 999 of file Target.java.
References anl.verdi.area.target.Target.currentGridNum.
Referenced by anl.verdi.area.target.Target.calcTotalDeposition(), and anl.verdi.area.target.Target.containsDeposition().
Geometry anl.verdi.area.target.Target.getDataObject ()
Get the object corresponding to a target
Returns
the object
Definition at line 463 of file Target.java.
static String anl.verdi.area.target.Target.getDefaultUnits () static
Calculate the polygon area intersections and update the screen when done
Returns
whether it had to spawn a process to do it Get the default area units for target polygons.
the default units
Definition at line 558 of file Target.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.createTable(), and anl.verdi.area.target.Target.setUnitConverters().
float anl.verdi.area.target.Target.getDeposition ()
Get the current deposition value
Returns
the deposition
Definition at line 728 of file Target.java.
Referenced by anl.verdi.area.target.Target.getAverageDeposition().
String anl.verdi.area.target.Target.getDescription ()
Definition at line 932 of file Target.java.
References anl.verdi.area.target.Target.toString().
String anl.verdi.area.target.Target.getKeyName ()
Get the name (HUC code) of the target
Returns
the name
Definition at line 755 of file Target.java.
Referenced by anl.verdi.area.target.Target.getName().
String anl.verdi.area.target.Target.getName ()
Definition at line 937 of file Target.java.
References anl.verdi.area.target.Target.getKeyName().
static ArrayList anl.verdi.area.target.Target.getSelectedSets () static
Get the list of only selected target sets
Returns
the list of selected target sets
Definition at line 699 of file Target.java.
static ArrayList anl.verdi.area.target.Target.getSelectedTargets () static
Get a list of all selected targets
Returns
the list of selected targets
Definition at line 471 of file Target.java.
static ArrayList anl.verdi.area.target.Target.getSelectedTargetsAndSets () static
Get the list of selected targets and target sets
Returns
the current list
Definition at line 712 of file Target.java.
AreaFile anl.verdi.area.target.Target.getSource ()
Get the name of the source file the target came from
Returns
the source file
Definition at line 763 of file Target.java.
static ArrayList anl.verdi.area.target.Target.getSourceNames () static
Get the list of source shape file names for the targets.
Returns
the list of names
Definition at line 373 of file Target.java.
static ArrayList<AreaFile> anl.verdi.area.target.Target.getSources () static
Get the list of source shape files for the targets.
Returns
the list of source files
Definition at line 364 of file Target.java.
static Target anl.verdi.area.target.Target.getTarget (Geometry obj) static
Find a target that corresponds to a given polygon
Parameters
obj the Geometry object
Returns
the target that matches
Definition at line 397 of file Target.java.
static ArrayList anl.verdi.area.target.Target.getTargets () static
Get the entire list of targets
Returns
the whole list of them
Definition at line 388 of file Target.java.
Referenced by anl.verdi.plot.gui.FastAreaTilePlot.createTable().
static ArrayList anl.verdi.area.target.Target.getTargetsForSource (AreaFile sourceFile) static
Get the targets for a particular source file
Parameters
source the name of the source file
Returns
the matching targets or null if none exist
Definition at line 411 of file Target.java.
static void anl.verdi.area.target.Target.hideSelectedTargetsLayer () static
Hides the layer showing selected targets. Called if the target selection window opens.
Definition at line 520 of file Target.java.
static String anl.verdi.area.target.Target.indexFileName (String sourceName) static
Generates the name of the index file from the source filename
Parameters
sourceName the original hydrological file
Returns
the corresponding index file name
Definition at line 351 of file Target.java.
boolean anl.verdi.area.target.Target.isSelectedPolygon ()
Whether a target has been selected by the user.
Returns
if it's selected
Definition at line 535 of file Target.java.
static int anl.verdi.area.target.Target.load (Vector data, int offset) throws IOException static
Load the data from the vector of options
Parameters
data the vector containing the file data
offset the current offset
Returns
if it was successful
Exceptions
IOException
Definition at line 774 of file Target.java.
References anl.verdi.area.target.TargetSet.includedTargets(), anl.verdi.area.target.Target.NAME, anl.verdi.area.target.Target.setSelectedTargets(), and anl.verdi.area.target.Target.unloadAll().
static void anl.verdi.area.target.Target.loadData (File file, String nameField, CoordinateReferenceSystem proj, boolean redrawIt) static
Load a bunch of polygons in from a file
Parameters
fileName the filename
nameField the name of the field used for the id
projString the projection the data is in
redrawIt whether or not a redraw should be done
Definition at line 226 of file Target.java.
static CoordinateReferenceSystem anl.verdi.area.target.Target.loadProjectionInfo (String fileName) static
Definition at line 310 of file Target.java.
static void anl.verdi.area.target.Target.removeSource (AreaFile source) static
Definition at line 307 of file Target.java.
void anl.verdi.area.target.Target.setAreaInfo (int gridNum, int[] rowIndex, int[] colIndex, float[] overlapArea)
Definition at line 86 of file Target.java.
static void anl.verdi.area.target.Target.setCurrentGridInfo (doublegridBounds [][], double domain[][]) static
Definition at line 987 of file Target.java.
Referenced by anl.verdi.area.target.Target.computeAverageDepositionRange(), and anl.verdi.area.target.Target.computeDepositionRange().
static void anl.verdi.area.target.Target.setCurrentGridInfo (GridInfo grid) static
Definition at line 992 of file Target.java.
References anl.verdi.area.target.Target.setCurrentGridNum().
static void anl.verdi.area.target.Target.setCurrentGridNum (int currentGridNum) static
Definition at line 1002 of file Target.java.
References anl.verdi.area.target.Target.currentGridNum.
Referenced by anl.verdi.area.target.Target.setCurrentGridInfo().
static void anl.verdi.area.target.Target.setCurrentSelectedTargets (List list) static
Definition at line 490 of file Target.java.
References anl.verdi.area.target.Target.setSelectedTargets().
static boolean anl.verdi.area.target.Target.setCurrentTilePlot (AreaTilePlot currentTilePlot) static
Definition at line 975 of file Target.java.
Referenced by anl.verdi.area.target.Target.computeAverageDepositionRange(), and anl.verdi.area.target.Target.computeDepositionRange().
void anl.verdi.area.target.Target.setSelected (boolean state)
Definition at line 526 of file Target.java.
static void anl.verdi.area.target.Target.setSelectedTargets (ArrayList list) static
Set the list of selected targets
Parameters
list the list of targets to select
Definition at line 479 of file Target.java.
Referenced by anl.verdi.area.target.Target.load(), anl.verdi.area.target.Target.setCurrentSelectedTargets(), and anl.verdi.area.target.Target.syncSelectedTargetSets().
static void anl.verdi.area.target.Target.setSelectedTargetsAndSets (ArrayList list) static
Set the list of selected targets and target sets
Parameters
list the new list
Definition at line 720 of file Target.java.
Referenced by anl.verdi.area.target.Target.syncSelectedTargetSets().
static void anl.verdi.area.target.Target.setTargets (ArrayList list) static
Set the entire list of targets to the passed in one
Parameters
list the new list
Definition at line 443 of file Target.java.
static void anl.verdi.area.target.Target.setUnitConverters (String gridUnit) static
Definition at line 573 of file Target.java.
References anl.verdi.area.target.Target.converterGrid, anl.verdi.area.target.Target.converterTargetGrid, anl.verdi.area.target.Target.converterTargetStandard, anl.verdi.area.Units.getAreaUnit(), anl.verdi.area.target.Target.getDefaultUnits(), anl.verdi.area.Units.getTopUnit(), anl.verdi.area.Units.isConcentration(), anl.verdi.area.Units.isLength(), and anl.verdi.area.Units.isUnitPerArea().
static void anl.verdi.area.target.Target.syncSelectedTargetSets () static
Update the list of selected targets in case one is deleted
Definition at line 203 of file Target.java.
References anl.verdi.area.target.TargetSet.includedTargets(), anl.verdi.area.target.Target.setSelectedTargets(), and anl.verdi.area.target.Target.setSelectedTargetsAndSets().
String anl.verdi.area.target.Target.toString ()
Get the string representing the target
Returns
the string to show for it
Definition at line 451 of file Target.java.
Referenced by anl.verdi.area.target.Target.getDescription(), and anl.verdi.plot.gui.FastAreaTilePlot.processMouseMotionEvent().
static void anl.verdi.area.target.Target.unloadAll () static
Unload the indicated file of target polygons
Parameters
sourceFile the file to unload
Definition at line 891 of file Target.java.
Referenced by anl.verdi.area.target.Target.load().
static void anl.verdi.area.target.Target.updateSelectedTargetsLayer () static
Update the layer showing selected targets. Called if the target selection window closes
Definition at line 504 of file Target.java.
Member Data Documentation
UnitConverter anl.verdi.area.target.Target.converterGrid =null static
Definition at line 82 of file Target.java.
Referenced by anl.verdi.area.target.Target.setUnitConverters().
UnitConverter anl.verdi.area.target.Target.converterTargetGrid =null static
Definition at line 84 of file Target.java.
Referenced by anl.verdi.area.target.Target.calcAverageDeposition(), anl.verdi.area.target.Target.calculateAverageDeposition(), anl.verdi.area.target.Target.computeAverageDeposition(), anl.verdi.area.target.Target.getAverageDeposition(), and anl.verdi.area.target.Target.setUnitConverters().
UnitConverter anl.verdi.area.target.Target.converterTargetStandard =null static
Definition at line 83 of file Target.java.
Referenced by anl.verdi.area.target.Target.calcTotalDeposition(), and anl.verdi.area.target.Target.setUnitConverters().
int anl.verdi.area.target.Target.currentGridNum =-1 static
Definition at line 81 of file Target.java.
Referenced by anl.verdi.area.target.Target.getCurrentGridNum(), and anl.verdi.area.target.Target.setCurrentGridNum().
String anl.verdi.area.target.Target.loadLayer = "Load Objects" static
name of the temporary GeoLayer used to load objects
Definition at line 173 of file Target.java.
final String anl.verdi.area.target.Target.NAME ="Watershed Segment" static
Definition at line 79 of file Target.java.
Referenced by anl.verdi.area.target.Target.load(), and anl.verdi.area.target.TargetFileCard.TargetFileCard().
String anl.verdi.area.target.Target.selectedTargetLayer = "Selected Watershed Segments" static
name of the GeoLayer holding selected targets
Definition at line 171 of file Target.java.
String anl.verdi.area.target.Target.targetLayer = "Watershed Segments" static
name of the target GeoLayer
Definition at line 169 of file Target.java.
boolean anl.verdi.area.target.Target.useFixedWidth =false static
Definition at line 78 of file Target.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/target/Target.java