VERDI: anl.verdi.plot.gui.AreaSelectionEvent Class Reference
anl.verdi.plot.gui.AreaSelectionEvent Class Reference
Public Member Functions
AreaSelectionEvent (Rectangle area, boolean finished)
AreaSelectionEvent (Rectangle area, String areaString, boolean finished)
Rectangle getArea ()
boolean isFinished ()
String areaToString ()
Detailed Description
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 9 of file AreaSelectionEvent.java.
Constructor & Destructor Documentation
anl.verdi.plot.gui.AreaSelectionEvent.AreaSelectionEvent (Rectangle area, boolean finished)
Definition at line 15 of file AreaSelectionEvent.java.
References anl.verdi.plot.gui.AreaSelectionEvent.isFinished().
anl.verdi.plot.gui.AreaSelectionEvent.AreaSelectionEvent (Rectangle area, String areaString, boolean finished)
Definition at line 33 of file AreaSelectionEvent.java.
References anl.verdi.plot.gui.AreaSelectionEvent.isFinished().
Member Function Documentation
String anl.verdi.plot.gui.AreaSelectionEvent.areaToString ()
Definition at line 47 of file AreaSelectionEvent.java.
Rectangle anl.verdi.plot.gui.AreaSelectionEvent.getArea ()
Definition at line 39 of file AreaSelectionEvent.java.
boolean anl.verdi.plot.gui.AreaSelectionEvent.isFinished ()
Definition at line 43 of file AreaSelectionEvent.java.
Referenced by anl.verdi.plot.gui.AreaSelectionEvent.AreaSelectionEvent().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/gui/AreaSelectionEvent.java