VERDI: anl.verdi.plot.types.Contour3D Class Reference
anl.verdi.plot.types.Contour3D Class Reference
Public Member Functions
Contour3D (DataFrame frame) throws RemoteException, VisADException
Contour3D (DataFrame frame, PlotConfiguration config) throws RemoteException, VisADException
BufferedImage getBufferedImage ()
synchronized BufferedImage getBufferedImage (int width, int height)
void createPrintJob ()
int print (Graphics g, PageFormat pf, int pageIndex)
void updateTimeStep (int timestep)
void updateTimeStepLayer (int timestep, int layer)
List< DataFrame > getData ()
void addPlotListener (PlotListener listener)
JToolBar getToolBar ()
JMenuBar getMenuBar ()
JPanel getPanel ()
void removePlotListener (PlotListener listener)
Formula.Type getType ()
void exportImage (String format, File file, int width, int height) throws IOException
void configure (PlotConfiguration config, Plot.ConfigSource source)
void configure (PlotConfiguration config)
PlotConfiguration getPlotConfiguration ()
String getTitle ()
void viewClosed ()
JMapPane getMapPane ()
Public Member Functions inherited from anl.verdi.plot.gui.Plot
void configure (PlotConfiguration config, ConfigSource source)
Protected Member Functions
PlotConfiguration getTitlesLabelsConfig (PlotConfiguration config)
Detailed Description
Definition at line 97 of file Contour3D.java.
Constructor & Destructor Documentation
anl.verdi.plot.types.Contour3D.Contour3D (DataFrame frame) throws RemoteException, VisADException
Creates a contour style 3D image graph
Parameters
frame
Exceptions
RemoteException
VisADException
Definition at line 135 of file Contour3D.java.
anl.verdi.plot.types.Contour3D.Contour3D (DataFrame frame, PlotConfiguration config) throws RemoteException, VisADException
Creates a contour style 3D image graph
Parameters
frame
Exceptions
RemoteException
VisADException
Definition at line 147 of file Contour3D.java.
References anl.verdi.plot.types.Contour3D.configure(), anl.verdi.data.DataFrame.getAxes(), anl.verdi.plot.types.Contour3D.getPlotConfiguration(), anl.verdi.plot.config.PlotConfiguration.getSubtitle1(), and anl.verdi.plot.types.Contour3D.getTitle().
Member Function Documentation
void anl.verdi.plot.types.Contour3D.addPlotListener (PlotListener listener)
Adds the specified PlotListener.
Parameters
listener the plot listener to add
Implements anl.verdi.plot.gui.Plot.
Definition at line 545 of file Contour3D.java.
void anl.verdi.plot.types.Contour3D.configure (PlotConfiguration config, Plot.ConfigSource source)
Configure this Plot according to the specified PlotConfiguration.
Parameters
config the new plot configuration
Definition at line 788 of file Contour3D.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), anl.verdi.plot.types.Contour3D.Contour3D(), and anl.verdi.plot.types.Contour3D.getMenuBar().
void anl.verdi.plot.types.Contour3D.configure (PlotConfiguration config)
Configure this Plot according to the specified PlotConfiguration.
Parameters
config the new plot configuration
Implements anl.verdi.plot.gui.Plot.
Definition at line 791 of file Contour3D.java.
References anl.verdi.plot.config.TilePlotConfiguration.COLOR_MAP, anl.verdi.plot.types.Contour3D.configure(), anl.verdi.plot.config.PlotConfiguration.DOMAIN_COLOR, anl.verdi.plot.config.PlotConfiguration.DOMAIN_FONT, anl.verdi.plot.config.PlotConfiguration.DOMAIN_LABEL, anl.verdi.plot.config.PlotConfiguration.DOMAIN_SHOW_TICK, anl.verdi.plot.config.PlotConfiguration.getColor(), anl.verdi.plot.config.PlotConfiguration.getObject(), anl.verdi.plot.util.VerdiCanvas3D.getSub1(), anl.verdi.plot.util.VerdiCanvas3D.getSub2(), anl.verdi.plot.util.VerdiCanvas3D.getTitle(), anl.verdi.plot.config.PlotConfiguration.LEGEND_SHOW, anl.verdi.plot.config.PlotConfiguration.RANGE_COLOR, anl.verdi.plot.config.PlotConfiguration.RANGE_FONT, anl.verdi.plot.config.PlotConfiguration.RANGE_LABEL, anl.verdi.plot.config.PlotConfiguration.RANGE_SHOW_TICK, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_FONT, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_FONT, anl.verdi.plot.config.PlotConfiguration.TITLE_COLOR, anl.verdi.plot.config.PlotConfiguration.TITLE_FONT, anl.verdi.plot.config.PlotConfiguration.UNITS, anl.verdi.plot.config.PlotConfiguration.UNITS_COLOR, anl.verdi.plot.config.PlotConfiguration.UNITS_FONT, anl.verdi.plot.config.PlotConfiguration.UNITS_SHOW_TICK, anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_COLOR, anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_FONT, anl.verdi.plot.config.PlotConfiguration.Z_COLOR, anl.verdi.plot.config.PlotConfiguration.Z_FONT, anl.verdi.plot.config.PlotConfiguration.Z_LABEL, and anl.verdi.plot.config.PlotConfiguration.Z_SHOW_TICK.
void anl.verdi.plot.types.Contour3D.createPrintJob ()
Creates a print job for the chart.
Definition at line 415 of file Contour3D.java.
Referenced by anl.verdi.plot.types.Contour3D.getMenuBar().
void anl.verdi.plot.types.Contour3D.exportImage (String format, File file, int width, int height) throws IOException
Exports an image of this Plot to the specified file in the specified format.
Parameters
format the image format. One of PlotExporter.JPG, PlotExporter.TIF, PlotExporter.PNG, or PlotExporter.BMP
file the file to save the image to.
width width of image in pixels
height height of image in pixels
Implements anl.verdi.plot.gui.Plot.
Definition at line 778 of file Contour3D.java.
BufferedImage anl.verdi.plot.types.Contour3D.getBufferedImage ()
Gets a BufferedImage of the plot.
Returns
a BufferedImage of the plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 361 of file Contour3D.java.
Referenced by anl.verdi.plot.types.Contour3D.print().
synchronized BufferedImage anl.verdi.plot.types.Contour3D.getBufferedImage (int width, int height)
This will not respect the width and height arguments due to visad limitations.
Parameters
width ignored
height ignored
Returns
the created image
Implements anl.verdi.plot.gui.Plot.
Definition at line 373 of file Contour3D.java.
List<DataFrame> anl.verdi.plot.types.Contour3D.getData ()
Gets the data that this Plot plots.
Returns
the data that this Plot plots.
Implements anl.verdi.plot.gui.Plot.
Definition at line 534 of file Contour3D.java.
JMapPane anl.verdi.plot.types.Contour3D.getMapPane ()
Gets the JMapPane that contains the mapping portion of the plot component.
Returns
the mapping panel that contains the mapping portion of the plot component.
Implements anl.verdi.plot.gui.Plot.
Definition at line 993 of file Contour3D.java.
JMenuBar anl.verdi.plot.types.Contour3D.getMenuBar ()
Gets a menu bar for this Plot.
Returns
a menu bar for this Plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 590 of file Contour3D.java.
References anl.verdi.plot.types.Contour3D.configure(), anl.verdi.plot.types.Contour3D.createPrintJob(), and anl.verdi.plot.types.Contour3D.getPlotConfiguration().
JPanel anl.verdi.plot.types.Contour3D.getPanel ()
Gets the entire panel that contains the plot component.
Returns
the entire panel that contains the plot component.
Implements anl.verdi.plot.gui.Plot.
Definition at line 739 of file Contour3D.java.
PlotConfiguration anl.verdi.plot.types.Contour3D.getPlotConfiguration ()
Gets this Plot's configuration data.
Returns
this Plot's configuration data.
Implements anl.verdi.plot.gui.Plot.
Definition at line 894 of file Contour3D.java.
References anl.verdi.formula.Formula.Type.CONTOUR, anl.verdi.plot.config.PlotConfiguration.FOOTER1_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.FOOTER2_SHOW_LINE, anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), anl.verdi.plot.config.PlotConfiguration.LEGEND_SHOW, anl.verdi.plot.config.PlotConfiguration.OBS_SHOW_LEGEND, anl.verdi.plot.config.PlotConfiguration.PLOT_TYPE, anl.verdi.plot.config.PlotConfiguration.UNITS, anl.verdi.plot.config.PlotConfiguration.UNITS_COLOR, anl.verdi.plot.config.PlotConfiguration.UNITS_FONT, anl.verdi.plot.config.PlotConfiguration.UNITS_SHOW_TICK, anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_COLOR, anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_FONT, anl.verdi.plot.config.PlotConfiguration.Z_COLOR, anl.verdi.plot.config.PlotConfiguration.Z_FONT, anl.verdi.plot.config.PlotConfiguration.Z_LABEL, and anl.verdi.plot.config.PlotConfiguration.Z_SHOW_TICK.
Referenced by anl.verdi.plot.types.Contour3D.Contour3D(), and anl.verdi.plot.types.Contour3D.getMenuBar().
String anl.verdi.plot.types.Contour3D.getTitle ()
Gets this plot's current title.
Implements anl.verdi.plot.gui.Plot.
Definition at line 964 of file Contour3D.java.
Referenced by anl.verdi.plot.types.Contour3D.Contour3D().
PlotConfiguration anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig (PlotConfiguration config) protected
Definition at line 927 of file Contour3D.java.
References anl.verdi.plot.config.PlotConfiguration.DOMAIN_COLOR, anl.verdi.plot.config.PlotConfiguration.DOMAIN_FONT, anl.verdi.plot.config.PlotConfiguration.DOMAIN_LABEL, anl.verdi.plot.config.PlotConfiguration.DOMAIN_SHOW_TICK, anl.verdi.plot.config.Title.getColor(), anl.verdi.plot.config.PlotConfiguration.RANGE_COLOR, anl.verdi.plot.config.PlotConfiguration.RANGE_FONT, anl.verdi.plot.config.PlotConfiguration.RANGE_LABEL, anl.verdi.plot.config.PlotConfiguration.RANGE_SHOW_TICK, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_FONT, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_FONT, anl.verdi.plot.config.PlotConfiguration.TITLE_COLOR, and anl.verdi.plot.config.PlotConfiguration.TITLE_FONT.
Referenced by anl.verdi.plot.types.Contour3D.getPlotConfiguration().
JToolBar anl.verdi.plot.types.Contour3D.getToolBar ()
Gets a tool bar for this plot. This may return null if there is no tool bar.
Returns
a tool bar for this plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 555 of file Contour3D.java.
References anl.verdi.data.DataFrame.getAxes(), anl.verdi.data.AxisRange.getExtent(), anl.verdi.data.AxisRange.getOrigin(), and anl.verdi.plot.types.Contour3D.updateTimeStepLayer().
Formula.Type anl.verdi.plot.types.Contour3D.getType ()
Gets the type of the Plot.
Returns
the type of the Plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 763 of file Contour3D.java.
int anl.verdi.plot.types.Contour3D.print (Graphics g, PageFormat pf, int pageIndex)
Prints the chart on a single page.
Parameters
g the graphics context.
pf the page format to use.
pageIndex the index of the page. If not 0, nothing gets print.
Returns
The result of printing.
Definition at line 442 of file Contour3D.java.
References anl.verdi.plot.types.Contour3D.getBufferedImage().
void anl.verdi.plot.types.Contour3D.removePlotListener (PlotListener listener)
Removes the specified PlotListener.
Parameters
listener the plot listener to remove
Implements anl.verdi.plot.gui.Plot.
Definition at line 754 of file Contour3D.java.
void anl.verdi.plot.types.Contour3D.updateTimeStep (int timestep)
Update this plot to the specified timestep.
Parameters
timestep the new timestep.
Implements anl.verdi.plot.types.TimeAnimatablePlot.
Definition at line 471 of file Contour3D.java.
References anl.verdi.plot.types.Contour3D.updateTimeStepLayer().
void anl.verdi.plot.types.Contour3D.updateTimeStepLayer (int timestep, int layer)
Definition at line 479 of file Contour3D.java.
References anl.verdi.data.DataFrame.getAxes(), and anl.verdi.plot.config.PlotConfiguration.getTitle().
Referenced by anl.verdi.plot.types.Contour3D.getToolBar(), and anl.verdi.plot.types.Contour3D.updateTimeStep().
void anl.verdi.plot.types.Contour3D.viewClosed ()
Implements anl.verdi.plot.gui.Plot.
Definition at line 968 of file Contour3D.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/types/Contour3D.java