VERDI: anl.verdi.parser.TokenMgrError Class Reference
anl.verdi.parser.TokenMgrError Class Reference
Public Member Functions
String getMessage ()
TokenMgrError ()
TokenMgrError (String message, int reason)
TokenMgrError (boolean EOFSeen, int lexState, int errorLine, int errorColumn, String errorAfter, char curChar, int reason)
Static Protected Member Functions
static final String addEscapes (String str)
static String LexicalError (boolean EOFSeen, int lexState, int errorLine, int errorColumn, String errorAfter, char curChar)
Detailed Description
Definition at line 4 of file TokenMgrError.java.
Constructor & Destructor Documentation
anl.verdi.parser.TokenMgrError.TokenMgrError ()
Definition at line 127 of file TokenMgrError.java.
anl.verdi.parser.TokenMgrError.TokenMgrError (String message, int reason)
Definition at line 130 of file TokenMgrError.java.
anl.verdi.parser.TokenMgrError.TokenMgrError (boolean EOFSeen, int lexState, int errorLine, int errorColumn, String errorAfter, char curChar, int reason)
Definition at line 135 of file TokenMgrError.java.
References anl.verdi.parser.TokenMgrError.LexicalError().
Member Function Documentation
static final String anl.verdi.parser.TokenMgrError.addEscapes (String str) static protected
Replaces unprintable characters by their espaced (or unicode escaped) equivalents in the given string
Definition at line 45 of file TokenMgrError.java.
Referenced by anl.verdi.parser.TokenMgrError.LexicalError().
String anl.verdi.parser.TokenMgrError.getMessage ()
You can also modify the body of this method to customize your error messages. For example, cases like LOOP_DETECTED and INVALID_LEXICAL_STATE are not of end-users concern, so you can return something like :
"Internal Error : Please file a bug report .... "
from this method for such cases in the release version of your parser.
Definition at line 119 of file TokenMgrError.java.
static String anl.verdi.parser.TokenMgrError.LexicalError (boolean EOFSeen, int lexState, int errorLine, int errorColumn, String errorAfter, char curChar) static protected
Returns a detailed message for the Error when it is thrown by the token manager to indicate a lexical error. Parameters : EOFSeen : indicates if EOF caused the lexicl error curLexState : lexical state in which this error occured errorLine : line number when the error occured errorColumn : column number when the error occured errorAfter : prefix that was seen before this error occured curchar : the offending character Note: You can customize the lexical error message by modifying this method.
Definition at line 102 of file TokenMgrError.java.
References anl.verdi.parser.TokenMgrError.addEscapes().
Referenced by anl.verdi.parser.TokenMgrError.TokenMgrError().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/parser/TokenMgrError.java