VERDI: simphony.settings.SettingsRegistry Class Reference
simphony.settings.SettingsRegistry Class Reference
Public Member Functions
SettingsRegistry (String registryId)
synchronized void setRegistryId (String registryId)
synchronized String getRegistryId ()
synchronized Object get (Object key)
synchronized Object put (String key, Object value)
synchronized Object putHere (String key, Object value)
synchronized SettingsRegistry getNext ()
synchronized void setNext (SettingsRegistry next)
Static Public Member Functions
static SettingsRegistry getRegistry (String registryId, String fileName)
static SettingsRegistry getRegistry (String registryId)
static SettingsRegistry register (SettingsRegistry registry)
Static Public Attributes
static final String REGISTRY_ID_KEY = "SettingsRegistryId"
Protected Member Functions
SettingsRegistry findRegistryWithKey (String key)
Detailed Description
This is a simple class for storing settings for an application. This is at heart just a chain of java.util.Maps with an id associated to them. This stores that id in itself through the key REGISTRY_ID_KEY.
Author
Jerry Vos
Definition at line 15 of file SettingsRegistry.java.
Constructor & Destructor Documentation
simphony.settings.SettingsRegistry.SettingsRegistry (String registryId)
Constructs this registry with the specified key.
See Also
putHere(String, Object) used for storing the registry id
Parameters
registryId the registry's id
Definition at line 35 of file SettingsRegistry.java.
References simphony.settings.SettingsRegistry.putHere(), and simphony.settings.SettingsRegistry.REGISTRY_ID_KEY.
Referenced by simphony.settings.SettingsRegistry.getRegistry().
Member Function Documentation
SettingsRegistry simphony.settings.SettingsRegistry.findRegistryWithKey (String key) protected
Definition at line 126 of file SettingsRegistry.java.
Referenced by simphony.settings.SettingsRegistry.put().
synchronized Object simphony.settings.SettingsRegistry.get (Object key)
This will try to find a value for the specified key in this registry, and if it cannot it will attempt to find one in the next registry (which also will attempt to check in itself and then the next, ...).
Parameters
key the key to search for a value for
Returns
the value for the given key in the registry chain starting at this registry and onwards
Definition at line 73 of file SettingsRegistry.java.
synchronized SettingsRegistry simphony.settings.SettingsRegistry.getNext ()
Retrieves the next registry in the chain (the one after this one).
Returns
the next registry
Definition at line 150 of file SettingsRegistry.java.
static SettingsRegistry simphony.settings.SettingsRegistry.getRegistry (String registryId, String fileName) static
Retrives a static registry with the specified key. If another settings registry has been created with the specified id (using this method) that registry will be returned. If no registry has been created with the specified id, this will attempt to read one in using the specified file name. If reading the file name fails then a new SettingsRegistry will be created and returned.
See Also
SettingsIO::loadSettings(String, String)
Parameters
registryId the id of the registry
fileName the name of the settings file+
Returns
a SettingsRegistry
Definition at line 179 of file SettingsRegistry.java.
References simphony.settings.SettingsRegistry.SettingsRegistry().
static SettingsRegistry simphony.settings.SettingsRegistry.getRegistry (String registryId) static
Retrives a static registry with the specified key. If no registry has been created or registered with the specified id, this will return null.
See Also
SettingsRegistry::getRegistry(String)
SettingsRegistry::register(SettingsRegistry)
Parameters
registryId the id of the registry
Returns
a SettingsRegistry
Definition at line 204 of file SettingsRegistry.java.
synchronized String simphony.settings.SettingsRegistry.getRegistryId ()
Retrieves this registry's id. This is the same as get(REGISTRY_ID_KEY).
Returns
the id for this registry
Definition at line 58 of file SettingsRegistry.java.
References simphony.settings.SettingsRegistry.REGISTRY_ID_KEY.
synchronized Object simphony.settings.SettingsRegistry.put (String key, Object value)
This attempts to find a registry with the given key already stored in it. If it cannot find one it will add the key and value to itself. If it can find one with the specified key it will set that value on that registry.
See Also
putHere(String, Object)
getNext()
Parameters
key the key to store the value under
value the value to store
Returns
the last value stored for the given key
Definition at line 100 of file SettingsRegistry.java.
References simphony.settings.SettingsRegistry.findRegistryWithKey(), and simphony.settings.SettingsRegistry.putHere().
synchronized Object simphony.settings.SettingsRegistry.putHere (String key, Object value)
Stores the given value into this registry. This is like put(String, Object), except it will not attempt to find a registry with the specified key.
Parameters
key the key to store
value the value to store it under
Returns
Definition at line 122 of file SettingsRegistry.java.
Referenced by simphony.settings.SettingsRegistry.put(), simphony.settings.SettingsRegistry.setRegistryId(), and simphony.settings.SettingsRegistry.SettingsRegistry().
static SettingsRegistry simphony.settings.SettingsRegistry.register (SettingsRegistry registry) static
Registers a SettingsRegistry using its id from its getRegistryId(). This will be returned from calls to SettingsRegistry#getRegistry(String, String) with the registry's id.
Parameters
registry the registry to register
Returns
the passed in registry
Definition at line 217 of file SettingsRegistry.java.
synchronized void simphony.settings.SettingsRegistry.setNext (SettingsRegistry next)
Sets the next registry in the settings chain.
Parameters
next the next registry
Definition at line 160 of file SettingsRegistry.java.
synchronized void simphony.settings.SettingsRegistry.setRegistryId (String registryId)
Sets this registry's id. This is the same as put(REGISTRY_ID_KEY, registryId).
See Also
putHere(String, Object)
Parameters
registryId the id for this registry
Definition at line 49 of file SettingsRegistry.java.
References simphony.settings.SettingsRegistry.putHere(), and simphony.settings.SettingsRegistry.REGISTRY_ID_KEY.
Member Data Documentation
final String simphony.settings.SettingsRegistry.REGISTRY_ID_KEY = "SettingsRegistryId" static
The key the registry id is stored under
Definition at line 19 of file SettingsRegistry.java.
Referenced by simphony.settings.SettingsRegistry.getRegistryId(), simphony.settings.SettingsRegistry.setRegistryId(), and simphony.settings.SettingsRegistry.SettingsRegistry().
The documentation for this class was generated from the following file:
verdi_saf_core_runtime/src/simphony/settings/SettingsRegistry.java