VERDI: anl.verdi.area.target.ProjectionInfo.LambertCCProjectionGUIAdaptor Class Reference
anl.verdi.area.target.ProjectionInfo.LambertCCProjectionGUIAdaptor Class Reference
Public Member Functions
LambertCCProjectionGUIAdaptor ()
void initialize (ProjectionInfo d)
boolean validate (ProjectionInfo d)
CoordinateReferenceSystem getProjection (ProjectionInfo d)
String createWKT () throws IOException
Detailed Description
Lambert adaptor
Author
Gordon Lurie
Version
Revision:
1.3
Definition at line 57 of file ProjectionInfo.java.
Constructor & Destructor Documentation
anl.verdi.area.target.ProjectionInfo.LambertCCProjectionGUIAdaptor.LambertCCProjectionGUIAdaptor ()
Constructor for GeoLambertCCProjectionGUIAdaptor
Definition at line 62 of file ProjectionInfo.java.
Member Function Documentation
String anl.verdi.area.target.ProjectionInfo.LambertCCProjectionGUIAdaptor.createWKT () throws IOException
Implements anl.verdi.area.target.ProjectionInfo.ProjectionGUIAdaptor.
Definition at line 179 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.doubleValueOf().
Referenced by anl.verdi.area.target.ProjectionInfo.LambertCCProjectionGUIAdaptor.getProjection().
CoordinateReferenceSystem anl.verdi.area.target.ProjectionInfo.LambertCCProjectionGUIAdaptor.getProjection (ProjectionInfo d)
Method getArgs
Parameters
d ProjectionInfo
Returns
Object[] Method getProjection
Parameters
d ProjectionInfo
Returns
GeoProjection
See Also
anl.jeoviewer.gui.ProjectionInfo$ProjectionGUIAdaptor::getProjection(ProjectionInfo)
Implements anl.verdi.area.target.ProjectionInfo.ProjectionGUIAdaptor.
Definition at line 166 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.LambertCCProjectionGUIAdaptor.createWKT().
void anl.verdi.area.target.ProjectionInfo.LambertCCProjectionGUIAdaptor.initialize (ProjectionInfo d)
Method initialize
Parameters
d ProjectionInfo
See Also
anl.jeoviewer.gui.ProjectionInfo$ProjectionGUIAdaptor::initialize(ProjectionInfo)
Implements anl.verdi.area.target.ProjectionInfo.ProjectionGUIAdaptor.
Definition at line 71 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.getAllEllipseData().
boolean anl.verdi.area.target.ProjectionInfo.LambertCCProjectionGUIAdaptor.validate (ProjectionInfo d)
Method validate
Parameters
d ProjectionInfo
Returns
boolean
See Also
anl.jeoviewer.gui.ProjectionInfo$ProjectionGUIAdaptor::validate(ProjectionInfo)
Implements anl.verdi.area.target.ProjectionInfo.ProjectionGUIAdaptor.
Definition at line 102 of file ProjectionInfo.java.
References anl.verdi.area.target.ProjectionInfo.doubleValueOf().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/target/ProjectionInfo.java