VERDI: anl.verdi.plot.color.PalettePanel Class Reference
anl.verdi.plot.color.PalettePanel Class Reference
Public Member Functions
void enableScale (boolean enable)
PalettePanel ()
void setPalettes (List< Palette > palettes)
void initMap (ColorMap colorMap, DataUtilities.MinMax minMax)
ColorMap getColorMap () throws Exception
ColorMap.PaletteType getPaletteType ()
void setPaletteType (PaletteType paletteType)
void setForFastTitle (boolean isForFastTitle)
boolean isForFastTitle ()
Detailed Description
Author
User #2
Definition at line 59 of file PalettePanel.java.
Constructor & Destructor Documentation
anl.verdi.plot.color.PalettePanel.PalettePanel ()
Definition at line 327 of file PalettePanel.java.
References anl.verdi.plot.color.PalettePanel.getColorMap(), and anl.verdi.plot.color.PalettePanel.getPaletteType().
Member Function Documentation
void anl.verdi.plot.color.PalettePanel.enableScale (boolean enable)
Definition at line 99 of file PalettePanel.java.
ColorMap anl.verdi.plot.color.PalettePanel.getColorMap () throws Exception
Definition at line 793 of file PalettePanel.java.
Referenced by anl.verdi.plot.color.PalettePanel.PalettePanel().
ColorMap.PaletteType anl.verdi.plot.color.PalettePanel.getPaletteType ()
Definition at line 1029 of file PalettePanel.java.
References anl.verdi.plot.color.ColorMap.PaletteType.QUALITATIVE, and anl.verdi.plot.color.ColorMap.PaletteType.SEQUENTIAL.
Referenced by anl.verdi.plot.color.PalettePanel.PalettePanel(), and anl.verdi.plot.color.PalettePanel.setPaletteType().
void anl.verdi.plot.color.PalettePanel.initMap (ColorMap colorMap, DataUtilities.MinMax minMax)
Definition at line 703 of file PalettePanel.java.
References anl.verdi.plot.color.ColorMap.getNumberFormat(), and anl.verdi.plot.color.ColorMap.getPalette().
boolean anl.verdi.plot.color.PalettePanel.isForFastTitle ()
Definition at line 1085 of file PalettePanel.java.
Referenced by anl.verdi.plot.color.PalettePanel.setForFastTitle().
void anl.verdi.plot.color.PalettePanel.setForFastTitle (boolean isForFastTitle)
Definition at line 1046 of file PalettePanel.java.
References anl.verdi.plot.color.PalettePanel.isForFastTitle().
void anl.verdi.plot.color.PalettePanel.setPalettes (List< Palette > palettes)
Definition at line 671 of file PalettePanel.java.
References anl.verdi.plot.color.ColorMapTableModel.getColorMap().
void anl.verdi.plot.color.PalettePanel.setPaletteType (PaletteType paletteType)
Definition at line 1040 of file PalettePanel.java.
References anl.verdi.plot.color.PalettePanel.getPaletteType().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/color/PalettePanel.java