VERDI: anl.verdi.core.VerdiAppConfigurator Class Reference
anl.verdi.core.VerdiAppConfigurator Class Reference
Public Member Functions
VerdiAppConfigurator (VerdiApplication verdi)
void createLayout (DockingManager manager)
void fillBars (GUIBarManager guiBarManager)
void postWindowClose ()
void postWindowOpen (ISAFDisplay display)
void closeSplash ()
boolean preWindowClose ()
boolean preWindowOpen (IWindowCustomizer customizer)
Detailed Description
Application configurator for VERDI.
The methods in this interface are called by the SAF application initialization mechanism during points in the application's life cycle. On application start up, the order in which they are called is:
preWindowOpen
createLayout
fillBars
postWindowOpen
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 52 of file VerdiAppConfigurator.java.
Constructor & Destructor Documentation
anl.verdi.core.VerdiAppConfigurator.VerdiAppConfigurator (VerdiApplication verdi)
Creates a VerdiAppConfigurator.
Parameters
verdi the main verdi application object
Definition at line 77 of file VerdiAppConfigurator.java.
Member Function Documentation
void anl.verdi.core.VerdiAppConfigurator.closeSplash ()
Definition at line 187 of file VerdiAppConfigurator.java.
Referenced by anl.verdi.core.VerdiAppConfigurator.createLayout(), anl.verdi.core.VerdiAppConfigurator.fillBars(), and anl.verdi.core.VerdiAppConfigurator.postWindowOpen().
void anl.verdi.core.VerdiAppConfigurator.createLayout (DockingManager manager)
Creates the initial layout in the main application window. Typically, implementors would add the initial application views here, setting up the initial gui layout.
Parameters
viewManager the ViewManager used to create the initial layout
Implements saf.core.ui.IAppConfigurator.
Definition at line 92 of file VerdiAppConfigurator.java.
References anl.verdi.core.VerdiConstants.AREA_VIEW, anl.verdi.core.VerdiAppConfigurator.closeSplash(), anl.verdi.core.VerdiConstants.DATASET_VIEW, anl.verdi.core.VerdiConstants.FORMULA_DATASET_GROUP, anl.verdi.core.VerdiConstants.FORMULA_VIEW, anl.verdi.core.VerdiApplication.getDomainPanelContext(), and anl.verdi.core.VerdiConstants.PERSPECTIVE_ID.
void anl.verdi.core.VerdiAppConfigurator.fillBars (GUIBarManager guiBarManager)
Optionally adds menu items and actions to the menu and tool bars. This can be used to programmatically add tool bar and menus / menu items for those that are not described in an xml plugin file.
Parameters
guiBarManager the GUIBarManager used to configure tool and menu bars.
Implements saf.core.ui.IAppConfigurator.
Definition at line 138 of file VerdiAppConfigurator.java.
References anl.verdi.core.VerdiAppConfigurator.closeSplash(), anl.verdi.core.VerdiConstants.FORMULA_BAR_GROUP, and anl.verdi.core.VerdiConstants.FORMULA_LABEL.
void anl.verdi.core.VerdiAppConfigurator.postWindowClose ()
Performs some arbitrary clean up type actions immediately prior to closing the main application window.
Implements saf.core.ui.IAppConfigurator.
Definition at line 165 of file VerdiAppConfigurator.java.
void anl.verdi.core.VerdiAppConfigurator.postWindowOpen (ISAFDisplay display)
Performs some arbitrary actions immediately after the main application window has been open.
Parameters
display the display representing the main application window.
Implements saf.core.ui.IAppConfigurator.
Definition at line 175 of file VerdiAppConfigurator.java.
References anl.verdi.core.VerdiAppConfigurator.closeSplash(), anl.verdi.core.VerdiConstants.DATASET_VIEW, saf.core.ui.ISAFDisplay.getFrame(), and anl.verdi.core.VerdiApplication.getProject().
boolean anl.verdi.core.VerdiAppConfigurator.preWindowClose ()
Performs some arbitrary clean up type actions immediately prior to closing the main application window. The calls the pave application to determine whether the app should exit or not.
Returns
true if the window can continue to close, false to veto the window close.
Implements saf.core.ui.IAppConfigurator.
Definition at line 202 of file VerdiAppConfigurator.java.
boolean anl.verdi.core.VerdiAppConfigurator.preWindowOpen (IWindowCustomizer customizer)
Performs some arbitrary actions prior to the main application window opening. This can be setting the application's look and feel, using the customizer parameter to set the initial window's size, title and so on.
Parameters
customizer the customizer used to customize the initial application window
Returns
true if the application should continue to open, or false to close stop application initialization. Note that return false can be a normal condition, such as a login failing.
Implements saf.core.ui.IAppConfigurator.
Definition at line 218 of file VerdiAppConfigurator.java.
References anl.verdi.core.VerdiApplication.skipSplash().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/core/VerdiAppConfigurator.java