VERDI: anl.verdi.area.target.RegionNames Class Reference
anl.verdi.area.target.RegionNames Class Reference
Public Member Functions
RegionNames ()
void copyList (RegionNames list)
void loadDefaultData ()
void loadData (String fileName)
void addRegion (String id, int keyType, String fullName)
boolean loadData (Vector data)
Static Public Member Functions
static int getKeyType (String key)
static String getRegionName (String keyName)
static RegionNames getAllRegions ()
Detailed Description
File Name:RegionNames.java Description: A list of watershed regions
Version
February 22, 2006
Author
Mary Ann Bitz
Argonne National Lab
Definition at line 31 of file RegionNames.java.
Constructor & Destructor Documentation
anl.verdi.area.target.RegionNames.RegionNames ()
Construct a new list of species
Definition at line 43 of file RegionNames.java.
Member Function Documentation
void anl.verdi.area.target.RegionNames.addRegion (String id, int keyType, String fullName)
Definition at line 110 of file RegionNames.java.
Referenced by anl.verdi.area.target.RegionNames.loadData().
void anl.verdi.area.target.RegionNames.copyList (RegionNames list)
Copy the passed in list to this one
Parameters
list the list to copy
Definition at line 51 of file RegionNames.java.
static RegionNames anl.verdi.area.target.RegionNames.getAllRegions () static
Definition at line 225 of file RegionNames.java.
static int anl.verdi.area.target.RegionNames.getKeyType (String key) static
Definition at line 85 of file RegionNames.java.
Referenced by anl.verdi.area.target.RegionNames.loadData().
static String anl.verdi.area.target.RegionNames.getRegionName (String keyName) static
Get a species matching a given name
Returns
the desired species from the global list
Definition at line 213 of file RegionNames.java.
void anl.verdi.area.target.RegionNames.loadData (String fileName)
Load in a given filename with species weights
Parameters
fileName the file to read
Definition at line 74 of file RegionNames.java.
References anl.verdi.area.FileHelper.readDataLines().
Referenced by anl.verdi.area.target.RegionNames.loadDefaultData().
boolean anl.verdi.area.target.RegionNames.loadData (Vector data)
Create species data from the given data
Parameters
data the list of data from the file
Returns
whether it was successfully loaded
Definition at line 125 of file RegionNames.java.
References anl.verdi.area.target.RegionNames.addRegion(), and anl.verdi.area.target.RegionNames.getKeyType().
void anl.verdi.area.target.RegionNames.loadDefaultData ()
Load in default chemical species weights
Definition at line 61 of file RegionNames.java.
References anl.verdi.area.target.RegionNames.loadData(), and anl.verdi.area.FileHelper.readDataLines().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/target/RegionNames.java