VERDI: simphony.util.messages.Log4jMessageListener Class Reference
simphony.util.messages.Log4jMessageListener Class Reference
Public Member Functions
Log4jMessageListener (Class clazz)
Log4jMessageListener (String name)
Log4jMessageListener ()
void messageReceived (MessageEvent event)
Static Public Member Functions
static void loadDefaultSettings ()
static void main (String[] args)
Static Public Attributes
static final String INTERNAL_ANCHOR
static final String CONFIG_FILE_NAME = "MessageCenter.log4j.properties"
Protected Member Functions
String getMessage (MessageEvent event)
Detailed Description
A MessageEventListener that forwards messages on to log4j.
Author
Jerry Vos
Definition at line 14 of file Log4jMessageListener.java.
Constructor & Destructor Documentation
simphony.util.messages.Log4jMessageListener.Log4jMessageListener (Class clazz)
Definition at line 36 of file Log4jMessageListener.java.
simphony.util.messages.Log4jMessageListener.Log4jMessageListener (String name)
Definition at line 40 of file Log4jMessageListener.java.
simphony.util.messages.Log4jMessageListener.Log4jMessageListener ()
Definition at line 44 of file Log4jMessageListener.java.
References simphony.util.messages.Log4jMessageListener.INTERNAL_ANCHOR.
Member Function Documentation
String simphony.util.messages.Log4jMessageListener.getMessage (MessageEvent event) protected
Definition at line 64 of file Log4jMessageListener.java.
References simphony.util.messages.MessageEvent.getMessage().
Referenced by simphony.util.messages.Log4jMessageListener.messageReceived().
static void simphony.util.messages.Log4jMessageListener.loadDefaultSettings () static
Loads the default logging settings. This sets up a console logger and a rolling file logger, both allowing DEBUG messages and higher. The default settings are found in the properties file in this package with the name CONFIG_FILE_NAME.
Definition at line 78 of file Log4jMessageListener.java.
References simphony.util.messages.Log4jMessageListener.CONFIG_FILE_NAME.
Referenced by simphony.util.messages.Log4jMessageListener.main().
static void simphony.util.messages.Log4jMessageListener.main (String[] args) static
Definition at line 82 of file Log4jMessageListener.java.
References simphony.util.messages.Log4jMessageListener.loadDefaultSettings().
void simphony.util.messages.Log4jMessageListener.messageReceived (MessageEvent event)
Sends a message to log4j with the event's level, message, and throwable (if it is not null).
Parameters
event a message event
Implements simphony.util.messages.MessageEventListener.
Definition at line 55 of file Log4jMessageListener.java.
References simphony.util.messages.Log4jMessageListener.getMessage(), and simphony.util.messages.MessageEvent.getThrowable().
Member Data Documentation
final String simphony.util.messages.Log4jMessageListener.CONFIG_FILE_NAME = "MessageCenter.log4j.properties" static
Definition at line 19 of file Log4jMessageListener.java.
Referenced by simphony.util.messages.Log4jMessageListener.loadDefaultSettings().
final String simphony.util.messages.Log4jMessageListener.INTERNAL_ANCHOR static
Initial value:
= "MessageCenter" + "."
            + "INTERNAL"
Definition at line 16 of file Log4jMessageListener.java.
Referenced by simphony.util.messages.Log4jMessageListener.Log4jMessageListener().
The documentation for this class was generated from the following file:
verdi_saf_core_runtime/src/simphony/util/messages/Log4jMessageListener.java