VERDI: anl.verdi.data.DataFrameAxis Class Reference
anl.verdi.data.DataFrameAxis Class Reference
Public Member Functions
int getArrayIndex ()
Public Member Functions inherited from anl.verdi.data.AxisRange
AxisRange (CoordAxis axis)
AxisRange (CoordAxis axis, int origin, int extent)
CoordAxis getAxis ()
Unit getUnits ()
boolean isCompatible (CoordAxis axis)
double getValue (int index)
String getDescription ()
String getName ()
Range getRange ()
int getExtent ()
int getOrigin ()
AxisType getAxisType ()
Static Public Member Functions
static DataFrameAxis createDataFrameAxis (CoordAxis axis, int index)
static DataFrameAxis createDataFrameAxis (CoordAxis axis, int origin, int extent, int index)
static DataFrameAxis createDataFrameAxis (DataFrameAxis axis, int index)
Protected Member Functions
DataFrameAxis (CoordAxis axis, int index)
DataFrameAxis (CoordAxis axis, int origin, int extent, int index)
DataFrameAxis (DataFrameAxis axis, int index)
Additional Inherited Members
Protected Attributes inherited from anl.verdi.data.AxisRange
CoordAxis axis
Range range
Detailed Description
Metadata for the axes / dimensions of a dataframe.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 9 of file DataFrameAxis.java.
Constructor & Destructor Documentation
anl.verdi.data.DataFrameAxis.DataFrameAxis (CoordAxis axis, int index) protected
Creates a DataFrameAxis for the specified axis with origin and extent equal to that of the axis.
Parameters
axis the axis
index the array index of this axis
Definition at line 66 of file DataFrameAxis.java.
References anl.verdi.data.AxisRange.axis, anl.verdi.data.AxisRange.getExtent(), and anl.verdi.data.CoordAxis.getRange().
Referenced by anl.verdi.data.DataFrameAxis.createDataFrameAxis().
anl.verdi.data.DataFrameAxis.DataFrameAxis (CoordAxis axis, int origin, int extent, int index) protected
Creates a DataFrameAxis for the specified axis with the specified origin and extent.
Parameters
origin the origin of the range
extent the extent of the range
axis the axis
index the array index of this axis
Definition at line 78 of file DataFrameAxis.java.
anl.verdi.data.DataFrameAxis.DataFrameAxis (DataFrameAxis axis, int index) protected
Creates a DataFrameAxis from the specified axis and index. This DataFrameAxis will have the same origin and extent as the specified axis.
Parameters
axis the axis to create this DataFrameAxis from
index the array index of this axis
Definition at line 91 of file DataFrameAxis.java.
References anl.verdi.data.AxisRange.getExtent().
Member Function Documentation
static DataFrameAxis anl.verdi.data.DataFrameAxis.createDataFrameAxis (CoordAxis axis, int index) static
Creates a DataFrameAxis for the specified axis with origin and extent equal to that of the axis.
Parameters
axis the axis
index the array index of this axis
Returns
the created DataFrameAxis
Definition at line 21 of file DataFrameAxis.java.
References anl.verdi.data.DataFrameAxis.DataFrameAxis(), anl.verdi.data.CoordAxis.getAxisType(), and anl.verdi.data.AxisType.TIME.
Referenced by anl.verdi.data.DataUtilities.createDataFrame().
static DataFrameAxis anl.verdi.data.DataFrameAxis.createDataFrameAxis (CoordAxis axis, int origin, int extent, int index) static
Creates a DataFrameAxis for the specified axis with the specified origin and extent.
Parameters
origin the origin of the range
extent the extent of the range
axis the axis
index the array index of this axis
Returns
the create axis.
Definition at line 38 of file DataFrameAxis.java.
References anl.verdi.data.DataFrameAxis.DataFrameAxis(), anl.verdi.data.CoordAxis.getAxisType(), and anl.verdi.data.AxisType.TIME.
static DataFrameAxis anl.verdi.data.DataFrameAxis.createDataFrameAxis (DataFrameAxis axis, int index) static
Creates a DataFrameAxis from the specified axis and index. This DataFrameAxis will have the same origin and extent as the specified axis.
Parameters
axis the axis to create this DataFrameAxis from
index the array index of this axis
Returns
the create axis
Definition at line 55 of file DataFrameAxis.java.
References anl.verdi.data.AxisRange.getExtent().
int anl.verdi.data.DataFrameAxis.getArrayIndex ()
Gets the index of the array dimension that corresponds to this axis.
Returns
the index of the array dimension that corresponds to this axis.
Definition at line 100 of file DataFrameAxis.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/data/DataFrameAxis.java