VERDI: anl.verdi.area.SwingWorker Class Reference
anl.verdi.area.SwingWorker Class Reference abstract
Public Member Functions
abstract Object construct ()
void finished ()
void interrupt ()
Object get ()
SwingWorker ()
void start ()
Protected Member Functions
synchronized Object getValue ()
Detailed Description
File Name:SwingWorker.java Description: Code to invoke a task when under swing Based on code off Sun site
Version
May 2004
Author
Mary Ann Bitz
Argonne National Lab This is the 3rd version of SwingWorker (also known as SwingWorker 3), an abstract class that you subclass to perform GUI-related work in a dedicated thread. For instructions on and examples of using this class, see:
http://java.sun.com/docs/books/tutorial/uiswing/misc/threads.html
Note that the API changed slightly in the 3rd version: You must now invoke start() on the SwingWorker after creating it.
Definition at line 31 of file SwingWorker.java.
Constructor & Destructor Documentation
anl.verdi.area.SwingWorker.SwingWorker ()
Start a thread that will call the construct method and then exit.
Definition at line 114 of file SwingWorker.java.
References anl.verdi.area.SwingWorker.construct(), and anl.verdi.area.SwingWorker.finished().
Member Function Documentation
abstract Object anl.verdi.area.SwingWorker.construct () abstract
Compute the value to be returned by the get method.
Referenced by anl.verdi.area.SwingWorker.SwingWorker().
void anl.verdi.area.SwingWorker.finished ()
Called on the event dispatching thread (not on the worker thread) after the construct method has returned.
Definition at line 71 of file SwingWorker.java.
Referenced by anl.verdi.area.SwingWorker.SwingWorker().
Object anl.verdi.area.SwingWorker.get ()
Return the value created by the construct method. Returns null if either the constructing thread or the current thread was interrupted before a value was produced.
Returns
the value created by the construct method
Definition at line 93 of file SwingWorker.java.
References anl.verdi.area.SwingWorker.getValue(), and anl.verdi.area.SwingWorker.interrupt().
synchronized Object anl.verdi.area.SwingWorker.getValue () protected
Get the value produced by the worker thread, or null if it hasn't been constructed yet.
Definition at line 51 of file SwingWorker.java.
Referenced by anl.verdi.area.SwingWorker.get().
void anl.verdi.area.SwingWorker.interrupt ()
A new method that interrupts the worker thread. Call this method to force the worker to stop what it's doing.
Definition at line 78 of file SwingWorker.java.
Referenced by anl.verdi.area.SwingWorker.get().
void anl.verdi.area.SwingWorker.start ()
Start the worker thread.
Definition at line 139 of file SwingWorker.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/SwingWorker.java