VERDI: anl.verdi.area.target.ProjectionCard Class Reference
anl.verdi.area.target.ProjectionCard Class Reference
Public Member Functions
ProjectionCard (WizardWindow win)
void initialize (String fileDBF, String fileName)
void showCoordinateInfo (boolean state)
CoordinateReferenceSystem getProjection ()
String getNameString ()
void setProjectionPanelInfo (String coordString)
boolean doAction (String nameString, String projString)
boolean backAction ()
boolean nextAction ()
Detailed Description
Definition at line 32 of file ProjectionCard.java.
Constructor & Destructor Documentation
anl.verdi.area.target.ProjectionCard.ProjectionCard (WizardWindow win)
Definition at line 46 of file ProjectionCard.java.
References anl.verdi.area.target.ProjectionCard.setProjectionPanelInfo().
Member Function Documentation
boolean anl.verdi.area.target.ProjectionCard.backAction ()
Definition at line 163 of file ProjectionCard.java.
boolean anl.verdi.area.target.ProjectionCard.doAction (String nameString, String projString)
Definition at line 157 of file ProjectionCard.java.
String anl.verdi.area.target.ProjectionCard.getNameString ()
Definition at line 139 of file ProjectionCard.java.
CoordinateReferenceSystem anl.verdi.area.target.ProjectionCard.getProjection ()
Definition at line 135 of file ProjectionCard.java.
Referenced by anl.verdi.area.target.OpenTargetWindow.doAction(), and anl.verdi.area.target.ProjectionCard.nextAction().
void anl.verdi.area.target.ProjectionCard.initialize (String fileDBF, String fileName)
Definition at line 100 of file ProjectionCard.java.
References anl.verdi.area.target.ProjectionCard.showCoordinateInfo().
boolean anl.verdi.area.target.ProjectionCard.nextAction ()
Definition at line 166 of file ProjectionCard.java.
References anl.verdi.area.target.ProjectionCard.getProjection().
Referenced by anl.verdi.area.target.OpenTargetWindow.doAction().
void anl.verdi.area.target.ProjectionCard.setProjectionPanelInfo (String coordString)
Set the info in the projection panel based on the coordinate string
Parameters
coordString
Definition at line 148 of file ProjectionCard.java.
References anl.verdi.area.target.ProjectionPanel.projBox.
Referenced by anl.verdi.area.target.ProjectionCard.ProjectionCard().
void anl.verdi.area.target.ProjectionCard.showCoordinateInfo (boolean state)
Definition at line 129 of file ProjectionCard.java.
Referenced by anl.verdi.area.target.ProjectionCard.initialize().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/area/target/ProjectionCard.java