VERDI: anl.verdi.plot.types.LinePlot Class Reference
anl.verdi.plot.types.LinePlot Class Reference
Classes
class AreaFinder
Public Member Functions
void viewClosed ()
LinePlot (java.util.List< DataFrame > frames, PlotConfiguration config)
List< DataFrame > getData ()
JToolBar getToolBar ()
JMenuBar getMenuBar ()
void addPlotListener (PlotListener listener)
void removePlotListener (PlotListener listener)
void updateLayer (int layer)
JPanel getPanel ()
void chartProgress (ChartProgressEvent event)
Formula.Type getType ()
void configure (PlotConfiguration config)
PlotConfiguration getPlotConfiguration ()
String getTitle ()
JMapPane getMapPane ()
Public Member Functions inherited from anl.verdi.plot.types.AbstractPlot
void exportImage (String format, File file, int width, int height) throws IOException
BufferedImage getBufferedImage ()
BufferedImage getBufferedImage (int width, int height)
void configure (PlotConfiguration config)
void configure (PlotConfiguration config, Plot.ConfigSource source)
PlotConfiguration getPlotConfiguration ()
Public Member Functions inherited from anl.verdi.plot.gui.Plot
void configure (PlotConfiguration config, ConfigSource source)
Additional Inherited Members
Protected Attributes inherited from anl.verdi.plot.types.AbstractPlot
VerdiChartPanel panel
Detailed Description
Class used to create time series line plot
Author
Mark Altaweel
Definition at line 92 of file LinePlot.java.
Constructor & Destructor Documentation
anl.verdi.plot.types.LinePlot.LinePlot (java.util.List< DataFrame > frames, PlotConfiguration config)
Check if a chart theme has been loaded.
Definition at line 116 of file LinePlot.java.
References anl.verdi.plot.types.LinePlot.configure(), anl.verdi.plot.types.LinePlot.getPlotConfiguration(), anl.verdi.plot.config.PlotConfiguration.getSubtitle1(), and anl.verdi.plot.types.AbstractPlot.panel.
Member Function Documentation
void anl.verdi.plot.types.LinePlot.addPlotListener (PlotListener listener)
Adds the specified PlotListener.
Parameters
listener the plot listener to add
Implements anl.verdi.plot.gui.Plot.
Definition at line 290 of file LinePlot.java.
void anl.verdi.plot.types.LinePlot.chartProgress (ChartProgressEvent event)
Definition at line 453 of file LinePlot.java.
References anl.verdi.plot.types.AbstractPlot.panel, and anl.verdi.plot.types.AbstractPlot.ControlAction.PROBE.
void anl.verdi.plot.types.LinePlot.configure (PlotConfiguration config)
Configure this Plot according to the specified PlotConfiguration.
Parameters
config the new plot configuration
Implements anl.verdi.plot.gui.Plot.
Definition at line 615 of file LinePlot.java.
References anl.verdi.plot.types.JChartTitlesLabels.getTitleConfigurator(), and anl.verdi.plot.config.TimeSeriesPlotConfiguration.SERIES_COLOR.
Referenced by anl.verdi.plot.types.LinePlot.LinePlot().
List<DataFrame> anl.verdi.plot.types.LinePlot.getData ()
Gets the data that this Plot plots.
Returns
the data that this Plot plots.
Implements anl.verdi.plot.gui.Plot.
Definition at line 146 of file LinePlot.java.
JMapPane anl.verdi.plot.types.LinePlot.getMapPane ()
Gets the JMapPane that contains the mapping portion of the plot component.
Returns
the mapping panel that contains the mapping portion of the plot component.
Implements anl.verdi.plot.gui.Plot.
Definition at line 678 of file LinePlot.java.
JMenuBar anl.verdi.plot.types.LinePlot.getMenuBar ()
Gets a menu bar for this Plot.
Returns
a menu bar for this Plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 185 of file LinePlot.java.
References anl.verdi.plot.types.AbstractPlot.panel, anl.verdi.plot.types.AbstractPlot.ControlAction.PROBE, and anl.verdi.plot.types.AbstractPlot.ControlAction.ZOOM.
JPanel anl.verdi.plot.types.LinePlot.getPanel ()
Gets the entire panel that contains the plot component.
Returns
the entire panel that contains the plot component.
Implements anl.verdi.plot.gui.Plot.
Definition at line 448 of file LinePlot.java.
References anl.verdi.plot.types.AbstractPlot.panel.
PlotConfiguration anl.verdi.plot.types.LinePlot.getPlotConfiguration ()
Gets this Plot's configuration data.
Returns
this Plot's configuration data.
Implements anl.verdi.plot.gui.Plot.
Definition at line 654 of file LinePlot.java.
References anl.verdi.plot.config.PlotConfiguration.FOOTER1_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.FOOTER2_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.LEGEND_SHOW, anl.verdi.plot.config.PlotConfiguration.OBS_SHOW_LEGEND, anl.verdi.plot.config.PlotConfiguration.PLOT_TYPE, anl.verdi.plot.config.TimeSeriesPlotConfiguration.SERIES_COLOR, anl.verdi.formula.Formula.Type.TIME_SERIES_LINE, anl.verdi.plot.config.PlotConfiguration.UNITS, anl.verdi.plot.config.PlotConfiguration.UNITS_COLOR, and anl.verdi.plot.config.PlotConfiguration.UNITS_FONT.
Referenced by anl.verdi.plot.types.LinePlot.LinePlot().
String anl.verdi.plot.types.LinePlot.getTitle ()
Gets this plot's current title.
Implements anl.verdi.plot.gui.Plot.
Definition at line 674 of file LinePlot.java.
JToolBar anl.verdi.plot.types.LinePlot.getToolBar ()
Gets a tool bar for this plot. This may return null if there is no tool bar.
Returns
a tool bar for this plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 156 of file LinePlot.java.
References anl.verdi.data.DataFrame.getAxes(), and anl.verdi.plot.types.LinePlot.updateLayer().
Formula.Type anl.verdi.plot.types.LinePlot.getType ()
Gets the type of the Plot.
Returns
the type of the Plot.
Implements anl.verdi.plot.gui.Plot.
Definition at line 604 of file LinePlot.java.
void anl.verdi.plot.types.LinePlot.removePlotListener (PlotListener listener)
Removes the specified PlotListener.
Parameters
listener the plot listener to remove
Implements anl.verdi.plot.gui.Plot.
Definition at line 299 of file LinePlot.java.
void anl.verdi.plot.types.LinePlot.updateLayer (int layer)
Definition at line 361 of file LinePlot.java.
Referenced by anl.verdi.plot.types.LinePlot.getToolBar().
void anl.verdi.plot.types.LinePlot.viewClosed ()
Implements anl.verdi.plot.gui.Plot.
Definition at line 105 of file LinePlot.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/types/LinePlot.java