VERDI: anl.verdi.plot.config.PlotConfiguration Class Reference
anl.verdi.plot.config.PlotConfiguration Class Reference
Public Member Functions
PlotConfiguration ()
PlotConfiguration (File file) throws IOException
PlotConfiguration (PlotConfiguration config)
void initTilePlotConf ()
void putObject (Object key, Object value)
void removeObject (Object key)
Object getObject (Object key)
void setProperty (String name, String value)
String getProperty (String name)
void setSubtitle1 (String val)
void setSubtitle2 (String val)
void setTitle (String val)
void setUnits (String val)
String getSubtitle1 ()
String getSubtitle2 ()
String getTitle ()
String getShowTitle ()
String getShowSubtitle1 ()
String getShowSubtitle2 ()
String getShowFooter1 ()
String getShowFooter2 ()
String getUnits ()
String getConfigFileName ()
void setConfigFileName (String fileName)
String getString (String key)
Color getColor (String key)
Font getFont (String key)
File getPreviousFolder ()
void setPreviousFolder (File file)
void merge (PlotConfiguration config)
void setShowTitle (String show)
void setShowTitle (Boolean aBool)
void setShowSubtitle1 (String show)
void setShowSubtitle2 (String show)
void save (File file, boolean saveTitle) throws IOException
Static Public Attributes
static final String PLOT_TYPE = PlotConfiguration.class.getName() + ".plot_type"
static final String TITLE = PlotConfiguration.class.getName() + ".title"
static final String TITLE_FONT = PlotConfiguration.class.getName() + ".title_font"
static final String TITLE_COLOR = PlotConfiguration.class.getName() + ".title_color"
static final String TITLE_SIZE = PlotConfiguration.class.getName() + ".title_size"
static final String TITLE_SHOW_LINE = PlotConfiguration.class.getName() + ".title_show_line"
static final String SUBTITLE_1 = PlotConfiguration.class.getName() + ".subtitle1"
static final String SUBTITLE_1_FONT = PlotConfiguration.class.getName() + ".subtitle1_font"
static final String SUBTITLE_1_COLOR = PlotConfiguration.class.getName() + ".subtitle1_color"
static final String SUBTITLE_1_SIZE = PlotConfiguration.class.getName() + ".subtitle1_size"
static final String SUBTITLE_1_SHOW_LINE = PlotConfiguration.class.getName() + ".subtitle1_show_line"
static final String SUBTITLE_2 = PlotConfiguration.class.getName() + ".subtitle2"
static final String SUBTITLE_2_FONT = PlotConfiguration.class.getName() + ".subtitle2_font"
static final String SUBTITLE_2_COLOR = PlotConfiguration.class.getName() + ".subtitle2_color"
static final String SUBTITLE_2_SIZE = PlotConfiguration.class.getName() + ".subtitle2_size"
static final String SUBTITLE_2_SHOW_LINE = PlotConfiguration.class.getName() + ".subtitle2_show_line"
static final String LEGEND_SHOW = PlotConfiguration.class.getName() + ".legend_show"
static final String UNITS = PlotConfiguration.class.getName() + ".units"
static final String UNITS_FONT = PlotConfiguration.class.getName() + ".units_font"
static final String UNITS_COLOR = PlotConfiguration.class.getName() + ".units_color"
static final String UNITS_SIZE = PlotConfiguration.class.getName() + ".units_size"
static final String UNITS_SHOW_TICK = PlotConfiguration.class.getName() + ".units_show_tick"
static final String UNITS_TICK_COLOR = PlotConfiguration.class.getName() + ".units_tick_color"
static final String UNITS_TICK_FONT = PlotConfiguration.class.getName() + ".units_tick_font"
static final String UNITS_TICK_SIZE = PlotConfiguration.class.getName() + ".units_tick_size"
static final String UNITS_TICK_NUMBER = PlotConfiguration.class.getName() + ".units_tick_number"
static final String DOMAIN_LABEL = PlotConfiguration.class.getName() + ".domain"
static final String DOMAIN_FONT = PlotConfiguration.class.getName() + ".domain_font"
static final String DOMAIN_COLOR = PlotConfiguration.class.getName() + ".domain_color"
static final String DOMAIN_SIZE = PlotConfiguration.class.getName() + ".domain_size"
static final String DOMAIN_SHOW_TICK = PlotConfiguration.class.getName() + ".domain_show_tick"
static final String DOMAIN_TICK_COLOR = PlotConfiguration.class.getName() + ".domain_tick_color"
static final String DOMAIN_TICK_FONT = PlotConfiguration.class.getName() + ".domain_tick_font"
static final String DOMAIN_TICK_SIZE = PlotConfiguration.class.getName() + ".domain_tick_size"
static final String DOMAIN_TICK_NUMBER = PlotConfiguration.class.getName() + ".domain_tick_number"
static final String DOMAIN_TICK_LABEL_FORMAT = PlotConfiguration.class.getName() + ".domain_tick_label_format"
static final String DOMAIN_TICK_LABEL_FORMAT_4CAT = PlotConfiguration.class.getName() + ".domain_tick_label_format_4cat"
static final String DOMAIN_TICK_LABEL_ORIENTATION = PlotConfiguration.class.getName() + ".domain_tick_label_orientation"
static final String RANGE_LABEL = PlotConfiguration.class.getName() + ".range"
static final String RANGE_FONT = PlotConfiguration.class.getName() + ".range_font"
static final String RANGE_COLOR = PlotConfiguration.class.getName() + ".range_color"
static final String RANGE_SIZE = PlotConfiguration.class.getName() + ".range_size"
static final String RANGE_SHOW_TICK = PlotConfiguration.class.getName() + ".range_show_tick"
static final String RANGE_TICK_COLOR = PlotConfiguration.class.getName() + ".range_tick_color"
static final String RANGE_TICK_FONT = PlotConfiguration.class.getName() + ".range_tick_font"
static final String RANGE_TICK_SIZE = PlotConfiguration.class.getName() + ".range_tick_size"
static final String RANGE_TICK_NUMBER = PlotConfiguration.class.getName() + ".range_tick_number"
static final String Z_LABEL = PlotConfiguration.class.getName() + ".z"
static final String Z_FONT = PlotConfiguration.class.getName() + ".z_font"
static final String Z_COLOR = PlotConfiguration.class.getName() + ".z_color"
static final String Z_SHOW_TICK = PlotConfiguration.class.getName() + ".z_show_tick"
static final String Z_TICK_COLOR = PlotConfiguration.class.getName() + ".z_tick_color"
static final String Z_TICK_FONT = PlotConfiguration.class.getName() + ".z_tick_font"
static final String Z_TICK_NUMBER = PlotConfiguration.class.getName() + ".z_tick_number"
static final String FOOTER1 = PlotConfiguration.class.getName() + ".footer_line_1"
static final String FOOTER1_SHOW_LINE = PlotConfiguration.class.getName() + ".footer_show_line_1"
static final String FOOTER1_AUTO_TEXT = PlotConfiguration.class.getName() + ".footer_line_1_auto_text"
static final String FOOTER1_COLOR = PlotConfiguration.class.getName() + ".footer_line_1_color"
static final String FOOTER1_FONT = PlotConfiguration.class.getName() + ".footer_line_1_font"
static final String FOOTER1_SIZE = PlotConfiguration.class.getName() + ".footer_line_1_size"
static final String FOOTER2 = PlotConfiguration.class.getName() + ".footer_line_2"
static final String FOOTER2_SHOW_LINE = PlotConfiguration.class.getName() + ".footer_show_line_2"
static final String FOOTER2_AUTO_TEXT = PlotConfiguration.class.getName() + ".footer_line_2_auto_text"
static final String FOOTER2_COLOR = PlotConfiguration.class.getName() + ".footer_line_2_color"
static final String FOOTER2_FONT = PlotConfiguration.class.getName() + ".footer_line_2_font"
static final String FOOTER2_SIZE = PlotConfiguration.class.getName() + ".footer_line_2_size"
static final String OBS_SHOW_LEGEND = PlotConfiguration.class.getName() + ".obs_show_legend"
static final String OBS_LEGEND_COLOR = PlotConfiguration.class.getName() + ".obs_legend_color"
static final String OBS_LEGEND_FONT = PlotConfiguration.class.getName() + ".obs_legend_font"
static final String OBS_LEGEND_SIZE = PlotConfiguration.class.getName() + ".obs_legend_size"
static final String CONFIG_FILE = PlotConfiguration.class.getName() + ".config_file"
Protected Attributes
Properties props = new Properties()
Detailed Description
Extensible plot configuration data.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 25 of file PlotConfiguration.java.
Constructor & Destructor Documentation
anl.verdi.plot.config.PlotConfiguration.PlotConfiguration ()
Definition at line 110 of file PlotConfiguration.java.
anl.verdi.plot.config.PlotConfiguration.PlotConfiguration (File file) throws IOException
Loads the configuration from the specified File.
Parameters
file the file to load from
Exceptions
IOException if there is an error during loading.
Definition at line 120 of file PlotConfiguration.java.
anl.verdi.plot.config.PlotConfiguration.PlotConfiguration (PlotConfiguration config)
Copy constructor.
Parameters
config the configuration to copy into this PlotConfiguration
Definition at line 131 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.props.
Member Function Documentation
Color anl.verdi.plot.config.PlotConfiguration.getColor (String key)
Definition at line 383 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), and anl.verdi.plot.config.TimeSeriesPlotConfiguration.getSeriesColor().
String anl.verdi.plot.config.PlotConfiguration.getConfigFileName ()
Gets the file name of a configuration file.
Returns
the file name of a configuration file.
Definition at line 366 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.CONFIG_FILE.
Font anl.verdi.plot.config.PlotConfiguration.getFont (String key)
Definition at line 387 of file PlotConfiguration.java.
Object anl.verdi.plot.config.PlotConfiguration.getObject (Object key)
Gets the object associated with the specified key from the configuration map.
Parameters
key the key of the object to return
Returns
the object associated with the specified key from the configuration map or null if no such object exists.
Definition at line 225 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.AbstractTilePlot.configure(), anl.verdi.plot.types.Contour3D.configure(), anl.verdi.plot.gui.FastTilePlot.configure(), gov.epa.emvl.TilePlot.drawAxis(), anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), gov.epa.emvl.TilePlot.drawLabels(), gov.epa.emvl.TilePlot.drawLegend(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.config.TilePlotConfiguration.getColorMap(), anl.verdi.plot.config.VertCrossPlotConfiguration.getCrossSectionRowCol(), anl.verdi.plot.config.VertCrossPlotConfiguration.getCrossSectionType(), gov.epa.emvl.TilePlot.getFootnoteHeight(), gov.epa.emvl.TilePlot.getLegendWidth(), anl.verdi.plot.gui.FastTilePlot.getMenuBar(), anl.verdi.plot.gui.ConfigDialog.init(), and anl.verdi.plot.config.PlotConfigurationIO.loadConfiguration().
File anl.verdi.plot.config.PlotConfiguration.getPreviousFolder ()
Definition at line 391 of file PlotConfiguration.java.
String anl.verdi.plot.config.PlotConfiguration.getProperty (String name)
Gets the value of the named property.
Parameters
name the name of the property to get
Returns
the value of the named property.
Definition at line 245 of file PlotConfiguration.java.
String anl.verdi.plot.config.PlotConfiguration.getShowFooter1 ()
Gets value to show or not the footer #1
Returns
TRUE or FALSE
Definition at line 340 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.FOOTER1_SHOW_LINE.
String anl.verdi.plot.config.PlotConfiguration.getShowFooter2 ()
Gets value to show or not the footer #2
Returns
TRUE or FALSE
Definition at line 348 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.FOOTER2_SHOW_LINE.
String anl.verdi.plot.config.PlotConfiguration.getShowSubtitle1 ()
Gets value to show or not the subtitle #1
Returns
TRUE or FALSE
Definition at line 324 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_SHOW_LINE.
String anl.verdi.plot.config.PlotConfiguration.getShowSubtitle2 ()
Gets value to show or not the subtitle #2
Returns
TRUE or FALSE
Definition at line 332 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_SHOW_LINE.
String anl.verdi.plot.config.PlotConfiguration.getShowTitle ()
Gets value to show or not the title
Returns
TRUE or FALSE
Definition at line 316 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.TITLE_SHOW_LINE.
String anl.verdi.plot.config.PlotConfiguration.getString (String key)
Definition at line 379 of file PlotConfiguration.java.
String anl.verdi.plot.config.PlotConfiguration.getSubtitle1 ()
Gets subtitle 1.
Returns
subtitle 1.
Definition at line 290 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1.
Referenced by anl.verdi.plot.gui.FastTilePlot.addObservationData(), anl.verdi.plot.types.Contour3D.Contour3D(), anl.verdi.plot.types.LinePlot.LinePlot(), anl.verdi.plot.types.ScatterPlot.ScatterPlot(), anl.verdi.plot.types.TilePlot.TilePlot(), anl.verdi.plot.types.TimeSeriesBarPlot.TimeSeriesBarPlot(), and anl.verdi.plot.types.VerticalCrossSectionPlot.VerticalCrossSectionPlot().
String anl.verdi.plot.config.PlotConfiguration.getSubtitle2 ()
Gets subtitle 2
Returns
subtitle 2.
Definition at line 299 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2.
String anl.verdi.plot.config.PlotConfiguration.getTitle ()
Gets the title.
Returns
the title.
Definition at line 308 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.TITLE.
Referenced by anl.verdi.plot.types.Contour3D.updateTimeStepLayer().
String anl.verdi.plot.config.PlotConfiguration.getUnits ()
Gets the units text.
Returns
the units text.
Definition at line 357 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.UNITS.
void anl.verdi.plot.config.PlotConfiguration.initTilePlotConf ()
Initialize a PlotConfiguration object to the default contents and values for a TilePlot
Definition at line 145 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.CONFIG_FILE, anl.verdi.plot.config.PlotConfiguration.FOOTER1, anl.verdi.plot.config.PlotConfiguration.FOOTER1_COLOR, anl.verdi.plot.config.PlotConfiguration.FOOTER1_FONT, anl.verdi.plot.config.PlotConfiguration.FOOTER1_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.FOOTER1_SIZE, anl.verdi.plot.config.PlotConfiguration.FOOTER2, anl.verdi.plot.config.PlotConfiguration.FOOTER2_COLOR, anl.verdi.plot.config.PlotConfiguration.FOOTER2_FONT, anl.verdi.plot.config.PlotConfiguration.FOOTER2_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.FOOTER2_SIZE, anl.verdi.plot.config.TilePlotConfiguration.GRID_LINE_COLOR, anl.verdi.plot.config.PlotConfiguration.LEGEND_SHOW, anl.verdi.plot.config.PlotConfiguration.OBS_LEGEND_COLOR, anl.verdi.plot.config.PlotConfiguration.OBS_LEGEND_FONT, anl.verdi.plot.config.PlotConfiguration.OBS_LEGEND_SIZE, anl.verdi.plot.config.PlotConfiguration.OBS_SHOW_LEGEND, anl.verdi.plot.config.TilePlotConfiguration.SHOW_GRID_LINES, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_FONT, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_SIZE, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_FONT, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_SIZE, anl.verdi.plot.config.PlotConfiguration.TITLE, anl.verdi.plot.config.PlotConfiguration.TITLE_COLOR, anl.verdi.plot.config.PlotConfiguration.TITLE_FONT, anl.verdi.plot.config.PlotConfiguration.TITLE_SHOW_LINE, anl.verdi.plot.config.PlotConfiguration.TITLE_SIZE, anl.verdi.plot.config.PlotConfiguration.UNITS, anl.verdi.plot.config.PlotConfiguration.UNITS_COLOR, anl.verdi.plot.config.PlotConfiguration.UNITS_FONT, anl.verdi.plot.config.PlotConfiguration.UNITS_SHOW_TICK, anl.verdi.plot.config.PlotConfiguration.UNITS_SIZE, anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_COLOR, anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_FONT, and anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_SIZE.
void anl.verdi.plot.config.PlotConfiguration.merge (PlotConfiguration config)
Merges this PlotConfiguration with the specified configuration. The specified config will override any configuration info in this PlotConfiguration.
Parameters
config the configuration to merge with
Definition at line 409 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.props.
void anl.verdi.plot.config.PlotConfiguration.putObject (Object key, Object value)
Puts the specified object into the configuration map with the specified key.
Parameters
key the configuration key
value the configuration value
Definition at line 204 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.gui.FootersPanel.fillConfiguration(), anl.verdi.plot.config.TilePlotConfiguration.setColorMap(), anl.verdi.plot.config.VertCrossPlotConfiguration.setCrossSectionRowCol(), anl.verdi.plot.config.VertCrossPlotConfiguration.setCrossSectionType(), and anl.verdi.plot.config.TilePlotConfiguration.setGridLines().
void anl.verdi.plot.config.PlotConfiguration.removeObject (Object key)
Removes the specified object from the configuration map.
Parameters
key the configuration key
Definition at line 214 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.props.
void anl.verdi.plot.config.PlotConfiguration.save (File file, boolean saveTitle) throws IOException
Saves this PlotConfiguration to a file.
Parameters
file the file to save the configuration to
saveTitle indicates whether to save the tile as part of the configuration or not
Exceptions
IOException if there is an error during saving.
Definition at line 451 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.props, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_FONT, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_FONT, anl.verdi.plot.config.PlotConfiguration.TITLE, anl.verdi.plot.config.PlotConfiguration.TITLE_COLOR, and anl.verdi.plot.config.PlotConfiguration.TITLE_FONT.
void anl.verdi.plot.config.PlotConfiguration.setConfigFileName (String fileName)
Sets the file name of a configuration file.
Parameters
fileName the name of the configuration file
Definition at line 375 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.CONFIG_FILE.
void anl.verdi.plot.config.PlotConfiguration.setPreviousFolder (File file)
Definition at line 395 of file PlotConfiguration.java.
void anl.verdi.plot.config.PlotConfiguration.setProperty (String name, String value)
Sets the named configuration property to the specified value.
Parameters
name the name of the property to set
value the value of the property
Definition at line 235 of file PlotConfiguration.java.
void anl.verdi.plot.config.PlotConfiguration.setShowSubtitle1 (String show)
Sets value to show or not the subtitle #1
Returns
TRUE or FALSE
Definition at line 432 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_SHOW_LINE.
void anl.verdi.plot.config.PlotConfiguration.setShowSubtitle2 (String show)
Sets value to show or not the subtitle #2
Returns
TRUE or FALSE
Definition at line 440 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_SHOW_LINE.
void anl.verdi.plot.config.PlotConfiguration.setShowTitle (String show)
Sets value to show or not the title
Returns
TRUE or FALSE
Definition at line 419 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.TITLE_SHOW_LINE.
void anl.verdi.plot.config.PlotConfiguration.setShowTitle (Boolean aBool)
Definition at line 423 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.TITLE_SHOW_LINE.
void anl.verdi.plot.config.PlotConfiguration.setSubtitle1 (String val)
Sets the text for subtitle 1.
Parameters
val the text of subtitle 1.
Definition at line 254 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1.
void anl.verdi.plot.config.PlotConfiguration.setSubtitle2 (String val)
Sets the text for subtitle 2.
Parameters
val the text of subtitle 2.
Definition at line 263 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2.
void anl.verdi.plot.config.PlotConfiguration.setTitle (String val)
Sets the title text.
Parameters
val the title text
Definition at line 272 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.TITLE.
void anl.verdi.plot.config.PlotConfiguration.setUnits (String val)
Sets the units text.
Parameters
val the units text
Definition at line 281 of file PlotConfiguration.java.
References anl.verdi.plot.config.PlotConfiguration.UNITS.
Member Data Documentation
final String anl.verdi.plot.config.PlotConfiguration.CONFIG_FILE = PlotConfiguration.class.getName() + ".config_file" static
Definition at line 104 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.config.PlotConfiguration.getConfigFileName(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), and anl.verdi.plot.config.PlotConfiguration.setConfigFileName().
final String anl.verdi.plot.config.PlotConfiguration.DOMAIN_COLOR = PlotConfiguration.class.getName() + ".domain_color" static
Definition at line 58 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawAxis(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.DOMAIN_FONT = PlotConfiguration.class.getName() + ".domain_font" static
Definition at line 57 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawAxis(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), gov.epa.emvl.TilePlot.getFootnoteHeight(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.DOMAIN_LABEL = PlotConfiguration.class.getName() + ".domain" static
Definition at line 56 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawAxis(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), gov.epa.emvl.TilePlot.getFootnoteHeight(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.DOMAIN_SHOW_TICK = PlotConfiguration.class.getName() + ".domain_show_tick" static
Definition at line 60 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), anl.verdi.commandline.ScriptHandler.constructMap(), gov.epa.emvl.TilePlot.drawAxis(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.DOMAIN_SIZE = PlotConfiguration.class.getName() + ".domain_size" static
Definition at line 59 of file PlotConfiguration.java.
final String anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_COLOR = PlotConfiguration.class.getName() + ".domain_tick_color" static
Definition at line 61 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawAxis(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_FONT = PlotConfiguration.class.getName() + ".domain_tick_font" static
Definition at line 62 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawAxis(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), gov.epa.emvl.TilePlot.getFootnoteHeight(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_LABEL_FORMAT = PlotConfiguration.class.getName() + ".domain_tick_label_format" static
Definition at line 65 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_LABEL_FORMAT_4CAT = PlotConfiguration.class.getName() + ".domain_tick_label_format_4cat" static
Definition at line 66 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.TimeSeriesBarPlot.configure(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), and anl.verdi.plot.types.TimeSeriesBarPlot.getPlotConfiguration().
final String anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_LABEL_ORIENTATION = PlotConfiguration.class.getName() + ".domain_tick_label_orientation" static
Definition at line 67 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_NUMBER = PlotConfiguration.class.getName() + ".domain_tick_number" static
Definition at line 64 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawAxis(), and anl.verdi.plot.gui.LabelsPanel.fillConfiguration().
final String anl.verdi.plot.config.PlotConfiguration.DOMAIN_TICK_SIZE = PlotConfiguration.class.getName() + ".domain_tick_size" static
Definition at line 63 of file PlotConfiguration.java.
final String anl.verdi.plot.config.PlotConfiguration.FOOTER1 = PlotConfiguration.class.getName() + ".footer_line_1" static
Definition at line 87 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.FootersPanel.fillConfiguration(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.FOOTER1_AUTO_TEXT = PlotConfiguration.class.getName() + ".footer_line_1_auto_text" static
Definition at line 89 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), and anl.verdi.plot.gui.FootersPanel.fillConfiguration().
final String anl.verdi.plot.config.PlotConfiguration.FOOTER1_COLOR = PlotConfiguration.class.getName() + ".footer_line_1_color" static
Definition at line 90 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.FootersPanel.fillConfiguration(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.FOOTER1_FONT = PlotConfiguration.class.getName() + ".footer_line_1_font" static
Definition at line 91 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.FootersPanel.fillConfiguration(), gov.epa.emvl.TilePlot.getFootnoteHeight(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.FOOTER1_SHOW_LINE = PlotConfiguration.class.getName() + ".footer_show_line_1" static
Definition at line 88 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.FootersPanel.fillConfiguration(), gov.epa.emvl.TilePlot.getFootnoteHeight(), anl.verdi.plot.types.ScatterPlot.getPlotConfiguration(), anl.verdi.plot.types.LinePlot.getPlotConfiguration(), anl.verdi.plot.types.TimeSeriesBarPlot.getPlotConfiguration(), anl.verdi.plot.types.Contour3D.getPlotConfiguration(), anl.verdi.plot.types.AbstractTilePlot.getPlotConfiguration(), anl.verdi.plot.config.PlotConfiguration.getShowFooter1(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.FOOTER1_SIZE = PlotConfiguration.class.getName() + ".footer_line_1_size" static
Definition at line 92 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.FOOTER2 = PlotConfiguration.class.getName() + ".footer_line_2" static
Definition at line 93 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.FootersPanel.fillConfiguration(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.FOOTER2_AUTO_TEXT = PlotConfiguration.class.getName() + ".footer_line_2_auto_text" static
Definition at line 95 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), and anl.verdi.plot.gui.FootersPanel.fillConfiguration().
final String anl.verdi.plot.config.PlotConfiguration.FOOTER2_COLOR = PlotConfiguration.class.getName() + ".footer_line_2_color" static
Definition at line 96 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.FootersPanel.fillConfiguration(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.FOOTER2_FONT = PlotConfiguration.class.getName() + ".footer_line_2_font" static
Definition at line 97 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.FootersPanel.fillConfiguration(), gov.epa.emvl.TilePlot.getFootnoteHeight(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.FOOTER2_SHOW_LINE = PlotConfiguration.class.getName() + ".footer_show_line_2" static
Definition at line 94 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.FootersPanel.fillConfiguration(), gov.epa.emvl.TilePlot.getFootnoteHeight(), anl.verdi.plot.types.ScatterPlot.getPlotConfiguration(), anl.verdi.plot.types.LinePlot.getPlotConfiguration(), anl.verdi.plot.types.TimeSeriesBarPlot.getPlotConfiguration(), anl.verdi.plot.types.Contour3D.getPlotConfiguration(), anl.verdi.plot.types.AbstractTilePlot.getPlotConfiguration(), anl.verdi.plot.config.PlotConfiguration.getShowFooter2(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.FOOTER2_SIZE = PlotConfiguration.class.getName() + ".footer_line_2_size" static
Definition at line 98 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.LEGEND_SHOW = PlotConfiguration.class.getName() + ".legend_show" static
Definition at line 45 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawLegend(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.ScatterPlot.getPlotConfiguration(), anl.verdi.plot.types.LinePlot.getPlotConfiguration(), anl.verdi.plot.types.TimeSeriesBarPlot.getPlotConfiguration(), anl.verdi.plot.types.Contour3D.getPlotConfiguration(), anl.verdi.plot.types.AbstractTilePlot.getPlotConfiguration(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), and anl.verdi.plot.config.PlotConfigurationIO.loadConfiguration().
final String anl.verdi.plot.config.PlotConfiguration.OBS_LEGEND_COLOR = PlotConfiguration.class.getName() + ".obs_legend_color" static
Definition at line 100 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.FootersPanel.fillConfiguration(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.OBS_LEGEND_FONT = PlotConfiguration.class.getName() + ".obs_legend_font" static
Definition at line 101 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.FootersPanel.fillConfiguration(), gov.epa.emvl.TilePlot.getFootnoteHeight(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.OBS_LEGEND_SIZE = PlotConfiguration.class.getName() + ".obs_legend_size" static
Definition at line 102 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.OBS_SHOW_LEGEND = PlotConfiguration.class.getName() + ".obs_show_legend" static
Definition at line 99 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.gui.FastTilePlot.addObservationData(), gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.FootersPanel.fillConfiguration(), gov.epa.emvl.TilePlot.getFootnoteHeight(), anl.verdi.plot.types.ScatterPlot.getPlotConfiguration(), anl.verdi.plot.types.LinePlot.getPlotConfiguration(), anl.verdi.plot.types.TimeSeriesBarPlot.getPlotConfiguration(), anl.verdi.plot.types.Contour3D.getPlotConfiguration(), anl.verdi.plot.types.AbstractTilePlot.getPlotConfiguration(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.PLOT_TYPE = PlotConfiguration.class.getName() + ".plot_type" static
Definition at line 28 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.LinePlot.getPlotConfiguration(), anl.verdi.plot.types.TimeSeriesBarPlot.getPlotConfiguration(), anl.verdi.plot.types.Contour3D.getPlotConfiguration(), and anl.verdi.plot.types.TilePlot.TilePlot().
Properties anl.verdi.plot.config.PlotConfiguration.props = new Properties() protected
Definition at line 108 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), anl.verdi.plot.config.PlotConfiguration.merge(), anl.verdi.plot.config.PlotConfiguration.PlotConfiguration(), anl.verdi.plot.config.ThemeConfig.removeObject(), anl.verdi.plot.config.PlotConfiguration.removeObject(), and anl.verdi.plot.config.PlotConfiguration.save().
final String anl.verdi.plot.config.PlotConfiguration.RANGE_COLOR = PlotConfiguration.class.getName() + ".range_color" static
Definition at line 71 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawAxis(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.RANGE_FONT = PlotConfiguration.class.getName() + ".range_font" static
Definition at line 70 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawAxis(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.RANGE_LABEL = PlotConfiguration.class.getName() + ".range" static
Definition at line 69 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawAxis(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.RANGE_SHOW_TICK = PlotConfiguration.class.getName() + ".range_show_tick" static
Definition at line 73 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), anl.verdi.commandline.ScriptHandler.constructMap(), gov.epa.emvl.TilePlot.drawAxis(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.RANGE_SIZE = PlotConfiguration.class.getName() + ".range_size" static
Definition at line 72 of file PlotConfiguration.java.
final String anl.verdi.plot.config.PlotConfiguration.RANGE_TICK_COLOR = PlotConfiguration.class.getName() + ".range_tick_color" static
Definition at line 74 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawAxis(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.RANGE_TICK_FONT = PlotConfiguration.class.getName() + ".range_tick_font" static
Definition at line 75 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawAxis(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), and anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig().
final String anl.verdi.plot.config.PlotConfiguration.RANGE_TICK_NUMBER = PlotConfiguration.class.getName() + ".range_tick_number" static
Definition at line 77 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawAxis(), and anl.verdi.plot.gui.LabelsPanel.fillConfiguration().
final String anl.verdi.plot.config.PlotConfiguration.RANGE_TICK_SIZE = PlotConfiguration.class.getName() + ".range_tick_size" static
Definition at line 76 of file PlotConfiguration.java.
final String anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1 = PlotConfiguration.class.getName() + ".subtitle1" static
Definition at line 34 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.config.PlotConfiguration.getSubtitle1(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), anl.verdi.plot.config.PlotConfiguration.save(), and anl.verdi.plot.config.PlotConfiguration.setSubtitle1().
final String anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_COLOR = PlotConfiguration.class.getName() + ".subtitle1_color" static
Definition at line 36 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.ChartTitlesPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), and anl.verdi.plot.config.PlotConfiguration.save().
final String anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_FONT = PlotConfiguration.class.getName() + ".subtitle1_font" static
Definition at line 35 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), anl.verdi.commandline.ScriptHandler.constructMap(), anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.ChartTitlesPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), and anl.verdi.plot.config.PlotConfiguration.save().
final String anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_SHOW_LINE = PlotConfiguration.class.getName() + ".subtitle1_show_line" static
Definition at line 38 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.config.PlotConfiguration.getShowSubtitle1(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), and anl.verdi.plot.config.PlotConfiguration.setShowSubtitle1().
final String anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_SIZE = PlotConfiguration.class.getName() + ".subtitle1_size" static
Definition at line 37 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2 = PlotConfiguration.class.getName() + ".subtitle2" static
Definition at line 39 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.config.PlotConfiguration.getSubtitle2(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), anl.verdi.plot.config.PlotConfiguration.save(), and anl.verdi.plot.config.PlotConfiguration.setSubtitle2().
final String anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_COLOR = PlotConfiguration.class.getName() + ".subtitle2_color" static
Definition at line 41 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.ChartTitlesPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), and anl.verdi.plot.config.PlotConfiguration.save().
final String anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_FONT = PlotConfiguration.class.getName() + ".subtitle2_font" static
Definition at line 40 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), anl.verdi.commandline.ScriptHandler.constructMap(), anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.ChartTitlesPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), and anl.verdi.plot.config.PlotConfiguration.save().
final String anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_SHOW_LINE = PlotConfiguration.class.getName() + ".subtitle2_show_line" static
Definition at line 43 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.config.PlotConfiguration.getShowSubtitle2(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), and anl.verdi.plot.config.PlotConfiguration.setShowSubtitle2().
final String anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_SIZE = PlotConfiguration.class.getName() + ".subtitle2_size" static
Definition at line 42 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.TITLE = PlotConfiguration.class.getName() + ".title" static
Definition at line 29 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.config.PlotConfiguration.getTitle(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), anl.verdi.plot.config.PlotConfiguration.save(), and anl.verdi.plot.config.PlotConfiguration.setTitle().
final String anl.verdi.plot.config.PlotConfiguration.TITLE_COLOR = PlotConfiguration.class.getName() + ".title_color" static
Definition at line 31 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.ChartTitlesPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), and anl.verdi.plot.config.PlotConfiguration.save().
final String anl.verdi.plot.config.PlotConfiguration.TITLE_FONT = PlotConfiguration.class.getName() + ".title_font" static
Definition at line 30 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), anl.verdi.commandline.ScriptHandler.constructMap(), anl.verdi.plot.gui.FastTilePlot.drawBatchImage(), gov.epa.emvl.TilePlot.drawLabels(), anl.verdi.plot.gui.ChartTitlesPanel.fillConfiguration(), anl.verdi.plot.types.JChartTitlesLabels.getConfiguration(), anl.verdi.plot.types.Contour3D.getTitlesLabelsConfig(), anl.verdi.plot.types.AbstractTilePlot.getTitlesLabelsConfig(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), and anl.verdi.plot.config.PlotConfiguration.save().
final String anl.verdi.plot.config.PlotConfiguration.TITLE_SHOW_LINE = PlotConfiguration.class.getName() + ".title_show_line" static
Definition at line 33 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.config.PlotConfiguration.getShowTitle(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), and anl.verdi.plot.config.PlotConfiguration.setShowTitle().
final String anl.verdi.plot.config.PlotConfiguration.TITLE_SIZE = PlotConfiguration.class.getName() + ".title_size" static
Definition at line 32 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.UNITS = PlotConfiguration.class.getName() + ".units" static
Definition at line 46 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), anl.verdi.area.AreaTilePlot.draw(), gov.epa.emvl.TilePlot.drawLegend(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.ScatterPlot.getPlotConfiguration(), anl.verdi.plot.types.LinePlot.getPlotConfiguration(), anl.verdi.plot.types.TimeSeriesBarPlot.getPlotConfiguration(), anl.verdi.plot.types.Contour3D.getPlotConfiguration(), anl.verdi.plot.types.AbstractTilePlot.getPlotConfiguration(), anl.verdi.plot.config.PlotConfiguration.getUnits(), anl.verdi.plot.config.PlotConfiguration.initTilePlotConf(), and anl.verdi.plot.config.PlotConfiguration.setUnits().
final String anl.verdi.plot.config.PlotConfiguration.UNITS_COLOR = PlotConfiguration.class.getName() + ".units_color" static
Definition at line 48 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawLegend(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.ScatterPlot.getPlotConfiguration(), anl.verdi.plot.types.LinePlot.getPlotConfiguration(), anl.verdi.plot.types.TimeSeriesBarPlot.getPlotConfiguration(), anl.verdi.plot.types.Contour3D.getPlotConfiguration(), anl.verdi.plot.types.AbstractTilePlot.getPlotConfiguration(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.UNITS_FONT = PlotConfiguration.class.getName() + ".units_font" static
Definition at line 47 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawLegend(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), gov.epa.emvl.TilePlot.getLegendWidth(), anl.verdi.plot.types.ScatterPlot.getPlotConfiguration(), anl.verdi.plot.types.LinePlot.getPlotConfiguration(), anl.verdi.plot.types.TimeSeriesBarPlot.getPlotConfiguration(), anl.verdi.plot.types.Contour3D.getPlotConfiguration(), anl.verdi.plot.types.AbstractTilePlot.getPlotConfiguration(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.UNITS_SHOW_TICK = PlotConfiguration.class.getName() + ".units_show_tick" static
Definition at line 50 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), anl.verdi.commandline.ScriptHandler.constructMap(), gov.epa.emvl.TilePlot.drawLegend(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), gov.epa.emvl.TilePlot.getLegendWidth(), anl.verdi.plot.types.Contour3D.getPlotConfiguration(), anl.verdi.plot.types.AbstractTilePlot.getPlotConfiguration(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.UNITS_SIZE = PlotConfiguration.class.getName() + ".units_size" static
Definition at line 49 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_COLOR = PlotConfiguration.class.getName() + ".units_tick_color" static
Definition at line 51 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawLegend(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), anl.verdi.plot.types.Contour3D.getPlotConfiguration(), anl.verdi.plot.types.AbstractTilePlot.getPlotConfiguration(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_FONT = PlotConfiguration.class.getName() + ".units_tick_font" static
Definition at line 52 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), gov.epa.emvl.TilePlot.drawLegend(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), gov.epa.emvl.TilePlot.getLegendWidth(), anl.verdi.plot.types.Contour3D.getPlotConfiguration(), anl.verdi.plot.types.AbstractTilePlot.getPlotConfiguration(), and anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_NUMBER = PlotConfiguration.class.getName() + ".units_tick_number" static
Definition at line 54 of file PlotConfiguration.java.
Referenced by gov.epa.emvl.TilePlot.drawLegend(), and anl.verdi.plot.gui.LabelsPanel.fillConfiguration().
final String anl.verdi.plot.config.PlotConfiguration.UNITS_TICK_SIZE = PlotConfiguration.class.getName() + ".units_tick_size" static
Definition at line 53 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.config.PlotConfiguration.initTilePlotConf().
final String anl.verdi.plot.config.PlotConfiguration.Z_COLOR = PlotConfiguration.class.getName() + ".z_color" static
Definition at line 81 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), and anl.verdi.plot.types.Contour3D.getPlotConfiguration().
final String anl.verdi.plot.config.PlotConfiguration.Z_FONT = PlotConfiguration.class.getName() + ".z_font" static
Definition at line 80 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), and anl.verdi.plot.types.Contour3D.getPlotConfiguration().
final String anl.verdi.plot.config.PlotConfiguration.Z_LABEL = PlotConfiguration.class.getName() + ".z" static
Definition at line 79 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), and anl.verdi.plot.types.Contour3D.getPlotConfiguration().
final String anl.verdi.plot.config.PlotConfiguration.Z_SHOW_TICK = PlotConfiguration.class.getName() + ".z_show_tick" static
Definition at line 82 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.types.Contour3D.configure(), anl.verdi.plot.gui.LabelsPanel.fillConfiguration(), and anl.verdi.plot.types.Contour3D.getPlotConfiguration().
final String anl.verdi.plot.config.PlotConfiguration.Z_TICK_COLOR = PlotConfiguration.class.getName() + ".z_tick_color" static
Definition at line 83 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.gui.LabelsPanel.fillConfiguration().
final String anl.verdi.plot.config.PlotConfiguration.Z_TICK_FONT = PlotConfiguration.class.getName() + ".z_tick_font" static
Definition at line 84 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.gui.LabelsPanel.fillConfiguration().
final String anl.verdi.plot.config.PlotConfiguration.Z_TICK_NUMBER = PlotConfiguration.class.getName() + ".z_tick_number" static
Definition at line 85 of file PlotConfiguration.java.
Referenced by anl.verdi.plot.gui.LabelsPanel.fillConfiguration().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/config/PlotConfiguration.java