VERDI: anl.verdi.plot.config.ThemeConfig Class Reference
anl.verdi.plot.config.ThemeConfig Class Reference
Public Member Functions
ThemeConfig ()
ThemeConfig (File file) throws IOException
void putObject (Object key, Object value)
void removeObject (Object key)
Object getObject (Object key)
void setProperty (String key, String value)
String getProperty (String key)
String getConfigFileName ()
void setConfigFileName (String fileName)
String getString (String key)
Color getColor (String key)
Font getFont (String key)
File getPreviousFolder ()
void setPreviousFolder (File file)
void merge (PlotConfiguration theme)
void save (File file) throws IOException
ChartTheme getTheme ()
Static Public Attributes
static final String SHOW_SHADOW = ThemeConfig.class.getName() + ".show_shadow"
static final String X_LARGE_FONT = ThemeConfig.class.getName() + ".extra_large_font"
static final String LARGE_FONT = ThemeConfig.class.getName() + ".large_font"
static final String REGULAR_FONT = ThemeConfig.class.getName() + ".regular_font"
static final String SMALL_FONT = ThemeConfig.class.getName() + ".small_font"
static final String TITLE_PAINT = ThemeConfig.class.getName() + ".title_paint"
static final String SUBTITLE_PAINT = ThemeConfig.class.getName() + ".subtitle_paint"
static final String LEGEND_PAINT = ThemeConfig.class.getName() + ".legend_paint"
static final String LEGEND_BG_PAINT = ThemeConfig.class.getName() + ".legend_background_paint"
static final String AXIS_LABEL_PAINT = ThemeConfig.class.getName() + ".axis_label_paint"
static final String TICK_LABEL_PAINT = ThemeConfig.class.getName() + ".tick_label_paint"
static final String CHART_BG_PAINT = ThemeConfig.class.getName() + ".chart_background_paint"
static final String PLOT_BG_PAINT = ThemeConfig.class.getName() + ".plot_background_paint"
static final String PLOT_OUTLINE_PAINT = ThemeConfig.class.getName() + ".plot_outline_paint"
static final String DOMAIN_GRDLN_PAINT = ThemeConfig.class.getName() + ".domain_gridline_paint"
static final String RANGE_GRDLN_PAINT = ThemeConfig.class.getName() + ".range_gridline_paint"
static final String BASELINE_PAINT = ThemeConfig.class.getName() + ".baseline_paint"
static final String CROSSHAIR_PAINT = ThemeConfig.class.getName() + ".crosshair_paint"
static final String ITEM_LABEL_PAINT = ThemeConfig.class.getName() + ".item_label_paint"
static final String SHADOW_PAINT = ThemeConfig.class.getName() + ".shadow_paint"
Detailed Description
Definition at line 20 of file ThemeConfig.java.
Constructor & Destructor Documentation
anl.verdi.plot.config.ThemeConfig.ThemeConfig ()
Definition at line 45 of file ThemeConfig.java.
anl.verdi.plot.config.ThemeConfig.ThemeConfig (File file) throws IOException
Definition at line 49 of file ThemeConfig.java.
Member Function Documentation
Color anl.verdi.plot.config.ThemeConfig.getColor (String key)
Definition at line 131 of file ThemeConfig.java.
String anl.verdi.plot.config.ThemeConfig.getConfigFileName ()
Gets the file name of a configuration file.
Returns
the file name of a configuration file.
Definition at line 114 of file ThemeConfig.java.
Font anl.verdi.plot.config.ThemeConfig.getFont (String key)
Definition at line 135 of file ThemeConfig.java.
Object anl.verdi.plot.config.ThemeConfig.getObject (Object key)
Gets the object associated with the specified key from the configuration map.
Parameters
key the key of the object to return
Returns
the object associated with the specified key from the configuration map or null if no such object exists.
Definition at line 85 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme().
File anl.verdi.plot.config.ThemeConfig.getPreviousFolder ()
Definition at line 139 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme().
String anl.verdi.plot.config.ThemeConfig.getProperty (String key)
Gets the value of the named property.
Parameters
key the name of the property to get
Returns
the value of the named property.
Definition at line 105 of file ThemeConfig.java.
String anl.verdi.plot.config.ThemeConfig.getString (String key)
Definition at line 127 of file ThemeConfig.java.
ChartTheme anl.verdi.plot.config.ThemeConfig.getTheme ()
Definition at line 169 of file ThemeConfig.java.
References anl.verdi.plot.config.ThemeConfig.AXIS_LABEL_PAINT, anl.verdi.plot.config.ThemeConfig.BASELINE_PAINT, anl.verdi.plot.config.ThemeConfig.CHART_BG_PAINT, anl.verdi.plot.config.ThemeConfig.CROSSHAIR_PAINT, anl.verdi.plot.config.ThemeConfig.DOMAIN_GRDLN_PAINT, anl.verdi.plot.config.ThemeConfig.getObject(), anl.verdi.plot.config.ThemeConfig.getPreviousFolder(), anl.verdi.plot.config.ThemeConfig.ITEM_LABEL_PAINT, anl.verdi.plot.config.ThemeConfig.LARGE_FONT, anl.verdi.plot.config.ThemeConfig.LEGEND_BG_PAINT, anl.verdi.plot.config.ThemeConfig.LEGEND_PAINT, anl.verdi.plot.config.ThemeConfig.PLOT_BG_PAINT, anl.verdi.plot.config.ThemeConfig.PLOT_OUTLINE_PAINT, anl.verdi.plot.config.PlotConfiguration.props, anl.verdi.plot.config.ThemeConfig.RANGE_GRDLN_PAINT, anl.verdi.plot.config.ThemeConfig.REGULAR_FONT, anl.verdi.plot.config.ThemeConfig.SHADOW_PAINT, anl.verdi.plot.config.ThemeConfig.SHOW_SHADOW, anl.verdi.plot.config.ThemeConfig.SMALL_FONT, anl.verdi.plot.config.ThemeConfig.SUBTITLE_PAINT, anl.verdi.plot.config.ThemeConfig.TICK_LABEL_PAINT, anl.verdi.plot.config.ThemeConfig.TITLE_PAINT, and anl.verdi.plot.config.ThemeConfig.X_LARGE_FONT.
void anl.verdi.plot.config.ThemeConfig.merge (PlotConfiguration theme)
Merges this theme with the specified configuration. The specified theme will override any configuration info in this theme.
Parameters
theme the configuration to merge with
Definition at line 154 of file ThemeConfig.java.
void anl.verdi.plot.config.ThemeConfig.putObject (Object key, Object value)
Puts the specified object into the configuration map with the specified key.
Parameters
key the configuration key
value the configuration value
Definition at line 62 of file ThemeConfig.java.
void anl.verdi.plot.config.ThemeConfig.removeObject (Object key)
Removes the specified object from the configuration map.
Parameters
key the configuration key
Definition at line 72 of file ThemeConfig.java.
References anl.verdi.plot.config.PlotConfiguration.props.
void anl.verdi.plot.config.ThemeConfig.save (File file) throws IOException
Saves this theme to a file.
Parameters
file the file to save the configuration to
Exceptions
IOException if there is an error during saving.
Definition at line 164 of file ThemeConfig.java.
void anl.verdi.plot.config.ThemeConfig.setConfigFileName (String fileName)
Sets the file name of a configuration file.
Parameters
fileName the name of the configuration file
Definition at line 123 of file ThemeConfig.java.
void anl.verdi.plot.config.ThemeConfig.setPreviousFolder (File file)
Definition at line 143 of file ThemeConfig.java.
void anl.verdi.plot.config.ThemeConfig.setProperty (String key, String value)
Sets the named configuration property to the specified value.
Parameters
key the name of the property to set
value the value of the property
Definition at line 95 of file ThemeConfig.java.
Member Data Documentation
final String anl.verdi.plot.config.ThemeConfig.AXIS_LABEL_PAINT = ThemeConfig.class.getName() + ".axis_label_paint" static
Definition at line 31 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.BASELINE_PAINT = ThemeConfig.class.getName() + ".baseline_paint" static
Definition at line 38 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.CHART_BG_PAINT = ThemeConfig.class.getName() + ".chart_background_paint" static
Definition at line 33 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.CROSSHAIR_PAINT = ThemeConfig.class.getName() + ".crosshair_paint" static
Definition at line 39 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.DOMAIN_GRDLN_PAINT = ThemeConfig.class.getName() + ".domain_gridline_paint" static
Definition at line 36 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.ITEM_LABEL_PAINT = ThemeConfig.class.getName() + ".item_label_paint" static
Definition at line 40 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.LARGE_FONT = ThemeConfig.class.getName() + ".large_font" static
Definition at line 24 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.LEGEND_BG_PAINT = ThemeConfig.class.getName() + ".legend_background_paint" static
Definition at line 30 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.LEGEND_PAINT = ThemeConfig.class.getName() + ".legend_paint" static
Definition at line 29 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.PLOT_BG_PAINT = ThemeConfig.class.getName() + ".plot_background_paint" static
Definition at line 34 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.PLOT_OUTLINE_PAINT = ThemeConfig.class.getName() + ".plot_outline_paint" static
Definition at line 35 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.RANGE_GRDLN_PAINT = ThemeConfig.class.getName() + ".range_gridline_paint" static
Definition at line 37 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.REGULAR_FONT = ThemeConfig.class.getName() + ".regular_font" static
Definition at line 25 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.SHADOW_PAINT = ThemeConfig.class.getName() + ".shadow_paint" static
Definition at line 41 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.SHOW_SHADOW = ThemeConfig.class.getName() + ".show_shadow" static
Definition at line 22 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.SMALL_FONT = ThemeConfig.class.getName() + ".small_font" static
Definition at line 26 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.SUBTITLE_PAINT = ThemeConfig.class.getName() + ".subtitle_paint" static
Definition at line 28 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.TICK_LABEL_PAINT = ThemeConfig.class.getName() + ".tick_label_paint" static
Definition at line 32 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.TITLE_PAINT = ThemeConfig.class.getName() + ".title_paint" static
Definition at line 27 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
final String anl.verdi.plot.config.ThemeConfig.X_LARGE_FONT = ThemeConfig.class.getName() + ".extra_large_font" static
Definition at line 23 of file ThemeConfig.java.
Referenced by anl.verdi.plot.config.ThemeConfig.getTheme(), and anl.verdi.plot.gui.ChartThemePanel.setThemeProperties().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/config/ThemeConfig.java