VERDI: anl.verdi.commandline.task.TilePlotTask Class Reference
anl.verdi.commandline.task.TilePlotTask Class Reference
Public Member Functions
TilePlotTask (Map< String, String > map, File[] dataFiles, VerdiApplication vApp, String[] subDomainArgs)
TilePlotTask (Map< String, String > map, File[] dataFiles, VerdiApplication vApp)
void run ()
int getVectorSamplingIncr ()
void setVectorSamplingIncr (int vectorSamplingIncr)
Static Public Attributes
static final String JPEG = "jpeg"
static final String JPG = "jpg"
static final String TIFF = "tiff"
static final String TIF = "tif"
static final String PNG = "png"
static final String BMP = "bmp"
static final String EPS = "eps"
Detailed Description
Definition at line 32 of file TilePlotTask.java.
Constructor & Destructor Documentation
anl.verdi.commandline.task.TilePlotTask.TilePlotTask (Map< String, String > map, File[] dataFiles, VerdiApplication vApp, String[] subDomainArgs)
Definition at line 57 of file TilePlotTask.java.
anl.verdi.commandline.task.TilePlotTask.TilePlotTask (Map< String, String > map, File[] dataFiles, VerdiApplication vApp)
Definition at line 64 of file TilePlotTask.java.
Member Function Documentation
int anl.verdi.commandline.task.TilePlotTask.getVectorSamplingIncr ()
Returns
the vectorSamplingIncr
Definition at line 302 of file TilePlotTask.java.
void anl.verdi.commandline.task.TilePlotTask.run ()
Implements anl.verdi.commandline.AbstractTask.
Definition at line 72 of file TilePlotTask.java.
References anl.verdi.gui.DatasetListModel.getElementAt(), anl.verdi.core.VerdiApplication.getProject(), anl.verdi.gui.DatasetListModel.getSize(), and anl.verdi.core.VerdiConstants.TIME_STEP.
void anl.verdi.commandline.task.TilePlotTask.setVectorSamplingIncr (int vectorSamplingIncr)
Parameters
vectorSamplingIncr the vectorSamplingIncr to set
Definition at line 309 of file TilePlotTask.java.
Member Data Documentation
final String anl.verdi.commandline.task.TilePlotTask.BMP = "bmp" static
Definition at line 41 of file TilePlotTask.java.
final String anl.verdi.commandline.task.TilePlotTask.EPS = "eps" static
Definition at line 42 of file TilePlotTask.java.
final String anl.verdi.commandline.task.TilePlotTask.JPEG = "jpeg" static
Definition at line 36 of file TilePlotTask.java.
final String anl.verdi.commandline.task.TilePlotTask.JPG = "jpg" static
Definition at line 37 of file TilePlotTask.java.
final String anl.verdi.commandline.task.TilePlotTask.PNG = "png" static
Definition at line 40 of file TilePlotTask.java.
final String anl.verdi.commandline.task.TilePlotTask.TIF = "tif" static
Definition at line 39 of file TilePlotTask.java.
final String anl.verdi.commandline.task.TilePlotTask.TIFF = "tiff" static
Definition at line 38 of file TilePlotTask.java.
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/commandline/task/TilePlotTask.java