VERDI: anl.verdi.gui.HelpWindowWithContents Class Reference
anl.verdi.gui.HelpWindowWithContents Class Reference
Public Member Functions
HelpWindowWithContents (Dialog dialog, String title, String doc, String doc2)
HelpWindowWithContents (Frame frame, String title, String doc, String doc2)
void inits (String doc, String doc2)
boolean doAction ()
void dispose ()
Public Member Functions inherited from anl.verdi.gui.OKWindow
OKWindow (Dialog fr, String title, boolean state)
OKWindow (Frame fr, String title, boolean state)
OKWindow (Frame fr, String title, boolean state, String[] buttons)
void actionPerformed (ActionEvent event)
void addPrintButton ()
void busy ()
boolean doAction ()
void doPrint ()
Frame getParentFrame ()
void notBusy ()
void oKAction ()
void centerOver (Component comp)
void setEnabled (boolean state)
void windowActivated (WindowEvent e)
void windowClosed (WindowEvent e)
void windowClosing (WindowEvent e)
void windowDeactivated (WindowEvent e)
void windowDeiconified (WindowEvent e)
void windowIconified (WindowEvent e)
void windowOpened (WindowEvent e)
Public Member Functions inherited from anl.verdi.gui.ExtendedDialog
ExtendedDialog (Frame owner) throws HeadlessException
ExtendedDialog (Frame owner, boolean modal) throws HeadlessException
ExtendedDialog (Frame owner, String title) throws HeadlessException
ExtendedDialog (Frame owner, String title, boolean modal) throws HeadlessException
ExtendedDialog (Frame owner, String title, boolean modal, GraphicsConfiguration gc)
void show ()
Static Public Member Functions
static void showContents (Window frame, String title, String doc, String doc2)
Static Public Member Functions inherited from anl.verdi.gui.OKWindow
static void setChildrenEnabled (Component item, boolean state)
Static Public Member Functions inherited from anl.verdi.gui.ExtendedDialog
static void setDefaultParent (Frame win)
static Frame getDefaultParent ()
Additional Inherited Members
Protected Attributes inherited from anl.verdi.gui.OKWindow
JPanel buttonPanel
Frame parentFrame
Detailed Description
Definition at line 26 of file HelpWindowWithContents.java.
Constructor & Destructor Documentation
anl.verdi.gui.HelpWindowWithContents.HelpWindowWithContents (Dialog dialog, String title, String doc, String doc2)
Definition at line 33 of file HelpWindowWithContents.java.
References anl.verdi.gui.HelpWindowWithContents.inits().
Referenced by anl.verdi.gui.HelpWindowWithContents.showContents().
anl.verdi.gui.HelpWindowWithContents.HelpWindowWithContents (Frame frame, String title, String doc, String doc2)
Definition at line 37 of file HelpWindowWithContents.java.
References anl.verdi.gui.HelpWindowWithContents.inits().
Member Function Documentation
void anl.verdi.gui.HelpWindowWithContents.dispose ()
Definition at line 136 of file HelpWindowWithContents.java.
Referenced by anl.verdi.gui.HelpWindowWithContents.inits().
boolean anl.verdi.gui.HelpWindowWithContents.doAction ()
Definition at line 133 of file HelpWindowWithContents.java.
void anl.verdi.gui.HelpWindowWithContents.inits (String doc, String doc2)
Definition at line 42 of file HelpWindowWithContents.java.
References anl.verdi.gui.HelpWindowWithContents.dispose(), anl.verdi.gui.OKWindow.windowActivated(), and anl.verdi.gui.OKWindow.windowClosing().
Referenced by anl.verdi.gui.HelpWindowWithContents.HelpWindowWithContents().
static void anl.verdi.gui.HelpWindowWithContents.showContents (Window frame, String title, String doc, String doc2) static
Definition at line 141 of file HelpWindowWithContents.java.
References anl.verdi.gui.HelpWindowWithContents.HelpWindowWithContents().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/gui/HelpWindowWithContents.java