VERDI: anl.verdi.parser.SimpleNode Class Reference
anl.verdi.parser.SimpleNode Class Reference
Public Member Functions
SimpleNode (int i)
SimpleNode (Parser p, int i)
Object getInfo ()
void setInfo (Object info)
void jjtOpen ()
void jjtClose ()
void jjtSetParent (Node n)
Node jjtGetParent ()
void jjtAddChild (Node n, int i)
Node jjtGetChild (int i)
int jjtGetNumChildren ()
String toString ()
String toString (String prefix)
void dump (String prefix)
void gatherInfo (ASTTreeInfo info)
FormulaArray evaluate (Frame frame) throws IllegalFormulaException
void preprocess (Frame frame) throws IllegalFormulaException
Protected Attributes
Node parent
Node[] children
int id
Parser parser
Object info
Static Protected Attributes
static final double DEG_TO_RAD_FACTOR = 180 * Math.PI
Detailed Description
Definition at line 11 of file SimpleNode.java.
Constructor & Destructor Documentation
anl.verdi.parser.SimpleNode.SimpleNode (int i)
Definition at line 24 of file SimpleNode.java.
Referenced by anl.verdi.parser.SimpleNode.dump(), anl.verdi.parser.SimpleNode.gatherInfo(), and anl.verdi.parser.SimpleNode.preprocess().
anl.verdi.parser.SimpleNode.SimpleNode (Parser p, int i)
Definition at line 28 of file SimpleNode.java.
References anl.verdi.parser.SimpleNode.parser.
Member Function Documentation
void anl.verdi.parser.SimpleNode.dump (String prefix)
Definition at line 91 of file SimpleNode.java.
References anl.verdi.parser.SimpleNode.children, anl.verdi.parser.SimpleNode.SimpleNode(), and anl.verdi.parser.SimpleNode.toString().
FormulaArray anl.verdi.parser.SimpleNode.evaluate (Frame frame) throws IllegalFormulaException
Evaluates this Node.
Parameters
frame
Returns
the result of the evaluation.
Implements anl.verdi.parser.Node.
Definition at line 123 of file SimpleNode.java.
void anl.verdi.parser.SimpleNode.gatherInfo (ASTTreeInfo info)
Gathers info about this node and places it into the info object.
Parameters
info collection of tree info
Definition at line 108 of file SimpleNode.java.
References anl.verdi.parser.SimpleNode.children, anl.verdi.parser.SimpleNode.info, and anl.verdi.parser.SimpleNode.SimpleNode().
Object anl.verdi.parser.SimpleNode.getInfo ()
Definition at line 33 of file SimpleNode.java.
References anl.verdi.parser.SimpleNode.info.
void anl.verdi.parser.SimpleNode.jjtAddChild (Node n, int i)
This method tells the node to add its argument to the node's list of children.
Implements anl.verdi.parser.Node.
Definition at line 55 of file SimpleNode.java.
References anl.verdi.parser.SimpleNode.children.
void anl.verdi.parser.SimpleNode.jjtClose ()
This method is called after all the child nodes have been added.
Implements anl.verdi.parser.Node.
Definition at line 44 of file SimpleNode.java.
Node anl.verdi.parser.SimpleNode.jjtGetChild (int i)
This method returns a child node. The children are numbered from zero, left to right.
Implements anl.verdi.parser.Node.
Definition at line 66 of file SimpleNode.java.
References anl.verdi.parser.SimpleNode.children.
Referenced by anl.verdi.parser.ASTAdd.evaluate(), anl.verdi.parser.ASTDiv.evaluate(), anl.verdi.parser.ASTGreaterEq.evaluate(), anl.verdi.parser.ASTMod.evaluate(), anl.verdi.parser.ASTSubtract.evaluate(), anl.verdi.parser.ASTNotEqual.evaluate(), anl.verdi.parser.ASTGreaterThan.evaluate(), anl.verdi.parser.ASTLessEq.evaluate(), anl.verdi.parser.ASTOr.evaluate(), anl.verdi.parser.ASTPow.evaluate(), anl.verdi.parser.ASTLessThan.evaluate(), anl.verdi.parser.ASTstart.evaluate(), anl.verdi.parser.ASTAnd.evaluate(), anl.verdi.parser.ASTEqEqual.evaluate(), anl.verdi.parser.ASTMul.evaluate(), anl.verdi.parser.ASTMin.evaluate(), anl.verdi.parser.ASTMax.evaluate(), anl.verdi.parser.ASTSum.evaluate(), anl.verdi.parser.ASTLn.evaluate(), anl.verdi.parser.ASTLog.evaluate(), anl.verdi.parser.ASTSin.evaluate(), anl.verdi.parser.ASTCosd.evaluate(), anl.verdi.parser.ASTCos.evaluate(), anl.verdi.parser.ASTExp.evaluate(), anl.verdi.parser.ASTTan.evaluate(), anl.verdi.parser.ASTNeg.evaluate(), anl.verdi.parser.ASTTand.evaluate(), anl.verdi.parser.ASTSind.evaluate(), anl.verdi.parser.ASTSqrt.evaluate(), anl.verdi.parser.ASTSqr.evaluate(), anl.verdi.parser.ASTMean.evaluate(), anl.verdi.parser.ASTAbs.evaluate(), anl.verdi.parser.AggregateFuncNode.max(), and anl.verdi.parser.AggregateFuncNode.min().
int anl.verdi.parser.SimpleNode.jjtGetNumChildren ()
Return the number of children the node has.
Implements anl.verdi.parser.Node.
Definition at line 70 of file SimpleNode.java.
References anl.verdi.parser.SimpleNode.children.
Node anl.verdi.parser.SimpleNode.jjtGetParent ()
Implements anl.verdi.parser.Node.
Definition at line 51 of file SimpleNode.java.
References anl.verdi.parser.SimpleNode.parent.
void anl.verdi.parser.SimpleNode.jjtOpen ()
This method is called after the node has been made the current node. It indicates that child nodes can now be added to it.
Implements anl.verdi.parser.Node.
Definition at line 41 of file SimpleNode.java.
void anl.verdi.parser.SimpleNode.jjtSetParent (Node n)
This pair of methods are used to inform the node of its parent.
Implements anl.verdi.parser.Node.
Definition at line 47 of file SimpleNode.java.
References anl.verdi.parser.SimpleNode.parent.
void anl.verdi.parser.SimpleNode.preprocess (Frame frame) throws IllegalFormulaException
Performs any node level preprocessing prior to any evaluation. This should only be called once on the tree. This default implementation just calls preprocess on its children.
Parameters
frame
Implements anl.verdi.parser.Node.
Definition at line 135 of file SimpleNode.java.
References anl.verdi.parser.SimpleNode.children, and anl.verdi.parser.SimpleNode.SimpleNode().
void anl.verdi.parser.SimpleNode.setInfo (Object info)
Definition at line 37 of file SimpleNode.java.
References anl.verdi.parser.SimpleNode.info.
String anl.verdi.parser.SimpleNode.toString ()
Definition at line 80 of file SimpleNode.java.
References anl.verdi.parser.SimpleNode.id.
Referenced by anl.verdi.parser.SimpleNode.dump(), and anl.verdi.parser.SimpleNode.toString().
String anl.verdi.parser.SimpleNode.toString (String prefix)
Definition at line 84 of file SimpleNode.java.
References anl.verdi.parser.SimpleNode.toString().
Member Data Documentation
Node [] anl.verdi.parser.SimpleNode.children protected
Definition at line 19 of file SimpleNode.java.
Referenced by anl.verdi.parser.ASTTreeInfo.ASTTreeInfo(), anl.verdi.parser.SimpleNode.dump(), anl.verdi.parser.SimpleNode.gatherInfo(), anl.verdi.parser.SimpleNode.jjtAddChild(), anl.verdi.parser.SimpleNode.jjtGetChild(), anl.verdi.parser.SimpleNode.jjtGetNumChildren(), and anl.verdi.parser.SimpleNode.preprocess().
final double anl.verdi.parser.SimpleNode.DEG_TO_RAD_FACTOR = 180 * Math.PI static protected
Definition at line 16 of file SimpleNode.java.
int anl.verdi.parser.SimpleNode.id protected
Definition at line 20 of file SimpleNode.java.
Referenced by anl.verdi.parser.SimpleNode.toString().
Object anl.verdi.parser.SimpleNode.info protected
Definition at line 22 of file SimpleNode.java.
Referenced by anl.verdi.parser.AggregateFuncNode.gatherInfo(), anl.verdi.parser.ASTVar.gatherInfo(), anl.verdi.parser.SimpleNode.gatherInfo(), anl.verdi.parser.SimpleNode.getInfo(), and anl.verdi.parser.SimpleNode.setInfo().
Node anl.verdi.parser.SimpleNode.parent protected
Definition at line 18 of file SimpleNode.java.
Referenced by anl.verdi.parser.SimpleNode.jjtGetParent(), and anl.verdi.parser.SimpleNode.jjtSetParent().
Parser anl.verdi.parser.SimpleNode.parser protected
Definition at line 21 of file SimpleNode.java.
Referenced by anl.verdi.parser.SimpleNode.SimpleNode().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/parser/SimpleNode.java