VERDI: anl.verdi.gui.AbstractListElement Class Reference
anl.verdi.gui.AbstractListElement Class Reference abstract
Public Member Functions
boolean isLayerUsed ()
void setLayerUsed (boolean layerUsed)
boolean isTimeUsed ()
void setTimeUsed (boolean timeUsed)
int getLayerMax ()
void setLayerMax (int layerMax)
int getLayerMin ()
void setLayerMin (int layerMin)
int getTimeMax ()
void setTimeMax (int timeMax)
int getTimeMin ()
void setTimeMin (int timeMin)
int getXMax ()
void setXMax (int xMax)
int getXMin ()
void setXMin (int xMin)
int getYMax ()
void setYMax (int yMax)
int getYMin ()
void setYMin (int yMin)
boolean isXYUsed ()
void setXYUsed (boolean xyUsed)
void setDomain (int xMin, int xMax, int yMin, int yMax)
abstract Axes< CoordAxis > getAxes ()
abstract Dataset getDataset ()
Static Public Attributes
static int NO_TIME_VALUE = -1
static int NO_LAYER_VALUE = -1
Protected Attributes
int timeMin
int timeMax
int layerMin
int layerMax
Detailed Description
Abstract class for formula and dataset list elements.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 13 of file AbstractListElement.java.
Member Function Documentation
abstract Axes<CoordAxis> anl.verdi.gui.AbstractListElement.getAxes () abstract
Referenced by anl.verdi.gui.FormulasPanel.setDomainValues(), and anl.verdi.gui.DataSetPanel.setDomainValues().
abstract Dataset anl.verdi.gui.AbstractListElement.getDataset () abstract
Referenced by anl.verdi.gui.DomainPanel.editDomain(), and anl.verdi.gui.DomainPanel.setDomainValues().
int anl.verdi.gui.AbstractListElement.getLayerMax ()
Definition at line 42 of file AbstractListElement.java.
References anl.verdi.gui.AbstractListElement.layerMax.
Referenced by anl.verdi.core.Project.createRanges(), and anl.verdi.gui.DataSetPanel.setLayerValues().
int anl.verdi.gui.AbstractListElement.getLayerMin ()
Definition at line 50 of file AbstractListElement.java.
References anl.verdi.gui.AbstractListElement.layerMin.
Referenced by anl.verdi.gui.FormulasPanel.setLayerValues(), and anl.verdi.gui.DataSetPanel.setLayerValues().
int anl.verdi.gui.AbstractListElement.getTimeMax ()
Definition at line 58 of file AbstractListElement.java.
References anl.verdi.gui.AbstractListElement.timeMax.
Referenced by anl.verdi.core.Project.createRanges(), and anl.verdi.util.CompatibilityChecker.isCompatible().
int anl.verdi.gui.AbstractListElement.getTimeMin ()
Definition at line 66 of file AbstractListElement.java.
References anl.verdi.gui.AbstractListElement.timeMin.
int anl.verdi.gui.AbstractListElement.getXMax ()
Definition at line 74 of file AbstractListElement.java.
Referenced by anl.verdi.core.Project.createRanges(), anl.verdi.gui.DomainPanel.editDomain(), and anl.verdi.gui.DomainPanel.setDomainValues().
int anl.verdi.gui.AbstractListElement.getXMin ()
Definition at line 82 of file AbstractListElement.java.
Referenced by anl.verdi.gui.DomainPanel.setDomainValues().
int anl.verdi.gui.AbstractListElement.getYMax ()
Definition at line 90 of file AbstractListElement.java.
Referenced by anl.verdi.core.Project.createRanges(), and anl.verdi.gui.DomainPanel.setDomainValues().
int anl.verdi.gui.AbstractListElement.getYMin ()
Definition at line 98 of file AbstractListElement.java.
Referenced by anl.verdi.gui.DomainPanel.setDomainValues().
boolean anl.verdi.gui.AbstractListElement.isLayerUsed ()
Definition at line 26 of file AbstractListElement.java.
Referenced by anl.verdi.core.Project.createRanges(), anl.verdi.gui.AbstractListElement.setLayerUsed(), and anl.verdi.gui.FormulasPanel.setLayerValues().
boolean anl.verdi.gui.AbstractListElement.isTimeUsed ()
Definition at line 34 of file AbstractListElement.java.
Referenced by anl.verdi.core.Project.createRanges(), anl.verdi.util.CompatibilityChecker.isCompatible(), and anl.verdi.gui.AbstractListElement.setTimeUsed().
boolean anl.verdi.gui.AbstractListElement.isXYUsed ()
Definition at line 106 of file AbstractListElement.java.
Referenced by anl.verdi.core.Project.createRanges(), anl.verdi.gui.AbstractListElement.setDomain(), and anl.verdi.gui.AbstractListElement.setXYUsed().
void anl.verdi.gui.AbstractListElement.setDomain (int xMin, int xMax, int yMin, int yMax)
Definition at line 113 of file AbstractListElement.java.
References anl.verdi.gui.AbstractListElement.isXYUsed(), anl.verdi.gui.AbstractListElement.setXMax(), anl.verdi.gui.AbstractListElement.setXMin(), anl.verdi.gui.AbstractListElement.setYMax(), and anl.verdi.gui.AbstractListElement.setYMin().
void anl.verdi.gui.AbstractListElement.setLayerMax (int layerMax)
Definition at line 46 of file AbstractListElement.java.
References anl.verdi.gui.AbstractListElement.layerMax.
void anl.verdi.gui.AbstractListElement.setLayerMin (int layerMin)
Definition at line 54 of file AbstractListElement.java.
References anl.verdi.gui.AbstractListElement.layerMin.
void anl.verdi.gui.AbstractListElement.setLayerUsed (boolean layerUsed)
Definition at line 30 of file AbstractListElement.java.
References anl.verdi.gui.AbstractListElement.isLayerUsed().
void anl.verdi.gui.AbstractListElement.setTimeMax (int timeMax)
Definition at line 62 of file AbstractListElement.java.
References anl.verdi.gui.AbstractListElement.timeMax.
void anl.verdi.gui.AbstractListElement.setTimeMin (int timeMin)
Definition at line 70 of file AbstractListElement.java.
References anl.verdi.gui.AbstractListElement.timeMin.
void anl.verdi.gui.AbstractListElement.setTimeUsed (boolean timeUsed)
Definition at line 38 of file AbstractListElement.java.
References anl.verdi.gui.AbstractListElement.isTimeUsed().
void anl.verdi.gui.AbstractListElement.setXMax (int xMax)
Definition at line 78 of file AbstractListElement.java.
Referenced by anl.verdi.gui.AbstractListElement.setDomain().
void anl.verdi.gui.AbstractListElement.setXMin (int xMin)
Definition at line 86 of file AbstractListElement.java.
Referenced by anl.verdi.gui.AbstractListElement.setDomain().
void anl.verdi.gui.AbstractListElement.setXYUsed (boolean xyUsed)
Definition at line 110 of file AbstractListElement.java.
References anl.verdi.gui.AbstractListElement.isXYUsed().
void anl.verdi.gui.AbstractListElement.setYMax (int yMax)
Definition at line 94 of file AbstractListElement.java.
Referenced by anl.verdi.gui.AbstractListElement.setDomain().
void anl.verdi.gui.AbstractListElement.setYMin (int yMin)
Definition at line 102 of file AbstractListElement.java.
Referenced by anl.verdi.gui.AbstractListElement.setDomain().
Member Data Documentation
int anl.verdi.gui.AbstractListElement.layerMax protected
Definition at line 21 of file AbstractListElement.java.
Referenced by anl.verdi.gui.DatasetListElement.DatasetListElement(), anl.verdi.gui.FormulaListElement.FormulaListElement(), anl.verdi.gui.AbstractListElement.getLayerMax(), and anl.verdi.gui.AbstractListElement.setLayerMax().
int anl.verdi.gui.AbstractListElement.layerMin protected
Definition at line 20 of file AbstractListElement.java.
Referenced by anl.verdi.gui.DatasetListElement.DatasetListElement(), anl.verdi.gui.FormulaListElement.FormulaListElement(), anl.verdi.gui.AbstractListElement.getLayerMin(), and anl.verdi.gui.AbstractListElement.setLayerMin().
int anl.verdi.gui.AbstractListElement.NO_LAYER_VALUE = -1 static
Definition at line 16 of file AbstractListElement.java.
Referenced by anl.verdi.gui.DatasetListElement.DatasetListElement(), anl.verdi.gui.FormulaListElement.FormulaListElement(), anl.verdi.gui.FormulasPanel.setLayerValues(), and anl.verdi.gui.DataSetPanel.setLayerValues().
int anl.verdi.gui.AbstractListElement.NO_TIME_VALUE = -1 static
Definition at line 15 of file AbstractListElement.java.
Referenced by anl.verdi.gui.DatasetListElement.DatasetListElement(), and anl.verdi.gui.FormulaListElement.FormulaListElement().
int anl.verdi.gui.AbstractListElement.timeMax protected
Definition at line 19 of file AbstractListElement.java.
Referenced by anl.verdi.gui.DatasetListElement.DatasetListElement(), anl.verdi.gui.FormulaListElement.FormulaListElement(), anl.verdi.gui.AbstractListElement.getTimeMax(), and anl.verdi.gui.AbstractListElement.setTimeMax().
int anl.verdi.gui.AbstractListElement.timeMin protected
Definition at line 18 of file AbstractListElement.java.
Referenced by anl.verdi.gui.DatasetListElement.DatasetListElement(), anl.verdi.gui.FormulaListElement.FormulaListElement(), anl.verdi.gui.AbstractListElement.getTimeMin(), and anl.verdi.gui.AbstractListElement.setTimeMin().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/gui/AbstractListElement.java