VERDI: anl.verdi.plot.gui.ChartTitlesPanel Class Reference
anl.verdi.plot.gui.ChartTitlesPanel Class Reference
Public Member Functions
ChartTitlesPanel ()
void initTitle (boolean use, String title, Font font, Color color)
void initSubTitle1 (boolean use, String title, Font font, Color color)
void initSubTitle2 (boolean use, String title, Font font, Color color)
PlotConfiguration fillConfiguration (PlotConfiguration config)
Static Public Member Functions
static void main (String[] args)
Detailed Description
Author
User #2
Definition at line 27 of file ChartTitlesPanel.java.
Constructor & Destructor Documentation
anl.verdi.plot.gui.ChartTitlesPanel.ChartTitlesPanel ()
Definition at line 32 of file ChartTitlesPanel.java.
Referenced by anl.verdi.plot.gui.ChartTitlesPanel.main().
Member Function Documentation
PlotConfiguration anl.verdi.plot.gui.ChartTitlesPanel.fillConfiguration (PlotConfiguration config)
Definition at line 50 of file ChartTitlesPanel.java.
References anl.verdi.plot.gui.ChartTitlePanel.getTitle(), anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_1_FONT, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_COLOR, anl.verdi.plot.config.PlotConfiguration.SUBTITLE_2_FONT, anl.verdi.plot.config.PlotConfiguration.TITLE_COLOR, anl.verdi.plot.config.PlotConfiguration.TITLE_FONT, and anl.verdi.plot.gui.ChartTitlePanel.useTitle().
void anl.verdi.plot.gui.ChartTitlesPanel.initSubTitle1 (boolean use, String title, Font font, Color color)
Definition at line 42 of file ChartTitlesPanel.java.
void anl.verdi.plot.gui.ChartTitlesPanel.initSubTitle2 (boolean use, String title, Font font, Color color)
Definition at line 46 of file ChartTitlesPanel.java.
void anl.verdi.plot.gui.ChartTitlesPanel.initTitle (boolean use, String title, Font font, Color color)
Definition at line 38 of file ChartTitlesPanel.java.
static void anl.verdi.plot.gui.ChartTitlesPanel.main (String[] args) static
Definition at line 85 of file ChartTitlesPanel.java.
References anl.verdi.plot.gui.ChartTitlesPanel.ChartTitlesPanel().
The documentation for this class was generated from the following file:
verdi_core/src/anl/verdi/plot/gui/ChartTitlesPanel.java