VERDI: saf.core.ui.dock.DockableFrame Interface Reference
saf.core.ui.dock.DockableFrame Interface Reference
Public Member Functions
void putClientProperty (Object key, Object value)
Object getClientProperty (Object key)
JToolBar getToolBar ()
void addToolBar (JToolBar bar)
JPanel getContentPane ()
boolean isMinimized ()
boolean isHidden ()
boolean isMaximized ()
boolean isFloating ()
String getID ()
String getTitle ()
void setTitle (String title)
void toFront ()
void restore ()
void minimize (DockingManager.MinimizeLocation location)
void maximize ()
void doFloat ()
void close ()
void close (String perspectiveID)
Detailed Description
Interface for classes that implement a dockable frame.
Definition at line 8 of file DockableFrame.java.
Member Function Documentation
void saf.core.ui.dock.DockableFrame.addToolBar (JToolBar bar)
Adds a toolbar to this frame.
Parameters
bar the toolbar to add
Implemented in saf.core.ui.dock.DefaultDockableFrame.
void saf.core.ui.dock.DockableFrame.close ()
Close this dockable. Assumes the dockable is in the current perspective.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
void saf.core.ui.dock.DockableFrame.close (String perspectiveID)
Closes this dockable in the specified perspective.
Parameters
perspectiveID the id of the perspective to close the dockable in.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
void saf.core.ui.dock.DockableFrame.doFloat ()
Floats this DockableFrame.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
Object saf.core.ui.dock.DockableFrame.getClientProperty (Object key)
Returns the value of the property with the specified key. Only properties added with putClientProperty will return a non-null value.
Parameters
key the property key whose value should be returned.
Returns
the value of the property with the specified key.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
JPanel saf.core.ui.dock.DockableFrame.getContentPane ()
Gets the panel that contains the component displayed in this frame. By default this component can be retrieved by calling getComponent(0) on the returned panel.
Note that this panel should not contain the toolbar.
Returns
the panel that contains the component displayed in this frame.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
String saf.core.ui.dock.DockableFrame.getID ()
Gets the unique id for this DockableFrame.
Returns
the unique id for this DockableFrame.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
Referenced by anl.verdi.core.VerdiGUI.addPlot(), anl.verdi.core.VerdiGUI.dockableClosed(), and saf.core.ui.event.DockableSelectionSupport.focusGained().
String saf.core.ui.dock.DockableFrame.getTitle ()
Gets the title text for this DockableFrame.
Returns
the title text for this DockableFrame.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
Referenced by saf.core.ui.actions.WindowMenuAction.WindowMenuAction().
JToolBar saf.core.ui.dock.DockableFrame.getToolBar ()
Gets the toolbar, if any, for this frame.
Returns
the toolbar for this frame if one exists, otherwise null.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
boolean saf.core.ui.dock.DockableFrame.isFloating ()
Gets whether or not this DockableFrame is floating.
Returns
true if this DockableFrame is floating, otherwise false.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
boolean saf.core.ui.dock.DockableFrame.isHidden ()
Gets whether or not this DockableFrame is hidden - possibly by another tab. Change made 2016 by MPAS team
Returns
true if this DockableFrame is hidden, otherwise false.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
Referenced by anl.verdi.core.VerdiGUI.isHidden().
boolean saf.core.ui.dock.DockableFrame.isMaximized ()
Gets whether or not this DockableFrame is maximized.
Returns
true if this DockableFrame is maximized, otherwise false.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
boolean saf.core.ui.dock.DockableFrame.isMinimized ()
Gets whether or not this DockableFrame is minimized.
Returns
true if this DockableFrame is minimized, otherwise false.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
Referenced by saf.core.ui.actions.WindowMenuAction.actionPerformed().
void saf.core.ui.dock.DockableFrame.maximize ()
Maximizes this DockableFrame.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
void saf.core.ui.dock.DockableFrame.minimize (DockingManager.MinimizeLocation location)
Minimizes this DockableFrame.
Parameters
location the location to minimize to
Implemented in saf.core.ui.dock.DefaultDockableFrame.
void saf.core.ui.dock.DockableFrame.putClientProperty (Object key, Object value)
Adds an arbitrary key/value "client property" to this component.
Parameters
key the new client property key
value the new client property value; if this is null the property will be removed
Implemented in saf.core.ui.dock.DefaultDockableFrame.
void saf.core.ui.dock.DockableFrame.restore ()
Restores this DockableFrame.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
Referenced by saf.core.ui.actions.WindowMenuAction.actionPerformed().
void saf.core.ui.dock.DockableFrame.setTitle (String title)
Sets the title text for this DockableFrame.
Parameters
title the title text for this DockableFrame.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
void saf.core.ui.dock.DockableFrame.toFront ()
Selects this DockableFrame.
Implemented in saf.core.ui.dock.DefaultDockableFrame.
The documentation for this interface was generated from the following file:
verdi_saf_ui/src/saf/core/ui/dock/DockableFrame.java