VERDI: anl.verdi.data.DataFrame Interface Reference
anl.verdi.data.DataFrame Interface Reference
Public Member Functions
Array getArray ()
Axes< DataFrameAxis > getAxes ()
List< Dataset > getDataset ()
Variable getVariable ()
Class getArrayType ()
long getSize ()
int[] getShape ()
DataFrameIndex getIndex ()
double getDouble (DataFrameIndex index)
float getFloat (DataFrameIndex index)
int getInt (DataFrameIndex index)
long getLong (DataFrameIndex index)
DataFrame slice (Slice slice) throws InvalidRangeException
DataFrame sliceCopy (Slice slice) throws InvalidRangeException
Detailed Description
Array-based data and metadata for a single variable.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 14 of file DataFrame.java.
Member Function Documentation
Array anl.verdi.data.DataFrame.getArray ()
Gets the Array that contains the data.
Returns
the Array that contains the result data.
Implemented in anl.verdi.data.AbstractDataFrame.
Referenced by anl.verdi.data.DataUtilities.minMax(), anl.verdi.parser.ASTVar.preprocess(), and anl.verdi.data.DataUtilities.unitVectorTransform().
Class anl.verdi.data.DataFrame.getArrayType ()
Gets the element type contained by the data array.
Returns
the element type contained by the data array.
Implemented in anl.verdi.data.AbstractDataFrame.
Axes<DataFrameAxis> anl.verdi.data.DataFrame.getAxes ()
Gets metadata describing this data frame's axes.
Returns
metadata describing this data frame's axes.
Implemented in anl.verdi.data.AbstractDataFrame.
Referenced by anl.verdi.plot.types.TilePlot.addObsAnnotation(), anl.verdi.plot.types.TilePlot.addVectorAnnotation(), anl.verdi.plot.types.Contour3D.Contour3D(), anl.verdi.plot.types.AbstractTilePlot.createMapAnnotation(), anl.verdi.plot.types.TilePlot.createSubtitle(), anl.verdi.plot.types.VerticalCrossSectionPlot.createSubtitle(), anl.verdi.plot.types.TilePlot.getToolBar(), anl.verdi.plot.types.LinePlot.getToolBar(), anl.verdi.plot.types.TimeSeriesBarPlot.getToolBar(), anl.verdi.plot.types.ScatterPlot.getToolBar(), anl.verdi.plot.types.VerticalCrossSectionPlot.getToolBar(), anl.verdi.plot.types.Contour3D.getToolBar(), anl.verdi.plot.probe.TimeSeriesProbeCreator.TimeSeriesProbeCreator(), anl.verdi.data.TimeStepAverager.transform(), and anl.verdi.plot.types.Contour3D.updateTimeStepLayer().
List<Dataset> anl.verdi.data.DataFrame.getDataset ()
Gets the dataset that produced this DataFrame.
Returns
the dataset that produced this DataFrame.
Implemented in anl.verdi.data.AbstractDataFrame.
Referenced by anl.verdi.plot.types.AbstractTilePlot.createLayer(), and anl.verdi.plot.types.AbstractTilePlot.createMapAnnotation().
double anl.verdi.data.DataFrame.getDouble (DataFrameIndex index)
Gets the item at the specified indices as a double. The appropriate order of the indices can be gotten via the Axes information
Parameters
index the index of the data to retrieve.
Returns
the item at the specified indices as a double.
Implemented in anl.verdi.data.AbstractDataFrame.
Referenced by anl.verdi.data.TLDataFrameTableModel.getValueAt(), anl.verdi.data.XYDataFrameTableModel.getValueAt(), and anl.verdi.data.XYLDataFrameTableModel.getValueAt().
float anl.verdi.data.DataFrame.getFloat (DataFrameIndex index)
Gets the item at the specified indices as a float. The appropriate order of the indices can be gotten via the Axes information
Parameters
index the index of the data to retrieve.
Returns
the item at the specified indices as a float.
Implemented in anl.verdi.data.AbstractDataFrame.
DataFrameIndex anl.verdi.data.DataFrame.getIndex ()
Gets a DataFrameIndex used to retrieve data from this DataFrame.
Returns
a DataFrameIndex used to retrieve data from this DataFrame.
Implemented in anl.verdi.data.AbstractDataFrame.
int anl.verdi.data.DataFrame.getInt (DataFrameIndex index)
Gets the item at the specified indices as an int. The appropriate order of the indices can be gotten via the Axes information
Parameters
index the index of the data to retrieve.
Returns
the item at the specified indices as an int.
Implemented in anl.verdi.data.AbstractDataFrame.
long anl.verdi.data.DataFrame.getLong (DataFrameIndex index)
Gets the item at the specified indices as a long. The appropriate order of the indices can be gotten via the Axes information
Parameters
index the index of the data to retrieve.
Returns
the item at the specified indices as a long.
Implemented in anl.verdi.data.AbstractDataFrame.
int [] anl.verdi.data.DataFrame.getShape ()
Gets the shape - the array dimensionality - of this DataFrame.
Returns
the shape - the array dimensionality - of this DataFrame.
Implemented in anl.verdi.data.AbstractDataFrame.
long anl.verdi.data.DataFrame.getSize ()
Gets the total number of items in the data array.
Returns
the total number of items in the data array.
Implemented in anl.verdi.data.AbstractDataFrame.
Variable anl.verdi.data.DataFrame.getVariable ()
Gets the variable associated with this DataFrame.
Returns
the variable associated with this DataFrame.
Implemented in anl.verdi.data.AbstractDataFrame.
Referenced by anl.verdi.plot.data.DataFrameXYZDataset.addSeries().
DataFrame anl.verdi.data.DataFrame.slice (Slice slice) throws InvalidRangeException
Creates a new DataFrame that is a slice or subsection of this one. The two DataFrames will share data, so any change to one will be reflected in the other. The slice ranges should be in terms of the array indices of the data frame which are NOT necessarily the axes origins and extents.
Parameters
slice describes the slice of data contained by the new DataFrame.
Returns
a new DataFrame that is a slice or subsection of this one
Exceptions
InvalidRangeException if the slice is not within the range of this DataFrame's dimensions.
Implemented in anl.verdi.data.AbstractDataFrame.
DataFrame anl.verdi.data.DataFrame.sliceCopy (Slice slice) throws InvalidRangeException
Creates a new DataFrame that is a slice or subsection of this one. The two DataFrames will NOT share data, so any change to one will NOT be reflected in the other. The slice ranges should be in terms of the array indices of the data frame which are NOT necessarily the axes origins and extents.
Parameters
slice describes the slice of data contained by the new DataFrame.
Returns
a new DataFrame that is a slice or subsection of this one
Exceptions
InvalidRangeException if the slice is not within the range of this DataFrame's dimensions.
Implemented in anl.verdi.data.AbstractDataFrame.
The documentation for this interface was generated from the following file:
verdi_core/src/anl/verdi/data/DataFrame.java