VERDI: saf.core.ui.dock.DockingManager Interface Reference
saf.core.ui.dock.DockingManager Interface Reference
Classes
enum MinimizeLocation
Public Member Functions
GUIBarManager getBarManager ()
void dock (DockableFrame dockable, DockableFrame target)
void dock (DockableFrame dockable, DockableFrame relativeTo, Location location, float fillPercent)
void addDockableToGroup (String perspectiveID, String groupID, DockableFrame dockable)
Set< String > getGroupIDs (String perspectiveID)
List< DockableFrame > getDockableFrames (String perspectiveID, String groupID)
DockableFrame createDockable (String id, JComponent comp)
DockableFrame createDockable (String id, JComponent comp, MinimizeLocation hideLocation)
DockableFrame createDockable (String id, JComponent comp, MinimizeLocation location, int dockableControls)
void init ()
void setPerspective (String perspectiveID)
List< String > getPerspectiveIDs ()
Perspective getPerspective (String id)
Perspective getPerspective ()
DockableFrame getDockable (String id)
void addDockableListener (DockableFrameListener listener)
void removeDockableListener (DockableFrameListener listener)
void addDockableSelectionListener (DockableSelectionListener listener)
void removeDockableSelectionListener (DockableSelectionListener listener)
void addPerspectiveSelectionListener (PerspectiveSelectionListener listener)
void removePerspectiveSelectionListener (PerspectiveSelectionListener listener)
Public Attributes
int CLOSE = 1
int MINIMIZE = 2
int MAXIMIZE = 4
int FLOAT = 8
Detailed Description
Interface for classes that manage dockable frames.
Definition at line 16 of file DockingManager.java.
Member Function Documentation
void saf.core.ui.dock.DockingManager.addDockableListener (DockableFrameListener listener)
Adds a dockable listener to this DockingManager to listen for dockable events.
Parameters
listener the listener to add.
Implemented in saf.core.ui.dock.DefaultDockingManager.
void saf.core.ui.dock.DockingManager.addDockableSelectionListener (DockableSelectionListener listener)
Adds a dockable selection listener to this DockingManager to listen for dockable selection events.
Parameters
listener the listener to add.
Implemented in saf.core.ui.dock.DefaultDockingManager.
void saf.core.ui.dock.DockingManager.addDockableToGroup (String perspectiveID, String groupID, DockableFrame dockable)
Adds the specified dockable to the specified group in the specified perspective.
Parameters
perspectiveID the id of the perspective to add the dockable to
groupID the id of the group to add the dockable to
dockable the dockable to add
Implemented in saf.core.ui.dock.DefaultDockingManager.
void saf.core.ui.dock.DockingManager.addPerspectiveSelectionListener (PerspectiveSelectionListener listener)
Adds a perspective selection listener to this DockingManager to listen for perspective selection events.
Parameters
listener the listener to add.
Implemented in saf.core.ui.dock.DefaultDockingManager.
DockableFrame saf.core.ui.dock.DockingManager.createDockable (String id, JComponent comp)
Creates a Dockable with the specified id containing the specified component. This only creates the dockable. To add a created dockable into a window use the addDockableToGroup method.
Parameters
id the id that uniquely identifies the created Dockable
comp the component displayed by the dockable
Returns
the created dockable
See Also
addDockableToGroup
Implemented in saf.core.ui.dock.DefaultDockingManager.
DockableFrame saf.core.ui.dock.DockingManager.createDockable (String id, JComponent comp, MinimizeLocation hideLocation)
Creates a dockable with the specified id, hide location and containing the specified component. This only creates the dockable. To add a created dockable into a window use the addDockableToGroup method.
Parameters
id the id that uniquely identifies the created Dockable
comp the component displayed by the dockable
hideLocation the location where the dockable is minimized to
Returns
the created dockable
Implemented in saf.core.ui.dock.DefaultDockingManager.
DockableFrame saf.core.ui.dock.DockingManager.createDockable (String id, JComponent comp, MinimizeLocation location, int dockableControls)
Creates a dockable with the specified id, hide location, window controls and containing the specified component. This only creates the dockable. To add a created dockable into a window use the addDockableToGroup method.
The dockable controls are:
DockingManager.CLOSE
DockingManager.HIDE
DockingManager.MAXIMIZE
DockingManager.FLOAT
These can be logically or'ed together.
Parameters
id the id that uniquely identifies the created Dockable
comp the component displayed by the dockable
location the location where the dockable is minimized to
dockableControls specifies what controls (close, maximize, float etc.) are displayed on the dockable's title bar
Returns
the created dockable
Implemented in saf.core.ui.dock.DefaultDockingManager.
void saf.core.ui.dock.DockingManager.dock (DockableFrame dockable, DockableFrame target)
Attempts to dock the specified dockable to the target, stacking the dockable on top of the target. This will do nothing if the target is minimized or the dockable has not been added to a group.
Parameters
dockable the dockable to dock
target the target to dock to
Implemented in saf.core.ui.dock.DefaultDockingManager.
void saf.core.ui.dock.DockingManager.dock (DockableFrame dockable, DockableFrame relativeTo, Location location, float fillPercent)
Attempts to dock the specified dockable in some location relative to another dockable. This will not work if relativeTo is minimized or maximized, or if the dockable hasn't been added to a group yet.
Parameters
dockable the dockable to dock
relativeTo the dockable to dock relative to
location the relative location
fillPercent the fill percent that the dockable should take up
Implemented in saf.core.ui.dock.DefaultDockingManager.
GUIBarManager saf.core.ui.dock.DockingManager.getBarManager ()
Gets the bar manager that manages the tool, menu and status bars.
Returns
the bar manager that manages the tool, menu and status bars.
Implemented in saf.core.ui.dock.DefaultDockingManager.
Referenced by anl.verdi.core.VerdiGUI.setCurrentFormula().
DockableFrame saf.core.ui.dock.DockingManager.getDockable (String id)
Gets the specified dockable by its id.
Parameters
id the id of the dockable to get
Returns
the specified dockable by its id.
Implemented in saf.core.ui.dock.DefaultDockingManager.
List<DockableFrame> saf.core.ui.dock.DockingManager.getDockableFrames (String perspectiveID, String groupID)
Gets all the dockables in the specified group in the specified perspective.
Parameters
perspectiveID the id of the perspective
groupID the id the group
Returns
all the dockables in the specified group in the specified perspective.
Implemented in saf.core.ui.dock.DefaultDockingManager.
Set<String> saf.core.ui.dock.DockingManager.getGroupIDs (String perspectiveID)
Gets the group ids of the groups in the specified perspective.
Parameters
perspectiveID the perspective whose groups are of interest
Returns
group ids of the groups in the specified perspective
Implemented in saf.core.ui.dock.DefaultDockingManager.
Perspective saf.core.ui.dock.DockingManager.getPerspective (String id)
Gets the specified perspective.
Parameters
id the id of the perspective to get
Returns
the specified perspective.
Implemented in saf.core.ui.dock.DefaultDockingManager.
Referenced by saf.core.ui.GUIBarManager.createPerspectiveMenu().
Perspective saf.core.ui.dock.DockingManager.getPerspective ()
Gets the current perspective.
Returns
the current perspective
Implemented in saf.core.ui.dock.DefaultDockingManager.
List<String> saf.core.ui.dock.DockingManager.getPerspectiveIDs ()
Gets a list of all the perspective ids.
Returns
a list of all the perspective ids.
Implemented in saf.core.ui.dock.DefaultDockingManager.
Referenced by saf.core.ui.GUIBarManager.createPerspectiveMenu().
void saf.core.ui.dock.DockingManager.init ()
Initializes the docking manger by activitating the current perpspective.
Implemented in saf.core.ui.dock.DefaultDockingManager.
void saf.core.ui.dock.DockingManager.removeDockableListener (DockableFrameListener listener)
Removes the specified dockable listener.
Parameters
listener the listener to remove
Implemented in saf.core.ui.dock.DefaultDockingManager.
void saf.core.ui.dock.DockingManager.removeDockableSelectionListener (DockableSelectionListener listener)
Removes the specified dockable selection listener.
Parameters
listener the listener to remove
Implemented in saf.core.ui.dock.DefaultDockingManager.
void saf.core.ui.dock.DockingManager.removePerspectiveSelectionListener (PerspectiveSelectionListener listener)
Removes the specified perspective selection listener.
Parameters
listener the listener to remove
Implemented in saf.core.ui.dock.DefaultDockingManager.
void saf.core.ui.dock.DockingManager.setPerspective (String perspectiveID)
Sets the specified perspective as the currently active perspective.
Parameters
perspectiveID the id of the perspective to set
Implemented in saf.core.ui.dock.DefaultDockingManager.
Member Data Documentation
int saf.core.ui.dock.DockingManager.CLOSE = 1
Definition at line 23 of file DockingManager.java.
Referenced by saf.core.ui.dock.DefaultDockingManager.createDockable().
int saf.core.ui.dock.DockingManager.FLOAT = 8
Definition at line 26 of file DockingManager.java.
Referenced by saf.core.ui.dock.DefaultDockingManager.createDockable().
int saf.core.ui.dock.DockingManager.MAXIMIZE = 4
Definition at line 25 of file DockingManager.java.
Referenced by saf.core.ui.dock.DefaultDockingManager.createDockable().
int saf.core.ui.dock.DockingManager.MINIMIZE = 2
Definition at line 24 of file DockingManager.java.
Referenced by saf.core.ui.dock.DefaultDockingManager.createDockable().
The documentation for this interface was generated from the following file:
verdi_saf_ui/src/saf/core/ui/dock/DockingManager.java