VERDI: anl.verdi.plot.gui.Plot Interface Reference
anl.verdi.plot.gui.Plot Interface Reference
Classes
enum ConfigSource
Public Member Functions
JPanel getPanel ()
JMapPane getMapPane ()
JMenuBar getMenuBar ()
JToolBar getToolBar ()
void addPlotListener (PlotListener listener)
void removePlotListener (PlotListener listener)
Formula.Type getType ()
List< DataFrame > getData ()
void exportImage (String format, File file, int width, int height) throws IOException
void configure (PlotConfiguration config)
void configure (PlotConfiguration config, ConfigSource source)
PlotConfiguration getPlotConfiguration ()
BufferedImage getBufferedImage ()
BufferedImage getBufferedImage (int width, int height)
String getTitle ()
void viewClosed ()
Detailed Description
Interface for Plot classes.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 24 of file Plot.java.
Member Function Documentation
void anl.verdi.plot.gui.Plot.addPlotListener (PlotListener listener)
Adds the specified PlotListener.
Parameters
listener the plot listener to add
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.AbstractTilePlot, anl.verdi.plot.types.Contour3D, anl.verdi.plot.types.TimeSeriesBarPlot, anl.verdi.plot.types.LinePlot, and anl.verdi.plot.types.ScatterPlot.
void anl.verdi.plot.gui.Plot.configure (PlotConfiguration config)
Configure this Plot according to the specified PlotConfiguration.
Parameters
config the new plot configuration
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.Contour3D, anl.verdi.plot.types.LinePlot, anl.verdi.plot.types.TimeSeriesBarPlot, anl.verdi.plot.types.ScatterPlot, anl.verdi.plot.types.AbstractTilePlot, anl.verdi.plot.gui.FastAreaTilePlot, and anl.verdi.plot.types.AbstractPlot.
void anl.verdi.plot.gui.Plot.configure (PlotConfiguration config, ConfigSource source)
void anl.verdi.plot.gui.Plot.exportImage (String format, File file, int width, int height) throws IOException
Exports an image of this Plot to the specified file in the specified format.
Parameters
format the image format. One of PlotExporter.JPG, PlotExporter.TIF, PlotExporter.PNG, or PlotExporter.BMP
file the file to save the image to.
width width of image in pixels
height height of image in pixels
Exceptions
IOException if there is an error creating the image
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.Contour3D, and anl.verdi.plot.types.AbstractPlot.
BufferedImage anl.verdi.plot.gui.Plot.getBufferedImage ()
Gets a BufferedImage of the plot.
Returns
a BufferedImage of the plot.
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.AbstractTilePlot, anl.verdi.plot.types.Contour3D, and anl.verdi.plot.types.AbstractPlot.
BufferedImage anl.verdi.plot.gui.Plot.getBufferedImage (int width, int height)
Gets a BufferedImage of the plot.
Parameters
width the width of the image in pixels
height the height of the image in pixels
Returns
a BufferedImage of the plot.
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.AbstractTilePlot, anl.verdi.plot.types.Contour3D, and anl.verdi.plot.types.AbstractPlot.
List<DataFrame> anl.verdi.plot.gui.Plot.getData ()
Gets the data that this Plot plots.
Returns
the data that this Plot plots.
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.Contour3D, anl.verdi.plot.types.AbstractTilePlot, anl.verdi.plot.types.ScatterPlot, anl.verdi.plot.types.TimeSeriesBarPlot, and anl.verdi.plot.types.LinePlot.
Referenced by anl.verdi.plot.anim.MultiPlotAnimation.init().
JMapPane anl.verdi.plot.gui.Plot.getMapPane ()
Gets the JMapPane that contains the mapping portion of the plot component.
Returns
the mapping panel that contains the mapping portion of the plot component.
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.Contour3D, anl.verdi.plot.types.ScatterPlot, anl.verdi.plot.types.VerticalCrossSectionPlot, anl.verdi.plot.types.TimeSeriesBarPlot, anl.verdi.plot.types.LinePlot, and anl.verdi.plot.types.TilePlot.
JMenuBar anl.verdi.plot.gui.Plot.getMenuBar ()
Gets a menu bar for this Plot. This may return null if there is no menu bar.
Returns
a menu bar for this Plot.
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.AbstractTilePlot, anl.verdi.plot.types.Contour3D, anl.verdi.plot.gui.FastAreaTilePlot, anl.verdi.plot.types.TimeSeriesBarPlot, anl.verdi.plot.types.ScatterPlot, and anl.verdi.plot.types.LinePlot.
JPanel anl.verdi.plot.gui.Plot.getPanel ()
Gets the entire panel that contains the plot component.
Returns
the entire panel that contains the plot component.
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.Contour3D, anl.verdi.plot.types.AbstractTilePlot, anl.verdi.plot.types.LinePlot, anl.verdi.plot.types.TimeSeriesBarPlot, and anl.verdi.plot.types.ScatterPlot.
Referenced by anl.verdi.plot.gui.PlotPanel.PlotPanel().
PlotConfiguration anl.verdi.plot.gui.Plot.getPlotConfiguration ()
Gets this Plot's configuration data.
Returns
this Plot's configuration data.
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.AbstractTilePlot, anl.verdi.plot.types.Contour3D, anl.verdi.plot.types.TimeSeriesBarPlot, anl.verdi.plot.types.LinePlot, anl.verdi.plot.types.ScatterPlot, and anl.verdi.plot.types.AbstractPlot.
Referenced by anl.verdi.plot.gui.ConfigDialog.init().
String anl.verdi.plot.gui.Plot.getTitle ()
Gets this plot's current title.
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.Contour3D, anl.verdi.plot.types.ScatterPlot, anl.verdi.plot.types.VerticalCrossSectionPlot, anl.verdi.plot.types.TimeSeriesBarPlot, anl.verdi.plot.types.LinePlot, and anl.verdi.plot.types.TilePlot.
JToolBar anl.verdi.plot.gui.Plot.getToolBar ()
Gets a tool bar for this plot. This may return null if there is no tool bar.
Returns
a tool bar for this plot.
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.Contour3D, anl.verdi.plot.types.VerticalCrossSectionPlot, anl.verdi.plot.types.ScatterPlot, anl.verdi.plot.types.TimeSeriesBarPlot, anl.verdi.plot.types.LinePlot, and anl.verdi.plot.types.TilePlot.
Formula.Type anl.verdi.plot.gui.Plot.getType ()
Gets the type of the Plot.
Returns
the type of the Plot.
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.Contour3D, anl.verdi.plot.types.VerticalCrossSectionPlot, anl.verdi.plot.types.LinePlot, anl.verdi.plot.types.TimeSeriesBarPlot, anl.verdi.plot.types.TilePlot, and anl.verdi.plot.types.ScatterPlot.
Referenced by anl.verdi.core.VerdiGUI.getDisplayedPlots(), and anl.verdi.util.Save2Ascii.Save2Ascii().
void anl.verdi.plot.gui.Plot.removePlotListener (PlotListener listener)
Removes the specified PlotListener.
Parameters
listener the plot listener to remove
Implemented in anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.AbstractTilePlot, anl.verdi.plot.types.Contour3D, anl.verdi.plot.types.TimeSeriesBarPlot, anl.verdi.plot.types.LinePlot, and anl.verdi.plot.types.ScatterPlot.
void anl.verdi.plot.gui.Plot.viewClosed ()
Implemented in anl.verdi.plot.types.Contour3D, anl.verdi.plot.gui.FastTilePlot, anl.verdi.plot.types.AbstractTilePlot, anl.verdi.plot.types.ScatterPlot, anl.verdi.plot.types.LinePlot, and anl.verdi.plot.types.TimeSeriesBarPlot.
The documentation for this interface was generated from the following file:
verdi_core/src/anl/verdi/plot/gui/Plot.java