VERDI: anl.verdi.data.Dataset Interface Reference
anl.verdi.data.Dataset Interface Reference
Public Member Functions
void setAlias (String alias)
String getAlias ()
List< String > getVariableNames ()
List< Variable > getVariables ()
Variable getVariable (String name)
Axes< CoordAxis > getCoordAxes ()
boolean hasTimeAxis ()
boolean hasZAxis ()
boolean hasXAxis ()
boolean hasYAxis ()
URL getURL ()
int getIndexInURL ()
String getName ()
void close () throws IOException
boolean isObs ()
DatasetMetadata getMetadata ()
int getNetcdfCovn ()
void setNetcdfConv (int conv)
Static Public Attributes
static final String NULL_ALIAS = "anl.verdi.data.DataSet.NULL_ALIAS"
static final int SINGLE_DATASET = -1
Detailed Description
Encapsulates a set of data. Each Dataset can have an alias to help with identifying its variables from those of other datasets.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 17 of file Dataset.java.
Member Function Documentation
void anl.verdi.data.Dataset.close () throws IOException
Closes this dataset. It will have to be recreated to be used again.
Exceptions
IOException if an error occurs while closing the dataset
Implemented in anl.verdi.loaders.GridNetcdfDataset, anl.verdi.loaders.SpreadsheetDataset, anl.verdi.loaders.AbstractNetcdfDataset, anl.verdi.loaders.Models3ObsDataset, and anl.verdi.data.AbstractDataset.
String anl.verdi.data.Dataset.getAlias ()
Gets the alias of this Dataset. If no alias has been assigned the alias will be NULL_ALIAS.
Returns
the alias of this Dataset.
Implemented in anl.verdi.loaders.SpreadsheetDataset, and anl.verdi.data.AbstractDataset.
Referenced by anl.verdi.plot.gui.ObsAnnotation.getVarString(), and anl.verdi.data.DefaultVariable.toString().
Axes<CoordAxis> anl.verdi.data.Dataset.getCoordAxes ()
Gets the coordindate Axes for this Dataset.
Returns
the coordindate Axes for this Dataset.
Implemented in anl.verdi.loaders.CSVDataset, anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.GridNetcdfDataset, anl.verdi.loaders.AbstractNetcdfDataset, anl.verdi.loaders.SpreadsheetDataset, and anl.verdi.data.AbstractDataset.
Referenced by anl.verdi.data.ObsEvaluator.evaluate().
int anl.verdi.data.Dataset.getIndexInURL ()
Gets the index of this Dataset inside its URL, or Dataset.SINGLE_DATASET if it is the only dataset inside the URL.
Returns
the index of this Dataset inside its URL
Implemented in anl.verdi.loaders.CSVDataset, anl.verdi.loaders.GridNetcdfDataset, anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.SpreadsheetDataset, and anl.verdi.loaders.AbstractNetcdfDataset.
DatasetMetadata anl.verdi.data.Dataset.getMetadata ()
Return a dataset meta data including projection information
Returns
a dataset meta data including projection information.
Implemented in anl.verdi.loaders.CSVDataset, anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.GridNetcdfDataset, anl.verdi.loaders.SpreadsheetDataset, anl.verdi.loaders.Models3Dataset, and anl.verdi.loaders.WRFDataset.
String anl.verdi.data.Dataset.getName ()
Gets the name of this Dataset.
Returns
the name of this Dataset.
Implemented in anl.verdi.loaders.CSVDataset, anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.GridNetcdfDataset, anl.verdi.loaders.SpreadsheetDataset, and anl.verdi.data.AbstractDataset.
int anl.verdi.data.Dataset.getNetcdfCovn ()
Implemented in anl.verdi.loaders.CSVDataset, anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.SpreadsheetDataset, anl.verdi.loaders.GridNetcdfDataset, anl.verdi.loaders.Models3Dataset, and anl.verdi.loaders.WRFDataset.
URL anl.verdi.data.Dataset.getURL ()
Gets the url of this Dataset.
Returns
the url of this Dataset.
Implemented in anl.verdi.loaders.SpreadsheetDataset, and anl.verdi.data.AbstractDataset.
Variable anl.verdi.data.Dataset.getVariable (String name)
Gets the named variable.
Parameters
name the name of the variable to get
Returns
the named variable
Implemented in anl.verdi.loaders.CSVDataset, anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.GridNetcdfDataset, anl.verdi.loaders.AbstractNetcdfDataset, and anl.verdi.data.AbstractDataset.
List<String> anl.verdi.data.Dataset.getVariableNames ()
Gets the list of variable names in this Dataset.
Returns
the list of variable names in this Dataset.
Implemented in anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.CSVDataset, anl.verdi.loaders.GridNetcdfDataset, anl.verdi.loaders.AbstractNetcdfDataset, anl.verdi.loaders.SpreadsheetDataset, and anl.verdi.data.AbstractDataset.
List<Variable> anl.verdi.data.Dataset.getVariables ()
Gets the list of variables in this Dataset.
Returns
the list of variables in this Dataset.
Implemented in anl.verdi.loaders.CSVDataset, anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.GridNetcdfDataset, anl.verdi.loaders.AbstractNetcdfDataset, anl.verdi.loaders.SpreadsheetDataset, and anl.verdi.data.AbstractDataset.
boolean anl.verdi.data.Dataset.hasTimeAxis ()
Returns
true if there is a time axis, otherwise false
Implemented in anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.SpreadsheetDataset, and anl.verdi.data.AbstractDataset.
boolean anl.verdi.data.Dataset.hasXAxis ()
Returns
true if there is a X axis, otherwise false
Implemented in anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.SpreadsheetDataset, and anl.verdi.data.AbstractDataset.
boolean anl.verdi.data.Dataset.hasYAxis ()
Returns
true if there is a Y axis, otherwise false
Implemented in anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.SpreadsheetDataset, and anl.verdi.data.AbstractDataset.
boolean anl.verdi.data.Dataset.hasZAxis ()
See if there is a z (e.g. layer) axis
Returns
true if there is a Z axis, otherwise false
Implemented in anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.SpreadsheetDataset, and anl.verdi.data.AbstractDataset.
boolean anl.verdi.data.Dataset.isObs ()
Whether or not this dataset represents an observational dataset
Returns
true if this contains obs data, otherwise false.
Implemented in anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.SpreadsheetDataset, and anl.verdi.data.AbstractDataset.
Referenced by anl.verdi.gui.DatasetListElement.toString().
void anl.verdi.data.Dataset.setAlias (String alias)
Sets the alias for this Dataset.
Parameters
alias the alias for this Dataset.
Implemented in anl.verdi.loaders.CSVDataset, anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.GridNetcdfDataset, anl.verdi.loaders.SpreadsheetDataset, and anl.verdi.data.AbstractDataset.
void anl.verdi.data.Dataset.setNetcdfConv (int conv)
Implemented in anl.verdi.loaders.CSVDataset, anl.verdi.loaders.Models3ObsDataset, anl.verdi.loaders.SpreadsheetDataset, anl.verdi.loaders.GridNetcdfDataset, anl.verdi.loaders.Models3Dataset, and anl.verdi.loaders.WRFDataset.
Member Data Documentation
final String anl.verdi.data.Dataset.NULL_ALIAS = "anl.verdi.data.DataSet.NULL_ALIAS" static
Definition at line 19 of file Dataset.java.
final int anl.verdi.data.Dataset.SINGLE_DATASET = -1 static
Definition at line 20 of file Dataset.java.
Referenced by anl.verdi.loaders.CSVDataset.CSVDataset(), anl.verdi.loaders.SpreadsheetDataset.getIndexInURL(), anl.verdi.loaders.Models3ObsDataset.getIndexInURL(), anl.verdi.loaders.GridNetcdfDataset.GridNetcdfDataset(), anl.verdi.loaders.GridNetcdfDataset.setAlias(), and anl.verdi.loaders.CSVDataset.setAlias().
The documentation for this interface was generated from the following file:
verdi_core/src/anl/verdi/data/Dataset.java