VERDI: anl.verdi.data.ExtendCoordAxis Interface Reference
anl.verdi.data.ExtendCoordAxis Interface Reference
Public Member Functions
String getName ()
String getDescription ()
Range getRange ()
AxisType getAxisType ()
Object getValue (int index)
Unit getUnits ()
boolean isCompatible (ExtendCoordAxis axis)
Detailed Description
Interface for classes implementing Extended axis metadata: not only x,y,z,time.
Author
Jizhen (Jason) Zhao
Version
$Revision$ $Date$
Definition at line 15 of file ExtendCoordAxis.java.
Member Function Documentation
AxisType anl.verdi.data.ExtendCoordAxis.getAxisType ()
Gets the type of this axis.
Returns
the type of this axis.
Implemented in anl.verdi.data.ExtendAxisRange, anl.verdi.loaders.ExtendNetCdfCoordAxis, anl.verdi.loaders.ExtendSyntheticTimeAxis, and anl.verdi.loaders.ExtendCSVCoordAxis.
Referenced by anl.verdi.data.ExtendDataFrameAxis.createDataFrameAxis(), anl.verdi.loaders.ExtendCSVCoordAxis.isCompatible(), and anl.verdi.loaders.ExtendNetCdfCoordAxis.isCompatible().
String anl.verdi.data.ExtendCoordAxis.getDescription ()
Gets the description of this CoordAxis.
Returns
the description of this CoordAxis.
Implemented in anl.verdi.loaders.ExtendSyntheticTimeAxis, anl.verdi.loaders.ExtendNetCdfCoordAxis, anl.verdi.data.ExtendAxisRange, and anl.verdi.loaders.ExtendCSVCoordAxis.
String anl.verdi.data.ExtendCoordAxis.getName ()
Gets the name of this CoordAxis.
Returns
the name of this CoordAxis.
Implemented in anl.verdi.loaders.ExtendSyntheticTimeAxis, anl.verdi.loaders.ExtendNetCdfCoordAxis, anl.verdi.data.ExtendAxisRange, and anl.verdi.loaders.ExtendCSVCoordAxis.
Range anl.verdi.data.ExtendCoordAxis.getRange ()
Disable this option: some dim does not has a range Gets the range of this axis.
Returns
the range of this axis.
Implemented in anl.verdi.loaders.ExtendSyntheticTimeAxis, anl.verdi.loaders.ExtendNetCdfCoordAxis, anl.verdi.data.ExtendAxisRange, and anl.verdi.loaders.ExtendCSVCoordAxis.
Referenced by anl.verdi.data.ExtendAxisRange.ExtendAxisRange(), anl.verdi.data.ExtendDataFrameAxis.ExtendDataFrameAxis(), anl.verdi.loaders.ExtendCSVCoordAxis.isCompatible(), and anl.verdi.loaders.ExtendNetCdfCoordAxis.isCompatible().
Unit anl.verdi.data.ExtendCoordAxis.getUnits ()
Gets the unit of measurement for this coordinate axis.
Returns
the unit of measurement for this coordinate axis.
Implemented in anl.verdi.loaders.ExtendSyntheticTimeAxis, anl.verdi.loaders.ExtendNetCdfCoordAxis, anl.verdi.data.ExtendAxisRange, and anl.verdi.loaders.ExtendCSVCoordAxis.
Object anl.verdi.data.ExtendCoordAxis.getValue (int index)
Gets the value at the specified index.
Parameters
index the index
Returns
the value at the specified index.
Implemented in anl.verdi.loaders.ExtendSyntheticTimeAxis, anl.verdi.data.ExtendAxisRange, anl.verdi.loaders.ExtendNetCdfCoordAxis, and anl.verdi.loaders.ExtendCSVCoordAxis.
boolean anl.verdi.data.ExtendCoordAxis.isCompatible (ExtendCoordAxis axis)
Gets whether or not the this axis is compatible with the specified axis. Two axes are compatible if they can be used together in the same formula.
Parameters
axis the axis to check for compatibility
Returns
true if this axis is compatibilty with the other axis, otherise false.
Implemented in anl.verdi.loaders.ExtendSyntheticTimeAxis, anl.verdi.loaders.ExtendNetCdfCoordAxis, anl.verdi.data.ExtendAxisRange, and anl.verdi.loaders.ExtendCSVCoordAxis.
Referenced by anl.verdi.data.ExtendAxisRange.isCompatible().
The documentation for this interface was generated from the following file:
verdi_core/src/anl/verdi/data/ExtendCoordAxis.java