VERDI: anl.verdi.data.CoordAxis Interface Reference
anl.verdi.data.CoordAxis Interface Reference
Public Member Functions
String getName ()
String getDescription ()
Range getRange ()
AxisType getAxisType ()
double getValue (int index)
Unit getUnits ()
boolean isCompatible (CoordAxis axis)
Detailed Description
Interface for classes implementing axis metadata.
Author
Nick Collier
Version
$Revision$ $Date$
Definition at line 14 of file CoordAxis.java.
Member Function Documentation
AxisType anl.verdi.data.CoordAxis.getAxisType ()
Gets the type of this axis.
Returns
the type of this axis.
Implemented in anl.verdi.data.AxisRange, anl.verdi.loaders.SyntheticTimeAxis, anl.verdi.loaders.NetCdfCoordAxis, and anl.verdi.loaders.CSVCoordAxis.
Referenced by anl.verdi.data.DataFrameAxis.createDataFrameAxis(), anl.verdi.loaders.CSVCoordAxis.isCompatible(), and anl.verdi.loaders.NetCdfCoordAxis.isCompatible().
String anl.verdi.data.CoordAxis.getDescription ()
Gets the description of this CoordAxis.
Returns
the description of this CoordAxis.
Implemented in anl.verdi.loaders.SyntheticTimeAxis, anl.verdi.loaders.NetCdfCoordAxis, anl.verdi.data.AxisRange, and anl.verdi.loaders.CSVCoordAxis.
String anl.verdi.data.CoordAxis.getName ()
Gets the name of this CoordAxis.
Returns
the name of this CoordAxis.
Implemented in anl.verdi.loaders.SyntheticTimeAxis, anl.verdi.loaders.NetCdfCoordAxis, anl.verdi.data.AxisRange, and anl.verdi.loaders.CSVCoordAxis.
Range anl.verdi.data.CoordAxis.getRange ()
Gets the range of this axis.
Returns
the range of this axis.
Implemented in anl.verdi.loaders.SyntheticTimeAxis, anl.verdi.loaders.NetCdfCoordAxis, anl.verdi.data.AxisRange, and anl.verdi.loaders.CSVCoordAxis.
Referenced by anl.verdi.data.AxisRange.AxisRange(), anl.verdi.data.DataFrameAxis.DataFrameAxis(), anl.verdi.gui.DatasetListElement.DatasetListElement(), anl.verdi.gui.FormulaListElement.FormulaListElement(), anl.verdi.plot.gui.LayerChartPanel.init(), anl.verdi.plot.gui.TimeLayerPanel.init(), anl.verdi.plot.gui.TimeConstantAxisPanel.init(), anl.verdi.gui.LayerPanel.reset(), and anl.verdi.gui.TimePanel.reset().
Unit anl.verdi.data.CoordAxis.getUnits ()
Gets the unit of measurement for this coordinate axis.
Returns
the unit of measurement for this coordinate axis.
Implemented in anl.verdi.loaders.SyntheticTimeAxis, anl.verdi.loaders.NetCdfCoordAxis, anl.verdi.data.AxisRange, and anl.verdi.loaders.CSVCoordAxis.
double anl.verdi.data.CoordAxis.getValue (int index)
Gets the value at the specified index.
Parameters
index the index
Returns
the value at the specified index.
Implemented in anl.verdi.loaders.SyntheticTimeAxis, anl.verdi.data.AxisRange, anl.verdi.loaders.NetCdfCoordAxis, and anl.verdi.loaders.CSVCoordAxis.
boolean anl.verdi.data.CoordAxis.isCompatible (CoordAxis axis)
Gets whether or not the this axis is compatible with the specified axis. Two axes are compatible if they can be used together in the same formula.
Parameters
axis the axis to check for compatibility
Returns
true if this axis is compatibility with the other axis, Otherwise false.
Implemented in anl.verdi.loaders.SyntheticTimeAxis, anl.verdi.loaders.NetCdfCoordAxis, anl.verdi.loaders.CSVCoordAxis, and anl.verdi.data.AxisRange.
Referenced by anl.verdi.data.AxisRange.isCompatible().
The documentation for this interface was generated from the following file:
verdi_core/src/anl/verdi/data/CoordAxis.java